### PR TITLE
fix: remove async deprecation from `testLogin()` in HttpTest.kt

### LINKED ISSUE #7108: AsyncTask is deprecated
###### Reproduction Steps

1. bump targetSdk above 28 (I'm attempting 30 right now)
2. compile
3. 

###### Expected Result

Clean compile

###### Actual Result

Piles of deprecation warnings of course - because AsyncTask is deprecated and it's the entire way we do non-UI thread processing.

Replacing this is going to be a big deal.

### PR DESCRIPTION
**Pull request by oyeraghib**
## Purpose / Description
fix: removes the async deprecation from `testLogin()` in HttpTest.kt

## Fixes
Partially fixes #7108 

## How Has This Been Tested?
Unit test passed successfully

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by lukstbit — CHANGES_REQUESTED** [review]
I don't think these changes should be applied and this PR should be closed:

- my understanding is that the Connection class is deprecated and will be removed so it doesn't make sense to refactor it(besides fixing bugs) or its dependents(like tests)
- it's not ideal to have tests using coroutines when the code under tests is using AsyncTasks(both should be changed at the same time)
- the implementation has flaws:
    - runTest should be used instead of runBlocking(but this would require the coroutines-test artifact to be added to the androidTestImplementation configuration, which again doesn't make sense to do)
    - don't create manually a coroutine scope
    - the coroutines implementation doesn't call get() which doesn't replicate the original code(Connection.login() does create and start an AsyncTask in certain cases and the get() call would wait for that task to finish)

**Comment by mikehardy** [comment]
the most important part is that the class will go away I think, seconded

**Comment by oyeraghib** [comment]
@lukstbit @mikehardy Oh yeah Connection.kt is deprecated. Are we in the process of migrating it to more latest version, like has someone already started working on it? If not, I would like to pick it up. Any references/suggestions that could be used 
 while migrating the class would be helpful.
Should we use libraries like Retrofit ?

**Comment by mikehardy** [comment]
With new backend the connection will be managed inside the rust library we bundle from Anki desktop vía ankidroid rust backend project/library so this goes away totally

**Pull request closed without merging**
