### PR TITLE
Fix auto label and milestone to PR

### LINKED ISSUE #10410: Automate process of adding merged PR to milestone and removal of labels
Might be useful to automate this in the longer-term, either with a check to confirm that all merged PRs have a milestone, or a bot reminder to set a milestone once merged

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/10353#issuecomment-1044721187_

### PR DESCRIPTION
**Pull request by krmanik**
## Purpose / Description
_Describe the problem or feature and motivation_
fix `Resource not accessible by integration`

## Fixes
Fixes #10410

## Approach
It needs to be `pull_request_target` not `pull_request`.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
https://github.com/interledger/rafiki/pull/280/files

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Okay - this *should* work, and the typical reason you do not want to do this is because you might be running untrusted code in the main repo context, but there is no code checkout happening here and the pull_request_target run type was specifically added by github actions in order to handle this case

I've used it in other repositories to great effect. Let's see how it goes :-)

**Comment by mikehardy** [comment]
The CI Actions report they passed now, their output looks perfect, but I don't see the results I expect. So weird! Not sure what to do now, perhaps wait? I dunno.

**Comment by krmanik** [comment]
May be it is blocked by other actions?

**Comment by mikehardy** [comment]
No, you can check the actual action output, I did, it looks great. I'm really confused.

**Comment by krmanik** [comment]
Permission related is issues fixes. I am still searching for possible solution.

**Pull request merged**
