### PR TITLE
Editor Toolbar: Handle Night Mode

### PR DESCRIPTION
**Pull request by david-allison-1**
Related: #7124

Before:

image

After:

image

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
nice

**Comment by mikehardy** [comment]
Interesting - is there some aspect of the style in use that is not available until API24? Travis fails on API21/22/23

**Comment by david-allison-1** [comment]
<details><summary>Exception</summary>

```
com.ichi2.anki.FieldEditLineTest > testSaveRestore[test(AVD) - 5.0.2] FAILED 
	java.lang.UnsupportedOperationException: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f0400bf a=-1}
	at androidx.core.content.res.TypedArrayUtils.getNamedColorStateList(TypedArrayUtils.java:172)
[InstrumentationResultParser]: Ignoring repeated failed event for com.ichi2.anki.FieldEditLineTest#testSaveRestore. Stack: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.NoteEditor}: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f0400bf a=-1}
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 1: TypedValue{t=0x2/d=0x7f0400bf a=-1}
at androidx.core.content.res.TypedArrayUtils.getNamedColorStateList(TypedArrayUtils.java:172)
at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:765)
at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:719)
at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:682)
at androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:664)
at com.ichi2.anki.noteeditor.Toolbar.insertItem(Toolbar.java:168)
at com.ichi2.anki.NoteEditor.updateToolbar(NoteEditor.java:1888)
at com.ichi2.anki.NoteEditor.setNote(NoteEditor.java:1828)
at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.java:600)
at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:339)
at com.ichi2.anki.NoteEditor.onCreate(NoteEditor.java:408)
at android.app.Activity.performCreate(Activity.java:5937)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:711)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
... 10 more
```

</details>

Cause:

ic_add_toolbar_icon uses `colorControlNormal`
https://github.com/ankidroid/Anki-Android/blob/800640572b3f1d9a6c1eabf6e056cf4dd6b191d1/AnkiDroid/src/main/res/drawable/ic_add_toolbar_icon.xml#L6

When we passed `null` to the theme, this was not defined in lower APIs

**Comment by mikehardy** [comment]
Every time I consider taking out some of the APIs, they catch something in a weird middle-API slice or something :-)

**Comment by david-allison-1** [comment]
> Every time I consider taking out some of the APIs, they catch something in a weird middle-API slice or something :-)

The "add toolbar item" button wasn't supported on <API 21, hence the strange API slice. I'm just really glad that I added that test, turned out to be really high-value.

**Pull request merged**
