### PR TITLE
chore: add funding.json for FLOSS/fund

### PR DESCRIPTION
**Pull request by david-allison**
Initiative by Zerodha: potential funding from $10k-100k/year and a listing on https://dir.floss.fund/

**Announcement:**
https://floss.fund/blog/announcing-floss-fund/

**Manifest/schema:**
https://floss.fund/funding-manifest/

**Generated partially with**
https://vishnukvmd.github.io/funding.json/

⚠️ I am using the repo URL as ankidroid.org does not entice people to donate

I am not using the Play Store link as that did not pass the `.well-known` validation

* Part of Issue #17268

**Validated with:**
https://dir.floss.fund/validate

uri: https://github.com/ankidroid/Anki-Android/blob/main/funding.json

## Review Notes

See a sample: https://dir.floss.fund/view/funding/@ziglang.org

* ⚠️ This document proposes a 'end' goal of funding two part-time maintainers. This seems reasonable to me, but I haven't discussed it with the team
* I propose adding two 'commercial' tiers for funding at $100/mo and $200/mo as Zig is doing:
  * https://dir.floss.fund/view/funding/@ziglang.org
* I couldn't figure out how to add a custom donation
  * Maybe change to 123.45 USD 
* Open Collective links for the 'funding' may not be the right move

### CODE REVIEW

**Comment by mikehardy** [comment]
> ⚠️ I am using the repo URL as ankidroid.org does not entice people to donate

Huh - that could probably be changed, regardless of what we use - ankidroid.org should probably have a donate link

> ⚠️ This document proposes a 'end' goal of funding two part-time maintainers. This seems reasonable to me, but I haven't discussed it with the team

I don't see that proposal but also seems reasonable - I mean, we already basically do that but not funded well

> I propose adding two 'commercial' tiers for funding at $100/mo and $200/mo as Zig is doing:
https://dir.floss.fund/view/funding/@ziglang.org

Yeah for sure

> I couldn't figure out how to add a custom donation
> Maybe change to 123.45 USD

whatever works 😆 

> Open Collective links for the 'funding' may not be the right move

Why not? Because of the fees? I still think they provide value for money, personally

**Comment by david-allison** [comment]
AnkiDroid website: 

Redoing the website is number 2 on my priority list

----

2 maintainers: 

In the project description

----

Open Collective funding URLs

The dashboard is private, so the links are only for our benefit

**Comment by david-allison** [comment]
In order to get this approved: 

* (If agreed) I should add two more tiers on Open Collective and mirror them here

Is there anything else which is blocking?

**Review by mikehardy — APPROVED** [review]
still LGTM - thanks for taking the initiative

**Review by lukstbit — APPROVED** [review]
> ⚠️ This document proposes a 'end' goal of funding two part-time maintainers. This seems reasonable to me, but I haven't discussed it with the team

Sure!

> I propose adding two 'commercial' tiers for funding at $100/mo and $200/mo as Zig is doing:

Sure! I don't see why we wouldn't add these tiers just in case.

> I couldn't figure out how to add a custom donation

That field forces a numeric value so there's nothing to do. Instead of 123,45 I would still go with 10.

> Open Collective links for the 'funding' may not be the right move

As an alternative, we could provide the links to the transations, example for 2023 https://opencollective.com/ankidroid/transactions?period=2023-01-01T00%3A00%3A00.000Z%E2%86%922023-12-31T23%3A59%3A59.999Z%7EUTC . To be honest I don't see the value in these links if they are private or verbose(like the link I added above).

**Pull request merged**
