### PR TITLE
ContentProvider: Fix for wrong "IllegalArgumentException"

### PR DESCRIPTION
**Pull request by wlky**
Fix for the problem reported [here](https://github.com/ankidroid/Anki-Android/issues/3326#issuecomment-125635018)

@timrae this fixes the problem for me. Performance might suffer though for notes with huge amounts cards, since we'd now have to compare all cards of a note to find the one with the right ord.

### CODE REVIEW

**Comment by wlky** [comment]
@timrae any news on this?

**Comment by timrae** [comment]
Hey, sorry for the delay, I wanted to finish my changes to the content
provider before thinking about this, but it's kind of more work than I
estimated, and I've been really busy. I'll try get onto it this weekend

**Comment by wlky** [comment]
all right, no worries :) Thanks for the update.

**Comment by timrae** [comment]
Sorry for the delay, I've basically left your stuff untouched in #3630, but there are a few breaking changes there. I suggest outsourcing as much of the stuff dealing directly with the ContentProvider in your app to the API.

The ContentProvider may potentially (hopefully unlikely) be subject to breaking changes in the future, but the API will not.

**Comment by wlky** [comment]
sounds good. But the api itself doesn't contain methods to get any review/schedule information yet  (if I saw it correctly). Do you think those should be added?

**Comment by timrae** [comment]
Yeah I'm not too sure, but I think it could be a good idea if you want to
do that, basically it's up to you.
Compared to not adding the scheduling stuff to the api, it would probably
entail a bit of extra responsibility in terms of documentation, and make it
harder for you to change things...

**Comment by timrae** [comment]
@wlky
Is your app working with 2.5alpha57? I want to move to beta phase (feature freeze) pretty soon, so if you could give an ETA on any changes that you need, that would be appreciated!

**Comment by wlky** [comment]
@timrae yeah my app works without any changes. I just added the api dependancy to my app so I always have an up to date version of the FlashCardsContract.
I don't have any changes planned right now, I guess the next wave of changes will come with prod when more people start using the wear app.
Thanks for keeping me in the loop though!

**Comment by wlky** [comment]
@timrae ehm AnkiDroid Wear just got suspended from the Play Store :angry: ...
>REASON FOR SUSPENSION:Violation of the impersonation or deceptive behavior provisions of the Content Policy. Please refer to the [impersonation policy help article](https://play.google.com/about/developer-content-policy.html#impersonation) for more information.
If you are authorized to publish on behalf of the original content or brand owner, please contact us via the Google Play Help Center and attach verifiable and accepted proof of permission.

They do not name any specific reason for the suspension, but I guess using the Picture and name of AnkiDroid was the main reason.
As I see it, I have 2 options: 
1. Remove any reference to AnkiDroid, and call it sth. stupid like FlashcardWear
2. Try to convince Google I'm authorized to use the name and icon... I guess I would need your help for that though.

I guess it makes sense that google is trying to protect big apps like Anki from being impersonated, but still this is kind of annoying for me right now, so any help is welcome :P

**Comment by timrae** [comment]
@wlky OK I've just sent Google an email from the Developer Console stating that we have no objection to your use of the AnkiDroid name or logo, and asking to reinstate your app. Hopefully it will be resolved within a day.

**Comment by wlky** [comment]
@timrae thank you! I hope so too^^. 
I guess I'll wait two or three days and if nothing happens I'll go through the Help Center filing an official appeal.

**Comment by timrae** [comment]
@wlky
I've tried quite hard to reason with the Google Play rep, but it feels no different than talking to a robot. I suggest trying to change the app name to something like "AnkiWear for AnkiDroid", and see if their bots can handle that. 

When we contacted them they keep asking for "verifiable and approved proof of permission" but won't define what that means in the context of an open source project.

**Comment by wlky** [comment]
thx for the effort @timrae!
I also filed an appeal against the suspension, but since the automatic conformation email stating that I would get an response within "72 hours", I haven't received anything (It's been over two weeks).
Well I guess I will probably have to do something like what you suggested, I just really don't want my account to get suspended, which is apparently what happens when you get multiple apps suspended, so I'll probably get rid of the AnkiDroid in the title and the logo completely and only mention it in the description...

**Comment by timrae** [comment]
According to @nicolas-raoul, XXX for #INSERT_PRODUCT_NAME is the naming pattern that Google suggest, so I think AnkiWear for AnkiDroid is a safe bet, but AnkiWear might be ok as well, though it's not as obvious what it does as the former IMO.

As for the logo, from what I read that's the main reason why apps get rejected, so you should definitely remove any logo. The name may potentially have nothing to do with your rejection actually

**Pull request merged**
