### PR TITLE
Used """ instead of " to avoid \"

### LINKED ISSUE #11451: Use `"""` instead of `"` to avoid `\"`
One usual issue in reading code inside of code (e.g. string containing html, css, or js) is that they contains quote, which you must escape. Worst is when you want to have actual quote in the inside language. 
Kotlin offers one solution, triple quote. Let's take an example: https://github.com/ankidroid/Anki-Android/blob/8d4083e1ddbad8f0633679997a4b5b44ee88dc72/api/src/main/java/com/ichi2/anki/api/BasicModel.kt
```Kotlin
val AFMT = arrayOf("{{FrontSide}}\n\n<hr id=\"answer\">\n\n{{Back}}")
```
It would be nice to look for all \" in the code base and remove then when possible.
Simultaneously, you can add `@Language("HTML")` or any other relevant language, to ensure proper syntax coloring

So that would become
```Kotlin
@Language("HTML")
val AFMT = arrayOf("""{{FrontSide}}\n\n<hr id="answer">\n\n{{Back}}""")
```

It's cleanup, it's a matter of taste and not of absolute rules. If in some case you believe the result would be worse than the original, feel free to not make a change. As an example, we have some part in the code `"\""`, the string containing a single double-quote. You should probably leave it alone, because `"""""""` (7 double-quote), which is a valid template for the string containing a single double-quote, is far far less readable.
Each change should take less than a minute to make. If you do a PR by change, they should be merged almost immediately, so the risk of conflict and wasted work is low. You can just look below to see if someone did what you are about to do. This mean that you don't have to ask permission to work on it.

Once it is done, an extra task would be to consider adding a lint issue for escaped quote.

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
Used """ instead of " to avoid \" 

## Fixes
Fixes #11451 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
Your previous commits are here too, you should use rebase : )

**Comment by SanjaySargam** [comment]
> Your previous commits are here too, you should use rebase : )

Yes I am doing

**Comment by SanjaySargam** [comment]
> Your previous commits are here too, you should use rebase : )

@criticalAY what is the shortcut key to exit from git rebase. I forget

**Comment by criticalAY** [comment]
use cmd line to use git commands

**Pull request closed without merging**
