### PR TITLE
Remove the ability to translate from application

### LINKED ISSUE #7595: Translation with Glosbe.com not working
###### Reproduction Steps

1. Press add button
2. Type in a word
3. Select add
4. Press media button
5. Select advanced editor
6. Press translation button
7. Select Glosbe.com
8. Press translate button

###### Expected Result
Translates the word

###### Actual Result
Gives back error "Getting translation failed"

###### Debug info
AnkiDroid Version = 2.13.5

Android Version = 10

ACRA UUID = 4940c10c-177d-41da-83dd-c49c6b469afe

Scheduler = std

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

As discussed in #7595  this PR removes the option to translate from the application. 

When the feature was available:
before

After I removed the feature.
I removed the search  label because I think the pronunciation button is self explanatory. I also made the pronunciation button to take the entire width because in certain cases the "Clone from" button will disappear and the "Clear button" will fill the entire width of the screen(I think it looks better this was vs centering the button or making it half the screen and align to one side). 
after

## Fixes
Closes #7595 

## How Has This Been Tested?

Ran the usual tests.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
You should only need to remove the strings in `values`, our translation sync process will handle the rest ([Development Guide](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations))

That should massively reduce the code churn in this PR

**Comment by lukstbit** [comment]
> You should only need to remove the strings in values, our translation sync process will handle the rest ([Development Guide](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations))

Sorry I didn't knew that, I'll make changes only to the values folder. I will not push any changes until the cleanup for BasicTextFieldController(#11234) is merged because I'm going to have to solve some conflicts. Also if this PR is going to be merged the cleanup for TranslationActivity(#11118) will not be needed.

**Comment by lukstbit** [comment]
I rebased and fixed the conflicts. Ready for reviewing.

**Review by david-allison — APPROVED** [review]
LGTM

**Review by mikehardy — APPROVED** [review]
RIP translation :coffin: 
Thanks for this! Also I think it effectively translates some 400 lines of java to not-java (by deletion) as well as removing 400 or so of kotlin. I don't like losing a feature but maintaining 870 lines of code for a feature we know statistically is barely used and does not really work well, it's for the best
Cheers

**Pull request merged**
