### PR TITLE
Update Chrome Web Store scripts

### PR DESCRIPTION
**Pull request by agrueneberg**
Some improvements and fixes in the release script, plus window scaling support for the Chrome OS version of AnkiDroid. The update will hopefully also fix all the problems people started having recently (see #3814).

### CODE REVIEW

**Comment by mikehardy** [comment]
Hey @agrueneberg - if you're still listening on anything AnkiDroid related :-), I'm interested in documenting how to do chrome releases - can you confirm if this is roughly the process:

- develop chrome features (can use the newly released Chromebook emulator with it's device identification of "novato_cheets")
- Either use apk_to_crx from here https://console.cloud.google.com/storage/browser/arc-sdk?pli=1 on a release build or use arc welder to save a zip out of a debug build
- Upload it how? Using the API (https://developer.chrome.com/webstore/using_webstore_api) by some scripts (like https://gist.github.com/adrienjoly/5c7e3573f182eccc590fd0b65628e857 ) or did you push releases manually using some developer console?

Any advice appreciated - thanks

**Comment by agrueneberg** [comment]
Hi Mike,

thanks for looking into this, and sorry for not doing a good job documenting the process.

I used to create the .crx file using the script in `tools/chromeos/release.sh` with the most recent stable version of apk_to_crx (the ARC Welder app didn't support translations of metadata such as app title and description) and manually upload it to the Chrome Web Store (if I remember correctly, all managers of the AnkiDroid group on Google Groups are allowed to manage releases).

Notice that I used the past tense; almost all Chromebooks have access to the Play Store these days (https://www.chromium.org/chromium-os/chrome-os-systems-supporting-android-apps) and no separate release is required anymore. I don't see any reason why Google would continue supporting Android apps on the Chrome Web Store once all devices have access to the Play Store, so I expect them to remove this feature at some point similarly to how they removed Chrome Apps recently (https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html). Another reason why the app on the Chrome Web Store is not up to date (and is badly rated) is because the update experience was (is?) quite buggy and sometimes the app could not be opened anymore after an ARC update and had to be reinstalled, which meant that users would lose their decks unless they used sync (Chome Web Store apps used an app-specific filesystem that was removed on uninstall). I was considering to remove the app, but it would hurt users that don't have access to the Play Store yet. So I thought maybe keeping it at a relatively stable version is a good compromise.

I'm using the Play Store version on my Chromebook on a regular basis and the experience is quite smooth except for imports and exports. A file picker would be the best option here.

Let me know if you have any other questions,
Alex

**Comment by mikehardy** [comment]
Hey, thanks for replying. I was thinking the same thing on the filepicker for import/export - and maybe ingesting into mainline https://github.com/vi/AnkiImporter so CSV via Sheets->Drive->Anki would work. Regardless - I see what you're saying about the Android App via ARC versus via regular Play Store, but unfortunately on the emulator (my only access to a Chromebook) they don't have the Play Store working so I can't verify it unless you know of a trick to get Play Store working on the emulator?

As for the release - that makes sense, I think I understand the script wrapped around apk-to-crx and I get the motivation. I have no idea to upload to the store though. I'm a manager of the mailing list but I'm unaware of what links to follow at all in order to upload a new release to the Chrome App Store. Any illumination there would be really welcome!

**Comment by agrueneberg** [comment]
Mike, you can reach the Developer Dashboard of the Chrome Web Store at https://chrome.google.com/webstore/developer/dashboard. The Google Group authorized to manage the app is actually called "AnkiDroid Web Store Publishing" and only Nicholas and me are members right now. If the others are OK with it I will add you to the group. To update the app, find the listing and click "Edit" -> "Upload Updated Package" -> "Publish Changes".

**Comment by timrae** [comment]
Sure, fine with me. I think there are more efficient ways to spend your time tbh but I'm not gonna stop you 😅

**Comment by mikehardy** [comment]
Thanks, and I agree it's not a huge priority. But if it already works and the infrastructure exists (2 yeses) it makes me happy 😁. I enjoyed learning about the platform either way, interesting implementation

**Comment by mikehardy** [comment]
Just looked into this again while waiting on something long-running. Publishing the updated version was trivial as your script still worked perfectly:

mike@isabela:~/work/AnkiDroid/Anki-Android/tools/chromeos (master) % ./release.sh /home/mike/work/AnkiDroid/releases/apk_to_crx-54.5021.629.0/apk_to_crx.py /home/mike/work/AnkiDroid/releases/AnkiDroid-2.8.4.apk

Nearly instantaneous and the publish was fast as well. I added some notes on the listing that we suggest Play Store for AnkiDroid going forward and that the ARC update process is potentially unstable, requiring an uninstall of all ARC-related apps prior to reinstall - out of our control.

In general it looks to me like ChromeOS support isn't actually a sub-class of Android support, specifically I made a PR to alter camera support to a hardware availability check vs ChromeOS check since some ChromeBooks have cameras. If we also alter .apkg import to a filepicker, there will be nothing ChromeOS specific going forward, other than this publish to Chrome Web Store which will also die eventually as the ecosystem moves, but will be easy to push versions to in the meantime thanks to this script.

Which is all to say, well done on the script, and ChromeOS will be supported without actually being a priority going forward - win win

**Pull request merged**
