### PR TITLE
Fix crash in Reviewer due to incorrect cast

### LINKED ISSUE #4451: Crash on Nougat in full screen mode with answer buttons hidden
AnkiDroid Version = 2.7beta1

Android Version = 7.0

ACRA UUID = 005d2c15-788a-4a61-90e8-5da77e4f8693

### PR DESCRIPTION
**Pull request by timrae**
Fixes #4451 

I have no idea why it was working before... The code assumes the parent of the flashcard layout is a relative layout, but it looks like I accidentally "optimized" out the "unnecessary" RelativeLayout for the total fullscreen mode.

### CODE REVIEW

**Comment by hssm** [comment]
Is this the right branch?

**Comment by timrae** [comment]
Sorry, old habits die hard. We can cherry pick in either direction though right?

**Comment by hssm** [comment]
Yes, as long as we aren't delaying the next release. I don't mind if the change is included as long as it doesn't add another week+.

**Comment by timrae** [comment]
Yeah sorry my life has been quite crazy recently, and I haven't had much
time to stay on top of this release. I def want to include this fix, I'll
try put out a final beta this weekend, and a final release after a day or
two of testing.

On 14 Oct. 2016 11:08, "Houssam Salem" <notifications@github.com> wrote:

Yes, as long as we aren't delaying the next release. I don't mind if the
change is included as long as it doesn't add another week+.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ankidroid/Anki-Android/pull/4452#issuecomment-253691697>,
or mute the thread

**Pull request merged**
