### PR TITLE
NF: Replace `when` by whenever

### PR DESCRIPTION
**Pull request by Arthur-Milchior**

### CODE REVIEW

**Comment by david-allison** [comment]
```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveFileTest.kt: (248, 69): Unresolved reference: whenever
```

**Review by david-allison — APPROVED** [review]
Awesome!

**Review by mikehardy — APPROVED** [review]
Took a conflict but I like the change, seems like an obvious improvement, any other reviewer should merge this thing assuming CI passes

**Comment by david-allison** [comment]
Good first issue: add a lint check for `when` to improve our Kotlin migration automation.

**Comment by Arthur-Milchior** [comment]
> Good first issue: add a lint check for `when` to improve our Kotlin migration automation.

I thought about it, but  MockedStatic don't have `whenever`; so it would require to first define it or ensure that the link occurs only on non static

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
