### PR TITLE
Change mic icon to audio in advanced editor of notes

### LINKED ISSUE #8711: [Bug] Confusing icons in "Advanced editor" for notes
###### Reproduction Steps

1. Click on the floating action button (+)
2. Add note
3. Click on attach button (📎) in Front or Back
4. Select Advanced editor 
5. Notice the icons in the title bar.

###### Expected Result
There are two mic icons, the first one for Audio recording and the second one for Audio Clip.
The second icon should be something different because it's so confusing.

###### Actual Result
The two icons are the same.

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Additional Information
If you approved the issue, I would like to work on it.

### PR DESCRIPTION
**Pull request by Abanoub-Asaad**
## Purpose / Description
In advanced editor of notes, there are two mic icons, the first one for Audio recording and the second one for Audio Clip.
The second icon should be something different because it's so confusing.

## Fixes
Fixes #8711

## Approach
By changing the mic icon to the audio icon.

## How Has This Been Tested?
Tested by [Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&utm_source=www.apk4fun.com).

## Screenshots

<div align="center">
<pre>
   
       
     
</pre>
</div>

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Looks good!

* Can you use a svg instead of a .png
* Can you provide attribution, either by a license in the file, or a link to the license in the resources folder

**Comment by Abanoub-Asaad** [comment]
- I've changed the png to SVG, but I've changed the icon to be without a frame because it's more suitable and the dimensions are better than before.
- Also, I've added the license of the SVG and it's from an open source library which is "Remix Icon".

## Screenshots of the current audio SVG

<div align="center">
<pre>
   
     
     
</pre>
</div>

**Comment by mikehardy** [comment]
I like this but - is that really your SVG drawing or did you get it from somewhere? I'm suspicious of the copyright header

**Comment by Abanoub-Asaad** [comment]
> I like this but - is that really your SVG drawing or did you get it from somewhere? I'm suspicious of the copyright header (seems it should be copyright Remixicon...)

I got it from Remix icon and their license is [here](https://github.com/Remix-Design/remixicon/blob/master/License).

**Comment by Abanoub-Asaad** [comment]
Oooh, I should add their name here
` Copyright [yyyy] [name of copyright owner]`

But I wrote my name in the copyright owner
I'm fixing it now.

**Comment by Abanoub-Asaad** [comment]
What about now?
@mikehardy

**Review by mikehardy — APPROVED** [review]
Looks like a thing of beauty to me now :-) - thanks!

**Comment by mikehardy** [comment]
David's comments were all addressed with the SVG and license addition, this is good to go

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!

**Pull request merged**
