### PR TITLE
NF: Copyright remove javadoc in favor of c like comment

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This seems to be what is advised as far as copyright goes in java.

Furthermore, I can't ignore this kind of warning for copyright only, so need to either ignore relevant warning, or
correct copyright

### CODE REVIEW

**Review by david-allison-1 — COMMENTED** [review]
This one needs discussion for standardisation.

**Comment by Arthur-Milchior** [comment]
I agree. That's also why I left it separated from the other PR about dangling javadoc.

**Comment by mikehardy** [comment]
It's just diff noise to me. It does generate a warning. If this gets rid of the warning okay
I just copy-paste the template each time anyway

**Comment by Arthur-Milchior** [comment]
Actually, the auto-correction done by IntelliJ does not even remove the warning. So I'll close this PR.
I'll ignore this warning at project level. This will have the side effect to not show a warning for any other javadoc which occurs where it should not occur, but, unless IntelliJ follow my feature-request to make this a separate warning, that's a price I guess that should be paid if I want to remove all warnings

**Pull request closed without merging**
