### PR TITLE
Updated strings from Crowdin 20211110

### PR DESCRIPTION
**Pull request by mikehardy**
Standard I18N Sync

### CODE REVIEW

**Comment by david-allison-1** [comment]
```
> Task :AnkiDroid:compilePlayReleaseKotlin
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/AnkiCardContextMenu.kt: (20, 1): Class 'AnkiCardContextMenu' is not abstract and does not implement abstract base class member protected abstract val defaultEnabledStatus: Boolean defined in com.ichi2.anki.contextmenu.SystemContextMenu
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/AnkiCardContextMenu.kt: (21, 5): 'getActivityName' overrides nothing
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/AnkiCardContextMenu.kt: (25, 5): 'getDefaultEnabledStatus' overrides nothing
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/AnkiCardContextMenu.kt: (29, 5): 'getPreferenceKey' overrides nothing
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/CardBrowserContextMenu.kt: (20, 1): Class 'CardBrowserContextMenu' is not abstract and does not implement abstract base class member protected abstract val defaultEnabledStatus: Boolean defined in com.ichi2.anki.contextmenu.SystemContextMenu
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/CardBrowserContextMenu.kt: (21, 5): 'getActivityName' overrides nothing
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/CardBrowserContextMenu.kt: (25, 5): 'getDefaultEnabledStatus' overrides nothing
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/contextmenu/CardBrowserContextMenu.kt: (29, 5): 'getPreferenceKey' overrides nothing
```

Build is broken, I'll get it

**Comment by david-allison-1** [comment]
Fixed by #9867

**Comment by mikehardy** [comment]
I'm re-running the i18n sync which will force it to come from fresh master now that the fix is merged, then I'll close/re-open to re-run

**Comment by david-allison-1** [comment]
```
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-fa/02-strings.xml:140: This definition does not require arguments
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java:96: Error: Format string 'preview_progress_bar_text' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]
        assertThat("Progress text at the beginning.", t.getText(), is(previewer.getString(R.string.preview_progress_bar_text, 1, 6)));
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-fa/02-strings.xml:140: This definition does not require arguments
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java:106: Error: Format string 'preview_progress_bar_text' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]
        assertThat("Progress text at the beginning.", t.getText(), is(previewer.getString(R.string.preview_progress_bar_text, 1, 6)));
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-fa/02-strings.xml:140: This definition does not require arguments
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java:119: Error: Format string 'preview_progress_bar_text' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]
        assertThat("Progress text at the beginning.", t.getText(), is(previewer.getString(R.string.preview_progress_bar_text, 3, 6)));
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-fa/02-strings.xml:140: This definition does not require arguments
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java:132: Error: Format string 'preview_progress_bar_text' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]
        assertThat("Progress text at the beginning.", t.getText(), is(previewer.getString(R.string.preview_progress_bar_text, 2, 6)));
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-fa/02-strings.xml:140: This definition does not require arguments
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/PreviewerTest.java:135: Error: Format string 'preview_progress_bar_text' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]
        assertThat("Progress text at the beginning.", t.getText(), is(previewer.getString(R.string.preview_progress_bar_text, 1, 6)));
                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-fa/02-strings.xml:140: This definition does not require arguments
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:129: Error: Inconsistent number of arguments in formatting string preview_progress_bar_text; found both 2 here and 0 in values-fa/02-strings.xml [StringFormatCount]
    <string name="preview_progress_bar_text" comment="What card we are on out of how many in card previewer progress bar">%1$d of %2$d</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-fa/02-strings.xml:140: Conflicting number of arguments (0) here
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:312: Error: Inconsistent number of arguments in formatting string invalid_json_data; found both 1 here and 0 in values-fa/02-strings.xml [StringFormatCount]
    <string name="invalid_json_data">Card provided invalid data. %s</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-fa/02-strings.xml:304: Conflicting number of arguments (0) here
9 errors, 0 warnings
```

**Comment by david-allison-1** [comment]
02-strings: `preview_progress_bar_text`

**Comment by mikehardy** [comment]
Yes okay with all remove, I had to do that once, it made me sad but after a sampling strategy showed like 3 out of 5 erroneous when I checked, I just cleared them all

**Comment by david-allison-1** [comment]
Done. Running i18n and prodding CI

**Review by david-allison-1 — APPROVED** [review]

**Pull request merged**
