### PR TITLE
Renamed files extension to .kt extension in string xmls

### PR DESCRIPTION
**Pull request by n1snt**
## Purpose / Description
MyAccount.java, Reviewer.java & Deckpicker.java were migrated to kotlin but comments in resource files still used the old java extension.

## Fixes
Renamed all the instances of MyAccount.java, Reviewer.java & Deckpicker.java in comments in resource files.

## Checklist

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented on your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [  ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [  ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by Akshay0701 — APPROVED** [review]
Nice Catch, Thanks @n1snt

**Comment by Akshay0701** [comment]
pr name could be: renamed files extension to .kt extension in string xmls

**Comment by n1snt** [comment]
Done 👍

**Review by mikehardy — CHANGES_REQUESTED** [review]
Oh my! - the only changes should be in directory `values/` all the language-specific ones are generated by a script processing an export from our translation platform so should never be subject of PRs - https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations

I think that reduces this to just a couple of files / couple of lines not 279...

**Review by mikehardy — APPROVED** [review]
clean!

**Pull request merged**
