### PR TITLE
Use Theme in Statistics

### PR DESCRIPTION
**Pull request by jvanprehn**
Using Theme in Statistics fixes
https://github.com/ankidroid/Anki-Android/issues/3622

### CODE REVIEW

**Comment by hssm** [comment]
Thank you so much for doing this! It's looking good.

**Comment by timrae** [comment]
Yeah it looks really nice! 

The only problem is that when using the black theme, the unseen cards are shown as black on black in the pie chart. Maybe change to grey?

Also, when you first open the stats, it flashes white for a second. I'm pretty sure you can fix that by changing the background to transparent like we do in the Reviewer.

**Comment by jvanprehn** [comment]
I fixed it here: https://github.com/jvanprehn/Anki-Android
But I screwed up the history trying to do rebase.
I get merge conflicts in the rebase. If I resolve them manually, it doesn't squash into a single commit but into as many commits as the number of merge conflicts I resolve.
If you have a quick solution, let me know. If not I will use the same workaround as before. But I would prefer to know the proper way to do this instead of using the workaround all the time.

**Comment by timrae** [comment]
What git commands did you try?

**Comment by jvanprehn** [comment]
I committed my changes first.
Then I updated and got a conflict.
I merged it and then I commmitted again.
So I had 2 commits.

I wanted to squash them so I did:
git rebase -i develop~2
Then changed pick on the second line to squash

Then I had to resolve the merge conflict again and I still got two commits. It seems that it only squashes the commits until the merge conflict into one commit etc.

After that I googled and found and tried this:
# Reset the current branch to the commit just before the last 12:
git reset --hard HEAD~2

# HEAD@{1} is where the branch was just before the previous command.
# This command sets the state of the index to be as it would just
# after a merge from that commit:
git merge --squash HEAD@{1}

# Commit those squashed changes.  The commit message will be helpfully
# prepopulated with the commit messages of all the squashed commits:
git commit

After the git merge -squash HEAD@{1} command it says unknown switch 'c'.

I updated because the git reset --hard HEAD~2 screwed things up.

Then I tried git rebase -i -p HEAD~6 (now I had 6 commits if I remember correctly). But that one says that I have to provide the -m switch but I wouldn't know what to provide as an argument.

**Comment by timrae** [comment]
OK I see. First of all, you should always create a new 'feature' branch based on the latest version of 'develop' when you work on a new task. Don't modify your local develop branch directly. To fix that and get back to a usual workflow, let's do the following:

```
# create a new branch based off of your original commit
git checkout 4a55b97 -b stats-fix-white-flash
# fix your local devlop branch
git branch -d develop
git checkout upstream/develop -b develop
git checkout stats-fix-white-flash
```

Now that we're back to the usual workflow, you'd usually do the following

```
# next three commands are unnecessary in this case since we just pulled from upstream
# bring local develop branch up to date with upstream
git checkout develop
git pull upstream develop
git checkout stats-fix-white-flash
# do rebase
git rebase develop
# push to origin
git push origin stats-fix-white-flash
```

Now if you go to the AnkiDroid repository, it should offer you to create a new pull request

**Comment by timrae** [comment]
I added a new section to the development wiki on the recommended git workflow, please check it out :)

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#git-workflow

**Comment by jvanprehn** [comment]
Thanks. It is clear and it works.

**Pull request merged**
