### PR TITLE
Don't show Full Sync From Server if user does not have AnkiWeb Account

### PR DESCRIPTION
**Pull request by mahisharma-cs**
## Purpose
I want to work upon this, the Database error for not show sync from server.

## Fixes
I just hide the option of FULL SYNC for unregistered users.

## Approach
This will affect simply hide the icon, and if icon not visible, then it is also not clickable,

## Checklist

- [*] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [*] You have a descriptive commit message with a short title (first line, max 50 chars).
- [*] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [*] You have commented your code, particularly in hard-to-understand areas
- [*] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Thanks!!!!

The idea isn't to hide the sync icon - instead, if there is database corruption, one of the requests is "Full Sync From Server", this doesn't make sense if the user does not have an AnkiWeb account.

Relevant code: https://github.com/ankidroid/Anki-Android/blob/e034b3851f1b7de0f5864d3c7f830e19de4e5d87/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java#L141-L142

**Comment by david-allison-1** [comment]
@mahisharma-cs are you still working on this? There's some changes required, but we should be able to get this in

**Comment by mahisharma-cs** [comment]
I am trying but it takes too longer than expected. So, I thnik at this time I am able to make just to hide the icon. I actually want to work upon this issue. @david-allison-1 as you want to remove assignee from me than you may. Whenever I complete this part, I just ping here.

**Comment by david-allison-1** [comment]
> I am trying but it takes too longer than expected. So, I thnik at this time I am able to make just to hide the icon. I actually want to work upon this issue. @david-allison-1 as you want to remove assignee from me than you may. Whenever I complete this part, I just ping here.

I've pointed you in the right direction in my comment above, happy to help more if you need it, but removing the icon isn't the correct approach

**Pull request closed without merging**
