### PR TITLE
[Need Feedback/Help] Draft Fix for Study Shortcut Bug

### LINKED ISSUE #10840: [Bug] Crash: Tapping "Study" shortcut ends up closing AnkiDroid immediately without any explanation if the last-selected deck doesn't have any "due" cards
Thank you always, developers.

###### Reproduction Steps

1. On `Decks` screen, tap a deck which doesn't have any "due" cards* at the moment
*it includes the case that the deck is emptyimage
image

2. Press Back button (twice if necessary), or close AnkiDroid completely. Anyway, go back to Android Home screen 
image
3. Long tap (press) AnkiDroid app icon
4. Tap `Study` on the shortcut menu
image

###### Expected Result
AnkiDroid shows some message which explains the last-selected deck doesn't have any due cards at the moment (or is empty).
image
image

###### Actual Result
AnkiDroid "crashes". I mean, it closes immediately and unexpectedly without any explanation.
image

https://user-images.githubusercontent.com/10436072/163364495-e5c91b4e-0635-418b-9df1-6e50e979fd51.mp4

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release 
  (2.16alpha58)

### LINKED ISSUE #10841: [Bug] Crash: Studying all "due" cards started from "Study" shortcut ends up closing AnkiDroid without returning to Decks screen with "Congraturations!" snackbar
###### Reproduction Steps

1. On Decks screen, tap a deck which has one or more "due" cards
image
 (Then, Study screen gets shown)
image
2. Go back to Android Home screen
 (ex. press Back button twice [or more if necessary] )
3. Long tap (press) AnkiDroid app icon
4. Tap `Study` on the shortcut menu.
image
 (Then, Study screen gets shown again)
image
5. Answer all "due" cards in the deck.
image

###### Expected Result
Decks screen with `Congratulation! You have finished for now.` snackbar gets shown.
image

###### Actual Result
AnkiDroid "crashes". I mean, it closes unexpectedly without any explanation.
image

https://user-images.githubusercontent.com/10436072/163378134-a9eb0498-900a-41a8-bbfc-e060ab6e18b7.mp4

###### Debug info
```
AnkiDroid Version = 2.16alpha56

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36

ACRA UUID = 69410480-0b9c-401f-ae8d-94da0f29c9dc

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release 
  (2.16alpha58)

### PR DESCRIPTION
**Pull request by raymondwzeng**
## Purpose / Description
This PR was intended to fix a pair of bugs that occur as a result of the current app behavior associated with the "Study" shortcut. 

I took a swing for about a day or so, and have _a_ solution, but unfortunately, it introduces a bug of its own. So I'm leaving it as a draft to solicit feedback or advice from others for now.

## Fixes
This PR fixes #10840 and fixes #10841.

## Approach
I decided to switch the shortcut to open DeckPicker rather than the Reviewer, and then have the DeckPicker launch a review using the selected deck.

## How Has This Been Tested?

This was manually tested on my OnePlus 8T, running Android 11.

The suite of DeckPicker tests was also run to ensure no regressions were introduced.
image

https://user-images.githubusercontent.com/13594022/163695272-eb16b23b-7622-4cfb-944f-e8ebf1a19d81.mp4

https://user-images.githubusercontent.com/13594022/163695276-fc494435-c92b-43fe-9619-63796bb7e734.mp4

## Learning + Current Issue
Navigation is a strange beast and a part of the Android API that I don't have much experience in. Following @BrayanDSO's advice, I tried to find some way to manually push an Activity onto the backstack, but a search didn't seem to pull up anything worthwhile (though that may still be the better approach, let me know!)

My current workaround is to open DeckPicker first, then navigate to Reviewer. However, my approach introduces a new issue, in that on decks with no cards, it will still return the "Congrats!" snack bar despite not having studied anything.

An attempt was made to utilize _handleDeckSelection()_ to show the appropriate snackbar without launching to the reviewer, but this caused a NPE as the collection list/tree is not initialized. I tried to use _\_\_renderPage()_ to populate the structure, but I was unsuccessful in handling this. Any advice on this front (or if a better approach can be implemented) would be appreciated.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
(untested, not thought through thoroughly): 

Have you tried `android:parentActivityName` in the Manifest?

**Comment by BrayanDSO** [comment]
I haven't thought through it thoroughly as well

https://developer.android.com/reference/android/app/TaskStackBuilder may help

A detail I noticed is that if it is a warm boot, i.e. reopening an app in the background, we probably don't want to add another activity before the reviewer, just put it on the backstack top or do nothing if it is already on the backstack top. 

This logic may apply to the other shortcuts (Add Note, Card Browser). I noticed this after tapping the "Add Note" shortcut while I was reviewing a card, then the app closed after I added the card

If it is a cold boot, adding the DeckPicker activity to the backstack is useful

**Comment by sauravrao637** [comment]
Hey, 
would you like to provide the apk built after the changes.I think it might help someone understand the issue better.
Also if u can describe briefly what's happening in each video or maybe just title or something?

**Comment by raymondwzeng** [comment]
Thanks for the suggestions! I've made a new static method that adds the DeckPicker underneath activities launched through the shortcuts. 

Just need to figure out how to trigger the snackbar when the Reviewer pops from the stack. From logs, it seems like the DeckPicker fires its _onResume()_ even before the _onStop()_ of the Reviewer. Attempting to set DeckPicker's flag to [single top](https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_SINGLE_TOP), oddly enough, didn't trigger the _onNewIntent()_ override as I imagine it should have, which is what I think I would have needed as if [this part of the documentation is true](https://developer.android.com/reference/android/app/Activity#onNewIntent(android.content.Intent)), then I can't get the updated intent from the activity if it is updated outside.

**Comment by BrayanDSO** [comment]
The snackBar is set on DeckPicker's `onActivityResult()`

https://github.com/ankidroid/Anki-Android/blob/26372394335babed3a388d44840caa455fde8949/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L686-L693

And DeckPicker launches the reviewer for a result here

https://github.com/ankidroid/Anki-Android/blob/26372394335babed3a388d44840caa455fde8949/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L2238-L2241

I guess you should launch only `DeckPicker` with the shortcut intent (the taskstack may not be necessary) and on its creation or any convenient place open the reviewer, which will probably trigger the correct snackbar

**Pull request closed without merging**
