### PR TITLE
Completed the partial Hindi translation of Anki Android

### PR DESCRIPTION
**Pull request by ayushsinha25**
The Hindi translation of the name of the application was partial so I have completed it.

### CODE REVIEW

**Review by david-allison-1 — COMMENTED** [review]
Thanks!

Does anyone know how this will affect SEO/UX on the app store? It's a slight worry, most of the titles contain "AnkiDroid", and this change may cause issues if people are searching for "AnkiDroid" and don't see a matching title.

**Review by david-allison-1 — COMMENTED** [review]
My two relevant google results for "should you translate your app title" leads to a slight "no":

> usually, you won’t translate your app title in order to strengthen your brand, but you can (and probably should) add a localized element right up there near the title to enhance engagement. 

https://www.storemaven.com/academy/use-localization-to-boost-cvr/

> Should you translate your app title? It depends.
> 
> One of the key ranking factors is your app title. Translating it can make it clear and easy to understand for users in a different market searching for your app.
> 
> However, sometimes it makes sense to keep your title in the same language. For instance, if branding is an important aspect of your app, keeping the title the same will allow for consistency across multiple markets.
> 
> If keeping the title the same, you can still translate the title description (or the small descriptor phrase beside the title). This is a good way to localize your title while maintaining the important brand that your company is known for.

https://iglobe.ca/your-guide-to-localizing-your-app-store-description/

**Comment by ayushsinha25** [comment]
OK I understand the concern. 
But some other languages in the list already have it translated completely. Should I change it back to "Ankidroid" in English and make a PR?

**Comment by mikehardy** [comment]
Interesting - the attempt, and the research, thanks
Seems like leaving the title alone, but translating the description is ideal, as described in the second link
Any PR that did that would be welcome
I'll close this one

**Pull request closed without merging**
