### PR TITLE
Fab debug

### PR DESCRIPTION
**Pull request by HuWeiyy**
## Purpose / Description
After Create deck is tapped, the FAB  on the screenshot attached, it shouldn't go that high. 
So I add some code in `DeckPickerFloatingActionMenu.kt`.When we click `create deck`, I will set `isFABOpen` to be `false` so that the FAB will not move that high. But if I only do that, after we move out from the “create deck interface”, the isFABOpen is false. Now if we click FAB, the FAB interface will not appear. So I add a new private value called `isCreateDeckOpen` .This value can help the FAB interface appears normally.

## Fixes
[Fixes _Link to the issues 11019._](https://github.com/ankidroid/Anki-Android/issues/11019)

### CODE REVIEW

**Comment by Akshay0701** [comment]
hello @HuWeiyy,

these things need to be done before requesting reviews from other contributors
-> fill pr template
-> proper pr title 
-> complete the implementation/bug fix
-> proper commit message

I am marking this pr as a draft, for now, lets us know we are done all above

**Comment by HuWeiyy** [comment]
### First Pull Request of  Issue#11019 

## Purpose / Description
After Create deck is tapped, the FAB on the screenshot attached, it shouldn't go that high.
83e1c6d566e2bef35a4a0a484f5bfbdf_164675300-0e9341d8-eb93-4209-9a4a-8630c69e2aa7

## Fixes
[Issues#11019](https://github.com/ankidroid/Anki-Android/issues/11019)

## Approach
So I add some code in `DeckPickerFloatingActionMenu.kt`.When we click create deck, I will set `isFABOpen` to be false so that the FAB will not move that high. But if I only do that, after we move out from the “create deck interface”, the `isFABOpen` is false. Now if we click FAB, the FAB interface will not appear. So I add a new private value called `isCreateDeckOpen` .This value can help the FAB interface appears normally.

## How Has This Been Tested?
I did the same operation again according to the operation steps provided in issue (first create a deck, and then open create deck again). The bug in issue did not reappear (see figure below).
2U~((RMGWW )0FEM7MOMFZY

**Comment by HuWeiyy** [comment]
I've just started working on it. Is my PR correct? Thank you for your help！

**Review by david-allison — CHANGES_REQUESTED** [review]
This doesn't seem like the right solution. It seems that any keyboard movement will move the FAB, it's the opening of the keyboard which triggers the issue, not the 'add deck' dialog.

Its position should be independent of the keyboard state, rather than trying to determine when the keyboard is open or not.

**Comment by winstoncooke** [comment]
> This doesn't seem like the right solution. It seems that any keyboard movement will move the FAB, it's the opening of the keyboard which triggers the issue, not the 'add deck' dialog.
> 
> Its position should be independent of the keyboard state, rather than trying to determine when the keyboard is open or not.

Agreed. I also want to point out that this is similar to #10854, so perhaps look to that for inspiration.

**Comment by mikehardy** [comment]
original issue no longer reproduces, strange but true

**Pull request closed without merging**
