### PR TITLE
crash fix due to null pointer exception

### LINKED ISSUE #12874: [Bug] alpha90 crashed when pressed deck options
###### Reproduction Steps

1. press and hold a deck
2. click deck options / open the deck click three dots and select deck options

###### Expected Result

deck options is opended

###### Actual Result

app crashed

###### Debug info
AnkiDroid Version = 2.16alpha90

Android Version = 12

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_x86_64 Build/SE1A.220630.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = e866436a-5059-4551-a16a-57081f7a81d5

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Pull Request template
crash fixing arising due to NPE

## Fixes
Fixes #12874

## Approach
placed ```?```  (a null pref was set at non null)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by lukstbit — CHANGES_REQUESTED** [review]
This doesn't fix the issue, it just covers it.
You introduced this crash in one of your [previous PR](https://github.com/ankidroid/Anki-Android/commit/7b86f76c7e0d7f803017b44322705c8004dbb936) that we/I missed. Do you see the issue in DeckOptionsActivity?

**Comment by criticalAY** [comment]
Scope function?

**Comment by criticalAY** [comment]
Found the issue and I take full responsibility for the blunder that I created and will correct it. Sorry for this

**Comment by criticalAY** [comment]
I am pushing the code but would like to know if the above changes needs to be reverted because it's just a safe call ?

**Comment by lukstbit** [comment]
Yes, the initial changes in this PR should be reverted.

**Comment by criticalAY** [comment]
> Yes, the initial changes in this PR should be reverted.

Done

**Review by lukstbit — APPROVED** [review]

**Pull request merged**
