### PR TITLE
Show more lines of edittext when editing in CardTemplateEditor

### PR DESCRIPTION
**Pull request by marcardar**
add adjustpan to CardTemplateEditor's windowSoftInputMode for more convenient editing (shows 2-3 times as many lines at once).

### CODE REVIEW

**Comment by timrae** [comment]
Could you make a screenshot please? I'm not familiar with adjustpan

**Comment by marcardar** [comment]
device-2016-04-26-154031
device-2016-04-26-154010
device-2016-04-26-153859

**Comment by marcardar** [comment]
The keyboard overlays the UI rather than squeezing the UI into a smaller space.

**Comment by timrae** [comment]
Ah right, are you still able to edit the back template properly? Did you mistakenly include two screenshots  of what it used to look like? I don't understand why there are three screenshots.

**Comment by marcardar** [comment]
One for each edittext being edited. Sorry, one of them the cursor was in the wrong blinking state :)

BTW what's the deal with the "font-familiy"?

**Comment by marcardar** [comment]
All of the screenshots are with the new code.

**Comment by timrae** [comment]
Ah right, that's cool.

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/issues?q=is%3Aissue+font-familiy+is%3Aclosed

**Comment by flerda** [comment]
I believe "font-familiy" is a typo in an old note type that has since been fixed, but if you created the note type with the client including the typo, it will still be there.

https://github.com/ankidroid/Anki-Android/commit/60c1c085d1cf01365dd11f8b4ac1a33915826d00

**Comment by marcardar** [comment]
Ah, yes, that would explain it. I installed the develop version of AnkiDroid on top of the release version (i.e. without deleting the AnkiDroid folder), so that explains where the typo came from.

**Pull request merged**
