### PR TITLE
delay search result snackbar when card deleted

### LINKED ISSUE #14298: [BUG]: Undo Delete Snackbar Doesn't Appear
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Open card browser
2. Search is:new(a snackbar appears here saying [number of cards] cards shown)
3. Select a card
4. Press Delete(a second snackbar should appear)

### Expected behaviour

Snackbar for deletion should appear.

### Actual behaviour

It doesn't unless the previous snackbar has disappeared.

### Debug info

```text
AnkiDroid Version = 2.16.3

Android Version = 11

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36

ACRA UUID = dce906d5-19f7-4514-a0e4-0071f4f7b489

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

In my opinion the snackbar should be replaced by a bin feature. I've raised this here #14227
But it seems Improbable unless anki desktop implements a similar feature.
But anyways, thanks to all the devs for their amazing work!

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Using the `Handler(Looper.getMainLooper())` to delay the snackbar and allow the undo snackbar to be visible 

## Fixes
Fixes #14298

## Approach
Delay the search result snackbar by 2 seconds and allow the undo snackbar to be shown to the user and then show the result snackbar

## How Has This Been Tested?
Tested on Google emulator

https://github.com/ankidroid/Anki-Android/assets/48384865/f03e07e0-2aee-42a6-b7c0-f097fb3e4d0b

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
@david-allison Review requested

**Comment by dae** [comment]
Suggest you fix the merge conflicts first.

**Comment by criticalAY** [comment]
> Suggest you fix the merge conflicts first.

It took conflict after the backend PR merge, but done, I would rebase it after review

**Comment by BrayanDSO** [comment]
Pinging the snackbar lord @oakkitten, which should have a good opinion here

**Comment by oakkitten** [comment]
I don't mind this solution.

However if we go this way I'd prefer that the solution code is isolated and a comment is added explaining what is happening here. As we shouldn't be using a snackbar for this in the first place, we should plan on removing this once we have a better way of showing the numbet of cards etc.

Also I suggest using coroutines instead of `Handler` (`delay()` + cancelling the job), although for a well-isolated hacky code it shouldn't really matter.

**Comment by criticalAY** [comment]
ok will extract the code for this

**Review by david-allison — CHANGES_REQUESTED** [review]
(I've checked the issue discussion, but may have missed a technical reason why my comment doesn't stand)

This feels like a bug in `showSnackbar` (a snackbar is not shown if there is currently a snackbar on the screen) and it should be fixed here.

As the app grows and becomes more snackbar-centric, there are hundreds of places where this bug could occur. 

This change adds more code & this would need to be duplicated in any other places where this occurs.

It would seem sensible to handle this logic (via a queue or otherwise) inside `showSnackbar`

**Comment by oakkitten** [comment]
It's my understanding that we show a snackbar on card deletion... but then immediately re-show a sticky snackbar with “n cards shown” as a part of updating the card list.

**Comment by criticalAY** [comment]
> 

yes we call the snackbars one after the other so that causes this issue

**Comment by criticalAY** [comment]
@david-allison the snackbar is shown but there is a overlap

**Comment by BrayanDSO** [comment]
I agree with David that the delay shouldn't be the definitive solutionhere, and in general I don't want to pursue temporary solutions in non vital issues. Either we should think in a different UX for the `X cards shown` message, or some way to show consecutive snackbar messages

**Comment by criticalAY** [comment]
Option 1 : let's move the search all option at the top below the search bar?
Option 2: tweak the snackbar code itself so that they don't overlap

**Comment by oakkitten** [comment]
I think a good solution would be to move “x cards shown” where it is when search input is empty, that is the toolbar, and instead of having “Search all decks” have user choose “All decks” in the “Deck” chip's bottom sheet. And, don't limit the search to the current deck in the first place, not sure why this is a thing. And before all of this is done, I'm down with this fix provided it's easy to spot and remove.

**Comment by criticalAY** [comment]
I did research about the search functionality so I'm also in favour of this so are we accepting this solution till then ? I'll leave a todo

**Comment by criticalAY** [comment]
@oakkitten

**Pull request closed without merging**
