### PR TITLE
set last selected deck Id in statistics

### LINKED ISSUE #8826: [Bug] 2.15.0Bata Statistics for another deck are displayed
###### Reproduction Steps

1. Select a deck from the deck list
2. Open the statistics screen

###### Expected Result

The deck name displayed on the statistics screen matches the deck that actually displays the statistics.

###### Actual Result
The deck name displayed on the statistics screen does not match the deck that actually displays the statistics.

https://user-images.githubusercontent.com/43168745/118224616-784c8a00-b4be-11eb-8f71-25090d0a7e67.mp4

###### Debug info
AnkiDroid Version = 2.15.0beta2

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 05b6416d-1bc6-4282-bd44-b8be120255f2

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Akshay0701**
Fixes #8826

### CODE REVIEW

**Comment by Akshay0701** [comment]
I made this pr and commented on other issues in a very hurry,

So I request, @mikunimaru and others to review this and try to test it, on your device.

**Review by mikehardy — COMMENTED** [review]
This one definitely needs testing it is not as obvious how it works. I will wait to hear from someone that has tested it (hopefully @mikunimaru :pray: )

**Comment by mikunimaru** [comment]
Thank you for the update.
#8826 has been fixed, but #8857 has not.

1. View statistics
2. Switch to the option of 0 new learning schedules
3. View statistics again

The bug is still reproducible with the above steps.

**Comment by mikehardy** [comment]
@mikunimaru Your testing here is so helpful, thank you :heart:

**Comment by mikunimaru** [comment]
This pull request works perfectly for #8826 and I think it's okay to merge it.

**Pull request merged**
