### PR TITLE
Split migrate user data

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
While trying to have a proper worker and/or foreground service, I realize one part of the complexity is simply that the class is extremely big while most of it are other classes.
So I moved them in other file this way I'll be able to see clearly which must be changed to create a worker

### CODE REVIEW

**Review by lukstbit — APPROVED** [review]
Reviewed each commit, changes LGTM.

Non blocking observation, but as the two methods in the last commit are only used in MigrateUserData I don't see the value of the change(unless you plan to use them from other places as well).

**Comment by Arthur-Milchior** [comment]
I'm fine removing the last commit. That class becames sufficiently simple to read that it would be acceptable

**Comment by BrayanDSO** [comment]
Has conflicts

**Review by mikehardy — APPROVED** [review]
I actually kind of like the Executor separate (that is: preserve last commit) but I do not feel strongly enough about it to get in the way of Arthur moving forward as fast as possible :laughing: 

With that though perhaps we can say this? There are conflicts so it requires a fixup + repush either way - Arthur - keep or drop the last commit as you personally desire, then this is good to go?

**Review by david-allison — CHANGES_REQUESTED** [review]
This introduces a large amount of risk from modifying previously tested code and shouldn't be necessary for a service. I've posted a skeleton for a 'service' in the Discord for further discussion

**Comment by mikehardy** [comment]
I guess from the perspective of reviewing knowing that the person proposing it will be (is) working with it intensely, and that it had tests, I'm curious why the risk is large? I suppose checking coverage on the covered code is the determiner for me as it is a concrete metric vs a feeling

They all appear to have really high coverage (chapeau, David) - https://app.codecov.io/gh/ankidroid/Anki-Android/pull/12651 as such I am not really concerned

So to me this was "implementor's choice" on Arthur's behalf now and I would still merge 🤷

**Comment by BrayanDSO** [comment]
Removed "Pending Merge" because this is a draft

**Pull request closed without merging**
