### PR TITLE
make "Add From Gallery" visible on Amazon Build Flavor

### LINKED ISSUE #9323: [Bug] "Add From Gallery" no longer visible on Amazon Build Flavor
Cause: 6d68424cd48ab0a702da949bd49a70eeb05f0dfd

Even though we can't use the camera, we can still use the gallery, which is contained in the "Add Image" screen

The "add image" permission is requested:

https://github.com/ankidroid/Anki-Android/blob/c84cf4b151cfe460fd820d4cdf90c5daec4f43e1/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1566-L1570

### PR DESCRIPTION
**Pull request by huenical**
## Purpose / Description
Fix a bug causing "Add From Gallery" option missing from the note editor on Amazon Build Flavor

## Fixes
Fixes #9323

## How Has This Been Tested?
This has been tested on an emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Review by mikehardy — COMMENTED** [review]
@huenical - fantastic! My only hesitation with this is that we do not have automation set up to check the different build flavors, or even the multimedia edit capabilities of the main build flavor. That means that we need to request manual verification of this or with as many users as we have we will *certainly* see a future issue related to it and need further repair.

Specifically, can you check these 5 (:weary: ) cases by going to edit a field and seeing what happens as you try to add an image

1- play build, fresh install, permission not requested yet
2- play build, no camera permission (camera permission denied...)
3- play build, camera permission granted
4- amazon build, fresh install (no permissions granted, even though there is no camera...)
5- amazon build, second time through when permissions should all be verified (really, should be no change from case 4)

**Comment by huenical** [comment]
1. showing a dialog asking for camera permission
2. toasting "Could not obtain camera permission ...", displaying only Gallery button
3. displaying both Gallery and Camera buttons
4. displaying only Gallery button, no dialog asking for permissions
5. displaying only Gallery button

**Comment by huenical** [comment]
Hi, the results are as follows:
1. showing a dialog asking for camera permission
2. toasting "Could not obtain camera permission ...", displaying only Gallery button
3. displaying both Gallery and Camera buttons
4. displaying only Gallery button, no dialog asking for permissions
5. displaying only Gallery button

**Comment by mikehardy** [comment]
Sounds perfect - thank you for confirming!

**Comment by mikehardy** [comment]
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in August 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for August 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!

**Pull request merged**
