### PR TITLE
Improve "Sync Conflict" UX

### LINKED ISSUE #8702: UX: Improve AnkiWeb Upload/Download Screen
Caught a portfolio piece with a great suggestion (Ctrl+F for `AnkiWeb Sync Dialogue (Before)`: https://www.hunternielsen.com/project/04096f2e/AnkiMobile

image

Our Dialog:

image

----

@Arthur-Milchior @mikehardy I'd like to move this to the 2.15 milestone, as it should be very simple to do, and very high impact. 

Pending on whether you agree that this would be a worthwhile change and the wording change makes sense to you

Author has provided their blessing:

image

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

The wording of "Sync Conflict" was ambiguous and caused our users issues

## Fixes
Fixes #8702

## Approach
Instead of using "Upload" or "Download", use "AnkiDroid"/"AnkiWeb"

This doesn't take into account custom sync servers, but it's a price worth paying

And have the call to action request what to keep

* Don't use "sync conflict" as it's techy
* Use small sentences to ensure attention

We change the suggested wording from the site from:
`your decks differ and can't be combined`
to
`your decks can't be combined`

We use a new title for the confirmation screen as we show the opposite on the follow-up:

`Which do you want to keep? AnkiDroid` ->`Overwrite Decks -> Confirm overwrite AnkiWeb`
## Screenshots

**before**

image

**after**

image
image
image

## How Has This Been Tested?

Tested on my Andorid 11

## Learning (optional, can help others)

Idea obtained from:

https://www.hunternielsen.com/project/04096f2e/AnkiMobile

Many thanks to Hunter Nielsen for permission

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
Main question: do we want the "the collection on the other side will be overwritten"?

**Comment by Arthur-Milchior** [comment]
It should be "collection" and not "deck"

Not sure how much "ankiweb" is known. People can never use it once the account is created. It’s virtually a sync from computer to smartphone or from one phone to another I assume, so I don’t know how helpful mentionning ankiweb is

**Comment by david-allison-1** [comment]
> Not sure how much "ankiweb" is known. People can never use it once the account is created. It’s virtually a sync from computer to smartphone or from one phone to another I assume, so I don’t know how helpful mentionning ankiweb is

Users log in to AnkiWeb, we want to give the impression that it exists as the location that you sync to. "AnkiWeb the service", not "AnkiWeb the website" 

> It should be "collection" and not "deck"

Unsure about this one. Posted on the main issue, but would a user know what a collection is? 

My thoughts:

* decks - acceptable to me, most user-friendly, but not technically correct (for example: stats are also wiped)
* data - IMO, the best, not too technical
* collection - acceptable, unknown if users will fully understand
* database - too technical

**Comment by mikehardy** [comment]
I can't recall the last time a user has actually used the word "collection". "Decks" is what users know. 

Only way I could think to do it is say "Overwrite all decks on ..."

I'm not sure about "Overwrite" really, that actually sounds tech-y to me. I think the second dialog loses just a little context from the first dialog though and for a user about to hit a very important button it makes sense to include all the necessary context as one complete statement, like:

"Replace all decks on AnkiDroid with decks from AnkiWeb?"
"Replace all decks on AnkiWeb with decks from AnkiDroid?"

:thinking: 

In general this is great though and I already checked to see it was string key replacement not string change (as it should be I think)

**Comment by mikehardy** [comment]
Arthur made a good point about collection being in use all over, whether users commonly use it or not. I accept that for consistency.

I don't feel super strong about "Replace" vs "Overwrite" but per Arthur's comment on the issue it seems "Replace" is already used in at least one spot.

This is already incrementally better than existing for sure, go for at least "collection" vs "decks", maybe swap "Replace" for overwrite (or don't, no big) and I'm cool with this

**Comment by david-allison-1** [comment]
I like "replace" and will go with "collection". 

@mikehardy @Arthur-Milchior any opinions on https://github.com/ankidroid/Anki-Android/pull/8703#issuecomment-826449675

**Comment by mikehardy** [comment]
@david-allison-1 

>     Do we want the "the collection on the other side will be overwritten"? Or is the prompt on the next page scary enough

prompt on next page seems adequate to me

>    Do we want to make more use of colors, especially with the "overwrite"/"AnkiDroid"/"AnkiMobile" buttons

Nah, for me

>    Do we want to move these strings to 01-core, they seem vital enough

Yes good thinking!

>    Do we want to include the icon on the next screens?

If it's easy, maintains the heightened state of alert with that exclamation

**Review by mikehardy — APPROVED** [review]
LGTM - @Arthur-Milchior had great backing data to defend use of collection vs decks in the text, will definitely defer until he has a chance

**Comment by david-allison-1** [comment]
I'll state for the record that I prefer '[all] decks' over 'collection' seeing this in action, but no matter what happens, the copy is massively improved. I'm not going to bikeshed

Thanks for the help improving this 👍

**Comment by david-allison-1** [comment]
EDIT: Forgot to hit 'save' updating the OP

**Comment by Arthur-Milchior** [comment]
> ## Review goals

> * Do we want the "the collection on the other side will be overwritten"? Or is the prompt on the next page scary enough

Not sure it's scary. That's really hard to guess. I suspect at some point we should really consider how to do real user testing here. But I guess on the short term we really want to note that the one not kept will be lost.

> * Do we want to make more use of colors, especially with the "overwrite"/"AnkiDroid"/"AnkiMobile" buttons

I clearly think that anything signaling a warning near "replace" would be nice. But I have no idea how to do it. But even looking at Material Design rules, I don't see anything about way to emphasize warning.

> * Do we want to move these strings to `01-core`, they seem vital enough

Yes

> * Do we want to include the icon on the next screens?

Which icon?

**Comment by david-allison-1** [comment]
> > * Do we want the "the collection on the other side will be overwritten"? Or is the prompt on the next page scary enough
> 
> Not sure it's scary. That's really hard to guess. I suspect at some point we should really consider how to do real user testing here. But I guess on the short term we really want to note that the one not kept will be lost.

Any action needed on this one? 


> > * Do we want to make more use of colors, especially with the "overwrite"/"AnkiDroid"/"AnkiMobile" buttons
> 
> I clearly think that anything signaling a warning near "replace" would be nice. But I have no idea how to do it. But even looking at Material Design rules, I don't see anything about way to emphasize warning.

I think the icon + double confirmation may be enough

> 
> > * Do we want to move these strings to `01-core`, they seem vital enough
> 
> Yes

Done 

> 
> > * Do we want to include the icon on the next screens?
> 
> Which icon?

Done: sync conflict icon https://github.com/ankidroid/Anki-Android/pull/8703/commits/dd0d047ed29a61d0989ef056eecb735ec3613aed

**Comment by mikehardy** [comment]
@Arthur-Milchior I think this is just pending confirmation this is okay from you or some concrete guidance:

>>>            Do we want the "the collection on the other side will be overwritten"? Or is the prompt on the next page scary enough

>>    Not sure it's scary. That's really hard to guess. I suspect at some point we should really consider how to do real user testing here. But I guess on the short term we really want to note that the one not kept will be lost.

> Any action needed on this one?

To me "replace" and the warning (and there's a backup...) are okay, but you may disagree...

**Comment by the-nilosch** [comment]
The long text dialogs always confuse me. And now again after this renaming. I change the types of my card almost daily, what leads to daily sync problems.

I find the two dialogs now very confusing. The names "Ankidroid" and "Ankiweb" are just too similar. The upload download naming was more clear, as the words make clear, what the action does.

Even more better might be, to have not two dialogs (select and confirm) but having one dialog:

Two big icons as buttons with arrow up / arrow down show the options, and when one is selected, you can press the confirm button below (which is highlighted). Beside would be a cancel alternative.

Even more smarter would then be an auto-selection if there are last-changed dates, that clearly show, that all local changes base on the current Anki-Web state.

And to be further honest: I also change the number of new cards daily. the work flow there is also not optimal, even it's always the same movements. Maybe further icons, may ease the use. 7 text options, that have to be read are quite overwhelming. Then rarely used options (as a bin for delete) can be made smaller, and in a grid like order.

I hope this feedback helps :)

**Comment by mikehardy** [comment]
Perhaps "Device" and "Web" for endpoint names. I get your point on naming

Up and Down are fraught, unfortunately they are muddy terms now (even my mom says "upload to my device") so directional arrows will work for you but will confuse others. Maybe something else :thinking:

**Comment by mikehardy** [comment]
Oh - @david-allison-1 this was from a play store review, @the-nilosch kindly came over here to offer some suggestions, share their thoughts

**Comment by david-allison-1** [comment]
I'd support a visual dialog, but I don't have the bandwidth right now.

I feel "device" is ambiguous and complex. Would "this device" work?

We definitely could do with better copy, and I'm open to suggestions

**Comment by mikehardy** [comment]
narrow response: this device is definitely better than device

**Pull request merged**
