### PR TITLE
Kotlin migration TagsDialogTest

### PR DESCRIPTION
**Pull request by Arnold2381**
Kotlin migration TagsDialogTest

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM - I see the otherwise dangerous !!'s matched with assertions prior

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Could you rebase this onto master to ensure that nullability changes in `TagsDialog.kt` won't break tests

**Comment by Arnold2381** [comment]
@david-allison-1 I did the rebase already.

**Review by david-allison-1 — APPROVED** [review]
Thanks!

**Comment by mikehardy** [comment]
Hi there! November OpenCollective Notice

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in November 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for November 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!

**Pull request merged**
