### PR TITLE
refactor: move Sound.kt out of libanki 

### PR DESCRIPTION
**Pull request by BrayanDSO**
The equivalent to `sound.py` at Anki Desktop is actually SoundKt.kt, so there is no reason to keep `Sound.kt` at libanki

Part of #14320

## How Has This Been Tested?

Hasn't. CI should suffice

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Just to note: I'll be rebuilding these in the next week as part of TTS work

Full support as long as we can merge it quickly

**Comment by BrayanDSO** [comment]
wdym by rebuilding here?

**Comment by david-allison** [comment]
https://github.com/david-allison/Anki-Android/commit/b71e9542a00b5b3aa979266ea56d4c9b43adb21b#diff-7cd4e14b716b1bcd35f3cb3318da36eb706289a8e79658266d1f37d4ff8df796 - pretty much a full rewrite

**Comment by BrayanDSO** [comment]
Nice. Your changes kind of remove the `Android` dependencies from `libanki` as well, so I'm going to close this and focus on something else

**Pull request closed without merging**
