### PR TITLE
Fix Crash on Previewing Existing Image

### LINKED ISSUE #5856: 2.10Alpha54: Crash when pressing "edit field" for img field
###### Reproduction Steps

1. Review a card with an image
2. Go to the edit card screen
3. Tap the paper clip icon (edit field) next to the img field

###### Expected Result

The edit field screen with the image is shown

###### Actual Result

(Soft) Crash. A report is being sent and AnkiDroid returns to the reviewer. 

I think I'll downgrade to alpha53 for now since I can't view/change images anymore from the edit card screen.

###### Debug info
AnkiDroid Version = 2.10alpha54

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [ x ] character to confirm the points below:*

[X  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Cause: #5849

Added additional UI components, which worked when testing on a new screen, but not when re-editing a field with an image (logic exercising this came before logic initialising the view).

## Fixes
Fixes #5856 

## Approach

Split UI initialisation and functional methods.

Fixed API errors which were previously hidden by: `@SuppressLint( {"UnsupportedChromeOsCameraSystemFeature", "NewApi"})`. Incorrectly assumed to scope the `NewApi` only to the camera functionality.

## How Has This Been Tested?

On my Android, no longer crashes

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
Happy to shoot for a Roboelectric regression test on this if it'll be easy work (haven't tried it directly yet).

**Comment by mikehardy** [comment]
robolectric is actually really easy for the database-related stuff now (you can see how I use it to abuse the card templates #5151 but for UI-related things it is not quite as easy. That said, not impossible either - I'm tempted to say easier than it seems even. For this one I'm not sure I see the value, but for fixintegrity and maybe pulling the fields JSON out via chunk-loading instead of getString, that would be where I'd play with it (generating a >2MB field and stuffing it into an ephemeral testing database, checking to make sure it fails and thus likely reproduces the second part of #5852, then altering it to do chunk-loading to see if it passes

**Comment by david-allison-1** [comment]
I've had a quick look and play around, I'm sure it's powerful, but it's frustrating as the main example on the front page of the website is deprecated.

**Comment by mikehardy** [comment]
easiest just to see it in action I think - https://github.com/ankidroid/Anki-Android/pull/5151/files#diff-933130223a83e5d9a88efa60a4906afd

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldControllerTest.java  1
- AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/activity/MultimediaEditFieldActivityTestBase.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5231473&bid=17150775)

**Comment by david-allison-1** [comment]
> These look great - do you think it's ready for merge? How was it using robolectric with the current test infrastructure? I find most of the time now is spent thinking _how_ to test vs dealing with the test setup itself (should always be the goal) so I'm happy with it but to date @adamwolf (for mathjax items) and I are the only users I think. And I'm not sure Adam actually used robolectric or if the mathjax was possible without even going there

Happy to merge, robolectric was easy for what I needed. I'll try and integrate it more into my next PRs, I don't feel I'm testing enough (partially due to libAnki compatibility, and partially keeping changes small, but that's not a good excuse going forwards).

**Comment by mikehardy** [comment]
2.10alpha55 is out with the fix, as soon as Google is done processing it and starts delivery...

**Comment by mikehardy** [comment]
released in 2.9.6beta4

**Pull request merged**
