### PR TITLE
[Bug] Color of 'Hide whiteboard' Icon in App Bar Not White

### LINKED ISSUE #15457: [Bug] The color of 'Hide whiteboard' icon in App bar is not white
###### Reproduction Steps

1. `Settings - Appearance - App bar buttons - Hide whiteboard - Always show` (default)
2. Open a deck
3. `Three dot icon - Enable whiteboard`
4. See `Hide whiteboard` icon in App bar

###### Expected Result
Its color is white, as the other icons.
image
(2.16.5)

###### Actual Result
Its color is not white.
image

###### (Optional) Anything else you want to share?
The issue is observed in 2.17alpha2, too.
image
(2.17alpha2)

###### Debug info
```
AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.143 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by ro4i7**
## Purpose / Description
The 'Hide whiteboard' icon in the app bar is displaying in a color other than white, contrary to the expected behavior where it should match the color of other icons. This issue persists across versions, including 2.17alpha2.

## Fixes
* Fixes #15457 

## Approach
This change addresses the problem by ensuring that the 'Hide whiteboard' icon in the app bar is consistently displayed in white color in light theme and palin theme, aligning with the expected behavior of matching other icons' colors.

 ###### Before this Bug UI

> Its color is black, unlike the other icons in light theme.  

> Its color is black, unlike the other icons in plain theme. 

 ###### After this Bug Solved UI

> Its color is white, like the other icons in light theme.  

> Its color is white, like the other icons in plain theme.  

> Its color is white, like the other icons in dark theme.  

> Its color is white, like the other icons in black theme.  

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Too many icons are affected

Screenshot 2024-03-11 at 18 07 13

**Comment by criticalAY** [comment]
Should be handled in the drawable via attributes and color scheme

**Review by david-allison — APPROVED** [review]

**Comment by criticalAY** [comment]
@ro4i7 I would be good if you could provide the screenshot of the icon in all themes

**Comment by BrayanDSO** [comment]
git blame points to 988033ad4fca697d83d78eff1334da38edd66b7c, so I bet that this makes the icon vanish from the controls page

**Comment by BrayanDSO** [comment]
Go to Settings → Controls and try to find the `Settings - Controls` while using the `Light` theme. The icon shouldn't be blank, but it is with your PR

**Pull request closed without merging**
