### PR TITLE
fix:#8236:Margin,Boldness and textSize added to card_item_browser tex…

### PR DESCRIPTION
**Pull request by haran2248**
…tView

## Pull Request template
#8236 
## Purpose / Description
_Describe the problem or feature and motivation_
The card browser is extremely Congested and it is very hard for the user to glance through the items during revision

## Fixes
Fixes _Link to the issues._
#8236 

## Approach
_How does this change address the problem?_
,adding margins and making the items bold will help the student memorize better,without any confusion
## How Has This Been Tested?

UI accessibilty tools using material design by google has been referred to 

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

https://material.io/design/usability/accessibility.html#writing
WhatsApp Image 2021-03-16 at 03 55 12

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Akshay0701** [comment]
it is really good and readable design for user , not if we have big sentences in questions or answers , it might not be best option to bold text ,let me know what others think ?

**Comment by Arthur-Milchior** [comment]
Thanks very much for taking time to run with accessibility tool. Thanks also for linking to material guideline, that explain clearly why it was not accessible. 

Adding margins is a clear win to me, and I'd happily approve that. I'm pretty pretty sure that some users will complain. That's probably unavoidable given the size, but I still fear it. In particular, I suspect people will regret that there is less informations on screen.

I'm less convinced about bold text. In particular because question can actually contains bold, italic, etc... So I'd assume it might be slightly confusing, why is the question shown in bold here and not in the card. But I can be convinced that you're right.

> help the student memorize better,

This part confuse me. This help cleaning card, exporting them, editing them... but I don't see how the browser will directly help learning.

**Comment by haran2248** [comment]
> Thanks very much for taking time to run with accessibility tool. Thanks also for linking to material guideline, that explain clearly why it was not accessible.
> 
> Adding margins is a clear win to me, and I'd happily approve that. I'm pretty pretty sure that some users will complain. That's probably unavoidable given the size, but I still fear it. In particular, I suspect people will regret that there is less informations on screen.
> 
> I'm less convinced about bold text. In particular because question can actually contains bold, italic, etc... So I'd assume it might be slightly confusing, why is the question shown in bold here and not in the card. But I can be convinced that you're right.
> 
> > help the student memorize better,
> 
> This part confuse me. This help cleaning card, exporting them, editing them... but I don't see how the browser will directly help learning.

What I thought initially was the bold text of the questions and answers will help the students understand what part of the activity is given importance to,It also creates a difference between the spinner drop down and the actual questions and answers.As to why it helps students memorize better is because since the text is bold,it indicates that it is of some importance,thus instead of scrolling thorugh it people take time to note/memorize it.But I can remove the bold part if it is not ok with you.

**Comment by haran2248** [comment]
> it is really good and readable design for user , but if we have big sentences in questions or answers , it might not be best option to bold text ,let me know what others think ?

That might be true,I can remove the textStyle if not required,Lets see what other reviewers think about it:)

**Comment by david-allison-1** [comment]
Hi, thanks!

Personally don't like the bolding of the text, but let's move this forward

* Can we get a before/after comparison
* Could a few lines overflow to the next, so we can see how word-wrap occurs?

**Comment by haran2248** [comment]
> Hi, thanks!
> 
> Personally don't like the bolding of the text, but let's move this forward
> 
> * Can we get a before/after comparison
> * Could a few lines overflow to the next, so we can see how word-wrap occurs?

WhatsApp Image 2021-03-17 at 23 36 46 (1)
WhatsApp Image 2021-03-17 at 23 36 46

**Comment by david-allison-1** [comment]
off-topic: you can improve how your card types appear in the browser: https://www.youtube.com/watch?v=JbxNP4pSIBA

**Comment by haran2248** [comment]
> off-topic: you can improve how your card types appear in the browser: https://www.youtube.com/watch?v=JbxNP4pSIBA

ohh thats great!Do you want me to make any changes in my PR?

**Comment by david-allison-1** [comment]
I'm really sorry, I don't like it visually. 

I'll leave other maintainers to discuss. I'd vote to close it, but I don't want to be a negative voice - if people disagree with me then I'm happy to be wrong, this is all qualitative.

---

From a technical/quantitative perspective:

* I don't like the inconsistent top/bottom padding values.
* You can also use styles to cut down on code duplication: https://developer.android.com/guide/topics/resources/style-resource

**Comment by mikehardy** [comment]
@Arthur-Milchior said:

> Thanks very much for taking time to run with accessibility tool. Thanks also for linking to material guideline, that explain clearly why it was not accessible.

I don't see any clear explanation of what exactly is inaccessible.
Specifically, for every change suggested in this PR to margin, padding, font etc, there should be a clear statement of:

- this exact thing is configured this exact way, the accessibility guideline for elements like that says it should be this specific range (link to guideline)

An example:

"the margin between rows is currently 2dp and accessibility guidelines say they should be minimum 4dp with no maximum specified (link to doc)", I propose setting them to 4dp"
"the divider between rows is currently low-contrast (include set of contrast values for each of our theme settings) while accessibility sets a minimum guideline of 2:1 for row dividers (link to doc), I propose these theme changes for row dividers which achieve exactly 2:1 ratio"

If the proposed changes are not *quantifiable* and *tied explicitly to a document* this will be nothing but pain.

Why? Users will complain, they'll want a toggle back to the old way etc etc, and we (who are not great designers) will have no defense and likely may not do a good job anyway. Our idea of "congested" is just opinion.

So to be clear - for me to be +1 on this - every single change must have explicit and measured backing + verification to a guideline we may reference.

Then we may stand up to any user complaints with a valid deference to established best practice

**Comment by mikehardy** [comment]
For the record: I love the idea of accessibility - what I do not love is the idea of changes I can't verify are *actually* meeting accessibility standards as they are generally agreed by experts

**Comment by haran2248** [comment]
> For the record: I love the idea of accessibility - what I do not love is the idea of changes I can't verify are _actually_ meeting accessibility standards as they are generally agreed by experts

Yes I understand,I will close this PR

**Pull request closed without merging**
