### PR TITLE
compile with up-to-date toolchain, bump to 1.1.0alpha6, fix #4857

### LINKED ISSUE #4857: Outdated API at jcenter.bintray.com have issues detecting duplicates. Please update with current version
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

Hello!,

I'm new on Android development. I'm trying to use the AnkiDroid API in a personal project based on the sample provided at:

https://github.com/ankidroid/apisample

The API is working fine except for the findDuplicateNotes function. I'm trying to detect all duplicates I have stored in a file but it is not detecting all the duplicates. In a list of 2000 cards, it finds approximately 1100 duplicates (the remaining 900 are not detected even if they are already in the deck).

I have been trying to debug my project (based on the sample) and debugging also the Anki-Android APP, and as far as I have been able to understand, the problem seems related to a hashcode calculation that was already solved in this commit:

https://github.com/ankidroid/Anki-Android/commit/269fd178e09e9c43a8f2066c63d65802c6f6c156

In fact, I have seen the source code of the latest version of the API that I'm referencing: 

https://jcenter.bintray.com/com/ichi2/anki/api/1.1.0alpha5/

And I see that the affected files are not updated... 

I think that publishing the current version of the API should solve the problem

¿Can you please update the published API? 

In case it is not possible, ¿Could you suggest any workaround to use the latest version of the API in my project or how to point to the git version in the gradle file? (I have been trying to build the current version of the API to a JAR in my machine and then reference it in my project, but by the moment I was unable to make it work... I think I need to understand better the dependencies and build system in order to do this.. :))

###### Expected Result

When searching a duplicated card the key "熊, くま" (for example) it should find 1 result in my deck (since I have already added this card)

###### Actual Result

The card is not detected as duplicated and I can add it over and over again

###### Debug info

AnkiDroid Version = Any (the problem is with the API)
AnkiDroid API Version = 1.1.0alpha5
Android Version = 7.0.0

- Key searched for duplicates: "熊, くま"
- Wrong hashcode obtained by the published 1.1.0alpha5 version of the API: 4081968894
- Right hashcode obtained by the latest version of the AP in github: 255123055 (which seems it should work)

### PR DESCRIPTION
**Pull request by mikehardy**
I moved the version, which is probably presumptuous but I wanted to generate a test version for Issue #4857 

Other than that, this is 100% javadoc fixups to compile cleanly with Java8's new fail-fast doclint

### CODE REVIEW

**Comment by timrae** [comment]
I've merged this as is, but in the future please separate unrelated changes into separate commits :)

**Comment by mikehardy** [comment]
Yeah I could tell it smelled while doing it, should have had a clean pull then the version bump as local only for the test release. Next time if there is one

**Comment by timrae** [comment]
Also I reverted the html5 flag you added because it wouldn't compile for me, and added a fix for the version number (I prefer to do this myself anyway)

**Comment by mikehardy** [comment]
> Also I reverted the html5 flag you added because it wouldn't compile for me, and added a fix for the version number (I prefer to do this myself anyway)

Huh. Turns out that's a java 10 thing. It *will* get us in the future. Instead of reverting, applying a version check works for me locally. 

    if(JavaVersion.current() >= JavaVersion.VERSION_1_10){
        options.addBooleanOption('html5', true)
    }

**Comment by timrae** [comment]
> Instead of reverting, applying a version check works for me locally.

Feel free to submit a PR for that or include it as a separate commit next time you make a PR or whatever

**Pull request merged**
