### PR TITLE
Fix crash on add picture from camera on Android 7

### LINKED ISSUE #4586: Crash on add picture from camera on Android 7
Seems like a similar permissions issue to the crash when emailing apkgs that I recently fixed

```
android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/img_201702162214361518016482.jpg exposed beyond app through ClipData.Item.getUri()
```

### PR DESCRIPTION
**Pull request by jkennethcarino**
Fixes #4586.

### CODE REVIEW

**Comment by timrae** [comment]
Thanks for the fix. Since we end up moving the file to the media dir anyway, maybe we should just be writing to internal storage (i.e. [getCacheDir()](https://developer.android.com/reference/android/content/Context.html#getCacheDir()). Then we can avoid specifying a path in the manifest. What do you think?

**Comment by jkennethcarino** [comment]
Yeah, that will be great. I'll push another commit, and let know if I missed anything.

**Comment by timrae** [comment]
Using the File provider shouldn't be necessary either.

**Comment by jkennethcarino** [comment]
Yes, we have access to that directory, but on Android Nougat and higher, `file://` scheme is not allowed to be attached with Intent (Camera Intent in our case). We're using [FileProvider#getUriForFile(Context, String, File)](https://developer.android.com/reference/android/support/v4/content/FileProvider.html#getUriForFile(android.content.Context,%20java.lang.String,%20java.io.File)) which returns a `content://` URI instead of [Uri.fromFile(File)](https://developer.android.com/reference/android/net/Uri.html#fromFile(java.io.File)) which returns a `file://` URI.

For reference: https://developer.android.com/about/versions/nougat/android-7.0-changes.html#perm
> Passing file:// URIs outside the package domain may leave the receiver with an unaccessible path. Therefore, attempts to pass a file:// URI trigger a FileUriExposedException. The recommended way to share the content of a private file is using the FileProvider.

**Comment by timrae** [comment]
Thanks a lot, I confirmed that fixes the crash. There appears to be a problem with the image scaling now (the image isn't scaled to fit within the screen by default). It's unlikely to be related to your patch, but it should be a fairly recent regression nonetheless. If you have any time and interest on submitting a patch for that as well, I'm sure it would help a lot of users who use this feature!

**Comment by jkennethcarino** [comment]
Sure! I'll try and look into it this next weekend if I can find some free time. Thank you!

**Comment by timrae** [comment]
It looks like there was already a bug report (#4673) for the issue I mentioned

**Pull request merged**
