### PR TITLE
NF: Remove warning about unchecked CardQueue

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This remove a warning that CardQueue was returned with UncheckedType... not clear how it improves anything in term of typing, but at least this remove the warning

### CODE REVIEW

**Comment by mikehardy** [comment]
Not sure on this one I'll have to research

**Comment by Arthur-Milchior** [comment]
Essentially, it means that we explicitly don't care about the generic parameter (as long as it satisfies the constraint above that it extends Card.Cache)
I guess the warning simply ask us to check whether we actually do not care. This is consistent with the returned type

**Comment by Arthur-Milchior** [comment]
@mikehardy any news on your research?

**Review by mikehardy — APPROVED** [review]
Ok, LGTM

**Pull request merged**
