### PR TITLE
make deck expander clickable

### PR DESCRIPTION
**Pull request by nobnago**

### CODE REVIEW

**Comment by hssm** [comment]
You will need to rebase this after the recent merges.

**Comment by jshevek** [comment]
It would be really great if all people working on UI code could be kept abreast of all of the other work that other people are doing and planning to do.  Perhaps a specific thread in the mailing list, or a separate wiki, or even an email thread or irc channel.

**Comment by eginhard** [comment]
How about a shared Google Doc? No overhead involved and real-time collaboration. Just click here and edit: https://docs.google.com/document/d/1SlybFOtfkp2qZeJ-orc69gLQBVLUMC18Cpfq29FhvmE/edit?usp=sharing

**Comment by timrae** [comment]
It's probably worth waiting for #774 and the surrounding discussion to be resolved before rebasing

**Comment by timrae** [comment]
Also as @hssm previously mentioned, I think a material design icon would look better, would be easier to click (thus letting us remove the context menu item) and would be more consistent since there may be some devices that don't render that symbol correctly.

**Comment by timrae** [comment]
I'll merge this for now; we can look at switching to icons later

**Comment by timrae** [comment]
By the way, the normal workflow in git is to create a new branch everytime you work on a PR, rather than putting your changes directly into develop. This will make it easier for you to setup PRs as github will automatically suggest for you to create a PR as soon as you push a new branch. It also makes keeping track of local vs remote branches easier

**Pull request merged**
