### PR TITLE
Porting exporting

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
dae/anki@a5b0852360b132c0d04094f5ca8f1933f64d7c7e

As explained in the commit, I can't find how to compress file in Zip, so it's only a partial port of anki's commit. However, it at least follows anki by factorizing this part of the code

## Purpose / Description
Main purpose: having libanki similar to Anki's folder Anki.

## Approach
As in Anki

## How Has This Been Tested?

gradlew.
In ankidroid, I selected a deck with a card with an image. I exported it.
I took the apkg file in the computer and imported it in anki. It worked perfectly, the image and cards were still here.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Only API 18 failed. And the first error i can understand seems to be unrelated to anki, but to connecting the device. So I'd like it restarted, please

**Comment by mikehardy** [comment]
I just spun through all your PRs on Travis and re-kicked the ones that seemed to have single-API failures.

**Comment by timrae** [comment]
I hope this is obvious, but for every commit you make to libanki, you need
to manually test the code paths you have changed by exercising the
appropriate feature in AnkiDroid and checking that the behaviour is as
expected.

Any pull request for which the testing section of the description just says
checking that the CI has passed will not be accepted. Please list in detail
(step by step) how have manually tested each pull request. This is
especially true since most of the AnkiDroid code base does not have unit
tests.

**Comment by Arthur-Milchior** [comment]
I do intend to do manual test once I know automated tests pass. Otherwise, I'll have to do the test again manually and loose quite some time.
Note that there are some pull requests which can't be tested. I'll mention it explicitly and explain why when it is the case. Free to you to accept or not the PR

**Comment by Arthur-Milchior** [comment]
If aI don't know how much codacy can be configured, but you may want to reconsider «The instance method name '_exportMedia' doesn't match '[a-z][a-zA-Z0-9]*'»
Because actually, to follow anki, we want to have _ starting names.

**Comment by mikehardy** [comment]
Yes we had a minor codacy mishap and there's some configuration missing at current, it is on my list as a priority along with fixing the travis ci flakiness which is in the same area (automated checks on PRs) - definitely going to get done and we'll use discretion in the meantime. I am actively watching things at least and trying to help push them through until I determine root causes

**Comment by Arthur-Milchior** [comment]
Test explained
Tabs removed

**Pull request merged**
