### PR TITLE
Added ic_remove_circle for 24dp and removed the others.

### PR DESCRIPTION
**Pull request by brunodea**
The icon for the folder drawable-hdpi was already correct and looks like that ic_remove_circle_grey600_36dp.png (hdpi) is the same as ic_remove_circle_grey600_24dp.png (xxhdpi), that's why git thinks I was just renaming/moving the file (I think).

### CODE REVIEW

**Comment by timrae** [comment]
For the `drawable-xhdpi` image github is saying "File renamed without changes". Are you sure you copied the correct size?

**Comment by brunodea** [comment]
I think I did (look my edit with my thoughts, but i'll check again just in case)
And I forgot to rebase, sorry!

**Comment by timrae** [comment]
OK, you also need to update `card_browser_item_my_searches_dialog.xml`

**Comment by brunodea** [comment]
Ah, I thought the Travis failed because I didn't rebase. Anyway, should work now.

And yeah, I actually copied the right file.

**Comment by timrae** [comment]
Thanks for the quick PR!

**Pull request merged**
