### PR TITLE
Material design add content menu. Remove ShowcaseView

### PR DESCRIPTION
**Pull request by timrae**
@hssm Please merge if you're happy with this.

We could probably do more to guide the user, but a) I think this is already pretty intuitive so it's not a priority for me and b) I think it would be nice to do that from within the DeckPicker rather than showing them a new activity they'll never see again. 

Oh I didn't check this on a tablet, I guess it's probably broken? I couldn't get my tablet emulator to start

untitled

### CODE REVIEW

**Comment by hssm** [comment]
Is it meant to pop up automatically on an empty collection? I thought that was what it would do.

Besides that, yes it works on a tablet.

**Comment by timrae** [comment]
Yeah I tried that, but the animation wasn't visible (at least on the emulator), and that made it look kind of stupid and pointless... We could do a hack like `postDelayed()` but do any other apps expand the FAB on startup?

**Comment by timrae** [comment]
aslo, I think it looks alright when the buttons expand dynamically, but I think it might look slightly too ugly for the very first screen showed to new users...?

**Comment by hssm** [comment]
I guess it really is kind of tacky now that I think about it. I've read about it being a possibility to introduce users to the button (much like the nav drawer on first load) but I've actually never seen it in practice.

my original comment about a giant blue "click me" button still stands, so there is no need to draw any more attention to it.

**Comment by timrae** [comment]
Which comment is that?

**Comment by hssm** [comment]
Point 2 in https://github.com/ankidroid/Anki-Android/pull/882#issuecomment-117169074

**Comment by timrae** [comment]
Ah yeah I kind of agree, although we do have a ton of white space in the layout that we can use

**Pull request merged**
