### PR TITLE
Travis config

### PR DESCRIPTION
**Pull request by hssm**
I'm going to use this PR to play around with the travis config and sort some things out.

### CODE REVIEW

**Comment by timrae** [comment]
Travis never closed the issue I opened about marshmallow not working

**Comment by hssm** [comment]
You mean the emulator? Do you have a link?

**Comment by hssm** [comment]
For now I'm going to leave the emulator on the old version since even locally we can't run the tests properly because of permissions. It's not that easy to set them up programmatically either.

**Comment by timrae** [comment]
Yeah emulator,  I'm not at the computer right now but will look for it later

**Comment by hssm** [comment]
All right the builds should be working fine now and I think we shave off about 2-3 minutes per build with the caching. The *tests* are currently failing though with the recent content provider changes.

**Comment by timrae** [comment]
Yeah I saw that, they were passing locally when I made the PR so I'll have
to look into that. Thanks for looking into the Travis config, it's been
getting pretty annoying.

**Comment by timrae** [comment]
Here's the link, actually it wasn't me that opened it.

https://github.com/travis-ci/travis-ci/issues/4763

**Pull request merged**
