### PR TITLE
chore: update to anki 24.06.2 and adopt SvelteKit

### LINKED ISSUE #16232: Prepare SvelteKit changes for Anki 24.06
~~Blocker for AnkiDroid 2.18 release~~

Some SvelteKit changes are necessary

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description

See https://github.com/ankidroid/Anki-Android-Backend/pull/381 for more details about changes in Anki and the backend

## Fixes
* Fixes #16232 
* Closes #16607

## Approach

On the commits

## How Has This Been Tested?

Emulator 34:

[csv.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/a0f40a40-9893-4e99-b9fc-103a8480f2e5)

[io.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/e2b1b2e7-3fe3-4468-b3d5-acae6a436482)

[stats_card_info.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/8c9b5872-9643-49ea-9a18-bebf81bf2527)

[Importer.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/91acac75-9ff5-42ef-93df-d277682a60d9)

## Learning (optional, can help others)

https://kit.svelte.dev/docs/routing

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Currently the importers can't import files with special chars in their names, although the page url is propertly encoded

Screenshot_20240521_214322

**Comment by dae** [comment]
The problem is probably that the path is lacking a leading /. The / character should also be escaped, so the leading one doesn't get stripped.

**Comment by BrayanDSO** [comment]
That worked. Thanks!

**Comment by voczi** [comment]
do things like audio files and images still work? just curious to see if ViewerResourceHandler is affected at all

**Comment by mikehardy** [comment]
> do things like audio files and images still work? just curious to see if ViewerResourceHandler is affected at all

I believe you can pull the PR and check it locally and report back - please report what you find

**Comment by mikehardy** [comment]
I did a `gh pr checkout 16449 && uum && ./gradlew installPlayDebug` (where `uum` is "update from upstream main" that rebases whatever PR I'm looking at to upstream/main...)

I logged into my test account and started review
While in reviewer on a card I attempted to use the 3-dot menu to look at "Deck Options" and I got an error page:

image

Logcat looked interesting, a route not found?

> 06-17 07:27:02.193 24508 24577 W PageWebViewClient: Not found backend/sveltekit/index.html


```
06-17 07:27:02.158 24508 24508 I AnkiDroidApp$onCreate: SingleFragmentActivity::onCreate
06-17 07:27:02.165 24508 24508 D TrafficStats: tagSocket(197) with statsTag=0xffffffff, statsUid=-1
06-17 07:27:02.177 24508 24508 I AnkiDroidApp$onCreate: SingleFragmentActivity::onStart
06-17 07:27:02.178 24508 24508 I FragmentLifecycleLogger: SingleFragmentActivity::DeckOptions::onAttach
06-17 07:27:02.178 24508 24508 I FragmentLifecycleLogger: SingleFragmentActivity::DeckOptions::onCreate
06-17 07:27:02.185 24508 24508 D AutofillManager: Fill dialog is enabled:false, hints=[]
06-17 07:27:02.187 24508 24508 I PageFragment: Loading http://127.0.0.1:41381/deck-options/1656458056109
06-17 07:27:02.193 24508 24577 W PageWebViewClient: Not found backend/sveltekit/index.html
06-17 07:27:02.194 24508 24508 I FragmentLifecycleLogger: SingleFragmentActivity::DeckOptions::onViewCreated
06-17 07:27:02.195 24508 24508 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
06-17 07:27:02.195 24508 24508 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
06-17 07:27:02.196 24508 24508 I FragmentLifecycleLogger: SingleFragmentActivity::DeckOptions::onStart
06-17 07:27:02.198 24508 24508 I AnkiDroidApp$onCreate: SingleFragmentActivity::onResume
06-17 07:27:02.198 24508 24508 D UsageAnalytics: sendAnalyticsScreenView(): SingleFragmentActivity
06-17 07:27:02.199 24508 24508 D UsageAnalytics: getOptIn() status: false
06-17 07:27:02.200 24508 24508 I FragmentLifecycleLogger: SingleFragmentActivity::DeckOptions::onResume
06-17 07:27:02.208 24508 25241 D TrafficStats: tagSocket(233) with statsTag=0xffffffff, statsUid=-1
06-17 07:27:02.210 24508 25242 D AnkiServer: Rejecting GET request to server /deck-options/1656458056109
06-17 07:27:02.212   541  2806 D CoreBackPreview: Window{31af148 u0 com.ichi2.anki.debug/com.ichi2.anki.SingleFragmentActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@e9e5d06, mPriority=0, mIsAnimationCallback=false}
06-17 07:27:02.216 24508 24631 E OpenGLRenderer: Unable to match the desired swap behavior.
```

**Comment by BrayanDSO** [comment]
@mikehardy, I rebased onto main (ee8087338d050dd96f909f57d7ec3ba71c50a524) and tried the steps mentioned by you and it worked fine here. Could you please check it again?

[Screen_recording_20240617_153716.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/41e0d7b5-c6cf-4d72-9a3d-b109f405df57)

**Comment by Arthur-Milchior** [comment]
I tried an it works.
The only problem is that I get asked whether I want to go back and cancel my change. Even when I didn't do any change

**Comment by BrayanDSO** [comment]
> The only problem is that I get asked whether I want to go back and cancel my change. Even when I didn't do any change

#14438

**Comment by mikehardy** [comment]
It was a local environment difference - it works on other machines I have here, just one that was failing

The machine that's failing simply will *not* pull in the updated Anki-Android-Backend dep, it's really bizarre

In fact, doing `./gradlew :AnkiDroid:dependencies | grep -i david` doesn't even show the backend dependency!
Clearing gradle cache completely (`\rm -fr ~/.gradle`) had no effect, which was strange
On the same machine in a freshly cloned repo it worked though

So this is good to go - I did review everything - going to merge and do an alpha

but if other devs have issues, just make sure you've committed everything in your local clone then blow it away and reclone I guess 🤷

**Review by mikehardy — APPROVED** [review]
Fantastic

**Pull request merged**
