### PR TITLE
Make heavy check mark and down arrow styleable

### PR DESCRIPTION
**Pull request by Alyxvance**
Changes to make heavy check mark and Down Arrow in type cards styleable
line 740 taken from anki desktop

## Fixes
Fixes 
https://github.com/ankidroid/Anki-Android/issues/4841#issuecomment-604230121

## How Has This Been Tested?
Testet by my own on all aviable versions untill 2.9alpha56 + on Android 7 an 10

- [x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x ] You have commented your code, particularly in hard-to-understand areas
- [x ] You have performed a self-review of your own code
PR

### CODE REVIEW

**Comment by mikehardy** [comment]
@Alyxvance thanks for your patience! We had a massive backlog of PRs that we're nearly done working through now, and this was stuck behind earlier ones. I like this change and will merge it, but you need to alter the test that's failing in CI as well. I believe it is the lines that look like this since you fixed (corrrectly!) the HTML attributes there so expectations are no longer correct: 

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java#L56
https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java#L89
https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java#L122
https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java#L155
https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java#L188
https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerTest.java#L221

Seems as though they are all basically the same problem.

You can verify they work locally with `./gradlew jacocoTestReport`

**Comment by Alyxvance** [comment]
oh dear , sorry i am not a programmer like you. but i get failed test with 
java.io.FileNotFoundException: F:\\Anki-Android-master\AnkiDroid\build\intermediates\java_res\debugUnitTest\out\path-traversal.zip (Das System kann den angegebenen Pfad nicht finden)
i am using windows
Android Studio 3.6.1
Build #AI-192.7142.36.36.6241897, built on February 27, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: 
i am so sorry but i have it compiled and it works fine

**Comment by mikehardy** [comment]
How unfortunate :-), we had a problem with windows and this file before #5602 but I thought I fixed it. Let me investigate the root cause and I can probably push a change to this PR to have it work as well - the change itself is good

**Comment by mikehardy** [comment]
After fixing the root cause of the windows test failure (sorry about that) in #5920 I pulled this branch and patched up the unit test failure - it pretty trivial and once it's done passing CI tests I'll merge it in. Thanks @Alyxvance

**Comment by mikehardy** [comment]
This released as 2.10alpha65 as soon as google is done processing it

**Comment by mikehardy** [comment]
Hello! with the 2.14 release we started accepting donations with the stated goal of accepting money from users (the users' way of saying "Thanks!") to support maintenance and development of AnkiDroid.

We are looking through PRs merged in releases going back to release 2.10 (where we have good record keeping of what's in releases) to let our contributors know.

If you'd like to submit an expense related to your work here, to share in a portion of our hopefully-sustainable monthly disbursement, please read here and do so in the next couple of days:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process

This is our first time handling donations and attempting to compensate anyone with these processes, so please be flexible and patient with us

Thank you for your contribution to AnkiDroid!

**Pull request merged**
