### PR TITLE
Fix bury note action

### LINKED ISSUE #14455: Can’t suspend note anymore
Running on 2 days old HEAD. On notes with multiple cards, the suspend note action lead to a toast stating 0 cards are suspended. The card do not change and still appear if I close and open the deck

### PR DESCRIPTION
**Pull request by dae**
Closes #14455

### CODE REVIEW

**Comment by snowtimeglass** [comment]
Thank you so much for the prompt fix. 

Since the originally mentioned issue in #14455 is about "Suspend note" action, I was wondering if you could add a change for it into this PR as well.

**Comment by dae** [comment]
Good catch!

**Comment by snowtimeglass** [comment]
Thank you!

**Review by BrayanDSO — APPROVED** [review]
I had encountered the same issue while studying. LGTM. Thanks for the fix

**Pull request merged**
