### PR TITLE
Updated strings from Crowdin 20210602

### PR DESCRIPTION
**Pull request by mikehardy**
Standard I18N sync after merging some new strings

### CODE REVIEW

**Comment by mikehardy** [comment]
Marking for stable branch pick as the strings now include new strings for features that are not on stable branch but they are backwards compatible so we can keep picking across the branches

**Comment by david-allison-1** [comment]
Fixed: valid_js_api_version (kr)

**Comment by david-allison-1** [comment]
Tested on my machine and `lintRelease` passed, but apparently missed one

**Comment by mikehardy** [comment]
Big enough gap we should be able to trigger another zipball build from crowdin, I just hit the action for sync again, thanks @david-allison-1

**Pull request merged**
