### PR TITLE
Only offer to migrate storage if logged in

### PR DESCRIPTION
**Pull request by david-allison**
If a user is not logged in, we risk losing their data

Issue #5304

### CODE REVIEW

**Review by ShridharGoel — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
Seems reasonable - I re-ran CI checks, appears related to general Github explosion today + prettier action failure (which you've seen. David..)

**Comment by david-allison** [comment]
I'm going to add an override in the debug/build config: I'd like this in the final build, but it gets in the way of testing

**Comment by mikehardy** [comment]
Marking as pending merge but in combo with blocked by dependency that should hold it up at your discretion

**Comment by david-allison** [comment]
Note: modified with a `BuildConfig` flag

**Review by mikehardy — APPROVED** [review]
still looks good post-addition of override

**Pull request merged**
