### PR TITLE
Add preview in notes editor

### LINKED ISSUE #5644: Preview not available in note editor
###### Reproduction Steps

1. Open card browser and click on the newly made flashcard
2. Edit the flashcard as required
3. Click top right corner to open the drop down menu

###### Expected Result

There should be an option to preview the flashcard

###### Actual Result

There is no such option. Instead you have to go back to the list of flashcards, then select the flashcard, then click on top right corner to get the drop down menu to select preview flashcard.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by Tetsuya95**
## Purpose / Description
Adds missing preview option in the notes editor.

## Fixes
Kinda fixes #5644 

"Kinda" because the current preview behaviour doesn't make much sense, since it will not preview the actual changes to the notes/cards but still the old card in the database. This should be somehow addressed in another PR since it involes changing how the Previwer itself works and which params are getting passed to it.

## Approach
Added the preview "eye" in the toolbar in notes editor. Clicking on it opens the previewer to preview the card that's beeing edited.

## How Has This Been Tested?
Testend on pixel 2 api 29 emulator.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
Thanks for your patience on this @crscher I'm going to link it to #5151 as it will be what addresses the concern of preview with currently-edited contents. I believe #5151 will need to go in first for this to make sense, yes. But then this is *exactly* what everyone will want.

**Comment by crscher** [comment]
Np, I'm glad I did something useful :)

**Comment by mikehardy** [comment]
@Tetsuya95 I finally finished #5151 (I think) and it's waiting for review, so I felt comfortable basing new work on it. I just created #6063 which took your edits as a starting point, but sent the unsaved information currently in the NoteEditor and passes it to the new CardTemplatePreviewer built for #5151 that can handle unsaved data

So this PR is obsolete but the one that hopefully goes in is built directly on it and saved me time as I knew the Previewer code well but I didn't have to look at the NoteEditor stuff much at all since it was done :-). Cheers

**Comment by mikehardy** [comment]
The related PR just merged so this feature will be in the next alpha!

**Pull request closed without merging**
