### PR TITLE
[Kotlin Migration] ImageField

### PR DESCRIPTION
**Pull request by Akshay0701**

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Some issues:

<details>

```
Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
    var mImagePath: String? = null
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 errors, 0 warnings
```

```
com.ichi2.anki.NoteEditorTest > clozeNoteWithClozeInWrongFieldDoesNotSave SKIPPED

com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest > nonExistingFileDoesNotDisplayPreview FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.multimediacard.fields.ImageField.getImagePath(ImageField.kt:63)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldController$ImageViewModel.replaceNullValues(BasicImageFieldController.java:860)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.createUI(BasicImageFieldController.java:139)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.recreateEditingUi(MultimediaEditFieldActivity.java:205)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onCreate(MultimediaEditFieldActivity.java:121)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:284)
        at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:113)
        at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:203)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:113)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:118)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivityTestBase.getControllerForIntent(MultimediaEditFieldActivityTestBase.java:63)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivityTestBase.getControllerForField(MultimediaEditFieldActivityTestBase.java:52)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest.getValidControllerNoImage(BasicImageFieldControllerTest.java:127)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest.nonExistingFileDoesNotDisplayPreview(BasicImageFieldControllerTest.java:66)

com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest > erroringFileDoesNotDisplayPreview FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.multimediacard.fields.ImageField.getImagePath(ImageField.kt:63)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldController$ImageViewModel.replaceNullValues(BasicImageFieldController.java:860)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.createUI(BasicImageFieldController.java:139)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.recreateEditingUi(MultimediaEditFieldActivity.java:205)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onCreate(MultimediaEditFieldActivity.java:121)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:284)
        at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:113)
        at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:203)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:113)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:118)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivityTestBase.getControllerForIntent(MultimediaEditFieldActivityTestBase.java:63)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivityTestBase.getControllerForField(MultimediaEditFieldActivityTestBase.java:52)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest.getValidControllerNoImage(BasicImageFieldControllerTest.java:127)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest.erroringFileDoesNotDisplayPreview(BasicImageFieldControllerTest.java:81)

com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest > invalidImageResultDoesNotCrashController FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.multimediacard.fields.ImageField.getImagePath(ImageField.kt:63)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldController$ImageViewModel.replaceNullValues(BasicImageFieldController.java:860)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.createUI(BasicImageFieldController.java:139)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.recreateEditingUi(MultimediaEditFieldActivity.java:205)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onCreate(MultimediaEditFieldActivity.java:121)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:284)
        at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:113)
        at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:203)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:113)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:118)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivityTestBase.getControllerForIntent(MultimediaEditFieldActivityTestBase.java:63)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivityTestBase.getControllerForField(MultimediaEditFieldActivityTestBase.java:52)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest.getValidControllerNoImage(BasicImageFieldControllerTest.java:127)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest.invalidImageResultDoesNotCrashController(BasicImageFieldControllerTest.java:108)

com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest > constructionWithoutDataGivesNoError FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.multimediacard.fields.ImageField.getImagePath(ImageField.kt:63)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldController$ImageViewModel.replaceNullValues(BasicImageFieldController.java:860)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.createUI(BasicImageFieldController.java:139)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.recreateEditingUi(MultimediaEditFieldActivity.java:205)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onCreate(MultimediaEditFieldActivity.java:121)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:284)
        at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:113)
        at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:203)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:113)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:118)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivityTestBase.getControllerForIntent(MultimediaEditFieldActivityTestBase.java:63)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivityTestBase.getControllerForField(MultimediaEditFieldActivityTestBase.java:52)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest.getValidControllerNoImage(BasicImageFieldControllerTest.java:127)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest.constructionWithoutDataGivesNoError(BasicImageFieldControllerTest.java:51)

com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest > fileSelectedOnSVG FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.multimediacard.fields.ImageField.getImagePath(ImageField.kt:63)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldController$ImageViewModel.replaceNullValues(BasicImageFieldController.java:860)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldController.createUI(BasicImageFieldController.java:139)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.recreateEditingUi(MultimediaEditFieldActivity.java:205)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity.onCreate(MultimediaEditFieldActivity.java:121)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:284)
        at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:113)
        at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:203)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:113)
        at org.robolectric.android.controller.ActivityController.create(ActivityController.java:118)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivityTestBase.getControllerForIntent(MultimediaEditFieldActivityTestBase.java:63)
        at com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivityTestBase.getControllerForField(MultimediaEditFieldActivityTestBase.java:52)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest.getValidControllerNoImage(BasicImageFieldControllerTest.java:127)
        at com.ichi2.anki.multimediacard.fields.BasicImageFieldControllerTest.fileSelectedOnSVG(BasicImageFieldControllerTest.java:96)
```

</details>

**Comment by Akshay0701** [comment]
yes i will solve this issues and other pr issues tonight...

**Comment by david-allison-1** [comment]
Still pending feedback

**Comment by Akshay0701** [comment]
can you change this pr to draft for now...

**Pull request closed without merging**
