### PR TITLE
Allow special characters to be escaped

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
dae/anki@491b8ea63fdf049dae122a0bc905e0eac3c7451f

## Purpose / Description
Main purpose: having libanki similar to Anki's folder Anki.

## Fixes
Allow to deal with search of tags when there are multiple tags

## Approach
As in Anki

## How Has This Been Tested?

gradlew.
Create a collection with two notes. one with tag "tag%". One with tag "tag". 
Open the browser. Enter search "tag:tag\%". You'll find only the first note, as in anki.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
compile error

**Comment by timrae** [comment]
Please keep these all in one of pull request as you were previously doing.
Otherwise I get a million emails in my inbox. I'll get to them when I can.

**Comment by Arthur-Milchior** [comment]
@timrae should I delete the pull request which did succesfully pass travis ?
I thought having plenty of small pull request was the usual way to do this. And since it seems hard to ensure that all tests suceeds, this allow for more finer control about what's wrong and what's ok. Avoiding to have everything delayed because a single commit from anki can't be ported easily because of a missing library in old APIs.

**Comment by timrae** [comment]
No need to delete the existing PRs yet, I guess it does make it easier to do the testing and get certain commits merged without blocking, it's just a bit bad timing since we just released v2.9.

**Comment by timrae** [comment]
Has this been tested yet?

**Comment by Arthur-Milchior** [comment]
No. I edit the text and post a comment when a manual test is done. However, I didn't yet have time to test all PR I did. I believe that I won't teach you anything if I tell you that each test actually take some time to perform. Mostly because of the time it takes to builds a apk, send it to the virtual machine, and actually use the VM

**Comment by timrae** [comment]
Yeah I understand that testing takes a lot of time. Normally you can just press the "run" button in Android studio, which will build + install + run the APK in the VM. Is this what you're doing, or are you doing some kind of manual installation process?

**Comment by Arthur-Milchior** [comment]
This is what I'm doing. My point that each time I did it, it took me something like 3 minutes before the program actually starts. And then the program is extremely slow. Furthermore, it's boring to do. So i didn't do all at once

**Comment by Arthur-Milchior** [comment]
Test explained

**Comment by Arthur-Milchior** [comment]
Test explained

**Pull request merged**
