### PR TITLE
Cancel load deck count on pause

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Since it's called again on onResume, it's useless to keep computing it in background.

No reason to use `tasksToCancelOnClose` since it does the same job as CancelAllTasks

Running it on my phone

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
It was not wrong at all. It was actually the only place in the code where cancelling of tasks were done at all.

**Comment by mikehardy** [comment]
I cancelled somewhere, in memory pressure during multi-select rescheduling undo I think :-)

**Comment by Arthur-Milchior** [comment]
I would suspect that you are making a reference to: d657e0548e6bc7c6a156cda74be9ca8ac1703feb

But I don't really see why it makes any sens to just cancel the task which is currently running. I mean, you have no idea what tasks is running, so you may cancel something important.
And anyway, this method only cancel a task which is running. Cancelling a future task may make sens, but not cancelling running task, since almost all of our method never check whether it is cancelled or not.

Anyway, I was making a reference to `cancelTask(type)`, the version with a fixed card type.

**Comment by mikehardy** [comment]
I may not have known exactly what I was doing back then, and you're right it should be switched to a cancel All tasks of these 3    case RESCHEDULE_CARDS:
                    case REPOSITION_CARDS:
                    case RESET_CARDS:

 I should PR that

**Comment by Arthur-Milchior** [comment]
I considered questionning this code. But I don't even know what `onTrimMemory` is, so I just dealt with other part of the code. It's not like I have not enough improvement to do right now :p

**Pull request merged**
