### PR TITLE
[Kotlin Migration] Atom

### PR DESCRIPTION
**Pull request by dorrin-sot**
## Purpose / Description
Migrate Atom.java to Kotlin

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Thanks for the conversion.

Can you please follow the two commit rules of https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md ?

**Comment by dorrin-sot** [comment]
@Arthur-Milchior I can't find the `Extra commit for java > kt renames` 
image

**Comment by dorrin-sot** [comment]
@Arthur-Milchior Done 😁

**Review by mikehardy — APPROVED** [review]
LGTM

**Comment by mikehardy** [comment]
This still passes local CI integration rebased against main

**Review by david-allison — APPROVED** [review]

**Pull request merged**
