### PR TITLE
Improved README

### LINKED ISSUE #8201: Improve README
I would recommend adding the tech stack being used and list of contributors like this - https://github.com/facebook/jest#credits
This would be a good morale booster for contributors and make the Readme look more attractive

I can work on this

### PR DESCRIPTION
**Pull request by aflah02**
## Purpose / Description
Makes README more attractive to contributors

Fixes #8201

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Note that I edited the PR description with the Github-specific `Fixes #number` style that we request in the template, so that the issue and the PR are connected in the GitHub UI - this really helps people that review things

**Review by mikehardy — CHANGES_REQUESTED** [review]
credits at the bottom was the right choice - good thinking there

I mentioned sponsors twice but that was my mistake sorry, what I meant was opencollective contributors as the third tier of opencollective credits (the last one, that is)

I think it is possible to pull that list as well so it is opencollective sponsors then backers then contributors?

This looks really close though!

**Comment by aflah02** [comment]
@mikehardy Is this better now?

**Review by mikehardy — APPROVED** [review]
This looks great! Honestly, it highlights how big this project has grown - and quite recently (last year or so, really). Amazing.

Thanks for this!

**Comment by aflah02** [comment]
@mikehardy It was my pleasure to work on this. I got to learn how big this project really is!

**Comment by mikehardy** [comment]
Yeah, it's a little crazy. Up until last year it was about 1.5 million users supported by 1 person (Tim Rae, then me) for the last few years. And even most of this year it is nearly 2 million users with just David, Arthur and I working on it. But the impact the application has on people's lives is incredible, and it is great to have this exposure to new developers and see so many new people eager to work on it. Cheers

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!

**Comment by aflah02** [comment]
@mikehardy Nah it wasn't anything special. Thanks though!

**Pull request merged**
