### PR TITLE
feat(v16): implement findCards in backend

### LINKED ISSUE #4821: Make duplicate check ignore accents/trema in Russian
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. add Russian word to deck
2. try to add the same word again with accent (indicating the stress), e.g. from QuickDic

###### Expected Result
Red highlight as duplicate indication

###### Actual Result
 Duplicate is not recognized

I suggest making the duplicate detection ignore accents/trema on Russian vowels, as
1. the trema is optional ("ё" often written as "е")
2. accents are only used in dictionaries to indicate the stressed syllable

I see the potential hitch with other languages where accents are used and make a difference between two different words (e.g. Spanish "se"≠"sé").
Maybe this can be limited to Russian/Cyrillic letters? (I don't know if there are other Cyrillic alphabets using accents, though.)
Or maybe the difference is that the Spanish "é" is an actual character opposed to a Russian vowel + an accent (separate combining Unicode character)?

Anyway, this is just an idea and not urgent by any means.

### LINKED ISSUE #5308: is:due not working for cards reviewed today when rebuilding filtered deck (v2?)
###### Reproduction Steps

0. Maybe prerequisite: Use v2 scheduler (so reviews should be consistent for learn or relearn cards)
1. Build a filtered deck "is:due prop:due>-1" (in my case currently includes cards mostly somewhere in "relearn")
2. review that deck until none of its cards is due
3. rebuild the deck

###### Expected Result

Since no cards are due, none should be in there. Anki Desktop 2.1.12 behaves that way.

###### Actual Result

Cards that were reviewed are shown as due again, even if they are scheduled for tomorrow.

I can repeat this cycle, and the same cards will show up every time.

###### Debug info

AnkiDroid Version = 2.9alpha68

Android Version = 6.0.1

ACRA UUID = ff44a484-01ff-4f08-9bd4-fb5454c0504c

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

### LINKED ISSUE #5543: Feature request: ignore accents etc. in browser search
It would be very useful for me if the search in the card browser could be improved in a way that accents etc. are ignored. I am searching very often a special term like, i.e. 'insólito', but if I omit the accent in the search input field (e. g. 'insolito') the result list is empty.

Of course this is nothing I expect, and I think also that everybody else would honour my feature request. For those who like to have a strict search there could be still an appropriate option.

I know that the original Anki program behaves the same, but there exists the possibility to loosen the strict search by means of a plugin (Ignore Accents in Browser Search).

Would be great if you could provide the same, e.g. with an appropriate option.

### LINKED ISSUE #6427: Feature request: support regex searches in libanki/finder.java
This isn't something I'd use many times, but I might attempt implementing. [Anki 2.1.24+ supports regular expression searching in the browser](https://docs.ankiweb.net/#/searching?id=regular-expressions)(and also filtered decks? Need to confirm) using a syntax of `re:`. If there's nothing holding back changes to finder.java, I'll give this a try.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #8116: Search card ignore case
**Is your feature request related to a problem? Please describe.**
Not a bug but a feature currently not very practical

**Describe the solution you'd like**
When searching for cards, I'd like to be able to ignore the case (all the time via a toggle in the advanced settings). Currently the search performs an exact contains match so if I have a uppercase letter in my word and searching with a lowercase I won't find my cards. This is annoying because I have to type all my search in multiple ways to make sure I have not that card already with a slightly different case (usually the first letter of the first word).

You might say I should write all my cards in lowercase but I already have a huge list of cards and I don't really feel like editing them one by one. Furthermore when downloading other user's collections the problem remains.

**Describe alternatives you've considered**
The workaround is currently to do multiple search with different case which is not very practical and I still can miss some cards and end up creating duplicates, very similar cards

**Additional context**

Searching for "воздух" ("air" in russian) with lowercase return nothing because I have created the card with a leading uppercase В

Screenshot_20210216-201111

Searching with a leading uppercase allow to find it
Screenshot_20210216-201100

### LINKED ISSUE #9573: [Bug] "is:learn is:review" not showing any cards
###### Reproduction Steps

1. Open Card browser
2. Put "is:learn is:review" as a search condition.

###### Expected Result
Should filter cards that have lapsed and are awaiting relearning. That how it works on desktop Anki.

###### Actual Result
No cards are shown.

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 8.0.0

Manufacturer = asus

Model = ASUS_Z01HD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 8.0.0; ASUS_Z01HD Build/OPR1.170623.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.61 Mobile Safari/537.36

ACRA UUID = ffc51eb1-d4d4-4314-a51d-a8de3cb61665

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
First change for the Rust backend: relatively simple - call through to `searchCards`

## Fixes
Fixes #9573
Related: #8307 - fixed after a backend upgrade
Fixes #8116
Fixes #6427
Fixes #5543
Fixes #5308
Fixes #4821 (brings us to ecosystem compatibility, new issue needs to be implemented on Anki Desktop)

## Approach

* mirror the protobuf in standard Java code
* change the implementation to use the mirror
* implement the method
* find that a new exception is thrown, handle it
* test
* Fix an issue with #7070

## How Has This Been Tested?

Unit tests and tested on my Android 11

image

⚠️ This is not translated, translations need to be handled in `Anki-Android-Backend`
🔋 Yes, I need to charge my phone more often

## Learning (optional, can help others)

https://github.com/david-allison-1/anki/blob/2296461136ada51437da076fda41cf735743c0e0/pylib/anki/collection.py#L417-L438

https://github.com/david-allison-1/Anki-Android-Backend/blob/main/tools/protoc-gen/test/backend.proto#L88

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
These all look good to me! Sorry this sat and took a conflict, happy to see de-conflict / merge after CI green

**Comment by david-allison-1** [comment]
That's a lot of purple notifications 💜💜

**Comment by voidplayer** [comment]
This is great, i cant wait for 2.16 :)

I have a workaround for some of these issues for so long

Thanks for the work!!

**Comment by david-allison-1** [comment]
> This is great, i cant wait for 2.16 :)
> 
> I have a workaround for some of these issues for so long
> 
> Thanks for the work!!

Awesome! Sorry to say, I think this will hit 2.17 (which could potentially be a quick follow-up after 2.16), we're waiting for https://github.com/ankidroid/Anki-Android/pull/9249, a very important and potentially dangerous change before 2.16 can go out.

I don't feel comfortable combining this with an additional risky change (upgrading the DB schema, and running Anki Desktop code for core operations). We want as few users uninstalling during storage the migration as possible, as it will raise additional issues.

**Comment by voidplayer** [comment]
Oh, what a shame, I saw it merged in master and thought that it was finally going to happen

#9249 does sound scary... 2.16 is going to be a big one!

Good job to everybody involved!

**Pull request merged**
