### PR TITLE
Fix crash when editing note and adding audio

### LINKED ISSUE #12865: [Bug] alpha90 crashes when editing note and adding audio
###### Reproduction Steps

1. go to edit note
2. remove all the text from back of the card
3. insert an image and hit ok
4. click on the attachment icon again
5. try inserting audio this time

###### Expected Result
there should be a menu to select options with

###### Actual Result
edit image is directly opened and when we hit add audio the application crashes

###### Debug info
AnkiDroid Version = 2.16alpha90

Android Version = 12

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_x86_64 Build/SE1A.220630.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = 246da304-f39d-4cd2-9fc7-d1bc0bd83ad0

New schema = true

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by pratyaksh1610**
## Purpose / Description
Fix crash when editing note and adding audio

## Fixes
Fixes #12865

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

## Before

https://user-images.githubusercontent.com/76740999/202966195-1b4308ed-fc80-47a1-82f2-fdcd7e9c03a6.mp4

## After

https://user-images.githubusercontent.com/76740999/202966207-f730d33b-3597-430b-afc2-00beebb6c2be.mp4

### CODE REVIEW

**Comment by criticalAY** [comment]
I wouldn't suggest changing the parameters. Let it be non null instead of doing that we can change the place where it's being used   ```textView.text = field?.text  ?: ""``` in the BasicAudioFieldController file if I recall correctly

**Review by BrayanDSO — APPROVED** [review]
LGTM. FWIW, `super.setText` takes null values and convert them to `""`

**Comment by criticalAY** [comment]
The original method doesn't have ```?``` so why to do so when we can simply catch and fix the NPE from where it is arising? just curious

**Comment by criticalAY** [comment]
https://developer.android.com/reference/android/widget/TextView.html#setText(java.lang.CharSequence):~:text=public%20void%20setText%20(CharSequence%20text%2C%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20TextView.BufferType%20type) this is the original method no ?

**Review by lukstbit — APPROVED** [review]

**Comment by lukstbit** [comment]
@criticalAY The superclass method from TextView is in java so it can accept nulls by default(as Brayan pointed out it simply transform them into empty strings). While we could handle the null where it appears it's better to use the proper method signature to clearly specify the types.

**Pull request merged**
