### PR TITLE
NF: remove background suffix from tasks-related classes

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
No need to specify "background" anymore since there is no "listener" type anymore

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
sorry I was unclear in my last comments @Arthur-Milchior - I welcome these PRs and now some of the complexity actually *does* look to be reducing, these internal APIs are starting to look pretty clean now.

**Review by david-allison-1 — APPROVED** [review]
LGTM

**Comment by mikehardy** [comment]
Ok - I re-started emulator tests (`Process crashed`...) and I'll mark this Pending Merge - pending directly on @Arthur-Milchior's preference to add the comments from #8753 as I think they naturally belong in this PR

**Comment by Arthur-Milchior** [comment]
If you so please

**Pull request merged**
