### PR TITLE
Tweak navigation drawer colors

### PR DESCRIPTION
**Pull request by timrae**
First of all, in my opinion the black theme doesn't work well in the drawer due to:

0. No contrast with the black background behind it
0. Lack of matching with the header image (which was designed for a grey drawer)

These issues could potentially be fixed by customizing the drawer shadow color (to a lighter color), and designing a new header image respectively, but I think it looks pretty good just using the standard dark theme in the drawer when black theme is enabled. How do others feel about this?

Secondly, I much prefer the dark theme drawer colors from the current version 2.5, so I have ported those customizations over to v2.6. This is something I've been meaning to do for a while.

New:
device-2016-04-26-111543

Old:
device-2016-04-26-112158

### CODE REVIEW

**Comment by hssm** [comment]
I don't think it looks good. It's really bright and doesn't match the rest of the theme. For reference, this is what the black theme looks like in Solid Explorer (which I sorta used as a guide):

screenshot_20160426-152757

I think it looks really good and wouldn't mind trying to emulate more of it in the future.

**Comment by timrae** [comment]
Alright, I've pushed a new version which adds the tweaks to the existing version, along with a better matched header image. How's this?

device-2016-04-26-160357

**Comment by timrae** [comment]
I still don't like that it's hard to distinguish where the drawer ends, but not too sure how we could fix that.

**Comment by hssm** [comment]
Yeah that looks good.

**Comment by snowtimeglass** [comment]
How about brightening the background a bit?
image
The characters on the background may need to be darkened as ever, though.

**Pull request merged**
