### PR TITLE
NF: uses AbstractSched before DeckDueTreeNode (performance)

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This will help make https://github.com/ankidroid/Anki-Android/pull/6522 smaller. It will use more correct path for the deck due nodes

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Force pushed to remove conflict

**Comment by mikehardy** [comment]
Took a conflict from the Reminder PR, but otherwise ready to go

**Comment by Arthur-Milchior** [comment]
We'll have a lot of conflict here. That's the problem with dealing with related PR in parallel

**Comment by mikehardy** [comment]
This one has a compile error after the conflict removal - it has to be something trivial but does need a fix @Arthur-Milchior

**Pull request merged**
