### PR TITLE
Move transparent tag from Application to Activity

### PR DESCRIPTION
**Pull request by timrae**
@hssm how's this?

### CODE REVIEW

**Comment by timrae** [comment]
Ugh actually it looks like this doesn't fix the original problem

**Comment by hssm** [comment]
Are you sure? I don't really notice it. At least there is no white flash even when in night mode.

**Comment by timrae** [comment]
I just realized I was testing with an extra `android:theme="@style/App_Theme_White"` inside the Application tag, which breaks it. If we are setting the theme programatically in every Activity (which I think we are), then we shouldn't need that and this commit should be OK.

**Comment by hssm** [comment]
I see no issues after a quick scan through all our main Activities.

**Comment by timrae** [comment]
Yeah I guess we'd know about it already if we weren't since we'd see a non-night-mode Activity with night mode on

**Comment by timrae** [comment]
OK let's just go with this, using a staged rollout

**Comment by timrae** [comment]
Sh*t forgot to update the changelog bundled with the app

**Pull request merged**
