### PR TITLE
[Kotlin Migration] JsonObjectTest

### PR DESCRIPTION
**Pull request by david-allison**
I wanted `JSONObject`, but the test needed to come first

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
agreed on this 

> @KotlinCleanup("fix `object`")` 

:-) 

Running it through my local CI simulacrum as well while CI here chews. Will merge if it passes, and try to get through to the 40-50s test perf improvement

**Comment by david-allison** [comment]
I found an existing lint check today which catches all of the backticks. 

Suggesting getting it into the codebase; #10449

**Comment by mikehardy** [comment]
Sounds great - could be a good first issue
I saw this left the source as TEST in kotlinMigration.gradle which causes conflicts in all existing kotlin migration PRs, repaired in https://github.com/ankidroid/Anki-Android/commit/a0642f573e67f03f6eff44d3440c490a2540addc

**Comment by david-allison** [comment]
> Sounds great - could be a good first issue I saw this left the source as TEST in kotlinMigration.gradle which causes conflicts in all existing kotlin migration PRs, repaired in [a0642f5](https://github.com/ankidroid/Anki-Android/commit/a0642f573e67f03f6eff44d3440c490a2540addc)

Oh geez, good catch, sorry!

**Pull request merged**
