### PR TITLE
Correcting #6289

### LINKED ISSUE #6289: AnkiDroid is creating broken custom study decks
A bunch of users have been reporting an error like the following:

https://anki.tenderapp.com/discussions/ankidesktop/41865-error

ec7b0356bdc6217212832bfd75a4853a6b476051 appears to be the cause - https://github.com/ankidroid/Anki-Android/blob/c6291ef91fdb2fc85bd852702541d0fad2257ed3/AnkiDroid/src/main/java/com/ichi2/utils/JSONObject.java#L15 is assigning to itself, causing it to be a null rather than a JSONObject.null, and a call in customstudy to dyn.put("delays", JSONObject.null) results in the key being missing. 

@Arthur-Milchior heads up

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Using the correct value of NULL.

I'll put a test soon. Wanted to push the obvious correction asap.

Thanks @dae for pinging me. 

----
_Edit by @david-allison-1_

Fixes #6289

### CODE REVIEW

**Comment by mikehardy** [comment]
Thanks for the quick fix! I purged out the current 2.10.3 hotfix queue but this one actually fits. I'll do a 2.10.3 with this and any obvious crash fixes shortly

**Comment by dae** [comment]
Thanks all

**Comment by mikehardy** [comment]
@dae sure - sorry for the hassle of course, release planning: the 2.10.3beta4 build just went out to google and I like a 2-day soak to make sure I did nothing dumb. All the contained changes have already soaked on alpha though so I can accelerate at your discretion, I won't feel bothered. Otherwise expect 2.10.3 on Friday afternoon my time with this fixed

**Comment by dae** [comment]
Not a problem - ultimately it comes back to the decision ~10 years ago to pass around untyped JSON instead of packing/unpacking it into a proper structure first, which is somewhat expensive in Python. Wish I had a time machine!

**Pull request merged**
