### PR TITLE
Updated strings from Crowdin 20201231

### PR DESCRIPTION
**Pull request by mikehardy**
Standard translation sync

### CODE REVIEW

**Comment by david-allison-1** [comment]
I've already sent a message of the Odia translators about format strings, will send a second nudge

**Comment by david-allison-1** [comment]
Fixes performed:

`sync_error_invalid_sync_server`
`check_media_nohave`
`check_media_invalid`

https://crowdin.com/translate/ankidroid/8169/en-or?filter=basic&value=0#q=stats_overview_answer_buttons_learn

**Comment by mikehardy** [comment]
Thanks! I appreciate the fix, crowdin only let's free people do a new download after a delay of 30-45 mins so I'll hit the resync button again after the delay

**Comment by mikehardy** [comment]
The lint check didn't run auto when the github action force synced (I'll examine) but I manually ran the check and it passed:

https://github.com/ankidroid/Anki-Android/runs/1631054586?check_suite_focus=true

**Pull request merged**
