### PR TITLE
NF: rename PREF_DECK_PATH to PREF_COLLECTION_PATH

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
For the context, long ago "deck" were called "collection" in anki. Then a
collection could have many decks, and the difference became important.

I don't want to change the value, because it would be hard to do properly and
have no interest. But I clearly want to change the constant name because "DECK"
makes no sens today

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
I mildly disapprove, as the variable no longer matches the value

**Comment by Arthur-Milchior** [comment]
"needs second approval" is strange if you don't approve.

I'd argue that the semantic is more important than the value stored in preference. In an ideal world, there should be no reason to ever look at the actual string used for preference

**Comment by david-allison** [comment]
> "needs second approval" is strange if you don't approve.
> 
> I'd argue that the semantic is more important than the value stored in preference. In an ideal world, there should be no reason to ever look at the actual string used for preference

I'm not going to bikeshed on this one, I wouldn't ask to have it changed if it exited as `PREF_COLLECTION_PATH`, and there's more important things to get through.

**Review by mikehardy — APPROVED** [review]
I think it does make more sense as a variable name and we're stuck with the pref key (or at least: migrating it is a lot of work + little gain) so this is okay by me

**Comment by mikehardy** [comment]
Hi there! APRIL OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [April 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-04-01..2022-04-30)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for all contributions. The only PRs that will not go through the OpenCollective process are ones directly related to am accepted GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!

**Comment by Arthur-Milchior** [comment]
I feel silly. I saw 10+ notificationd and I wondered how you were able to close that many PR so quickly in a few minutes.
Now I get it.

**Comment by mikehardy** [comment]
Yep, was just rolling through a spreadsheet keeping track of github handles along with the list of April PRs, add name / paste message, next :-)

**Pull request merged**
