### PR TITLE
migrate gradle to build-logic / composite build  module to share build logic between modules 

### PR DESCRIPTION
**Pull request by AbdelrahmanEsam**
## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
This hasn't been discussed and there's a lot here

What's the advantage? 

This needs the PR description filled in

**Comment by AbdelrahmanEsam** [comment]
@david-allison  hi david .... I will discuss this with you at discord

**Comment by david-allison** [comment]
Thanks! Can you post the reply here so people looking into the history can understand

**Comment by david-allison** [comment]
I don't see a message in Discord and I'm getting loads of notifications from this

It would be useful to discuss first, as it's currently a "close & don't merge" unless there's reasoning given

**Review by lukstbit — CHANGES_REQUESTED** [review]
Ok with the idea not with the implementation(too much extracted, too fragmented).
This also really needs a series of smaller precise commits not just one mega commit.

**Comment by AbdelrahmanEsam** [comment]
@david-allison  hi david hope you are doing well .... can you help me figureing out why emulator tests fails ?

**Comment by david-allison** [comment]
I want to go back to lukstbit and my unanswered comments first.

There's little point of getting this passing CI if we don't know whether we're going to merge it or not. 

I'll rerun CI

**Comment by AbdelrahmanEsam** [comment]
well I am  using a build-logic module for building the app but why ?
well this have good results like 
1- you are using regular kotlin code for build your app so it's so much easier to any kotlin dev to do it .
2- now your build is composable so you can share the same gradle plugin to more than one module instead of rewrite the same logic in more than one module  and when you alter it  you are altering it with all of your modules so this is good for archtiecture .

you can read more about composite build here 
https://docs.gradle.org/current/userguide/composite_builds.html

**Review by david-allison — CHANGES_REQUESTED** [review]
Comment stands

> Ok with the idea not with the implementation(too much extracted, too fragmented).
> This also really needs a series of smaller precise commits not just one mega commit.

**Pull request closed without merging**
