### PR TITLE
[Kotlin Cleanup] Cardbrowser

### PR DESCRIPTION
**Pull request by dorrin-sot**
[Kotlin Cleanup] Cardbrowser

### CODE REVIEW

**Comment by lukstbit** [comment]
I went through your code and found some issues if you want to look at them(too many to use the review function). I would go through them from the bottom, this way if you make changes the line that I referenced remain valid:

- line 118 delete the `@KotlinCleanup` annotation
- line 486 you could use the `edit {}` extension function on `SharedPreferences` to remove the need to call apply
- line 817 the two code blocks are not the same, the original added the flag only if it was true, yours always adds the flag. _Probably_ ok but there's no need to change it.
- line 944 the two lines are not equivalent anymore because `intent.action` can be null. The original code handled a potential null intent action while your code will crash if `intent.action` is null, the order is important
- line 1024 several issues here:
   - you're not using the original HashMapInit() which sets it's capacity
   - there's no point to add a function to another class for one usage just to simplify that piece of code
   - one way you could re write that piece of code:
   
```
                val savedFilters: HashMap<String?, String?> = savedFiltersObj?.let {  obj ->
                    HashMapInit<String?, String?>(obj.length()).apply {
                        for (searchName in obj) {
                            this[searchName] = obj.optString(searchName)
                        }    
                    }
                } ?: HashMapInit(0)

```          
- line 1315 should probably remove the java stream usage and use only kotlin collection methods.                   
- line 1496 use the `filterNot` to avoid the inverse check(and to also follow the original code):
`     .filterNot { Decks.isDynamic(it) }`
- line 1535 you have a duplication bug: you're adding the same data to the StringBuilder in its constructor and also immediately after with append()
- line 1549 the code is not equivalent, the original code adds a `(` only if the list of tags is not empty, your code adds a "(" not taking in consideration if the tags list has elements or not in it
- line 2043 should delete the @KotlinCleanup and the @Suppress annotations
- line 2123 the nullability of customFont could be improved, the only location where MultiColumnListAdapter is instantiated, it receives a non null Context and a non null custom font value
- line 2287 please leave the braces were they are as the [code convention](https://github.com/ankidroid/Anki-Android/wiki/Code-style#braces) requires, also add braces for a when case which has a block of code(similar for line 2307)

**Comment by dorrin-sot** [comment]
@lukstbit thanks for the review. a few questions:
1. In line 2123, is there a default value for `customFont` that i should set in case the preference "browserEditorFont" was null?
2. In line 474, is it right to just return
```
getSharedPreferences(PERSISTENT_STATE_FILE, 0).all[LAST_DECK_ID_KEY]?.let { id -> id as Long }
```

**Comment by Arthur-Milchior** [comment]
I agree with @lukstbit , there is a lot of things here. Which makes it hard to review as I don't know what is related to what.
Would you mind making small commits, or even small PR, so that I can concentrate on a specific change you want to make, and either merge it or request change. This will make review far simpler, and if one of those change introduce a bug, it'll be nice not to have to revert everything

**Comment by lukstbit** [comment]
@dorrin-sot 

1. That was a mistake from my part, as the property is a String it can have a null value so sflCustomFont can't be made non nullable
2. looks ok

**Pull request closed without merging**
