### PR TITLE
feat: Add public interface for Decks.java

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

First stage of abstracting out `Decks.java` and merging it with `DecksV16.kt`

This is going to be a massive project, as Decks.java has a lot of custom logic to deal with filtered decks incorrect naming etc... that `DecksV16` doesn't have.

## Fixes
Related: #8988 

## Approach
* Introduce `DeckManager` and expose from `Collection`
* Have `Decks` inherit from `DeckManager`
* Pull the methods using `refactor - Pull` until it compiles
* Change the ordering of the methods and the JavaDocs to use the base class

## How Has This Been Tested?

* Untested

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
Requires fix for emulator tests

**Review by mikehardy — APPROVED** [review]
Seems good - passing emulator tests now

**Comment by david-allison-1** [comment]
@Arthur-Milchior Could I get a quick confirmation that https://github.com/ankidroid/Anki-Android/pull/9392/commits/9c79821bd730925c5c2cb7a2fba4429630ff22c2 is correct before I merge this. Logically it seems fine to me after a second pass through, but confirmation would be fantastic

**Comment by mikehardy** [comment]
took a conflict :-), I'm inclined to merge though post-conflict-resolve

**Comment by mikehardy** [comment]
Has a specific request for review on commit https://github.com/ankidroid/Anki-Android/commit/9c79821bd730925c5c2cb7a2fba4429630ff22c2 from @Arthur-Milchior :pray:

**Comment by david-allison-1** [comment]
This has been rebased and now is a blocker for #8988. 

Happy to let this go through without a comment now (as long as CI passes)

**Review by mikehardy — APPROVED** [review]
Still LGTM - let's go

**Pull request merged**
