### PR TITLE
NF: Uses constant for decks "dyn" value

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
The goal is only to improve readability. Values are only 0 and 1, so rewritting `!= 0` to `== DECK_DYN` is always correct.

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Is there anything I am expected to do related to codecov ?

**Comment by mikehardy** [comment]
> Is there anything I am expected to do related to codecov ?

@Arthur-Milchior no :-), you are just the first PR to go through after I enabled it. I need to set up a .codecov.yml that tunes the expected coverage down to match our current reality. Actually, if you want to try doing that it would be helpful but not necessary. Just put one looking for a range of 36-100, maybe copying this one but 36 in place of 40 https://github.com/invertase/react-native-firebase/blob/master/codecov.yml and push it to this PR?

**Review by mikehardy — APPROVED** [review]
These all look fine - thanks for your patience, as ever @Arthur-Milchior

**Comment by mikehardy** [comment]
@Arthur-Milchior I know you are on record as not participating, but you do contribute so I will always include you in the monthly notices regardless :-)

Just a friendly notice (one per person, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for Jan 2021 submissions

Process note:

At the end of the month, go to our OpenCollective expense form and follow their process to file an expense.

As this process is new, we have little information on how many people will submit expenses, so we don't know what the total will be. As mentioned in "sustainable" above, we are trying to distribute about 10% of the total balance each month but we are just guessing how many hours and what hourly rate will actually add up to that now. 

We will almost certainly adjust the amount of hours or the hourly rate this month in order to distribute the target amount, so if you submit an expense please submit for all the hours you spent, at the arbitrary rate of $10/hr. Once all the hours from everyone are in so I have real numbers to do real math on, I'll comment on the expenses to offer guidance on how to adjust them, then we'll process them

Thanks!

**Pull request merged**
