### PR TITLE
Factorizing Timber on task listener

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description
Factorizing some code. Helping other dev' to make short code for task with timbers.

## Fixes
For some reason unknown to me, some task like to Timber.d before and
after execution. This lead to code duplication which I am
factorizing.

Note that in one case, the timbers started "start/finished" instead of onPre/PostExecute. I believe it's not a change that matters.

## How Has This Been Tested?

In my Merge branch. No particular test was done here. 

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
What is "an isDebug" 
Do you know if there is an easy way to uses introspection in java ? I.e. that the timber knows the name of the method which called them/variable where they are defined ? Because currently, the name of the variable/method are given explicitly in strings. And doing it systematically in every tasks is going to be long to write. I'd prefer for it to be automatized

**Comment by mikehardy** [comment]
> What is "an isDebug" 

```java
        if (BuildConfig.DEBUG) {
```

That will keep the expensive code from executing normally, where the expensive code is:

> Do you know if there is an easy way to uses introspection in java ? I.e. that the timber knows the name of the method which called them/variable where they are defined ? Because currently, the name of the variable/method are given explicitly in strings. And doing it systematically in every tasks is going to be long to write. I'd prefer for it to be automatized

We do this already for production logging, the implementation is in here and may be (?) reusable as is?

```java
AnkiDroidApp.ProductionCrashReportingTree.getTag()
```

**Comment by Arthur-Milchior** [comment]
It seems you have a good idea about what you want and how you want it. May I leave this task to you and close this PR ? I've a few thing I still want to investigate and I don't think I want to spend time on this one in the near future

**Comment by mikehardy** [comment]
I'm not interested enough to do it as I'm about full time busy just handling the throughput from you and David - I'll close this for now, and anyone that wants to work on it later can ask for a reopen - a viable PR for merge would definitely automate the thing completely vs sprinkling in another class

**Comment by Arthur-Milchior** [comment]
Yeah, thanks for being so quick with my PRs. I do realize that I am probably getting an important amount of your time.

**Pull request closed without merging**
