### PR TITLE
enhancements: add merged pr to milestone

### PR DESCRIPTION
**Pull request by krmanik**
## Purpose / Description
`curl` was used to send request for adding milestone to merged PR. But now GitHub actions script used to do the same task. It is cleaner and better than previous implementation. 

## Fixes
Fixes #10749

## Approach
Used [github-script](https://github.com/actions/github-script) to add milestone

## How Has This Been Tested?
Tested on my repository

## Learning (optional, can help others)
https://github.com/actions/github-script
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Let's give it a run :-)

**Comment by mikehardy** [comment]
💯 it worked - I verified by looking at actions output for the run that triggered on this merge, and it was using action-script this time + it has the milestone now

**Comment by krmanik** [comment]
One more enhancements will be to update the milestone number when current milestone closed. I will look into this later.

**Comment by mikehardy** [comment]
Or get associated issues that are closed by the PR and add the milestone to them...

**Pull request merged**
