### PR TITLE
RecyclerView, CardView in DeckPicker

### PR DESCRIPTION
**Pull request by abvanpelt**
Initial RecyclerView with CardViews implementation.

Not done:
- hiding default deck if empty
- new/learn/rev colors
- selectors
- selected deck
- arrow buttons to expand/collapse subdecks
- ellipsizing long deck names/adding spacing to multiline deck names
- general card UI tweaks

### CODE REVIEW

**Comment by eginhard** [comment]
Sorry, I missed the discussions on this. In Material Design, cards should only be used for "content composed of different types of objects or similar objects whose size or supported actions can vary considerably" (http://www.google.com/design/spec/components/cards.html) and often suggest some physical interaction like dragging or swiping away. Homogeneous content that doesn't have many actions or lines of text should be presented in a list, which also needs less space. 
I guess cards could work if the Deckpicker had a richer layout including deck descriptions and images, but I think having a compact deck list is more desirable, at least on small screens.

**Comment by jshevek** [comment]
I'm really glad steps are being taken to improve some of the old code.

I agree with Eginhard in theory, but this looks like a good first step to improve deckpicker.
I think that improving the app iteratively is more important than requiring that all UI improvements represent the best use of material design. 

The card-like look and style will also be familiar to users, which has its own advantages.

**Comment by abvanpelt** [comment]
I do think the current look of the cards (if you've built this branch) isn't great. I plan on making some improvements so that it looks nicer. 

I'm partial to the cards, though I could see a benefit to making them more like Inbox or Google+ cards, where they extend off the left/right sides of the screen. I think as we clean up the UI, we might like to put more information in the DeckPicker for each deck (what options group each belongs to, as one example), and so cards make a lot of sense to me moving forward.

I wouldn't mind a toggle to switch between currently due decks (as cards) and then a regular list of all decks. That wouldn't be part of this PR.

**Comment by abvanpelt** [comment]
I don't understand the failure -- I haven't made any changes to ShowcaseView, nor did I change anything to target v19.

`Execution failed for task ':ShowcaseView:library:preBuild'.`
`> failed to find target android-19 : /home/travis/build/ankidroid/android`

**Comment by timrae** [comment]
Don't worry about it, it's a problem with the server config that I'm trying to resolve

**Comment by timrae** [comment]
Can you post some screenshots please?

**Comment by abvanpelt** [comment]
device-2015-03-28-125631
device-2015-03-28-125748

**Comment by timrae** [comment]
Thanks for your work @abvanpelt and for your comments @eginhard 

Presumably that guideline is hinting at performance issues...? 

Rather than committing to one approach now, I think it might be more productive to do a bit more long-term planning on what the final design will look like in 2.5. Once we agree on how the app design will look in 2.5 we can decide if CardView is advantageous for that goal.  Obviously the main undecided factor is the StudyOptionsFragment... so I'd like to at least finish that discussion on the forum before making a decision on this.

**Comment by abvanpelt** [comment]
@timrae @eginhard -- sounds like we're not on the same page with using CardViews. I think the guideline is saying that ListViews are preferred for simple views. Our DeckPicker at this stage is still simple, so that makes sense.

We can explore UI options for DeckPicker in the forum. I think it would be helpful to have a transparent list of priorities for this project. It seemed like DeckPicker was the thing to change -- now we're pushing it back past StudyOptionsFragment.

I'd still like to merge in the RecyclerView work, which is actually the majority of my changes. I can change out the CardViews for LinearLayouts/RelativeLayouts. This would still give the appearance of a ListView while giving us the flexibility for different layouts later, and is much cleaner than our current implementation. Thoughts?

**Comment by timrae** [comment]
> It seemed like DeckPicker was the thing to change -- now we're pushing it back past StudyOptionsFragment.

For me, it's not really a matter of priorities or pushing one part of the design back against another, I'm just saying that we need to make decisions about the "big picture" before working on the fine details. Removing StudyOptions screen will necessarily imply some radical changes in `DeckPicker` so it's important to discuss more.

> I'd still like to merge in the RecyclerView work, which is actually the majority of my changes. I can change out the CardViews for LinearLayouts/RelativeLayouts.

Absolutely, that's a great idea

**Comment by timrae** [comment]
Just to clarify, you mean swap out the `CardView` for the old layout right? If it's not a quick fix, you might be better off waiting for the outcome from the discussion on the forum...? It's up to you

**Comment by abvanpelt** [comment]
It *should* be a quick fix, but I'll let you know if I run into unforeseen issues. I'll push that change tonight or tomorrow.

**Comment by abvanpelt** [comment]
Updated RecyclerView to have generic layouts. Looks just like a list now, with some nicer implementation. I added back in the colors for new/learn/rev.

Not working:
- hiding default deck if empty
- recycler item selectors
- selected deck
- clickable arrow buttons to expand/collapse subdecks
- ellipsizing long deck names/adding spacing to multiline deck names

device-2015-03-28-180325

**Comment by timrae** [comment]
Can you please resolve the merge conflicts? Also, if possible could you squash down to one commit?

> recycler item selectors

what do you mean by this?

**Comment by abvanpelt** [comment]
I just mean item selectors in general (changing color on pressed state).

I squashed a bunch of commits, which required a ton of re-resolving conflicts, then needed to do one last merge. Are you okay with two commits for this pull request?

**Comment by timrae** [comment]
Yes no problem

**Comment by timrae** [comment]
Please use a more descriptive commit name / description

**Comment by abvanpelt** [comment]
Okay, @timrae I updated the commit message.

**Comment by timrae** [comment]
oops there were a couple of stray version commits there that I thought would disappear from the commit history but didn't... oh well, nothing too major.

**Pull request merged**
