### PR TITLE
Use SQLite support library

### PR DESCRIPTION
**Pull request by hssm**
It's now or never I suppose. I really want to try this out and see how it goes.

See https://github.com/ankidroid/Anki-Android/issues/4332 for more details.

Only real downside I can think of is the added 2MB to the APK.

### CODE REVIEW

**Comment by timrae** [comment]
Did you forget to check-in the `build.gradle` file or something? The build is failing.

**Comment by timrae** [comment]
If these changes go well we should use the [`DatabaseErrorHandler`](https://developer.android.com/reference/android/database/DatabaseErrorHandler.html) Interface (i.e. the `onCorruption()` callback) on all platforms, as it's currently only supported on API 11+.

**Comment by hssm** [comment]
Oops, yea I did.

There's a bunch of WAL stuff we can get rid of as well.

**Comment by timrae** [comment]
2.2MB added to the binaries after this 泣

**Comment by hssm** [comment]
It's pretty large compared to the total size but I think it'll be worth it. AnkiDroid is still pretty tiny compared to other apps anyway.

**Pull request merged**
