### PR TITLE
Replaced String.format() with string template in Collection

### PR DESCRIPTION
**Pull request by Marius1501**
## Purpose / Description
Replaced basic usages of String.format with Kotlin string templates

## Fixes
Related to https://github.com/ankidroid/Anki-Android/issues/11449

## Approach
Replace `String.format("%s", x)` with `"$x"`

## How Has This Been Tested?

Passed all unit tests

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by n1snt — APPROVED** [review]

**Review by n1snt — CHANGES_REQUESTED** [review]
The same changes @oakkitten requested in the other [PR](https://github.com/ankidroid/Anki-Android/pull/12690) need to be made here too.

**Comment by oakkitten** [comment]
In this case I think that `+` results in a not very readable text, just because the number of elements is so big. What I would do is extract stuff into variables and reduce the overall number of transformations required. **Not tested**:

```kt
fun log(vararg objects: Any?) {
    if (!debugLog) return

    val unixTime = TimeManager.time.intTime()

    val outerTraceElement = Thread.currentThread().stackTrace[3]
    val fileName = outerTraceElement.fileName
    val methodName = outerTraceElement.methodName
    
    val objectsString = objects
        .map { if (it is LongArray) Arrays.toString(it) else it }
        .joinToString(", ")

    writeLog("[$unixTime] $fileName:$methodName() $objectsString")
}
```

I also renamed the `log` method's parameter to `objects`. We are printing method name below, and one could assume that “arguments” refers to arguments of that method. I think `objects` removes this confusion and better represents the idea.

**Review by lukstbit — APPROVED** [review]
Thank you for contributing.
Note: I edited you initial post to remove the keyword `Fixes` as it would close the issue while there are other usages of `String.format()` to be replaced.

**Review by david-allison — APPROVED** [review]
Looks great, thanks!

**Comment by david-allison** [comment]
@Marius1501 Please note that your `user.name` and `user.email` settings in your git config are not associated with an email/account on GitHub. This means your commits are not associated with your GitHub account.

Please see: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address

**Pull request merged**
