### PR TITLE
fix(tags-dialog): fix UTFDataFormatException

### LINKED ISSUE #16490: [BUG]: java.io.UTFDataFormatException: encoded string too long
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- Select a card in the Browser
- Click `Edit tags`

### Expected behaviour

Tags dialog opens up

### Actual behaviour

The following error appears and a report is sent.
```
java.io.UTFDataFormatException: encoded string too long: 1939277 bytes
```

### Debug info

```text
AnkiDroid Version = 2.19alpha3 (77b02ec1b0a29b0c9626ef4414ee3308f8bebd6b)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-5; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36

ACRA UUID = 70fd8e4a-1bcf-4f20-8bac-43ba9946410f

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
`DataOutputStream.writeUTF` had an undocumented exception: `java.io.UTFDataFormatException: encoded string too long` if the string length is greater than a short

## Fixes
* Fixes #16490

## Approach
Use `commons.io.FileUtils` to fix

## How Has This Been Tested?
* Unit tested
* Tested one tag on an API 24 emulator
* Personal device:
  * Personal collection
    * Turns out that I do have a couple of CJK tags, but they were unaffected by the issue 
    * Edit Tags 
  * Collection from #16476 
    * Filter by tags 
  * AnKing
    * Edit tags 

## Learning
We should discuss process improvements

https://stackoverflow.com/questions/22741556/dataoutputstream-purpose-of-the-encoded-string-too-long-restriction

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by lukstbit** [comment]
Did you test this on the lowest android version?
Also, it's safe to use that tag data? Asking as Anking looks like a paid thing.

**Comment by david-allison** [comment]
> Did you test this on the lowest android version? Also, it's safe to use that tag data? Asking as Anking looks like a paid thing.

AnKing V11 is free, it went paid after V12

**Comment by david-allison** [comment]
Thanks. Tested on SDK 23

```
AnkiDroid Version = 2.19alpha3-debug (77b02ec1b0a29b0c9626ef4414ee3308f8bebd6b)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 6.0 (SDK 23)

ProductFlavor = amazon

Manufacturer = unknown

Model = Android SDK built for arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0; Android SDK built for arm64 Build/MASTER; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.117 Mobile Safari/537.36

ACRA UUID = 3f065615-e889-4f4a-a395-325985e009e6

FSRS Enabled = false

Crash Reports Enabled = false
```

**Review by lukstbit — APPROVED** [review]
I'm fine with the changes.

**Review by mikehardy — APPROVED** [review]
"Thanks Apache Foundation and all you Apache Commons hackers" !

And thanks David :-)

**Pull request merged**
