### PR TITLE
#13921

### PR DESCRIPTION
**Pull request by AmitPandey1**
## Purpose / Description
This commit is regarding issue no #13921 

## Fixes
- add button is showing black after following some particular flow
to fix this add one vector files.

## Approach
- I was trying to change in source ic_add_white file and then I check its uses its been used in several places so I created new xml files for it and check.

## How Has This Been Tested?
I am able to reproduce this issue on realms x7 max flow details to reproduce this issue is mentioned on issue no #13921 

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by SanjaySargam** [comment]
Hey @AmitPandey1 Thanks for contributing 🚀🚀

**Review by Arthur-Milchior — COMMENTED** [review]
First, welcome. Thanks a lot for contributing.

I must admit your solution seems to work. So, congrats!
However, I've a few request before merging it.

First, I'd like your commit message to contain some text. Explaining what you are to do.
Because, if I understand correctly, you're adding a new search icon and a new + icon.
I'd really like if you could explain: did you copy them from somewhere, if so, what is their licence. 

Why are they different than already existing icon; they seems not to have the same pathData.

And more importantly, why does it solve anything. Because I admit I'm lost. I'd love to understand what caused the issue in the first place. So that we can ensure it does not occur anymore anywhere else.

Also, for the pull request, same, it would be nice to have a title that explains what is done here. Such as "Correcting color of the icon in the card browser"
Because, when I search for a PR to review when I have some free time, I need to have a title that I understand, to know whether it's something that seems simple enough or very complex. And also, if I want to find it later, I clearly won't recall what the number of the issue/pr

**Comment by oakkitten** [comment]
This is funny and probably my fault. The reason this PR works is not any of the changes inside the files but because the copy of the add icon is a different file.

What I either missed or ignored was this fact:

> By default, all drawables instances loaded from the same resource share a common state; if you modify the state of one instance, all the other instances will receive the same modification.

You might be seeing where the root of the problem is now. To reproduce the bug, you need to open reviewer, and one particular thing about it is that its overflow menu has icons. These icons are separately tinted with `overflowAndPopupMenuIconColor`:

https://github.com/ankidroid/Anki-Android/blob/77edd4f9e9668193e26a404c234b218cd9730894/AnkiDroid/src/main/java/com/ichi2/utils/MenuUtils.kt#L62-L75

`ic_add_white` is used in both reviewer and browser. So if you open the reviewer first, the icon gets tinted in code and made dark, and then it is reused in the browser without going further re-tinting.

The issue might be solved by mutating the icon, e.g. in the code above you'd say

```kt
item.icon?.mutate()?.setTint(iconColor)
```

However care must be taken to ensure that it's clear on the call site that the icons are being mutated, perhaps by naming the method `mutateAndTintOverflowMenuIcons`?

Also, `DrawableWrapperCompat` does not seem to be delegating `mutate()` to the wrapped drawable, making the call no-op. To overcome this we can reimplement the delegation:

```kt
    class Wrapper(drawable: Drawable) : DrawableWrapperCompat(drawable) {
        override fun mutate() = drawable!!.mutate()

        override fun getIntrinsicWidth() = super.getIntrinsicWidth() + extraPadding * 2

        override fun setBounds(left: Int, top: Int, right: Int, bottom: Int) {
            super.setBounds(left + extraPadding, top, right - extraPadding, bottom)
        }
    }
```

**Comment by Arthur-Milchior** [comment]
I prefer @oakkitten 's suggestion. While it's more complex, it ensures the problem is solved once and for all.
@AmitPandey1 do you think you can do it? I don't know how clear it is; personally, I had to look at some documentation to understand the full context of oakkitten's remark. Don't hesitate to ask question if you need help (are you on our discord by the way?)

I'd also like to note that `forEachOverflowItemRecursive` actually also runs on buttons that preferences are disabled.

**Comment by Arthur-Milchior** [comment]
So, I actually corrected the recursive function in #13948, and that seems to have corrected the bug.
And also ensure the function does what its name state. If my PR gets accepted, the current PR will probably have to be abandoned. I'm sorry to do this to your first contribution with us; but, generally, I'd prefer something that does not add more icons; and seems to just correct the problem everywhere at once

**Comment by AmitPandey1** [comment]
Hi @oakkitten @Arthur-Milchior, no issue. it will be learning for me.
However when I was understanding the flow I tried to copy new icon in same ic_add_white and it stopped working.

yes I think if we can specifically set tint for this icon when we that page comes in foreground.

and thanks I will keep trying to contribute and learn

**Pull request closed without merging**
