### PR TITLE
fix: Snackbar is misaligned during startup

### LINKED ISSUE #16061: [BUG]: `Upgraded version to %s` snackbar is misaligned
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Upgrade to an alpha version newer than the installed one
2. Open the app

### Expected behaviour

The `Upgraded version to ...` snackbar should be shown above the FAB

### Actual behaviour

It is shown in front of the FAB

### Debug info

```text
2.18alpha7 (e434419c31f9d27a85bce64fd362a40b1cb44181)

Emulator with API 34
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by 410063005**
## Purpose / Description
Try to fix #16061

## Fixes
* Fixes #16061 

## Approach
_How does this change address the problem?_

Wrap `showSnackbar()` in a `view.post()` call for these snackbars shown from `onCreate()`

image

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

- Emulator - Pixel XL (API 31)

## Before
image
image

## After
image
image

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

- https://stackoverflow.com/questions/66111612/snackbars-setanchorview-does-not-consistently-work-after-launching-an-activity
- https://stackoverflow.com/a/7735122

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by 410063005** [comment]
This is not a perfect and elegant fix but it works well.

**Comment by david-allison** [comment]
Why is this occurring?

**Comment by 410063005** [comment]
@david-allison 

Sometimes we call `showSnackbar()` from `onCreate()` in Anki. Sometimes we don't.  This is occurring in the former.

Calling `showSnackbar()` with a anchor view from `onCreate()` is not that reliable because the layout of the child views are not done.

I not sure I explain it clearly myself 😅 .  But I think this post has a better answer.  https://stackoverflow.com/a/7735122

> You can add a tree observer to the layout. This should return the correct width and height. onCreate() is called before the layout of the child views are done. So the width and height is not calculated yet. To get the height and width, put this on the onCreate() method:

**Review by david-allison — APPROVED** [review]
LGTM, thanks

**Review by krmanik — APPROVED** [review]

**Pull request merged**
