### PR TITLE
crash prevention by adding check for data connection

### PR DESCRIPTION
**Pull request by criticalAY**
## Pull Request template
crash check during sync

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
https://user-images.githubusercontent.com/48384865/198892938-28f71ea7-d6b7-4da9-a14a-810829d6e32a.mp4

**Comment by BrayanDSO** [comment]
1. To add/modify/remove a string you only need to do the changes at the `/values/` directory
2. Android methods to check if there is a internet connection aren't reliable, so we have a `Try Anyway` button if the user wants to insist. Adding another check (`NetworkUtils.isOnline`) makes the `Try anyway` button useless. If you want to avoid crashing, try catching the error and perhaps showing a suitable message to the user if that is the case

**Comment by criticalAY** [comment]
> 1. To add/modify/remove a string you only need to do the changes at the `/values/` directory. Please revert the rest
> 2. Android methods to check if there is a internet connection aren't reliable, so we have a `Try Anyway` button if the user wants to insist. Adding another check (`NetworkUtils.isOnline`) makes the `Try anyway` button useless. If you want to avoid crashing, try catching the error and perhaps showing a suitable message to the user if that is the case

The error is caused because there is no hostname attached to the call

**Comment by criticalAY** [comment]
```
java.net.UnknownHostException: Unable to resolve host "sync5.ankiweb.net": No address associated with hostname
                                                                                                    	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
                                                                                                    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
                                                                                                    	at java.net.InetAddress.getAllByName(InetAddress.java:787)
                                                                                                    	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
                                                                                                    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.kt:196)
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req$default(HttpSyncer.kt:127)
                                                                                                    	at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.kt:62)
                                                                                                    	at com.ichi2.libanki.sync.Syncer.sync(Syncer.kt:102)
                                                                                                    	at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:273)
                                                                                                    	at com.ichi2.async.Connection.doOneInBackground(Connection.kt:128)
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:122)
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:52)
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
                                                                                                    Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                                                                                                    	at libcore.io.Linux.android_getaddrinfo(Native Method)
                                                                                                    	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:58)
                                                                                                    	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
                                                                                                    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90) 
                                                                                                    	at java.net.InetAddress.getAllByName(InetAddress.java:787) 
                                                                                                    	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) 
                                                                                                    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) 
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) 
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) 
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.kt:196) 
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req$default(HttpSyncer.kt:127) 
                                                                                                    	at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.kt:62) 
                                                                                                    	at com.ichi2.libanki.sync.Syncer.sync(Syncer.kt:102) 
                                                                                                    	at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:273) 
                                                                                                    	at com.ichi2.async.Connection.doOneInBackground(Connection.kt:128) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:122) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:52) 
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764) 
2022-10-21 04:01:17.066  4814-7353  Connection              com.ichi2.anki                       E  doInBackgroundSync error
                                                                                                    java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "sync5.ankiweb.net": No address associated with hostname
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.kt:223)
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req$default(HttpSyncer.kt:127)
                                                                                                    	at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.kt:62)
                                                                                                    	at com.ichi2.libanki.sync.Syncer.sync(Syncer.kt:102)
                                                                                                    	at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:273)
                                                                                                    	at com.ichi2.async.Connection.doOneInBackground(Connection.kt:128)
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:122)
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:52)
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
                                                                                                    Caused by: java.net.UnknownHostException: Unable to resolve host "sync5.ankiweb.net": No address associated with hostname
                                                                                                    	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
                                                                                                    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
                                                                                                    	at java.net.InetAddress.getAllByName(InetAddress.java:787)
                                                                                                    	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
                                                                                                    	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
                                                                                                    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.kt:196)
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req$default(HttpSyncer.kt:127) 
                                                                                                    	at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.kt:62) 
                                                                                                    	at com.ichi2.libanki.sync.Syncer.sync(Syncer.kt:102) 
                                                                                                    	at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:273) 
                                                                                                    	at com.ichi2.async.Connection.doOneInBackground(Connection.kt:128) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:122) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:52) 
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764) 
                                                                                                    Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                                                                                                    	at libcore.io.Linux.android_getaddrinfo(Native Method)
                                                                                                    	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:58)
                                                                                                    	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
                                                                                                    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90) 
                                                                                                    	at java.net.InetAddress.getAllByName(InetAddress.java:787) 
                                                                                                    	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129) 
                                                                                                    	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) 
                                                                                                    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) 
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) 
                                                                                                    	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) 
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.kt:196) 
                                                                                                    	at com.ichi2.libanki.sync.HttpSyncer.req$default(HttpSyncer.kt:127) 
                                                                                                    	at com.ichi2.libanki.sync.RemoteServer.meta(RemoteServer.kt:62) 
                                                                                                    	at com.ichi2.libanki.sync.Syncer.sync(Syncer.kt:102) 
                                                                                                    	at com.ichi2.async.Connection.doInBackgroundSync(Connection.kt:273) 
                                                                                                    	at com.ichi2.async.Connection.doOneInBackground(Connection.kt:128) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:122) 
                                                                                                    	at com.ichi2.async.Connection.doInBackground(Connection.kt:52) 
                                                                                                    	at android.os.AsyncTask$2.call(AsyncTask.java:333) 
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                                                                                                    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764) 
```

**Comment by criticalAY** [comment]
I am closing this PR until I am handle the exception properly

**Pull request closed without merging**
