### PR TITLE
Dependency updates 20220205

### PR DESCRIPTION
**Pull request by mikehardy**
Mostly-standard dependency updates PR - been a while since I did one so quite a few are pending

### CODE REVIEW

**Comment by mikehardy** [comment]
I've merged in all the dependency updates that passed individual CI runs

I just rebased this on main and nothing on main has changed, so CI should be representative

This should be ready to go as soon as CI goes green, and I expect it to go green

Squash merge though of course :-)

**Comment by mikehardy** [comment]
Is this test just flaky? Wasn't failing on any of the individual commits...

```

SchedV2Test > test_learnV2 FAILED
    java.lang.AssertionError: expected:<3> but was:<2>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at com.ichi2.libanki.sched.SchedV2Test$test_learnV2$2.invoke(SchedV2Test.kt:478)
        at com.ichi2.libanki.sched.SchedV2Test$test_learnV2$2.invoke(SchedV2Test.kt:478)
        at com.ichi2.libanki.sched.SchedV2Test.ifV2(SchedV2Test.kt:83)
        at com.ichi2.libanki.sched.SchedV2Test.test_learnV2(SchedV2Test.kt:478)
```

**Comment by dae** [comment]
My guess is it's failing because it's a few minutes until 4AM GMT time. Might have more luck running it again in a minute or so?

**Comment by mikehardy** [comment]
Huh, didn't realize we still had that gremlin hanging around. Appears to be fine now, so yeah, we have the day rollover thing still in our test somehow :shrug:

**Pull request merged**
