### PR TITLE
NF: Gesture refactor to allow for mappable gestures

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
#8078 contains a large refactor to our gesture processing which allows arbitrary mapping of key inputs to commands

Currently, we map from Gesture -> Command

And we want to map from `Command -> [Gesture]` after the linked PR is completed

This brings the code closer to this PR, in a series of non-functional commits

The aim is that this change is fairly trivially reviewable, so we get closer to the idea

## How Has This Been Tested?

Unit tested

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM - this will be an interesting feature for 2.16 (more general mapping, and support for more peripherals, as this all lands, yes)

**Comment by mikehardy** [comment]
This doesn't look right?

```
> Task :AnkiDroid:compilePlayDebugAndroidTestJavaWithJavac FAILED
/home/mike/work/AnkiDroid/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/reviewer/PeripheralKeymapTest.java:45: error: incompatible types: invalid method reference
        PeripheralKeymap peripheralKeymap = new PeripheralKeymap(MockReviewerUi.displayingAnswer(), processed::add);
                                                                                                    ^
    incompatible types: ViewerCommand cannot be converted to Integer
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error

```

**Comment by david-allison-1** [comment]
Gah, sorry. Missed the `androidTest` classes, they're not built on a rebuild

**Comment by mikehardy** [comment]
All clean and passes this time :zap:

**Pull request merged**
