### PR TITLE
fix lint: `ImpliedQuantity`

### LINKED ISSUE #10481: Enable Lint `ImpliedQuantity`
The goal of this issue is to enable the lint check: `ImpliedQuantity`

Line: https://github.com/ankidroid/Anki-Android/blob/6260cd6e25f67f331833bbd0981f2cda5a426dde/lint-release.xml#L74

* This actively picks up vandalism in the lint
* We need to work out how to ignore `reschedule_cards_dialog_title`, (possibly others)
  * Ideally this only needs to be done in `/values`

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
This fixes the lint. Awaiting a translation sync to fix it for all strings

## Issue
FIxes #10481

## Approach

* Add a `%d`
* Rename string to force retranslation

And then make a small refactoring which I felt was worthwhile

## How Has This Been Tested?
<details><summary>Screenshots</summary>

image

image
</details>

## Learning

Reminder that `1` in other languages matches 11, 21, etc...

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
```
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-cs/03-dialogs.xml:85: Error: The plurals "reschedule_cards_dialog_title" in values-cs has no declaration in the base values folder; this can lead to crashes when the resource is queried in a configuration that does not match this qualifier [MissingDefaultResource]
    <plurals name="reschedule_cards_dialog_title">
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Unsure how to handle this one. The `reschedule_cards_dialog_title` appears to be unused in the code.

**Comment by Akshay0701** [comment]
I checked the values-cs/03-dialogs.xml file, and its plurals values are different the rest of the translation:
 
english and others:
```java
<plurals name="reschedule_cards_dialog_title_new">
        <item quantity="one">Reschedule %d card</item>
        <item quantity="other">Reschedule %d cards</item>
    </plurals>
```
values-cs:
```java
    <plurals name="reschedule_cards_dialog_title">
        <item quantity="one">Přeplánovat kartu</item>
        <item quantity="few">Přeplánovat karty</item>
        <item quantity="many">Přeplánovat karty</item>
        <item quantity="other">Přeplánovat karty</item>
    </plurals>
```

Maybe deleting this string will solve this issue.

**Comment by david-allison** [comment]
> I checked the values-cs/03-dialogs.xml file, and its plurals values are different then the rest of the translation:
> 
> english and others:
> 
> ```java
> <plurals name="reschedule_cards_dialog_title_new">
>         <item quantity="one">Reschedule %d card</item>
>         <item quantity="other">Reschedule %d cards</item>
>     </plurals>
> ```
> 
> values-cs:
> 
> ```java
>     <plurals name="reschedule_cards_dialog_title">
>         <item quantity="one">Přeplánovat kartu</item>
>         <item quantity="few">Přeplánovat karty</item>
>         <item quantity="many">Přeplánovat karty</item>
>         <item quantity="other">Přeplánovat karty</item>
>     </plurals>
> ```
> 
> Maybe deleting this string will solve this issue.

There's lots of similar issues https://github.com/ankidroid/Anki-Android/runs/5518256525?check_suite_focus=true

**Comment by mikehardy** [comment]
I take great pleasure from deleting unused things personally
If you remove the string it should auto-purge from all translations on next sync?

**Comment by david-allison** [comment]
Deleted strings and re-pushed. I hope this fixes things.

**Comment by david-allison** [comment]
> I take great pleasure from deleting unused things personally If you remove the string it should auto-purge from all translations on next sync?

I renamed the string, but errors were occurring on the old, unused one in the translation files

**Pull request merged**
