### PR TITLE
fix(model): generate req field for old client compatibility

### LINKED ISSUE #8945: [Bug] Collection created in 2.15 can't be opened in 2.14.6
###### Reproduction Steps

1. Create collection in 2.15
2. Create Note
3. Open in 2.14.6
4. Review

###### Expected Result

Works

###### Actual Result

```
2021-05-25 20:33:47.416 9612-9612/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki.e, PID: 9612
    com.ichi2.utils.JSONException: org.json.JSONException: No value for req
        at com.ichi2.utils.JSONObject.get(JSONObject.java:2)
        at org.json.JSONObject.getJSONArray(JSONObject.java:595)
        at com.ichi2.utils.JSONObject.getJSONArray(JSONObject.java:2)
        at com.ichi2.libanki.Models.emptyCard(Models.java:3)
        at com.ichi2.libanki.Card.isEmpty(Card.java:1)
        at com.ichi2.anki.AbstractFlashcardViewer.displayString(AbstractFlashcardViewer.java:1)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:6)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: org.json.JSONException: No value for req
        at org.json.JSONObject.get(JSONObject.java:400)
        at com.ichi2.utils.JSONObject.get(JSONObject.java:1)
        at org.json.JSONObject.getJSONArray(JSONObject.java:595) 
        at com.ichi2.utils.JSONObject.getJSONArray(JSONObject.java:2) 
        at com.ichi2.libanki.Models.emptyCard(Models.java:3) 
        at com.ichi2.libanki.Card.isEmpty(Card.java:1) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayString(AbstractFlashcardViewer.java:1) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:6) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1) 
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2) 
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10) 
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1) 
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4) 
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-05-25 20:33:47.418 9612-9612/? E/ACRA: ACRA caught a JSONException for com.ichi2.anki.e
    com.ichi2.utils.JSONException: org.json.JSONException: No value for req
        at com.ichi2.utils.JSONObject.get(JSONObject.java:2)
        at org.json.JSONObject.getJSONArray(JSONObject.java:595)
        at com.ichi2.utils.JSONObject.getJSONArray(JSONObject.java:2)
        at com.ichi2.libanki.Models.emptyCard(Models.java:3)
        at com.ichi2.libanki.Card.isEmpty(Card.java:1)
        at com.ichi2.anki.AbstractFlashcardViewer.displayString(AbstractFlashcardViewer.java:1)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:6)
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1)
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10)
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4)
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: org.json.JSONException: No value for req
        at org.json.JSONObject.get(JSONObject.java:400)
        at com.ichi2.utils.JSONObject.get(JSONObject.java:1)
        at org.json.JSONObject.getJSONArray(JSONObject.java:595) 
        at com.ichi2.utils.JSONObject.getJSONArray(JSONObject.java:2) 
        at com.ichi2.libanki.Models.emptyCard(Models.java:3) 
        at com.ichi2.libanki.Card.isEmpty(Card.java:1) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayString(AbstractFlashcardViewer.java:1) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:6) 
        at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1) 
        at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:2) 
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:10) 
        at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1) 
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:4) 
        at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1) 
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:791) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

req is unused in current clients but that is new enough we'll keep it for
compatibility for now

## Fixes
Fixes #8945

## Approach
restore some old code from release-2.14 branch - this is copy and paste from release-2.14, just adding comment clarifying the reason the code is back, and pointers to discussion

## How Has This Been Tested?

Visual inspection of JSON generated during model creation on release-2.14, release-2.15 without, and release-2.15 with this code

## Learning (optional, can help others)
There are no changes without unintended consequences

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Here's the deletion reference for comparison:

https://github.com/ankidroid/Anki-Android/pull/7980/files?file-filters%5B%5D=.java&hide-deleted-files=true#diff-c2ee46815a9845cdfdca8896c0676ea0f7e503cfe7203418b4b3b482fa49b94dL200-L978

**Review by david-allison-1 — APPROVED** [review]
LGTM, let's add a follow-up issue to revert the removal of unit tests

**Comment by mikehardy** [comment]
Database Structure document updated for future explorers https://github.com/ankidroid/Anki-Android/wiki/Database-Structure/_compare/3066e7777e7644a0e629fffdbadb91d4a013d538...ad04558b4a971639cc17861c7f73ca5e938163ee

**Comment by mikehardy** [comment]
Just as fast to restore the unit test right now - added commit with that, verified passing locally

**Pull request merged**
