### PR TITLE
build(ci): strip 'comment' from translated `/values/ `

### LINKED ISSUE #16208: Optimization: we should remove 'comment' from translated files to save space
Optimization: we should remove 'comment' from translated files to save space

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/16207#issuecomment-2064296781_
            

See: https://github.com/ankidroid/Anki-Android/blob/731203600791d01e7dfe1bdfb372679e66accb90/AnkiDroid/src/main/res/values-af/03-dialogs.xml#L240-L253

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
We had `comment=` elements in our translated XML which were not necessary

## Fixes
* Fixes #16208

## Approach
* sync
* Filter via regex
* run script

## How Has This Been Tested?
Script is executed in this PR. Trusting CI

## Learning (optional, can help others)
Our docs for the typescript localization are excellent. Thank you @krmanik!

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by lukstbit** [comment]
This took some conflicts. Should we add these commits to the git_blame_ignore file?

**Comment by david-allison** [comment]
@lukstbit I'll add to ignore-refs in a follow-up, commit hashes are unstable before we hit main

Would you accept this PR if conflicts are fixed? I'm mildly in favour

**Comment by lukstbit** [comment]
I would say yes. The main benefit that I see it's simpler diffs in the sync translation PRs. A bit annoying to have one translated word wrapped in 2-3 lines of comment text.

**Comment by Giyutomioka-SS** [comment]
@david-allison, is the tag 'Need a new dev' still valid? If so, what exactly do we need to do now?

**Comment by david-allison** [comment]
Just needs re-running after a translation sync and a quick merge

**Comment by Giyutomioka-SS** [comment]
Could you please clarify the specific steps I need to follow? What exactly do I need to do here?

**Comment by david-allison** [comment]
Right now, translation syncs are broken due to a markettitle issue, so don't take that on until it's fixed (probably a day)

Once it's done: 

* Rebase commit 1 and rerun the script listed in the commit message
* Rebase commit 3 and rerun the script listed in the commit message

**Comment by Giyutomioka-SS** [comment]
Is this the right approach?

1. Wait for the Fix
2. Rebase and Run for Commit 1:
    • Rebase my branch to include Commit 1:
    •	Navigate to the directory:
    •	Run the script:
3. Include Commit 2 in my Branch: 
    •	Rebase my branch to include Commit 2:
4. Rebase and Run for Commit 3:
    •	Rebase my branch to include Commit 3:
    •	Run the same script as in Commit 1:

**Comment by david-allison** [comment]
check out my branch 

* `gh pr checkout 16211`) - can also do this with pure git: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

* make your branch based off mine
* `rebase -i` and change the commits as you proposed

**Pull request closed without merging**
