### PR TITLE
Enhance the drawer experience #8070

### LINKED ISSUE #8070: Enhance the drawer experience
The conflict between the drawer and system gestures makes it not very convenient to use

### PR DESCRIPTION
**Pull request by HuixingWong**
https://user-images.githubusercontent.com/15938606/110728693-71a05d00-8258-11eb-807f-678744002736.MP4

## Purpose / Description
Greatly improve the drawer experience

## Fixes
Fixes #8070

## Approach
When the user swipes from a non-edge, it is easy to use the drawer, especially if the user has small hands and cannot touch the top left corner.

## How Has This Been Tested?
I used this in my self project for a long time

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

**Comment by mikehardy** [comment]
Hi there! How will this interact with the gesture system? It's my understanding from the library you integrated (https://github.com/PureWriter/FullDraggableDrawer) that this will now recognize drag from full screen, does it interact in any way with the existing gestures?

**Comment by HuixingWong** [comment]
> existing gestures
This library will determine whether the child view can consume scrolling events, so there will be no conflict with the existing gestures, only the current child view can not scroll horizontally will trigger the outer scrolling，My girlfriend is using this app for study and she told me that the phone screen is very large and it is sometimes difficult to tap out the drawer from the top left corner, so I made this modification so that I can call out the drawer at any time without conflicting with other gestures，she told me it was perfect after the change.

**Comment by mikehardy** [comment]
Fascinating - @david-allison-1 I think this has potential, as the person most familiar with gestures at this point, what do you think? @HuixingWong thank you for the detailed responses, and of course for attempting the modification in the first place. It just might work...

**Comment by david-allison-1** [comment]
I don't have a device with a version of Android capable of testing the new system level gestures.

If it works on an API 21 emulator, then I'm happy.

Won't be at a PC with free time for a few days, I'd be happy to see it in an alpha for testing.

**Comment by mikehardy** [comment]
Okay - I'll check it, I think the newer emulators (which I have) should be usable for gesture testing as well

**Review by jeeva2812 — CHANGES_REQUESTED** [review]
It would be of great help if you can add screen recordings in the PR description.

**Comment by HuixingWong** [comment]
> It would be of great help if you can add screen recordings in the PR description.

Thank you for your advice, i added a screen recording

**Comment by mikehardy** [comment]
Sorry this has sat for so long! I'm +1 on the change, personally. 
I just attempted to merge in current changes so this no longer has conflicts, and if it passes CI we can merge it

**Comment by mikehardy** [comment]
This will be in the next alpha - should be shortly

**Comment by mikehardy** [comment]
Very interesting! Thanks for testing and reporting @TowelSniffer - I am not surprised there is an interaction issue and I appreciate the link to a use case that shows the issue.

We can 
- revert (always a possibility)
- see if we can make it an advanced feature toggle (I would say default to off since interaction problems like this are difficult to describe)
- see if there is a way to make it coexist (the best option if possible)

I'll open a separate issue for this and tag it for 2.15 so we don't cause regressions for people

**Pull request merged**
