### PR TITLE
Lint: Enforce field naming rules: CONSTANT and mVar

### PR DESCRIPTION
**Pull request by david-allison-1**
**EDITED - now non-draft**

## Purpose / Description
Enforcing code style rules was taking a lot of time in code reviews

https://github.com/ankidroid/Anki-Android/wiki/Code-style#non-public-non-static-field-names-should-start-with-m
https://github.com/ankidroid/Anki-Android/wiki/Code-style#constant-final-variables-names-must-be-all-uppercase-using-underscore-to-separate-words

## Approach
Add a lint check

## How Has This Been Tested?
Lint failed when I added a badly named variable - also had IDE support

## Learning (optional, can help others)
Some inspiration from https://github.com/vanniktech/lint-rules

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
image
image

**Comment by david-allison-1** [comment]
Review goals:

* Do we want to go in this direction (worth the effort, and will we be able to/want to integrate this with a more automated solution)
* Is this level of automation appropriate, or would it be less intrusive as a pre-commit hook?

If accepted: what strategy to fix the currently broken variables

**Comment by TarekkMA** [comment]
I think if we want to follow the android style guidelines.

We need to add `s` before static fields also.

And for static final ALL_CAPS.

https://source.android.com/setup/contribute/code-style#follow-field-naming-conventions

**Comment by david-allison-1** [comment]
Agreed and happy to do so, just wanted maintainer consensus that the direction is good before continuing.

**Comment by Arthur-Milchior** [comment]
> I think if we want to follow the android style guidelines.

I think we want to follow our own guidelines: https://github.com/ankidroid/Anki-Android/wiki/Code-style#cheat-sheet

Admittedly, they are inspired/copied from Android ones.



> * Do we want to go in this direction (worth the effort, and will we be able to/want to integrate this with a more automated solution)

I'm totally for it.

> * Is this level of automation appropriate, or would it be less intrusive as a pre-commit hook?

This seems appropriate. I mean, in the worst case if it fails, there is a tool in android studio to rename the variable, so this is really quick to correct.

> If accepted: what strategy to fix the currently broken variables

Publish a branch with this PR + master, tell people to pull this branch, do as many correction as they want and do a PR with those corrections. Unless you have an easy way to correct automatically, which would be even better, I don't know lint.

**Comment by david-allison-1** [comment]
Okay, if we're going to ask for fixes manually, it feels nicer for contributors to handle this one issue at a time, rather than all at once. I'll add an issue

Thanks for the feedback and approval

**Review by mikehardy — APPROVED** [review]
LGTM FWIW, and I like the direction as well - maybe someone will change them one fell swoop with a PR

**Comment by david-allison-1** [comment]
> LGTM FWIW, and I like the direction as well - maybe someone will change them one fell swoop with a PR

I'll take it on if Arnold doesn't want it

**Review by mikehardy — APPROVED** [review]
Nice!

**Comment by mikehardy** [comment]
Anything built from main branch from here on out won't have these issues....

**Pull request merged**
