### PR TITLE
Dependency Updates 20220219

### PR DESCRIPTION
**Pull request by mikehardy**
This one is all ktlint stuff - there was quite a bit of upstream activity there filtering into quite a bit of "new version adoption" change required here and it's all in this PR

Underlying PR against the dependency-updates branch was #13265 and has separate commits if anyone wants to review again but I'll merge when CI is green

### CODE REVIEW

**Comment by mikehardy** [comment]
(I'm fixing conflicts now)

**Comment by mikehardy** [comment]
Had to run `./gradlew ktlintFormat` as there were some changes on main after the fixup I suppose? Asking for review on those as I recall some manual fixups on the original PR, perhaps these auto-fixups are distasteful, though I'm +1 on fully auto-formatting...

**Review by david-allison — APPROVED** [review]

**Review by david-allison — CHANGES_REQUESTED** [review]
> > Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/compat/ResolveInfoCompat.kt:43:9 Declarations and declarations with comments should have an empty space between.
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/compat/ResolveInfoCompat.kt:164:44 Unnecessary trailing comma before "]"

FAILURE: Build failed with an exception.

**Comment by david-allison** [comment]
Proposal: hold off on other merges for a while, get it green + rebased on `HEAD` + get it in, or it'll forever be red

**Comment by mikehardy** [comment]
Agreed - rebased, reformatted (again), repushed, hopefully it goes green :-)

**Comment by mikehardy** [comment]
Now I need to local pull / rebase / check PRs for a little bit until this is in place in everyone's PR base commit history...

**Pull request merged**
