### PR TITLE
fix: add merged pr to milestone

### LINKED ISSUE #10410: Automate process of adding merged PR to milestone and removal of labels
Might be useful to automate this in the longer-term, either with a check to confirm that all merged PRs have a milestone, or a bot reminder to set a milestone once merged

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/10353#issuecomment-1044721187_

### PR DESCRIPTION
**Pull request by krmanik**
## Purpose / Description
Fix, add merged PR to milestone. 

## Fixes
Fixes #10410 

## Approach
I have tried many implementation and only implementation in this PR works. I have used `curl` to send POST request using GITHUB_TOKEN to assign milestone to merged PR. I have used `pull_request` instead of `pull_request_target` because only that work. 

## How Has This Been Tested?
It works on my repository but it needs to tested here. 

## Learning (optional, can help others)
https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — COMMENTED** [review]
What happens if the PR already has the label

**Comment by krmanik** [comment]
> What happens if the PR already has the label

In that case also the milestone will be added for merged PR.

**Comment by mikehardy** [comment]
At least for this merge it gave me the dreaded

>   "message": "Resource not accessible by integration",

...is that because it was not in main yet? Could have been, I have another PR ready to go for a check

**Comment by mikehardy** [comment]
Nope, from #10735 merge same error

https://github.com/ankidroid/Anki-Android/runs/5872608218?check_suite_focus=true

I really think it must be pull_request_target not pull_request or the github token doesn't have permission

**Comment by krmanik** [comment]
I have tried `pull_request_target` and it doesn't work. I will check other implementation.

**Comment by mikehardy** [comment]
Such a pain in the butt! I'm surprised how hard this one is but I don't know any other tricks either. I guess we will all learn something...

**Pull request merged**
