### PR TITLE
Play more files as video

### PR DESCRIPTION
**Pull request by ospalh**
Extra test to determine whether [sonud:NN] is a video: Ask  URLConnection to guess the type.

Some systems can play e.g. avi videos, some can’t. This [asks](https://developer.android.com/reference/java/net/URLConnection.html#guessContentTypeFromName%28java.lang.String%29) `URLConnection` if that class thinks a [sound:NN] file is a video along with the old test.

Tested with Android 4.2 (plays .avi as videos with this change) and Android 2.2. (Doesn’t know about AVI. Can’t play (some) AVIs neither as video nor as sound, same as without this change.)

This is in response to [issue 2669](https://code.google.com/p/ankidroid/issues/detail?id=2669).

### CODE REVIEW

**Comment by timrae** [comment]
Thanks, good idea!

**Comment by timrae** [comment]
It seems this method doesn't like kanji in the file name... We probably have to normalize them beforehand:

0	java.lang.StringIndexOutOfBoundsException: length=45; regionStart=42; regionLength=-19
1	at java.lang.String.startEndAndLength(String.java:504)
2	at java.lang.String.substring(String.java:1333)
3	at java.net.DefaultFileNameMap.getContentTypeFor(DefaultFileNameMap.java:38)
4	at java.net.URLConnection.guessContentTypeFromName(URLConnection.java:680)
5	at com.ichi2.libanki.Sound.playSound(Sound.java:281)
6	at com.ichi2.libanki.Sound.playSound(Sound.java:260)
7	at com.ichi2.libanki.Sound.playSounds(Sound.java:246)
8	at com.ichi2.anki.AbstractFlashcardViewer.playSounds(AbstractFlashcardViewer.java:2159)
9	at com.ichi2.anki.AbstractFlashcardViewer.updateCard(AbstractFlashcardViewer.java:2109)
10	at com.ichi2.anki.AbstractFlashcardViewer.displayCardQuestion(AbstractFlashcardViewer.java:1903)
11	at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:381)

**Comment by timrae** [comment]
Actually the Japanese text was fine, I somehow had a filename like this:
`ひじ - <spanstyle="color:#959595;">肘</span>.mp3`

**Comment by ospalh** [comment]
Looks like i have to add a try/catch then.
But the docs don't say that that function throws anything. OK, it says you should put in a `source URL`, i guess that implies that you should do some clean-up.
Then again, a `#` should be fine in an URL, some other stuff is not.

Maybe a general "catch anything and return" would work. *Playing* a "file" with your name would have failed later, anyway.

**Comment by timrae** [comment]
Fixed in #884

**Comment by ospalh** [comment]
I'm not sure if i like your fix there. Isn't `#` allowed in file names?

**Comment by timrae** [comment]
I don't remember if it's allowed in the filename or not, but I guess it's not allowed to appear before a `/` in a URL. That method is presumably only looking at the extension so maybe we could just give it everything after the last `.` instead? I don't like the try/catch approach much

**Comment by timrae** [comment]
I just checked that's working

**Comment by ospalh** [comment]
> I don't like the try/catch approach much

Maybe i am thinking more pythonically, but i like it in general.

Maybe somebody will invent another pathological "file name" without # that is confusing the guessing function.

**Comment by timrae** [comment]
See better fix in #884

**Comment by timrae** [comment]
> Maybe somebody will invent another pathological "file name" without # that is confusing the guessing function.

Yeah I agree that the `replace("#","")` approach wasn't great, thanks for pushing that point.

**Pull request merged**
