### PR TITLE
fix: NPE fix in note editor

### LINKED ISSUE #16569: [BUG]: Copying a note and then saving it now results in a NullPointerException
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Pre-requisites: 2 decks, the first of which has at least one note (the second can as well but does not have to)

1. Open the card browser
2. Click on a note
3. Change the value of a field
4. Click the 3 dot menu in the upper right
5. Click copy note
6. Change the deck
7. Click the checkbox to save the copy to the second deck
8. Click the checkbox again to save the change to the original note to the first deck

### Expected behaviour

- The modified note should exist in the first deck
- A copy of the modified note should exist in the second deck

### Actual behaviour

- A copy of the modified note exists in the second deck
- Step 8 (saving the change to the original note to the first deck) shows a popup with the following text

**Error**
java.lang.NullPointerException

OK [right aligned]

Pressing OK and clicking the checkbox again results in the same error.

### Debug info

```text
AnkiDroid Version = 2.18.3 (e74513bdd21d521a7939a8b1f781123fb3ee2025)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 6a Build/AP1A.240505.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

ACRA UUID = dcd2b7f9-83a3-4437-a9ee-ced7c357e85b

FSRS Enabled = false

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

This has been happening since at least version 2.18.1 (possibly 2.18.0 - I don't remember). I submitted a crash report in-app earlier today for this issue.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by shrutigitte**
## Purpose / Description
This PR fixes a null pointer exception

## Fixes
* Fixes #16569 

## Approach
Instead of comparing the reference we are comparing actual value

## How Has This Been Tested?
Google emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by criticalAY — COMMENTED** [review]
CI is failing

**Comment by Arthur-Milchior** [comment]
It would be really nice if you had a single commit. And you could write in its commit message what is done.

I trust you that it repairs the bug (I've not yet tested, but someone will do it before it's merged). But I don't understand why this is the right solution, and would love you to explain why it is the right one.

It would be nice if you could state which variable wall null when the NPE was raised. I ugess it's newModel, given it's the only one you changed.
Then it'd be nice if you could also explain why it was null. I intuitively would expect `currentlySelectedNotetype`  to always return a non-null value. 
Adding documentation to explain when it returns null and when it is non-null would be very helpful actually for anyone reading our code source.

And either it would be nice to ensure that it's `null` less often. So that we don't risk another bug with the same cause later.

**Review by david-allison — CHANGES_REQUESTED** [review]
It would be great to have a regression test here. I suspect there's a much easier fix

**Comment by Arthur-Milchior** [comment]
@soCallmeAdityaKumar I'm sorry, but I fear you didn't investigate the actual cause of the issue.
I did and created #16730 to actually solve it while keeping the expected behavior. So I fear we can close this PR

**Pull request closed without merging**
