### PR TITLE
Screenshot in hindi language

### LINKED ISSUE #10091: Use fastlane for automated locale screenshots
The project has screenshots of the app in various languages. But it did not have in the Hindi language.
So I would like to add screenshots in hindi language.

### PR DESCRIPTION
**Pull request by jaiakash**
Screenshot of app in Hindi language. Fixes  #10091 

Approach
Screenshot was took from Poco X3 Pro

### CODE REVIEW

**Comment by ShridharGoel** [comment]
Why is the folder name `hi-ID`? Shouldn't it be `hi-IN`?

**Comment by jaiakash** [comment]
Yeah my bad, changed it now.

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
These screenshots are not named consistently compared to the other screenshots in the `screenshots` folders.

Maintainers: how are these screenshots sent to the Play Store? Do we need to do anything else here?
We should ideally have some documentation on this near the screenshots folder.

**Comment by ShridharGoel** [comment]
In `edit.jpg`, can you show correct (meaningful) text in the fields?

**Comment by jaiakash** [comment]
Yeah, sure I will make necessary changes and send pr asap.

**Comment by jaiakash** [comment]
I have named the screenshots according to content and other language screenshots. And added `edit.jpg` with meaning full text.

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
I've added questions on the [original issue](https://github.com/ankidroid/Anki-Android/issues/10091#issuecomment-1010555840) which I believe should be resolved first.

Feedback:

* The screenshot content isn't consistent with the existing screenshots
* The screenshots aren't using the system default font
* The screenshots should be using Android's "Demo Mode" to set the battery to 100% and remove notifications

**Pull request closed without merging**
