### PR TITLE
Update DeckPicker.java

### PR DESCRIPTION
**Pull request by SSTG**
## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
Hi @SSTG 
What's the purpose of this change? 

You'll need to trim down the PR diff to what your intended code change, and fill out the PR template before this is reviewable.

**Comment by SSTG** [comment]
Hey @david-allison-1  I don't know how but the commit shows a lot more changes than I made. I think I made only 5 changes. Let me just correct it

**Comment by david-allison-1** [comment]
Thanks! 

Check to see if your `master` branch is up to date with ours, that seems to be the likely cause of the issue

**Comment by SSTG** [comment]
Yeah I think that was the issue. I have made another PR with the issue corrected. With the PR, I have tried to solve issue #9961

**Comment by david-allison-1** [comment]
Okay, closing this one as superseded by #9961

**Comment by david-allison-1** [comment]
Closing this as superseded by https://github.com/ankidroid/Anki-Android/pull/9992

**Pull request closed without merging**
