### PR TITLE
TagsDialog is now independent from StyledDialog.

### PR DESCRIPTION
**Pull request by brunodea**
Also, fixed issue 2168: "Make selected tags show up at the top of the tag list".

@timrae I saw the discussion thread about this issue, but couldn't really understand. So, I fixed the issue based on its description.

### CODE REVIEW

**Comment by timrae** [comment]
Excellent! Thanks so much, you are amazing!  Can you please delete `StyledDialog.java`? Also, I have one suggestion to redesign the dialog, let me know what you think (of course you're welcome to refuse if you don't like it, or don't have time):

Replace the upper select all CheckBox, and lower "Add/ filter tags" bar with a [Toolbar](http://android-developers.blogspot.jp/2014/10/appcompat-v21-material-design-for-pre.html), and add the 3 items to it: (search, select all, add new tag). Search can use `SearchViewCompat` and there are standard icons for the others (ic_select_all_black_24dp, ic_add_black_24dp) [here](https://github.com/google/material-design-icons/)

**Comment by timrae** [comment]
Or actually maybe style the toolbar blue like the main actionbar, and use the white version of the icons

**Comment by timrae** [comment]
I will go ahead and merge this, please consider the other requests for a separate PR :+1:

**Comment by brunodea** [comment]
@timrae good idea, it will defenitely look better with a Toolbar. Tomorrow I think I can start working on it and also delete the `StyledDialog.java`.

**Comment by timrae** [comment]
Thanks!!! If we use a toolbar, you can get rid of the hint Toasts for adding tags too. I think we should also change the String of the positive button from "Select" to "OK" when coming from add note / edit note screens.

**Pull request merged**
