### PR TITLE
Added card repositioning

### PR DESCRIPTION
**Pull request by JordanCleeve**
Can reposition the card from the note edit context menu

### CODE REVIEW

**Comment by Alphyn-gunner** [comment]
Wow, thanks! That's a feature I missed a lot.

**Comment by mikehardy** [comment]
I checked this out locally and built it. The build works, and the new user interface dialog seems to function but what results should I expect?

For example, If I have a deck of 30 cards, none of which are new, and I reposition the first one to "2222", then go back to the deck picker, and finally go back into the deck I just repositioned the card in - I see the same card I just repositioned. Shouldn't it be last now?

Also, from a translation perspective, maybe "New card position: " is easier than a phrase with a variable in it "Reposition card to x position", but I'm no expert there.

**Comment by Alphyn-gunner** [comment]
Repositioning only works for new cards. For old cards use reschedule.

**Comment by mikehardy** [comment]
Ah, thank you. I was misunderstanding the feature. In that case, I can say it works! 

My test: I used the card browser, sorted by due date and showed number of reviews in the second column to make sure I was working with new cards and I could see the order. Then I repositioned a few cards to 1 and they always moved to the top in the sort order, so at least I am assuming this works. 

Thoughts: The text string "Reposition card" is consistent with the desktop version (I checked), and that is a good thing, but if this only works on new cards others could be surprised, as I was, when it doesn't seem to work. Could it be "reposition new card" or, could it check if the card is new and if it is not then there could be an error message saying it only works on new cards, and a suggestion to use reschedule for already viewed cards. 

Docs: Also, a PR for the docs to add a note about this would be useful, so if this is accepted we can point people there if they have questions (there is an example in the Anki desktop manual here https://apps.ankiweb.net/docs/manual.html if you search for reposition and use the second part) - I think that's here https://github.com/ankidroid/ankidroiddocs

**Comment by JordanCleeve** [comment]
Thanks for the system testing Mike.
You have also raised some good points I have overlooked.
I have pushed a new build with some clear naming, more inline with the desktop version and now only show the context menu option on new cards.

**Comment by mikehardy** [comment]
Cool - I looked at the comment and the changes look nice, if I had seen these the first time I don't think I would have had any confusion (meaning: shouldn't be a big support problem? I think?) and I already tested it and know the functionality works. I'm in no position to say yes or no but it does seem to add a feature present on other Anki platforms and it seems to work based on my testing, so if @timrae likes it, it could work

Have you considered adding (or copying from the Anki desktop docs really) a PR for the docs to describe / explain it? I put a link to the same in my previous comment

**Comment by timrae** [comment]
Thanks for this @JordanCleeve and thanks for testing this @mikehardy. The code looks good, so I'm happy to merge knowing that it's been independently tested.

**Comment by JordanCleeve** [comment]
Awesome! @mikehardy I will also do a PR for the docs at some point as you suggest.

**Pull request merged**
