### PR TITLE
NF: remove duplicate "All decks"

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Those are so similar that the "card browser" one is already used in the statistic window

### CODE REVIEW

**Comment by david-allison-1** [comment]
Should we move this into `02-strings`? Or flag it that it should be moved at a later date?

**Comment by Arthur-Milchior** [comment]
My understanding of crowdin is that a string is associated to an id and to a file. So moving a string to another file would probably require to retranslate everything.
In theory, we could solve this relatively easily by downloading languages, making the changes in all languages simultaneously, and uploading all languages back. However, I fear that this would still break the link between screenshot and the ressource's id.

The script would not be so hard to change to  add this feature. Doing so would have a second advantage, it would allow to correct plenty of ids, such as id with typos, or ids that are more specific than the real use of the ressource.

**Comment by mikehardy** [comment]
I find the string placement to be for the most part arbitrary and meaningless. I wish crowdin had them all in one file sometimes. Moving the string would cause a re-translation need for all the translations, and we don't have any tooling to avoid that re-translation but as Arthur said it could/should be possible. I'd take a move accompanied with a PR that added the feature to the translations script though

**Review by david-allison-1 — APPROVED** [review]
Eh, if it's hard then maybe flag it for later review, I doubt we'll get there.

This might as well go in.

**Comment by Arthur-Milchior** [comment]
In theory, it's not hard at all. The main downside is that I've not a single way to run test. I can't run the upload on my computer, so each test would need to create a PR, merge it, run the uploader, and check whether we have the correct result.
I don't feel I'd want to write code with so little benefits and that would take that long to test. Especially if I'm not 100% sure that all translation would keep their history in crowdin.

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
