### PR TITLE
build(deps): bump backend to 0.1.29-anki23.10.1

### PR DESCRIPTION
**Pull request by mikehardy**
Just heading towards a release, and I like to get all the possible things in there - so getting the backend bump in as well even though it is nominally dev-only

### CODE REVIEW

**Comment by user1823** [comment]
Does this mean that the next alpha of AnkiDroid will include all the commits that have been merged into Anki till now?

**Comment by david-allison** [comment]
Anki-Android-Backend is using https://github.com/ankitects/anki/commits/fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf (23.10.1) + a few extra commits. This shouldn't have been changed from the previous alpha

You can check the current version of the Anki submodule here: https://github.com/ankidroid/Anki-Android-Backend

**Comment by user1823** [comment]
> This shouldn't have been changed from the previous alpha

Then, I don't get what is the backend update mentioned in this PR all about.

Also, I am not a dev due to which, verifying such things can be difficult for me. So, can you just confirm whether the next alpha would include the above-mentioned FSRS update commit or not?

**Comment by david-allison** [comment]
It doesn't contain the above commit.

`Anki-Android-Backend` is the library which allows AnkiDroid to use Anki Desktop's code

It exists so new contributors to AnkiDroid don't need to deal with the additional steps to building Anki Desktop, and can get running and contributing quickly.

This update affects the code which defines how we connect to Anki, rather than updating the version of Anki which was used.

Specifically: https://github.com/ankidroid/Anki-Android-Backend/commit/94b201b19f64b294455693023a0ad3f46bb0add0 - This allows our automated tests to run without any Android code, which can lead to a 100x speedup

**Comment by mikehardy** [comment]
In general, we only update the actual version of anki packaged inside Anki-Android-Backend when it is a real Anki release, any other updates will be something like the above where it is for AnkiDroid but is not an "anki" change

As a concrete example, the last "real" backend update with anki change was as mentioned by David when we adopted 23.10.1

I'm not sure what the release plan for Anki upstream is, but whenever there is a 23.11 or 24.1 (or maybe a 23.10.2...) and it is a real tagged version, then we'll adopt it here and release AnkiDroid with it, but not until then

**Comment by user1823** [comment]
Thanks both for clarifying.

**Pull request merged**
