### PR TITLE
Removed recursive template processing.

### LINKED ISSUE #6295: Cloze deletions not treated consistently with desktop when included as non-cloze placeholder
###### Reproduction Steps

1. Define a card which contains a standard placeholder, as `{{Text}}`
2. Create a note of that type with a cloze deletion in the value for that field, as `All {{c1::men}} are mortal.`
3. Study the card

###### Expected Result
I expect the field to display on the card the same way Anki for desktop does it, with the cloze deletion unprocessed, as `All {{c1::men}} are mortal.`

###### Actual Result
All cloze deletions are dropped from the card with no indication anything was elided, as `All  are mortal.`

###### Debug info
AnkiDroid Version = 2.10.2

Android Version = 10

ACRA UUID = 0c27e711-8469-4257-8884-62f1a7fd4cb1

###### Debug info (desktop version, for comparison)
    
    Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=False sv=2
    Add-ons, last update check: 2020-05-28 10:19:00
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    
    
    ===IDs of active AnkiWeb add-ons===
    
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Notes
I recognize that people will not usually do this on purpose. However, the inconsistency can still cause problems, or at least lead to confusion. On the occasion that someone does do this on purpose (as I did), simply eliding of all clozed content is probably not ever going to be the intended result, and it is in any case a result not reproducible on desktop.

### PR DESCRIPTION
**Pull request by mikehardy**
This brings the behavior closer to Anki Desktop.

This is actually #6716 - but that one had issues because the github welcome action made it so travis wouldn't run, then I ran inadequate git commands

It's the same single commit though

@Arthur-Milchior you were in favor of this? You are closer to template processing than anyone

If this passes CI I can merge

Fixes #6295

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
@colin-p-hill  there seems to be a null pointer exception occurring a lot with your PR. Do you want to correct it ?

**Comment by Arthur-Milchior** [comment]
The problem is that render_some_tags returns null to indicate no change was done. So either test for null when calling render_some_tags, or change `render_some_tags` so that it always return the result

**Comment by mikehardy** [comment]
And I'm really sorry for hashing up the PR first with a failed attempt at a welcome bot so the test didn't run, then the wrong git commands. Please feel free of course to take the commit and put it on a proper branch in your clone and open a fresh PR. Note that it's best practice in git to not develop on master, even in your own fork, that's why I couldn't directly fix the problem (I couldn't push to master in your forked repo - it's a protected branch)

**Comment by mikehardy** [comment]
Superceded by #6855

**Pull request closed without merging**
