### PR TITLE
Fix Flaky Test: SchedV2Test.test_moveVersions

### LINKED ISSUE #6814: CI Failure: SchedV2Test.test_moveVersions
```
com.ichi2.libanki.sched.SchedV2Test > test_moveVersions FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Caused by:
        java.lang.AssertionError: expected:<50> but was:<51>
            at org.junit.Assert.fail(Assert.java:89)
            at org.junit.Assert.failNotEquals(Assert.java:835)
            at org.junit.Assert.assertEquals(Assert.java:647)
            at org.junit.Assert.assertEquals(Assert.java:633)
            at com.ichi2.libanki.sched.SchedV2Test.test_moveVersions(SchedV2Test.java:1564)
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Caused by changing scheduler - which removed our time dependency

Uses code from #6812 

## Fixes
Fixes #6814

## Approach
Extract method and use it

## How Has This Been Tested?
⚠️  Inconclusive - unit tested, but they passed previously

## Learning 
Time is hard

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
Moving to draft - this will need to be rebased against master (and reproed) before we conclude that things are fixed. I don't know why this is happening currently

**Comment by david-allison-1** [comment]
I plan to reopen this, but don't want to spam Travis with test pushes

**Comment by david-allison-1** [comment]
This XOR #6816 should be merged

**Comment by david-allison-1** [comment]
Reviewers: I've rebased this onto master, also confirm that was done correctly

**Comment by Arthur-Milchior** [comment]
I'm surprised that we have `replaceSchedulerForTests` in Col. I thought @mikehardy you wanted no code which is here only for tests and nothing else in the main code. This was one of the reason for the complexity of having android test in a separate folder.


LGTM

**Comment by mikehardy** [comment]
> I'm surprised that we have `replaceSchedulerForTests` in Col. I thought @mikehardy you wanted no code which is here only for tests and nothing else in the main code. This was one of the reason for the complexity of having android test in a separate folder.
> 
> LGTM

Separate folders is an Android project artifact, there are reasons for that because it separates unit, vs instrumented tests and the compile classpaths etc are quite different

I'm willing to have some things in main that enable tests, especially when it's something as integral as how time is handled. I think of these more like the factory adaptations which are basically de-coupling for test overrides in our use cases. They'd be unnecessary except for tests and could be named 'getSqliteProviderSoItIsTestable' as easily as 'getSqliteProvider' etc.

Design/architecture of software is always a tension, and this could be wrong and we change it in future, we'll see. Good for now though and when/if it passes CI it unblocks master to finish the current merge-fest for an alpha release

**Comment by mikehardy** [comment]
Needs a straightforward de-conflict, David's aware. Travis super backed up from the Arthur PR frenzy anyway :-)

**Comment by david-allison-1** [comment]
@Arthur-Milchior I'm about to rebase this branch

**Comment by david-allison-1** [comment]
Should be good to go

**Comment by mikehardy** [comment]
It is now 15th in the build queue :open_mouth:  - thanks David

**Comment by Arthur-Milchior** [comment]
> Needs a straightforward de-conflict, David's aware. Travis super backed up from the Arthur PR frenzy anyway :-)

Sorry, I did removed a lot of conflict. Is there any way to reorder the queue ? to state what is priority to Travis ? Because while I like my PR to have no conflict, there is no urgency here.

(For context, if I wait a lot to remove conflict, then I'll need to remove a lot of different conflict; which is hard. If I remove conflict as soon as they occur, it means that I'll only need to deal with one kind of change, such as adding type annotation, or changing the path of a class, it's far easier to ensure that the rebase is correct)

**Comment by mikehardy** [comment]
No worries @Arthur-Milchior - this is an unusual state I think and okay to just let Travis chew through it
Honestly it motivates me a bit to review the PRs that are "in the way" (from the perspective that I am impatient only), so that if they still need something I can cancel their builds. You have probably noticed me doing that a lot this morning, and in that sense it creates forward progress, so maybe it's a positive :-)

**Pull request merged**
