### PR TITLE
rot

### PR DESCRIPTION
**Pull request by Arthur-Milchior**

### CODE REVIEW

**Review by david-allison — APPROVED** [review]

**Comment by oyeraghib** [comment]
I was just curious what is `NoteFieldDecorator` is for ?

**Review by mikehardy — APPROVED** [review]
LGTM

**Comment by mikehardy** [comment]
@oyeraghib I say this in the sincere spirit of fun: it is much much much more fun to figure it out for yourself. Also, it is not *that* hard to figure out

**Comment by oyeraghib** [comment]
Sure :))

**Pull request merged**
