### PR TITLE
open card browser and search using deep links

### LINKED ISSUE #11885: Intent/Activity API for opening the Card Browser
**Is your feature request related to a problem? Please describe.**
At the moment, I have a website with my relevant anki notes to things like `nid:1238753945`. I have to select the text (which is rather painful on mobile) and click "Card Browser" in the context menu to go to it.

**Describe the solution you'd like**
An intent API for navigating to the Card Browser with an action parameter filled in as the search query.
Since you can deep-link to intents with a specially crafted [hyperlinks](https://developer.chrome.com/docs/multidevice/android/intents/#examples) in web apps, this would make the experience _much_ nicer. I could make the `nid:1238753945` text a hyperlink that automatically opens AnkiDroid to the right note when tapped.

**Describe alternatives you've considered**
Since it's not possible to use the native API from a website, I tried to see if context menu intents can already be triggered from a hyperlink. Unfortunately, I'm not very experienced in android development and couldn't figure out how to craft that intent hyperlink by looking at the `AndroidManifest.xml`.
If it's already possible, that would be great! If not, I'm hoping it would just be a small change to the way the intent is exported.

### PR DESCRIPTION
**Pull request by krmanik**
## Purpose / Description
Open card browser from another app with search query 

## Fixes
Fixes #11885

## Approach
1. Create intent-filter in Cardbrowser activity with `scheme="anki"`, `host="x-callback-url"` and `path="/cardbrowser"`
2. Get intent data using `getQueryParameter`

## How Has This Been Tested?
Tested using chrome and https://krmanik.github.io/deeplinks-intent-test/

1. Load the page on chrome browser on android device
2. Input the fields to make intent like this for searching `test`
```
intent://x-callback-url/cardbrowser?search=test#Intent;scheme=anki;package=com.ichi2.anki;end
```
3. The webpage creates `a` tag and href value with above intent
a) Searching nid

     ```
     <a href="intent://x-callback-url/cardbrowser?search=nid:1658178059263#Intent;scheme=anki;package=com.ichi2.anki;end">Search nid </a>
     ```
    b) Searching `some text`
     ```
     <a href="intent://x-callback-url/cardbrowser?search=some text#Intent;scheme=anki;package=com.ichi2.anki;end">Search text</a>
     ```

4. Clicking on `Open action` will open the card browser with `search`
5. Also following can be used to test
     a) Using adb
     ```
     adb shell am start 
          -W -a android.intent.action.VIEW 
          -d "anki://x-callback-url/cardbrowser?search=nid:1658178059263" com.ichi2.anki
     ```
     b) Using window.location
     ```
     ankiUrlScheme = "anki://x-callback-url/cardbrowser?search=nid:1658178059263"
     document.location = ankiUrlScheme;
     ```

</img>

## Learning (optional, can help others)
https://developer.android.com/training/app-links/deep-linking
https://developer.chrome.com/docs/multidevice/android/intents/

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by krmanik** [comment]
The `x-callback-url` only supported on iOS devices. I have updated it to match the url scheme but still there are differences in calling the url scheme / deep-links.

In safari or chrome for iOS devices, following can be used. Also only `addnote` supported on AnkiMobile currently.
```js
ankiUrlScheme = "anki://x-callback-url/addnote?profile=User%201&type=Basic&deck=Default&fldFront=front%20text&fldBack=back%20text"
document.location = ankiUrlScheme;
```

But for android it is different.
```
intent://x-callback-url/cardbrowser?search_query=test#Intent;scheme=ankidroid;package=com.ichi2.anki;end
```
Also in docs we have to mention that `x-callback-url` used to match the [AnkiMobile URL scheme](https://docs.ankimobile.net/url-schemes.html)

**Review by Koudinka — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
That looks surprisingly easy / "works as documented", and though the feature (search here, vs add note etc on ios) varies from iOS it has compatible construction. This looks like a style with lots of future potential to me.

**Comment by mikehardy** [comment]
Hey @dae if you have a minute, this is an ecosystem cross-compatibility thing. My hope is that all URLs will work on all platforms and I'd love it if you could confirm we're meeting that goal with our support here

**Comment by dae** [comment]
> ankiUrlScheme = "anki://x-callback-url/cardbrowser?search_query=nid:1658178059263"
document.location = ankiUrlScheme;

That looks like the syntax AnkiMobile uses, though please note it only supports adding notes at the moment, and does not support searching. 

Minor bikeshedding on the URL - how about this instead?

anki://x-callback-url/browser?search=nid:1658178059263

**Comment by mikehardy** [comment]
> it only supports adding notes at the moment, and does not support searching

But now that you're aware adding this we can stay in sync when/if you add searching :-). Good to hear we're on-target and I agree "search" is unambiguous enough while being shorter and reading better for non-developers

**Comment by BrayanDSO** [comment]
> anki://x-callback-url/browser?search=nid:1658178059263

I like the `cardbrowser` → `browser` change too

**Review by mikehardy — APPROVED** [review]
Looks great!
All of Damien's URL suggestions ingested now

**Review by BrayanDSO — APPROVED** [review]
LGTM too. Awesome feature

**Comment by mikehardy** [comment]
The emulator tests are erroring with different errors but every time I look at them it's the system going out of memory, I'll see if I can tune that quickly, the false-negative rate is atrocious. Thanks for the restart

**Pull request merged**
