### PR TITLE
feat: Display custom flag names

### LINKED ISSUE #16204: Display Renamed Flags
https://github.com/ankitects/anki/commit/9816227b5caa86d7edbcaec7b9697aefbfead2a7

```python
    def rename_flag(self, item: SidebarItem, new_name: str) -> None:
        labels = self.col.get_config("flagLabels", {})
        labels[str(item.id)] = new_name
        self.col.set_config("flagLabels", labels)
        item.name = new_name
        self.refresh()
```

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
AnkiDroid to use flag  names from col i.e. if user renames it then that name should be visible instead of hardcoding the string.
This PR intends to commit the changes that were reverted which were originally made in #16218

## Fixes
* Fixes #16204

## How Has This Been Tested?
Google emulator 
image

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
```
> Lint found errors in the project; aborting build.
```

**Review by david-allison — COMMENTED** [review]
This should ideally be two commits:

* reapply your PR
* Apply PR2 which adds the flag names

**Comment by david-allison** [comment]
I've fixed this up and optimized

image
image
image

**Review by david-allison — APPROVED** [review]

**Review by lukstbit — APPROVED** [review]
LGTM, team effort gets the PR merged.

**Pull request merged**
