### PR TITLE
Adding kotlin-test-junit to androidTestImplementation

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Following https://stackoverflow.com/a/55218573/414269 It ensures the IDE don't show error on `import kotlin.test.junit.JUnitAsserter.assertNotNull`

### CODE REVIEW

**Review by david-allison — APPROVED** [review]

**Comment by Arthur-Milchior** [comment]
Closed. #12353 is superior

**Comment by david-allison** [comment]
Disagree

**Comment by Arthur-Milchior** [comment]
Then I reopen it. But I'd appreciate @david-allison if you could explain your disagreement.

**Comment by david-allison** [comment]
Taking one of the most important unit test classes in the project and making the assertions inconsistent with the rest of the project is not a good idea. 

It's good to be consistent, especially when working with assertions.

**Comment by BrayanDSO** [comment]
Maybe add it to `testImplementation` too would be good.

Uninformed comment: As we are on all Kotlin now, maybe the `org.junit` dependencies can be dropped and use `kotlin.test.junit` everywhere

**Review by lukstbit — APPROVED** [review]

**Comment by Arthur-Milchior** [comment]
> Not informed comment: As we are on all Kotlin now, maybe the `org.junit` dependencies can be dropped and use `kotlin.test.junit` and `kotlin.test.junit5` everywhere

According to https://kotlinlang.org/api/latest/kotlin.test/kotlin.test.junit5/ kotlin.test.junit5 is done
> by delegating them to org.junit.jupiter.api.Assertions class.

I'll admit I'm surprised, I'd assert, given the name, it delegates to org.junit5

So I don't see any interest in using kotlin.test in any case

**Comment by BrayanDSO** [comment]
`org.junit.jupiter` is junit5

**Pull request merged**
