### PR TITLE
Unit Test : activity can only closed by continue button

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
Test should be run locally before pushing,btw `testActivityCantBeClosedByBackButton()` is failing in your case

**Comment by criticalAY** [comment]
```
 fun testActivityCantBeClosedByBackButton() {
        ActivityScenario.launch(PermissionsActivity::class.java).onActivity { activity ->
            activity.onBackPressedDispatcher.onBackPressed()
            assert(activity.isFinishing)
        }
    }
```

updating the code to this will get it fixed but I don't think this test is required

**Comment by lukstbit** [comment]
@SanjaySargam Please don't open pull requests if they aren't in a reviewable state as this creates clutter in the list of PRs for reviewers.

**Comment by SanjaySargam** [comment]
Test passed. Opening PR

**Comment by SanjaySargam** [comment]
@lukstbit Will you please reopen PR? I want to push commit ( test case passed )

**Comment by david-allison** [comment]
Please open a new PR, this PR can't be reopened as it was force pushed or recreated

**Comment by SanjaySargam** [comment]
> Please open a new PR, this PR can't be reopened as it was force pushed or recreated

Ok

**Pull request closed without merging**
