### PR TITLE
NF: remove Spannable from a string where it is never used

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
My goal is to preload card as much as possible. This mean pre rendering html before actually needing to show it, in particular mathjax and loading media. This also mean that I need to deal with sound outside of the AbstractFlashCard Viewer. I believe that doing simple cleaning is a good first step to attain this goal easily.

My point is that I'm not just doing refactoring for the sake of cleaning. I am doing it because I've got a goal in mind and that I expect that this will help reach it.

In this case, the cleaning is simply avoiding a constructor / toString when it is never useful

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
You told me how to time java. I could try to get it in, even if I am less intrinsically motivated (I mean, I tend to prioritize having ankidroid quick on my phone). But right now, I'm looking at loading image and mathjax, which is not done in java itself. So I don't see how we could measure this part

**Comment by mikehardy** [comment]
The card.js does a WebView callback which hooks in to our java code when the card is done loading, I think that would be the mechanism to close out the timer pair and generate a timing analytics hit if that's the goal

**Comment by mikehardy** [comment]
@Arthur-Milchior pending conflict removal then can merge

**Comment by Arthur-Milchior** [comment]
Done

**Pull request merged**
