### PR TITLE
Update backend version to 2.1.57

### PR DESCRIPTION
**Pull request by dae**
Requires https://github.com/ankidroid/Anki-Android-Backend/pull/268

This includes a change that will likely fix the "permission denied" errors users were getting when removing media manually/during sync.

2.1.56 revamped cloze deletion to include support for nested clozes, and includes extra information in the generated HTML to identify unexpanded clozes/extract their original content. This breaks the unit tests in this repo that expect the cloze deletions to follow a particular format, like what happened in https://github.com/ankidroid/Anki-Android/pull/12897/files, but more thoroughly this time :-) To work around this I've just disabled the tests in the new schema path - while you could potentially task someone with updating them as a "good first issue", I don't think they're adding much value in the new path, as the backend has its own unit tests for these already, so they're effectively testing the same thing twice. 

I noticed that the version number in build.gradle referred to a script that was no longer relevant, so I've removed it.

Some of Oakkitten's previous changes to the custom sync preferences have
had to be redone, as the backend now expects the base URL instead of
individual settings for collection and media sync.

### CODE REVIEW

**Comment by dae** [comment]
Note: I've left the 2.1.56 update as a separate commit for clarity, but this PR should be squash-merged, as there was never a 2.1.56 backend release, and the commit will fail to build.

**Comment by mikehardy** [comment]
Thanks for these and the ongoing help with the backend - finishing up a for-pay delivery crunch at the moment but will hopefully have ability to swing the attention beam back this direction and at least get the backend stuff pushed through here this week

**Comment by mikehardy** [comment]
Note for me as much as anyone but maybe useful for others to read, here is how it works:

0) In progress: CI is chewing on main on the related backend PR now
1) When it is done I'll run the action that publishes it so it is out on maven
2) then I do the stage/release thing using the maven central UI
3) then you wait for a few minutes until it is internet-distributed on their public repo
4) then you rerun CI here (ideally close + reopen the PR?) which should show it works
4a) also pull this PR locally and check it on windows / mac / linux

**Review by mikehardy — APPROVED** [review]
A relatively big change for the sync stuff after the work to allow them to be set separately, but also quite simplifying - I am able to sync to ankiweb at least, when testing this locally, which is the primary feature we support. No intention to *break* custom sync server but if it breaks I'm okay with taking fixes as follow-ons vs blocking this as staying current on the backend means we get some other important fixes

Stated differently: LG(Enough)TM - thank you!

**Comment by dae** [comment]
The reason why the backend used to accept separate media and sync endpoints is because the built-in sync server didn't support media, so users had to fall back on a different server or AnkiWeb for syncing media. As of 2.1.57, [this is no longer necessary](https://docs.ankiweb.net/sync-server.html), so there wasn't really anything to be gained by having separate settings for each of them.

**Comment by mikehardy** [comment]
@oakkitten is our champion here - you should be very interested in 2.1.57's new built in sync features then ☝️

**Comment by mikehardy** [comment]
I archived ankidroid/anki - https://github.com/ankidroid/anki/settings - we can always unarchive so it is reversible but I can't imagine we'd go back to a fork unnecessarily? Onwards!

**Pull request merged**
