### PR TITLE
Add fieldNamesForNotes to finder

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description
Main purpose: having libanki similar to Anki's folder Anki.

## Approach
As in Anki

## How Has This Been Tested?

gradlew.
Currently, there is no place in the code using this method (of course, since it's new). 
So no way to test it.
In anki, it's useful to create the search/replace window. 

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Tabs removed. Explained why it can't be tested even if I expect it to be eventually useful

**Comment by timrae** [comment]
Do you have plans to use this function in a future PR?

**Comment by Arthur-Milchior** [comment]
Currently not. It may be useful for a search and replace, but currently I don't believe it's planned to be implemented in the browser

**Comment by timrae** [comment]
Ok thanks for clarification. Closing for now, hopefully we remember if it's needed in the future.

**Pull request closed without merging**
