### PR TITLE
Fixed #8266:Unwanted else-if clause removed DeckPicker

### LINKED ISSUE #8266: "NOT_FOUND_DECK_ID" should be deleted.
"NOT_FOUND_DECK_ID" is used in DeckPicker. It is potentially set as preference for browserDeckIdFromDeckPicker . However this value is never read. Which lead me to suspect that REQUEST_BROWSE_CARDS request is entirely useless. Should be investigated. 

This should wait for #8196 to be merged first so that the constant is not used

### PR DESCRIPTION
**Pull request by haran2248**
## Purpose / Description

NOT_FOUND_DECK_ID removed

## Fixes
fixed #8266 

## Approach

Removes unwanted lines of code

## How Has This Been Tested?
Works on Samsung SM-M025F
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by haran2248** [comment]
Does the Emulator test failing indicate that,that part was required?

**Comment by mikehardy** [comment]
Oh no :-), you appear to have pulled from master during the brief window where I was working on the CI Emulator actions and they were not quite working yet - could you git rebase your changes against current master again so that the E2E tests will pass?

Additionally, use `Fixed #<issue number>` in your PR description (that is: edit it now, to do this) instead of just the issue number. That's special GitHub markdown syntax and cross-links the issue nicely.

**Review by mikehardy — CHANGES_REQUESTED** [review]
looks good to me, I mean, deleting code is obvious as long as it compiles and tests :-), the problem is it needs a rebase as mentioned, sorry about that - it was me working on CI things

**Comment by haran2248** [comment]
> Oh no :-), you appear to have pulled from master during the brief window where I was working on the CI Emulator actions and they were not quite working yet - could you git rebase your changes against current master again so that the E2E tests will pass?
> 
> Additionally, use `Fixed #<issue number>` in your PR description (that is: edit it now, to do this) instead of just the issue number. That's special GitHub markdown syntax and cross-links the issue nicely.

Yes ill work on this

**Comment by Arthur-Milchior** [comment]
Thanks for this correction. Most of my remarks on https://github.com/ankidroid/Anki-Android/pull/8280#issuecomment-803241431 still hold. 
One extra request I had in this case, it would be really great if you could take a look at history and check why this was added. I believe that we used in the past. There is probably a reason why "browserDeckIdFromDeckPicker" is in our codebase. Before removing it, I'd really like to know what occured. Because I can imagine that actually, we wanted to keep it and removed the feature they were contributing to by accident.

If you don't already know git well, my suggestion would be to simply search for "browserDeckIdFromDeckPicker" in git history. I'd use gitk for that, I find out that GUI helps for interaction, but you might also want to take a look at git grep https://git-scm.com/book/en/v2/Git-Tools-Searching

**Comment by haran2248** [comment]
> Thanks for this correction. Most of my remarks on [#8280 (comment)](https://github.com/ankidroid/Anki-Android/pull/8280#issuecomment-803241431) still hold.
> One extra request I had in this case, it would be really great if you could take a look at history and check why this was added. I believe that we used in the past. There is probably a reason why "browserDeckIdFromDeckPicker" is in our codebase. Before removing it, I'd really like to know what occured. Because I can imagine that actually, we wanted to keep it and removed the feature they were contributing to by accident.
> 
> If you don't already know git well, my suggestion would be to simply search for "browserDeckIdFromDeckPicker" in git history. I'd use gitk for that, I find out that GUI helps for interaction, but you might also want to take a look at git grep https://git-scm.com/book/en/v2/Git-Tools-Searching

BDP commit 2
previous browserDeckPicker

I hope this answers the question

**Comment by haran2248** [comment]
I made some error in rebasing im working on it

**Comment by haran2248** [comment]
Can I make a new PR for this,I tried rebasing it,All previous commits were loaded and Im not able to merge them in my machine locally,Android studio is stuck.Is it a problem if I make a new PR for this issue?

**Comment by haran2248** [comment]
I will close this PR.Please check #8297,Sorry for the inconvenience

**Comment by david-allison-1** [comment]
At some point, you should get familiar with rebasing to get out of a bad situation -  it's a great skill to have.

For now, closing this as requested by author

**Pull request closed without merging**
