### PR TITLE
NF: Deck class

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
In my opinion, having a well typed language is wonderful. For example, it can ensure that in my deck/configuration I only put the kind of value I'm expected to put in it. It also allows me to use android studio to quickly search all the places where a deck is renamed.

I ensured that Decks and DConf are still essentially JSON elements; this way we stay really close to upstream, while having the advantages of typing.

I could split this PR if required, but I believe that showing the class ReadOnlyJSONObject makes more sens when we see that multiple class inherits of it.

I've got multiple goals if you accept this PR. 
* Dealing with name more efficiently. In particular, I was interested in caching name map. Having a constant time access from name to deck object. One of the trouble was that it was almost impossible to check whether it is correct because there is no separate type for decks, and the same operation "put" is used for every single JSON operation. Thanks to this PR, we can check really easily whether each operation which change a deck name also update the cache correctly
* Having a proper class for decks allows us, if we want, to save extra datas in it, that are going to be useful but that should not be saved in the JSON. For example, the data for the deck picker could be added to it easily. We already have a class which is used to save the number of cards to review which are new/rev/in learning; we can merge both classes quite easily. (I didn't do it in this PR in order to remain close to JSON)
* It would also allow us to win time by saving a link from children to parent/parents to children and make a lot of operations faster.

The same class "ReadOnlyJSONObject" could also be used for note type and card type. That's really easy to do, but I believed this PR is already big enough.

Testing it by running it on my phone and using ankidroid

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Now that I can run test, I can have a version which works ! thanks

**Comment by Arthur-Milchior** [comment]
I don't understand your last question.

I have no problem with keeping it open waiting for rust to arrive. I doubt that it will be less useful after rust, because as long as we have some java, we'll need a type to represent decks. As long as we use the current database structure, I guess decks will be essentially JSON objects. Adding a better API over the JSONObject will still probably be relevant.

I probably won't work on https://github.com/ankidroid/Anki-Android/pull/6039 before either rust or there is a decision about this PR

**Comment by dae** [comment]
I wholeheartedly agree with you both on the value of static typing, but I don't recommend spending time on this at the moment. The latest desktop alpha is already storing the decks in protocol buffers instead of JSON, and converting it to and from JSON for the legacy Python code. Once the rest of libanki has been refactored/ported, the plan is to provide API calls that return the protobuf instead of JSON, meaning statically-typed getters/setters/code completion will be available for free.

**Comment by Arthur-Milchior** [comment]
Thanks for the update.

**Comment by mikehardy** [comment]
I think we're all agreed in general then that more typing is better, but despite this code existing I agree it doesn't feel like this exact moment is the time for this PR. Rather than let it dangle out there I'm going to close this for now so we can intentionally focus on other things. We'll get typing in over time with the libanki changeover

**Pull request closed without merging**
