### PR TITLE
Move Text to speech API

### PR DESCRIPTION
**Pull request by maxily**
## Purpose / Description
#5021 

## Fixes
Update compatibility for deprecated `TextToSpeech#speak` method

## Approach
This is WIP or "pre-review" purpose for @mikehardy 

## Testing
The TTS functionality works as expected (tested manually) on API 19 and API 28 (emulators)

### CODE REVIEW

**Comment by mikehardy** [comment]
I'll try to look at this later but as I'm on family vacation right now please be patient with me. Does seem simple + easy on first glance at least, shouldn't be too bad :-)

**Comment by milyukhin** [comment]
Actually, hold on, don't spend your time on this just yet. I'll try to make it with the Compat

**Comment by milyukhin** [comment]
I amended the PR (using the Compat this time), could you please take a look again when you have time, no rush at all. Thanks

**Comment by mikehardy** [comment]
This looks right on to me - you confirm it works for you?
@timrae this looks good - a nice clean deprecation fix

**Comment by milyukhin** [comment]
> you confirm it works for you?
Yep, tested manually against pre-deprecated and post-deprecated APIs

**Comment by mikehardy** [comment]
@timrae this is similar to the other one (#5387) I just tagged you in - should be good to go but is not necessary for 2.9, just "regular development" proceeding along

**Comment by timrae** [comment]
This seems isolated enough from the main code to merge now, thank you!

**Pull request merged**
