### PR TITLE
language: Add Kannada

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Add new language

This requires a translation sync afterwards

## Fixes
Related: #8979

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
Blocked on #9000

**Comment by david-allison-1** [comment]
https://www.youtube.com/watch?v=LHqEwIadhO8

**Review by mikehardy — APPROVED** [review]

**Comment by mikehardy** [comment]
looks great - merge at will - I'm on last bits of time before I get on an airplane so I won't be able to check+pick after this I think until some time maybe way later today or weekend

**Comment by david-allison-1** [comment]
> looks great - merge at will - I'm on last bits of time before I get on an airplane so I won't be able to check+pick after this I think until some time maybe way later today or weekend

Enjoy!

**Comment by mikehardy** [comment]
wow it is over 9000!

**Pull request merged**
