### PR TITLE
Fix onActivityResult deprecation for NavigationActivity

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

This PR replaces the deprecated onActivityResult() override in NavigationActivity with the newer ActivityResultLauncher.

## How Has This Been Tested?

Ran the usual tests.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Oh I am sorry to see this (or any of your PRs) going stale - thanks for your patience - you can see we're working but there is a little bit of a higher velocity of inbound "needs review" type work then there is velocity of "time to review". We'll get through it!

**Review by david-allison — APPROVED** [review]
Sorry this sat for so long

**Comment by lukstbit** [comment]
No problem, now I can remove the stale label myself.

**Review by mikehardy — APPROVED** [review]
this looks good, let's get it in - thank you!

**Pull request merged**
