### PR TITLE
undo action button removed from study option fragment main screen

### PR DESCRIPTION
**Pull request by criticalAY**
## Pull Request template
undo action button in study action feature fragment

## Purpose / Description
[Bug] an invalid "Undo" button appears on Deck Overview screen #12277

## Fixes
Button removed from there

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
We want to see the button when it's valid, not unconditionally disable it

**Comment by criticalAY** [comment]
https://user-images.githubusercontent.com/48384865/188297995-218e8403-dd97-42e1-9e31-94bde42b2db5.mp4

The button is visible but not at the screen where we press study in studyoption fragment. Is it not ok ? I have not completely removed it.

**Comment by david-allison** [comment]
> anki.mp4 
> The button is visible but not at the screen where we press study in studyoption fragment. Is it not ok ? I have not completely removed it.

We want the button to be visible in the fragment if it's usable.

**Comment by criticalAY** [comment]
i have made the required changes should i make a new pull request or update this one ?

**Comment by criticalAY** [comment]
I have committed the required changes please check.

**Comment by david-allison** [comment]
`git push --force-with-lease` to the branch, don't open a new PR

**Comment by criticalAY** [comment]
> `git push --force-with-lease` to the branch, don't open a new PR

it says, everything up-to-date

**Comment by david-allison** [comment]
What are your changes doing? It doesn't appear that they'd solve the problem

**Comment by criticalAY** [comment]
> What are your changes doing? It doesn't appear that they'd solve the problem

i attached a clip above after making these changes and the application was working fine and the undo button also started working i removed the actionProviderClass from StudyOptionFragment .xml in action_undo button.

**Comment by david-allison** [comment]
Can we fix this so the undo button still handles RTL correctly?

**Comment by divyansh-dxn** [comment]
Not related to code, but the PR template, you can put a cross inside [ ] like [x] to mark it tick in the checklist.

**Comment by criticalAY** [comment]
> Can we fix this so the undo button still handles RTL correctly?

like what exactly I didn't get in this part?

**Comment by david-allison** [comment]
The drawable is mirrored if in a right-to-left environment

**Pull request closed without merging**
