### PR TITLE
NF: Improve comment on dynamic cards

### PR DESCRIPTION
**Pull request by david-allison-1**
## Learning

Writing is a skill. I've improved

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
You should probably indicate that oDue == 0 iff oDid ==0. So it's suffice to test one to know whether a card is in a dynamic deck or not, assuming nothing broke

**Comment by david-allison-1** [comment]
> You should probably indicate that oDue == 0 iff oDid ==0. So it's suffice to test one to know whether a card is in a dynamic deck or not, assuming nothing broke

I have examples in my collection where this is not the case - hence the need for the original comment.

**Comment by david-allison-1** [comment]
> You should probably indicate that oDue == 0 iff oDid ==0. So it's suffice to test one to know whether a card is in a dynamic deck or not, assuming nothing broke

There were cased in my database where `oDid == 0` does not imply `oDue == 0`. This was the reason for the comment

**Comment by Arthur-Milchior** [comment]
Do you have any idea how it could have occured? I can't recall anything that could cause it, appart from creating a deck at epoch (i.e. timestamp 0)

**Comment by david-allison-1** [comment]
> Do you have any idea how it could have occured? I can't recall anything that could cause it, appart from creating a deck at epoch (i.e. timestamp 0)

No clue, possibly a bad deck which manually created.

**Review by mikehardy — APPROVED** [review]
works for me :-)

**Comment by mikehardy** [comment]
Note - without CI support I'm marking things pending merge, please feel free to do the same @Arthur-Milchior / @david-allison-1 - just mark it pending merge to indicate "I would have merged this, but..."
Then on my laptop I can start all emulators and merge things / pull / run tests at a rate of about one commit fully tested every 10mins

I'd rather do this so that I may be merging something iffy but then I do test it and can stop merging before things get out of hand

**Pull request merged**
