### PR TITLE
focus keyboard on firstNonSticky EditField

### LINKED ISSUE #14189: [Bug] The keyboard should focus on firstNonSticky EditField in NoteEditor
###### Reproduction Steps

1. Go to NoteEditor
2. Turn the toggle on of Front Card
3. Add a Note 

###### Expected Result
The keyboard should focus on firstNonSticky EditField in NoteEditor

###### Actual Result
The keyboard focusing on first EditField in NoteEditor

###### Debug info
AnkiDroid Version = 2.16.2-debug

Android Version = 9

ProductFlavor = amazon

Manufacturer = Google

Model = AOSP on IA Emulator

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 9; AOSP on IA Emulator Build/PSR1.180720.122; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36

ACRA UUID = ff087678-857e-4c63-9f39-7832f2214001

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
The keyboard should focus on firstNonSticky EditField in NoteEditor

## Fixes
Fixes #14189

## Approach
Find the first non-sticky index of EditField by iterating on HashMap `mToggleStickyText`

## How Has This Been Tested?
Tested on Emulator ( Pixel XL API 28 ) 

https://github.com/ankidroid/Anki-Android/assets/65113071/e9fe4f08-2b45-4e0e-86a3-e96b79ed106c

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
I'm not sure if this is intuitive. And, at least from my use, not sure if it is very helpful. Normally I pin the field not to keep it equal, but to change only some words without having to write the whole question again

**Comment by SanjaySargam** [comment]
> I'm not sure if this is intuitive. And, at least from my use, not sure if it is very helpful. Normally I pin the field not to keep it equal, but to change only some words without having to write the whole question again

But, it is not most of the case. Most of the users pin the field to stick the text to it.

**Comment by BrayanDSO** [comment]
How this behaves in Anki desktop?

**Comment by SanjaySargam** [comment]
> How this behaves in Anki desktop?

It behaves same as we have in AnkiDroid

**Comment by mikehardy** [comment]
If Desktop behaves the same as AnkiDroid now, then we should continue to follow Desktop.

**Pull request closed without merging**
