### PR TITLE
Duplicate refinement

### PR DESCRIPTION
**Pull request by timrae**
return `SparseArray<List<NoteInfo>>` containing *all* duplicates instead of `NoteInfo[]` with an arbitrary duplicate

### CODE REVIEW

**Comment by timrae** [comment]
I haven't tested this at all yet

**Comment by timrae** [comment]
Oh and the code should be much simpler to read if you only look at the first commit

**Comment by timrae** [comment]
@marcadar

I just tested that the code is functioning as expected and switched the inputs over from `String[][]` to `List<String>` for consistency with the other API methods.

Please let me know ideally today if you have any objections or suggestions

**Comment by marcardar** [comment]
No objections or suggestions from me :)

**Pull request merged**
