### PR TITLE
refactor: Convert Storage to Kotlin

### PR DESCRIPTION
**Pull request by david-allison**
Requested for https://github.com/ankidroid/Anki-Android/pull/11644/

Very high priority.

I was a little cheeky: `DroidBackend.kt` was easier to fix the nullability of, which made the `Collection()` method return a non-null

A strange error occurred from `JvmOverloads + JvmStatic` on the `Collection()` method. I didn't investigate. A rename to `collection()` fixed it.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
@BrayanDSO if you have time, your thorough review would be much appreciated

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
My guess is that most of this class will be eventually cut with the new backend, so left the review most for safety issues/migration correctness

**Review by mikehardy — APPROVED** [review]
This all looks fine is a hard-block on #11644 which is in my highest priority - going to check this locally and if it passes it goes in so I can continue over on the other PR

**Comment by mikehardy** [comment]
Nice, thanks @BrayanDSO - I'm adding those cleanups now and will re-push so I can merge this

**Comment by david-allison** [comment]
Thanks! I'm "out of office" for today. Fully onboard with the changes

**Pull request merged**
