### PR TITLE
Renaming "fact" to "note"

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This PR is similar to the PR "deck" to "collection"; even if this mistake was less confusing since there is no notion of "fact" anymore in anki.

Note that I won't do the same kind of PR for "model" since upstream still uses "model" in the code. However, "fact" is not used anymore (appart in some tests, I admit) so I believe that this PR is beneficial to ankidroid's code quality.

This has not been tested in any particular way, given that I only rename variables (all variables are renamed using android studio, in order to ensure they are replaced everywhere simultaneously)

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
I don't understand your point about translation. It seems all translations are preserved, since the IDs are changed in all files.

**Comment by Arthur-Milchior** [comment]
I just pushed to remove translations

**Comment by mikehardy** [comment]
The translated files (that is everything except the string xml values in the one directory called '/values/') are not actually "owned" by github here, and we don't really edit them here.

What we do is we take the XML resource files with English strings in the values directory, and push that out to crowdin.com for collaborative translating. We have lots of users there that get to work on them, then every once in a while I ask crowdin to "build" a new language bundle and I pull that down and put the files into their '/values-NN/' directories and build a release

Push string additions/changes out: https://github.com/ankidroid/Anki-Android/blob/master/tools/manage-crowdin.py

Pull translations in: https://github.com/ankidroid/Anki-Android/blob/master/tools/update-localizations.py

So two things:

1. you can't ever touch strings that aren't the English strings. They will be clobbered without thought later
1. every time you delete/add a string (which is what actually happens when you change a string name) you remove the existing translations and request fresh translations in each language

Which is why I wanted to leave those strings alone :-)

**Comment by mikehardy** [comment]
released as 2.10alpha70 as soon as google finishes processing it

**Pull request merged**
