### PR TITLE
NF: remove warning about try finally and uses resources

### PR DESCRIPTION
**Pull request by Arthur-Milchior**

### CODE REVIEW

**Comment by mikehardy** [comment]
Does the try-with-resources thing handle the null close on close correctly? Just curious - these aren't the newest language feature nevertheless I am not that familiar with them. Maybe @david-allison-1 knows otherwise I can research

**Comment by Arthur-Milchior** [comment]
I would believe that if android studio suggest such reformat and it didn't deal with null correctly, it would be a huge bug there.

A quick search on the web gives https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3 and 
>  A resource is closed only if it initialized to a non-null value.

**Comment by david-allison-1** [comment]
I know we have (and were having) problems with transactions in the `finally` block, but that's not try with resources.

Null safety is fine in the automatic `try with resources`. 

Exception safety should be fine as long as the exception is caught:

> any catch or finally block is run after the resources declared have been closed.

https://stackoverflow.com/a/15895463

**Review by mikehardy — APPROVED** [review]
thanks for the doc pointers on try-with-resources, I appreciate it and learned something :-)

**Pull request merged**
