### PR TITLE
Fix typo errors

### PR DESCRIPTION
**Pull request by Joaquin144**
## Purpose / Description
This is a typo fix in comments of %root/assets/scripts/card.js file

## Fixes
spelling mistakes at 2 places in comments/documentation
- Line 11: JavasSript 
- Line 237: middleground

## Approach
JavasSript -> JavaScript
middleground -> middle-ground

## How Has This Been Tested?

only comments have changed. No breaking changes. Ran and tested on my physical device.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
Thanks!

**Review by mikehardy — APPROVED** [review]
🤔  JavaScript is how people typically write it, so that's okay but the comment that was changed says this:

>   If the WebView loads too early on Android <= 2.3 (which happens on the first card or regularly with WebView switching enabled), then

Which makes me think the whole chunk of code is likely no longer needed and it may be worth removing.

'middle-ground' vs 'middleground' makes sense but I will note that neither of these typo fixes really add a lot of value, even if they are correct

I'm *always* happy to see new contributors, so hello 👋  and welcome 😄 - but I don't want to encourage PRs just for PRs sake. Something with more value would be thinking through what the comment mentioning old android versions we no longer use *means*, determining how you would test whether the described problem was still happening, and seeing if you could successfully remove that code

**Comment by Joaquin144** [comment]
Hi. Thanks for the feedback as this helps me improve.
Would definitely take care in future to contribute something more meaningful.

**Comment by david-allison** [comment]
Thanks! We have a lot of issues if you'd like to get stuck into something more meaty: https://github.com/ankidroid/Anki-Android/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%21%22

Feel free to pop by our [Discord](https://discord.gg/qjzcRTx) and say hi

**Pull request merged**
