### PR TITLE
Move migrate user data

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This PR simply moves Migrate User Data in its own package and so some work to ensure it can be used in Service instead of being used in AsyncTask. 
It's part of scoped storage, and once merged, will be followed by a PR to create a service to migrate those data

### CODE REVIEW

**Review by lukstbit — APPROVED** [review]
Changes LGTM,  just that the second commit fails checks(was fixed in the next commit). Should this be squashed merged?
```

> Task :AnkiDroid:compilePlayDebugUnitTestKotlin FAILED
e: /home/lucian/work/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt: (74, 62): Not enough information to infer type variable E
e: /home/lucian/work/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt: (90, 77): Unresolved reference: rename
e: /home/lucian/work/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt: (95, 23): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public open fun MigrateUserData.Operation.execute(): List<MigrateUserData.Operation> defined in com.ichi2.anki.servicelayer.scopedstorage.MoveDirectoryTest
e: /home/lucian/work/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt: (100, 23): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public open fun MigrateUserData.Operation.execute(): List<MigrateUserData.Operation> defined in com.ichi2.anki.servicelayer.scopedstorage.MoveDirectoryTest
e: /home/lucian/work/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt: (197, 85): Unresolved reference: MoveDirectory
e: /home/lucian/work/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt: (274, 57): Unresolved reference: MoveDirectory
e: /home/lucian/work/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/servicelayer/scopedstorage/MoveDirectoryTest.kt: (275, 16): Unresolved reference: MoveDirectory
```

**Comment by Arthur-Milchior** [comment]
I was fine with squash. But I'll correct

**Comment by Arthur-Milchior** [comment]
Done

**Comment by mikehardy** [comment]
goes through single commit checks fine - :rocket:

**Pull request merged**
