### PR TITLE
kotlinMigration for api project.

### PR DESCRIPTION
**Pull request by n1snt**
## Purpose / Description
Added kotlinMigration script for API project.

## How Has This Been Tested?
Tested by migrating NoteInfo to Kotlin & building the first commit.

## Checklist

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [  ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [  ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Does the second commit of the migration build for you?

I get 


```
Zip file '/Users/davidallison/StudioProjects/Anki-Android/api/build/intermediates/compile_library_classes_jar/debug/classes.jar' already contains entry 'com/ichi2/anki/api/NoteInfo.class', cannot overwrite
```

**Comment by n1snt** [comment]
Yeah, it's working fine here.
Try Build > Clean project maybe that would help.

**Comment by david-allison** [comment]
> Yeah, it's working fine here. Try Build > Clean project maybe that would help.

Nope, but I'll take it on trust. The gradle file in commit 1 worked fine

**Review by david-allison — APPROVED** [review]

**Comment by n1snt** [comment]
Tested this on BasicModel.java and is working properly.
Tried on both the first & second commit.

**Pull request merged**
