### PR TITLE
Remove log.wtf

### PR DESCRIPTION
**Pull request by david-allison-1**
Fixing a mistake I made when I was new to the project

## Learning

We should probably have a lint check

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Why is it a 'mistake'?

**Comment by david-allison-1** [comment]
> Why is it a 'mistake'?

Not used in the codebase anywhere else aside from here.

Was requested that I don't use it the day after, and it slipped through the net:  https://github.com/ankidroid/Anki-Android/pull/5855#discussion_r396457645

Under certain circumstances it'll kill the running app, we don't need to do that here: https://android.googlesource.com/platform/frameworks/base/+/jb-mr1-release/core/java/com/android/internal/os/RuntimeInit.java#328

**Comment by mikehardy** [comment]
Maybe if they had a softer version like "wth" or "wtactual" ;-)

**Comment by timrae** [comment]
Interesting, glad I asked!

**Pull request merged**
