### PR TITLE
Dependency updates 20220512

### PR DESCRIPTION
**Pull request by mikehardy**
Not quite a normal dependency update, android gradle plugin 7.2 needed a handful of tweaks to pass lint and stabilize on windows

### CODE REVIEW

**Comment by mikehardy** [comment]
Something still not quite right...

```
* What went wrong:
Execution failed for task ':AnkiDroid:compilePlayDebugUnitTestJavaWithJavac'.
> Failed to run Gradle Worker Daemon45 actionable tasks: 44 executed, 1 from cache

   > Unable to connect to the child process 'Gradle Worker Daemon 2'.
     It is likely that the child process have crashed - please find the stack trace in the build log.
     This exception might occur when the build machine is extremely loaded.
     The connection attempt hit a timeout after 120.0 seconds (last known process state: STARTED, running: true).
```

investigating

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/pull/11299#issuecomment-1125337757 - had the same flake on AGP

**Comment by mikehardy** [comment]
Going to have to table this for a while, I'm stuck trying to figure out how to reach in and cause this to be called with more than 120 (maybe 240 is enough)

https://github.com/gradle/gradle/blob/fdb0d5cb5d85ba3906d05067fd8522374fdc85a9/subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultWorkerProcessFactory.java#L59

Just not sure what to put in which part of the gradle file to hit it

**Comment by david-allison** [comment]
`(services.get(WorkerProcessFactory) as DefaultWorkerProcessFactory).connectTimeoutSeconds = 240` compiles

**Comment by mikehardy** [comment]
Nope - gonna have to think on this one

```

* What went wrong:
A problem occurred evaluating root project 'Anki-Android'.
> Could not get unknown property 'WorkerProcessFactory' for object of type org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.

```

**Comment by mikehardy** [comment]
discovered you can eliminate the standalone (multi-gigabyte, persists after compile) kotlin compiler daemon by having it run in process, and just ensuring main process is sufficient (it is, determined by GC logging). I think this might be the final set, allowing for a build/lint run that's about 2.5GB total for the JVM and a build/test run that is 2.5GB for compile and about 1.5GB*workers max, or 6.5GB max in CI, which should just fit  nicely in a 7.5GB RAM machine with swap enabled.

**Pull request merged**
