### PR TITLE
Replace transparent flag by white flag

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
2020-01-24-192321_467x864_scrot

Is that what was expected ?

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
2020-01-24-193958_467x864_scrot
I can also have this kind of image. But for some reason I can't successfully get an entirely white stroke. I just get this kind of grey.

**Comment by mikehardy** [comment]
@timrae this was in response to a request by you, could you check if you like this better?

**Comment by timrae** [comment]
Since this is PNG, you need to include all the [multiple resolutions of the image](https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp).

Which icon is that flag in the second screenshot coming from, and under what scenario? My understanding of how this feature works is that it behaves the same way as the starred icon, which is to say that it should have a white outline of a flag when the card has not been flagged, or it has a solid flag in the color of the flag if the user assigned one to the card. I'm not aware of any situation where a solid white flag would be required...?

@Arthur-Milchior 
I'm attaching the zip file I was intending you to download and use from the material.io website.
[outlined_flag-white-android.zip](https://github.com/ankidroid/Anki-Android/files/4209056/outlined_flag-white-android.zip). You should copy all of the `*_24.png` files to the appropriate folders and use those. Please delete all .png files from the main `drawable` folder and provide appropriate multi-resolution files for those as well.

**Comment by Arthur-Milchior** [comment]
Well, I'd prefer to use svg. But I don't see how to do it. I'm not specially in favor of png. I used it because it seems to be what is expected
"Which icon is that flag in the second screenshot coming from"
I am not sure to understand the question. The icon in the second image is not in the PR. I was asking which flag you did prefer. Or whether you can give me a flag to use (which you did)
That was only two version of the same flags, which are shown when:
* the user states to show flags in the toolbar
* no flag is set for current card

Thank you for the white flags. But how do I make colored flags in all resolution ? In my previous PR, I did it by changing the color of the SVG. But now that it's PNG it does not seems there is anyway to script those changes anymore.

**Comment by timrae** [comment]
I don't mind if you want to use svg, if someone knows how to do it. I believe we have an old PR open related to this, but I don't remember the details, as I've always just used PNG.

I believe the Android framework provides a way to change the icon color at runtime. You might want to look into that. If not, I'm sure there's a command line utility to change color if you google it.

**Comment by mikehardy** [comment]
#5134 - research indicated that SVG is totally possible for us now on all supported platforms. That one stalled not for lack of support, but because our 'FAB' (Floating Action Button, the plus sign to add things on the deck list) did something dirty internally. It was and is close to merge otherwise.

**Comment by Arthur-Milchior** [comment]
Si it would be okay if I just replace the png icons by svg icons ?
I assume in this case there is no point in giving multiple resolution, since SVG does not have resolution

**Comment by mikehardy** [comment]
I strongly prefer SVG at this point, as a stated goal nearly completed by that PR I want to exchange everything for SVG. I believe it will shrink the app size while improving the graphics, win/win. If you can do that here, all the better

**Comment by Arthur-Milchior** [comment]
I was only considering the flags right now. I'll try with the flag. I'll see whether it works and whether it makes sens to make more SVG afterwards.

**Comment by mikehardy** [comment]
That sounds great - just doing the flag is totally fine. The other PR gets most everything else, no need to go past what you need directly

**Pull request closed without merging**
