### PR TITLE
Remove 11-arrays.xml string-array elements

### LINKED ISSUE #7794: Remove 11-arrays.xml string-array elements
Arrays are better used in `constants.xml` and referenced via `@string` to allow for changes in the order of the array

----

* Deprecate `11-arrays.xml`
   * Instead, use `@string` references: https://stackoverflow.com/a/4161645
       * How do we do this without trashing the existing translations? Doesn't seem easy in Android Studio
   * Enforce via lint check

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/7793#issuecomment-735378061_

-----

Follow up steps from #7800 :

* [x] Language sync
* [x] Copy from string-array to string for each language file

<details><summary>progress</summary>

**no action**

* [x] af
* [x] am
* [x] bn
* [x] ckb
* [x] da
* [x] fy
* [x] ga
* [x] got
* [x] gu
* [x] hr
* [x] hy
* [x] is
* [x] jv
* [x] ka
* [x] kk
* [x] km
* [x] ky
* [x] lv
* [x] mn
* [x] mr
* [x] my
* [x] nn (nnno)
* [x] pa (pain)
* [x] ro
* [x] sq
* [x] ss
* [x] sw
* [x] tg
* [x] tgl (tagalog: tl)
* [x] th
* [x] ti
* [x] tn
* [x] ts
* [x] tt (ttru)
* [x] ur (urpk)
* [x] uz
* [x] ve
* [x] wo
* [x] xh
* [x] yue (yu)
* [x] zu

**Action Needed**

* [x] ar
* [x] az
* [x] be
* [x] bg
* [x] ca
* [x] cs
* [x] de
* [x] el
* [x] eo
* [x] es-rAR
* [x] es-rES
* [x] et
* [x] eu
* [x] fa
* [x] fi
* [x] fil
* [x] fr
* [x] gl
* [x] heb
* [x] hi
* [x] hu
* [x] ind
* [x] it
* [x] ja
* [x] ko
* [x] ku
* [x] lt
* [x] mk
* [x] ms
* [x] nl
* [x] no
* [x] pl
* [x] pt-rBR
* [x] pt-rPT
* [x] ru
* [x] sat
* [x] sk
* [x] sl
* [x] sr
* [x] sv
* [x] ta
* [x] te
* [x] tr
* [x] uk
* [x] vi
* [x] zh-rCN
* [x] zh-rTW

</details>

* [x] Move gestures_labels to constants.xml

### PR DESCRIPTION
**Pull request by TarekkMA**
## Purpose / Description
Extracted array and moved them to `constants.xml` file

## Fixes
Fixes #7794

## Approach
Built a script using python: 
https://github.com/TarekkMA/extract_android_array_to_strings/blob/master/main.py

## How Has This Been Tested?

It runs 😅 

## Learning (optional, can help others)
Using `lxml` python package. 

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by TarekkMA** [comment]
@david-allison-1, I think merging this will unblock #8224, right?

**Comment by david-allison-1** [comment]
I believe this will cause CrowdIn to be out-of-sync with the code, and the change will be reverted after our next translation sync.

@Arthur-Milchior Am I right in this assumption?

Issues: 

* CrowdIn is the source of truth for non-English translations, if we don't upload these to CrowdIn, then they will be clobbered after our next language sync
* CrowdIn has no knowledge that new string constants have been added
* CrowdIn has changes which aren't reflected in the code, uploading the files as-is to CrowdIn will revert these changes

**Comment by Arthur-Milchior** [comment]
I don't understand how the new strings are found by the code. Let's consider e.g. error_reporting_choice_labels_always_report, it seems no code know where to find it. So I assume it'll break ankidroid. 

David is right, we push english to Crowdin and download translations. 
It's not mandatory however. Note that we could do a script that:
* pull everything
* Make a backup of everything
* apply python script
* push everything
it "just" must be written down.

The only downside would be that translation done during the script execution, at most a few minutes, will be lost.  Not ideal, but may be acceptable if required.

Another solution would be:
* Pull everything
* make back-up
* Push only the new values (I assume it can be done, don't know how. In worst case just by moving to a different files)
* check that new values are correctly online
* delete arrays values

Probably safer. But during some time duplicate stirng would be in crowdin. If the translator translate the array one instead of the string one, work is lost

**Comment by david-allison-1** [comment]
You can push individual files. Realistically the chance of someone changing `11-arrays` is very small.

I'd propose:

1. Add new string constants to `11-arrays.xml` (non-array)
2. Translation Sync - create the values on CrowdIn for all languages
3. Pull
4. Modify script to copy from the string array into the newly created string values in `11-arrays`
5. Manually upload each new `11-arrays` value to CrowdIn
6. Translation Sync - download the changes
7. Move the string array to `constants.xml`, referencing the new strings
8. Remove the old values in `11-arrays.xml`
9. Push to master
10. Translation sync

Now.. points 2-4 should be done quickly, to ensure that no translators see the duplicate strings and waste effort translating them

**Comment by david-allison-1** [comment]
Also need to note that the lint failures are real errors

**Comment by TarekkMA** [comment]
Thank you for the feedback
I didn't know that Crowdln would be that big of an issue. I will read up more on how AnkiDriod syncs with Crowdln and I will reply here.

> @Arthur-Milchior  I don't understand how the new strings are found by the code. Let's consider e.g. error_reporting_choice_labels_always_report, it seems no code know where to find it. So I assume it'll break ankidroid.

Those strings are referenced by their array, so extracting the array content and making them as a string won't be a problem, I think. This what I got after looking on how David solved the previous array problem.

> @david-allison-1 Also need to note that the lint failures are real errors

Can you please guide me on how to enable lint rules during development/build or how to verify it

> @david-allison-1  5. Manually upload each new 11-arrays value to CrowdIn

What do you mean by uploading each new 11-arrays value? Only en?

**Comment by Arthur-Milchior** [comment]
> Thank you for the feedback

You're welcome. Thanks for contributing.

> I didn't know that Crowdln would be that big of an issue. 

It was also counter intuitive to me. Actually, it comes from the fact that we can't just run a copy of crowdin on our device and test. So any test need to be approved by other people before being run. We have a copy translations on git, so we will never lose everything, but there is always a risk that breaking things may be quite hard to solve. And even if we don't lose translations, we may loose screenshot associated to images, and translators comments, and have no back-up here.


> I will read up more on how AnkiDriod syncs with Crowdln and I will reply here.
> 
> > @Arthur-Milchior  I don't understand how the new strings are found by the code. Let's consider e.g. error_reporting_choice_labels_always_report, it seems no code know where to find it. So I assume it'll break ankidroid.
> 
> Those strings are referenced by their array, so extracting the array content and making them as a string won't be a problem, I think. This what I got after looking on how David solved the previous array problem.

I beg your pardon but I don't understand. For example the array error_reporting_choice_labels seems to be deleted, however the array still appears in the file preferences_general.xml, and if we were to merge your PR, I'd assume that this window would break. If I'm wrong, I'd really like to know what will occurs in preference and how it'll know what are the choices to report errors

**Comment by david-allison-1** [comment]
> > @david-allison-1 Also need to note that the lint failures are real errors
> 
> Can you please guide me on how to enable lint rules during development/build or how to verify it

`gradlew lintRelease`

> > @david-allison-1  5. Manually upload each new 11-arrays value to CrowdIn
> 
> What do you mean by uploading each new 11-arrays value? Only en?

Upload one file for each of the languages `/af/11-arrays.xml`, `/ar/11-arrays.xml` etc...

The intention of this is to send your local changes (setting the newly created strings to the correct values) to CrowdIn

**Comment by TarekkMA** [comment]
> I beg your pardon but I don't understand. For example the array error_reporting_choice_labels seems to be deleted, however the array still appears in the file preferences_general.xml, and if we were to merge your PR, I'd assume that this window would break. If I'm wrong, I'd really like to know what will occurs in preference and how it'll know what are the choices to report errors

Oh, yeah sorry for the long commit, 😄  arrays are still intact in `constants.xml`, but instead of hard coding the string in `<item>xyz<item>` they are now referencing it via string xmls `<item>@strings/arr_xyz<item>`

**Comment by Arthur-Milchior** [comment]
Thanks a lot for the explanation, makes far more sens now.

**Comment by mikehardy** [comment]
Out of curiosity, what's the current state here? Where is this PR going? Right now it's gone stale and has a pile of conflicts from work in the related area. It's *huge* as well :-)

**Comment by TarekkMA** [comment]
> Out of curiosity, what's the current state here? Where is this PR going? Right now it's gone stale and has a pile of conflicts from work in the related area. It's _huge_ as well :-)

I will do modifications to the script so we can do the steps David mentioned

**Comment by TarekkMA** [comment]
It's okay no problems, this issue needs coordination to be done right, I will write my final thought about how I think this can be done.

The provided 5 commits should be a demo of the end result. the first commit to avoid `DuplicateCrowdInStrings` lint error 

I took #7794 PRs and David's steps (https://github.com/ankidroid/Anki-Android/pull/8271#issuecomment-802475938) as an example of how we will go through this:

#### [First PR] (Extract English array item strings) 
- run the script in `extract_english` mode
- example: #7800
#### [Second PR] Sync Translations with crowdin
- this can be simulated for testing with running script in `fill_translations_with_en` mode
- example: #7802
#### [Thrid PR] Extract array translations
- replace english with translated values
- run script with `extract_translations` mode
- example: #7803
#### Upload new translations files (11-arrays.xml) manually to crowdln
- I don't have a script for that unfortunately 

#### [Fourth PR] Move `string-array` elements to `constants.xml` with string references
- run script with `move_arrays` mode
- example: #7804

**Pull request closed without merging**
