### PR TITLE
notify StudyOptionsFragment when deck deleted on tablet 

### LINKED ISSUE #15921: [Bug] Deleting Deck doesn't update the StudyOptionsFragment in Tablet mode
###### Reproduction Steps

1. Delete Deck

###### Expected Result
StudyOptionsFragment should show another deck details (other than deleted)

###### Actual Result
StudyOptionsFragment still shows deleted deck details

###### Debug info
AnkiDroid Version = 2.18alpha6-debug (14173d3aab96a63611bbf630ba859bc0ad620e1b)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 9 (SDK 28)

ProductFlavor = amazon

Manufacturer = Google

Model = AOSP on IA Emulator

Hardware = ranchu

Webview User Agent = null

ACRA UUID = 0e18e70d-4cdd-4099-ba65-85d82d40cb91

FSRS Enabled = false

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by AbdelrahmanEsam**
notify StudyOptionsFragment when deck deleted on tablet

* Fixes #15921

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
There's changes in "files changed" which aren't relevant to this pull request 

You'll need to revert these before it's reviewable

**Comment by AbdelrahmanEsam** [comment]
> There's changes in "files changed" which aren't relevant to this pull request
> 
> You'll need to revert these before it's reviewable

which file please ?

**Comment by david-allison** [comment]
Comment still stands - see Files Changed on GitHub

**Review by david-allison — APPROVED** [review]
Thanks!

**Review by lukstbit — APPROVED** [review]

**Pull request merged**
