### PR TITLE
Displaying toast when creating deck with any existing deck name

### LINKED ISSUE #10401: Creating new deck with name same as any existing deck should give proper error message
###### Reproduction Steps

1. Create new deck.
2. Set name same as any existing deck.

###### Result
No error message displayed

###### Expected Result
Should give a message that deck with same name exists

https://user-images.githubusercontent.com/75438613/155757640-201b7a41-6bd9-4ac0-af2b-0f07e8dcf339.mp4

### PR DESCRIPTION
**Pull request by AayushSolanki**
Fixes #10401 
Shows toast if user try to create deck with same name as of any existing deck.

**Before**

https://user-images.githubusercontent.com/75438613/158241466-53c73019-a0f3-4c76-9c97-31d1d9a3a5a0.mp4

**After**

https://user-images.githubusercontent.com/75438613/158241888-6c53dc0e-c3d4-4462-a38d-7276975230f9.mp4

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
This PR shows no changes. Could you `git squash` so the commits display the changes which you made

**Review by david-allison — CHANGES_REQUESTED** [review]
Ideally we want the dialog to show the user that there is a problem visually, rather than displaying a toast and closing the window

**Comment by AayushSolanki** [comment]
@david-allison so do we need to display the dialog box again so that user can enter a different name

**Comment by david-allison** [comment]
> @david-allison so do we need to display the dialog box again so that user can enter a different name

Our dialog box already has UX for validation:

image

I would add a message stating that the deck name already exists, along with the red highlighting and blocking out the "OK" button

**Comment by AayushSolanki** [comment]
alright where is this UX located or how can i use this?

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/blob/0c0d6f75c3d6b33c550e74bb9fbc578332af6caf/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt#L62-L68

The source code of `MaterialDialog.java` contains the current implementation, but the implementation doesn't appear to easily be extensible.

You can define a similar/identical view via `.customView()`, there's already a fair few examples in the codebase of us using this method

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/blob/d6398590f74435a03d282be0e5949c6efd6292d9/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt#L136-L164

**Comment by AayushSolanki** [comment]
so should i create such a dialog in `CreateDeckDailog.kt` and call it in function `createDeck` ?

**Comment by david-allison** [comment]
Modify this code: [https://github.com/ankidroid/Anki-Android/blob/0c0d6f75c3d6b33c550e74bb9fbc578332af6caf/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt#L62-L68] to handle additional validation of the text

**Comment by david-allison** [comment]
This doesn't do validation on the name.

* If the name already exists
  * Disable "OK"
  * Make the line on the EditText red
  * Add a message explaining the reason for the validation

**Comment by AayushSolanki** [comment]
Do we need to check in realtime(while the user is typing the name) if the deck with same name exist not?
and is it possible with MaterialDialog to add a line underneath the EditText or i need to use AlertDailog

**Comment by mikehardy** [comment]
Feedback not addressed, converted to draft

**Comment by AayushSolanki** [comment]
I got busy due to my academic exam i will be submitting a PR soon after my exams get over

**Comment by vinaydeepkaur** [comment]
This can be enhance by displaying the Toast message at the middle of the screen with colored text. For example: 
red  for "Deck with same name already exist"
and green for "Deck created successfully"

**Comment by AayushSolanki** [comment]
@david-allison could you please assign this to me?

**Pull request closed without merging**
