### PR TITLE
Added Malayalam Language 

### PR DESCRIPTION
**Pull request by vinishhub**
## Purpose / Description
Added Malayalam language support

## Fixes
Fixes _Link to the issues._[#8676]

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
I'm not aware of any reason all the RTL changes should be in a language addition PR, those should be completely separate PRs

**Comment by david-allison-1** [comment]
When you start a new change, could you:

* change your branch to master
* Pull the latest master
* Make your branch

As you haven't done this, this change contains a lot of irrelevant commits which makes it hard to review

To fix this, could you rebase your change onto master so the files changed are relevant to this PR

**Comment by mrudultora** [comment]
Your fork is 227 commits behind the upstream. Please make the fork even with upstream to avoid merge conflicts.

**Review by mikehardy — CHANGES_REQUESTED** [review]
Not git merge, git rebase - there are now 68 commits in this PR when there should be a single commit with nothing but your changes. It may be easier to start fresh on a clean PR based off current master

**Comment by vinishhub** [comment]
how can I delete this pr ?

**Comment by mrudultora** [comment]
Once a PR is made it cannot be deleted. But don't worry, try to look some basics of rebase or watch out some tutorials. If that doesn't help open a new PR (and close this one).

**Pull request closed without merging**
