### PR TITLE
An icon added to the item of "Deck options" on Actionbar

### LINKED ISSUE #10731: [Suggestion] Add an icon to the item of "Deck options" on Actionbar of Study screen
Thanks to developers.

**Is your feature request related to a problem? Please describe.**

- #9110 is unquestionably a wonderful work, but it seems to have not solved all of the tasks mentioned on  #8912 yet. One of the unsolved tasks is [to add an icon to "Deck options"](https://github.com/ankidroid/Anki-Android/issues/8912#issuecomment-850807096). 
image

**Describe the solution you'd like**

- Add [the following icon](https://fonts.google.com/icons?selected=Material+Icons+Outlined:tune:) to "Deck options".
image
image

**Describe alternatives you've considered**

- Add [the following icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Asettings_applications%3A) to "Deck options".
image
image

**Additional context**

- N/A

### PR DESCRIPTION
**Pull request by s-deepak-kumar**
## Purpose / Description
Add an icon to the item of "Deck options" on Actionbar of Study screen

## Fixes
Fixes #10731 

## Approach
Just go into drawable folder & add ic_tune_white.xml, then go into menu folder & edit (i.e. add icon to menu) reviewer.xml

## How Has This Been Tested?

Run project via android studio on emulator as well as real device

## Learning (optional, can help others)
I got whole codebase of Anki-Android & started exploring it deeply.

### CODE REVIEW

**Review by Arthur-Milchior — APPROVED** [review]
Would you mind adding a screenshot?  LGTM assuming the result work. Thanks

**Comment by s-deepak-kumar** [comment]
Here Is Screenshot:
Screenshot_20220407-104633_AnkiDroid

**Review by mikehardy — COMMENTED** [review]
needs unrelated set-activity-title commit removed, but otherwise looks perfect

**Comment by s-deepak-kumar** [comment]
> needs unrelated set-activity-title commit removed, but otherwise looks perfect

When i remove it, again same problem occurs. If you have any idea about it please give some hint.

**Comment by mikehardy** [comment]
@s-deepak-kumar I think I wasn't clear - here's how PRs work:

- each PR should fix one thing and one thing only
- commits unrelated to the thing being fixed in a PR are not accepted

What that means concretely for this PR and the other one that is now tangled with this one:

1. re-open this PR
2. use git rebase to drop the commit for activity title from this PR, so you have *just* the icon commit in this PR. Now this is a valid "fixes one thing PR"
3. use git rebase to drop the commit for icon from PR #10742 - then that PR is a valid "fixes one thing  PR"

That's a process answer to your question. The short answer to your question is: your fixes are fine, your PRs are simply not merge-able for *structural* reasons, because we require PRs to only have commits to fix one thing

**Review by mikehardy — APPROVED** [review]
Nice! This is a clean fix for the problem with no unrelated stuff in it :-)
It would have been better to use git rebase and actually drop the commit, then force-push that back out to your branch, but I understand that is more advanced git work, and a git revert also works. We can squash merge it here

**Comment by mikehardy** [comment]
Hi there! APRIL OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [April 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-04-01..2022-04-30)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of March.

Please note that GSoC contributions are okay for this process. Our philosophy is that our users have donated to AnkiDroid for all contributions. The only PRs that will not go through the OpenCollective process are ones directly related to am accepted GSoC project from a selected participant, since those receive a stipend from GSoC itself.

Please understand that this means the monthly budget we have for payments might be stretched a bit and the cap on payments-per-person may be lower, but we try to make our process as fair and transparent as possible, we just need your understanding.

Thanks!

**Pull request merged**
