### PR TITLE
Removed the unused string file

### LINKED ISSUE #9525: string: `link_donation` is unused
This is used incorrectly (used in code, but not displayed). It's not picked up by our lint checks as we:

* Get the string from an array
* Apply substitutions to this string via `String.format`, rather than the Android `getString()`

It should be removed, but let's handle this in a separate issue/PR

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/9400#discussion_r711767936_

### PR DESCRIPTION
**Pull request by pratik2315**
## Purpose / Description
Modifying unused string file from the codebase

## Fixes
Fixes #9525 

## Approach
Updating the method used for fetching unused file from the codebase

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by pratik2315** [comment]
So its actually used in the app and in the "Info.java" file in the code.
I didn't wait for the build to finish and submitted a PR but got an error as soon as the build stopped after a while😅

**Comment by pratik2315** [comment]
I will soon get the string using the String.Format instead of gestring( ) 👍

**Comment by mikehardy** [comment]
It is "used" but only in the sense that it is referenced, the error (in my mind) is that in Info.java where it is used, it is used to interpolate into a String.format slot that *does not actually exist* in the string being formatted

According to David, converting that String.format to an android format should result in the linter picking up the problem (and throwing an error) then it is obvious that the format / interpolation is wrong which points out that link_donation really is unused, and then the final / proper fix is to remove it from Link.java and the xml strings file

**Comment by david-allison-1** [comment]
> It is "used" but only in the sense that it is referenced, the error (in my mind) is that in Info.java where it is used, it is used to interpolate into a String.format slot that _does not actually exist_ in the string being formatted
> 
> According to David, converting that String.format to an android format should result in the linter picking up the problem (and throwing an error) then it is obvious that the format / interpolation is wrong which points out that link_donation really is unused, and then the final / proper fix is to remove it from Link.java and the xml strings file

We can't convert the `String.format` to an Android format, as the format string is defined as one element in an `R.array`, rather than a `R.string`.

The solution is to remove the reference to this string from the code, as it's unused

**Review by david-allison-1 — COMMENTED** [review]
picked up a conflict with the [https change](https://github.com/ankidroid/Anki-Android/pull/9400). We're still fine to remove the constant

**Pull request closed without merging**
