### PR TITLE
Changed color of ProgressBar

### LINKED ISSUE #14963: Change color of ProgressBar
The color of the progress bar does not match the App's theme. 

###### Reproduction Steps

1. Go to DeckPicker
2. Click on Three-Dots
3. Check Media

###### Expected Result
The color of the progress bar should match the App's theme. 

###### Actual Result

The color of the progress bar does not match the App's theme. 

WhatsApp Image 2023-12-12 at 5 02 15 PM (1)
WhatsApp Image 2023-12-12 at 5 02 15 PM (2)
WhatsApp Image 2023-12-12 at 5 02 15 PM
WhatsApp Image 2023-12-12 at 5 02 16 PM

###### Debug info
AnkiDroid Version = 2.17alpha10-debug (50fa39cd561d83662cd5ef1f708b14a9a15c74ac)

Backend Version = 0.1.31-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.193 Mobile Safari/537.36

ACRA UUID = 75cf281b-7921-408d-a660-d55f11d401fe

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
The color of the progress bar does not match the App's theme.

## Fixes
* Fixes #14963 

## Approach
Create a custom dialog

## How Has This Been Tested?

Physical Device ( Realme 9 )
WhatsApp Image 2023-12-14 at 6 36 41 PM

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by SanjaySargam** [comment]
There is no way to change the color of progress bar.

**Comment by SanjaySargam** [comment]
@BrayanDSO Kindly review it

**Review by BrayanDSO — APPROVED** [review]
Works for me.

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
```
* What went wrong:
Execution failed for task ':AnkiDroid:processPlayDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     warn: removing resource com.ichi2.anki.debug:string/decks_rename_exists without required default value.
     warn: removing resource com.ichi2.anki.debug:string/decks_rename_filtered_nosubdecks without required default value.
     com.ichi2.anki.AnkiDroid-mergePlayDebugResources-60:/values/values.xml:4436: error: resource color/theme_light_primary (aka com.ichi2.anki.debug:color/theme_light_primary) not found.
     com.ichi2.anki.AnkiDroid-mergePlayDebugResources-60:/values/values.xml:4436: error: resource color/theme_light_primary (aka com.ichi2.anki.debug:color/theme_light_primary) not found.
     error: failed linking references.
```

**Comment by SanjaySargam** [comment]
@david-allison Will you please guide me how to resolve this issue ?

**Comment by SanjaySargam** [comment]
image


Test fails, but I don't see any issues in this file

**Comment by david-allison** [comment]
Rebased onto `main`, fixed the import + force pushed

Let's go! 🚀🚀

**Pull request merged**
