### PR TITLE
Remove anki sync

### PR DESCRIPTION
**Pull request by divyansh-dxn**
### Changes
- [✓] Removed anki-sync button from ( app bar in DeckPicker and swipe down action )
- [✓] Deck click behaviour from "open cards" ---> "expand deck"
- [✓] Multiple expanded deck ---> Can expand only one deck at a time

### CODE REVIEW

**Comment by david-allison** [comment]
Why is sync being removed here?

**Comment by divyansh-dxn** [comment]
Sorry I just joined an organisation which is working on a fork of AnkiDroid. They had'nt removed the remote path of Ankidroid original repo, by mistake I create a pull request on here instead of there. Sorry for the disturbance!

**Comment by david-allison** [comment]
@divyansh-dxn No worries! Feel free to send over a link, it'd be great to see what you guys are up to

**Comment by mikehardy** [comment]
Stated slightly more strongly, this is mostly a GPL licensed project, post the publicly available link here so we can see the source code of your derived work, thank you

**Comment by divyansh-dxn** [comment]
https://github.com/NestorAnalytics-AndroidApp/Anki-Android

They haven't made much changes as of now. I'm an intern there and looking forward to be a part of AnkiDroid this GSOC. Currently getting familiar with the codebase. I'll also try to fix some issues as well.

**Pull request closed without merging**
