### PR TITLE
cleanup: most Hungarian Notation

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
New contributors are confused as to which to use. We should standardize

## Approach

apply the following patch, run lint, then fix manually using Android Studio rename

**I have avoided files which I know are under PR, and some of the large activities**

<details>

<summary>patch</summary>

```patch
Index: lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt b/lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt
--- a/lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt	(revision 5f6bad5c10753b2c89f8b4907a99e99163a6d6f9)
+++ b/lint-rules/src/main/java/com/ichi2/anki/lint/IssueRegistry.kt	(date 1704230143005)
@@ -35,6 +35,7 @@
 import com.ichi2.anki.lint.rules.InvalidStringFormatDetector
 import com.ichi2.anki.lint.rules.JUnitNullAssertionDetector
 import com.ichi2.anki.lint.rules.NonPositionalFormatSubstitutions
+import com.ichi2.anki.lint.rules.NonPublicNonStaticFieldDetector
 import com.ichi2.anki.lint.rules.PrintStackTraceUsage
 import com.ichi2.anki.lint.rules.VariableNamingDetector
 
@@ -60,7 +61,8 @@
                 FixedPreferencesTitleLength.ISSUE_MAX_LENGTH,
                 FixedPreferencesTitleLength.ISSUE_TITLE_LENGTH,
                 VariableNamingDetector.ISSUE,
-                InvalidStringFormatDetector.ISSUE
+                InvalidStringFormatDetector.ISSUE,
+                NonPublicNonStaticFieldDetector.ISSUE
             )
         }
     override val api: Int
Index: lint-rules/src/main/java/com/ichi2/anki/lint/rules/FieldNamingPatternDetector.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FieldNamingPatternDetector.kt b/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FieldNamingPatternDetector.kt
new file mode 100644
--- /dev/null	(date 1704230143008)
+++ b/lint-rules/src/main/java/com/ichi2/anki/lint/rules/FieldNamingPatternDetector.kt	(date 1704230143008)
@@ -0,0 +1,62 @@
+/*
+ *  Copyright (c) 2024 David Allison <davidallisongithub@gmail.com>
+ *
+ *  This program is free software; you can redistribute it and/or modify it under
+ *  the terms of the GNU General Public License as published by the Free Software
+ *  Foundation; either version 3 of the License, or (at your option) any later
+ *  version.
+ *
+ *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
+ *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
+ *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License along with
+ *  this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+@file:Suppress("UnstableApiUsage")
+
+package com.ichi2.anki.lint.rules
+
+import com.android.tools.lint.client.api.UElementHandler
+import com.android.tools.lint.detector.api.Detector
+import com.android.tools.lint.detector.api.JavaContext
+import org.jetbrains.uast.UField
+import org.jetbrains.uast.UVariable
+
+abstract class FieldNamingPatternDetector : Detector(), Detector.UastScanner {
+    override fun createUastHandler(context: JavaContext): UElementHandler? {
+        return VariableNamingHandler(context)
+    }
+
+    override fun getApplicableUastTypes() = listOf(UVariable::class.java)
+
+    private inner class VariableNamingHandler(private val mContext: JavaContext) :
+        UElementHandler() {
+        override fun visitVariable(node: UVariable) {
+            // HACK: Using visitField didn't return any results
+            if (node !is UField) {
+                return
+            }
+            if (!isApplicable(node)) {
+                return
+            }
+            val variableName = node.name
+            if (meetsNamingStandards(variableName)) {
+                return
+            }
+            reportVariable(mContext, node, variableName)
+        }
+    }
+
+    /** If the lint check is applicable to the given variable  */
+    protected abstract fun isApplicable(variable: UVariable): Boolean
+    protected abstract fun meetsNamingStandards(variableName: String): Boolean
+
+    /** Report the problematic variable to the lint checker  */
+    protected abstract fun reportVariable(
+        context: JavaContext,
+        node: UVariable,
+        variableName: String
+    )
+}
Index: lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPublicNonStaticFieldDetector.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPublicNonStaticFieldDetector.kt b/lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPublicNonStaticFieldDetector.kt
new file mode 100644
--- /dev/null	(date 1704230143007)
+++ b/lint-rules/src/main/java/com/ichi2/anki/lint/rules/NonPublicNonStaticFieldDetector.kt	(date 1704230143007)
@@ -0,0 +1,80 @@
+/*
+ *  Copyright (c) 2024 David Allison <davidallisongithub@gmail.com>
+ *
+ *  This program is free software; you can redistribute it and/or modify it under
+ *  the terms of the GNU General Public License as published by the Free Software
+ *  Foundation; either version 3 of the License, or (at your option) any later
+ *  version.
+ *
+ *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
+ *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
+ *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
+ *
+ *  You should have received a copy of the GNU General Public License along with
+ *  this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+@file:Suppress("UnstableApiUsage")
+
+package com.ichi2.anki.lint.rules
+
+import com.android.tools.lint.detector.api.Implementation
+import com.android.tools.lint.detector.api.Issue
+import com.android.tools.lint.detector.api.JavaContext
+import com.android.tools.lint.detector.api.Scope
+import com.ichi2.anki.lint.utils.Constants
+import org.jetbrains.uast.UElement
+import org.jetbrains.uast.UVariable
+import org.jetbrains.uast.UastVisibility
+import java.util.EnumSet
+
+/**
+ * https://github.com/ankidroid/Anki-Android/wiki/Code-style#non-public-non-static-field-names-should-start-with-m
+ */
+class NonPublicNonStaticFieldDetector : FieldNamingPatternDetector() {
+
+    companion object {
+        private val implementation = Implementation(NonPublicNonStaticFieldDetector::class.java, EnumSet.of(Scope.JAVA_FILE, Scope.TEST_SOURCES))
+
+        @JvmField
+        var ISSUE: Issue = Issue.create(
+            "NonPublicNonStaticFieldName",
+            "non-public non-static naming",
+            "Non-public, non-static field names should start with m: https://github.com/ankidroid/Anki-Android/wiki/Code-style#non-public-non-static-field-names-should-start-with-m",
+            Constants.ANKI_CODE_STYLE_CATEGORY,
+            Constants.ANKI_CODE_STYLE_PRIORITY,
+            Constants.ANKI_CODE_STYLE_SEVERITY,
+            implementation
+        )
+    }
+    override fun isApplicable(variable: UVariable): Boolean {
+        if (variable.isStatic) {
+            return false
+        }
+        return variable.visibility != UastVisibility.PUBLIC
+    }
+
+    override fun meetsNamingStandards(variableName: String): Boolean {
+        if (variableName.length <= 2) return true
+        if (!variableName.startsWith("m")) return true
+        return !Character.isUpperCase(variableName[1])
+    }
+
+    override fun reportVariable(context: JavaContext, node: UVariable, variableName: String) {
+        if (variableName.length < 2) {
+            // cast the node as it's ambiguous between two interfaces
+            val uNode: UElement = node
+            context.report(ISSUE, uNode, context.getNameLocation(uNode), "Variable name is too short")
+            return
+        }
+
+        // trim the 'm' and make the next character lowercase
+        val replacement = variableName[1].lowercaseChar() + variableName.substring(2)
+
+        // TODO: A fix should be possible, but it requires a rename operation
+
+        // cast the node as it's ambiguous between two interfaces
+        val uNode: UElement = node
+        context.report(ISSUE, uNode, context.getNameLocation(uNode), "Field should be named: '$replacement'")
+    }
+}
```

</details>

## How Has This Been Tested?
Trusting CI

## Learning (optional, can help others)
`LintFix` works, but I still haven't looked into how to do a 'rename' replacement, rather than 'replace line' replacement

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
As much as I'd like my activity graph to have 100 commits in a day, this feels like a 'squash'

**Review by BrayanDSO — APPROVED** [review]
If CI is happy, so am I

**Comment by david-allison** [comment]
I'm dropping commits if there's a conflict. More work to fix than it is to redo them

**Review by lukstbit — APPROVED** [review]
I like the change! Feel free to merge when you want, I really dislike not being able to do a squash merge with the queue.

**Comment by david-allison** [comment]
No squash is annoying, we probably want a bot here (?)

**Pull request merged**
