### PR TITLE
Show progress bars when loading count tree in deck picker

### PR DESCRIPTION
**Pull request by timrae**
I've noticed there are times when a blank activity is shown with really big collections

### CODE REVIEW

**Comment by hssm** [comment]
If I go into the browser and then back, there is a visible spinner in front of the decklist that lasts about 5 seconds.

**Comment by timrae** [comment]
I can't reproduce it on my device, maybe give me some more detailed steps?

**Comment by hssm** [comment]
1 - Be in DeckPicker
2 - Open card browser from Navigation Drawer
3 - Tap back button

I'll have a go at fixing it later since I can reproduce it.

**Comment by timrae** [comment]
Thanks, yeah I can't reproduce with those steps

**Pull request merged**
