### PR TITLE
[Upstream feature] Separate learn and young on the stats screen

### PR DESCRIPTION
**Pull request by mikunimaru**
Changed to display young and learn separately
 in the pie chart of the statistics screen.

The latest version of the anki desktop stats circle graph separates young, learning, and relearning, so AnkiDroid splits it as well.way.

## Purpose / Description
Changed to display young and learn separately in the pie chart of the statistics screen.

## Approach
Divided young+learn in the pie chart of the statistics screen into "young", "learn" and "relearn"
Screenshot_20210527-044532454_1
Screenshot_20210527-070222661 (1)

## How Has This Been Tested?
I actually opened the statistics screen and confirmed that the total value of the numerical values was correct.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikunimaru** [comment]
I found one while creating a pull request.

The constant, Consts.QUEUE_TYPE_DAY_LEARN_RELEARN, indicates a "learn" query.
The constant, Consts.QUEUE_TYPE_LRN, seems to indicate a "releran" query.

I was confused because the intuition and the meaning of the constant name were reversed.

Probably a careless mistake in the commit below.
https://github.com/ankidroid/Anki-Android/commit/34bd91169a7d27cc23a1fdc63073d1dce658bdb6

Fortunately, since the above constants were introduced, it seems that there have been no commits dealing with constants other than this time, so it seems that there are no additional bugs.

I think it's better to change the above constant name after merging or rejecting this commit.
(If the constant name is changed before this commit operation, it may cause a bug without conflict.)

**Comment by mikunimaru** [comment]
Unsearn and Suspended are missing from the display. I don't know the cause, but I'll try to fix it.

**Comment by mikunimaru** [comment]
I don't know where to fix the code.
I don't even know why only Buried remains.
I need some advice.

**Comment by mikehardy** [comment]
With apologies @mikunimaru - I'm not very experienced with this area of the code either but I'm mostly writing to say that your help fixing the 2.15 release was so valuable, thank you! I have been focused like a laser on that for the last few weeks and now I need to take a break while some family visits me from another country so I won't be able to give this the time it deserves. Hopefully others can give it a look but if not and you are patient I'll be back in a week or two. Thanks!

**Comment by david-allison-1** [comment]
If you hold "shift", you should see the version of the Anki stats that we emulate. 

I don't think we should aim to emulate the features of the new stats screen with the legacy stats, mostly because that brings us out of sync with both versions.

We'll get the new stats for free once we implement the V16 schema, which is upcoming (I'd like to say 2.16.0, but we'll see how the release schedule looks). We can then deprecate the old stats (these).

**Comment by mikunimaru** [comment]
@david-allison-1 
From a development perspective, I think that opinion is correct, but from a user perspective, I don't think there are any disadvantages to this change.

**Comment by mikehardy** [comment]
As the person that has most recently been fixing crashes and doing user support: there is no change without unintended consequences. I don't know *how* that is true but even the simplest changes bring consequences. We'd strongly prefer not to touch statistics right now as it is "dead code" from a future perspective as the Rust conversion continues

**Comment by mikunimaru** [comment]
Considering the opinions of the two, it seems better to close this pull request once.

**Comment by mikehardy** [comment]
I'm sorry about that but I do think it is best for this one area of the code (also template parsing I think...). The more UI-related areas of the code that are *not* stats will continue past the Rust migration though so most areas of the codebase with user impact are still wide open for change if interested - but I would definitely post an issue first describing the problem and proposed solution prior to doing the solution, so you can have an idea before working if it will be accepted

**Pull request closed without merging**
