### PR TITLE
Use inlined SVG for the replay button

### PR DESCRIPTION
**Pull request by ospalh**
I missed the discussion for #4104 and #4106.
I’m OK with a new, simpler button (although i think the old one was OK).
But i don’t like the white background of the image with anything but a white card background:
night_old
old_day_nonwhite

As the new replay icon is quite literally as simple as it can be, i came up with the solution of using inlined SVG, and CSS to change the color from black to white in night mode. (Inlined SVG does not work on Android 2.3, so the bit of version dependent code stays.)

night_new

Added benefits:
When you zoom in, the new button stays sharp:
old:
zoom_fuzz
new:
zoom_sharp

when you use non-black (or white) text, you can style the replay icon to your text color:

new_styled

### CODE REVIEW

**Comment by ospalh** [comment]
P.S.: The inline play button .png files where based on a [Google SVG](https://github.com/google/material-design-icons/blob/master/av/svg/design/ic_play_arrow_48px.svg) file.
The new SVG here is *not* that file, but an independent  recreation.

**Comment by Glutanimate** [comment]
Some of my templates could definitely benefit from a more flexible styling of the replay icon, so I really like this solution. Good job!

**Comment by timrae** [comment]
I don't think svg is supported down to sdk 8, did you test?

**Comment by hssm** [comment]
This is a neat solution to the problem. Great work!

@timrae This commit still uses the original png on gingerbread. It was mentioned above in between the images.

**Comment by ospalh** [comment]
@timrae I did push one version to GitHub that tried SVG for *all* versions and tried it on API 8 only after i had already started writing the PR.
… Then i wrote this as a second version.

**Pull request merged**
