### PR TITLE
fix: add merged pr to milestone

### LINKED ISSUE #10410: Automate process of adding merged PR to milestone and removal of labels
Might be useful to automate this in the longer-term, either with a check to confirm that all merged PRs have a milestone, or a bot reminder to set a milestone once merged

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/10353#issuecomment-1044721187_

### PR DESCRIPTION
**Pull request by krmanik**
## Purpose / Description
Add merged PR to current milestone.

## Fixes
Fixes #10410

## Approach
I have used permission to solve `Resource not accessible by integration`.  Additional permission `issues: write` added.
```
    permissions:
      contents: read
      issues: write
      pull-requests: write
```

## How Has This Been Tested?
Tested on local repository. It needs to test here. Hope it will work now.

## Learning (optional, can help others)
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Let's do it! :-)

**Comment by mikehardy** [comment]
IT WORKED IT WORKED IT WORKED!!!
Dude, you did it. Nice.

**Comment by krmanik** [comment]
Thanks
I think now that `issues: write` permissions in previous may have worked.

**Comment by krmanik** [comment]
For adding labels does not require `issues: write` but for milestone requires. So, they have already covered in github script but documentation is lacking. 

If you can tell, I will create PR with following.

```
name: PR Milestone

on:
  pull_request_target:
    types: [ closed ]

jobs:
  milestone:
    if: github.event.pull_request.merged == true && github.event.pull_request.milestone == null
    permissions:
      contents: read
      pull-requests: write    
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          await github.rest.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ github.event.pull_request.number }},
            milestone: 42
          });
```

**Comment by mikehardy** [comment]
Ah, so adding a label has specific APIs in the github script action, but adding a milestone is actually an update to the issue itself (via the update API). That makes sense since there is only one milestone per issue - it's part of issue metadata - whereas labels are a collection so you have to manage them via specific APIs.

Your script now looks much cleaner, assuming permissions issues write was the critical missing part

**Comment by krmanik** [comment]
Thats true. It better explanation for this.

**Pull request merged**
