### PR TITLE
[Kotlin Migration] Legendable 

### PR DESCRIPTION
**Pull request by codingtosh**
[Kotlin Migration] Legendable

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (130, 9): Val cannot be reassigned
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (135, 9): Val cannot be reassigned
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (136, 9): Val cannot be reassigned
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (137, 9): Val cannot be reassigned
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (138, 9): Val cannot be reassigned
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (139, 9): Val cannot be reassigned
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (140, 9): Val cannot be reassigned
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (141, 9): Val cannot be reassigned
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (142, 9): Val cannot be reassigned
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (183, 13): Val cannot be reassigned
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (209, 17): Val cannot be reassigned
```

**Comment by codingtosh** [comment]
> ```
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (130, 9): Val cannot be reassigned
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (135, 9): Val cannot be reassigned
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (136, 9): Val cannot be reassigned
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (137, 9): Val cannot be reassigned
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (138, 9): Val cannot be reassigned
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (139, 9): Val cannot be reassigned
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (140, 9): Val cannot be reassigned
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (141, 9): Val cannot be reassigned
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (142, 9): Val cannot be reassigned
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (183, 13): Val cannot be reassigned
> e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt: (209, 17): Val cannot be reassigned
> ```

I think these checks are failing due to changes that were made in this commit on ChartBuilder by another author:
https://github.com/ankidroid/Anki-Android/commit/c799a31ed454f8c5a8d41d7c02224369a08cc2a3

Not sure how changelist on this PR could have caused this...I could make another commit as a followup to ChartBuilder's migration here in this  PR, but that would mean the aforementioned commit causing this check failure would stay in the history. Please let me know how I should proceed.

**Comment by david-allison-1** [comment]
Could you rebase onto the current master, which should fix the issue

Strange that only this PR was affected

**Comment by codingtosh** [comment]
:thinking: hmm, still no dice. 
I'll do some deeper inspection later today.

**Pull request closed without merging**
