### PR TITLE
Migrate FunctionalInterfaces to kotlin

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

Migrates the FunctionaInterfaces.java file to kotlin following the migration guide. The migration couldn't be done directly and needed some refactoring because in java the `FunctionThrowable.apply` has a throws clause but the @Throws clause in kotlin doesn't accept generic type parameters:

        _Cannot use 'TEx' as reified type parameter. Use a class instead.
        Type parameter in a class literal is deprecated in an annotation argument_

My solution was to rename the `FunctionThrowable` to `FunctionThrowsJSONException`(and use a `@Throws(JSONException::class)`) because there's only one place where this interface is used(Collection.fixIntegrity()) and there the 3rd parameter is declared as `JSONException`. It should probably be decided if this interface should be scrapped as there's only one usage of it or, once the codebase is only kotlin, keep it generic and remove the generic @throws annotation.

## How Has This Been Tested?

Ran the usual tests.

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — COMMENTED** [review]
Do you think this one would be better blocked on `Collection` moving to Kotlin. 

After this, we can probably remove the method

**Comment by lukstbit** [comment]
@david-allison Should I close this one? Or should I make it a draft so it can be found if be others if they try to migrate it before Collection?

**Comment by david-allison** [comment]
Let's draft it.

Just to note: I'd be happy if you said "I'd prefer to merge it now"

**Comment by lukstbit** [comment]
After the migration of Collection.java to kotlin and the increased usages of FunctionThrowable I removed its third generic parameter and made FunctionThrowable to throw JSONException to migrate it to kotlin.

**Review by david-allison — APPROVED** [review]
Great! Hopefully we can remove this class completely

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
