### PR TITLE
startActivityForResult migration in Preferences.kt

### PR DESCRIPTION
**Pull request by divyansh-dxn**
## Purpose / Description
Remove usage of depricated startActivityForResult()

## Fixes
Fixes a part of #8602

## Approach
1. Remove the `onActivityResult()` method and create an equivalent `ActivityResultLauncher`
2. Replace call to `startActivityForResult()`, call `activityLancher.launch()`

# How Has This Been Tested?
Passes all unit tests and runs as expected on Realme 6i 

https://user-images.githubusercontent.com/69595691/158453132-932f1969-abb2-4f19-9334-aa203f4f47a7.mp4

https://user-images.githubusercontent.com/69595691/158445981-16e8bf8b-5cb7-4b9d-8383-d9ee5730ef9a.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Change looks good. "After" and "Before" are the same video. Just confirming this was tested after

**Comment by divyansh-dxn** [comment]
> 

Yeah! That's a mistake. I'm updating it.

**Review by david-allison — APPROVED** [review]
Look great!

**Review by mikehardy — APPROVED** [review]
thank you!

**Pull request merged**
