### PR TITLE
Assertion to try to debug https://github.com/ankidroid/Anki-Android/issues/6383

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This is related to https://github.com/ankidroid/Anki-Android/issues/6383
I add an assertion, so that if the bug occurs again, we get more interesting informations: e.g. the name of the deck whose parent is not seen. 

Normally, checkIntegrity has added the parent of all decks. The sorting function should ensure that parents are seen before the children. So either it's a problem related to normalization or something similar, in which case it may help understand it (assuming at least that Acra does not break unnormalized unicode)
If, as I suspect, it's a problem related to the fact that the set of deck was changed while the method is executed, i.e. because of sync or renaming... then this will occur so rarely that I don't expect to see many bug reports, and I don't really see how to get interesting information to reproduce it.

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Currently, it crashes with "java.lang.NullPointerException: Attempt to read from null array"
Now it will crash with a slightly more meaningful error message.

There are many ways to reduce the risk. For example, if I detect that the parent is missing, restarting deckDueList. I can use a boolean to know whether it's first or second try. Hopefully, the second try will work when the first failed. That would add complexity, it may not solve the problem if my conclusions were wrong, and make the code different from the one of ankiweb.
We could also just compute an arbritrary value, such as 99999. The problem here deals with computing limits, it would mean that we would not be propagating parents value to their children when the parent can't be found. It means that users would potentially see that there are more card to review in the subdeck than the actual number of cards to review. I fear that this problem will be quite harder to debug than just a crash if we ever get a bug report about it.

That's why I made so many long comments about this problem. I see no simple solution here.

**Comment by david-allison-1** [comment]
Is there a better solution that won't crash in the meantime? This bug will block people from syncing.

**Comment by Arthur-Milchior** [comment]
I already told you all solutions I see.
Appart from making a big tru catch in sanityCheck and just reject, because the exception probably indicates that the sanity check failed

**Comment by mikehardy** [comment]
I understand this would crash with or without the now-more-obvious crash. So as an incremental improvement I am inclined to merge this.

I've been thinking about how to reduce risk etc and I think you are on to something Arthur. All I can think of is that if this is going to throw an unchecked exception it would be useful to modify the callers by wrapping them in try/catch and logging the information there where you have more information about what AnkiDroid was *trying* to do, and maybe there is a possibility to fail gracefully at that level

**Comment by mikehardy** [comment]
This is waiting for feedback on the last comment

**Comment by Arthur-Milchior** [comment]
I really don't see any place where I can retrieve if this error occurs. There is really no reason for it to occur in the first place. 
We could theoretically just decide not to show the deck without parent, but there is no sens in doing that either

I would expect the error message and stack trace to give as many information as I could hope to get anyway

**Comment by mikehardy** [comment]
@david-allison-1 I'm thinking this is as good as we can get to diagnose what's causing the crash and am leaning towards not just merging but cherry-picking to any eventual 2.12.2 (if it's needed, so far, quiet there)

It's still a crash but it's not a regression and adds information

**Comment by mikehardy** [comment]
That's a reasonable ask and a good idea - @Arthur-Milchior add comment with reference to the bug (just 'temporary for diagnosis of bug #6383' is sufficient for me)

**Comment by Arthur-Milchior** [comment]
Done

**Pull request merged**
