### PR TITLE
Update Preferences to use PreferenceFragments on new APIs

### PR DESCRIPTION
**Pull request by timrae**
I also removed the `useBackup` preference as it was taking too much time to get it working.

I've left some remnants of it commented out so that it could be added back later, but I'm personally in favor of removing this setting entirely, as we already allow reducing backup number down to 1 (for the purpose of saving space), and it runs in the background anyway (therefore doesn't really have any effect on performance) -- so I can't imagine any scenario where someone would want to completely disable backups.

Finally, I had to move the About dialog into the bottom of advanced settings. In the future I'd like to merge help, feedback, and about all into a single dialog, but for now this will have to do.

### CODE REVIEW

**Comment by timrae** [comment]
@hssm 
Could you please test this on your tablet, and merge if it's stable enough and you're happy with the other changes?

**Comment by hssm** [comment]
Nice work! The tablet version looks a lot better. So far it seems to work well on my devices. The phone version feels a little sluggish to me however. It might just be the transition animations, I'm not sure.

Wouldn't setting the max number of backups to 0 achieve the same thing as disabling backups (and making the `useBackup` setting redundant)? We could change the minimum to 0 and upgrade any preference that had `useBackup` disabled to set the max to 0.

**Comment by hssm** [comment]
Never mind the sluggish comment, it's about the same as gmail and other apps. It's just the addition of the animation that makes it feel that way compared to before.

**Comment by timrae** [comment]
Re: `useBackup`
Of course we *could* allow the user to set the slider to 0.... However, currently when the CheckBox is unchecked we show the user a warning, and then go and delete any existing backups. It's a bit of chore to re-implement that

**Comment by timrae** [comment]
Maybe we could remove that delete functionality for now while still allowing disabling via setting the slider to 0...?

**Comment by hssm** [comment]
That sounds like a good way to do it.

**Comment by timrae** [comment]
OK that's done

**Comment by timrae** [comment]
I fixed that bug where AnkiDroid would refuse to boot when we specify an upgrade version in the future as well

**Comment by hssm** [comment]
Great, thanks.

**Comment by hssm** [comment]
Hmm... I have blank DeckPicker after merging this.

**Comment by timrae** [comment]
You mean do decks show up? Alpha35 is looking good on my Xperia phone

**Comment by hssm** [comment]
Nope no decks. It's weird, the collection is loading because I can open up settings or statistics, and after I do the DeckPicker works normally afterwards. I'll try and debug it.

screenshot_2015-06-09-18-58-05

**Comment by timrae** [comment]
It may be a long shot, but did you try doing a fresh install?

**Comment by timrae** [comment]
The only thing I changed in the DeckPicker was the upgrade code... I guess it's possible that I messed up the logic there

**Comment by hssm** [comment]
Okay it works fine after the version bump (I tested it before that commit) so it's probably the upgrade code.

**Comment by timrae** [comment]
Ah OK thanks. At least it's better than just crashing like it used to I guess lol, I'll try take a look at some point

**Comment by hssm** [comment]
Yeah it's a more obvious symptom this time around. I remember it freezing in an infinite loop instead of crashing before, so this is at least better.

**Pull request merged**
