### PR TITLE
NF: remove unused string

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This will ensure that we don't loose time looking to screeshot them

### CODE REVIEW

**Comment by david-allison-1** [comment]
```
  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/res/values-fi/08-widget.xml:49: Error: The plurals "widget_cards_in_decks_due" in values-fi has no declaration in the base values folder; this can lead to crashes when the resource is queried in a configuration that does not match this qualifier [MissingDefaultResource]
      <plurals name="widget_cards_in_decks_due">
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/res/values-fi/08-widget.xml:53: Error: The plurals "widget_decks" in values-fi has no declaration in the base values folder; this can lead to crashes when the resource is queried in a configuration that does not match this qualifier [MissingDefaultResource]
      <plurals name="widget_decks">
               ~~~~~~~~~~~~~~~~~~~
```

**Review by mikehardy — APPROVED** [review]
Hmm - odd that with current lint rules we are *forced* to purge things from the translations when normally it is illegal in our development process to do so. Not a high priority item but an unwanted side effect of stricter lint in this case

**Comment by Arthur-Milchior** [comment]
Don't hesitate to revert if you figure out why and want to respect our process. I do care about English version because it's what people are asked to translate. I absolutely don't care about the remaining since their only cost is in the size of the compiled program, and that probably don't increase the size noticeably.

I guess one intermediate solution could have been to just see what strings are unused in English and delete those strings that are both newly deleted in english and have plural.

But honestly, I don't know an easy way to automate searching for all instances of a string ressource in all translation, so it sounds like an even longer and more boring process in order to deal with translation, which is already taking me far more time than I thought

**Comment by mikehardy** [comment]
No reason to revert or anything, was just something I noticed - if you delete something in "values/" then the next time I do an i18n sync with crowdin, crowdin itself will purge out the remnants in "values-NNN/". So it was just a mention that in order to actually lint things *and remove a values/ string now* you have to purge it out of the others.

I'd actually vote for merge-without-that-CI-passing for unused strings and maintain a strict prohibition on touching "values-NNN/" entries still

**Pull request merged**
