### PR TITLE
Get next time for review in WebView

### PR DESCRIPTION
**Pull request by infinyte7**
## Purpose / Description
When redesigning card in CSS & JS, then it may required to show next review time below buttons. This is continuation of #6307

## Fixes
Fixes _Link to the issues._

## Approach
Added javascript interface in WebView settings then added functions in under
```@JavascriptInterface```

## How Has This Been Tested?
Tested on emulator,
Add following function in ```<script>``` tag in card templates, then use at/below buttons designed in css & js
```javascript
<script>
    console.log(AnkiDroidJS.ankiShowNextTime1());
    console.log(AnkiDroidJS.ankiShowNextTime2());
    console.log(AnkiDroidJS.ankiShowNextTime3());
    console.log(AnkiDroidJS.ankiShowNextTime4());
</script>
```

## Learning (optional, can help others)
https://developer.android.com/reference/android/webkit/WebView#addJavascriptInterface(java.lang.Object,%20java.lang.String)

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code

### CODE REVIEW

**Comment by infinyte7** [comment]
This will be useful when card developer designing cards and want to show next time below custom answer buttons.

**Comment by infinyte7** [comment]
Is there any improvement for this PR?

**Comment by mikehardy** [comment]
Hi @infinyte7 there is a conflict right now that needs resolution but I think the main thing is just that we're a bit constrained by available time so we haven't had a good look yet, sorry

**Comment by infinyte7** [comment]
It's okay. When you have time then review this PR.
Thank you.

**Comment by infinyte7** [comment]
It will be good with a page containing details and usage of all functionality related to ```webview / java``` or ```javascript interface``` in wiki page.

**Comment by mikehardy** [comment]
Nice! I like that (the documentation adds) - would be good perhaps to cross-link to the HTML/JS debugging page, and also directly link to card.js internally as the "source of truth", plus start adding information about API registration and the reason behind it. Might be good to make a whole separate page for "AnkiDroid Javascript API" developers and link to *it* from where you've started adding things

And it looks like there's a conflict now in one of the files, possibly because of a related change from you that I just merged

**Comment by infinyte7** [comment]
Yes, I will add the all information as suggested in a separate page.

**Comment by mikehardy** [comment]
Just waiting for conflict resolution then re-request review from me @infinyte7 and I'll mark it pending merge to make sure CI goes green

**Comment by infinyte7** [comment]
How can I add re-request review from you @mikehardy ?

**Comment by mikehardy** [comment]
Up at the very top right you'll see our review states, and you can hit the little re-do icon for it to trigger a request to me (which gives me a notification, so I know to do it!)

**Comment by infinyte7** [comment]
Is conflict resolved or should I create a separate PR? @mikehardy

**Comment by david-allison-1** [comment]
@infinyte7 If you scroll down, you should be able to see: 
image

The warning at the bottom means there's still a conflict to be resolved

**Comment by infinyte7** [comment]
It seems resolved.
Capture

**Pull request merged**
