### PR TITLE
chore : Redundant Package `DialogUtils`

### PR DESCRIPTION
**Pull request by neeldoshii**
Since the customstudydialog is now migrated(#15459) dialog Utils is no longer used.

### CODE REVIEW

**Comment by david-allison** [comment]
Don't need an issue, feel free to add a PR

**Comment by neeldoshii** [comment]
> Don't need an issue, feel free to add a PR

If I am not wrong, I created the PR?

**Comment by david-allison** [comment]
🤦  I'm still getting used to my new GitHub theme, thanks!

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
Note: I've `reword`ed this PR

**Pull request merged**
