### PR TITLE
feat(tests): Apple Silicon Support

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description

`anki-android-backend-testing` contains pre-compiled Rust code so Robolectric can load it and run natively.

We can't currently include an Apple Silicon (AS) dylib inside `anki-android-backend-testing `(`cross` doesn't compile AS code yet)

## Fixes
Fixes https://github.com/ankidroid/Anki-Android-Backend/issues/164

## Approach

But, we can compile an AS dylib on an AS Mac and reference it.

So we include the `dylib` in the releases folder of `Anki-Android-Backend` and add functionality to specify an environment variable to load this `dylib` from disk, instead of from the `.jar`

**Instructions (for 0.1.10):**

Download librsdroid-arm64.dylib from https://github.com/ankidroid/Anki-Android-Backend/releases/tag/0.1.10

And add the following environment variables:
one to the path and one for the version

```
export ANKIDROID_BACKEND_PATH="/Users/davidallison/StudioProjects/Anki-Android-Backend/rslib-bridge/target/aarch64-apple-darwin/release/librsdroid-arm64.dylib"
export ANKIDROID_BACKEND_VERSION="0.1.10"
```

Library generated from:
```
davidallison@Davids-MBP rslib-bridge % pwd
/Users/davidallison/StudioProjects/Anki-Android-Backend/rslib-bridge
rustup install 1.54.0
rustup default 1.54.0
cross build --release --features no-android --verbose --target aarch64-apple
```
on an AS MacBook

## How Has This Been Tested?

Tested the version mismatch case and the valid case

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
backwards-compatible so should have no impact on existing users
incremental improvement as new M1 users can now use arm64 JDKs

--> LGTM

**Comment by mikehardy** [comment]
The actions are actually running, but status is not showing up here. Odd.

**Comment by david-allison** [comment]
@viciousAegis FYI

**Comment by david-allison** [comment]
We probably want to follow up with instructions for M1 macs if `.init()` fails, but I'll leave that as lower priority than getting myself unblocked.

**Comment by mikehardy** [comment]
unit tests passed (twice) and that's the key here

**Pull request merged**
