### PR TITLE
fix crash due to `lateint var` not initialized

### LINKED ISSUE #13527: [BUG]: Check Media causing crash
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Deck Picker 
2. Check Media

### Expected behaviour

Media check result dialog is shown

### Actual behaviour

Crash

### Debug info

```text
Alpha95-debug
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Fixing callback dialog issue that caused crash

## Fixes
Fixes #13527

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
Tested on one plus Nord ce

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
@david-allison the current solution is working as a patch over the real issue, I would like to hear it from you how can we actually fix it by taking care of the `callback` var

**Review by lukstbit — CHANGES_REQUESTED** [review]
I don't think this should be merged as it doesn't solve/fix the real issue.

**Comment by criticalAY** [comment]
Yes it doesn't I already mentioned that I am waiting for David to respond

**Comment by criticalAY** [comment]
I think the condition was misplaced rather than the initialization issue I saw the logcat its clean now but I would still like to discuss it with David

**Comment by criticalAY** [comment]
This too

**Comment by criticalAY** [comment]
@oakkitten patching things up 101 but I am waiting for David to respond it should not be a big issue to fix I guess

**Comment by mikehardy** [comment]
Grumble all you want. I'll continue to merge things if they take too long. We're on a deadline.

**Pull request closed without merging**
