### PR TITLE
Add Cloze Icon

### PR DESCRIPTION
**Pull request by david-allison-1**
My own work. Created with Inkscape. Intended for the visual editor. 

GPL-3 for this project, but placing this under the public domain.

----

Inkscape: text tool - convert to path - use the measure tool and fix lines to same length via guides. Delete Guides. Center & Align. 

@mikehardy You were right, this was unexpectedly fun to do once I got over the initial hurdle. 

https://github.com/ankidroid/Anki-Android/blob/53c12a3045d8ff460b22dc8500d621f5e3608b41/AnkiDroid/src/main/vector_source/cloze_icon.svg

image

### CODE REVIEW

**Comment by david-allison-1** [comment]
@sudomain tagging to ensure we're not duplicating work

**Comment by sudomain** [comment]
Thanks for the heads up. I haven't started on the icon, so i'll use this  when I get around to #6014

**Comment by mikehardy** [comment]
Looks great! Glad it turned out fun, combo of it not being as hard as I thought with result of something looking good is satisfying...

**Comment by mikehardy** [comment]
released as 2.10alpha71 as soon as google finishes processing it

**Pull request merged**
