### PR TITLE
Reapply: remove JSON tests 

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
A problem with macOS CI caused a revert of "remove JSON tests". This was caused by a really broken test

This commit was introduced in: https://github.com/ankidroid/Anki-Android/commit/2c76360f889838f66130b47061c14af774588da4
reverted in https://github.com/ankidroid/Anki-Android/commit/4408900b73673291fc8c48be535d28f5f1dfb3a2

Test is fixed in this PR

## Fixes
Related: #13298 - we should close once we get a regression test in so this buggy test would fail CI

## Approach
Diagnose a test which hung the testing process (AFAIK, was happening since I got back to the project)

Mark it as flaky

## How Has This Been Tested?
Test only: Let's see CI

## Learning (optional, can help others)
⚠️ This does not fix the fact the error was not reported in the test suite

The issue was a circular dependency (`ClassCircularityError`) caused by mocking `Collections`
```
Exception in thread "Test worker"
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Test worker"
FAILURE: Build failed with an exception.
```

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Likely flakes due to the cutoff time. 

Might be worth ignoring

**Comment by mikehardy** [comment]
> The issue was a circular dependency (ClassCircularityError) caused by mocking Collections

Curious how you finally got it down to that one - I was incrementally increasing logging to determine the stack that was hanging the worker but hadn't been able to see it. I mentioned the logs were noisy so there's a chance that I just missed it - did you just see it pop out no problem once you reduced log noise or do you have a better trick then showing full stacks and increasing verbosity of the test run?

> 2023-02-26T03:46:33.3579873Z SchedV2Test > test_learnV2 FAILED

Re-running

Flakes on cutoff time - perhaps, isn't that what all the MockTime stuff was for though? I suppose we don't have that injected into the backend 🤔 

Maybe there could be a "DayCutoffFlaky" sub-annotation 😆 but 🤔

**Review by mikehardy — APPROVED** [review]
Okay, this one is good to go again pending CI
All the related issues have a fair bit of interest for me but are a) not the true priority at the moment and b) being tracked on their own
So this stuff may finally be peeled out

**Comment by mikehardy** [comment]
This one's been reviewed before and passed, just had a test harness interaction. As such not marking for second review, just marking pending merge

**Comment by mikehardy** [comment]
Now we've got windows saying pagefile setup script exited with bogus status, and macos-latest gradle setup timed out - all sorts of flaky and these are not normal ones. Github status seems green per their status board, will re-run the failures again...

**Comment by david-allison** [comment]
> Curious how you finally got it down to that one

Sadly: manual work 
I was frustrated by a hanging test run (all tests passed, but the program didn't finish)

Manually tested per package: found it was `utils`

Went through each class individually and there was no hang, only the folder

Started narrowing down the collection of files which caused the hang (starting with JSONArray), and it clicked that I was handling the same issue

Went through per class. Discovered that `UniqueArrayList` passed tests, but showed a gradle error.

Added `@RunsWith` to the file

All tests after the broken test failed

Had a quick look into fixing the mock, then left it for later with an `@Ignore`

**Pull request merged**
