### PR TITLE
improvement(i18n): link 'Re-sync translations'

### PR DESCRIPTION
**Pull request by david-allison**
`[Re-sync translations](https://github.com/ankidroid/Anki-Android/actions/workflows/sync_translations.yml)` => [Re-sync translations](https://github.com/ankidroid/Anki-Android/actions/workflows/sync_translations.yml)

Should save a few clicks

⚠️ Untested

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
+1
it can't ever be fully auto but it is getting more and more helpful, yes

**Comment by david-allison** [comment]
I mean... it can be better still

I don't think we have the timeout documented in the repo, and it may have changed

If there still is one: have CI wait/schedule a job for the next valid time

**Comment by mikehardy** [comment]
I believe 40mins is minimum cooldown, less than that still doesn't work, but I don't think 45 is strictly required

**Comment by david-allison** [comment]
I just did 30 and it worked

**Pull request merged**
