### PR TITLE
Reenable DeckPickerTest

### LINKED ISSUE #9282: Stabilize / re-enable "open study options" instrumented test in CI
Ignoring it in CI now pending an issue I will peel off about stabilizing root view matching, but now it runs successfully locally and won't gum up CI runs.

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/9205#issuecomment-881542544_

There is related discussion on the original PR #9205, a solution will likely involve using a specific RootMatcher in CI

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Fixes #9282

### CODE REVIEW

**Comment by david-allison** [comment]
There were multiple emulator test failures. Please remove the label and request a review if these were flakes

**Comment by Arthur-Milchior** [comment]
All failures are unrelated to the two tests I re-enabled. So yeah for review

**Comment by Arthur-Milchior** [comment]
Would anyone have an idea why there is systematically failure with `testCustomSchedulerWithRuntimeError` related to Reviewer test class?  That seems entirely unrelated to the current change

**Comment by Arthur-Milchior** [comment]
This is rebased on top of #17419.

**Review by david-allison — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
let's do it
I just force-pushed but it is nothing except a rebase to current main
I'll let CI be my guide with merge-when-ready + merge-queue

Thanks @Arthur-Milchior - you've got a lot of cleanup stuff in the queue that should be able to land, thanks for your patience - I was laser-focused on individual contribution to decrease crash errors so spent zero time on shepherding PRs but I'll shift focus back to that after 2.20 starts beta cycle

**Pull request merged**
