### PR TITLE
Fix widget crash if external storage not mounted

### LINKED ISSUE #6214: Widget Crashes if External Storage is not mounted
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/14e9ae61-89c4-44f8-8b41-7f9c35f7d8b0

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Context.registerReceiver(android.content.BroadcastReceiver, android.content.IntentFilter)' on a null object reference
at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:558)
at com.ichi2.widget.AnkiDroidWidgetSmall$UpdateService.buildUpdate(AnkiDroidWidgetSmall.java:12)
at com.ichi2.widget.AnkiDroidWidgetSmall$UpdateService.doUpdate(AnkiDroidWidgetSmall.java:2)
at com.ichi2.widget.WidgetStatus$UpdateDeckStatusAsyncTask.onPostExecute(WidgetStatus.java:6)
at com.ichi2.widget.WidgetStatus$UpdateDeckStatusAsyncTask.onPostExecute(WidgetStatus.java:1)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5852)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

Reproduction: set `mounted = false` on this branch:

https://github.com/ankidroid/Anki-Android/blob/6e34663ba9d09dc8b023230811c3185b72ee7eec/AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java#L148

Cause: `Service.getContext()` is null, but is implicitly used in the following line:

https://github.com/ankidroid/Anki-Android/blob/6e34663ba9d09dc8b023230811c3185b72ee7eec/AnkiDroid/src/main/java/com/ichi2/widget/AnkiDroidWidgetSmall.java#L175

<details><summary>My LogCat</summary>

```
2020-05-18 13:07:36.353 24605-24605/com.ichi2.anki D/WidgetStatus: WidgetStatus.update(): already running or not enabled
2020-05-18 13:07:36.355 24605-24605/com.ichi2.anki D/UIUtils: saveCollectionInBackground: start
2020-05-18 13:07:46.159 24605-24605/com.ichi2.anki D/WidgetStatus$UpdateDeckStatusAsyncTask: WidgetStatus.UpdateDeckStatusAsyncTask.onPostExecute()
2020-05-18 13:07:46.174 24605-29607/com.ichi2.anki D/CollectionTask: doInBackgroundSaveCollection
2020-05-18 13:07:46.183 24605-29610/com.ichi2.anki D/CollectionTask: doInBackgroundSaveCollection
2020-05-18 13:07:46.188 24605-29610/com.ichi2.anki I/chatty: uid=10333(com.ichi2.anki) AsyncTask #19 identical 1 line
2020-05-18 13:07:46.191 24605-29610/com.ichi2.anki D/CollectionTask: doInBackgroundSaveCollection
2020-05-18 13:07:46.420 24605-24605/com.ichi2.anki D/AnkiDroidWidgetSmall$UpdateService: buildUpdate
2020-05-18 13:08:07.730 24605-24605/com.ichi2.anki D/AndroidRuntime: Shutting down VM
2020-05-18 13:08:07.801 24605-24605/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 24605
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Context.registerReceiver(android.content.BroadcastReceiver, android.content.IntentFilter)' on a null object reference
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)

...<snip>....
```
</details>

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
A service has no `baseContext`, so `registerReceiver` threw. See linked issue.

## Fixes
Fixes #6214 

## Approach
Use the application context instead.

## How Has This Been Tested?

Tested on my phone and modified code, can now take the branch without a crash

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
> Interesting - I wonder how long that's been in there...

9 years, judging from git blame

**Comment by mikehardy** [comment]
Holy __, diggin' *deep* in to the bag of crashes with this one. I believe that's a good sign. I'll push a 2.10.3beta2 with this and the current queue shortly. I want to finish language preening first and maybe we just go with the anti-flicker patch for now since it restores previous behavior even if that is a UI error. Which is just to say this'll be one less crash in the wild shortly - I haven't looked at the 2.10.x stats yet but they should still be floating down

**Comment by david-allison-1** [comment]
I really want to get #6191 (DeckPicker background) into the next release if at all possible.

I think I've got almost all of the crashes into GitHub issues now, so we'll gradually tend towards 0. #6213 is a massive one that'll help (about 6% of ACRA for 2.10.2). 

#6036 (slow imports) will be massive if I can land it.

**Comment by mikehardy** [comment]
Anything that lands will go, and I think it'll be a couple days yet. Anything that doesn't make it, there's always 2.10.4 :-) - I agree with all your statements in general though and thanks for sharing your current stack, just that there's no release train leaving the station permanently. I can make a new release really quickly. I can do a couple a *day* if the benefit justifies it

**Comment by mikehardy** [comment]
going out in 2.10.3beta2 and will be in 2.11alpha6

**Pull request merged**
