### PR TITLE
Fix analytics constants tests

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
I had a test failure when pulling my `master` branch 

## Approach
* Fix failure
* Refactor code

## How Has This Been Tested?

Unit test only

## Checklist
- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
@mrudultora Just for your reference on the refactorings in https://github.com/ankidroid/Anki-Android/pull/8599/commits/98dd7f31c33900b80c891263eb1584f87ae400b9

**Comment by mrudultora** [comment]
> @mrudultora Just for your reference on the refactorings in https://github.com/ankidroid/Anki-Android/pull/8599/commits/98dd7f31c33900b80c891263eb1584f87ae400b9

That's much cleaner.

**Comment by david-allison-1** [comment]
> > @mrudultora Just for your reference on the refactorings in [98dd7f3](https://github.com/ankidroid/Anki-Android/commit/98dd7f31c33900b80c891263eb1584f87ae400b9)
> 
> That's much cleaner. Why this test was failing ? I think it is because I was adding items to arraylist in the nested class, rather than a static block.

I didn't look into exactly why, but the setup method was called twice when I ran all tests from Android Studio: as the list was static and we never cleared the list, it meant that we added duplicates

**Review by mikehardy — APPROVED** [review]
LGTM

**Pull request merged**
