### PR TITLE
NF: check database result puts a database result

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Putting an array of object is usulessly complex here

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
It seems to me that TaskData save a bunch of unrelated type.

Anyway, my goal behind all of this PR is to eventually removes as many TaskData as possible by using the various subclass of CollectionTask I created and using type parametrization.
But in order to do it cleanly, I should try to avoid array of objects and clean the types as much as possible

**Comment by Arthur-Milchior** [comment]
This can get closed if/when #6758 get merged. I had the hope that it would make #6758 easier to read, but now that the whole work is done, I guess this PR would not have made a huge difference anyway

**Comment by mikehardy** [comment]
waiting on resolution of #6758

**Comment by Arthur-Milchior** [comment]
I think you got the dependencies wrong. The goal of this bunch of small PR was to make the big PR simpler by removing a part of it. More precisely, since the goal of https://github.com/ankidroid/Anki-Android/pull/6758 is to have tasks correctly typed, I wanted to introduce actual type in separate PR so that, when we consider https://github.com/ankidroid/Anki-Android/pull/6758 we don't have any Object[] anymore.

That did not please David, because I was introducing more types in TaskData and he prefers to avoid it. As my ultimate goal is to entirely remove Task Data, I do not actually care a lot. If some people believe those small PR decrease the quality of code, they can disappear and everything will be allright by me.

What is sure is that if https://github.com/ankidroid/Anki-Android/pull/6758 gets merged, those bunch of small PR will be closed as they won't be relevant anymore

**Pull request closed without merging**
