### PR TITLE
Update localization deps / fix linting errors and formatting errors and test those in CI

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

- dependabot had some PRs for localization and I wanted to examine them locally
- eslint needed a forward port to v9
- while in there I noticed that the code wasn't currently linting correctly or formatted correctly
- did the linting and formatting and added checks for same in CI

⚠️  !!! **NOTE: this will require org settings changes on protected branch rules for main to change the name of the required check from `Lint Debug` (which is kind of meaningless) to be the two checks `Lint Kotlin` and `Lint Javascript` now**

## Fixes

- Related #16799
- Related #16807
- Related #16777

## Approach
Slow incremental fixes with independent commits...

## How Has This Been Tested?

it's all testing

## Learning (optional, can help others)

Quality is a slow process and the work's never done

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
Minimal lint fixes, LGTM if it compiles and runs

**Comment by mikehardy** [comment]
Definitely runs locally :-)

Intended merge process for this one is:
- [ ] merge to dependency-updates branch
- [ ] create + merge a dependency updates PR to main from dependency-updates - note this will blow up the org required checks when merged, and will require a forced merge, but these are always forced anyways since we squash-merge them
- [ ] alter org required checks for main branch to be `Lint Kotlin` and `Lint Javascript`
- [ ] close/reopen any open PRs to re-run CI and get the new checks run so they go green on all newly required checks (vs the old checks set)

I think that's it anyway

org branch checks settings are here https://github.com/ankidroid/Anki-Android/settings/branch_protection_rules/17281133

**Review by krmanik — APPROVED** [review]
LGTM, Thanks

**Comment by david-allison** [comment]
Waiting for @mikehardy to merge with the above plan

**Pull request merged**
