### PR TITLE
lint[tests]: NewApi

### PR DESCRIPTION
**Pull request by Arnold2381**
## Fixes
Related: #9538 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Arnold2381** [comment]
@david-allison-1 Please take a look.

**Comment by david-allison-1** [comment]
Two should go in: others can be fixed to work without the `RequiresApi`

**Comment by Arnold2381** [comment]
@david-allison-1 I am unable to solve this error

when i am running `./gradlew ktlintFormat` i am getting this error 

```
> Configure project :AnkiDroid
WARNING:The option setting 'android.jetifier.ignorelist=bcprov' is experimental.

> Task :AnkiDroid:runKtlintFormatOverTestSourceSet FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':AnkiDroid:runKtlintFormatOverTestSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > D:\opensource\Anki-Android\AnkiDroid\src\test\java\com\ichi2\anki\RoboelectricTest.kt (The system cannot find the file specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 26s
11 actionable tasks: 1 executed, 10 up-to-date
```
My file name is `RobolectricTest.kt`, idk where is it getting `RoboelectricTest.kt`

**Comment by mikehardy** [comment]
I believe this should be closed as superceded by #9647  ?

**Comment by Arnold2381** [comment]
@mikehardy there were still some changes left. I will commit the remaining changes in this PR.

**Pull request closed without merging**
