### PR TITLE
Fix inconsistent type for placeholder in japanese translation

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description
In the [last translation sync](https://github.com/ankidroid/Anki-Android/pull/14113) I didn't notice that there was a switch from a string placeholder to a number placeholder in one of the Japanese translations.

## How Has This Been Tested?

Ran lint like I should have done from the start.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by lukstbit** [comment]
I'll fix it on Crowdin and do another sync.

**Comment by snowtimeglass** [comment]
I apologize for the time and trouble I have caused you... Thank you for the work.

**Comment by lukstbit** [comment]
@snowtimeglass No problem, I should have ran lint before merging.

**Comment by snowtimeglass** [comment]
@lukstbit Thank you for the kind words. I should not have heedlessly used suggested phrases from translation memory and machine translation, especially when they include placeholders. Also, I did not review them enough. I will learn from my repeated lapses, and change my behavior patterns.

**Pull request closed without merging**
