### PR TITLE
Note editor addon

### LINKED ISSUE #7959: [Feature] JavaScript Addons support for AnkiDroid
**Is your feature request related to a problem? Please describe.**
For Anki, addons can be made using Python. But for AnkiDroid JavaScript may be option to implement some of the addons. There are already some API have been exposed in AnkiDroid JS API. But deck developer have to tell or guide user to add ```HTML/CSS/JS```. So this is idea for having js addons. 

The addons made in javascript so it will be used in Anki Ecosystem as Anki Desktop and Anki Mobile use webview for reviewer. But the AnkiDesktop and AnkiMobile have not exposed the API like AnkiDroid JS API. So, in #7958 PR there are implementation for containing the addons to AnkiDroid only. It can be extented for AnkiDesktop and AnkiMobile if both have API.

But GOAL here is to have addon support so that all deck should share same ```HTML/CSS/JS```  like addon for AnkiDroid. The addons will use AnkiDroid JS API.

**Describe the solution you'd like**
#7958 . I am implementing this Feature but it requires some discussion and possible changes to make this feature more useful.

**Describe alternatives you've considered**
The alternative solution will be copying pasting the code to Card template manually.

**Additional context**
The workflow will be
1. User will download the addon ```.adaddon``` (AnkiDroid Addons) or ```.jsaddon``` (JavaScript Addon) files
2. Install using in app option (to be implemented)
3. Enable the addons, so that the contents of addons will be added to reviewer during review. 

捕获

```
Example of some Anki Addons that can be implemented
1. Progress Bar
2. Custom buttons at bottom
3. Card layout changes
4. Cards info during review
5. Clickable tag
etc...
```
The more API get exposed the more features will addon will have.

### PR DESCRIPTION
**Pull request by infinyte7**
## Purpose / Description
This continuation of previous PR #7958. As Anki desktop have python for creating addons. But in AnkiDroid Java and JavaScript can be used to create addons. This PR is implemented for running JavaScript addon. 

## Fixes
Fixes #7959 

## Approach
Most of enable and disable logic part and code of PR #7958 is used in this. But for note editor tool bar.
1. Created Horizontal recycler view at bottom 
2. Added button when SharedPreferences have enable status of addons.
3. Copy the index.js file code and pass to [js-evaluator](https://github.com/evgenyneu/js-evaluator-for-android/#call-a-javascript-function) function.

4. When a string selected in Note editor and Addon button pressed then selected text in FieldEditText passed to ```js-evaluator``` and the function defined in index.js file perform logic on that string then return it to caller.

## How Has This Been Tested?
1. Create addon with following file and folder structure and paste it in ```AnkiDroid / addons / ankidroid-js-addon-some-name```
```
ankidroid-js-addon-some-name
↳ package
    ↳ package.json
      index.js
      Readme.md
```

The ```package.json``` file contains following for converting space separated text to list.
```
{
  "name": "ankidroid-js-addon-bullet",
  "version": "1.0.0",
  "description": "Convert list to bullet",
  "main": "index.js",
  "ankidroid_js_api": "0.0.1",
  "addon_type":"note_editor",
  "addon_icon": "="
}
```

Note: The package.json must contains ```name, ankidroid_js_api, addon_type, addon_icon.``` Here addon icon single letter.

4. And ```index.js``` file contains following
```
function AnkiJSFunction(data) {
    var s = "";
    data = data.split(" ");
    for (i=0; i<data.length; i++) {
        s += "<li>" + data[i] + "</li>\n";
    }
    s = "<ul>" + s + "</ul>";

    return s;
}
```
Note: The name in index.js must be ```AnkiJSFunction``` it will be called by ```js-evaluator```.

5. Enable the addon from AnkiDroid->Addons->Note Editor Addons -> addon-name
6. Now use it in Note Editor

**Demo**

## Learning (optional, can help others)
https://github.com/evgenyneu/js-evaluator-for-android/
https://developer.android.com/guide/topics/ui/layout/recyclerview

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code
- [ x ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

**Comment by infinyte7** [comment]
I have tried multiple approach for text transformation. As it transform the text as per function deined in index.js but the previous selected not removed from edit text.
For example, the Field Edit Text have following text
```
AnkiDroid AnkiMobile AnkiDesktop
```
After selecting those text and then calling AnkiJSFunction from index.js function using js-evaluator, it transform the text return the following string to caller function
```
<ul><li>AnkiDroid</li>
<li>AnkiMobile</li>
<li>AnkiDesktop</li>
</ul>AnkiDroid AnkiMobile AnkiDesktop
```
The text ```AnkiDroid AnkiMobile AnkiDesktop``` is not cleared. I tried ```modifyCurrentSelection``` and ```mToolbar.onformat```  but didn't work.

**Comment by infinyte7** [comment]
Needs improvement

**Comment by infinyte7** [comment]
Update:
Layout show and hide using `arrow` button in toolbar

</img>

**Comment by infinyte7** [comment]
Update:
Show / hide addon list in toolbar using `arrow` button. 

</img>

**Comment by infinyte7** [comment]
Update:

```
AnkiDroid  -->  JS Addon
send deck name, model name, fields count, fields name and selected text in json format to js addon
```

```
AnkiDroid  <--  JS Addon
receive json format data with changed text and data that needs to be inserted to fields with index
```

provide these to js addon in json format and receive changed data in json format
```
AnkiDroid  -->  JS Addon
 { 
   "noteType": "Basic",
   "deckName": "Default",
   "fieldsName": ["Front", "Back"],
   "fieldsCount": 2,
   "selectedText": "Some selected text..." 
}
```

data changed by js addon and pass to AnkiDroid
```
AnkiDroid  <--  JS Addon
 { 
  "changedText": "some changed text...",
  "addToFields": { 
                 "0": "some text to field one",
                 "2": "some text to field two"
                 "3": "some text to field three" 
                 },
  "changeOption": "replace"
}
```

To be implemented
```
change option - replace, append, clear, default - with selected text
```

Usage of above implementation in new **[AnkiDroid Cloze Overlapper Mini JS Addon](https://www.npmjs.com/package/ankidroid-js-addon-cloze)**

<details>
<summary>View index.js</summary>

```js
function AnkiJSFunction(data) {

    var jsonData = JSON.parse(data);

    var selectedText = jsonData['selectedText'];

    var newJsonData = {};
    var fieldsData = {};
    if (jsonData['noteType'] == "ocloze-infi" && jsonData["fieldsCount"] == 26) {
        newJsonData["changedText"] = "";  // intentionally empty

        var list = selectedText.split("\n");

        var fullText = "";
        var len = list.length;
        var startField = 5;
        for (i = 0; i < len; i++) {
            var text = "";
            fullText += "<div>{{c21::" + list[i] + "}}</div>";
            for (j = 0; j < len; j++) {
                if (i == j) {
                    if (j > 0) {
                        text += "<div>" + list[j - 1] + "</div>";
                    }
                    text += "<div>{{c" + (j + 1) + "::" + list[j] + "}}</div>";
                } else {
                    text += "<div>...</div>";
                }
            }
            fieldsData[startField] = text;
            startField++;
        }
        fieldsData[25] = fullText;

        newJsonData["addToFields"] = fieldsData;
    }

    return JSON.stringify(newJsonData);
}
```

</details>

Cloze generated by js addon

</img>

**Comment by infinyte7** [comment]
Implemented: change selected text according to option : ```replace```, ```clear```, ```append``` and ```default```

<details>

<summary>Click to view index.js</summary>

```js
AnkiDroid  <-- JS Addon

function AnkiJSFunction(data) {

    var jsonData = JSON.parse(data);

    var selectedText = jsonData['selectedText'];

    var newJsonData = {};

    newJsonData["changedText"] = "<sub>"+ selectedText +"</sub>";

    // changeType options - replace, append, clear, default
    newJsonData["changeType"] = "replace";

    return JSON.stringify(newJsonData);
}
```

</details>

**Comment by infinyte7** [comment]
This continuation of previous PR #7958. So, I will mark it ready for review after merge of previous one. Some files are same in both PR.

**Comment by mikehardy** [comment]
Ugh - not stale just so maxed out stabilizing all the GSoC work on the release-2.15 branch

**Comment by infinyte7** [comment]
I will re-implement this js addons feature with more number of PR. I will divide this PR in small part so reviewing will take less time.

**Pull request closed without merging**
