### PR TITLE
Hide action bar together with system status bar in fullscreen mode

### PR DESCRIPTION
**Pull request by timrae**

### CODE REVIEW

**Comment by hssm** [comment]
I always envisioned this as an additional setting under gestures since you can map the functionality offered by the action bar to gestures and opt to remove it knowing you have all your options covered.

Since I use fullscreen mode and don't use gestures, I can't use any of the features in the action bar any more and there's no way to make it show up again. I was aware of this guideline and figured in our case we can disregard it to maintain functionality.

**Comment by timrae** [comment]
> Since I use fullscreen mode and don't use gestures, I can't use any of the features in the action bar any more and there's no way to make it show up again

I'm not sure what you mean... you can just swipe down to see the status bar and action bar... At least on my Lollipop device

**Comment by timrae** [comment]
Also with the new immersive mode, clicking an item on the action bar makes the status bar appear, it looks really dumb

**Comment by hssm** [comment]
Hmm... I'm also on Lollipop and it doesn't show for me.

**Comment by timrae** [comment]
even swiping from the bottom to show the navigation controls?!

**Comment by timrae** [comment]
From the docs:

> When immersive full-screen mode is enabled, your activity continues to receive all touch events. The user can reveal the system bars with an inward swipe along the region where the system bars normally appear.

**Comment by hssm** [comment]
I've done all kinds of swiping. The navigation bar and system status bar both appear but not the action bar. That's on both a Nexus 5 and Nexus 10.

**Comment by timrae** [comment]
Oh right, sorry I thought you were talking about the status bar. I thought this PR was gonna show the action bar whenever the status bar was shown, but I haven't tested it properly on my device, I'll take a look now

**Comment by hssm** [comment]
I've only been using it for a couple minutes but full screen mode actually looks really nice and clean now. It's hard to go back after using it.

**Comment by timrae** [comment]
It seems that `View.OnSystemUiVisibilityChangeListener()` is not even triggered on swipe down :-1: 
Thanks Google, for making something that should be easy so difficult, as usual

I'll do some searching later

**Comment by timrae** [comment]
F#$k Google, get it together:
http://stackoverflow.com/questions/19750700/detecting-when-system-buttons-are-visible-while-using-immersive-mode

**Comment by timrae** [comment]
Clearly I shouldn't skim-read the documentation, it's properly written there.
I guess we'll have to split it up into two preferences...?

**Pull request merged**
