### PR TITLE
Add stats provider

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description
Implement a stats provider for AnkiDroid, based on work by @MarcinMoskala 

## Fixes
- Fixes #4881 Responds to comment on original PR asking for a contract
- Moves original PR and API up to master (AndroidX, api levels etc)

## Approach
Original PR has info: #4881 

Contract and Provider were done with re-use of logic from card provider
I added a read-only permission so people didn't have to grant full access

## How Has This Been Tested?

I added a demonstration to the apisample, and it's a good thing - the query didn't work without a quick fix - https://github.com/ankidroid/apisample/pull/9

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
Also self-reviewed and polished this one. Best to review it commit-by-commit otherwise my extraction of ProviderUtils makes things terrible to review, but if I didn't extract that I would have duplicated a lot of security logic in StatsProvider. This affects the API so I will not merge this without review, but I think it's ready to go.

**Comment by timrae** [comment]
Perhaps you're not understanding the purpose of this contract file, since you're not using it in the sample project you made... The idea is that users copy the contract file and use that instead of hardcoding paths. Ideally it should be part of a higher level API like I mentioned in that PR.

**Comment by mikehardy** [comment]
Okay, so something like AddContentApi.java, how do you manage development across api and apisample? By which I mean how do you do a local "api build" such that apisample can consume it with gradle dependencies and everything? Just a gradle target and a mavenLocal() repo add in apisasmple? I only see a jar dumped into a sub-directory in the api build.gradle so I'm not sure how to iterate over on the apisample side

For google-analytics-java I have a local deploy (provided by maven as `mvn install`) that puts jar into $HOME/.m2 and then if I add mavenLocal() as a gradle dep, the version is ends in 'SNAPSHOT', and tell gradle to check changing (i.e., SNAPSHOT) artifacts every time, I have very nice cross-project iteration.

That would make working on the contract file and API a lot more friendly.

As for the UI, yeah it's tacked on :-). Here I figured I'd get extra credit for at least exercising the API (and finding a bug! and realizing permissions were unhandled in StatsProvider) and I get dinged on bad UX. I mean, you're right, but my inner child is going "do I have to..."

**Comment by mikehardy** [comment]
OK - I think can go for full-featured. Let me add some tooling across the projects to do what I mentioned (local maven install available on one side, dep resolution consuming local on the other) so the iteration isn't painful because no, I have no experience in contract files, and little experience in APIs - so I iterate a lot. I'll ping you again if I have questions or when they're in shape

**Comment by mikehardy** [comment]
This one doesn't necessarily hold up 2.9 because it doesn't involve strings - we can get betas out prior to completing it but I'm still worried about 2.9 timing - I'd rather see it happen sooner than later so I'm moving milestones

**Pull request closed without merging**
