### PR TITLE
refactor(preferences): Post-Kotlin Cleanup

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
I mentioned some issues via `KotlinCleanup` in: https://github.com/ankidroid/Anki-Android/pull/10456

This fixes most of the `@KotlinCleanup` annotations, and starts the "proper" refactor to idiomatic Kotlin.

Not massive, but I wanted to make a commit today.

## Approach
Lint on:

* rename variable 
* 'protected' visibility is effectively 'private' in a final class
* Variable is same as 'X' and can be inlined
* Cascade if should be replaced with when
* Fix variable names
* Always returns null type

Then some manual work

## How Has This Been Tested?
Untested, mostly automated refactorings

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Nice - all LGTM - esp nice trick cleaving out one TextUtils reference for less android platform dependency

**Comment by david-allison** [comment]
> Nice - all LGTM - esp nice trick cleaving out one TextUtils reference for less android platform dependency

This one's big, I'm almost considering linting it until we're clear of the Kotlin migration - we can probably knock a minute off our test run after we're 100% in Kotlin and fix the usages/tests.

**Comment by david-allison** [comment]
And with this, I (temporarily) join the [4k club](https://user-images.githubusercontent.com/62114487/157329445-e38c318c-ad65-4825-86dd-ccebe0812b65.png). 🥳

**Comment by mikehardy** [comment]
Hahahaha nice one. Welcome, or sorry ? :laughing:

**Pull request merged**
