### PR TITLE
Stop handling system's dark mode changes manually and fix dark mode on the app

### LINKED ISSUE #11982: [Bug] Follow system dark mode may not update the theme if the AnkiDroid widget is being used
###### Reproduction Steps

Quite specific to get it
1. Have "Follow system" as theme
2. Have AnkiDroid widget on your home screen (bug only happens with it)
3. Enable "Change automatically based on time" on the system's dark mode
4. Have AnkiDroid closed
5. Wait until system automatically changes the dark mode

###### Expected Result

App uses the new dark mode status (either light or dark)

###### Actual Result

App uses the old dark mode status

###### Debug info
On latest main

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

---

I didn't expect the widget to interfere with this. I know how to fix it, so I should push it soon

### LINKED ISSUE #12906: maybe extracting everything to a recreateIfThemeHasChanged method as an Activity's extension method could work
The same needs to be done on `DeckOptions.kt` and `FilteredDeckOptions.kt` as well (they are not `AnkiActivity`s and at the time I just duplicated the code as I expected to deal with it soon, but life took over my time). 

For reusability purposes, maybe extracting everything to a `recreateIfThemeHasChanged` method as an Activity's extension method could work

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/pull/12765#discussion_r1012245142_

### LINKED ISSUE #12958: [Bug] Night mode is not set for the whole app
###### Reproduction Steps
1. Have day mode switched on
2. Force quit AnkiDroid in the app info
3. Start AnkiDroid
4. Study cards
5. Switch night mode on
6. Back to the deck picker

###### Expected Result
Deck picker is in night mode

###### Actual Result
The app is in day mode

###### Debug info
AnkiDroid Version = 2.16alpha91

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36

ACRA UUID = 26e4486a-d86f-4fe9-84d4-2bf87a7c4d03

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
Fixes #12958
Closes #11982
Closes #12906 
part of #12832

## Approach
Initially when I added the `Follow system` option to set dark mode, I had to add `uiMode` to all the activities' `android:configChanges` because the context's configuration were being editted at `attachBaseContext` in order to configure the language. As languages are going to be properly managed after the merge of #12991, `uiMode` doesn't have to be handled manually anymore, which is going to make theme handling much easier and way less bug-prone

## How Has This Been Tested?

On SDK 33 emulator and on my phone, Android 12, One Ui 4.1, by changing themes and the system dark mode

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Blocked by #12991

**Review by david-allison — COMMENTED** [review]
Looks good on initial review 

Could you test this on the API level where "night mode" & "follow system" was introduced

**Comment by BrayanDSO** [comment]
Sure. Tested the upgrade from a 2.16alpha50 build and it worked correctly (follow system dark mode were introduced at 2.16alpha52)

**Review by david-allison — APPROVED** [review]
LGTM

**Review by mikehardy — APPROVED** [review]
Lots of deleted code, always nice to see ;-) - thanks Brayan!

**Comment by mikehardy** [comment]
I rebased this locally and checked it and it worked ✅

**Pull request merged**
