### PR TITLE
implement serde for Key Binding

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Key Bindings need to be serialized and deserialized from preferences

This brings in the code for #8078 to handle this aspect  of #6052 

## How Has This Been Tested?

Should be non-functional, unit tests lifted from the PR

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
blocked by #9193

Note: the implementation has not strongly been reviewed by me (and should be) before this goes in

**Comment by mikehardy** [comment]
Unit test failure looks legit ? 
```
        Caused by:
        java.lang.AssertionError: expected:<com.ichi2.anki.reviewer.PeripheralKeymap$MappableBinding@8c1b> but was:<com.ichi2.anki.reviewer.PeripheralKeymap$MappableBinding@745f>
            at org.junit.Assert.fail(Assert.java:89)
            at org.junit.Assert.failNotEquals(Assert.java:835)
            at org.junit.Assert.assertEquals(Assert.java:120)
            at org.junit.Assert.assertEquals(Assert.java:146)
            at com.ichi2.anki.reviewer.BindingAndroidTest.assertBindingEquals(BindingAndroidTest.kt:56)
            at com.ichi2.anki.reviewer.BindingAndroidTest.testFromString(BindingAndroidTest.kt:42)
```

**Review by mikehardy — APPROVED** [review]
LGTM! Also, because of this I learned of Rust "traits" via lookup of "what is serde" and seeing serde.rs :nerd_face:

**Comment by david-allison-1** [comment]
> LGTM! Also, because of this I learned of Rust "traits" via lookup of "what is serde" and seeing serde.rs 🤓

modem = modulator-demodulator
serde = serialiser-deserialiser

**Pull request merged**
