### PR TITLE
Kotlin migration Importer.java

### PR DESCRIPTION
**Pull request by divyansh-dxn**
## Purpose / Description
Kotlin Migration

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
oK with this, but needs to be explicitly checked against the `HEAD` of `main` before merging as this is very likely to conflict

**Review by lukstbit — CHANGES_REQUESTED** [review]
When you remove the KotlinCleanup also rebase on top of main.

**Comment by mikehardy** [comment]
> oK with this, but needs to be explicitly checked against the `HEAD` of `main` before merging as this is very likely to conflict

This ran with no hitches just now rebased against main/HEAD locally but I see luktsbit flagged it, so waiting for that :-)

**Comment by divyansh-dxn** [comment]
@mikehardy done rebase, everything is fine 👍🏻

**Review by lukstbit — APPROVED** [review]

**Pull request merged**
