### PR TITLE
Partially Solve #5238: Gradle 5 incompatibilities 

### PR DESCRIPTION
**Pull request by fajarnuha**
## Purpose / Description
Solve incompatibilities issue with Gradle 6, I haven't found solution for last 2 remaining deprecation in the issue, open for discussion

## Fixes
https://github.com/ankidroid/Anki-Android/issues/5238

## Approach
Change with new methods

## How Has This Been Tested?
running jacoco command as described in the issue

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
Hey, this is neat! Thanks for the help. Did the quick fix for just switching to these for the last 2 not work? https://docs.gradle.org/current/javadoc/org/gradle/api/model/ObjectFactory.html

Just curious

Also, there is some unrelated problem on Travis right now where all emulators are failing for some reason. It started on a previous PR and hasn't self-resolved apparently - not sure what it is, but I would disregard Travis status for a moment, this change is likely good though I will still attempt to work through the Travis issue before merging this

**Comment by mikehardy** [comment]
Ah, I just checked and I think those may be coming in from a plugin. I don't believe we are using them.

So as we get closer to Gradle 6 I imagine they will update and the rest of this will resolve on it's own. 

You could try updating the play plugin it has a new version I think. Jacoco 0.8.3 is the most there..unsure if there is anything else

**Comment by mikehardy** [comment]
Tracking CI issue here https://travis-ci.community/t/android-emulators-not-starting-for-the-last-few-days-late-march-2019/2871?u=mikehardy

**Comment by fajarnuha** [comment]
Yes, that `ProjectLayout.fileDirecory()` things bug me quite a while, I couldn't find it in our code and maybe you're right, the code just doesn't exist and it will resolve on its own.

Alright then, no problem for me, just make sure CI is working before merging

**Comment by mikehardy** [comment]
Almost done fixing emulators: https://travis-ci.community/t/android-emulators-not-starting-for-the-last-few-days-late-march-2019/2871/11?u=mikehardy

**Comment by mikehardy** [comment]
If you rebase and repush your PR should build and get through CI fine, the emulator issue is resolved https://github.com/ankidroid/Anki-Android/pull/5280

**Comment by mikehardy** [comment]
Fixing the pile of emulators on travis always takes for ever because the tests run about 30-40 minutes :-). Finally got them though, rebasing + force-pushing your branch right now so it goes green on the PR then it'll merge in

**Pull request merged**
