### PR TITLE
Display different languages in their own language.

### LINKED ISSUE #6251: Language settings should be displayed in their own language.
###### Reproduction Steps

1. Go to Settings -> AnkiDroid -> language

###### Expected Result

Different languages' names should be displayed in their own language. 
It is possible to set a wrong language. Display languages' names in their own language can help user to change language in an unfamiliar environment.

###### Actual Result

Different languages' names are shown in the same language.

###### Debug info
Android Version = 7.0
AnkiDroid Version = 2.10alpha

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Sc-Weng**
## Purpose / Description
In language settings, display different lanuages in their own language.
However, some languages such as Arabic seems display in an wrong location which need further help.

## Fixes
Fixes #6251

## Approach
In function initializeLanguageDialog in Preference.java, Map<String, String> items' key change from loc.getDisplayName() to loc.getDisplayName(loc). 

## How Has This Been Tested?

Starting the app, opening the settings, opening the language settings.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
@Sc-Weng I like this a lot - can I ask you to post a quick screenshot of the language menu showing with this change so we can get an idea of what it looks like without having to pull it ourselves and build it? I believe I can picture it and I can merge this right away but I'd like to be sure :-)

**Comment by Sc-Weng** [comment]
Screenshot_language

**Comment by david-allison-1** [comment]
Would it be possible to use a case-insensitive string comparison for sorting?

**Comment by Sc-Weng** [comment]
@david-allison-1 The lanuguage order display now is sorted by country codes. I think it would not be a big problem to change its order. Maybe an simple Arrays.sort method could solve this problem.

**Comment by david-allison-1** [comment]
> @david-allison-1 The lanuguage order display now is sorted by country codes. I think it would not be a big problem to change its order. Maybe an simple Arrays.sort method could solve this problem.

Sounds good! 

Looks to be a little more complex as it doesn't use a tuple for the Key/Value pair: https://stackoverflow.com/questions/31657379/how-to-sort-a-listpreference-by-the-display-value

Implementer's choice as to whether it's done now. The UI's much better, and we can always follow-up later if it becomes problematic.

**Comment by david-allison-1** [comment]
<details><summary>Full Language List</summary> 

image


</details>

**Pull request closed without merging**
