### PR TITLE
NF: replace executeMany by execute for a single set

### PR DESCRIPTION
**Pull request by Arthur-Milchior**

### CODE REVIEW

**Comment by david-allison-1** [comment]
Might be interesting to add a `warn` in DEBUG mode for this one

**Comment by Arthur-Milchior** [comment]
I don't understand in which case you want a warning to occur

**Review by mikehardy — APPROVED** [review]
seems fine by me pending @david-allison-1 clarification

**Comment by david-allison-1** [comment]
@Arthur-Milchior You typically wouldn't want to call executeMany with one element, and it may be useful to flag this in the debug logs.

Feel free to merge either way. Not a serious concern, only a suggestion.

**Comment by Arthur-Milchior** [comment]
Added a warning, hoping I understood correctly

**Review by david-allison-1 — APPROVED** [review]

**Pull request merged**
