### PR TITLE
NF: remove duplicate "Lapses"

### PR DESCRIPTION
**Pull request by Arthur-Milchior**

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Commit message is incorrect

**Comment by Arthur-Milchior** [comment]
Corrected

**Review by david-allison-1 — APPROVED** [review]
Taken on a conflict - good to go otherwise

**Review by mikehardy — APPROVED** [review]
LGTM, squashing since contains a merge commit

**Pull request merged**
