### PR TITLE
AGP 7.4.1: Automated updates with manual fixups

### LINKED ISSUE #11288: AGP 7.2.0 upgrade recommendations
> **Upgrade AGP dependency from 7.1.3 to 7.2.0**
> Changing the version of the Android Gradle Plugin dependency effectively upgrades the project. Pre-upgrade steps must be run no later than this version change; post-upgrade steps must be run no earlier, but can be run afterwards by continuing to use this assistant after running the upgrade.

The below steps are all **recommended** for the AGP 7.1.3 to 7.2.0 transition by the Android Studio 'upgrade wizard' when at commit d8708b68ebcbeec5e15a18ff6c5c3c93b1c3dd71

NOTE: A patch is supplied below, but this is incorrect in many ways

## Migrate from jacoco to testCoverage

Configuration related to test coverage is now performed using the 
`testCoverage` block.

## Migrate packagingOptions directives to sub-blocks

Directives to affect packaging have been split into those affecting libraries (.so files) and those affecting all other resources.

## Migrate from lintOptions to lint

Configuration related to lint is now performed using the lint block.

## Move package from Android manifest to build files

Declaration of a project's namespace using the package attribute of the Android manifest is deprecated in favour of a namespace declaration in build files.

<details><summary>Incorrect Patch</summary>

```patch
Index: api/src/main/AndroidManifest.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/api/src/main/AndroidManifest.xml b/api/src/main/AndroidManifest.xml
--- a/api/src/main/AndroidManifest.xml	(revision d8708b68ebcbeec5e15a18ff6c5c3c93b1c3dd71)
+++ b/api/src/main/AndroidManifest.xml	(date 1652119647113)
@@ -1,5 +1,4 @@
-<manifest xmlns:android="http://schemas.android.com/apk/res/android"
-    package="com.ichi2.anki.api">
+<manifest xmlns:android="http://schemas.android.com/apk/res/android">
     <uses-permission android:name="com.ichi2.anki.permission.READ_WRITE_DATABASE"/>
     <application android:allowBackup="true" android:label="@string/app_name">
     </application>
Index: api/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/api/build.gradle b/api/build.gradle
--- a/api/build.gradle	(revision d8708b68ebcbeec5e15a18ff6c5c3c93b1c3dd71)
+++ b/api/build.gradle	(date 1652119646879)
@@ -12,6 +12,19 @@
     mavenCentral()
 }
 android {
+
+    lint {
+        abortOnError true
+        checkReleaseBuilds true
+        checkTestSources true
+        explainIssues false
+        lintConfig file('../lint-release.xml')
+        showAll true
+        textOutput file('stdout')
+        textReport true
+        warningsAsErrors true
+    }
+    namespace 'com.ichi2.anki.api'
     compileSdkVersion 31
 
     defaultConfig {
Index: AnkiDroid/jacoco.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/jacoco.gradle b/AnkiDroid/jacoco.gradle
--- a/AnkiDroid/jacoco.gradle	(revision d8708b68ebcbeec5e15a18ff6c5c3c93b1c3dd71)
+++ b/AnkiDroid/jacoco.gradle	(date 1652119646892)
@@ -7,11 +7,6 @@
 
 }
 
-android {
-    jacoco {
-        version = "0.8.8"
-    }
-}
 
 @Memoized
 Properties getLocalProperties() {
Index: api/src/test/AndroidManifest.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/api/src/test/AndroidManifest.xml b/api/src/test/AndroidManifest.xml
--- a/api/src/test/AndroidManifest.xml	(revision d8708b68ebcbeec5e15a18ff6c5c3c93b1c3dd71)
+++ b/api/src/test/AndroidManifest.xml	(date 1652119647115)
@@ -1,6 +1,5 @@
 <?xml version="1.0" encoding="utf-8"?>
 <manifest
-    xmlns:tools="http://schemas.android.com/tools"
-    package="com.ichi2.anki.api">
+    xmlns:tools="http://schemas.android.com/tools">
     <uses-sdk tools:overrideLibrary="androidx.test"/>
 </manifest>
Index: build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build.gradle b/build.gradle
--- a/build.gradle	(revision d8708b68ebcbeec5e15a18ff6c5c3c93b1c3dd71)
+++ b/build.gradle	(date 1652119646960)
@@ -18,7 +18,7 @@
         }
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:7.1.3'
+        classpath 'com.android.tools.build:gradle:7.2.0'
         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files
         classpath "app.brant:amazonappstorepublisher:0.1.0"
Index: AnkiDroid/src/main/AndroidManifest.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/AndroidManifest.xml b/AnkiDroid/src/main/AndroidManifest.xml
--- a/AnkiDroid/src/main/AndroidManifest.xml	(revision d8708b68ebcbeec5e15a18ff6c5c3c93b1c3dd71)
+++ b/AnkiDroid/src/main/AndroidManifest.xml	(date 1652119647117)
@@ -20,8 +20,7 @@
 -->
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
           xmlns:tools="http://schemas.android.com/tools"
-          package="com.ichi2.anki"
-          android:installLocation="auto"
+    android:installLocation="auto"
           >
     <uses-feature android:name="android.hardware.camera" android:required="false" />
     <uses-feature android:name="android.hardware.camera.any" android:required="false" />
Index: AnkiDroid/src/amazon/AndroidManifest.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/amazon/AndroidManifest.xml b/AnkiDroid/src/amazon/AndroidManifest.xml
--- a/AnkiDroid/src/amazon/AndroidManifest.xml	(revision d8708b68ebcbeec5e15a18ff6c5c3c93b1c3dd71)
+++ b/AnkiDroid/src/amazon/AndroidManifest.xml	(date 1652119647118)
@@ -1,5 +1,4 @@
-<manifest package="com.ichi2.anki"
-    xmlns:android="http://schemas.android.com/apk/res/android"
+<manifest xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:tools="http://schemas.android.com/tools"
     android:installLocation="auto">
 
Index: AnkiDroid/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/build.gradle b/AnkiDroid/build.gradle
--- a/AnkiDroid/build.gradle	(revision d8708b68ebcbeec5e15a18ff6c5c3c93b1c3dd71)
+++ b/AnkiDroid/build.gradle	(date 1652119647111)
@@ -26,6 +26,22 @@
 
 def homePath = System.properties['user.home']
 android {
+
+    testCoverage {
+        jacocoVersion '0.8.8'
+    }
+    lint {
+        abortOnError true
+        checkReleaseBuilds true
+        checkTestSources true
+        explainIssues false
+        lintConfig file('../lint-release.xml')
+        showAll true
+        textOutput file('stdout')
+        textReport true
+        warningsAsErrors true
+    }
+    namespace 'com.ichi2.anki'
     compileSdkVersion 31 // change api compileSdkVersion at the same time
 
     defaultConfig {
@@ -178,7 +194,9 @@
         coreLibraryDesugaringEnabled true
     }
     packagingOptions {
-        exclude 'META-INF/DEPENDENCIES'
+        resources {
+            excludes += ['META-INF/DEPENDENCIES']
+        }
     }
     sourceSets {
         debug {

```

</details>

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
* While going through the lint checks, I noticed some build warnings about `com.ichi2.anki` as the package name
* I looked into it, and this was automatically fixed by Tools -> AGP Upgrade Assistant

## Approach
* I ran each check, then cleaned up the code
* Did a small number of lint fixes here as well

## How Has This Been Tested?
CI

Closes #13067 (supercedes)
Fixes #11288

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
rebased - just to ensure https://github.com/ankidroid/Anki-Android/pull/13268 works

**Comment by BrayanDSO** [comment]
I believe this supersedes #13067

**Comment by mikehardy** [comment]
Indeed @RSBat had done some work here on #13067 but that one got stuck on something around the namespace changes. Either way this is a larger superset of those changes so, focusing on this one and marked it as closing the other

**Review by mikehardy — APPROVED** [review]
These all look good and I verified it was both a superset of #13067 plus does actually address all of #11288 (it does). Pulling locally to test, CI passed, if my local run passes I'll merge

**Comment by mikehardy** [comment]
Implicit dependencies cause build errors for some tasks

Strange one here - our CI is working because if you do this sequence (which our CI does as gradle warm then test) things work:

```bash
./gradlew packagePlayDebug packagePlayDebugAndroidTest --daemon
./gradlew uninstallAll jacocoAndroidTestReport --daemon
```

But if you do this:

```bash
./gradlew clean uninstallAll jacocoTestReport :api:lintRelease :AnkiDroid:lintPlayRelease ktlintCheck lint-rules:test
```

... there is some implicit dependency on the build dir used by the report and various tasks that drop things in the build dir, specifically:


```
* What went wrong:
Some problems were found with the configuration of task ':AnkiDroid:jacocoTestReport' (type 'JacocoReport').
  - Gradle detected a problem with the following location: '/home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/build'.
    
    Reason: Task ':AnkiDroid:jacocoTestReport' uses this output of task ':AnkiDroid:compilePlayReleaseAidl' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':AnkiDroid:compilePlayReleaseAidl' as an input of ':AnkiDroid:jacocoTestReport'.
      2. Declare an explicit dependency on ':AnkiDroid:compilePlayReleaseAidl' from ':AnkiDroid:jacocoTestReport' using Task#dependsOn.
      3. Declare an explicit dependency on ':AnkiDroid:compilePlayReleaseAidl' from ':AnkiDroid:jacocoTestReport' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/build'.
    
    Reason: Task ':AnkiDroid:jacocoTestReport' uses this output of task ':AnkiDroid:compilePlayReleaseJavaWithJavac' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':AnkiDroid:compilePlayReleaseJavaWithJavac' as an input of ':AnkiDroid:jacocoTestReport'.
      2. Declare an explicit dependency on ':AnkiDroid:compilePlayReleaseJavaWithJavac' from ':AnkiDroid:jacocoTestReport' using Task#dependsOn.
      3. Declare an explicit dependency on ':AnkiDroid:compilePlayReleaseJavaWithJavac' from ':AnkiDroid:jacocoTestReport' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/build'.
    
    Reason: Task ':AnkiDroid:jacocoTestReport' uses this output of task ':AnkiDroid:mergePlayReleaseResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':AnkiDroid:mergePlayReleaseResources' as an input of ':AnkiDroid:jacocoTestReport'.
      2. Declare an explicit dependency on ':AnkiDroid:mergePlayReleaseResources' from ':AnkiDroid:jacocoTestReport' using Task#dependsOn.
      3. Declare an explicit dependency on ':AnkiDroid:mergePlayReleaseResources' from ':AnkiDroid:jacocoTestReport' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/build'.
    
    Reason: Task ':AnkiDroid:jacocoTestReport' uses this output of task ':AnkiDroid:generatePlayReleaseResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':AnkiDroid:generatePlayReleaseResValues' as an input of ':AnkiDroid:jacocoTestReport'.
      2. Declare an explicit dependency on ':AnkiDroid:generatePlayReleaseResValues' from ':AnkiDroid:jacocoTestReport' using Task#dependsOn.
      3. Declare an explicit dependency on ':AnkiDroid:generatePlayReleaseResValues' from ':AnkiDroid:jacocoTestReport' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/home/mike/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/build'.
    
    Reason: Task ':AnkiDroid:jacocoTestReport' uses this output of task ':AnkiDroid:generatePlayReleaseBuildConfig' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':AnkiDroid:generatePlayReleaseBuildConfig' as an input of ':AnkiDroid:jacocoTestReport'.
      2. Declare an explicit dependency on ':AnkiDroid:generatePlayReleaseBuildConfig' from ':AnkiDroid:jacocoTestReport' using Task#dependsOn.
      3. Declare an explicit dependency on ':AnkiDroid:generatePlayReleaseBuildConfig' from ':AnkiDroid:jacocoTestReport' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

I played around with it a bit and the "area" (vague statement, apologies) of the problem is related to task definition - that is, what tasks are generating what outputs where and what the test tasks actually depend on. The general idea in modern gradle is to define inputs / outputs explicitly on tasks vs depending on files and directories and things with `**/dirname` etc - and we could improve that a lot.

It is also possible that simply defining the task dependencies better for the jacoco test tasks could do it, for instance making it depend on assemblePlayDebug or similar, but then we run into problems with the APK signing configuration and need for passwords etc.

So the correct fix is likely to alter the report tasks such that it really only depends on the actual outputs it needs somehow, using gradle Providers vs raw dirs and files, but I'm not sure exactly how to do it best - so that's the task

**Comment by mikehardy** [comment]
This PR is an incremental improvement though and not the cause of the comment-which-will-be-an-issue above, no issues with it going in.

**Pull request merged**
