### PR TITLE
lint[tests]: NewApi

### PR DESCRIPTION
**Pull request by Arnold2381**
## Fixes
Related: #9538 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
I don't feel this is correct. When I looked at this, only one method needed the annotation

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
I don't feel this is correct. When I looked at this, only one method needed the annotation

**Comment by Arnold2381** [comment]
@david-allison-1 when I checked it showed me errors in all these files.

**Comment by david-allison-1** [comment]
Oh, I see. I was looking at `InlinedApi`

Most of this seems to be due to `MockTime`.

We can cut this out into a separate PR, as it's likely a much more simple change to recode `MockTime.timeStamp` than bringing in the massive code changes.

For the smaller changes, it'll be useful to comment after the `@Requires` to list the API which it is required for.

There's no harm in applying the annotation to the class if all tests require an API - that will also reduce unnecessary line noise and code churn

**Comment by Arnold2381** [comment]
@david-allison-1 okay so for this PR I will put the annotation to the class if most of the functions of that class are using it. and comment the function names using it.

**Comment by david-allison-1** [comment]
While I'm here, it's best to use the auto suggested API level rather than a blanket "Android O"

This lets our tests be as permissive as possible, and run on the largest API skew

**Comment by Arnold2381** [comment]
David I messed this up. I had reset my branch to the master and pushed it. It closed the PR.

**Comment by david-allison-1** [comment]
> David I messed this up. I had reset my branch to the master and pushed it. It closed the PR.

You can typically get out of that with `git reflog`, but OK

**Pull request closed without merging**
