### PR TITLE
Bump gradle plugin to 4.0.0

### PR DESCRIPTION
**Pull request by mikehardy**

### CODE REVIEW

**Comment by mikehardy** [comment]
@david-allison-1 you can merge this whenever you feel like taking the network-related transfer pause since gradle will have to rebuild it's local cache of deps etc

**Comment by david-allison-1** [comment]
@mikehardy Hate to ask, is this a squash or a rebase?

Don't block it on me, my internet's typically good, was just a bad server the last time I needed it.

**Comment by mikehardy** [comment]
A good question

Per tradition I *always* rebase unless the commit history is a real mess

I understand people feel really strongly about this in all directions. It's just the way it's been done and like whitespace wars I just do as in the past for a given project and move on

**Comment by mikehardy** [comment]
great first merge though, there is almost no way it could go wrong and if it does it'll be even more perfect as an example of wow, how could that have gone wrong!?! :-)

 I'll leave it for you :-)

**Comment by david-allison-1** [comment]
Success! Thanks for the guidance

**Comment by mikehardy** [comment]
the first merge wooooo :-)

**Pull request merged**
