### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by HUN-sp**
Added some more strings in Strings.xml

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Hi, thanks for the PR!

Marking this as draft as there's quite a lot to do to get this mergeable

* Please fill out the default PR template: https://github.com/ankidroid/Anki-Android/blob/main/.github/pull_request_template.md
* Please link the issue: https://github.com/ankidroid/Anki-Android/issues/16789
* Please name the PR so we understand what it does
* Please use `/values` instead of `strings.xml` so we cab translate the strings: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations
* Please implement the functionality, rather than adding unused strings

**Comment by david-allison** [comment]
This PR is related to: 

* https://github.com/ankidroid/Anki-Android/pull/16791#issuecomment-2254596459

Please pick one to work on and get to completion, and close the other one

In future: it's best to have one pull request with multiple commits

**Comment by HUN-sp** [comment]
@david-allison Its a mistake

**Comment by david-allison** [comment]
@HUN-sp how do you plan to resolve this?

**Pull request closed without merging**
