### PR TITLE
Migrate CollectionGetter to kotlin

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

Migrates the CollectionGetter.java file to kotlin following the migration guide.
Note for reviewers: The migration tool made the col property in CollectionGetter nullable which would require tens of changes in the code base. I reviewed where CollectionGetter is implemented and it seems it can be turned into a non null property which I did. 

## How Has This Been Tested?

Ran the usual tests.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by Arthur-Milchior — APPROVED** [review]

**Review by david-allison — APPROVED** [review]
Another one bites the dust! Thanks!

**Comment by lukstbit** [comment]
I think this isn't ready to be merged. 

I was trying to migrate CollectionHelper and in CollectionHelper.getCol() the returned Collection can be null if we don't have access to the file structure. AnkiActivity relies on the CollectionHelper's getCol method so its returned Collection should be null if we want to respect the type system. However, all of its subclasses think and use AnkiActivity.getCol as not nullable. There are hundreds of usages of AnkiActivity.getCol() :(

I'm not sure how we should handle this.

**Comment by Arthur-Milchior** [comment]
If I get it right, there is a single method implementation that may return null, CollectionHelper (which actually create the collection). Ever other implementation return a collection that it receives and is non-null.
In this case, I guess it just would make sens to rename collectionHelper's method into something such as `createCol`. Seems to make sens also because on the first call it actually creates it, which is why it may return null.

In this case, it's indeed worth waiting here, as the this change must be done in a first PR. 
Maybe it would be best to first port some of the classes that actually deal with the case where getCol returns null, so that we later actually see the impact of type on conversion

**Comment by lukstbit** [comment]
> Maybe it would be best to first port some of the classes that actually deal with the case where getCol returns null, so that we later actually see the impact of type on conversion

It's AnkiActivity which relies on CollectionHelper.getCol(), and being the top hierarchy activity in the codebase it's heavily used and will bring a lot of changes. Over the next days I'm going through the codebase to check and improve nullability where I can and then try again to migrate CollectionGetter.

**Comment by mikehardy** [comment]
Just moving this to draft based on last comment, I just do this to keep the queues clean for repo maintenance as I use draft / not draft as a signal for what is actionable

**Comment by david-allison** [comment]
`withCol` has solved most of this, superseded by converting the rest of the classes to Kotlin and https://github.com/ankidroid/Anki-Android/pull/12200

**Pull request closed without merging**
