### PR TITLE
Used val instead of var

### LINKED ISSUE #11450: Cleanup: avoid var
As a general rule, `val` is better than `var`. Because that means that you can read code without having to keep track of how a value change. Even when there is no "kotlinCleanup", if you see a var and can change it to a val, it would be appreciated. 

This change has very low importance. So no need to got searching for all vars. The goal of this issue is simply to let you know that if, when you are reading/touching some part of the code base, you find some `var`, you can potentially improve the code in the ways described below. This means that if part of the code is never touched, it'll keep those var; but that's not so bad, after all, if nobody touches some code, the fact that it is not as beautiful as possible do not hurt anybody.

You can do PRs with a single change; so they 'll be easy to review, and can be merged quickly. And if they is an error, the error won't block other changes to be accepted. This also ensure PR can be merged quickly, and so there is very little risk of conflict.
You don't need to ask permission to work on this issue

This is a question of taste, and if you see a change that would leave the code uglier, don't do it, none of those changes are mandatory, and if they don't improve readability, they are not worth it.

# Hints to change var to val.

## Iteration

If a var is used to count the number of time a loop was executed, e.g. 
```kotlin
var i = 0
for (elt in elts) {
  ...
  i++
}
```
you can instead use 
```
for elts.forEachIndexed {i, elt ->
  ...
}
```
For a lot of loops, you use elt/i a single time, and so don't actually need to introduce it into a value.

## Fixed number of assignment

Some time, you'll see
```kotlin
var title = sectionTitle()
...
title = buttonTitle()
...
title = footerTitle()
```
Usually, you can simply use three distinct values ` sectionTitle`, `buttonTitle` and `footerTitle` as all of those titles are actually entirely independent and there is no reason to use the same variable

## Early return
In some old code we have
```kotlin
var x = defaultValue()
try {
if (condition) x = otherValue()
} catch (Exception e) {...}
return x
```
You can return `otherValue()` directly, and in the last case, do `return defaultValue()`. This only works if none of the function have side effect

## Use if conditional
Sometime we have
```kotlin
var x = defaultValue()
if (condition) x = otherValue()
```
you can use instead 
```kotlin
val x = if (condition) otherValue else defaultValue()
```

there are too special cases.
```kotlin
var x = defaultValue()
if (condition(x)) x = otherValue()
```
you can use instead 
```kotlin
val x = defaultValue().let {if condition(it) otherValue() else it)
```

there are too special cases.
```kotlin
var x = defaultValue()
if (x == null) x = otherValue()
```
you can use instead 
```kotlin
val x = defaultValue() ?: otherValue()
```

## other case?
If you see pattern I forgot, please add them in answer. I'll copy here.

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Pull Request template
Used val instead of var

Bug #11450 

Note: edited by @Arthur-Milchior, because it's not a fix

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Thanks!

CI is failing, and it seems that you have additional commits which aren't related to this PR. 

Could you rebase them out and fix the build?

**Comment by SanjaySargam** [comment]
> Thanks!
> 
> CI is failing, and it seems that you have additional commits which aren't related to this PR. 
> 
> Could you rebase the commits out and fix the build?

Yes, It was done by mistake. I will resolve this.

**Comment by Arthur-Milchior** [comment]
I edited your PR message. With "fixed:", it would have closed the issue. I am certain there are still `var`s around the code that may be changed to `val`.

**Review by Arthur-Milchior — APPROVED** [review]
Thanks. Really appreciate this kind of cleanup. Very quick to review, and makes code clearer

**Pull request merged**
