### PR TITLE
Replacing ints by constant

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description
I find that using Constants instead of using directly integers allows to have a far more readable code. 

## Approach
Replacing the integers by a static public int. 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
I don't disagree with your position, philosophically, but we have a special relationship with the code in the libanki folder - the code there is *supposed* to be the purest possible port of the upstream python to java so that we may easily compare and carry in upstream changes

I gather from your post on the list that this is actually one of your stated goals - merging in upstream changes - but does the upstream use the constants or does it use the less-readable magic numbers?

If it does not use constants then I'm on the fence with a little lean towards not going down a slippery slope of altering the code from upstream

**Comment by Arthur-Milchior** [comment]
I did a separate pull request because it's not mainstram. It thus has
nothing to do with my other goal of being up to date. No trouble if you
reject it. After all dae did reject when I did the same pull request in anki

Le ven. 11 oct. 2019 à 05:04, Mike Hardy <notifications@github.com> a
écrit :

**Comment by timrae** [comment]
Will respect Damien's decision for now
https://github.com/dae/anki/pull/269

**Comment by Arthur-Milchior** [comment]
Not surprised. Not really my most important PR anyway

**Comment by Arthur-Milchior** [comment]
I want to emphasize that the equivalent PR has now been merged in https://github.com/ankitects/anki/pull/433 (and some other commits such as https://github.com/ankitects/anki/pull/509)
Would you now accept this PR ?

**Comment by mikehardy** [comment]
I would, it looked as if there was a fair amount of feedback on the other PR, if all of that was incorporated so that the PRs matched and libanki was then in harmony, I definitely would

**Comment by Arthur-Milchior** [comment]
At the very least, I'll need to change the constant name, since Damien didn't like my initial choice and wanted me to use other name.
He also wanted to do a single variable by commit. It made me redo everything, but it was so much simpler to review commits

**Comment by mikehardy** [comment]
The constant names would have to line up of course. I can see the value in one commit per variable and since the code is so fundamental I'd like to avoid the possibility of any follow-on issues since we already have a couple of those to tamp down

**Pull request closed without merging**
