### PR TITLE
Run jacoco separately to work around errors; use debug variant only

### PR DESCRIPTION
**Pull request by dae**
https://github.com/ankidroid/Anki-Android/issues/14048#issuecomment-1613923181

### CODE REVIEW

**Comment by mikehardy** [comment]
I think the release variants on lint were important because our lint configuration has variance? https://github.com/ankidroid/Anki-Android/blob/main/lint-release.xml

**Comment by dae** [comment]
Bugger. Is there a reason the extra checks need to be done on the release variant and not the debug variant? If so, I can just roll the change back.

**Comment by mikehardy** [comment]
I think it's just specifying the Release version of the lint checks, the check separation is still fixing the total-failure issue
I wish I remembered why we had lint variance between debug and release, but I don't, and nothing I read just now while trying to find out if there is a difference normally or should be a difference was useful.
As far as I can tell, having lint be the same in debug and release is *possibly* a desired outcome, unless I'm just not understanding something

**Comment by dae** [comment]
I've reverted the debug->release change for now

@lukstbit it looks like you were the original committer - any thoughts?

**Review by mikehardy — APPROVED** [review]
Merging this so that you aren't blocked, but happy to entertain any sort of variant discussion + progress in a separate PR

**Comment by lukstbit** [comment]
@dae Sorry for taking so long to answer.

>  any thoughts?

Nothing, unfortunately. I think it was requested to add it for release but I'm not sure(or why if this was the case).

Just for reference, this jacoco issue is known for [some time](https://github.com/ankidroid/Anki-Android/issues/13277).

**Pull request merged**
