### PR TITLE
Fix representation of months to match Anki Desktop

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
We want more passing tests. This helps

## Fixes
Fixes two of the many checkboxes on #6751

## Approach
Fix values to match Rust: https://github.com/ankitects/anki/blob/05cc47a5d3d48851267cda47f62af79f468eb028/rslib/src/sched/timespan.rs#L83

## How Has This Been Tested?

Unit test now passes

## Learning (optional, can help others)
1 month is 30 days. Who woulda thunk it.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
I doubt it'll close https://github.com/ankidroid/Anki-Android/pull/6933/commits/93641eb5b8de5717b09ed65c7820ea4be3dfafe4
The difference in number between anki and ankidroid seems far too big. Furthermore, it would not be consistent with the fact that, according to user, it occurs only on filtered decks.

I've seen upstream do the formatting of the date using rust. Have you check what rules they use exactly to compute the number of month ? In my mind, both definition of month made sens. 30 days or 365/12=30.4 makes very little difference

**Review by Arthur-Milchior — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
A financial year is 360 days and work years are 2080 hours also, no more no more less...well, 2000 in continental Europe ;-)

**Comment by mikehardy** [comment]
I suppose this could also be 2.12.x perhaps?

**Comment by david-allison-1** [comment]
>> A financial year is 360 days and work years are 2080 hours also, no more no more less...well, 2000 in continental Europe ;-)

> each month can have 29 or 30 days depending on the visibility of the moon,

https://en.wikipedia.org/wiki/Islamic_calendar#Length_of_months

Time is a fun thing.

**Comment by david-allison-1** [comment]
2.12.2 would sound good with me - it's a bugfix

**Pull request merged**
