### PR TITLE
Drop legacy Java backend implementation

### PR DESCRIPTION
**Pull request by dae**
As AnkiDroid begins to adopt more of the backend code, it will not be
practical to maintain a fallback for devices that are unable to load
the backend library. Assuming there are an acceptably few number of
DroidBackendFactory::getInstance crash reports, cutting the Java
fallback is one step towards a single concrete backend interface.

Also introduce AnkidroidApp.currentBackendFactory() to get the currently
active backend version, and switch a couple of calls that were using
BackendFactory.createInstance() (which hard-codes V11).

### CODE REVIEW

**Comment by dae** [comment]
Unsure if the Windows failure is a flaky test or a regression.

**Comment by dae** [comment]
This appears to have broken the emulator; investigating.

**Comment by mikehardy** [comment]
I still have a pending task of bringing up new crash reporting database after the security issue a few weeks back

Once I do that (hopefully this weekend - it's nearly setup), I'd like to let this sit for a week to allow for an answer to the question "how many DroidBackendFactory::getInstance crashes do we have?". I think the answer is actually zero, it was before the security incident resulted in us wiping the crash reporting instance

**Review by mikehardy — APPROVED** [review]
Looks good pending
- data-backed verification of assertion "we don't have problems loading the library"
- architectural review from David - not sure he would agree with it in AnkiDroidApp

**Comment by dae** [comment]
Re the latter point, my thinking here was that:

a) TESTING_USE_V16_BACKEND is defined inside AnkiDroid, and would need to be moved into AnkiDroidBackend and a new release made
b) the function can be removed once AnkiDroid's switched over to the new code by default, so it's only temporary

**Review by david-allison — COMMENTED** [review]
Architecturally, I don't mind as long as there's a cleanup attribute.

When this causes a crash, the user won't have migrated to the new storage mechanism, and their collection will be safe, allowing them to downgrade.

But, we shouldn't show the regular 'collection open failed' message here, as that provides incorrect solutions to this issue.

image
image


I'd accept either:
1. throw an `Error` if `NativeMethods.ensureSetup()` fails (to hard crash the app)
2. Expose the exception from `NativeMethods` and check in `DatabaseErrorDialog`

I'd prefer `1` for now, with a cleanup attribute to move to `2`, to retain velocity

**Comment by dae** [comment]
Ok, good to know it can be cut. I'll circle back to this later; currently experimenting with updating the backend code to the latest desktop code.

**Comment by mikehardy** [comment]
Mildly related - to your last comment - have not had time to investigate enabling Kotlin in anki-android-code yet, but hopefully soon...

**Comment by david-allison** [comment]
> Mildly related - to your last comment - have not had time to investigate enabling Kotlin in anki-android-code yet, but hopefully soon...

I wouldn't be opposed to doing a migration in a single commit for the backend.

**Comment by dae** [comment]
I managed to figure it out - had applied the plugin to the wrong module, and needed some extra steps to get generated Kotlin to work.

**Comment by mikehardy** [comment]
> > Mildly related - to your last comment - have not had time to investigate enabling Kotlin in anki-android-code yet, but hopefully soon...
> 
> I wouldn't be opposed to doing a migration in a single commit for the backend.

agreed on that. If you're in to it, just do it, boom done.

**Comment by dae** [comment]
Closing in favor of #11644

**Pull request closed without merging**
