### PR TITLE
Slide in

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Use Enum instead of multiple constants

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
```
e: warnings found and -Werror specified
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anim/ViewAnimation.kt: (69, 13): 'when' is exhaustive so 'else' is redundant here
```

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Actual change looks fine

For an additional commit:

`@KotlinCleanup`: `Animation.RELATIVE_TO_SELF` can be removed with local function, and named args should be added
`@KotlinCleanup:` `[enable/disable]ViewAnimation` would be better as extension methods on `View`

**Review by mikehardy — APPROVED** [review]
LGTM modulo David's comment - I'm fine with this when he is, no need to wait further to merge...

**Comment by Arthur-Milchior** [comment]
> @KotlinCleanup: Animation.RELATIVE_TO_SELF can be removed with local function, and named args should be added

Done, I think

> @KotlinCleanup: [enable/disable]ViewAnimation would be better as extension methods on View

I don't understand this one

**Comment by david-allison-1** [comment]
> [enable/disable]ViewAnimation

`[enable/disable]ViewAnimation` currently exists in `AnkiActivity`, but I don't feel that these belong here, they're using `AnkiActivity` as a `Context` to obtain preferences related to animations.

I feel a better signature would be a Kotlin extension method: `View.enableAnimation(Context, Animation)`

**Pull request closed without merging**
