### PR TITLE
Update:twitter logo

### PR DESCRIPTION
**Pull request by shrutigitte**
## Purpose / Description
I forked the ankidroid repo today and I am a new contributor so I am eager to contribute so I decided to start with minor refractor.

## How Has This Been Tested?
It's a PNG file and doesn't need testing

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
I question if we have to include some kind of "X logo is from X, and is not affiliated with AnkiDroid" kind of message. A link to the logo distribution docs would help

**Comment by shrutigitte** [comment]
https://about.x.com/en/who-we-are/brand-toolkit 

I downloaded the icon from here i don't think there is need to write anything extra this is especially for the purpose of using X logo on websites/Apps

**Comment by criticalAY** [comment]
Still look good to me

**Review by neeldoshii — APPROVED** [review]
LGTM!!

**Comment by david-allison** [comment]
Could we resize this back to 400x400?

Sorry this sat for so long

**Comment by shrutigitte** [comment]
> Could we resize this back to 400x400?
> 
> Sorry this sat for so long
The photo is already 50 in the place it is used.
```<a href="https://twitter.com/ankidroid"></a>```

**Comment by snowtimeglass** [comment]
I suspect the white logo with transparent background would be invisible when the background of the page is white.
image
image

**Comment by david-allison** [comment]
It's more that it's a large file, and it adds to the `git clone`/CI time unnecessarily

**Comment by criticalAY** [comment]
@snowtimeglass @david-allison How about we use this, and it is given by twitter/X itself
twitter

**Comment by david-allison** [comment]
Looks nice

**Comment by snowtimeglass** [comment]
@criticalAY 
> How about we use this

I'm still not sure which part you point to. Do you literally point to this wide rectangle PNG image? Or the "X" logo, which was made as a font or something?
image


Also, doesn't that jaggedness occur in the actual page?
image

**Comment by snowtimeglass** [comment]
The following material and the site look trustworthy and useful to me.

image
image
https://www.iconpacks.net/free-icon/twitter-x-logo-black-round-20851.html

image
https://www.iconpacks.net/terms/

---------------



I guess it is possible to provide an adjusted PNG image based on the material above (or a material from twitter/X' site) here.
image

**Comment by mikehardy** [comment]
@snowtimeglass I love the idea of a 50px PNG that is always white `X` on black background, if you did that and proposed it I would merge it paired with #16828

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
Great stuff, thanks

**Comment by Arthur-Milchior** [comment]
At this point, I'd suggest also renaming the file. Won't block on it. Thanks @shrutigitte

**Comment by snowtimeglass** [comment]
The current pushed icon looks blur, jaggy and no padding, unlike other icon images.



image
(64 × 64 px) 

image
(400 × 400 px)

image
(400 × 400 px)

------

@mikehardy 
> if you did that and proposed it

Thank you. I would gladly do so. On the other hand, I can also provide the image file here. Either way is fine for me.
image
(400 × 400 px)

The PNG image file is here. 
[x-logo-adjusted.zip](https://github.com/user-attachments/files/16665639/x-logo-adjusted.zip)

**Comment by snowtimeglass** [comment]
@mikehardy Ah, I just noticed that you commented that 4 days ago. I overlooked it until now.

**Comment by mikehardy** [comment]
"This job failed" is as much information as I could get out of the merge queue failure, not really informative. Was the windows unit test run that failed.

Put it back in the queue...

**Pull request merged**
