### PR TITLE
Force play next sound

### LINKED ISSUE #9523: [Bug] Second audio file not auto played if first one is not available
###### Reproduction Steps

0. Ensure auto playback for audio files is enabled.
1. Create a card template with 2 audio files on the front page, e.g. `[sound:broken.mp3] [sound:existing.mp3]`.
2. Change `existing.mp3` to any audio file available in your collection.
3. Review that card.

###### Expected Result

The second audio file is auto played (the first one is missing).

###### Actual Result

Nothing is auto played (on the front page). It is required to tap the (second) "playing triangle" to hear existing audio file.

###### Additional info

It is a minor issue and usually is caused by some problem on the user side, however, tracking down why auto playing for audio files doesn't work for the front page in my new card template, it took me a while to pinpoint the original problem (here, missing audio file). It was especially unpleasant, as Anki Desktop (2.1.15 on Linux) auto played the second file without any problem (and the first (missing) one was `silence05.mp3` which was inaudible :-) ).

Tested with AnkiDroid 2.15.6 and 2.9beta5.

###### Debug info

Not needed

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by prateek-singh-3212**
## Purpose / Description
 Force play next audio when first audio is corrupted or not found.

## Fixes
Fixes  #9523

## Approach
 Created the force play next Sound method which triggers when error ocurred while playing sound. 

## How Has This Been Tested?

 Samsung Galaxy M51 API 30

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
This is on me, please follow up tomorrow if this hasn't been properly reviewed. 

I don't feel triggering `onError` manually is correct. We should have the class do this, therefore `onCompletionListener` will be played, and we can remove the need for all this code.

If the above isn't possible, I don't feel that triggering playback from `onError` is correct, and instead we should call `onError`, then call the `onCompletionListener` based on the result of the function

**Comment by prateek-singh-3212** [comment]
> Can you split the refactor and the bugfix commit?

Sure.

> Have you tested the new code?

Yes. It is working as expected.

> What's the reason for one null check on the media player after we've used it as a parameter?

I'll fix that.

**Comment by prateek-singh-3212** [comment]
@mikehardy One request : please add hacktober fest tag in this pr

**Comment by david-allison-1** [comment]
> @mikehardy One request : please add hacktober fest tag in this pr

Shouldn't need it, the repo has the topic

**Comment by prateek-singh-3212** [comment]
I think that we have to add to PR also because it is reflecting in my dashboard but not as part of hacktober fest.

**Comment by david-allison-1** [comment]
What does the exclamation mark show if you hover?

**Comment by prateek-singh-3212** [comment]
Thanks for clearing.

**Comment by mikehardy** [comment]
Hi there! **October OpenCollective Notice**

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in **October** 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for October 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!

**Pull request merged**
