### PR TITLE
feat: Speed up tests on Apple Silicon and CI

### PR DESCRIPTION
**Pull request by david-allison**
M1 Macs don't have SMT, so there's no need to halve the processors when running tests

Before:
BUILD SUCCESSFUL in 3m 1s
BUILD SUCCESSFUL in 2m 57s

After:
BUILD SUCCESSFUL in 2m 08s
BUILD SUCCESSFUL in 1m 53s

Note: Scenario was unit test runs inside Android Studio, had similar speedup with `./gradlew clean jacocoUnitTestReport --rerun-tasks`

## How Has This Been Tested?

All tests
## Learning (optional, can help others)

We may want to do this based on physical CPUs if there is a good platform-agnostic method.

```
davidallison@Davids-MBP optilingo_mobile_app_v2 % sysctl -n hw.physicalcpu                                         
10
davidallison@Davids-MBP optilingo_mobile_app_v2 % sysctl -n hw.ncpu                                 
10
```

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Nice! For reference on intel mac, it generates what seems to work for you stated possible other version

```
mike@osxvm:~ % sysctl -n hw.physicalcpu
6
mike@osxvm:~ % sysctl -n hw.ncpu 
12
```

Additionally, there is perhaps an opportunity for CI tuning "while we're here" - that is, I have this information from github's doc:

```
Hardware specification for Windows and Linux virtual machines:

2-core CPU
7 GB of RAM memory
14 GB of SSD disk space
Hardware specification for macOS virtual machines:

3-core CPU
14 GB of RAM memory
14 GB of SSD disk space
```

So it could be that 2 is the right number for CI in general, and 3 is the right number for macOS in CI ? Then hw.physicalcpu if it's !CI && macOS-arm64 ?

**Comment by mikehardy** [comment]
using hardware cpu count would also mean it works even if people are using x86-64 JVM still, on arm64 hardware

**Comment by david-allison** [comment]
Not sure about that statement. Seems to be one physical CPU on Linux if I'm reading correctly: See `physical id`

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
stepping	: 4
microcode	: 0xffffffff
cpu MHz		: 2095.179
cache size	: 36608 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt avx512cd avx512bw avx512vl xsaveopt xsavec xsaves md_clear
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 4190.35
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
stepping	: 4
microcode	: 0xffffffff
cpu MHz		: 2095.179
cache size	: 36608 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt avx512cd avx512bw avx512vl xsaveopt xsavec xsaves md_clear
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 4190.35
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

```

**Comment by mikehardy** [comment]
An interesting point, the problem of course is that they are virtual machines, so the physical topology presented to the virtual machine and reported in /proc/cpuinfo is fictitious

The only way to know is to bench it both ways :laughing:

**Comment by mikehardy** [comment]
(by the way, my intel mac cpu info above is also fictitious, that was from a VM, but I happen to know that I presented an imaginary CPU topology that was SMT with 2 threads per core, so the experimental result is valid - I don't know what hardware resources they are actually presenting in azure cloud as their "vCPU", just an SMT thread or a real core)

It appears that for this instance type we are 1:1 so we should use 2 cores!

https://docs.microsoft.com/en-gb/azure/virtual-machines/acu

```


DS1_v2 - DS15_v2 | 210 - 250* | 1:1
-- | -- | --


[DS1_v2 - DS15_v2](https://docs.microsoft.com/en-gb/azure/virtual-machines/dv2-dsv2-series)	210 - 250*	1:1
```

**Review by mikehardy — APPROVED** [review]
magically delicious comments on commit and in code as well, :100:

**Comment by mikehardy** [comment]
Looking at the recent actions timings vs this ones, I think this is a really significant CI speedup, except windows. I booted my windows VM today and got it up to date, I'll see what I can do about memory optimization there since all indications are that's the issue

**Pull request merged**
