### PR TITLE
Reviewer: Increase Left/Right Padding for Top Bar

### LINKED ISSUE #7854: Padding/Margin issues (answer counts truncated) on OnePlus 7 Pro
Had a user report that the answer counts are truncated on a OnePlus 7 Pro (possibly due to the curved screen)

As can be seen by the pictures (without phone case), there is a large amount of the left hand of the margin missing. 

I'm not sure what to do here - adding a workaround for larger padding may be the best option.

image

image

> About the screen shifting part-- No, there was another entirely different app which is used and I don't remember the name. Couple of them had this same issue because it was a curved screen. And the dev introduced something called "extra padding" for curved screen to turn on in settings

User did not post UUID for privacy 
```
AnkiDroid Version = 2.14.2
Android Version = 10
Scheduler = std
Crash Reports Enabled = true
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
OnePlus 7 Pro phones truncated the "new count"

## Fixes
Fixes #7854

## Approach

* Material design states we should have 16dp padding to the sides if in full screen.
* This should fix the issue, and bring us closer to the Material Design guidelines

## How Has This Been Tested?
API 16 emulator. 3.3 inch screen
image
image

## Learning
* http://web.archive.org/web/20180105203433if_/https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-keylines-spacing
* https://android-developers.googleblog.com/2017/12/tuning-your-apps-and-games-for-long.html

Maybe:

* https://developer.android.com/reference/android/view/WindowInsets#getInsets(int)
* https://github.com/th3rdwave/react-native-safe-area-context

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

**Comment by david-allison-1** [comment]
This is likely to annoy users, so treat this as "draft but complete, anything goes suggestion-wise"

**Comment by mikehardy** [comment]
Does it really look like that? I think pushing contents in is a good thing but this looks like it pushed backgrounds in as well so there is this unpainted edge?

**Comment by david-allison-1** [comment]
> Does it really look like that? I think pushing contents in is a good thing but this looks like it pushed backgrounds in as well so there is this unpainted edge?

That's an artifact of the emulator - I should have used the in-app screenshot rather than cropping. Apologies

image
Screenshot_1607606113

**Review by mikehardy — APPROVED** [review]
ah, okay - LGTM then :-)

**Pull request merged**
