### PR TITLE
Fixed a bug about NavigateUp Button on DeckOverview screen

### PR DESCRIPTION
**Pull request by MrPenguins**
## Purpose / Description
When long press the NavigateUp Button on the DeckOverview screen, the name of the button won't show on the screen.

## Fixes
Fixes [#10895](https://github.com/ankidroid/Anki-Android/issues/10895)

## Approach

The layout file of the `androidx.appcompat.widget.Toolbar` in `studyoptions_fragment.xml` didn't contain the `navigationContentDescription` and `navigationIcon`, so I added them.

## How Has This Been Tested?

It was manually tested on the emulator (Pixel 2 API 29) and my phone.
I also write an Espresso Test to test it and it works fine.

## Screenshot
image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by krmanik — CHANGES_REQUESTED** [review]
The test does not require here. Remove Espresso and change it to Robolectic

**Comment by MrPenguins** [comment]
> The test does not require here. If want to add test then remove espresso and change it to robolectric.

Sure! I will try to replace the espresso test with roboletric, and if it doesn't work, I will remove it.

**Review by david-allison — COMMENTED** [review]
Looks good!

What happens if this is tested on an emulated tablet (we split the screen in this case)?

Could you drop a `@NeedsTest("message")` on the class so someone can add the test in the future

**Comment by MrPenguins** [comment]
> Looks good!
> 
> What happens if this is tested on an emulated tablet (we split the screen in this case)?
> 
> Could you drop one or more `@NeedsTest("explanation")` on the class so someone can add the test in the future

I tested it in the split-screen mode and it works fine.
image

I was confused about the `@NeedsTest("explanation")` annotation. Since I only modified the `.xml` file, where should I add these annotations?

**Comment by mikehardy** [comment]
split screen is different from tablet mode
In tablet mode, especially in landscape, we use a completely different main screen layout where *inside the app* the layout is split between deck list and the deck info page
The only way I personally know to test it is to set up a Tablet emulator and load the app in landscape

**Review by mikehardy — APPROVED** [review]
A lot of checking for such a simple change! But the checking is important, it really is costly to fix bugs after and much easier + faster to check things thoroughly as changes go in.

I think this looks great, thank you!

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
> I was confused about the `@NeedsTest("explanation")` annotation. Since I only modified the .xml file, where should I add these annotations?

Feel free to put it on the relevant class. I'll leave it to @mikehardy to say whether we should merge now, or wait for the documentation

**Comment by mikehardy** [comment]
Doing a second PR just to add the needstest seems overdone - just add it as a commit here then we can (finally! :sweat_smile: ) merge

**Comment by MrPenguins** [comment]
I added `@NeedsTest` in function `configureToolbarInternal()` in `StudyOptionsFragment.kt`, though I'm not sure whether it is necessary.

**Review by david-allison — APPROVED** [review]
Thanks!

**Pull request merged**
