### PR TITLE
fix: remove maxLength on `paste_as_png_summary`

### PR DESCRIPTION
**Pull request by david-allison-1**
Accidental inclusion. Reported on CrowdIn

Need to see how this is handled after a translation sync

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Oh! Good catch. I'll merge this and re-sync crowdin, I'm in that area right this moment waiting for current tests to finish

**Comment by mikehardy** [comment]
@david-allison-1 i18n sync running now, typically only takes ~2 minutes, if you want to check crowdin after since you probably have all the tabs open right now?

**Comment by david-allison-1** [comment]
This doesn't look fixed: https://crowdin.com/translate/ankidroid/8173/en-id?filter=basic&value=0#6535542

**Comment by mikehardy** [comment]
@david-allison-1 copying from crowdin for full visibility:

> @david-allison-1 I have manually altered it to zero (unlimited) as the i18n-sync did not seem to remove the constraint. Hopefully that is persistent in the next sync, should probably re-push (even if unchanged) to verify?

**Comment by mikehardy** [comment]
After resync the affected string and the fix to have it be unlimited again seemed to be (correctly) persisted. I think we're good now

**Pull request merged**
