### PR TITLE
Replace usages of String.format in with string templating

### LINKED ISSUE #11449: Cleaning: replacing `format` by formatted strings
This is part of Kotlin clean-up  #10489, low priority, a way to slightly improve code quality and make easy changes.

There are currently 37 occurrences of `String.format` in Kotlin followed by a String literal. In Kotlin, you can generally use Template stings, which I find more readable. It'd be nice to replace them. In short, if you don't know string literals, you just have to use $varName or ${expression}. So for example you'd use `"$appName $pkgVersionName"` instead of `"String.format("%s v%s", appName, pkgVersionName)"`.

If `String.format` don't start with a template but with a locale, please don't change it, unless you can be sure that:
* either we don't actually care about the locale
* you can ensure we respect the locale requirement directly in the parameters

If it's not too hard, I appreciate if you can do one change by pull request; unless multiple changes are very strongly related. This way, those PR can be merged very quickly; and if there is an issue, I don't have to delay all other changes.

You don't have to ask permission to work on this. Just look at the answer below to see links to PR already done. I'll try to merge them quickly. Hopefully, most change should be done in less than a minute, so the risk of wasted work is really small

### PR DESCRIPTION
**Pull request by PotatoPresident**
## Purpose / Description
Replaced basic usages of String.format with Kotlin string templates

## Fixes
Fixes #11449 

## Approach
Replace `String.format("%s", x)` with `"$x"`

## How Has This Been Tested?

Passed all unit tests

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by BrayanDSO — APPROVED** [review]
LGTM. Thanks!

**Review by krmanik — APPROVED** [review]
Thanks

**Comment by krmanik** [comment]
@PotatoPresident 
I think you wanted this to be in [Hacktoberfest](https://hacktoberfest.com/). Then the label needs to be added so it will be marked as contribution for that.

**Comment by PotatoPresident** [comment]
> @PotatoPresident I think you wanted this to be in [Hacktoberfest](https://hacktoberfest.com/). Then the label needs to be added so it will be marked as contribution for that.

The repo has the label so its good.

**Pull request merged**
