### PR TITLE
change widget style to material design

### PR DESCRIPTION
**Pull request by cydia2020**

### CODE REVIEW

**Comment by timrae** [comment]
Thanks, could you please also add the svgs though? And also post some screenshots here.

**Comment by cydia2020** [comment]
Here you go some good old screenshots
screenshot_20171116-002332
screenshot_20171116-002345

I'm sorry but I dont know how to convert png into svg simply because every converter I tried has terrible final results. So please help me to convert the files if you can. Cheers

**Comment by timrae** [comment]
It's not possible to convert from png to svg, only the other way around.
Svg is vector format. Don't you have the source files?

On 15/11/2017 22:31, "池程 (Takumi Ikezaki)" <notifications@github.com> wrote:

Here you go some good old screenshots
[image: screenshot_20171116-002332]
<https://user-images.githubusercontent.com/12470297/32838487-30569494-ca65-11e7-9824-4f50b357e091.png>
[image: screenshot_20171116-002345]
<https://user-images.githubusercontent.com/12470297/32838490-3313e128-ca65-11e7-86e9-ca912a9b76c8.png>

I'm sorry but I dont know how to convert png into svg simply because every
converter I tried has terrible final results. So please help me to convert
the files if you can. Cheers

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ankidroid/Anki-Android/pull/4737#issuecomment-344592641>,
or mute the thread

**Comment by cydia2020** [comment]
Unfortunately I used Android studio to generate the image basically. So I don't have any kinds of source files, the largest file I've got is a 512 px file. Nothing much other than that. Sorry for that.

**Comment by timrae** [comment]
Sorry, I can't really accept these images without the svg source files. We are an open source project after all. Also I think it looks a bit weird with the star cropped like that, don't you think?

If you could generate the images from `.svg` source files (i.e. starting from the original source files [here](https://github.com/ankidroid/Anki-Android/tree/master/docs/graphics/src)), and fix the cropping issue then please open up a new pull request!

**Pull request closed without merging**
