### PR TITLE
chore: remove the duplicate background imageView

### PR DESCRIPTION
**Pull request by 410063005**
## Purpose / Description
Remove the duplicate background imageView.

## Fixes
* Fixes #

## Approach
_How does this change address the problem?_

Remove the duplicate background imageView from the layout file.

#### Before
image

#### After
image

#### Before
image

#### After
image

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

Tested on:

- Emulator - Pixel XL (API 31)
- Vivo V2238A (API 34)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — COMMENTED** [review]
Isn't this used here?

https://github.com/ankidroid/Anki-Android/blob/836c809547a29ec9cd57ef28d66612300b4c72f2/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L754-L785

**Comment by 410063005** [comment]
@david-allison Yes,  background is used and necessary.  Layout Inspector shows there are two imageViews with the same id background

image

But we need only one background imageView.  I removed the duplicate one in this PR.

**Comment by 410063005** [comment]
I'll check again and provide screenshots later. 

These are the layout files contain duplicate background images. `homescreen.xml` has a background and it includes `deck_picker.xml` which also contains a background. 

https://github.com/ankidroid/Anki-Android/blob/51be80182dcd3fe17f1aef42da643a978a31cd4e/AnkiDroid/src/main/res/layout/homescreen.xml#L1-L11

https://github.com/ankidroid/Anki-Android/blob/51be80182dcd3fe17f1aef42da643a978a31cd4e/AnkiDroid/src/main/res/layout/deck_picker.xml#L1-L12

**Comment by 410063005** [comment]
> Can you provide a before & after with a background image applied to ensure there are no regressions
> 
> I suspect the view should be renamed instead. The intention was likely the outer view was to be used

@david-allison  There are no regressions.  These are the screenshots. I've also updated the before & after in the PR

# Vivo V2238A (API 34)
## Before
image

## After
image

# Emulator - Pixel XL (API 31)

## Before
image

## After
image

**Review by david-allison — APPROVED** [review]
Cheers, looks great!

**Review by krmanik — APPROVED** [review]

**Pull request merged**
