### PR TITLE
NF: executeInTransaction returns value

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This commit is on top of #12016. I expect it may be used in #11952 to remove a nullability type issue

### CODE REVIEW

**Comment by dae** [comment]
I came across `executeInTransactionReturn` in the codebase the other day.

**Comment by Arthur-Milchior** [comment]
Thanks. Didn't know about it.
Not exactly surprised the idea is not new.
Still, I consider that it was a good thing to migrate DB, which ensure that this method can now integrate db's declaration and can be easier to find

**Review by lukstbit — APPROVED** [review]
Approved, assuming that it passes the tests/no conflicts after merging the other needed PRs.

**Review by david-allison — CHANGES_REQUESTED** [review]
This contains a lot of unrelated changes. Specific change is fine

**Comment by Arthur-Milchior** [comment]
@david-allison "unrelated", do you mean the four first PR? 
Migration of `DB` is required to have the type `()->T`, given that `Runnable` don't return value. And DB itself require to correct the types of two functions that calls the database. So that'll have to wait for required PR to be merged.

If you mean that I'm touching AsyncLayer, it seems to me that its function had no interest anymore now that DB is in Kotlin. 
However, I'll admit I should have clarified it in the commit message. I'll do so as soon as DB is merged, since we'll get a merge conflict and I'll have to rebase and force push anyway

**Comment by david-allison** [comment]
Shouldn't this be a draft, or 'blocked by dependency' until it's mergeable?

**Comment by Arthur-Milchior** [comment]
Merge conflict resolved

As I stated for the "DB migration" PR. I thought that "draft" were for PR that can't be reviewed. While this one could already be reviewed. It probably should not be merged until the DB was merged, but the last commit could be merged by itself

**Review by david-allison — APPROVED** [review]

**Comment by Arthur-Milchior** [comment]
Yeah. That was the original goal of all those five commits and 3 PR. Thanks for merging it !

**Pull request merged**
