### PR TITLE
WIP: Unit Tests added into the Utils.java class (api Module).

### PR DESCRIPTION
**Pull request by bresan**
- Add dependency on support-annotations (in order to use @VisibleForTesting);
	- Add dependnecy on JUnit in order to allow unit tests for the module api;

### CODE REVIEW

**Comment by timrae** [comment]
Is this still work in progress?

**Comment by mikehardy** [comment]
I'm also curious about this. Is this still in progress?

I've just worked through the build system and I'd like to add some unit tests as well so not everything requires the emulator running

**Comment by timrae** [comment]
Sure, more tests are always good, just try to make any PR very simple to understand please :)

**Comment by mikehardy** [comment]
Roger that

**Pull request closed without merging**
