### PR TITLE
Kotlin migration TagsDialog

### PR DESCRIPTION
**Pull request by Arnold2381**
Kotlin migration TagsDialog

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
```
com.ichi2.anki.dialogs.tags.TagsDialogTest > test_AddNewTag_shouldBeVisibleInRecyclerView_andSortedCorrectly FAILED
    java.lang.NullPointerException: Parameter specified as non-null is null: method com.ichi2.anki.dialogs.tags.TagsDialog.<init>, parameter listener
        at com.ichi2.anki.dialogs.tags.TagsDialog.<init>(TagsDialog.kt)
        at com.ichi2.anki.dialogs.tags.TagsDialogTest.test_AddNewTag_shouldBeVisibleInRecyclerView_andSortedCorrectly(TagsDialogTest.java:169)

com.ichi2.anki.dialogs.tags.TagsDialogTest > testTagsDialogCustomStudyOptionInterface FAILED
    java.lang.NullPointerException: Parameter specified as non-null is null: method com.ichi2.anki.dialogs.tags.TagsDialog.<init>, parameter listener
        at com.ichi2.anki.dialogs.tags.TagsDialog.<init>(TagsDialog.kt)
        at com.ichi2.anki.dialogs.tags.TagsDialogTest.testTagsDialogCustomStudyOptionInterface(TagsDialogTest.java:77)

com.ichi2.anki.dialogs.tags.TagsDialogTest > testTagsDialogCustomStudyOptionFragmentAPI FAILED
    java.lang.NullPointerException: Parameter specified as non-null is null: method com.ichi2.anki.dialogs.tags.TagsDialog.<init>, parameter listener
        at com.ichi2.anki.dialogs.tags.TagsDialog.<init>(TagsDialog.kt)
        at com.ichi2.anki.dialogs.tags.TagsDialogTest.testTagsDialogCustomStudyOptionFragmentAPI(TagsDialogTest.java:116)

com.ichi2.anki.dialogs.tags.TagsDialogTest > test_AddNewTag_existingTag_shouldBeSelectedAndSorted FAILED
    java.lang.NullPointerException: Parameter specified as non-null is null: method com.ichi2.anki.dialogs.tags.TagsDialog.<init>, parameter listener
        at com.ichi2.anki.dialogs.tags.TagsDialog.<init>(TagsDialog.kt)
        at com.ichi2.anki.dialogs.tags.TagsDialogTest.test_AddNewTag_existingTag_shouldBeSelectedAndSorted(TagsDialogTest.java:217)
```

**Review by david-allison-1 — APPROVED** [review]
LGTM

**Comment by mikehardy** [comment]
Wait! We really want to examine #8751 first ? I don't know if I can rescue that one across a Java->Kotlin conversion but it seemed discussed-to-death and tested and ready to go last time I rescued it from conflict entropy last week...

**Comment by mikehardy** [comment]
The related PR has landed! This will need a rebase to remove conflicts - which from a kotlin migration perspective probably means just re-doing it completely, apologies, but that other PR was a really really big one containing a feature for a frequent user request, so I appreciate your patience

**Comment by Arnold2381** [comment]
No problem at all. I will make the changes soon. Will be back by monday!

**Review by david-allison-1 — APPROVED** [review]
LGTM

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
