### PR TITLE
DeckTask cleanup

### LINKED ISSUE #3598: "Collection not opened" after sync
Seems to be reproducible by:
1 - Start sync
2 - Go to another app/home screen
3 - Open AnkiDroid while sync is ongoing. When the sync finishes, the *Collection not opened* dialog is raised.

```
08-05 16:45:35.941  12965-13128/com.ichi2.anki I/Syncer﹕ Sync: finishing
08-05 16:45:35.983  12965-13128/com.ichi2.anki I/Collection﹕ flush - Saving information to DB...
08-05 16:45:38.534  12965-13128/com.ichi2.anki D/Connection﹕ doInBackgroundSync -- closing collection on outer finally statement
08-05 16:45:38.597  12965-13128/com.ichi2.anki D/AnkiDb﹕ closeDatabase, database /sdcard/AnkiDroidhssm/collection.anki2 closed = true
08-05 16:45:38.614  12965-13128/com.ichi2.anki D/AnkiDb﹕ closeDatabase, database /sdcard/AnkiDroidhssm/collection.media.ad.db2 closed = true
08-05 16:45:38.616  12965-13128/com.ichi2.anki I/Collection﹕ Collection closed
08-05 16:45:38.616  12965-13128/com.ichi2.anki D/Connection﹕ doInBackgroundSync -- reopening collection on outer finally statement
08-05 16:45:38.618  12965-13128/com.ichi2.anki I/CollectionHelper﹕ openCollection: /sdcard/AnkiDroidhssm/collection.anki2
08-05 16:45:38.643  12965-13128/com.ichi2.anki D/Collection﹕ [1438757138] Collection.java:<init>(): /sdcard/AnkiDroidhssm/collection.anki2,  2.5alpha50
08-05 16:45:38.689  12965-13128/com.ichi2.anki D/Collection﹕ [1438757138] Sched.java:_updateCutoff(): 1116,  1438797600
08-05 16:45:38.692  12965-12965/com.ichi2.anki D/DeckPicker﹕ Sync Listener onPostExecute()
08-05 16:45:38.700  12965-13319/com.ichi2.anki D/DeckTask﹕ doInBackgroundSaveCollection
08-05 16:45:38.702  12965-12965/com.ichi2.anki D/DialogHandler﹕ Storing persistent message
08-05 16:45:38.703  12965-13319/com.ichi2.anki E/DeckTask﹕ Error on saving deck in background
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.ichi2.anki.AnkiDb.getMod()' on a null object reference
            at com.ichi2.libanki.Collection.save(Collection.java:260)
            at com.ichi2.libanki.Collection.save(Collection.java:245)
            at com.ichi2.async.DeckTask.doInBackgroundSaveCollection(DeckTask.java:503)
            at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:251)
            at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:74)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
08-05 16:45:38.703  12965-13319/com.ichi2.anki D/DeckTask﹕ Waiting for 2 to finish before starting 22
08-05 16:45:38.704  12965-13319/com.ichi2.anki D/DeckTask﹕ Finished waiting for 2 to finish. Status= RUNNING
08-05 16:45:38.706  12965-13319/com.ichi2.anki D/DeckTask﹕ doInBackgroundLoadDeckCounts
08-05 16:45:38.707  12965-13319/com.ichi2.anki E/DeckTask﹕ doInBackgroundLoadDeckCounts - error
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.ichi2.anki.AnkiDb.getMod()' on a null object reference
            at com.ichi2.libanki.Decks.recoverOrphans(Decks.java:697)
            at com.ichi2.libanki.Sched.deckDueList(Sched.java:389)
            at com.ichi2.libanki.Sched.deckDueTree(Sched.java:441)
            at com.ichi2.async.DeckTask.doInBackgroundLoadDeckCounts(DeckTask.java:490)
            at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:248)
            at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:74)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
08-05 16:45:38.708  12965-13319/com.ichi2.anki D/DeckTask﹕ Waiting for 22 to finish before starting 2
08-05 16:45:38.708  12965-13319/com.ichi2.anki D/DeckTask﹕ Finished waiting for 22 to finish. Status= RUNNING
08-05 16:45:38.710  12965-12965/com.ichi2.anki D/UIUtils﹕ saveCollectionInBackground: finished
08-05 16:45:38.710  12965-12965/com.ichi2.anki D/DeckTask﹕ enabling garbage collection of mPreviousTask...
08-05 16:45:38.710  12965-13319/com.ichi2.anki D/DeckTask﹕ doInBackgroundSaveCollection
08-05 16:45:38.711  12965-12965/com.ichi2.anki E/DeckPicker﹕ null result loading deck counts
08-05 16:45:38.711  12965-12965/com.ichi2.anki D/DeckTask﹕ enabling garbage collection of mPreviousTask...
08-05 16:45:38.714  12965-12965/com.ichi2.anki D/DialogHandler﹕ Storing persistent message
08-05 16:45:38.714  12965-13319/com.ichi2.anki E/DeckTask﹕ Error on saving deck in background
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.ichi2.anki.AnkiDb.getMod()' on a null object reference
            at com.ichi2.libanki.Collection.save(Collection.java:260)
            at com.ichi2.libanki.Collection.save(Collection.java:245)
            at com.ichi2.async.DeckTask.doInBackgroundSaveCollection(DeckTask.java:503)
            at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:251)
            at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:74)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
08-05 16:45:38.714  12965-13319/com.ichi2.anki D/DeckTask﹕ Waiting for 2 to finish before starting 22
08-05 16:45:38.714  12965-13319/com.ichi2.anki D/DeckTask﹕ Finished waiting for 2 to finish. Status= RUNNING
08-05 16:45:38.714  12965-12965/com.ichi2.anki D/UIUtils﹕ saveCollectionInBackground: finished
08-05 16:45:38.714  12965-13319/com.ichi2.anki D/DeckTask﹕ doInBackgroundLoadDeckCounts
08-05 16:45:38.715  12965-12965/com.ichi2.anki D/DeckTask﹕ enabling garbage collection of mPreviousTask...
08-05 16:45:38.715  12965-13319/com.ichi2.anki E/DeckTask﹕ doInBackgroundLoadDeckCounts - error
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.ichi2.anki.AnkiDb.getMod()' on a null object reference
            at com.ichi2.libanki.Decks.recoverOrphans(Decks.java:697)
            at com.ichi2.libanki.Sched.deckDueList(Sched.java:389)
            at com.ichi2.libanki.Sched.deckDueTree(Sched.java:441)
            at com.ichi2.async.DeckTask.doInBackgroundLoadDeckCounts(DeckTask.java:490)
            at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:248)
            at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:74)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
08-05 16:45:38.716  12965-12965/com.ichi2.anki E/DeckPicker﹕ null result loading deck counts
08-05 16:45:38.716  12965-12965/com.ichi2.anki D/DeckTask﹕ enabling garbage collection of mPreviousTask...
08-05 16:45:38.716  12965-12965/com.ichi2.anki D/DialogHandler﹕ Storing persistent message
08-05 16:45:38.717  12965-13319/com.ichi2.anki D/DeckTask﹕ doInBackgroundSaveCollection
08-05 16:45:38.718  12965-13319/com.ichi2.anki E/DeckTask﹕ Error on saving deck in background
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.ichi2.anki.AnkiDb.getMod()' on a null object reference
            at com.ichi2.libanki.Collection.save(Collection.java:260)
            at com.ichi2.libanki.Collection.save(Collection.java:245)
            at com.ichi2.async.DeckTask.doInBackgroundSaveCollection(DeckTask.java:503)
            at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:251)
            at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:74)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
08-05 16:45:38.718  12965-12965/com.ichi2.anki D/UIUtils﹕ saveCollectionInBackground: finished
08-05 16:45:38.719  12965-12965/com.ichi2.anki D/DeckTask﹕ enabling garbage collection of mPreviousTask...
08-05 16:45:57.081  12965-12965/com.ichi2.anki D/DeckPicker﹕ onResume()
08-05 16:45:57.083  12965-12965/com.ichi2.anki D/DialogHandler﹕ Reading persistent message
08-05 16:45:57.083  12965-12965/com.ichi2.anki D/DeckPicker﹕ Refreshing deck list
08-05 16:45:57.087  12965-13000/com.ichi2.anki D/DeckTask﹕ doInBackgroundLoadDeckCounts
08-05 16:45:57.096  12965-13343/com.ichi2.anki D/CollectionLoader﹕ CollectionLoader accessing collection
08-05 16:45:57.132  12965-12965/com.ichi2.anki W/System.err﹕ java.io.IOException: Error running exec(). Command: [sqlite3, --version] Working Directory: null Environment: null
08-05 16:45:57.132  12965-12965/com.ichi2.anki W/System.err﹕ at java.lang.ProcessManager.exec(ProcessManager.java:211)
08-05 16:45:57.132  12965-12965/com.ichi2.anki W/System.err﹕ at java.lang.Runtime.exec(Runtime.java:173)
08-05 16:45:57.132  12965-12965/com.ichi2.anki W/System.err﹕ at java.lang.Runtime.exec(Runtime.java:246)
08-05 16:45:57.132  12965-12965/com.ichi2.anki W/System.err﹕ at java.lang.Runtime.exec(Runtime.java:189)
08-05 16:45:57.132  12965-12965/com.ichi2.anki W/System.err﹕ at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.java:101)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at com.ichi2.anki.dialogs.DatabaseErrorDialog.onCreateDialog(DatabaseErrorDialog.java:24)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:308)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at com.ichi2.anki.AnkiActivity.showDialogFragment(AnkiActivity.java:313)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at com.ichi2.anki.AnkiActivity.showAsyncDialogFragment(AnkiActivity.java:326)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at com.ichi2.anki.DeckPicker.showDatabaseErrorDialog(DeckPicker.java:951)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at com.ichi2.anki.dialogs.DialogHandler.handleMessage(DialogHandler.java:80)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5254)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ Caused by: java.io.IOException: Permission denied
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at java.lang.ProcessManager.exec(Native Method)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ at java.lang.ProcessManager.exec(ProcessManager.java:209)
08-05 16:45:57.133  12965-12965/com.ichi2.anki W/System.err﹕ ... 22 more
08-05 16:45:57.164  12965-12965/com.ichi2.anki D/CollectionLoader﹕ CollectionLoader.deliverResult()

```

### PR DESCRIPTION
**Pull request by hssm**
Fixes #3598.

1 - DeckTasks are queued up and executed in sequence.
2 - When a sync is finished, the collection is closed and reopened (I don't remember why we do this). 

If DeckTasks are queued up *before* a sync finishes and run *after* the sync finishes, they will be using stale references to the Collection since we pass in a Collection object for them to use. This commit changes all DeckTasks to use the CollectionHelper to get a current reference to the collection.

I did a bit of a cleanup of DeckTask while fixing this issue. I've removed any dead code, unused methods, and redundant parameters/TaskData things.

### CODE REVIEW

**Comment by timrae** [comment]
I have this vague recollection that you tried to remove the Collection from the `DeckTask` arguments some time ago, and that created another bug or I didn't like it for some reason or something....? Do you remember? I guess we need to think about the implications

**Comment by hssm** [comment]
It was https://github.com/ankidroid/Anki-Android/pull/762#discussion_r26891100.

If my understanding is correct, the way it's being used here isn't a problem. We get the application context before we perform any DeckTask so we always have a context to work with.

And I just realised that the Travis CI build isn't running our tests...

**Comment by timrae** [comment]
OK yeah thanks, I think you're right as well, and keeping a reference to a context is no problem from a memory leak perspective, so long as it's the application context, not an Activity context. I'll try give the code a proper read through tomorrow.

**Comment by timrae** [comment]
Hopefully the Application context will not be null until after the last Async task is finished?

**Comment by hssm** [comment]
I don't see why it would become null as long as the application is still running. Do you mean to say that the application might be killed and then it fails? I think if we've already reached that point then all bets are off anyway.

**Comment by timrae** [comment]
I was imagining the scenario where the UI thread is destroyed before the
AsyncTask thread is destroyed... I think you're right though, it should be
totally fine to assume that won't happen under ordinary operating
conditions.

**Pull request merged**
