### PR TITLE
Card browser accepts empty answer string

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
It partially corrects #5694. The browser does not seems to be loading
anymore when the answer is an empty string. (E.g. if the answer
consists only of a music file, or anything else which was deleted
because it can't be rendered)
2020-01-05-054837_757x1242_scrot

### CODE REVIEW

**Comment by mikehardy** [comment]
@timrae ready to go I think - seems a little subtle but no more subtle then the original empty dectection, now at least empty ("") fields should not be conflated with unloaded fields and cause the eternal spinner problem I've seen in card browser

Separately there was a single-API transient sort of CI failure on last CI merge, I kicked it off again and it should build fine once it chews through backlog

**Comment by Arthur-Milchior** [comment]
Thanks for approving those changes.
I don't really see how it is "subtle" in any way. Null represents a missing value, empty string represents a value which is empty. And so when we used to read string, there is no a check for null before actually using the string. It seems pretty standard way to use null for me

**Comment by mikehardy** [comment]
I believe null has been called the trillion dollar mistake, and the amount of hits you get if you google NullPointerException indicate that there is always a little subtlety to null, but I do like the change and it's java enough for sure, idiomatically

**Comment by mikehardy** [comment]
Thanks for this @Arthur-Milchior !

**Pull request merged**
