### PR TITLE
Introduced assertEquals for int

### LINKED ISSUE #11965: Introduce `assertEquals` for `int`
Currently `assertEquals` only consider Long and Object. In Java, Int were converted to Long, but in Kotlin they are converted to Object. Which force conversion to explicitly write `toLong` to get the proper overloaded method to be invoked.

I suggest adding in AnkiDroid/src/test/java/com/ichi2/testutils/AnkiAssert.java the following methods

```java
    public static void assertEquals(int left, int right) {
        org.junit.Assert.assertEquals((long) left, (long) right);
    }

    public static void assertEquals(String message, int left, int right) {
        org.junit.Assert.assertEquals(message, (long) left, (long) right);
    }
```

and going through the 121 results of the search of `assertEquals\(.*long` in the codebase to uses this new method instead of the previous, and simplify the equality assertion slightly

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
Introduced `assertEquals` for `int`

## Fixes
#11965 

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
I suggest discussing on the original issue more. Particularly, I agree with David that adding a new method for this isn't necessary in Kotlin. Plus, I don't see any benefit removing `.toLong()` from tests right now.

**Comment by SanjaySargam** [comment]
> I suggest discussing on the original issue more. Particularly, I agree with David that adding a new method for this isn't necessary in Kotlin. Plus, I don't see any benefit removing `.toLong()` from tests right now.

Ok

**Comment by SanjaySargam** [comment]
> I suggest discussing on the original issue more. Particularly, I agree with David that adding a new method for this isn't necessary in Kotlin. Plus, I don't see any benefit removing `.toLong()` from tests right now.

So what changes need I render?

**Comment by BrayanDSO** [comment]
> So what changes need I render?

In my opinion, none. But please feel free to disagree

**Pull request closed without merging**
