### PR TITLE
System dark mode

### LINKED ISSUE #5685: Follow Android system-level dark mode settings
Hi. AnkiDroid has an app-specific dark mode that does not follow the system-level configuration present in newer versions of Android. Would you accept a up-to-standard pull request implementing automatically switching night mode on when Android system gets switched to night mode, and automatically switching night mode off when Android system night mode gets switched off?
If nobody has the bandwidth to fix this soonish, I might do it myself or maybe place a bounty on it.

###### Reproduction Steps

1. Start out with AnkiDroid in light mode, system in light mode
2. Turn on Android dark mode (e.g., using the quick settings bar in the notification bar)

###### Expected Result

AnkiDroid should follow the system-level dark mode settings and switch to dark mode.

###### Actual Result

AnkiDroid remains in light mode unless you manually switch it.

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by VishnuSanal**
## Purpose / Description
To make the AnkiDroid Android App follow the system dark mode

## Fixes
Fixes #5685

## Approach
Followed suggestions in [this](https://github.com/ankidroid/Anki-Android/pull/9408#issuecomment-944240970) comment

## How Has This Been Tested?

Tested on a real android device running Android 11

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

## Additional details

Superseded from #9408

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Few lint errors coming up regarding unused strings:

```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/01-core.xml:116: Error: The resource R.string.night_mode appears to be unused [UnusedResources]
Fix the issues identified by lint, or add the following to your build script to proceed with errors:
    <string name="night_mode">Night mode</string>
...
            ~~~~~~~~~~~~~~~~~
android {
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/10-preferences.xml:125: Error: The resource R.string.follow_system appears to be unused [UnusedResources]
    lintOptions {
    <string name="follow_system" maxLength="41">Follow System Theme</string>
        abortOnError false
            ~~~~~~~~~~~~~~~~~~~~
    }
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/10-preferences.xml:126: Error: The resource R.string.light_theme appears to be unused [UnusedResources]
}
    <string name="light_theme" maxLength="41">Light Theme</string>
...
            ~~~~~~~~~~~~~~~~~~

/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/10-preferences.xml:127: Error: The resource R.string.dark_theme appears to be unused [UnusedResources]
FAILURE: Build failed with an exception.
    <string name="dark_theme" maxLength="41">Dark Theme</string>
```

**Review by mikehardy — CHANGES_REQUESTED** [review]
Oh this is cool - I am excited to get this one in. A few issues:

1) there should never be changes in the language-specific values directories. Even for removals - just change the `/values/` languages files and that's it - our crowdin translation script infrastructure will handle the rest https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations

2) In the preferences screen, if they are in "single theme" mode, the two choices for default day / default night should be disabled (more gray, less white), if they are in the "follow system" mode, then the "single theme" choice should be disabled (more gray, less white)

3) With apologies it took a conflict, I think the Themes file may have been pulled from Java to Kotlin during our Kotlin migration. This is a big pain point for doing a migration like that and I'm not sure there is way to avoid it, all I can do is apologies profusely and ask you to check the conflict, possibly re-applying the original changes you made to the Java file to the new Kotlin file

**Comment by VishnuSanal** [comment]
>     1. there should never be changes in the language-specific values directories. Even for removals - just change the `/values/` languages files and that's it - our crowdin translation script infrastructure will handle the rest https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations

Okay.

>     2. In the preferences screen, if they are in "single theme" mode, the two choices for default day / default night should be disabled (more gray, less white), if they are in the "follow system" mode, then the "single theme" choice should be disabled (more gray, less white)

Agreed, now it gets disabled but it's not that obvious.

>     3. With apologies it took a conflict, I think the Themes file may have been pulled from Java to Kotlin during our Kotlin migration. This is a big pain point for doing a migration like that and I'm not sure there is way to avoid it, all I can do is apologies profusely and ask you to check the conflict, possibly re-applying the original changes you made to the Java file to the new Kotlin file
 > > ask you to check the conflict
 > > possibly re-applying the original changes you made to the Java file to the new Kotlin file

Sure.

**Comment by Arthur-Milchior** [comment]
Also, would you mind confirming that we are expected to review all of this as a single change, and once we are happy with it, we should squash it.
Or do you plan to transform it in a sequence of atomic commits?

**Comment by mikehardy** [comment]
@VishnuSanal and @Akshay0701 are you two coordinating? We appear to have two PRs here in flight at the same time, each with review comments that are really recent - this one and #10035 

Please communicate + coordinate between you two, then communicate with us what the forward path is.

**Comment by Akshay0701** [comment]
> @VishnuSanal and @Akshay0701 are you two coordinating?

@mikehardy nope, this pr has a conflict and @VishnuSanal didn't resolve that conflict, so I thought he abandoned this pr, so I resolved the conflict and made new pr,

now I see @VishnuSanal is active again, I will close my pr, reviewer can move forward with pr.

**Comment by VishnuSanal** [comment]
> Also, would you mind confirming that we are expected to review all of this as a single change, and once we are happy with it, we should squash it. Or do you plan to transform it in a sequence of atomic commits?

As you wish, I'm okay with either of those.

> @VishnuSanal and @Akshay0701 are you two coordinating? We appear to have two PRs here in flight at the same time, each with review comments that are really recent - this one and #10035
> 
> Please communicate + coordinate between you two, then communicate with us what the forward path is.

Akshay can take this forward. Thanks for letting me work on AnkiDroid.

**Pull request closed without merging**
