### PR TITLE
Bold font fix and streamline "Rename" dialogs.

### LINKED ISSUE #4052: Self-made flashcards only in bold font
# Problem description
I created flashcards with the default Desktop environments (Linux, Windows and Mac). They contain pictures, but mostly written english text with **bold**, underlined and _italic_ words. They are properly displayed in the Desktop applications. However on AnkiDroid all text except for _italic_ and underlined are displayed as **bold** (also regular text). This does not happen with other decks downloaded form the _Shared Decks_ platform.
# Example flashcard
```html
<div><b>Survey field studies</b></div>
<div>- &nbsp;Measurement problems</div>
<div>- &nbsp;Difficulty of determining causality</div>
<div><b>Field experiments &amp; quasi-experimental studies</b></div>
<div>- &nbsp;Implementation of a participative program + other interventions</div>
<div>- &nbsp;Temporary elation</div>
<div>- &nbsp;Resentment of the “untreated”</div>
<div>- &nbsp;Difficulty of comparing different studies</div>
<div><b>Measure of participation consequences</b></div>
<div>- &nbsp;Mostly: satisfaction + performance -&gt; insensitive criterion</div>
<div>- &nbsp;Underlying influences and motivational processes were often disregarded</div>
```
this code seems to be valid HTML and also displays properly in an [online HTML viewer](http://codebeautify.org/htmlviewer/cbf4e5d5)
# AnkiDroid badly formatted display
Android Screenshot

### PR DESCRIPTION
**Pull request by eginhard**
Fixes #4052

### CODE REVIEW

**Comment by timrae** [comment]
Nice find! This won't actually correct the error for users currently experiencing the problem right? It'd be nice to attempt to correct the error in the default 'Basic' model when upgrading

**Comment by eginhard** [comment]
Yes, the styling will remain the same on existing note types. It should be
easy to fix this for users, although this will probably lead to quite a few
people asking why the font is suddenly not bold anymore. :D

**Comment by hssm** [comment]
@eginhard before we forget, were you planning to work on a fix for existing collections? I think it's important that we fix errors we've introduced.

With the error included, the appearance of cards will be different to the desktop client, so we have consistent appearance as another point in favor of doing it.

**Comment by eginhard** [comment]
@hssm Sorry, I'm quite busy right now and don't really have time for this during the next 3 weeks, but I can do it after that.

**Pull request merged**
