### PR TITLE
fix: IDE lint in SchedTimingToday

### PR DESCRIPTION
**Pull request by oyeraghib**
## Purpose / Description
fix IDE lint by renaming the functions names in SchedTimingToday.kt

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Consistency with Anki Desktop is more important than lint here. Propose to ignore the naming-based lint issues.

**Review by Koudinka — APPROVED** [review]

**Comment by oyeraghib** [comment]
> Consistency with Anki Desktop is more important than lint here. Propose to ignore the naming-based lint issues.

Okay, I understand! Thanks.

**Comment by david-allison** [comment]
To note: I'd approve of  a `@SuppressLint` here

**Comment by oyeraghib** [comment]
@david-allison What would be the value for `@SuppressLint` here? Is it `"VariableNamingDetector"` ?

**Comment by david-allison** [comment]
you can find out from theQuick fixes menu

Screenshot 2022-07-21 at 13 38 11

**Comment by oyeraghib** [comment]
Something interesting happened. As I closed this PR, and then `forced pushed`, now it says `The ____ branch was forced push or recreated`. A new branch has been automatically created by GitHub from which I can make a new PR.

I went through [this](https://github.com/isaacs/github/issues/361) and realized many people have been through the same problem and GitHub officially hasn't come up with anything for this. Interesting!

**Comment by dae** [comment]
An argument in favour of using more natural naming instead: https://github.com/ankidroid/Anki-Android/issues/11582

**Pull request closed without merging**
