### PR TITLE
To handle TalkBack issue

### PR DESCRIPTION
**Pull request by jindalshiva**
## Purpose / Description
_When the user enable TalkBack, then there were some issues with the UI of the app._

## Fixes
Fixes _https://github.com/ankidroid/Anki-Android/issues/7913_

## Approach
_I had to make changes in the XML files of the app, make some graphics and buttons of the app focusable_

## How Has This Been Tested?
Test this app by running this updated code, on your physical devices or emulator and also enable TalkBack on the device. 

## Learning (optional, can help others)
_Started by learning about TalkBack. After this, I started making some changes to it._

_https://support.google.com/accessibility/android/answer/6283677?hl=en_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Thanks for the PR!

This contains a lot of changes which aren't related to the work you've done.

Could you rebase your commit onto master, such that the review only contains your change(s):  (https://github.com/ankidroid/Anki-Android/pull/8286/commits/41e0165b4f680ec022e05e23d89a9275fe7d94c5)

**Comment by mikehardy** [comment]
What does "My Feature Branch" mean as a PR title :thinking:

**Comment by jindalshiva** [comment]
Actually, I am not so good at using GitHub, so while learning about how to send a pull request, So, I started using your documentation. So, I used the same name as mentioned in the documentation.

**Comment by mikehardy** [comment]
> Actually, I am not so good at using GitHub, so while learning about how to send a pull request, So, I started using your documentation. So, I used the same name as mentioned in the documentation.

And that's okay :-), we are here to learn. What we mean by "my feature branch" is a meaningful name (your feature branch should have a meaningful name as well, right?). So this should be something like "Add ... to handle TalkBack" or something similar. Something that tells us what the PR is doing.

**Comment by jindalshiva** [comment]
I have rebase the commit, could you please confirm it?

**Comment by jindalshiva** [comment]
I have rebase the commit, could you please confirm it?
@david-allison-1

**Comment by mrudultora** [comment]
Hi @jindalshiva, thanks for the PR. This PR already contains changes done by other people also. And, CI is failing too. I suggest you to look at some beginner friendly git videos. The important point is that this PR must contain changes done in this commit only `
41e0165`

**Comment by david-allison-1** [comment]
> I have rebase the commit, could you please confirm it?
> @david-allison-1

It's still showing as 65 commits in GitHub - will need another interactive rebase

**Comment by jindalshiva** [comment]
Sorry, I couldn't find any better material to keep just my commits, hence I am closing this one and will open a new one with only my changes listed.

**Pull request closed without merging**
