### PR TITLE
Code cleaning: using enum where possible

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This PR (quite simplified compared to first version), replace some else -> by an exhaustive constant list. This will ensure that if more enum are added, we won't forget to consider all enums

### CODE REVIEW

**Comment by david-allison** [comment]
Could you split this into a few smaller PRs? This isn't going to be easy to review otherwise, especially as it's low priority.

The first commit in the series uses single variable names for a class (`.B` implies `boolean`), which doesn't feel at all intuitive. I suspect the rest is mergeable, but it's a huge time commitment in this state, and attracts conflicts

**Comment by Arthur-Milchior** [comment]
@david-allison done

**Comment by david-allison** [comment]
Tests fail on this one

**Comment by Arthur-Milchior** [comment]
Actually needed to be closed, everything was merged in separate PR

**Pull request closed without merging**
