### PR TITLE
Fix scrollbar's position not remembered in CardBrowser #6857

### LINKED ISSUE #6857: Card Browser doesn’t remember scroll position after editing card
###### Reproduction Steps

1. Open the Card Browser.
2. Scroll down and tap on a card low on the list.
3. Edit the card and tap the “Save” (check mark) button.

###### Expected Result

The card list should appear in the same scroll position from which I tapped on the card, with the edited note visible. This is how it used to work before.

###### Actual Result

The top of the note list is shown, such that, if I want to edit multiple notes in a row, I'm made to scroll down every time.

###### Debug info

AnkiDroid Version = 2.12.1

Android Version = 9

ACRA UUID = 869df53d-5443-4c1e-86cf-3fa599383fc6

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by tda1009**
## Fixes
Fixes #6857 

## Approach

**Problem Analysis**

The scrollbar's position is reset because, when user edits and saves a note in NoteEditor, NoteEditor sends a "noteChanged" event back to CardBrowser. In method onActivityResult() of CardBrowser, this event causes a reload, which resets the scrollbar position.

In my opinion, the solution which programmatically scrolls to the old position (using methods like ListView.setSelection(oldPosition)) might be suboptimal, because after scrolling like this, we still have to handle the logic to show / hide progressbar. This is a nontrivial task because method onScroll() of ListView gets called multiple times, asynchronously and unpredictably.

In search for a simpler solution, I think that a reload for the "noteChanged" event (sent from NoteEditor to CardBrowser) might not be necessary.

(with other events like adding note(s) or previewing card(s), a reload is still necessary, because:
when adding note(s), the number of notes is changed
when previewing card(s), multiple of notes can be editted before the user comes back to CardBrowser, in this case, it does not make sense to remember the scrollbar's old position)

**The Solution**

In this PR, I remove the "noteChanged" event (sent from NoteEditor to CardBrowser) from the list of events that cause a reload (in onActivityResult() of CardBrowser).

After doing this, now when I tap on a row in CardBrowser (to navigate from CardBrowser to NoteEditor), make changes to the selected note in NoteEditor, save the changes, and come back to CardBrowser, 2 things are achieved:
\* the scrollbar still remains at its previous position.
\* the note gets updated with new modification.

(the note gets updated in CardBrowser even without a reload because in onActivityResult() of CardBrowser, the "noteChanged" event still triggers the UPDATE_NOTE collectionTask, which will eventually call notifyDatasetChanged() on mCardsAdapter)

## How Has This Been Tested?

I have tested this solution in Emulator (API 27 and API 28).

First I verified that the solution works as expected.

After that I ran the following automatic tests and they all passed:
\* unit tests in com/ichi2/anki
\* instrumentation tests

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
I haven't reviewed the PR code yet, just this assertion

> In search for a simpler solution, I think that a reload for the "noteChanged" event (sent from NoteEditor to CardBrowser) might not be necessary.

Card Edits may generate or delete cards via selective generation when you have conditional fields in your template, this may affect the amount of cards in the browser after an edit https://docs.ankiweb.net/#/templates/generation?id=selective-card-generation

I think that's why there's a reload after note edit

Perhaps the scroll could be a seek to the previous card and only go back to the top if the card completely disappeared?

**Comment by tda1009** [comment]
Hi @mikehardy, you are right, I was not aware of the fact that in Anki and AnkiDroid, editing a card might lead to other cards being created, thank you for pointing this out.

> "Perhaps the scroll could be a seek to the previous card and only go back to the top if the card completely disappeared?"

I just push a commit (commit "Scroll to previously selected card") to accomplish this requirement.

As discussed, after user edits a card and comes back to CardBrowser, a reload must be done. This also means the CardsList (in CardBrowser) is always re-sorted each time a card changes. This commit proposes a solution to maintain the visible position of the card on screen, even when it's real position in the list has changed.

I aslo push another commit (commit "Handle progress bar"). The reason is: after auto-scrolling to the card's previous position, sometimes the progress bar (the circular loading icon) disappears, sometimes is does not. I think this is because, after auto-scrolling with method setSelectionFromTop(), method onScrollStateChanged() is not fired, so method hideProgressBar() is not called. To deal with this problem, I used a boolean flag inside method onScroll() to decide whether or not to show the progress bar.

I verified on Emulator (API 27 and 28) that these two commits work as expected. I also ran the automated tests and they passed.

Please take a look at these commits.

**Comment by mikehardy** [comment]
This one took a conflict which I believe I resolved correctly as the OnClickListener was refactored to a lambda in #7210 - at the same time I corrected order-of-operations for position/cardid calculation prior to opening the other activity, but the variables still need dehydration/rehydration handling in onSaveInstanceState/onCreate

**Review by mikehardy — CHANGES_REQUESTED** [review]
need dehydration/rehydration handling of all new instance variables in onSaveInstanceState/onCreate

**Comment by tda1009** [comment]
Hi @mikehardy , thank you for your feedback, and for merging the new changes from master to this PR.

I know you are busy with other problems of AnkiDroid so it might take some time before you reply.

I also think that you might not like this PR because it is not very elegant: quite a few member variables are added and used throughout the activity just to implement a 'good first issue'. But I've not yet found a better way to achieve the original goal while keeping changes to AnkiDroid's existing codebase to a minimum. If this PR is not good enough, maybe we should discard it and wait for another better solution in the future?

Anyway, based on your latest suggestions, I've updated the PR with commit "Improve handling of scrolling state variables"

Basically in this new commit I did 2 things:
* save & restore scrolling state variables using savedInstanceState
* save scrolling state variables in mCardsListView.setOnItemLongClickListener() (in the previous commit, I only saved them in mCardsListView.setOnItemClickListener())

After these new changes, I tested and the PR worked correctly.

One thing I would like to say about screen rotation: I've considered this in the previous commit, but because in the app's manifest file, activity CardBrowser declared that it will not restart when rotation happens, so I think we don't need to save the state variables for this purpose. But you are absolutely right: those state variables still need to be saved / restored for other cases, like when the user navigates away, does something else and then comes back => CardBrowser might be re-created.

**Comment by mikehardy** [comment]
When I reviewed last time I wasn't aware of a better solution actually, given that the Activity may have it's cards all change underneath it, it has to save enough information to attempt to scroll back almost from scratch which implies all this instance state, so design wise I think it is a bit nasty but also optimal - frequently that is the way of things with Android :-). Thanks for handling the Activity restart case and I'll re-scan it. Might be good to go...

**Review by mikehardy — APPROVED** [review]
This was a user complaint recently even - sorry for the delay in review, you handled my last comment exactly right I think. @david-allison-1 what do you think?

**Comment by mikehardy** [comment]
@david-allison-1 well it was waiting for review in general but not yours specifically, I only just tagged you :-)

**Comment by david-allison-1** [comment]
Works for me

**Comment by mikehardy** [comment]
Merged 🚀  - will be out in the next 2.14 alpha in a few hours, thanks @tda1009 !

**Comment by tda1009** [comment]
Hi @mikehardy Thank you for merging the PR,

There's one small problem though: The commit description is currently like this:

> 
> * Fix scrollbar's position not remembered in CardBrowser
> 
> The scrollbar's position is reset because, when user edits and saves a note in NoteEditor, NoteEditor sends a "noteChanged" event back to CardBrowser. In method onActivityResult() of CardBrowser, this event causes a reload, which resets the scrollbar position.
> 
> In this PR, I remove the "noteChanged" event from the list of events that cause a reload (in onActivityResult() of CardBrowser).

It is part of my first message in this PR, but now it's out-dated and incorrect because the PR has changed significantly after our discussion. In other words, it is not what has been done.

The correct commit description should be:

_\* add some scrolling state variables in CardBrowser, save them before NoteEditor is launched
\* when CardBrowser is visible again => restore these variables and then perform an auto-scroll using setSelectionFromTop()
\* handle showing & hiding the progress bar properly after above changes_

If possible, could you please help me to update the commit with this correct description?

**Comment by mikehardy** [comment]
Sorry, that won't be possible - once it's merged to master that's it, it is poured i concrete, however the commit and the PR will be cross-linked now and if there are questions people will be able to deduce

**Pull request merged**
