### PR TITLE
Fix: Retain Search Filter After Deleting or Renaming Note Type in ManageNotetypes

### LINKED ISSUE #17101: [BUG]: Search Results Reset After Deleting or Renaming a Note Type
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Go to Manage Note Types
2. Search something
3. Delete or Rename note type from filteredList

### Expected behaviour

After deleting or renaming a note type from the filtered search results, the list should remain filtered based on the original search query, displaying only the note types that match the query

### Debug info

```text
AnkiDroid Version = 2.19beta2-debug (1f3d0bdcfbc3c1d6a7862da889e669b4c270a7a3)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 14 (SDK 34)

ProductFlavor = amazon

Manufacturer = OPPO F21 Pro 5G

Model = CPH2341

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; RMX3521 Build/UKQ1.230924.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.146 Mobile Safari/537.36

ACRA UUID = 15292e55-b323-4593-a062-b0a27fae21ec

FSRS Enabled = false

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by gayatriii0803**
## Purpose / Description
This PR addresses an issue where the note types list would reset to display all items after a note type was deleted or renamed, even if a search filter was applied.

## Fixes
* Fixes #17101 

## Approach
`filterNoteTypes` after deleting or renaming note

## How Has This Been Tested?
Oppo F21 Pro 5G

https://github.com/user-attachments/assets/534943e8-729c-4061-9190-ba3c44088841

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
Looks good! Could you add a `@NeedsTest("")` annotation, which explains what a regression test would be looking for

**Review by mikehardy — APPROVED** [review]
This seems fine, thank you!
I rebased to current main
I added the NeedsTest annotation David mentioned
So this can move forward

**Comment by david-allison** [comment]
* Fixed lint error in import ordering
* Improved commit message

**Comment by mikehardy** [comment]
> Fixed lint error in import ordering

🤦  sorry about that

**Comment by david-allison** [comment]
I didn't get any errors in `./gradlew lint`, might want to investigate further, but it's a very minor issue

**Pull request merged**
