### PR TITLE
Codecov tuning

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

- codecov was not posting expected coverage results
- codecov graphs had useless coloration
- github workflows were not executing on workflow definition changes

## Fixes
Fixes issue noticed by @david-allison-1 that coverage diffs weren't as expected, e.g. https://github.com/ankidroid/Anki-Android/pull/7977#issuecomment-751676625 where root cause appears to be 

>  ->  Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0

...from https://github.com/ankidroid/Anki-Android/pull/7977/checks?check_run_id=1616994735

## Approach
- set github checkout action to fetch-depth of 20, that's fairly arbitrary but should cover all our PRs
- set coverage range minimum to 36 so that coloration divergence starts from our current baseline
- add workflow files to the path inclusion list for workflow execution

## How Has This Been Tested?

It is literally made of tests. The codecov comment on this PR should show whether it worked.

## Learning (optional, can help others)
The default, we only need to override one part: https://docs.codecov.io/docs/codecov-yaml
The config reference: https://docs.codecov.io/docs/codecovyml-reference

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

**Review by david-allison-1 — COMMENTED** [review]
I've recently cut down #7962 from 46 commits to 21, this is an unusual case (it's a draft and subject to further changes), but likely implies the current limit is a little too low

**Comment by mikehardy** [comment]
Just realized I have workflow exclusions set up and still fiddling with this one, 21 is quite large but this is arbitrary anyway and almost any number is less than 12,074 current comments, I'll set it to 50 and repush :-)

**Comment by mikehardy** [comment]
This looks mostly normal but I fear the parts that aren't exactly what I want are because the current main branch report is somewhat polluted by fetch depth issues or similar.

I'm going to merge these though as I think they are correct by themselves, and the reports will even out once this one is through

**Comment by mikehardy** [comment]
Note that "unexpected decreases in coverage" may occur for many reasons, and timing-dependencies in tests are one possible cause as they may impact execution plans. I think that may be occurring here

**Pull request merged**
