### PR TITLE
refactor: make functions in UIUtils class as top level

### LINKED ISSUE #16146: UIUtils: move towards making these kind of functions as top level
We should move towards making these kind of functions as top level, using an object as namespace is java like behavior.

_Originally posted by @lukstbit in https://github.com/ankidroid/Anki-Android/pull/15699#discussion_r1536748258_

### PR DESCRIPTION
**Pull request by 410063005**
## Purpose / Description
_Describe the problem or feature and motivation_

Move functions in UIUtils class as top level to make it more Kotlin. 

## Fixes
* Fixes #16146

## Approach
_How does this change address the problem?_

Update UIUtils class and its related lint rule.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

Tested on:
- Emulator - Pixel XL (API 31)

Step 1: run `./gradlew lintPlayDebug :api:lintDebug ktLintCheck lintVitalFullRelease lint-rules:test` and all tests pass

Step 2:  set a background image and then remove it, the `showThemedToast()` works well as before

### Before
image

### After

image

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by 410063005** [comment]
I'm not sure that L59 works as expected after these changes. I need some help here.

https://github.com/ankidroid/Anki-Android/blob/175dee49d1279bad5a83fb2c91c067250774cafc/lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectToastMakeTextUsage.kt#L50-L60

**Comment by 410063005** [comment]
`./gradlew lintPlayDebug :api:lintDebug ktLintCheck lintVitalFullRelease lint-rules:test` works well. 

But this unit test failed unexpectedly. I can't find a way to make the actions run again.

```
CardBrowserTest > resetDataTest FAILED
    java.lang.AssertionError: Initial due of checked card
    Expected: "8/12/20"
         but: was "8/13/20"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
```

**Comment by neeldoshii** [comment]
Instead of closing the old PR, next time consider rebasing your branch, git reset and use the same PR. This helps in maintaining a cleaner history.

**Comment by 410063005** [comment]
@neeldoshii  Thank you. I really need some time to figure out how it works.

 Sometings I try ideas and open a demo PR in my own repo.  I don't know that may have some effect on this repo.

**Review by lukstbit — APPROVED** [review]
LGTM, thanks for the quick fix!

@410063005 There's no issue with creating PRs in your own repo(as you own it).

**Review by david-allison — APPROVED** [review]
Looks great, cheers!

**Pull request merged**
