### PR TITLE
add icons to controls

### LINKED ISSUE #14243: Add icons to commands
Probably best to be done after #14242, so some commands can live without icons like answer button 1, 2, 3, 4

Most of the commands already have a suitable icon since most are also app bar commands. Others are going to need some creativity to pick good icons.

The task doesn't need to be done for all icons at once, but as much icons as possible in a single PR would facilitate IMO

### PR DESCRIPTION
**Pull request by RobozinhoD**
## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
#14243 

## Approach
i added the icons to the prefs and changed some colors to colorControlNormal which is what people tend to use ofr icons

i didnt know what to use in all of them so i put icons only in some controls

## How Has This Been Tested?

in the emulator
image

image

image

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [X] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
From the screenshots attached, Card Info and Whiteboard editor colors are different. IIRC, they are using `?attr/iconColor`.

The point about using `colorControlNormal` like most apps do is valid, so I'd be okay to change the uses of `iconColor` with `colorControlNormal`

**Comment by RobozinhoD** [comment]
okay. replaced iconColor with colorControlNormal

**Review by BrayanDSO — APPROVED** [review]
LGTM. I removed the "Fixes" keyword to avoid closing the original issue, since there are still some icons to be added

**Review by lukstbit — APPROVED** [review]
Looks like a nice change, thanks!

**Pull request merged**
