### PR TITLE
Updated the cursor colour in all themes

### LINKED ISSUE #12337: [Bug] The same colour of a cursor and the background
###### Reproduction Steps
1. Have Light Day theme
2. Open Card browser
3. Tap Search
4. Type some text
5. Tap inside the text

###### Expected Result
The cursor is visible

###### Actual Result
The cursor has the same colour as the background

###### Debug info
AnkiDroid Version = 2.16alpha83

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 5df52f79-f5cd-436f-8b15-11830f324973

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by pratyaksh1610**
## Purpose / Description
Changed the cursor colour to white.

## Fixes
fixes #12337

## Screenshots for all themes

| WhatsApp Image 2022-09-24 at 9 15 40 PM |
WhatsApp Image 2022-09-24 at 9 15 39 PM (1)
 | WhatsApp Image 2022-09-24 at 9 15 39 PM
 | 
WhatsApp Image 2022-09-24 at 9 15 38 PM

### CODE REVIEW

**Comment by ShridharGoel** [comment]
It would be better to use a more descriptive PR title and commit message which indicates that you have changed the cursor colour to white.

**Comment by ShridharGoel** [comment]
Will this change not cause unintended changes at other places?

**Comment by pratyaksh1610** [comment]
> Will this change not cause unintended changes at other places?

I don't think so, it will only change the cursor colour to white in light theme.

> It would be better to use a more descriptive PR title and commit message which indicates that you have changed the cursor colour to white.

Oh, I missed that .

**Comment by pratyaksh1610** [comment]
@ShridharGoel It managed to change at all places , as I made the change at the highest level, I think change needs to be made in the theme of `toolbar section` only.

**Review by ShridharGoel — APPROVED** [review]

**Comment by pratyaksh1610** [comment]
@ShridharGoel Just a quick follow up, after this change , in all themes the colour changes to white, so is the change required in all themes or in light theme only.
PTAL.
Thanks.

**Comment by ShridharGoel** [comment]
@pratyaksh1610 It should be fine since `textColorPrimary` and `textColorSecondary` are also set as white.

**Comment by BrayanDSO** [comment]
FYI, colorControlActivated changes switches, dialogs details, progress bar colors + a lot of things.

Also, there are other ways of changing the cursor color which can be found on the internet or be looked at Android's source.

Also 2, ?attr/colorPrimaryDark would be better here

**Comment by ShridharGoel** [comment]
This change is in ActionBarStyle, so shouldn't affect those components.

**Comment by BrayanDSO** [comment]
> This change is in ActionBarStyle, so shouldn't affect those components.

Didn't pay attention. But I still definetely don't like white here. As part of the cursor fuses on the bottom with the white background.

Nor I like changing the other themes and breaking their consistency (i.e. having a different cursor color at the action bar for no reason)

**Comment by pratyaksh1610** [comment]
@BrayanDSO  I think the colour of the cursor needs to be changed due to the fact that it is hidden due to the colour of action bar in light theme .

**Comment by BrayanDSO** [comment]
Yes. I haven't said that the color should not been changed. I'm just saying
that 1. White isn't a good color for it; 2. If possible, just change the
color at the Light theme, which is the only theme with the problem

**Comment by pratyaksh1610** [comment]
@BrayanDSO Yes, I also think that we should change the colour in light theme only without affecting the others,
Any preference for cursor colour ?

**Comment by pratyaksh1610** [comment]
@BrayanDSO  I explored a lot but unable to find any method by which the cursor colour changes in only light theme.

**Comment by mikehardy** [comment]
Sorry to put this one in a stalled state, but until the difference of opinion (color) and technical challenge (reduce scope of change?) has consensus it doesn't seem right to merge this one

**Comment by BrayanDSO** [comment]
Try creating a custom color attribute, set it as the color of `colorControlActivated` at the action bar style, then declare the color on each of the 4 AnkiDroid themes (light, plain, dark and black). It should use `?attr/colorControlActivated` on plain, dark and black, and probably `?attr/colorPrimaryDark` on the light theme

**Pull request closed without merging**
