### PR TITLE
Typo correction for French stats

### PR DESCRIPTION
**Pull request by viivgit**
Just a one letter mistake that I corrected in the French stats screen.

### CODE REVIEW

**Comment by mikehardy** [comment]
Hi there! Thank you so much for helping to improve AnkiDroid's translations

These files here are actually pulled in from the crowdin platform though, where it is much easier to collaborate on translations specifically - could you make the change there? https://github.com/ankidroid/Anki-Android/wiki/Contributing#translate-ankidroid

If we make the change here, the next time we sync from crowdin it will be overwritten

**Comment by viivgit** [comment]
It seems that someone corrected it 13 days ago on Crowdin. Does it seem normal it is not live on 2.9.3 which was released 5 days ago (I checked that's the one I'm running).

**Comment by mikehardy** [comment]
That does seem normal, I am doing the releases and I would be doing the sync with crowdin and I have not synced crowdin in a while. I'll put it on the list but you will have to be patient - I'm working through fixes for crashes right now which is a higher priority than translation changes sorry :-)

Happy to hear the community is keeping the translations up to date though - that's 100% community effort

**Comment by viivgit** [comment]
Sounds good, thanks for the great work! I was just making sure there wasn't some kind of automated routine falling or something along these lines :)

**Pull request closed without merging**
