### PR TITLE
Update severity for time related lint violations

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description
Update the lint rules related to Anki time to make Android Studio apply them and to break builds by changing the severity. By using the FATAL severity the release APK will not be built if any of the time related violations are broken.

Remember to **clean** the project and then **rebuild** it to make the rules available in Android Studio.

## Fixes
This is related to the discussions in #6956 and #6965 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
Does this look like the output you expect?
https://travis-ci.org/github/ankidroid/Anki-Android/jobs/721765688#L362

Apologies that those artifacts are published exactly *nowhere* so it's not possible to really inspect them. But you can likely locally test by inserting a bad usage then running the release lint to make sure it fails, removing it and making sure it passes.

I'll migrate the lint checks to github actions in the hopefully-near future so I can publish those artifacts more easily...

**Comment by mikehardy** [comment]
:thinking: I would expect this to fail until #6965 is merged? But I may have incorrect expectations

**Comment by lukstbit** [comment]
@mikehardy Yes this will fail until that PR will be merged. I'm not sure if @Arthur-Milchior implemented all the changes there so there might still be some failing pieces of code.

**Comment by mikehardy** [comment]
Great! Thank you @lukstbit I can see it failing now on lint release (as it should be...) I'll figure out how to get these two related PRs in together

**Comment by Arthur-Milchior** [comment]
Here is the error message obtained.

Wonderful

>> Lint found errors in the project; aborting build.
>  
>  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
>  ...
>  android {
>      lintOptions {
>          abortOnError false
>      }
>  }
>  ...
>  
>  The first 3 errors (out of 14) were:
>  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java:130: Error: Use the collection's getTime() method instead of directly creating Calendar instances [DirectCalendarInstanceUsage]
>          final Calendar calendar = Calendar.getInstance();
>                                    ~~~~~~~~~~~~~~~~~~~~~~
>  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/CardStats.java:18: Error: Use the collection's getTime() method instead of directly creating Calendar instances [DirectCalendarInstanceUsage]
>          Calendar cal = Calendar.getInstance();
>                         ~~~~~~~~~~~~~~~~~~~~~~
>  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java:2093: Error: Use the collection's getTime() method instead of directly creating Calendar instances [DirectCalendarInstanceUsage]
>          Calendar calendar = Calendar.getInstance();
>                              ~~~~~~~~~~~~~~~~~~~~~~


First time I'm happy to see Travis fail !


Ive rebased https://github.com/ankidroid/Anki-Android/pull/6965 on top of this branch, to ensure that I did not miss any other time method

**Comment by mikehardy** [comment]
I will close this in a little bit as the commit will be carried in on #6965 once that is settled in - having it included there is useful as the lint change is together with the fixes

**Comment by Arthur-Milchior** [comment]
Do you think you could rebase over master, or merge with master, so that the conflict disappear ? I would suspect that just keeping all lines would be a correct resolution, but I don't know what I'm doing so prefer to avoid

**Comment by lukstbit** [comment]
@Arthur-Milchior I rebased off master and solved the merge conflict.

**Comment by Arthur-Milchior** [comment]
Thanks. I rebased mine on top of you

**Comment by mikehardy** [comment]
Thank you guys for working through all the rebasing and merging etc. Git is pretty powerful but truly distributed collaboration on a coordinated change is still a challenge...

**Comment by mikehardy** [comment]
Got these that are failing:

```
  

  The first 3 errors (out of 13) were:

  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/Whiteboard.java:53: Error: Custom view Whiteboard is missing constructor used by tools: (Context) or (Context,AttributeSet) or (Context,AttributeSet,int) [ViewConstructor]

  public class Whiteboard extends View {

               ~~~~~~~~~~

  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java:130: Error: Use the collection's getTime() method instead of directly creating Calendar instances [DirectCalendarInstanceUsage]

          final Calendar calendar = Calendar.getInstance();

                                    ~~~~~~~~~~~~~~~~~~~~~~

  /home/travis/build/ankidroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/CardStats.java:18: Error: Use the collection's getTime() method instead of directly creating Calendar instances [DirectCalendarInstanceUsage]

          Calendar cal = Calendar.getInstance();

                         ~~~~~~~~~~~~~~~~~~~~~~
```

And this unrelated one that is neverthless worrisome - I'll fix it on crowdin:

```
> Task :api:bundleLibCompileToJarRelease FROM-CACHE

> Task :api:compileLint

/home/travis/build/ankidroid/Anki-Android/AnkiDroid/build/intermediates/incremental/mergeReleaseResources/merged.dir/values-ru/values-ru.xml:1402: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
```

**Comment by mikehardy** [comment]
Okay - the PR that is going to fix these - #6965 - is about to land, after removing these from the commit series, once that lands, then this may be rebased on top of it and should succeed? Then we merge this one and all move forward :-)

**Comment by lukstbit** [comment]
@mikehardy 

> ...then this may be rebased on top of it and should succeed?

Rebasing off master still showed a warning in the Whiteboard class about missing constructors(there was a request to enable this check). I suppressed that warning with SuppressLint because that view is used in just one place and is created programmatically, if someone would use it in xml it will fail so the suppressing is not a problem. With this change lint shows no problems for the release build.

**Comment by mikehardy** [comment]
Hello! with the 2.14 release we started accepting donations with the stated goal of accepting money from users (the users' way of saying "Thanks!") to support maintenance and development of AnkiDroid.

We are looking through PRs merged in releases going back to release 2.10 (where we have good record keeping of what's in releases) to let our contributors know.

If you'd like to submit an expense related to your work here, to share in a portion of our hopefully-sustainable monthly disbursement, please read here and do so in the next couple of days:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process

This is our first time handling donations and attempting to compensate anyone with these processes, so please be flexible and patient with us

Thank you for your contribution to AnkiDroid!

**Pull request merged**
