### PR TITLE
Better night mode and top review counts bar

### PR DESCRIPTION
**Pull request by ospalh**
* Move the review counts up a bit. Looks better now, with the border around the flash card gone
* Do not set the review buttons background to white explicitly. Probably redundant now
* Use 48 dp high flat buttons as persistent footer buttons. Rename the style, which is used only for these footer buttons
* Dark night mode top bar with light new, learn, review counts

Before: 
night_mode_before

After:
night_mode_after

The different steps as several commits:
[This branch](https://github.com/ospalh/Anki-Android/tree/feature-review-buttons-and-night-mode-comments)

The white frame around the answer buttons at the bottom doesn’t look *that* bad now, but it is quite glaring, literally, when you want to review at night. The shadows around those buttons are against Google’s style, anyway:
“[Never use raised buttons within persistent button areas.](https://www.google.com/design/spec/components/buttons.html#buttons-usage)”

The buttons are of course flat in day mode now, too:
day_mode_after

(One thing i did not quite understand: a lot of the `material_NN_x` colors (`material_green_600` &c.) have an alpha component in the `colors.xml` file. I don’t know why or whence. I added three which i took from [here](https://www.google.com/design/spec/style/color.html#color-color-palette) that have no alpha value.)

### CODE REVIEW

**Comment by timrae** [comment]
Maybe store the 48dp layout_height as a constant in dimens.xml rather than hardcoding

**Comment by timrae** [comment]
We should probably move *all* the paddings to dimens, so no problem if you can't be bothered moving it at the present time

**Comment by ospalh** [comment]
This “touch target height” is basically where i got the 48 from.

**Comment by ospalh** [comment]
Thanks.

Hmm.
I don’t quite understand github.
Looks like you can add commits, but when you rebase it, e.g. to squash two commits into one, push `-f` to that branch, *that* change is not applied.

**Comment by timrae** [comment]
Usually it works, not sure what happened here. Anyway, any more PRs planned today or should I go ahead and release a new alpha?

**Comment by ospalh** [comment]
I’m done for now :grin:

**Comment by timrae** [comment]
I suppose there should maybe be *some* padding between the bottom of the Webview and the buttons... What version of Android are you using btw? I get a blue status bar on Lollipop.
screenshot 22-06-2015 11-56-03 pm

**Comment by ospalh** [comment]
> padding

Hmm. You do have the `margin: 0.5em;` from the flash card style. This is a bit like the lower border of a browser window, where the content gets cut off.

I’m not sure that padding would look any better than this: What color? when you have non-black card background having a black stripe between the buttons and the card would look odd, too.

> version?

Different Kitkats. The images are with 4.4.2.

**Pull request merged**
