### PR TITLE
NF: Clean finder

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
I learned my lesson. Before doing an actual PR with any effect, I'm doing the cleaning first.
In this case, I remove unused method, which allow to simplify other methods.

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
I originally did a single PR, and at last moment realized that it would be "simpler" to split it... how silly was I

**Comment by Arthur-Milchior** [comment]
Actually, this error message seems to be related to a version of the code before I split the PR in two. A version which was removed before your comment. Seems strange

**Comment by Arthur-Milchior** [comment]
Removed the last two commits, because I realized that actually, I was deleting a function which is currently unused but that I intend to use

**Comment by mikehardy** [comment]
will need a rebase since a nearby PR just went in but are standard refactors in general

**Comment by Arthur-Milchior** [comment]
That's the reason why it was originally a single (more complex) PR

**Comment by Arthur-Milchior** [comment]
Pushed again

**Comment by david-allison-1** [comment]
I'm happy, but I'd rather see #6362 go in.

**Comment by mikehardy** [comment]
This one has approval and CI has finished - merge it or should we focus on #6362 and get it done in batch? In this case, I vote for #6362 but I can do either, "implementor's choice" (Arthur) combined with "reviewers choice" (David)

**Comment by Arthur-Milchior** [comment]
Choice made for you

**Pull request closed without merging**
