### PR TITLE
Add insert cloze option to the paperclip menu

### PR DESCRIPTION
**Pull request by mooingcat**
Second attempt at adding the option to insert clozes. (First attempt [here](https://github.com/ankidroid/Anki-Android/pull/4598))

Fixing issue https://github.com/ankidroid/Anki-Android/issues/2520

### CODE REVIEW

**Comment by timrae** [comment]
Thanks for the second patch :)
I don't have time right now to test it, but how does it behave when the text box is empty, and when the text box has text but nothing is selected? Is that the desired behavior?

**Comment by timrae** [comment]
Also, is the same label "Insert cloze" used on Anki Desktop?

**Comment by mooingcat** [comment]
Thanks for the speedy feedback!

Just checked Anki Desktop, and there is a button with this symbol on it `[...]` with the text label "Cloze deletion" so I'll change it from "Insert cloze" to "Cloze deletion" to match.

When the text box is empty or if there is no selection, the button still inserts the pattern `{{c1::}}`. This is the same behaviour as in the desktop app and I think it makes sense.

The other difference is that in the desktop app, if there is a zero length selection, the cursor is moved to be after the second `:` , ready to type in the word which will be obscured, and if there is a selection of one or more characters then the cursor is moved to be after the second `}`. In the mobile app I've simply let android do what it likes with the cursor. Maybe this is something that could be polished up later on? It doesn't seem too annoying and I wouldn't want to put something moving the cursor in without trying it on a heap of different devices - it seems like the sort of thing which could do funny things on different phones.

A final difference is that the clozes are all marked as "c1" in this PR - in the desktop app that number increments with each highlight, and you can override that behaviour by holding the Alt key. Perhaps we could add this option (incrementing indices) in a later version - it's slightly more fiddly though and I thought it would be nice to get this simpler version out there first!

**Comment by Royal2000H** [comment]
Why was this commit reverted? Any plans to bring it back?

**Comment by mikehardy** [comment]
It wasn't reverted that I can see. It is in the 2.9 alpha series you can download from the releases page. Looks like it is not perfect yet per last comment on issue #2520 but should work when adding a new card

**Comment by Royal2000H** [comment]
Interesting. I was referring to: https://github.com/ankidroid/Anki-Android/commit/b0ec59f87a5e521ac38abd5e0a4deac2a74c4230

**Comment by mikehardy** [comment]
Ah! I missed that - if you look at where it was reverted, it was reverted on a hotfix branch in order to make sure the hotfix was as focused as possible. 

Looks like on mainline (next version, available on releases page) it is still there.

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1247

**Pull request merged**
