### PR TITLE
Done keyboard button has similar action to ok during deck creation

### PR DESCRIPTION
**Pull request by MinusMallard**
…ating new deck or renaming deck

## Purpose / Description
Pressing ImeAction button on keyboard during Deck Creation resulted in new line in TextField

## Fixes
Defining a Done button click listener from the keyboard inside the input callback of the AlertDialog fixed this issue

https://github.com/ankidroid/Anki-Android/assets/116078997/f5a8daf5-60fa-4d7b-aaf6-d7fda1095a66

## How Has This Been Tested?
This fix is tested locally on my android 14 device and api level 33 emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by MinusMallard** [comment]
"Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0." i think latest gradle version is 8.8 or 8.9 something than what is this exception

**Comment by lukstbit** [comment]
> "Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0." i think latest gradle version is 8.8 or 8.9 something than what is this exception, could use a little bit of help here

This is irrelevant for this PR.

There's a lint issue(you can see more info by clicking _Details_ for the _Code Quality Checks_ action bellow), a space after the comment //.

**Comment by david-allison** [comment]
Hi @MinusMallard, in future could you rebase + force push, rather than creating a new pull request.

This makes it easier for us to review, and keeps the review history intact

* Superseded by https://github.com/ankidroid/Anki-Android/pull/16704

**Comment by david-allison** [comment]
Really appreciate your time, we should get the PR in quickly. It's an expected learning curve for us all.

In this repo, we strongly encourage rebase + force push and strongly discourage merge commits.

Thanks again!

**Pull request closed without merging**
