### PR TITLE
Alternative Adaptive Icon

### PR DESCRIPTION
**Pull request by cydia2020**

### CODE REVIEW

**Comment by timrae** [comment]
screenshot_1526095867

**Comment by timrae** [comment]
It doesn't look that great IMHO

**Comment by lokesh-krishna** [comment]
This looks pretty decent honestly. Manages to retain all the elements of the original and should look better in the other shapes (square, rounded square, etc.).

I would personally like to see this merged but if there is a way to put this up to a vote then that would offer a better idea of what people think.

**Comment by cydia2020** [comment]
Rounded square

[画像]



________________________________

**Comment by cydia2020** [comment]
I reckon maybe we can increase the contrast a little and probably make the background brighter, I'll see if that looks better. I am personally not an icon designer obviously and I don't know how to design icons appearently, so よろしくお願いいたします。

**Comment by timrae** [comment]
Yeah I think either increasing the contrast, or removing the grey part of the original icon entirely for the round icon so that only the star is visible, and perhaps making it bigger and/or centered. It's hard to say without seeing it.

**Comment by lokesh-krishna** [comment]
Instead of removing the lines, could we have lines with better contrast against a black background for the background layer with the star in the foreground layer?

**Comment by cydia2020** [comment]
Yup I reckon so. I have to modify it later though as I'm a total amateur with Adobe Illustrator :D
________________________________

**Comment by lokesh-krishna** [comment]
Really appreciate the effort you're putting into this :)

**Comment by cydia2020** [comment]
default
How about this?

**Comment by lokesh-krishna** [comment]
Wow! This looks really good.  
If it isn't asking for too much, could you please also share a version with the light and dark tones swapped? I just have a feeling that it might look even better.

**Comment by cydia2020** [comment]
Thank you!

I'm just wondering do you mean flip the whole thing or just the background colour?

Since if only the background colour is flipped, the contrast would still be low and that is what we are attempting to avoid

**Comment by cydia2020** [comment]
This is what it'll look on a Pixel
screenshot_20180521-125853

**Comment by lokesh-krishna** [comment]
Are the lines a part of the foreground? I meant flipping the background along with the lines.  

This looks so good. Really hope this makes it in as soon as possible and that I can enjoy a squircle AnkiDroid icon!

**Comment by cydia2020** [comment]
The lines is a part of the background, as seen here
anki_background_alternative

**Comment by lokesh-krishna** [comment]
I see. Then flipping the top and bottom shouldn't be difficult, right? I really like the present icon but I just want everyone to take a look at what what that would look like and then make the final call.

**Comment by cydia2020** [comment]
One slight problem with flipping the colours is that the drop shadows would be casting upwards if we want it to show and it is pretty weird

This is with the shadows casting down, which makes the shadow barely seeable
anki_background_flipped

**Comment by lokesh-krishna** [comment]
Ah right, I forgot about the drop shadow. Go for this!  
😁

**Comment by cydia2020** [comment]
See #4854

**Comment by timrae** [comment]
Personally I'm not a fan of this new two-color background... Perhaps it could work if it were just the monolith changing color rather than the entire background...? I mean (very roughly) like this:

40288900-eaf225a4-5cf8-11e8-8826-382a528afa82

**Comment by timrae** [comment]
In any case, I'd like to see a few more design variations.
For example, one like above, one without this new two color division but with better contrast than the original submission so that the monolith is more clearly visible, and one with just the star (i.e. without the monolith at all).

**Comment by mikehardy** [comment]
For some reason I don't like this one at all. I feel like the icon just gets lost in the dark, it doesn't look like a tangible thing to me. That is a pure personal opinion - I guess I like well-defined objects? I totally get the attempt to play with the original elements though - this is a reasonable thing to try

**Comment by cydia2020** [comment]
TBH this one is my favourite 😂

Tho I've got no time for now since it's final exams of the year.

**Comment by mikehardy** [comment]
I like the direction with the 2 colors but where it wasn't on the whole background, I could see something like that working, with the star on top. We have a while until 2.9 goes anyway - lots of other features, so if you have any time after exams that might actually be the perfect time...

**Pull request closed without merging**
