### PR TITLE
fixed windows keyboard layout frame position

### LINKED ISSUE #13028: answer_options_layout is not showing above keyboard when Fullscreen Mode is on Hide the system bars
###### Reproduction Steps

1. Set Fullscreen mode as `Hide the system bars`
2. Add card ( Card type as Type in the answer )
3. Try to Type Answer

###### Expected Result
answer_options_layout is showing above the keyboard

###### Actual Result
answer_options_layout is not showing above the keyboard

###### Debug info
AnkiDroid Version = 2.16alpha92

Android Version = 12

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = e424f7a3-b51c-4d82-88fe-d716504aae0c

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

**Screen Recording**

https://user-images.githubusercontent.com/65113071/209403541-a829f7cf-3695-4397-b7ed-a3a2e6cca80f.mp4

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Pull Request template
Added fits window system to adjust the layout

## Purpose / Description
Fixes the issue arising due to the window system fir

## Fixes
Fixes #13028
Closes #13028

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
Test on google emulator and works fine
Screenshot_24

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by SanjaySargam** [comment]
LGTM🚀🚀

**Review by BrayanDSO — APPROVED** [review]
LGTM

**Review by lukstbit — APPROVED** [review]
OK.
As a side note, while this does make the input to be visible it also changes the UI by pushing the original buttons up. Fixing this would require refactoring the current UI to re implement how the layout handles being full screen. This is going to be more difficult so I'm ok with the change here as it does allow the input to be visible which I think is important.

**Comment by criticalAY** [comment]
> OK. As a side note, while this does make the input to be visible it also changes the UI by pushing the original buttons up. Fixing this would require refactoring the current UI to re implement how the layout handles being full screen. This is going to be more difficult so I'm ok with the change here as it does allow the input to be visible which I think is important.

Sure will take care of it

**Pull request merged**
