### PR TITLE
Update adaptive icon

### LINKED ISSUE #5110: Improved adaptive icon proposal
I haven't been too happy with the way the Icon looks right now, compared to other apps.

1 anki-old_small

Part of the problem is that the shape that's supposed to represent a flashcard requires an additional background, which is a neutral white right now.
So I took the previous SVG, cleaned it up (SVGs generated by Illustrator are quite the mess) and turned it into a square version without the shape, but maintaining all other elements exactly the way they were.

anki svg

As an adaptive icon, it looks like this.

2 anki-new_small

Because I thought some people would dislike the cut-off star, I reduced the star size and moved it a bit.

3 anki-star_small

That's fine, but unfortunately the square version, which would still be visible in many launchers and possibly Google Play, doesn't look as attractive anymore in my opinion, because the star seems too small now.

anki_star svg

The people I've asked so far actually seemed to prefer the first (unmodified) version with the cut-off star, because it makes the whole thing a bit more visually interesting and dynamic.

What do you think, does something like this have a chance of getting merged?

### PR DESCRIPTION
**Pull request by martindisch**
## Purpose / Description
Changes the app icon to the adaptive icon selected in the poll.

## How Has This Been Tested?
Ran it on device with visual inspection. We need to get this to beta users to make sure there's no device/launcher where it looks crappy.

## Fixes
#5110

### CODE REVIEW

**Comment by timrae** [comment]
I think you need to remove the reference to the round icon in the manifest as well...?

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/blob/de4f46c404027eef01d0ab739d1d1fe1678f41fb/AnkiDroid/src/main/AndroidManifest.xml#L83

**Comment by martindisch** [comment]
Nicely spotted. I just noticed on closer inspection that there's still a bunch of old (now unused) icons lying around in the mipmap directories. I'll clean this up.

**Comment by timrae** [comment]
Thank you!

**Comment by martindisch** [comment]
Apparently the round icons were [introduced in 7.1](https://developer.android.com/about/versions/nougat/android-7.1#circular-icons) before adaptive icons, so we should probably still keep it for backwards compatibility. At least the asset generator seems to think so, after all it generated new round icons, so what is referenced in the manifest is still up to date.

But I did remove the truly unused icons I found.

**Pull request merged**
