### PR TITLE
[Bug] Review activity Menu item icon get hidden after one or two time screen rotation

### LINKED ISSUE #10732: [Bug] Review activity Menu item icon get hidden after one or two time screen rotation
###### Reproduction Steps

1. Open Review activity and open menu item 
2. Rotation the screen one or two time

###### Expected Result
Menu item icons not get hidden

###### Actual Result

https://user-images.githubusercontent.com/65972015/162023469-65c8eb2b-8473-41eb-b914-f54cba41a328.mp4

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
## Purpose / Description
Menu item icon of Review activity get hidden after one or two time screen rotation

## Fixes
Fixes #10732

## Approach
We set the color of Menu icon when `onMenuOpened` function is called  is wrong 
In below image it is soon how `onCreateOptionsMenu` and `onMenuOpened`  function  is called 

Screenshot 2022-04-07 085209

 

## How Has This Been Tested?
Android Device :Redmi y3

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
:thinking: The code seems like it might be the right fix, but this part from the PR description is confusing for me:

> In below image it is soon how onCreateOptionsMenu and onMenuOpened function is called

I examined the below image and I see how they are called but I need an explanation of why what I am seeing demonstrates either the bug or the solution. Is there a race condition? Is it just that one is called every time and one is only called some of the time? Is it just that they are in the wrong order?

I am *guessing* that onCreateOptionsMenu is called every time and onMenuOpened is only called some of the time, but that's just a guess

An explanation of test results would help understand what I'm seeing in the test results then

**Comment by winstoncooke** [comment]
I'm a bit confused by what you're trying to solve here. Some clarification would be great!
When implementing your changes, I'm seeing that the top menu bar items are not appropriately colored white anymore.

My feeling is that this all has to do with a lack of onPrepareOptionsMenu(), however that's just a working theory.

**Comment by Prince-kushwaha** [comment]
@mikehardy  the cause of bug is that We set the color of Menu icons  in `onMenuOpened`   
Screenshot 2022-04-08 182554

**Comment by mikehardy** [comment]
@Prince-kushwaha a neat github trick: open the file in github web UI, then select the lines you want so they have yellow highlighting and click on the little three dot menu you should get a "copy permalink" menu item, paste that in here and you get this, which is 10x better than an image of code because it lets you click around the file immediately and explore:

https://github.com/ankidroid/Anki-Android/blob/908884f1986ae34803324ac281bfcfc4e2a64df2/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt#L621-L629

**Comment by mikehardy** [comment]
To your point though, I think I understand now. Here's what I think I understand, to see if I actually understand:
- icon color is set in onMenuOpened, and if we don't set it the icons are white-on-white so they are invisible
- rotating the screen means the whole Activity restarts and onCreate is called again (but this time with a saved bundle etc)

My question is, how come it works some times but not all the time? Is it a race condition / order of operations thing? As @winstoncooke mentioned it may be that call to onMenuOpened is missing, or maybe it's in the wrong spot, versus code needing to move.

However, I think the code moving might be the right fix in fact - technically the icon color should be part of menu preparation I think, if we are putting the items in the menu (including their icons) during menu preparation, then setting their color there does seem appropriate.

What do you think @winstoncooke ?

**Comment by winstoncooke** [comment]
@mikehardy I definitely agree with your thought process that the icon color should be part of menu preparation and agree with what @Prince-kushwaha has laid out.

What concerns me though is what I noticed when exploring #10683 after applying this change. See the following picture for the new result:

image

The action bar items are no longer white despite still being actionable. The lack of coloring makes it appear that they are not actionable however. Perhaps not a major issue, but it does worsen that issue nonetheless.

**Comment by mikehardy** [comment]
Ah I see. If the fix causes icons that *are* enabled to appear grey, then that is not something we can merge

**Comment by winstoncooke** [comment]
Unfortunately that is the case, but I think @Prince-kushwaha is onto something here. If an issue isn't already open, I'd suggest opening an issue for this and continue working to figure out the best way to implement it.

**Comment by Prince-kushwaha** [comment]
@mikehardy  i fixed the action bar item color issue
Screenshot_2022-04-09-10-40-13-734_com ichi2 anki 1

**Comment by winstoncooke** [comment]
https://user-images.githubusercontent.com/71997294/162592365-f8407b0f-8dc6-4ff4-b16c-2b7a236244fd.mp4

Your changes are working for me and look great related to #10732, but I'm still getting the uncolored icons in the menu bar. It must have something to do with the onMenuOpened function you've removed. Good work so far! You can follow the steps in my video above of rotating the device horizontally and then tapping on the deck to study it to see those menu icons appear. Try to figure out why icons in the action bar that appear when there's space for them are not getting colored properly.

**Pull request closed without merging**
