### PR TITLE
Keep card timer running in the background

### PR DESCRIPTION
**Pull request by aportley**
Issue #4808 - To maintain parity with Anki desktop and to accurately measure study time for workflows which include switching to other apps like dictionaries and writing pads, keep the card timer running through typical change-of-focus events. However, still make an effort to pause the timer when the screen is turned off or a call is received.

### CODE REVIEW

**Comment by timrae** [comment]
Would you be able to make an issue for whatever bug this is fixing explaining the steps to reproduce it?

**Comment by aportley** [comment]
@timrae - sorry, should have mentioned in the comment that this addresses issue #4808.

**Comment by timrae** [comment]
Sorry for the delay. I commented on #4808

**Comment by mikehardy** [comment]
This is waiting for feedback in the associated #4808

**Comment by hssm** [comment]
I'm not in favor of merging this change Letting the timer run would violate the principal of least surprise. A timer that records how long you spend in the app shouldn't keep recording when you aren't in the app. That's all there is to it.

Also:
- Pausing for *some* use cases and not others only adds to the unexpected behavior.
- Users who don't make a habit of returning to the deck screen will now *always* see a red, maxed-out timer when they go back to AnkiDroid. There has never been a requirement to "close" your review session and this would essentially add that requirement in.
- Some users may have bumped up their review time cap and now their "studied x cards in y minutes" might end up saying "studied x cards in 3 hours" and think there is a bug.

**Comment by mikehardy** [comment]
So we've got the feedback and both @timrae and @hssm are against merge, but there was at least [some recognition that the reasoning may be valid](https://github.com/ankidroid/Anki-Android/issues/4808#issuecomment-410129449), and clearly this waffles back and forth (with Anki Desktop, for one, keeping it running).

The remaining option for merge then would be if it was a preference toggle or similar. In the interest of being able to merge or close then, is having the original behavior as the default, and this pause-on-background behavior as an option an idea worth pursuing, or should this be closed?

**Comment by timrae** [comment]
I don't think we really want to maintain two sets of timers, so a preference is not an attractive option for me. At times like these I really wish we had a proper plugin framework :( 

I'm sorry @aportley, but in light of @hssm's comments I'm going to close this. In the long term I hope one day somebody will take the initiative to develop and maintain a kind of "reviewer plus" application that has all the bells and whistles we can't maintain in the main project.

**Comment by timrae** [comment]
(note that you can of course keep using this by running your own fork of AnkiDroid and periodically rebasing on top of master)

**Comment by kieranclancy** [comment]
Oops, made a comment on #4808 without seeing that this had been closed here.

For what it's worth, I think that following the principle of least surprise would be to do what Anki does on desktop - keep the timer running. The timer is not supposed to measure how much time is spent with the app in focus; it's supposed to measure how long it takes you to review the card from the time you are first shown it, and you might be using other applications as part of that process.

It's worth noting that by default, the timer is not shown and the maximal review time is 60 seconds, so very little would change for the average user except for those users who are using other apps as part of the review process, who would then get far more reliable statistics.

**Comment by ukanuk** [comment]
It's discouraging spending an hour reviewing, and Anki reporting I only reviewed for 10 minutes.

I propose a simpler option. Record the card start time, and calculate elapsed time based on that no matter what (whether X app is opened, phone call is received, screen turns off, etc).

This implementation would overestimate review time, but still be dramatically better than the 5x-10x underestimate reported by OP and that I experience.

**Pull request closed without merging**
