### PR TITLE
fix:#8166:Icon colors in the help dialog box to blue

### LINKED ISSUE #8166: Change in the icon colors in Help dialog box
**Is your feature request related to a problem? Please describe.**

The Help dialog box icons has a monotonous color of white and grey.Which makes the app dull and lifeless

**Describe the solution you'd like**

The colour of the icon adjacent to the item header can be made blue.So as it adds a little bit of joy and color to the UI 

**Describe alternatives you've considered**

All the adjacent icons in the dialog box near to the item header can be shifted to the theme color of the app which is blue and white

**Additional context**

WhatsApp Image 2021-03-11 at 01 48 44 (2)
WhatsApp Image 2021-03-11 at 01 48 44 (1)
WhatsApp Image 2021-03-11 at 01 48 44

By changing the icon colors the UI of the app becomes more user friendly

** Edit by Arthur**
Removed the description of the sections

### PR DESCRIPTION
**Pull request by haran2248**
## Purpose / Description
_Describe the problem or feature and motivation_

The montonous colors of grey icons are changed to the app theme of blue

## Fixes
Fixes #8166 

## Approach
_How does this change address the problem?_

The PR fixes the icon color in help dialog box.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

Device:Samsung SM-M205F

## Learning (optional, can help others)
_Describe the research stage_

https://stackoverflow.com/questions/32924986/change-fill-color-on-vector-asset-in-android-studio
_Links to blog posts, patterns, libraries or addons used to solve this problem_

WhatsApp Image 2021-03-11 at 23 23 59 (3)
WhatsApp Image 2021-03-11 at 23 23 59 (2)
WhatsApp Image 2021-03-11 at 23 23 59 (1)
WhatsApp Image 2021-03-11 at 23 23 59

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

**Comment by haran2248** [comment]
@Arthur-Milchior @mikehardy Please review this

**Comment by Arthur-Milchior** [comment]
Please do not ping us unless you know you need a specific reviewer. We get notification for new PR already.

**Comment by Arthur-Milchior** [comment]
I like the look.

May I please ask you whether you did use any accessibility tool. I would like to be sure the contrast satisfies the standard of accessibility, ithat is, that it's easy to read for users that do not have a good view.

If the goal is really to use the same value as one already used in ankidroid, then you may want to consider AnkiDroid/src/main/res/values/theme_.*.xml , where you can store value, you can store different value depending on light/dark, and most importantly if we want to change the value, we can change it in a single place.

**Comment by haran2248** [comment]
> Please do not ping us unless you know you need a specific reviewer. We get notification for new PR already.

Yes definitely

**Comment by haran2248** [comment]
> I like the look.
> 
> May I please ask you whether you did use any accessibility tool. I would like to be sure the contrast satisfies the standard of accessibility, ithat is, that it's easy to read for users that do not have a good view.
> 
> If the goal is really to use the same value as one already used in ankidroid, then you may want to consider AnkiDroid/src/main/res/values/theme_.*.xml , where you can store value, you can store different value depending on light/dark, and most importantly if we want to change the value, we can change it in a single place.

Actually I tried using the colors that were previously used in Ankidroid,But I wanted the icon to look slightly brighter compared to the toolbar,So I ended up using a different color,

I used the material design UI accessibility page.I will link that here.

https://material.io/design/usability/accessibility.html#writing

**Review by mikehardy — APPROVED** [review]
These look good to me visually
with regard to accessibility thank you for the link. That implies that they should be contrast of 3:1 I think, did the accessbility tool actually like the result (i.e., did it say the contrast ratio was acceptable?)

I'm guessing it did, I'm just curious

**Comment by haran2248** [comment]
> These look good to me visually
> with regard to accessibility thank you for the link. That implies that they should be contrast of 3:1 I think, did the accessbility tool actually like the result (i.e., did it say the contrast ratio was acceptable?)
> 
> I'm guessing it did, I'm just curious

Yeas it came close!Thank you so much!

**Comment by mikehardy** [comment]
> Yea it came close!Thank you so much!

I don't understand what this means :thinking: :-) - I am looking for a "yes the accessibility tool passed on this contrast ratio for the help icons" or "no, it did not"

Since that is a yes / no binary state, "it came close" reads to me like: "no, it did not  have a sufficient contrast ratio but 'it came close'"

**Comment by haran2248** [comment]
> > Yea it came close!Thank you so much!
> 
> I don't understand what this means 🤔 :-) - I am looking for a "yes the accessibility tool passed on this contrast ratio for the help icons" or "no, it did not"
> 
> Since that is a yes / no binary state, "it came close" reads to me like: "no, it did not have a sufficient contrast ratio but 'it came close'"

Oh I meant that it passed the contrast ratio,I got little confused the first time.The contrast ratio was 3:1

**Comment by mikehardy** [comment]
Excellent, will be in the next alpha, thanks @haran2248 !

**Comment by haran2248** [comment]
Thank you so much!!More PRS coming up!:)

**Pull request merged**
