### PR TITLE
Correct ProgressSender

### LINKED ISSUE #7391: Crash in 2.14alpha19 - ClassCastException in CollectionTask.onProgressUpdate
@Arthur-Milchior I think you touched this area in the last release?

https://youtu.be/aG_hzaufq0w

```

10-14 22:08:51.704: I/AnkiDroid(20277): deleteNotesWithWrongFieldCounts - completed successfully
10-14 22:08:51.707: E/libc(644): Access denied finding property "vendor.debug.egl.swapinterval"
10-14 22:08:51.708: I/AnkiDroid(20277): cursor size: 0
10-14 22:08:51.708: I/AnkiDroid(20277): deleteNotesWithWrongFieldCounts - completed successfully
10-14 22:08:51.708: D/SurfaceFlinger(644): duplicate layer name: changing com.ichi2.anki/com.ichi2.anki.DeckPicker to com.ichi2.anki/com.ichi2.anki.DeckPicker#2
10-14 22:08:51.710: E/libc(644): Access denied finding property "vendor.debug.egl.swapinterval"
10-14 22:08:51.711: I/AnkiDroid(20277): cursor size: 0
10-14 22:08:51.711: I/AnkiDroid(20277): deleteNotesWithWrongFieldCounts - completed successfully
10-14 22:08:51.713: I/AnkiDroid(20277): cursor size: 0
10-14 22:08:51.713: I/AnkiDroid(20277): deleteNotesWithWrongFieldCounts - completed successfully
10-14 22:08:51.714: I/GoogleInputMethod(3419): onFinishInput() : Dummy InputConnection bound
10-14 22:08:51.714: D/AndroidRuntime(20277): Shutting down VM
10-14 22:08:51.714: W/Robo(20277): Ignoring exception.
10-14 22:08:51.714: W/Robo(20277): --------- beginning of crash
10-14 22:08:51.714: E/AndroidRuntime(20277): FATAL EXCEPTION: main
10-14 22:08:51.714: E/AndroidRuntime(20277): Process: com.ichi2.anki, PID: 20277
10-14 22:08:51.714: E/AndroidRuntime(20277): java.lang.ClassCastException: java.lang.Object[] cannot be cast to com.ichi2.async.TaskData[]
10-14 22:08:51.714: E/AndroidRuntime(20277): 	at com.ichi2.async.CollectionTask.onProgressUpdate(CollectionTask.java:1)
10-14 22:08:51.714: E/AndroidRuntime(20277): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:715)
10-14 22:08:51.714: E/AndroidRuntime(20277): 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-14 22:08:51.714: E/AndroidRuntime(20277): 	at android.os.Looper.loop(Looper.java:193)
10-14 22:08:51.714: E/AndroidRuntime(20277): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
10-14 22:08:51.714: E/AndroidRuntime(20277): 	at java.lang.reflect.Method.invoke(Native Method)
10-14 22:08:51.714: E/AndroidRuntime(20277): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-14 22:08:51.714: E/AndroidRuntime(20277): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
It seems I failed something while introducing interface. No idea what exactly, but I got an exception stating that
Object[] can't be cast to TaskData[]

No idea what to do as regression test.

----

Fixes #7391

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Can you cast to array inside the method?

**Comment by Arthur-Milchior** [comment]
I can cast. However, I can't create an array of `T`. 

Anyway, taking `T param` as a function parameter was a bad idea in the first place, because it forces the sender to always send a value, even if the value is null. That the case in a PR I expect to make to add a progress bar to Check Media. In this case, "sendProgress" just means "increase the bar by one", so there is no need to send any data.

**Review by david-allison-1 — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
Thanks for getting this so quickly @Arthur-Milchior I appreciate it!

**Comment by Arthur-Milchior** [comment]
I actually made the correction before the bug report. I honestly still don't undertand why the bug is here in the first place. Why using an interface adds a casting bug when there was none before.

**Pull request merged**
