### PR TITLE
[GSoC] NF: Remove the old CSV importer implementation

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description
https://github.com/ankidroid/Anki-Android/pull/6773 started to implement a CSV importer, but now all that code/strings is unnecessary as we get the implementation from the new backend

## Approach
On the commits

## How Has This Been Tested?

CI

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
can you drop the commit with the string from the other files? We'll get those with the i18n sync, after pushing values/ out, when the sync comes back they'll be dropped automagically

**Comment by BrayanDSO** [comment]
Last time I tried it, locally and on CI, lint failed, let's see if this repeats

**Comment by mikehardy** [comment]
Ah, :hankey: I see what you mean. Well, it will be the same as the automated version and lint passes so bisect will work. I guess we have to go with the extra commit, sorry for the churn, I should have read more closely

**Review by david-allison — APPROVED** [review]
Great work!

**Review by mikehardy — APPROVED** [review]

**Comment by dae** [comment]
Please ignore me if this will resolve itself after a strings sync.

Seeing the following when building from main:

warn: removing resource com.ichi2.anki:string/csv_importer_error_exception without required default value.
warn: removing resource com.ichi2.anki:string/csv_importer_error_invalid_field_count without required default value.
warn: removing resource com.ichi2.anki:string/note_importer_empty_cards_found without required default value.
warn: removing resource com.ichi2.anki:string/note_importer_error_added_duplicate_first_field without required default value.
warn: removing resource com.ichi2.anki:string/note_importer_error_appeared_twice without required default value.
warn: removing resource com.ichi2.anki:string/note_importer_error_empty_first_field without required default value.
warn: removing resource com.ichi2.anki:string/note_importer_error_empty_notes without required default value.
warn: removing resource com.ichi2.anki:string/note_importer_error_first_field_matched without required default value.

**Comment by mikehardy** [comment]
Syncing them right now, nearly have CI green - that should clear them... #12180

**Pull request merged**
