### PR TITLE
Add support for selection args in the notes table in ContentProvider

### PR DESCRIPTION
**Pull request by timrae**
Add support for selection arguments that relate directly to the notes table when querying the db through the Content Provider. The existing `selection` argument that uses `col.findNotes(query)` with the Anki browser syntax can still be used, but if that argument is null then the `findNotes()` call is skipped, which reduces the number of queries to the db from 2 to 1, and should improve the speed by a decent amount.

This change allows searching for specific "csum" and "mid" values with a single sql query, which is useful for duplicate checking in the API. I've also implemented that, and in general brought the duplicate checking in-line with Anki Desktop (doesn't limit duplicates to a specific deck anymore - only the model).

### CODE REVIEW

**Comment by marcardar** [comment]
Please could you explain where decks fit in here?  What is the relationship between deck and note?  From what I understand, decks contain cards, and cards are derived from a model and a note.

Can a note be associated with multiple decks?  What happens if the client only wants to make note changes for a particular deck?

**Comment by timrae** [comment]
Yes, a note can have two cards in different decks. That isn't supported by the API but the user could manually move the card, or it could be temporarily in a filtered deck. Notes themselves don't have any deck associated with them.

The client shouldn't worry about which decks the user puts the cards after they're initially added. This is why your deck specific permission idea is not really feasible either.

**Comment by timrae** [comment]
A model specific permission would make a lot more sense, though I'm not sure what would be involved in implementing that

**Comment by marcardar** [comment]
Okay. Well it could just be a renaming: canUpdateAllNotesInDeck() and canUpdateNote(). Anyway, OT!

What's the expected behaviour for a client doing a large export of starred words, that have already been exported and potentially edited and reorganised into different decks by the user?  I would think such an export, should create a new note if the note no longer exists in that deck.

**Comment by marcardar** [comment]
It feels like there should be some kind of concept of Note Collections and permissions applied to that.

**Comment by timrae** [comment]
Due to the filtered deck possibility, I think the expected behavior has to be skipping duplicates even if they are in different decks. That was a bit of an oversight in the first API version.

Users that want to move cards out of control of the client app could just change the cards to a different model. Duplicate checking in all anki clients is non-deck-specific so it shouldn't be too surprising

**Comment by timrae** [comment]
Currently models are the closest thing to that.

**Comment by marcardar** [comment]
It's getting more and more mysterious!

> Currently models are the closest thing to that.

Okay, so the client should (must?) use a model specific to the client.

> Duplicate checking in all anki clients is non-deck-specific so it shouldn't be too surprising

So why do we pass deck id into `checkForDuplicates()`?  Is that what this PR is for - removing the deck id from such queries?

**Comment by marcardar** [comment]
> Due to the filtered deck possibility, I think the expected behavior has to be skipping duplicates even if they are in different decks.

I was thinking, one solution to update conflicts would be just to add them (i.e. add duplicates) and allow the user to delete as appropriate - or maybe add them to a new deck (with some "conflicts" naming).

This would not happen automatically - but as a result of the client invoking the method (on Result) to resolve conflicts.

**Comment by timrae** [comment]
Yes, it's most highly recommended to use a new model with a unique name such as the app package id, as in the docs. It's not currently a requirement, but not doing so will couple duplicate detection with other user content.

Removing the deck id and deprecating that method is one reason for this pull request. Speed of duplicate checking is another more important reason.

**Comment by timrae** [comment]
> I was thinking, one solution to update conflicts would be just to add them (i.e. add duplicates) and allow the user to delete as appropriate - or maybe add them to a new deck (with some "conflicts" naming).

Let's not do that!

**Comment by marcardar** [comment]
> Yes, it's most highly recommended to use a new model with a unique name such as the app package id, as in the docs.

It sounds like it should be a requirement. It's a shame getModelList() is there because that encourages reuse.

> Removing the deck id and deprecating that method is one reason for this pull request. Speed of duplicate checking is another more important reason.

I'd say the other way round. I never saw an issue with the speed of duplicate checking.  Have others complained?

Bearing in mind that we are updating notes regardless of deck, it seems essential that the deckId is not used in the duplicate check.

**Comment by marcardar** [comment]
> Let's not do that!

Why not?  It solves your problem of discouraging clients from overwriting note fields.

There has to be some way of solving the "Reading" scenario I mentioned earlier.

**Comment by marcardar** [comment]
Actually, this goes back to confusion regarding what duplicate means. The existing idea of duplicate would actually check using deck id, and ignore model id, no? You have a deck of cards, you want each card to have a different question, right?

Another type of duplicate checking would be checking that all fields are the same.

Terminology: Duplicate Note & Duplicate Card Question.

**Comment by timrae** [comment]
> Why not? It solves your problem of discouraging clients from overwriting note fields.

Not really, it just puts the burden on the user, in an extremely annoying way. Keep in mind that there isn't currently any way to delete notes in bulk with with AnkiDroid, it'd have to be done manually for each note.

> There has to be some way of solving the "Reading" scenario I mentioned earlier.

There is, just make a separate API call, for example you have `updateNoteFields()` in your PR

> The existing idea of duplicate would actually check using deck id, and ignore model id, no? 

No they are both used; it searches for `deck:DECK_NAME note:MODEL_NAME`

**Comment by marcardar** [comment]
> No they are both used; it searches for deck:DECK_NAME note:MODEL_NAME

Yes, but I'm saying there is value in the check being independent of model id because you don't want two cards with the same question in the same deck.

> Keep in mind that there isn't currently any way to delete notes in bulk with with AnkiDroid, it'd have to be done manually for each note.

Earlier, you said there is no real problem if the client inserts lots of notes (because it can easily be done in Anki Desktop). Why not use the same argument here?

> There is, just make a separate API call, for example you have updateNoteFields() in your PR

The problem here is you are trying to discourage updating fields, by making things awkward for the client, but I don't think that works. Since the client is updating their own notes, and they have been granted permission (by the user) to update those notes, this is something between the client and the user (not AnkiDroid). If the client writes over the user's edits, then the user complains to the client.

**Comment by timrae** [comment]
> Yes, but I'm saying there is value in the check being independent of model id because you don't want two cards with the same question in the same deck.

Yeah, I know what you're saying, but it's going against the grain of how Anki works so I don't support proceeding with this. I imagine Damien will do something to address this issue in a future version of Anki.

> Earlier, you said there is no real problem if the client inserts lots of notes (because it can easily be done in Anki Desktop). Why not use the same argument here?

There I was talking about the case where the developer screws up and does something stupid. A one-time bulk delete followed by probable uninstall of the offending app is relatively easy. Building a system into the API that requires the user to regular do bulk deletions is a completely different story.

> The problem here is you are trying to discourage updating fields, by making things awkward for the client, but I don't think that works. Since the client is updating their own notes, and they have been granted permission (by the user) to update those notes, this is something between the client and the user (not AnkiDroid). If the client writes over the user's edits, then the user complains to the client.

I guess we'll just have to agree to disagree on this particular point. I strongly believe that separating inserting and updating of notes into separate API calls is the correct way to design the API, and I don't think it's going to be that awkward.

**Comment by timrae** [comment]
I've pushed a new commit that has rewritten `addNotes()` in the way that I imagine it working. It's just a prototype idea and may still have some bugs, but would you please be able to test the performance in the same way that you tested your last PR?

**Comment by marcardar** [comment]
> I've pushed a new commit

The old notes map is much more efficient - why not use it?

**Comment by marcardar** [comment]
> Building a system into the API that requires the user to regularly do bulk deletions is a completely different story.

This is where I think we are imagining different things. My bulk exports happen very rarely. For most users, they would be a one-time operation, because from then on, everything would be incremental through addNewNote and updateNote.  It's okay, we don't need to discuss this part any more.

I'm thinking about the new addNotes() method. It just seems a shame to get all the duplicate note information and then only return the id to the caller. This lack of information would increase the chance the caller just calling update anyway. At least if you give some kind of diff information, the client would think about whether it's worth doing something about it.

Having some monolothic result array doesn't sound very nice either. How about a callback:

onDuplicateNote(int index, long noteId, String[] existingFields);

**Comment by timrae** [comment]
> The old notes map is much more efficient - why not use it?

Would you be able to please define "much more" a bit better using some numbers? This way involves a lot less code to maintain so there is a trade-off IMO.

**Comment by marcardar** [comment]
> Would you be able to please define "much more" a bit better using some numbers?

The purpose of addNotes is for large numbers of notes. So, in my 2000 note example, you've increased the number of provider calls from about 2 to 2002.  It's just bad design IMHO. I could make some calculations, but it will take time to get the code straight first.

For small numbers of notes, the client might as well just call the single note methods.

The other benefit missing is checking whether the notes are identical. If the note is identical, then we don't need tell the client about it.

**Comment by marcardar** [comment]
Don't you also find the "duplicate" naming confusing?

For a model id and fields array, there are three states: NEW, UPDATE, SKIP

The last two are "duplicates" in the existing use of the terminology.

**Comment by marcardar** [comment]
I just pushed a new `addNotes()` to #4122

**Comment by timrae** [comment]
> In my 2000 note example, you've increased the number of provider calls from about 2 to 2002.

Well I guess reads are a lot faster than writes, but anyway I've pushed a new commit that has updated it to do it all in one call. This should be faster than even your approach, since we don't pull any unnecessary data from the database.

I also added the missing API calls for getting and setting the tags.

**Comment by timrae** [comment]
It's still missing a few things from your PR, I'll go over them both a bit later on

**Comment by timrae** [comment]
> Don't you also find the "duplicate" naming confusing?

> For a model id and fields array, there are three states: NEW, UPDATE, SKIP

> The last two are "duplicates" in the existing use of the terminology.

That's not really how I see it, there is only "new" or "skip" when adding notes. Update is a completely separate operation done via the get and set methods.

**Comment by marcardar** [comment]
> That's not really how I see it, there is only "new" or "skip" when adding notes. Update is a completely separate operation done via the get and set methods.

I'm not talking about addNotes(). I'm talking about the general situation when the client wants to add notes.

**Comment by marcardar** [comment]
I don't understand what you are trying to solve by introducing this CSUM. Is it purely for efficiency? It looks messy to me, so you need to have data to back it up.  With one of my recent versions of addNotes() it took less than 200ms (and one provider call) to add 2000 notes that already exist (including all the duplicate checking). CSUM seems to complicate things.  If it is deemed important enough to use, then I guess it could be incorporated into my notes map building.

**Comment by marcardar** [comment]
BTW - I think it is already agreed that `addNotes()` does not do any updates.

**Comment by marcardar** [comment]
I just pushed another commit to #4122 which only returns the fields (and tags) that changed, in the callback.

**Comment by marcardar** [comment]
On important point to note is that if the client edits the question field, then it will not match the original note.

**Comment by timrae** [comment]
> I don't understand what you are trying to solve by introducing this CSUM. Is it purely for efficiency?

Yeah, introducing CSUM is for efficiency; all the Anki clients use CSUM for duplicate checking, that's why there is a TODO comment about it in develop.

Say you have 10,000 existing notes for your model, and you then call addNotes() with 100 new notes. In order to find the notes that require skipping, the current code in the develop branch will access the provider and call `col.findNotes("deck:DECK_NAME note:MODEL_NAME")` which will do an SQL query that will give a list of 10,000 note IDs. It'll then do a second SQL query using all of those IDs and return a cursor with 10,000 rows and 11 columns.

In this PR the first query will be skipped, so already a 2x improvement regardless of the number of new notes. Additionally, in this hypothetical example it'll only return a cursor with 100 rows and 2 columns which, will be much much faster.

>  If it is deemed important enough to use, then I guess it could be incorporated into my notes map building.

Actually I'm trying to cut out that whole note map building code. I see a high value in having a near optimal efficiency duplicate checker as part of the API, and once we have that, the map building code is unnecessary for addNotes(). The extra code in the Utils class is 95% just copy and pasted from Libanki utils, so it's already tested and familiar to us, and so easy to update. Conversely, the map building code is all new, untested, and only locally useful to that method (as opposed to more generally useful as an API method).

> I'm not talking about addNotes(). I'm talking about the general situation when the client wants to add notes.

To be honest I'm not a big fan of your callback idea in the addNotes() method. I want to completely separate these tasks. 

Most API users will have a list of marked words in their dictionary. The user will periodically add extra words, and then re-share the list with AnkiDroid to get the new words into AnkiDroid. The app developer will call `addNotes()` each time, the new words will be added (and old ones skipped), done. Problem solved.

If the developers really want to go further and update the fields or tags of notes they can do it like this:

``` java
String[][] fieldsArray;  // retrieved by your app
String[] tagsArray;     //  retrieved by your app
Long[] newIds = api.addNotes(mid, did, fieldsArray, tagsArray);
for (int i = 0; i < fieldsArray.length; i++) {
    if (ids[i] == null) {
        Long existingId = api.findExistingNoteId(mid, tagsArray[i]);
        String [] oldFields = api.getFields(existingId);
        String [] oldTags = api.getTags(existingId);
        // Do some inspection of oldFields, oldTags, figure out what needs to be updated, maybe the ask user for input, whatever
        api.setFields(existingId, newFields);
        api.setTags(existingId, newTags);
    }
}
```

It's straightforward and pretty obvious, and gives them a chance to ask for user input if needed. Additionally, it allows us to protect setFields() and setTags() with an extra permission if needed so that the user is further protected.

**Comment by marcardar** [comment]
> It's straightforward and pretty obvious, and gives them a chance to ask for user input if needed. Additionally, it allows us to protect setFields() and setTags() with an extra permission if needed so that the user is further protected.

I think we have already agreed that updates will be done through update() methods and not addNotes().

> The app developer will call addNotes() each time, the new words will be added (and old ones skipped), done.

Where does this api-usage assumption come from?  It's not how I use the API, as I mentioned earlier.

> it'll only return a cursor with 100 rows and 2 columns which, will be much much faster.

I don't have an argument against returning 100 rows instead of 10,000. But I don't see an argument for returning 2 columns instead of all those needed to check for Note changes. Those need to be returned anyway, and it seems silly to force the client to do it in separate API calls, especially when your rationale is efficiency.

> The extra code in the Utils class is 95% just copy and pasted from Libanki utils, so it's already tested and familiar to us, and so easy to update.

Copy-pasted code can cause other problems. Inevitably it will get out of sync and then that will cause confusion. I don't believe that's a strong argument for such a small amount of code.  The map building code can be understood easily by any developer in less than a  minute.

You know, we might not be far off an agreement on how to check for existing duplicates.  I think your existing long ids call be modified to add the extra fields and tags columns. Build the Note object as you go along. If you insist on not using a map, then you could just make those 10,000 provider calls like you had earlier.  It doesn't make sense to me, but, at the end of the day, it doesn't have a huge impact on implementation and also zero impact on the Api.

**Comment by timrae** [comment]
OK, I finally see what you're trying to say. We should return an array of some Objects instead of an array of Longs and then we can avoid these 3 calls in the example code I posted?

```
        Long existingId = api.findExistingNoteId(mid, tagsArray[i]);
        String [] oldFields = api.getFields(existingId);
        String [] oldTags = api.getTags(existingId);
```

**Comment by marcardar** [comment]
> We should return an array of some Objects instead of an array of Longs and then we can avoid these 3 calls in the example code I posted?

You should just use the Note class. It's much clearer IMO. I still think it's worth putting them in a Map too.

I've added a [AddNotesHelper](https://github.com/marcardar/Anki-Android/commit/68becebc0334c637a7c7539a9c4f812c16a6dbdf) class to give an idea of what I'm talking about with regards to the other problem: how to tell the client about update conflicts.

**Comment by marcardar** [comment]
In the latest [commit](https://github.com/marcardar/Anki-Android/commit/7ae90517a162d71b14ecd3bc50cc08deea01298e), I've isolated the method (`findPreExistingNote()`) to find whether the key already exists (so it will be easy to change between map or individual provider calls)

**Comment by timrae** [comment]
I'm working on some edits for this PR to discuss more; I think it's more efficient for me to change it here rather than going through and reviewing your PR.

**Comment by marcardar** [comment]
No worries - I'm only pointing out the AddNotesHelper class because that might be interesting to your PR.  Will you be adding an addNotes() or just the supporting code around it?

**Comment by timrae** [comment]
`addNotes()` has been in this PR from the start... AFAIK this does everything needed except handle the permissions changes, logging, and it might be missing some other checks for edge cases and nulls.

I think the AddNotesHelper class is a bit too much, I'd prefer something lightweight like a Bundle which is what I've used in the latest commit. Please check it out and let me know what you think.

**Comment by marcardar** [comment]
> addNotes() has been in this PR from the start...

Ah yes - I'm just not sure we need it. The more I look at the AddNotesHelper the more I like it. It solves so many problems and also doesn't require exposing a Note class or Bundle.

How about you change the existing addNotes() to use your new csum code (instead of the map), but still only return an int?

**Comment by marcardar** [comment]
It might be that I could just use the AddNotesHelper in my own code, but for that I would want to have access to an addNotes() that ignores duplicate checking (because my helper class takes care of that).

**Comment by marcardar** [comment]
I think the whole thing about how to give feedback to the client is something better addressed in my PR. You could just leave the addNotes() return value as int, merge the PR, and then we can thrash out the addNotes() in my PR.

**Comment by timrae** [comment]
I don't really want to spend too much more time thrashing this out to be honest. 

`addNotes()` needs to return some indicator of whether or not it added or skipped IMO, that's relatively important information. The code is now using a custom object instead of a Bundle, how about we merge it how it is and you can show a few different approaches in your PR?

**Comment by timrae** [comment]
(I don't mind if you make significant changes as long as the line count doesn't go up too much and the add / update methods of the API don't get coupled together)

**Comment by marcardar** [comment]
If you really don't like the helper class, then you might want to consider something like:

NoteInfo[] readNotes(long mid, long did, String[][] fieldsArr)
int addNewNotes(long mid, long did, String[][] fieldsArr, Set<String>[] tagsArr)

and let the client do all the work of separating out the new notes into the addNewNotes() call and the others into the updateNote() call. It's less safe but it keeps the Api simple.

**Comment by marcardar** [comment]
> (I don't mind if you make significant changes as long as the line count doesn't go up too much and the add / update methods of the API don't get coupled together)

fine :)

**Comment by timrae** [comment]
or the number of public API methods ;)

**Comment by marcardar** [comment]
I'll get to work as soon as you merge the PR :)

**Comment by timrae** [comment]
Thanks. The changes to the ContentProvider should be solid but I haven't tested the other code in the API yet, sorry, there might be some bugs there.

**Pull request merged**
