### PR TITLE
Include jQuery 3.5.1

### LINKED ISSUE #7920: AnkiDroid does not bundle JQuery, while AnkiWeb/AnkiMobile do
###### Reproduction Steps

1. Ankidroid未自带JQuery.js，PC端Anki中有自带JQuery.js
2. Ankidroid中无法手动引入外部js文件，使用如下语法无效： <script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
3. Ankidroid只能使用最最原生的js语法，想实现想要的页面效果或功能非常麻烦，希望能手动引入外部js文件实现

###### Expected Result
1.希望Ankidroid中能自带JQuery.js语法
2.希望 Ankidroid中可以实现手动引入外部js文件，能使用更多的语法实现更多的功能

###### Actual Result

Ankidroid中无法手动引入外部js文件，使用如下语法无效： <script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>

###### Debug info

AnkiDroid Version = 2.15alpha4

Android Version = 10

ACRA UUID = cfa90515-e628-4e81-b5a1-cff6c2301bb4

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by hgiesel**
## Purpose / Description
Include jQuery 3.5.1 in the card template.

## Fixes
Fixes #7920

## How Has This Been Tested?
I tested in the reviewer, and the chrome inspector.

## Learning (optional, can help others)
There is a slim and a normal build of jQuery. This includes the normal build, as it also on AnkiWeb, and AnkiDesktop. The difference between both of them is 200kB, where normal has 970kB, and slim has 768kB.
For the performance in the webview, it is rather negligible though. Just booting MathJax (not executing it), already takes ten times as long as loading jQuery.

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
This looks great - my only hesitation is that keeping track of dependencies and updating them is one of our most time-consuming tasks over the long term

The things I need to know as a maintainer are 
1. "what version am I on now?"
2. "what version should I be on ?"
3. "what is the most recent stable version?"

Those are the questions I am always asking about our dependencies, and we don't have a package.json / yarn.lock or package-lock.json / build.gradle to track them here, so I need something (anything) else

I'm thinking for each:

1. change the name to jquery-3.5.1.min.js so I know what we are actually on
2. add a README.txt to AnkiDroid/src/main/assets with a link to upstream indicating the version they are on (I looked for this but couldn't find anything? Only `@types/jquery` in the yarn.lock 🤔 )
3.include in that README.txt this link so I can just click it to see current https://github.com/jquery/jquery/releases

This seems minor but I'm not joking, maintaining the whole package as an up to date set of dependencies and troubleshooting inter-package issues / dependency issues is a huge amount of my time so I really need these :-)

Small side note, in a PR if you use `Fixes #NNNN` where NNNN is the issue number allows github to automatically cross-link a PR and an issue and auto-close the issue on merge - I edited this PR so you could see it

**Comment by mikehardy** [comment]
Note the README file I'm requesting in the assets could/should have an entry for all the other vendored assets we include, for the same reason, if you have a little extra time to add entries for the rest

**Comment by dae** [comment]
Now that I've merged in Henrik's PR, it's listed in packages.json/yarn.lock:

https://github.com/ankitects/anki/pull/856/files

**Comment by hgiesel** [comment]
I've added a README containing the currently installed versions, and where to find those versions in AnkiDesktop.
I would not recommend renaming the jQuery source files. In the case of jQuery, the version name is actually written inside of the file.

**Review by mikehardy — APPROVED** [review]
That's a good reason not to change the name! 

I'm jealous of the upstream build process for these assets, though I don't speak Bazel as a build language. Encodes the dependencies nicely. At any rate having the pointer to the upstream where they are encoded will help a lot for when I do dependency update sweeps, thanks!

**Pull request merged**
