### PR TITLE
Added contract for null -> null and non-null to non-null.

### PR DESCRIPTION
**Pull request by criticalAY**
## Pull Request template
TODO : Add contract for null -> null and non-null to non-null.

## Purpose / Description
todo

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
Locally tested on google emulator and compiled successfully 
Debug : 
AnkiDroid Version = 2.16alpha91

Android Version = 12

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_x86_64 Build/SE1A.220630.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = 45057c15-5541-46b3-8da6-3dadf1cea65c

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by lukstbit — CHANGES_REQUESTED** [review]
This should be closed as it doesn't address the TODO:

- that annotation doesn't work with kotlin code(see https://youtrack.jetbrains.com/issue/KT-22905/Support-org.jetbrains.annotations.Contract)
- kotlin has its own contract system but it's currently experimental(see https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.contracts/)
- the implementation is not correct anyway as it was declared for a method with two parameters(_ and null) when the method has only one parameter.

**Comment by criticalAY** [comment]
Even if I remove the extra param it would still be off no use. Should I update the TODO to be only done after the annotation is out of the experimental phase?

**Comment by lukstbit** [comment]
>  Should I update the TODO to be only done after the annotation is out of the experimental phase?

Much better than closing. Something like:

_// TODO: Add contract for null -> null and non-null to non-null when kotlin contracts become stable_

**Comment by criticalAY** [comment]
> // TODO: Add contract for null -> null and non-null to non-null when kotlin contracts become stable

ok done

**Review by lukstbit — APPROVED** [review]
Much better

**Pull request merged**
