### PR TITLE
Add Border to 'Mark' icon in topbar

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

Reported in https://github.com/ankidroid/Anki-Android/issues/5806#issuecomment-616482609

>  is it possible to change the color of the star when the button is hidden (i.e. only in the menu)? For me, it is rendering white on a gray background, which makes it difficult to see.

This is visible in the 'Plain Theme'

Before: 
image

## Approach
Add a border to the icon used in the topbar

After:
image

image

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
@lervag, tagging to confirm the fix is acceptable for you.

**Comment by lervag** [comment]
Thanks, yes, this makes it much better.

Out of curiosity, is it possible/easy to customize the colors of the elements in this top bar at user level?

**Comment by david-allison-1** [comment]
> Thanks, yes, this makes it much better.
> 
> Out of curiosity, is it possible/easy to customize the colors of the elements in this top bar at user level?

I'm still new to the platform and the visual side of Android isn't my area of expertise. I don't think so (outside Android theming).

**Comment by lervag** [comment]
Ok, thanks for the quick reply.

**Comment by mikehardy** [comment]
adding the border is actually nicer than my (in comment elsewhere) suggestion of gold. This looks classy, works for me

**Comment by mikehardy** [comment]
This went out with 2.10alpha72 - available as soon as google is done processing it

**Pull request merged**
