### PR TITLE
Added keyboard shortcut (Ctrl+F) to search in the card browser

### PR DESCRIPTION
**Pull request by Chandra-Mauli-Sharma**
## Purpose / Description
Added Ctrl+F shortcut to open search view when an external keyboard is attached to the device specified in the case of tablets.

## Fixes
It was a feature request  #13566.

## Approach
I used the function `fun onKeyUp(keyCode: Int, event: KeyEvent?)`.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
https://developer.android.com/develop/ui/views/touch-and-input/keyboard-input/commands

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Chandra-Mauli-Sharma** [comment]
@lukstbit can you review this PR?

**Comment by Chandra-Mauli-Sharma** [comment]
@david-allison can you review this PR?

**Comment by lukstbit** [comment]
@Chandra-Mauli-Sharma Please don't ping reviewers, your PR will be reviewed as time permits and based on our internal priorities(and there are things with higher priorities right now).

Quickly looking at your PR I see two issues:

- you didn't fill in one of the sections of the PR template, _How Has This Been Tested?_ Did you test the changes? How did you test the changes? This is important because I don't use an external keyboard and I wasn't able to test any of the keyboard shortcuts
- in the code you use `onKeyUp()` but the CardBrowser already implements(along with some keyboard shortcuts) the `onKeyDown()`. So why was `onKeyUp` necessary?

**Comment by Chandra-Mauli-Sharma** [comment]
Sorry, I will take care of this next time. I will open a new PR with the functionality in the `onKeyDown()` function.

**Comment by david-allison** [comment]
> Sorry, I will take care of this next time. I will open a new PR with the functionality in the `onKeyDown()` function.

Please rebase the PR in future, it's best to keep review comments in the same place

**Comment by Chandra-Mauli-Sharma** [comment]
Sorry, I will take care about this in future.

**Pull request closed without merging**
