### PR TITLE
Fix flaky test: limitAppliedAfterReview

### LINKED ISSUE #7565: CI Failure: limitAppliedAfterReview
```
com.ichi2.anki.DeckPickerTest > limitAppliedAfterReview FAILED
    java.lang.NullPointerException
        at com.ichi2.anki.DeckPickerTest.lambda$limitAppliedAfterReview$6(DeckPickerTest.java:176)
        at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:660)
        at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
        at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:670)
        at com.ichi2.anki.DeckPickerTest.limitAppliedAfterReview(DeckPickerTest.java:174)
```

### PR DESCRIPTION
**Pull request by david-allison-1**
Hopefully fixes #7565

### CODE REVIEW

**Comment by david-allison-1** [comment]
Personal CI flagged that #7389 needs fixing

**Comment by david-allison-1** [comment]
That's a new one:

```
com.ichi2.utils.LanguageUtilsTest > localeTwoLetterCodeResolves FAILED
    java.lang.RuntimeException: Method setLocale in android.content.res.Configuration not mocked. See http://g.co/androidstudio/not-mocked for details.
        at android.content.res.Configuration.setLocale(Configuration.java)
        at org.robolectric.android.DeviceConfig.setLocale(DeviceConfig.java:403)
        at org.robolectric.android.DeviceConfig.applyToConfiguration(DeviceConfig.java:165)
        at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:47)
        at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:151)
        at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
com.ichi2.utils.LanguageUtilsTest > localeThreeLetterCodeResolves FAILED
    java.lang.RuntimeException: Method setLocale in android.content.res.Configuration not mocked. See http://g.co/androidstudio/not-mocked for details.
        at android.content.res.Configuration.setLocale(Configuration.java)
        at org.robolectric.android.DeviceConfig.setLocale(DeviceConfig.java:403)
        at org.robolectric.android.DeviceConfig.applyToConfiguration(DeviceConfig.java:165)
        at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:47)
        at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:151)
        at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
com.ichi2.utils.LanguageUtilsTest > testNoLanguageIsRemoved FAILED
    java.lang.NoSuchFieldError: noncompatWidthPixels
        at org.robolectric.android.DeviceConfig.setDimensions(DeviceConfig.java:249)
        at org.robolectric.android.DeviceConfig.applyToConfiguration(DeviceConfig.java:201)
        at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:47)
        at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:151)
        at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
com.ichi2.utils.LanguageUtilsTest > testCurrentLanguagesHaveNotChanged FAILED
    java.lang.NoSuchFieldError: noncompatWidthPixels
        at org.robolectric.android.DeviceConfig.setDimensions(DeviceConfig.java:249)
        at org.robolectric.android.DeviceConfig.applyToConfiguration(DeviceConfig.java:201)
        at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:47)
        at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:151)
        at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
com.ichi2.utils.LanguageUtilsTest > localeTwoLetterRegionalVariantResolves FAILED
    java.lang.RuntimeException: Method setLocale in android.content.res.Configuration not mocked. See http://g.co/androidstudio/not-mocked for details.
        at android.content.res.Configuration.setLocale(Configuration.java)
        at org.robolectric.android.DeviceConfig.setLocale(DeviceConfig.java:403)
        at org.robolectric.android.DeviceConfig.applyToConfiguration(DeviceConfig.java:165)
        at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:47)
        at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:151)
        at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
com.ichi2.utils.LanguageUtilsTest > localeThreeLetterRegionalVariantResolves FAILED
    java.lang.RuntimeException: Method setLocale in android.content.res.Configuration not mocked. See http://g.co/androidstudio/not-mocked for details.
        at android.content.res.Configuration.setLocale(Configuration.java)
        at org.robolectric.android.DeviceConfig.setLocale(DeviceConfig.java:403)
        at org.robolectric.android.DeviceConfig.applyToConfiguration(DeviceConfig.java:165)
        at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:47)
        at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:151)
        at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by mikehardy** [comment]
That failure on setLocales was - I think - the leading indicator that the robolectric APIs weren't coming in correctly and was related to the gradle properties change where we pinned robolectric so it didn't need to go above java8 / API28 ? Or something? Ugh, didn't make an anki card out of it

**Comment by david-allison-1** [comment]
@mikehardy Anything that I can do about this failure - should fix our build issues in this goes in.

**Comment by mikehardy** [comment]
@david-allison-1 just need a clean CI run I think - that was what gave me pause before. Didn't want to see the robolectric setlocale stuff propagate to main branch :)

**Comment by mikehardy** [comment]
I don't know what's up with this PR run through CI but the setLocale thing is persistent on Unix only. I wonder if it would work on a completely different PR? (same commits). I think I have cleared caches at least once but that's also an option of course.

**Comment by david-allison-1** [comment]
I cleared cache - will make a new PR

**Pull request closed without merging**
