### PR TITLE
More new schema fixes

### LINKED ISSUE #12054: [Bug] Undo Delete crash with v16 schema
###### Reproduction Steps
1. Use v3 scheduler
2. Bury a note
3. Delete a note
4. Back to Deck picker
5. Tap the three dots menu - Undo Delete note

###### Expected Result
1. The note deletion is undone and a toast/snackbar appears.
2. Undo Bury is possible.

###### Actual Result
1. The note deletion is undone but no feedback.
2. Undo Delete note is offered again. The app crashes If Undo Delete note is used for the second time.

###### Debug info
AnkiDroid Version = 2.16alpha78

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36

ACRA UUID = 5166056d-62ff-4898-beed-7183997fc68e

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #12155: v3 scheduler sometimes crashes after editing
I'm having a similar crashing bug on 2.16a80 with V3 scheduler.

When reviewing, I sometimes want to edit a note. After an edition triggered from reviewing the back card (start editing from the front card doesn't seem to trigger this problem), if I choose to answer "good" for this card, it seems to crashes. I don't know how to extract and review the crash log but they got uploaded.

AnkiDroid Version = 2.16alpha80

Android Version = 13

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6a Build/TP1A.220624.021.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 9c32ddea-ccc7-42cb-9016-62a03202d3d3

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

_Originally posted by @escape0707 in https://github.com/ankidroid/Anki-Android/issues/12054#issuecomment-1225104401_

### PR DESCRIPTION
**Pull request by dae**
Closes #12054
Probably closes #12155

### CODE REVIEW

**Comment by david-allison** [comment]
This likely conflicts with https://github.com/ankidroid/Anki-Android/pull/12151, could it be rebased onto `develop` and could the build errors be fixed

**Comment by mikehardy** [comment]
I did a `gh pr checkout 12157` locally, rebased, fixed the obvious issue (just remove `.requireNonNulls()` from fields), and did a `git push --force-with-lease` 

I think it's ready for review again, I'm hoping to look at it myself but would love a look from anyone, would like to get this through quickly to maintain velocity on new backend

**Review by mikehardy — APPROVED** [review]
Would be a bit easier to review if the "Also:" items were separate commits but this all looks good to me and I'm to argue too strongly given the speed of fixes :smile: 

Hopefully CI + another reviewer agrees.

**Comment by mikehardy** [comment]
I hate to rush things but I want to do another alpha to fix a crash bug, and this *is* the crash bug fix, going to merge

**Comment by escape0707** [comment]
I wish for an alpha build to test the fix out.

**Comment by mikehardy** [comment]
@escape0707 yep - working on it! Should be a new alpha shortly (that is: in about an hour, you can "watch" the repo for new releases to get a github notification of the same

**Pull request merged**
