### PR TITLE
[Feature] Implemented Shortcut option for Review Cards, Add Note, Browser Card

### LINKED ISSUE #8648: Shortcut option without opening app
## Feature
Implement ShortcutInfo for common action like opening CardBrowser,Statistics, Settings,And Note Editor

### PR DESCRIPTION
**Pull request by Akshay0701**
fixes #8648

### CODE REVIEW

**Comment by Akshay0701** [comment]
>  java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
>         at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
>         at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
>         at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
>         at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:834)
> 
>         Caused by:
>         java.lang.NullPointerException
>             at com.ichi2.libanki.sched.LrnCardQueue.getFirstDue(LrnCardQueue.java:25)
>             at com.ichi2.libanki.sched.Sched._getLrnCard(Sched.java:392)
>             at com.ichi2.libanki.sched.Sched._getCard(Sched.java:263)
>             at com.ichi2.libanki.sched.SchedV2.getCard(SchedV2.java:176)
>             at com.ichi2.libanki.sched.SchedTest.test_ordcycleV1(SchedTest.java:1075)

**Comment by david-allison-1** [comment]
Kicked off the test again, likely just a flaky test.

Let me know if it fails again and I'll look into it

**Review by mikehardy — APPROVED** [review]
That's cool I think I'd use add note a lot

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!

**Comment by Arthur-Milchior** [comment]
Out of curiosity, @Akshay0701 if you still read notification. Would you recall why you used dynamic and not static shortcuts?

**Comment by Akshay0701** [comment]
we can also use static, but I used dynamic because it can be created, updated, and removed programmatically at runtime, allowing the application to adapt to the user's current context.

**Pull request merged**
