### PR TITLE
Remove simple interface

### PR DESCRIPTION
**Pull request by hssm**
Here's the removal of the simple interface. I may have overestimated the amount of code this was taking up, but it's still a lot nicer now.

I have not removed the orphaned string resouces left over by this commit. I was planning on removing all unused strings in another commit later.

### CODE REVIEW

**Comment by timrae** [comment]
I noticed yesterday that you're one of the only people to have a higher number of red than green lines. Keep it up! :)

**Comment by timrae** [comment]
@hssm I believe this has introduced a crash when you open and close settings from the Reviewer.

java.lang.NullPointerException
at com.ichi2.anki.Reviewer.onKeyUp(Reviewer.java:313)
at android.view.KeyEvent.dispatch(KeyEvent.java:2687)
at android.app.Activity.dispatchKeyEvent(Activity.java:2423)

**Comment by hssm** [comment]
I can't reproduce it on my devices. Then again, I'm not sure how to trigger the onKeyUp event in the reviewer. Hardware keyboard? Typing fields?

**Comment by timrae** [comment]
No just standard basic template. Press study button, press settings in
navigation drawer, then press the hardware back button on standard Xperia
ZR smartphone running Android 4.4.4:

https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/report-details/ankidroid/0eb82d7c-4921-40b8-a641-2e927ae388c5

**Comment by timrae** [comment]
Maybe gestures needs to be turned on

**Comment by timrae** [comment]
Hmmm after I disabled and re-enabled gestures I can't reproduce it anymore

**Comment by timrae** [comment]
I thought it was related to gestures, but that doesn't seem to be the case after all. I thought I made the crash stop by disabling gestures, but now I can't reproduce the crash stopping unless I have the answer shown. It never crashes if the answer is shown.

If you still can't reproduce it I can hook up the debugger I guess

**Comment by hssm** [comment]
Okay I reproduced it with your tip about the answer being shown. If you flip the card at least once it won't crash anymore no matter how many times you open/close the reviewer. If you kill the process and start fresh it crashes then.

Incidentally, while testing this, I discovered that the application crashes when you enter and leave the statistics from the reviewer:

```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
            at com.ichi2.anki.Reviewer.onActivityResult(Reviewer.java:485)
```

...which I think is caused by your earlier commit to statistics. I'll fix both while I'm at it.

**Comment by timrae** [comment]
Nice, thanks!

**Pull request merged**
