### PR TITLE
Improved UI for Add Decks Button.

### PR DESCRIPTION
**Pull request by iamvs-2002**
Tested successfully.

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._
#8223 

## Approach
_How does this change address the problem?_
Changed the background for the FAB Buttons to improve its UI
The below images and video show the improvement made:

Screenshot (129)

https://user-images.githubusercontent.com/54304786/113474465-b735fb80-948d-11eb-9ad6-355c1360c0b8.mp4

Screenshot (128)

Screenshot (192)

## How Has This Been Tested?
I have tested it on a physical device(Samsung Galaxy A30) as well as an emulator(Google Pixel XL Api 30).
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or add-ons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
Thanks! We avoid merge commits in git history, could you reset to before the merge and rebase your change onto master instead?

**Comment by iamvs-2002** [comment]
> Thanks! We avoid merge commits in git history, could you reset to before the merge and rebase your change onto master instead?
> 
> Edit: in future, could you use `Fixes #issue`, as this links the issue and the PR

Sure I'll create a new pull request.

**Comment by iamvs-2002** [comment]
> Thanks! We avoid merge commits in git history, could you reset to before the merge and rebase your change onto master instead?
> 
> Edit: in future, could you use `Fixes #issue`, as this links the issue and the PR

For that, shall I fork this repository once again? and then make all the changes once again.

**Comment by david-allison-1** [comment]
> > Thanks! We avoid merge commits in git history, could you reset to before the merge and rebase your change onto master instead?
> > Edit: in future, could you use `Fixes #issue`, as this links the issue and the PR
> 
> For that, shall I fork this repository once again? and then make all the changes once again.

You can do them on the branch for this PR

**Comment by mikehardy** [comment]
A repository once forked is all set forever. Re-forking is not something anyone normally does.
David's words were precise, `git reset` can be used to peel commits off your branch, so that removes the merge commit, `git rebase` can then take *your* commits and add them cleanly to the thing you are rebasing on to.

That gets you an up to date PR (all the changes from main branch are there) with yours at the end, but with no merge commit.

Deleting PRs, re-forking, all that - none of that is necessary.

**Comment by iamvs-2002** [comment]
> > > Thanks! We avoid merge commits in git history, could you reset to before the merge and rebase your change onto master instead?
> > > Edit: in future, could you use `Fixes #issue`, as this links the issue and the PR
> > 
> > 
> > For that, shall I fork this repository once again? and then make all the changes once again.
> 
> You can do them on the branch for this PR

**Comment by iamvs-2002** [comment]
> A repository once forked is all set forever. Re-forking is not something anyone normally does.
> David's words were precise, `git reset` can be used to peel commits off your branch, so that removes the merge commit, `git rebase` can then take _your_ commits and add them cleanly to the thing you are rebasing on to.
> 
> That gets you an up to date PR (all the changes from main branch are there) with yours at the end, but with no merge commit.
> 
> Deleting PRs, re-forking, all that - none of that is necessary.

Yea, I understood all of that after I deleted the fork...so sorry for that.
I have completed the code once again, so should I create a new branch and push the code there?

**Pull request closed without merging**
