### PR TITLE
Add syntax highlighting for card templates

### LINKED ISSUE #8739: [UX Proposal] Code Syntax Highlighting for Card Templates
**Is your feature request related to a problem? Please describe.**
Users often make syntax errors in their CSS. This is frustrating for them, and also requires support effort from the community

**Describe the solution you'd like**
I would like to see HTML, and CSS code highlighting for the Card Template Editor

**Describe alternatives you've considered**
Maybe CSS Validation? Maybe also show JS if possible.

**Additional context**
Night mode needs to be considered
This shouldn't crash, and shouldn't take too long.

### PR DESCRIPTION
**Pull request by ShridharGoel**
## Purpose / Description
Syntax highlighting feature for card templates.

## Fixes
Fixes #8739 

## Approach
Library used: https://github.com/massivemadness/Brackeys-IDE

## How Has This Been Tested?

Verified the UI for `Day theme` (Light and Plain) as well as `Night theme` (Black and Dark).

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

## Screenshots

Day theme

Night theme

### CODE REVIEW

**Comment by mikehardy** [comment]
The unit test failure is real - needs a fix
Can you turn minify on in your debug build in build.gradle and post the APK size with this PR and also from current master?

**Comment by ShridharGoel** [comment]
Updated.

**Comment by ShridharGoel** [comment]
Updated the unit test.

**Comment by ShridharGoel** [comment]
> Can you turn minify on in your debug build in build.gradle and post the APK size with this PR and also from current master?

Current master:
Current master

This PR:
This PR

**Comment by ShridharGoel** [comment]
It seems like this library has caused an increase of approximately 0.7 MB in the APK size.

**Comment by mikehardy** [comment]
Wow, 700Kb is crazy! That's not expected at all. If that's the case, it's too much for this feature, I wouldn't accept it like that. How in the world is text highlighting 700Kb worth of minimized code?

**Comment by ShridharGoel** [comment]
In that case, we might have to pick one of the less maintained libraries.

**Comment by mikehardy** [comment]
...or not do it

**Comment by Akshay0701** [comment]
[Rainbow ](https://craig.is/making/rainbows)— Another popular lightweight 6KB-25KB highlighter
“Rainbow is a code syntax highlighting library written in Javascript.”

**Comment by mikehardy** [comment]
But the template editor is not a webview :thinking: - I suppose it could be, that's getting pretty fancy but ...could work?

**Comment by ShridharGoel** [comment]
> [Rainbow ](https://craig.is/making/rainbows)— Another popular lightweight 6KB-25KB highlighter
> “Rainbow is a code syntax highlighting library written in Javascript.”

Is this available for Android? Also, does it support editing?

**Comment by mikehardy** [comment]
With apologies, now that I think about it, this is already way past the effort level I'm interested in for what is (to me) a very low priority feature

**Comment by mikehardy** [comment]
I'm going to close this for now, it's not viable as-is due to size and if we convert to webview or similar I think that's a different sort of PR

**Pull request closed without merging**
