### PR TITLE
[Kotlin Migration] Meaning 

### PR DESCRIPTION
**Pull request by codingtosh**
[Kotlin Migration] Meaning 
*EDIT: This is an auto generated file, migration is not required here. Closing the PR.*

### CODE REVIEW

**Review by david-allison-1 — COMMENTED** [review]
I think we want to keep auto-generated files in the target language. 

@mikehardy ?

**Review by mikehardy — COMMENTED** [review]
agreed - should either change the auto-generation tool or leave it be
I'm fine with leaving it be
I imagine this is the sort of thing that should get deleted for extraordinarily low usage anyway

**Comment by codingtosh** [comment]
@mikehardy @david-allison-1 I see, should I go ahead and close the 4 PR's for this directory then?

**Comment by mikehardy** [comment]
Yes, sorry for the hassle ! Maybe worth documenting it somewhere - I think there is a Kotlin process page? That auto-generated files are best left alone

**Comment by david-allison-1** [comment]
> I think there is a Kotlin process page?

https://github.com/ankidroid/Anki-Android/blob/master/docs/kotlin-migration.md

**Comment by codingtosh** [comment]
@mikehardy @david-allison-1  
Cool, no worries. I'll update the migration doc and upload it with the next migration batch.

**Pull request closed without merging**
