### PR TITLE
Statistics: right y-axis disappeared on "BREAKDOWN"

### PR DESCRIPTION
**Pull request by jvanprehn**
Solves: https://github.com/ankidroid/Anki-Android/issues/4317
Also fixed bug in AdvancedStatistics which:
- Made it crash if no cards were studied today
- Made it only take into account cards studied today in 1 deck

### CODE REVIEW

**Comment by jvanprehn** [comment]
Won't you forget to merge it into the release branch?

**Comment by timrae** [comment]
I'll cherry-pick it into the release branch and release a new beta this evening

**Comment by timrae** [comment]
I found a few instances of the following crash in the logs... Is it related?

Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.ichi2.anki.stats.StatsMetaInfo
at com.ichi2.libanki.Stats.calculateDue(Stats.java:311)
at com.ichi2.anki.stats.ChartBuilder.calcStats(ChartBuilder.java:73)
at com.ichi2.anki.stats.ChartBuilder.renderChart(ChartBuilder.java:113)
at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:110)
at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:81)

**Comment by jvanprehn** [comment]
Yes that seems to be the one I fixed. To be sure that it's the one I have to see the exception that caused this one. Is that one also logged?

**Comment by hssm** [comment]
Stack trace:
```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:305)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:232)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.ichi2.anki.stats.StatsMetaInfo
at com.ichi2.libanki.Stats.calculateDue(Stats.java:311)
at com.ichi2.anki.stats.ChartBuilder.calcStats(ChartBuilder.java:73)
at com.ichi2.anki.stats.ChartBuilder.renderChart(ChartBuilder.java:113)
at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:110)
at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:81)
at android.os.AsyncTask$2.call(AsyncTask.java:293)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
java.lang.ClassCastException: java.lang.String cannot be cast to com.ichi2.anki.stats.StatsMetaInfo
at com.ichi2.libanki.Stats.calculateDue(Stats.java:311)
at com.ichi2.anki.stats.ChartBuilder.calcStats(ChartBuilder.java:73)
at com.ichi2.anki.stats.ChartBuilder.renderChart(ChartBuilder.java:113)
at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:110)
at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:81)
at android.os.AsyncTask$2.call(AsyncTask.java:293)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:232)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

Logcat:

```
1	06-05 08:48:22.369 I/AnkiDroid( 9336): AbstractFlashcardViewer:: Question successfully shown for card id 1429122157413
2	06-05 08:48:22.849 I/AnkiDroid( 9336): flush - Saving information to DB...
3	06-05 08:48:26.189 E/AnkiDroid( 9336): Stats/ Exception while running hook advancedStatistics : com.ichi2.libanki.hooks.AdvancedStatistics
4	06-05 08:48:26.189 E/AnkiDroid( 9336): android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
5	06-05 08:48:26.189 E/AnkiDroid( 9336): at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
6	06-05 08:48:26.189 E/AnkiDroid( 9336): at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
7	06-05 08:48:26.189 E/AnkiDroid( 9336): at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:74)
8	06-05 08:48:26.189 E/AnkiDroid( 9336): at com.ichi2.libanki.hooks.AdvancedStatistics$TodayStats.<init>(AdvancedStatistics.java:857)
9	06-05 08:48:26.189 E/AnkiDroid( 9336): at com.ichi2.libanki.hooks.AdvancedStatistics.calculateDueAsPlottableSimulationResult(AdvancedStatistics.java:326)
10	06-05 08:48:26.189 E/AnkiDroid( 9336): at com.ichi2.libanki.hooks.AdvancedStatistics.calculateDueAsMetaInfo(AdvancedStatistics.java:203)
11	06-05 08:48:26.189 E/AnkiDroid( 9336): at com.ichi2.libanki.hooks.AdvancedStatistics.runFilter(AdvancedStatistics.java:145)
12	06-05 08:48:26.189 E/AnkiDroid( 9336): at com.ichi2.libanki.hooks.Hooks.runFilter(Hooks.java:150)
13	06-05 08:48:26.189 E/AnkiDroid( 9336): at com.ichi2.libanki.Stats.calculateDue(Stats.java:311)
14	06-05 08:48:26.189 E/AnkiDroid( 9336): at com.ichi2.anki.stats.ChartBuilder.calcStats(ChartBuilder.java:73)
15	06-05 08:48:26.189 E/AnkiDroid( 9336): at com.ichi2.anki.stats.ChartBuilder.renderChart(ChartBuilder.java:113)
16	06-05 08:48:26.189 E/AnkiDroid( 9336): at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:110)
17	06-05 08:48:26.189 E/AnkiDroid( 9336): at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:81)
18	06-05 08:48:26.189 E/AnkiDroid( 9336): at android.os.AsyncTask$2.call(AsyncTask.java:293)
19	06-05 08:48:26.189 E/AnkiDroid( 9336): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
20	06-05 08:48:26.189 E/AnkiDroid( 9336): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:232)
21	06-05 08:48:26.189 E/AnkiDroid( 9336): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
22	06-05 08:48:26.189 E/AnkiDroid( 9336): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
23	06-05 08:48:26.189 E/AnkiDroid( 9336): at java.lang.Thread.run(Thread.java:818)
24	06-05 08:48:26.879 E/AnkiDroid( 9336): Stats/ Exception while running hook advancedStatistics : com.ichi2.libanki.hooks.AdvancedStatistics
25	06-05 08:48:26.879 E/AnkiDroid( 9336): android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
26	06-05 08:48:26.879 E/AnkiDroid( 9336): at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
27	06-05 08:48:26.879 E/AnkiDroid( 9336): at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
28	06-05 08:48:26.879 E/AnkiDroid( 9336): at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:74)
29	06-05 08:48:26.879 E/AnkiDroid( 9336): at com.ichi2.libanki.hooks.AdvancedStatistics$TodayStats.<init>(AdvancedStatistics.java:857)
30	06-05 08:48:26.879 E/AnkiDroid( 9336): at com.ichi2.libanki.hooks.AdvancedStatistics.calculateDueAsPlottableSimulationResult(AdvancedStatistics.java:326)
31	06-05 08:48:26.879 E/AnkiDroid( 9336): at com.ichi2.libanki.hooks.AdvancedStatistics.calculateDueAsMetaInfo(AdvancedStatistics.java:203)
32	06-05 08:48:26.879 E/AnkiDroid( 9336): at com.ichi2.libanki.hooks.AdvancedStatistics.runFilter(AdvancedStatistics.java:145)
33	06-05 08:48:26.879 E/AnkiDroid( 9336): at com.ichi2.libanki.hooks.Hooks.runFilter(Hooks.java:150)
34	06-05 08:48:26.879 E/AnkiDroid( 9336): at com.ichi2.libanki.Stats.calculateDue(Stats.java:311)
35	06-05 08:48:26.879 E/AnkiDroid( 9336): at com.ichi2.anki.stats.ChartBuilder.calcStats(ChartBuilder.java:73)
36	06-05 08:48:26.879 E/AnkiDroid( 9336): at com.ichi2.anki.stats.ChartBuilder.renderChart(ChartBuilder.java:113)
37	06-05 08:48:26.879 E/AnkiDroid( 9336): at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:110)
38	06-05 08:48:26.879 E/AnkiDroid( 9336): at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackground(AnkiStatsTaskHandler.java:81)
39	06-05 08:48:26.879 E/AnkiDroid( 9336): at android.os.AsyncTask$2.call(AsyncTask.java:293)
40	06-05 08:48:26.879 E/AnkiDroid( 9336): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
41	06-05 08:48:26.879 E/AnkiDroid( 9336): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:232)
42	06-05 08:48:26.879 E/AnkiDroid( 9336): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
43	06-05 08:48:26.879 E/AnkiDroid( 9336): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
44	06-05 08:48:26.879 E/AnkiDroid( 9336): at java.lang.Thread.run(Thread.java:818)
```

**Comment by jvanprehn** [comment]
Yes; that's the one I fixed.

**Pull request merged**
