### PR TITLE
flags as SVG

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
2020-02-19-044540_800x1280_scrot
2020-02-19-044534_800x1280_scrot
2020-02-19-044841_757x1372_scrot
With svg instead of png. (Last screenshot with API 16)

If it is accepted, we can and should close https://github.com/ankidroid/Anki-Android/pull/5729#issuecomment-587018850
Should I also change the configuration so that flags appear by default in the toplevel bar instead of marked ?
I know that's not a priority, since this PR is not related to any kind of crash. But I would appreciate to have nice flags in master. Because currently the flag is black, and that's not beautiful. (I know, I'm the one who did add the black icon, months ago. So I'm the only one to blame here)

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Android Studio added "ic_" before the name of the files. I decided to keep it. I assume it means icon. Anyway, that's the reason why so many xml file change, because I needed to add the "ic_" behind it.

**Comment by timrae** [comment]
Have you tested on the lowest API we support?

**Comment by Arthur-Milchior** [comment]
Isn't it api 16 ?  My first commit contains an API 16 screenshot

**Comment by Arthur-Milchior** [comment]
I forgot to emphasize: the red flag in the card is not the svg. The other flags are svg

**Comment by mikehardy** [comment]
minSdkVersion is 15 right now https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/build.gradle#L20
There is a PR to move this to 16 #5665 but I am targeting that for 2.11 since 2.10 is so close to release and I want to defer clipping users off as long as possible.
Testing API15 used to be difficult but the emulators all run now.

I pulled this and tested it, and it's got a problem on Android 4.x (that is, Android API15-API19) - the CSS used to show the flag is not compatible: https://caniuse.com/#search=-webkit-text-stroke-width (as an example)

So the SVG works, this is good to merge

**Except** the flag won't show in the WebView showing the card until API20 / Android 5.x

That's actually a problem in an older PR already merged https://github.com/ankidroid/Anki-Android/commit/af65136dd7cd735666a3fa0d7d3cf5b09fc8ca88#diff-4857e1bad71b4eb152cfdf6771c1fdacR122 on #5679 

Specifically these CSS elements aren't supported in the Android Browser on Android 4.x according to https://caniuse.com:
```css
 -webkit-text-stroke-width: 1px;
 -webkit-text-stroke-color: black;
```

but you can use
```css
-webkit-text-stroke: 1px black;
```

And the glyph for the flag itself is not there in the font for some reason. If you replace it with a letter (I tested with `foo`) then it works fine. I have not found a replacement yet, perhaps it is just missing in the font we are currently using but is available elsewhere, or perhaps we can use something else? If anyone else has experience with the solid flag unicode character (or something similar) that works on Android 4.x that would be great, otherwise I will keep searching

**Comment by mikehardy** [comment]
Specific testing results

- Android 4.0.4 - flag completely missing, empty space
- Android 4.3.1 - flag completely missing, empty space
- Android 5.1.1 - flag represented by 'missing unicode character' box with X in it
- Android 6 - flag present, everything fine
- Android 7.1.1 - flag present, everything fine
- Android 8/8.1 - untested
- Android 9 - everything fine
- Android 10/11 - untested

So this is a problem with API22 and below. We need a text element we can refer to in the card template that will show up on those devices. The coloring CSS trick works fine after the very minor tweak above.

**Comment by mikehardy** [comment]
#5795 should fix the render problem. This PR is separate though, and fine to merge, I tested it a lot

**Pull request merged**
