### PR TITLE
Fix: Prevent crash on long pressing at end of card browser

### LINKED ISSUE #8467: [Bug] Long pressing a card below the end of the initial ListView crashes
###### Reproduction Steps

1. Go to card browser.
2. Long press on a card to select it.
3. After the card is selected, long press again.
4. Notice that the app crashes.

###### Expected Result

App should not crash.

###### Actual Result

The app crashes. Here are the logs:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at com.ichi2.anki.CardBrowser.lambda$onCollectionLoaded$2$CardBrowser(CardBrowser.java:673)
        at com.ichi2.anki.-$$Lambda$CardBrowser$cpk2FDlr72riVUwAw9LYnTvoqho.onItemLongClick(Unknown Source:6)
        at android.widget.AbsListView.performLongPress(AbsListView.java:3288)
        at android.widget.AbsListView$CheckForLongPress.run(AbsListView.java:3205)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6864)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
From #8468. fixed in prep for 2.15

> ## Purpose / Description
> App should not crash on long pressing an already selected card in the card browser.
>  
> ## Fixes
> Fixes #8467 
> 
> ## Approach
> `getChildAt()` method of `ListView` is wrongly used since it concerns the visible items and not the complete list of items. The approach followed to fix this is to make use of the `mCheckedCards` list. While iterating through the cards to select them, the `mCheckedCards` list is being updated and `onSelectionToggle()`  is being called to update the checked state of the list items.
> 
> ## How Has This Been Tested?
> 
> Verified that the mentioned issue does not occur after this change.
> 
> ## Checklist
> 
> - [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
> - [x] You have a descriptive commit message with a short title (first line, max 50 chars).
> - [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
> - [x] You have commented your code, particularly in hard-to-understand areas
> - [x] You have performed a self-review of your own code
> - [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
> - [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

My notes:

```
We were incorrectly using .getChildAt() which returns the view
based on the visual position. Once we got past the end of the
first "page" of the list, we got a crash.

We now update the data, and have the adapter set the checked state
when the data comes into the foreground

Fixes #8467
```

### CODE REVIEW

**Comment by david-allison-1** [comment]
Requesting a sqaush/merge if this goes in

**Comment by Arthur-Milchior** [comment]
If I understand correctly, the logic used to be that if the card was selected, a press on it would unselect it. Now it only select it can't unselect anymore.

A reason for that? I didn't read all commit message since they must be squashed anyway, I'd expect it to see it discussed in the PR message

**Comment by mikehardy** [comment]
@Arthur-Milchior if I understand correctly this is a crash related to a new feature where long-presses on a different part of the list select all cards between previous selection and long-pressed card, or you can drag a selection to select a bunch. It's a way to quickly select a group instead of previous all or nothing

except it had a crash related, which this should fix

But I still need to review it...

**Review by mikehardy — APPROVED** [review]
I'll trust you on this one especially with the test - I know you were working really closely with OP on it

**Comment by mikehardy** [comment]
@Arthur-Milchior you appeared to have a concern so I will mark this pending merge (on your review) but it's a high priority for 2.15 and David's been working on it for quite some time now, if you can't think of a particular thing wrong with it in review please merge

**Comment by david-allison-1** [comment]
> If I understand correctly, the logic used to be that if the card was selected, a press on it would unselect it. Now it only select it can't unselect anymore.
> 
> A reason for that? I didn't read all commit message since they must be squashed anyway, I'd expect it to see it discussed in the PR message

This is only a bugfix, not a change in behavior, the previous code did the same thing.

A long press on a card will now only select, a tap will deselect the card.

See: https://github.com/ankidroid/Anki-Android/pull/8278 for the rationale

**Comment by Arthur-Milchior** [comment]
I just realized that the `toggle` was inside a conditional, so that it can only be toggled to on, not to off. I was mistaken, sorry

**Pull request merged**
