### PR TITLE
Replace some usages of AlertDialog with MaterialDialog

### PR DESCRIPTION
**Pull request by lukstbit**
## Fixes

Replace the platform AlertDialog with MaterialDialog for consistency across the app. There are three more usages of AlertDialog(slightly more complex or maybe could be refactored completely, will be done in another PR). In the first commit there's also a fix for a potential bug, see the commit description.

 See images for the three replaced dialogs:

## How Has This Been Tested?

Ran the tests, manually checked the dialogs.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by oakkitten** [comment]
And I was hoping that we could replace `MaterialDialog`s with `AlertDialog`s instead...

**Comment by lukstbit** [comment]
> And I was hoping that we could replace `MaterialDialog`s with `AlertDialog`s instead...

Why?

**Comment by oakkitten** [comment]
Four reasons;

* I'm not a fan of some of the APIs. E.g. to have a dialog with input, you have to do this weird thing:

      MaterialDialog(...).show {
          positiveButton()
          input { _, text ->
              // For some reason this runs when the dialog is closed with Ok?
          }
      }
  Also, this requires `@SuppressLint("CheckResult")` for some reason:

      MaterialDialog(this).show {
          listItemsSingleChoice(items = items) { _, index, _ -> ... }
      }

* `MaterialDialog` by default looks a bit different from `AlertDialog` as can be seen from the screenshots. The margins are visibly inconsistent. I think `AlertDialog` looks better.

* Since the app has `AlertDialogs` in other places (e.g. preferences), you have to do more work if you want to style them in the same way.

* That's one more library to depend on.

**Comment by mikehardy** [comment]
I don't really care about the aesthetics of the two (and you should see my UI work! but more seriously I know others are paying attention). My $0.02 on material dialogs is that they are developer-unfriendly. Eliminating the dependency would not make me sad. As a focus though: scoped storage, scoped storage, scoped storage, scoped storage is what I actually care about. 

Check this out - they literally don't even have an issues list: https://github.com/afollestad/material-dialogs/ - and the reason I thought they were unfriendly is that years ago they converted to Kotlin in a way that *specifically* broke interop with Java and just said "move to kotlin" as a response. Because they turned off issues you can't even see it anymore, but it was good dark humor at the time https://github.com/ankidroid/Anki-Android/issues/5225#issuecomment-675747029

So anyway, I could use less of that sort of dependency

**Comment by lukstbit** [comment]
@oakkitten Valid points but this is the library that we are using. Removing it would require a huge number of changes and it would be very very low priority for the foreseeable future. Until this happens I would prefer consistency across the app.

**Comment by BrayanDSO** [comment]
Agreed with the points here. Getting rid of the library would be good, but it's a big job/low reward kind of work, so the priority is low. 

So it is best to create an issue about that, so someone motivated may do it on the future.

I wouldn't bother to not change these and not be 100% consistent, as we aren't consistent on other places as Android libraries (e.g. Preferences) nor we are close to being 100% consistent + a new release isn't near, as scoped storage still needs work, so we don't do any job that will be reverted on the future

**Review by mikehardy — APPROVED** [review]
Fine with these - I think we're all in general agreement that *one* style is better, even if we want to move from MaterialDialog in the future

FWIW, I see this as remaining Alerts

```
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:import androidx.appcompat.app.AlertDialog
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:        val builder = AlertDialog.Builder(this)
AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt:import androidx.appcompat.app.AlertDialog
AnkiDroid/src/main/java/com/ichi2/anki/Sync.kt:    val dialog = AlertDialog.Builder(deckPicker)
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:import com.google.android.material.dialog.MaterialAlertDialogBuilder
AnkiDroid/src/main/java/com/ichi2/anki/dialogs/BrowserOptionsDialog.kt:        return MaterialAlertDialogBuilder(requireContext()).run {
AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt:import android.app.AlertDialog
AnkiDroid/src/main/java/com/ichi2/anki/analytics/AnkiDroidCrashReportDialog.kt:        val dialogBuilder = AlertDialog.Builder(this)
AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt:import androidx.appcompat.app.AlertDialog
AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt:    AlertDialog.Builder(context)
AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt:        AlertDialog.Builder(this)
AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt:import android.app.AlertDialog
AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt:                AlertDialog.Builder(requireContext())
AnkiDroid/src/main/java/com/ichi2/anki/preferences/CustomSyncServerSettingsFragment.kt:                AlertDialog.Builder(requireContext())
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/PickStringDialogFragment.kt:import android.app.AlertDialog
AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/PickStringDialogFragment.kt:        val builder = AlertDialog.Builder(activity)
AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.kt:import android.app.AlertDialog
AnkiDroid/src/main/java/com/ichi2/ui/SeekBarPreference.kt:    override fun onPrepareDialogBuilder(builder: AlertDialog.Builder) {
AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt:import androidx.appcompat.app.AlertDialog
AnkiDroid/src/main/java/com/ichi2/preferences/SeekBarPreferenceCompat.kt:        override fun onPrepareDialogBuilder(builder: AlertDialog.Builder) {
```

**Pull request merged**
