### PR TITLE
Update ic_flag_red.xml to match AnkiDesktop

### PR DESCRIPTION
**Pull request by Jennifer202006**
## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
To note: related to #6525 - color is from https://github.com/ankitects/anki/blob/9dcbb8958d64f5be7bfa01201817947eec388c4c/qt/ts/src/reviewer.ts#L107-L112

**Comment by david-allison-1** [comment]
In future, could you use multiple commits in a single PR if the changes are almost identical to the same part of the codebase. Multiple PR increases the time taken both on your side, and on the reviewing/CI side without adding value.

**Comment by Jennifer202006** [comment]
> In future, could you use multiple commits in a single PR if the changes are almost identical to the same part of the codebase. Multiple PR increases the time taken both on your side, and on the reviewing/CI side without adding value.

ok

**Comment by david-allison-1** [comment]
Thanks, and thanks for the fixes :)

**Pull request merged**
