### PR TITLE
Replaced Toast with Snackbar in AnkiDroidJSAPI.kt

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
Used Snackbar instead of Toast

## Fixes
Related #13411 

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Tested on Emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
@SanjaySargam It has become common in your recent PRs please fill the PR template properly you are missing out on the checklist. Just a reminder Thanks though

**Comment by SanjaySargam** [comment]
> @SanjaySargam It has become common in your recent PRs please fill the PR template properly you are missing out on the checklist. Just a reminder Thanks though

Ohh Thanks
I forgot

**Comment by oakkitten** [comment]
..For future reference, when converting toasts to snackbars, please include the screenshots for all activities/fragments that you touch, and verify that the snackbars can be actually dismissed by flinging and animate properly when being flung.

The reason for this request is that it's not feasible to make sure of proper behavior when compiling. A snackbar requires a coordinator layout to work. When there is none, the app will compile without issues, but the snackbar will not render properly and will not visibly fling.

**Comment by SanjaySargam** [comment]
> ..For future reference, when converting toasts to snackbars, please include the screenshots for all activities/fragments that you touch, and verify that the snackbars can be actually dismissed by flinging and animate properly when being flung.
> 
> The reason for this request is that it's not feasible to make sure of proper behavior when compiling. A snackbar requires a coordinator layout to work. When there is none, the app will compile without issues, but the snackbar will not render properly and will not visibly fling.
Ok I will take care next time

**Comment by SanjaySargam** [comment]
> ..For future reference, when converting toasts to snackbars, please include the screenshots for all activities/fragments that you touch, and verify that the snackbars can be actually dismissed by flinging and animate properly when being flung.
> 
> The reason for this request is that it's not feasible to make sure of proper behavior when compiling. A snackbar requires a coordinator layout to work. When there is none, the app will compile without issues, but the snackbar will not render properly and will not visibly fling.

Ok I will take care next time

**Review by lukstbit — APPROVED** [review]

**Review by BrayanDSO — APPROVED** [review]

**Pull request merged**
