### PR TITLE
NF: Move instrumented test functions

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This PR move some code so that it can easily be reused. Multiple PR are going to be based on them, and use the method the current PR introduce.

### CODE REVIEW

**Review by mikehardy — COMMENTED** [review]
no issue with the extraction though it's not completely NF is it? (deck with unique name, one pressBack went away?)

structurally they are not test objects though, should be in testutils I think (sibling directory)

**Comment by Arthur-Milchior** [comment]
DeckWithUniqueName does not create a change in behavior. It is exactly the same behavior that the one that existed before this commit. It creates a deck based on the timestamp. The only difference being that now it generates the timestamp itself. This remove code duplication as many methods gave the same string as paramater.

One back press indeed went away. Given that the method was used only in disabled test, I'd still argue that it's NF. I can remove the NF if you want. In any case, the second back press was the cause of the failure, so it had to be removed. Otherwise the method was not usable. 
Indeed, the second back press, closed the deck picker, thus closed ankidroid, which caused the test failure

**Comment by Arthur-Milchior** [comment]
I admit that it's not clear to me what is inside /anki, what is inside utils, testutils, test, an dialogs.
If we have any specific rules, I'd love if we could write them down. Probably in README.md files in each directory, or at least in the anki/ directory

**Comment by mikehardy** [comment]
Not sure on rules in all cases, but in this case test/ should have actual tests, and things just used by tests are in utils/ because they are more like test utilities - at least that's where I think they should go

I'm okay with those mostly-maybe-not-quite-NF changes, especially based on your comments

**Review by mikehardy — APPROVED** [review]

**Comment by Arthur-Milchior** [comment]
I added a second commit @mikehardy. Because I believe the function as implemented was not exactly what a developer might expect while using it.

**Review by david-allison — APPROVED** [review]
Cheers

**Pull request merged**
