### PR TITLE
Fix NullPointerException in DeckPicker

### LINKED ISSUE #8886: 2.15.0beta4 - crash getting Decks.current().optLong("id") on freshly installed app / fresh collection
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long org.json.JSONObject.optLong(java.lang.String)' on a null object reference
at com.ichi2.anki.DeckPicker.__renderPage(DeckPicker.java:32)
at com.ichi2.anki.DeckPicker$UpdateDeckListListener.actualOnPostExecute(DeckPicker.java:9)
at com.ichi2.anki.DeckPicker$UpdateDeckListListener.actualOnPostExecute(DeckPicker.java:1)
at com.ichi2.async.TaskListenerWithContext.onPostExecute(TaskListenerWithContext.java:2)
at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.java:3)
at android.os.AsyncTask.finish(AsyncTask.java:755)
at android.os.AsyncTask.access$900(AsyncTask.java:192)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:221)
at android.app.ActivityThread.main(ActivityThread.java:7584)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:1)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23754)
at android.view.ViewGroup.layout(ViewGroup.java:7277)
at android.view.View.layout(View.java:23754)
```

```

5-17  13:52:58.534 E/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
--
1 | 05-17  13:52:58.534 E/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
3 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.os.Handler.dispatchMessage(Handler.java:107)
4 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.os.Looper.loop(Looper.java:221)
5 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread.main(ActivityThread.java:7584)
6 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at java.lang.reflect.Method.invoke(Native Method)
7 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
8 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
9 | 05-17 13:52:58.534 E/AnkiDroid(21476):
10 | 05-17  13:52:58.534 E/AnkiDroid(21476):  com.ichi2.anki.exception.StorageAccessException: Failed to create  AnkiDroid directory /storage/emulated/0/AnkiDroid
11 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:3)
12 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:6)
13 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:3)
14 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:1)
15 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.firstCollectionOpen(DeckPicker.java:9)
16 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.handleStartup(DeckPicker.java:2)
17 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.onRequestPermissionsResult(DeckPicker.java:5)
18 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8408)
19 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.Activity.dispatchActivityResult(Activity.java:8253)
20 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4953)
21 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5001)
22 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
23 | 05-17  13:52:58.534 E/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
24 | 05-17  13:52:58.534 E/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
25 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
26 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.os.Handler.dispatchMessage(Handler.java:107)
27 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.os.Looper.loop(Looper.java:221)
28 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at android.app.ActivityThread.main(ActivityThread.java:7584)
29 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at java.lang.reflect.Method.invoke(Native Method)
30 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
31 | 05-17 13:52:58.534 E/AnkiDroid(21476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
32 | 05-17  13:52:58.539 W/AnkiDroid(21476): CollectionHelper/  com.ichi2.anki.exception.StorageAccessException: Failed to create  AnkiDroid directory /storage/emulated/0/AnkiDroid
33 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:3)
34 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  com.ichi2.anki.CollectionHelper.isCurrentAnkiDroidDirAccessible(CollectionHelper.java:1)
35 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.InitialActivity.getStartupFailureType(InitialActivity.java:3)
36 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.handleStartup(DeckPicker.java:5)
37 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.onRequestPermissionsResult(DeckPicker.java:5)
38 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8408)
39 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.Activity.dispatchActivityResult(Activity.java:8253)
40 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4953)
41 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5001)
42 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
43 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
44 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
45 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
46 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.os.Handler.dispatchMessage(Handler.java:107)
47 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.os.Looper.loop(Looper.java:221)
48 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.main(ActivityThread.java:7584)
49 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at java.lang.reflect.Method.invoke(Native Method)
50 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
51 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
52 | 05-17 13:52:58.539 W/AnkiDroid(21476):
53 | 05-17  13:52:58.539 W/AnkiDroid(21476):  com.ichi2.anki.exception.StorageAccessException: Failed to create  AnkiDroid directory /storage/emulated/0/AnkiDroid
54 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:3)
55 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  com.ichi2.anki.CollectionHelper.isCurrentAnkiDroidDirAccessible(CollectionHelper.java:1)
56 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.InitialActivity.getStartupFailureType(InitialActivity.java:3)
57 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.handleStartup(DeckPicker.java:5)
58 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.ichi2.anki.DeckPicker.onRequestPermissionsResult(DeckPicker.java:5)
59 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8408)
60 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.Activity.dispatchActivityResult(Activity.java:8253)
61 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4953)
62 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5001)
63 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
64 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
65 | 05-17  13:52:58.539 W/AnkiDroid(21476): 	at  android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
66 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
67 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.os.Handler.dispatchMessage(Handler.java:107)
68 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.os.Looper.loop(Looper.java:221)
69 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at android.app.ActivityThread.main(ActivityThread.java:7584)
70 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at java.lang.reflect.Method.invoke(Native Method)
71 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
72 | 05-17 13:52:58.539 W/AnkiDroid(21476): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
73 | 05-17 13:52:58.545 I/AnkiDroid(21476): AnkiDroid directory inaccessible
74 | 05-17 13:52:58.579 I/AnkiDroid(21476): AnkiActivity::onResume - DeckPicker
75 | 05-17 13:52:58.604 I/AnkiDroid(21476): AnkiActivity::onPause - DeckPicker
76 | 05-17 13:52:58.704 I/AnkiDroid(21476): Adding open changelog
77 | 05-17 13:52:58.709 I/AnkiDroid(21476): Begin openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
78 | 05-17 13:52:58.719 I/AnkiDroid(21476): Opening rust backend. Server: false. Langs: 'en', path:
79 | 05-17 13:52:58.729 I/AnkiDroid(21476): Opening Collection: '/storage/emulated/0/AnkiDroid/collection.anki2' '' '' ''
80 | 05-17 13:52:58.758 I/AnkiDroid(21476): Opening Collection Log
81 | 05-17 13:52:58.771 I/AnkiDroid(21476): End openCollection: /storage/emulated/0/AnkiDroid/collection.anki2
82 | 05-17 13:52:58.787 E/AnkiDroid(21476): Preferences/ Preferences: no preference found for the key: syncAccount
83 | 05-17 13:52:58.943 I/AnkiDroid(21476): AnkiActivity::onStop - DeckPicker
84 | 05-17 13:52:58.948 I/AnkiDroid(21476): flush - Saving information to DB...
85 | 05-17 13:52:58.949 I/AnkiDroid(21476): Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
86 | 05-17 13:53:06.390 I/AnkiDroid(21476): Handling Activity Result: 1. Result: 0
87 | 05-17 13:53:06.390 I/AnkiDroid(21476): Creating notification channel with id/name: General Notifications/AnkiDroid
88 | 05-17 13:53:06.394 I/AnkiDroid(21476): Creating notification channel with id/name: Synchronization/同步
89 | 05-17 13:53:06.396 I/AnkiDroid(21476): Creating notification channel with id/name: Global Reminders/卡片到期
90 | 05-17 13:53:06.397 I/AnkiDroid(21476): Creating notification channel with id/name: Deck Reminders/提醒
91 | 05-17 13:53:06.399 I/AnkiDroid(21476): finishWithoutAnimation
92 | 05-17 13:53:06.529 I/AnkiDroid(21476): AnkiActivity::onDestroy - DeckPicker
93 | 05-17 13:53:07.369 I/AnkiDroid(21476): Launching DeckPicker
94 | 05-17 13:53:07.398 I/AnkiDroid(21476): AnkiActivity::onCreate - DeckPicker
95 | 05-17 13:53:07.404 I/AnkiDroid(21476): Fresh install
96 | 05-17 13:53:07.465 I/AnkiDroid(21476): AnkiActivity::onStart - DeckPicker
97 | 05-17 13:53:07.470 I/AnkiDroid(21476): AnkiActivity::onResume - DeckPicker
98 | 05-17 13:53:07.477 I/AnkiDroid(21476): Updating deck list UI

```
```

### PR DESCRIPTION
**Pull request by ShridharGoel**
## Purpose / Description
Fix NullPointerException in DeckPicker.

## Fixes
Fixes #8886 

## Approach
Select the default deck if the selected deck is null.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
Mmmm - I don't know :thinking: 
This will obviously protect this code from null, it will fix the crash in this stack trace

However...why is the current deck unknown? The current deck should always be valid - I think it's a fundamental assumption in the system that decks.current exists and is valid.

It's actually part of the collection configuration data structure even:

https://github.com/ankidroid/Anki-Android/blob/be061d064ee2ebdbb94f88280c7b2f7c484637b8/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java#L1070-L1080

So I think this is just a band aid on the real underlying problem "why is this deck configuration corrupt?" and "if the deck configuration is corrupt, *then what do we do?*"

There are two other call sites that use this assumption directly:

```
mike@isabela:~/work/AnkiDroid/Anki-Android-Upstream (release-2.15) % grep -r 'current().optLong("id"' AnkiDroid/src/main/java/
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:        long current = getCol().getDecks().current().optLong("id");
AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java:            if (mDid == deckPicker.getCol().getDecks().current().optLong("id")) {
AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.java:        return node.getDid() == mCol.getDecks().current().optLong("id");
AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java:            id = col.getModels().current().optLong("id", -1);

```

And the Decks.java file uses it a lot as well.

The logcat indicates it's a fresh install, so that indicates that starting from scratch, it's possible for a freshly generated collection to have a corrupt deck configuration. That's something we need to get to the root of

**Comment by dae** [comment]
Unfortunately that's not a safe assumption - if the user deletes a deck on one device and makes changes on another, the subsequent merge may result in the current deck being invalid. Even before the start of the Rust migration, the code handled this case by falling back to the default deck in the get() call if the deck couldn't be found:

https://github.com/ankitects/anki/blob/442df9d6689bc0395e80c4c28282c2f7814e2a51/anki/decks.py#L237

Aside from that syncing corner case, there's also bugs and broken third-party clients/add-ons/file generators to contend with as well. So unfortunately there isn't anything we can really safely assume is true when it comes to reading data from the DB, and the code always needs to be prepared for something to be missing or typed incorrectly. That doesn't mean we need to handle it transparently, but we should be at least able to present an error instead of crashing, and the newer backend code tries a lot harder to handle such cases than the old Python code did.

**Comment by mikehardy** [comment]
Boom! Thanks @dae - so @ShridharGoel the real fix is in Decks to make sure current isn't null before returning it, if it is null, set deck conf current deck to default deck then return that. Sound right Damien?

Still leaves the question: how did we end up with a corrupt current deck on a fresh install - that's worrying still.

**Comment by ShridharGoel** [comment]
> Still leaves the question: how did we end up with a corrupt current deck on a fresh install - that's worrying still.

Can it happen if the AnkiDroid folder was already there with a corrupted deck and a fresh install was done?

**Review by mikehardy — COMMENTED** [review]
I think this is the right solution for now - thanks @ShridharGoel - I also think you may be on to something with an uninstall/reinstall cycle meaning there may have been a corrupt deck already there, even with no permissions at first.
I noticed you changed a bunch of spacing, normally the only way I'll accept spacing changes in a bugfix PR is if you have a clean commit stream (that is: exactly 2 commits, one that is spacing only, one that fixes the bug). This PR does not meet that standard, the commit stream is a mess, so I have to squash merge it.

In the future please maintain good commit hygiene as well while working - it's a good habit to get in to. I will merge this regardless this time as it's a bug fix for 2.15 and I really want to get it out with as little extra delay as possible - of course I really appreciate the fix, thank you!

**Comment by ShridharGoel** [comment]
@mikehardy Sorry about the whitespace changes. I had noticed them in the `Files changed` section and had decided to revert them but forgot about it later.

**Comment by dae** [comment]
> make sure current isn't null before returning it, if it is null, set deck conf current deck to default deck then return that. Sound right Damien?

It could be null/missing, or it could point to an id that doesn't exist - both cases need to be handled

**Comment by mikehardy** [comment]
Hi there!

Apologies for the delay, and if you're already submitted something to OpenCollective for May 2021 PRs merged, you may feel free to ignore this.

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for May 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in May)

Thanks!

**Pull request merged**
