### PR TITLE
 Added Malayalam Language

### LINKED ISSUE #8676: Support for  "Malayalam" Language
**Is your feature request related to a problem? Please describe.**
AnkiDroid Does not support Malayalam Language

**Describe the solution you'd like**
Creating A `value-ml` will add Malayalam language

### PR DESCRIPTION
**Pull request by vinishhub**
## Purpose / Description
Fixes #8676  Added malayalam Language support to Ankidroid

## Fixes
Fixes _Link to the issues._

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by vinishhub** [comment]
I think now its perfect

**Comment by mrudultora** [comment]
@vinishhub Just a suggestion (this PR is completely fine). Avoid making PRs from master branch. Create a new branch, make the changes and then push the changes.

**Comment by vinishhub** [comment]
thanks @mrudultora from next time I will do that ,david also suggested me to do that!,I need to learn more about github from next time😅

**Review by mikehardy — APPROVED** [review]
This looks good to me - a clean PR :-), thank you

I modified the PR description to contain the exact text `Fixes #number` so that github auto-magically cross-links everything between the issue and pr

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for April 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged in April)

Thanks!

**Pull request merged**
