### PR TITLE
New icons - partially done

### PR DESCRIPTION
**Pull request by jshevek**
First set of new icons, taken from https://google.github.io/material-design-icons/

This is incomplete, but sufficient to give an impression of how it will look, so we can start making changes if needed. 

-----
previous commit message follows:

Cherry pick this commit if you just want to add these new icons:

(to mdpi, hdpi, xhdpi, xxhdip)

ic_action_accept.png
ic_action_camera.png
ic_action_cancel.png
ic_action_email.png
ic_action_import_export.png
ic_action_mic.png
ic_action_replay.png
ic_action_search.png
ic_action_settings.png
ic_action_storage.png
ic_action_time.png
ic_dialog_alert.png
ic_dialog_info.png
ic_menu_add.png
ic_menu_edit.png
ic_menu_mark.png
ic_menu_marked.png
ic_menu_night.png
ic_menu_night_checked.png
ic_menu_refresh.png
ic_menu_send.png
ic_menu_sort_by_size.png
ic_menu_statistics.png

--------------------------------------------------
Deleted these 3 files from the current branch during the cherry pick, after being warned of merge conflicts.

Conflicts:
	AnkiDroid/src/main/res/drawable-hdpi/ic_menu_add.png
	AnkiDroid/src/main/res/drawable-xhdpi/ic_action_help.png
	AnkiDroid/src/main/res/drawable-xhdpi/ic_menu_add.png

### CODE REVIEW

**Comment by timrae** [comment]
Thanks... obviously we can't merge until you finish all the icons.

It looks fine other than the following issues which will need to be resolved:

1. ic_menu_refresh needs to be changed to the sync one with the two arrows

2. ic_menu_add looks like rubbish due to the deletion of the high resolution versions... can't you just pull the latest branch from develop before running your script?

3. the color of the icons doesn't gel with the rest of the Holo interface. If possible please write your shell script so that it generates and copies all the icons, and temporarily set it to render them using the [holo theme colors](http://developer.android.com/design/style/iconography.html#action-bar). Put the script in the tools folder and configure it so that it can be run from the main parent folder with an optional argument for the location of the cloned github repository. e.g. `./tools/render-icons.sh $HOME/material-design-icons`. That way, once the targetApi is updated to 21, we can just change the color settings in the script and be on our way. In cases where the name of the icon in the source is different from the old filename, you should modify the xml to use the new filename, and delete the old file rather than trying to maintain consistency. You might want to make that a separate commit.

**Comment by jshevek** [comment]
Okay, so

(1)  ic_menu_refresh becomes:     https://google.github.io/material-design-icons/notification/svg/ic_sync_24px.svg

(4) ic_menu_manage.png is deleted, and that space becomes empty - no icon in the dialog, right?

(3a) dark and light icons should use "  #333333  Enabled: 60% opacity  Disabled: 30% opacity   and  #FFFFFF Enabled: 80% opacity Disabled: 30% opacity"

(3b) streamlining the script - thanks for explaining specific ways to improve it.  If I don't get to this, i'll be sure to make supporting info available to others. 

(3c)  "In cases where the name of the icon in the source is different from the old filename, you should modify the xml to use the new filename, and delete the old file rather than trying to maintain consistency."

I was intentionally trying to avoid editing xml for this PR - based on what I learned while theming...I chose (i) sneak the new images in under the old filenames over (ii) update all the xml, only to do it all over again for theming and over (iii) start trying to put the theming-via-attributes skeleton in place.

If (i) is not cool, I'll look at how much work is in (ii) vs (iii). 

Regarding (2), I think I just messed up the merge, should be easy to fix. 

But (5) is this everything? I'm especially interested in knowing what other icons we need to set up. 

(6) Are we deleting ic_start, and leaving blank space there?

**Comment by jshevek** [comment]
Oh, and ic_menu_revert is replaced with:
https://google.github.io/material-design-icons/content/svg/ic_undo_24px.svg

Regarding (3c) again, I think I understand you but want to be sure: you want the icon file names to bear the names which google gave them, rather than match the way we will use them, right?

**Comment by timrae** [comment]
> Regarding (3c) again, I think I understand you but want to be sure: you want the icon file names to bear the names which google gave them, rather than match the way we will use them, right?

yes exactly

> (3b) streamlining the script - thanks for explaining specific ways to improve it. If I don't get to this, i'll be sure to make supporting info available to others.

> I was intentionally trying to avoid editing xml for this PR - based on what I learned while theming...I chose (i) sneak the new images in under the old filenames over (ii) update all the xml, only to do it all over again for theming and over (iii) start trying to put the theming-via-attributes skeleton in place.

OK no worries about the script and the filenames for now... probably it makes sense to take care of that properly when changing the colors over from Holo to Material Design.

> (6) Are we deleting ic_start, and leaving blank space there?

just leave it as is for now, that whole screen needs to be redesigned IMO

> But (5) is this everything? I'm especially interested in knowing what other icons we need to set up.

yes no other problems that I'm aware of, but I'll check over it again once you address the issues discussed so far

**Comment by jshevek** [comment]
Okay, this sounds like a shorter path to calling this step 'done', though I also see benefit to  doing the icons more 'correctly', with the end goal of a themable app. (In other words, doing (iii) instead of (i) or (ii).   My theme-refactor branch is so far removed from develop, this might be a good way to start introducing theme-refactoring in smaller chunks.   It may not have any effect on the actual UI at all, just setting the foundation in code.  )

**Comment by timrae** [comment]
I'm in favor of step 1 and a quick merge

**Comment by abvanpelt** [comment]
This is a very hypothetical question, as there are other things I'd like to work on in AnkiDroid first, but what are your thoughts @timrae, @hssm, @jshevek on a StudyOptionsFragment redesign? I assume that's the screen that you mention needing to be redesigned, Tim?

I think that the Deck Options and Custom Study buttons could be moved into an overflow menu and the deck due / study button take up the whole screen (plus maybe a deck statistics chart?). I think the Add Note action item could be in an overflow as well. Not quite sure about the Night Mode button. What do you think?

**Comment by jshevek** [comment]
> I'm in favor of (i) and a quick merge.

Okay, I play to do that much within the next day, hopefully.

> The icons will all need to be changed again (i.e. the color) when we switch from Holo to Material Design, so the theming work can be done then.

The way I see it, we would simply copy new files into the project, and change the attr reference in themes.xml.  I feel it actually reduces the total future work to make a straightforward, bite sized change like this soon.

**Comment by timrae** [comment]
Yes I'm strongly in favour of redesigning that screen. The white buttons on
gray background looks horrible, particularly the gray space between the
widgets. If it was all one continuous card it would look much better imo.

Deck options and custom study should stay prominent on that screen. We get
enough support requests as is complaining about the "artificial study
limits".

Night mode button is hopefully going to disappear anyway. I don't see any
advantage to getting rid of add from the action bar.

Would love to see some mockups if you get time to work on this.

**Comment by jshevek** [comment]
> what are your thoughts @timrae, @hssm, @jshevek on a StudyOptionsFragment redesign? 

I'm in favor of anything that moves us towards a cleaner UI, one piece at a time.  Especially anything that sets a better foundation for theme or material design.

**Comment by timrae** [comment]
Thanks for the new commits, it's looking much better now. 

It seems the only thing left is the icons when night mode is enabled... You're free to implement that in this PR, or separately in your themes branch if you like, just please post the script you used in this PR description so that we can generate the icons ourselves in the unlikely event that you disappear.

Also, it seems you have a spurious set of `ic_menu_add_old` files.

Please squash everything down to a single commit, and post when you're ready to merge.

**Comment by nicolas-raoul** [comment]
Since you are talking about a major StudyOptionsFragment redesign, just a random idea:

How about removing the Study Options screen altogether?
It is not that useful, and takes a click (and time) at every deck switch.

**Comment by timrae** [comment]
Yeah I'd be in favor of that as well... all of the information available
there can be added to Statistics, in which case the screen only needs to be
shown when there are no cards left to view (i.e. the "congratulations
screen"). I believe Anki Mobile does something like this actually.

**Comment by jshevek** [comment]
I've placed the script in tools, but being of a cautious mindset (and not being especially skilled with bash scripting) I set it up to write only within its own directory.  It suggests to the user and easy method for moving the files into the project, after the user has viewed them.

If you guys wish to change it so it automatically overwrites project files, that's cool.

I'm still working on the night mode icons - these commits are work-in-progress. 

> Please squash everything down to a single commit, and post when you're ready to merge.
I usually run into trouble changing the history after pushing, but I'll see what happens.

**Comment by timrae** [comment]
Thanks for that. Are the svg-files necessary? I.e. can we not acquire them directly from Google without committing to the repository?

> I usually run into trouble changing the history after pushing, but I'll see what happens.

I normally just run `git rebase -i HEAD~$NUM` where NUM is the number of commits to go back on. Then change all the "pick"s into "squash" except for the last one. Resolve any merge conflicts (there shouldn't be), and then do `git push -f` (it will be rejected without the f argument)

**Comment by jshevek** [comment]
The svg files have been edited to work with the script, with insertions like:

<path fill="#COLOR_PLACE_HOLDER" fill-opacity="OPACITY_PLACE_HOLDER" d="M10 20v-6h4v6h5v-8h3l-10-9-10 9h3v8z"/>

If we re-download them, we have to re-modify them, and there were a few which required a small bit of thought (which svg path serves which purpose?).

They can all be zipped to a single 17k file, only 3x the size of the script itself.

**Comment by timrae** [comment]
OK well I guess we can deal with that... Although I'd be surprised if there wasn't a way around doing that. For Holo Google provided an illustrator script to render all the icon sizes for a given .ai file, which I modified to give all four color / opacity combinations. You can find it in `docs\graphics\Illustrator`

**Comment by jshevek** [comment]
This commit does not fix the problem of drop down icon in the action bar being the wrong color in night mode.   This will be fixed with the theme refactoring

**Comment by timrae** [comment]
Thanks a lot, looking forward to seeing the theme refactoring come together!

**Comment by timrae** [comment]
By the way, I remember you saying that you wanted to do this icon change initially, but decided against it because you thought that we wouldn't be open to changing the icons... I think you'll find that we're pretty open to changes in the UI, so please feel free to discuss any time, rather than making assumptions that restrict the options you have available to you.

**Comment by timrae** [comment]
@jshevek @abvanpelt 
I [posted to the forum](https://groups.google.com/forum/#!topic/anki-android/_m_As1MluXk) about the study options redesign; please post there if you are interested in contributing to the design or discussion

**Comment by abvanpelt** [comment]
Thanks! Will do.

**Comment by jshevek** [comment]
@nobnago  an easy way to get icons pre-made for all the screen sizes is to git clone https://github.com/google/material-design-icons

**Pull request merged**
