### PR TITLE
Add "Rate AnkiDroid" to changelog

### LINKED ISSUE #7301: Add "Rate App" button to changelog
A simple change which should hopefully drive more user engagement (and hopefully get AnkiDroid into the hands of more users)

### PR DESCRIPTION
**Pull request by david-allison-1**
Button brings up a picker containing AppGallery, F-Droid and Google Play Store on my Android 9.

"Continue" is full-width if rating is not available

## Fixes

Fixes #7301

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM - I'm chuckling to myself that when you say make sure it won't crash and you have a catch(Exception) in there, I'm sure there will be some crash that requires a catch of Throwable (like maybe it throws SecurityError or something totally unexpected). Because...yeah

**Comment by mikehardy** [comment]
Picking this to release-2.13 - it collides with the important back button pick, but more interestingly this will only show up for people updating a public version, so in fact there is no extra risk of including it here vs the next public version because we won't get any extra testing between now and then anyway! So going for the faster feature delivery and easier back button pick

**Comment by david-allison-1** [comment]
Could we make sure this gets a reasonable "release-beta" period to ensure I haven't done anything truly stupid with this

**Comment by mikehardy** [comment]
definitely - as mentioned on discord idea is to let it soak around 48 hours from now, we should see by then :crossed_fingers:

**Pull request merged**
