### PR TITLE
Updated strings from Crowdin 20220130

### PR DESCRIPTION
**Pull request by mikehardy**
Standard I18N sync, though it's been 9 days so the changes are correspondingly large

### CODE REVIEW

**Comment by david-allison-1** [comment]
```

> Task :AnkiDroid:lintPlayRelease FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java:352: Error: Format string 'cloze_sample_text' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]
            fieldValues.set(0, getString(R.string.cloze_sample_text, "c1"));
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-pl/02-strings.xml:291: This definition does not require arguments
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/test/java/com/ichi2/anki/CardTemplatePreviewerTest.java:128: Error: Format string 'cloze_sample_text' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]
        assertThat(arr[0], is(testCardTemplatePreviewer.getString(R.string.cloze_sample_text, "c1")));
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-pl/02-strings.xml:291: This definition does not require arguments
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java:142: Error: Format string 'time_quantity_hours_minutes' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]
            return res.getString(R.string.time_quantity_hours_minutes, (int) Math.floor(time_s/TIME_HOUR), (int) Math.round((time_s % TIME_HOUR) / TIME_MINUTE));
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-es-rAR/01-core.xml:147: This definition does not require arguments
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/01-core.xml:132: Error: Inconsistent number of arguments in formatting string time_quantity_hours_minutes; found both 2 here and 0 in values-es-rAR/01-core.xml [StringFormatCount]
    <string name="time_quantity_hours_minutes">%1$d h %2$d m</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-es-rAR/01-core.xml:147: Conflicting number of arguments (0) here
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:183: Error: Inconsistent number of arguments in formatting string export_email_text_new; found both 2 here and 0 in values-nl/02-strings.xml [StringFormatCount]
    <string name="export_email_text_new">
    ^
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-nl/02-strings.xml:191: Conflicting number of arguments (0) here
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/02-strings.xml:269: Error: Inconsistent number of arguments in formatting string cloze_sample_text; found both 1 here and 0 in values-pl/02-strings.xml [StringFormatCount]
    <string name="cloze_sample_text">This is a {{%1$s::sample}} cloze deletion.</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-pl/02-strings.xml:291: Conflicting number of arguments (0) here
6 errors, 0 warnings
```

**Comment by david-allison-1** [comment]
https://crowdin.com/translate/ankidroid/7291/en-pl?filter=basic&value=0#q=cloze_sample_text

Vandalism from https://crowdin.com/profile/yaninanabays123: https://crowdin.com/translate/ankidroid/7290/en-esar?filter=basic&value=0#6534926

Only one instance. Reverted

Fixed https://crowdin.com/translate/ankidroid/7291/en-nl?filter=basic&value=0#q=export_email_text_new

**Comment by david-allison-1** [comment]
Performing sync.

**Comment by mikehardy** [comment]
Ah thanks for the cleanup @david-allison-1 - I was to the point where I had the crowdin tab opened, was juuuust about to start cleaning then ran out of time for the day and now my kid's on school vacation rest of the week :weary: :laughing: . Current velocity: :snail:

**Pull request merged**
