### PR TITLE
Made MergeRootFrame Fatal

### LINKED ISSUE #10502: Enable Lint: `MergeRootFrame`
We perform lint checking to ensure code correctness and improve performance, but many of the system lint checks have not been enabled.

The goal of this issue is to enable the lint check: `MergeRootFrame`

Line: https://github.com/ankidroid/Anki-Android/blob/6260cd6e25f67f331833bbd0981f2cda5a426dde/lint-release.xml#L248

To do this: 

* Change `ignore` to `fatal`
* Move the line in the XML to be somewhere near the top of the file (before the large block of `ignore` elements. 
  * The exact position is up to you, but if there's no comment associated with the check, a large nearly alphabetical block of `fatal` warnings seems sensible
* Run `gradlew lint` in the Android Studio terminal and fix the errors which occur.
  * `@Suppress(str)` (Kotlin) or `@SuppressWarnings(str)`  (Java) the warnings if they are valid. Android Studio's quickfixes menu will offer options to suppress
    * Use your judgment, but aim to suppress as close to the error as possible (line/method) unless the class specifically has a reason why it will violate a lint check many times
  * If it was an error that we missed, fix it.
* Test your changes
* Submit a Pull Request

### PR DESCRIPTION
**Pull request by shankarpriyank**
## Purpose / Description
Enabled lint check for "ObsoleteLayouParam", changed "ignore" to "fatal" and took the line above.

## Fixes
Fixes #10502 

## How Has This Been Tested?
Ran ./gradlew lint and resolved errros in 5 xml fies

### CODE REVIEW

**Comment by shankarpriyank** [comment]
Hey @david-allison Thanks for the review!!
 I am on it, I will have to search through the app as I am new to it, It would really help me if you could give me some directions to get to those screens, also in the unit tests throwing null pointer exceptions! ,  sorry I also cannot interpret the changes you have requested it just show "No new Line at the end of file"

**Comment by david-allison** [comment]
> Hey @david-allison Thanks for the review!! I am on it, I will have to search through the app as I am new to it, It would really help me if you could give me some directions to get to those screens, also in the unit tests throwing null pointer exceptions! , sorry I also cannot interpret the changes you have requested it just show "No new Line at the end of file"

* Review a flashcard, with each of the `Preferences - Reviewing - Fullscreen` settings set
* Add Note - Paperclip - Advanced - Translate/Pronounce`

**Comment by shankarpriyank** [comment]
Hey @david-allison the app is crashing as soon as try to open a deck

`2022-03-18 12:17:29.107 7733-7733/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 7733
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.Reviewer}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.widget.FrameLayout.getLayoutParams()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.widget.FrameLayout.getLayoutParams()' on a null object reference
        at com.ichi2.anki.AbstractFlashcardViewer.initLayout(AbstractFlashcardViewer.java:1185)
        at com.ichi2.anki.Reviewer.initLayout(Reviewer.java:1175)
        at com.ichi2.anki.AbstractFlashcardViewer.onCollectionLoaded(AbstractFlashcardViewer.java:736)
        at com.ichi2.anki.Reviewer.onCollectionLoaded(Reviewer.java:356)
        at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.java:384)
        at com.ichi2.anki.Reviewer.onCreate(Reviewer.java:197)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) `

**Comment by david-allison** [comment]
The first step would be debugging `initLayout` and finding the variable which is null, then seeing if we can fix this.

I would presume `flashcard_frame` is null

**Pull request closed without merging**
