### PR TITLE
Migrate TopLevelParser to kotlin

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

Migrates the TopLevelParser.java file to kotlin following the migration guide. Class from the doomed wildplot package so no cleanups.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]

**Review by BrayanDSO — APPROVED** [review]
This needs a rebase into main. Otherwise looks good

**Comment by lukstbit** [comment]
@BrayanDSO Thanks for restarting the checks(working locally). Fixed the nullability issues by using `!!` with confirmation that is safe because that nullable property will only be called if the type is valid(and in that case it's assigned a non null string).

**Comment by mikehardy** [comment]
I have this queued for local re-integration check pre-merge in a local merge train...

**Comment by mikehardy** [comment]
passes locally, seems it is an emulator flake?

**Comment by lukstbit** [comment]
It was failing on our gradle check task task assertNonzeroAndroidTests() when we have 0 tests run. So it's not a single test being flaky.

**Comment by mikehardy** [comment]
> It was failing on our gradle check task task assertNonzeroAndroidTests() when we have 0 tests run. So it's not a single test being flaky.

Right, but that's what happens when the whole thing crashes or doesn't load for some reason. I added that check because it would silently-pass that case before, which was a real miss.

Now it at least flags it for review. But it did pass emulator tests locally

it failed on main later:
https://github.com/ankidroid/Anki-Android/runs/8169002074?check_suite_focus=true#step:9:308

I don't see anything immediately obvious in the logs though :thinking: 

But has also passed (the release version bump one passed after)
https://github.com/ankidroid/Anki-Android/runs/8161703489?check_suite_focus=true

So, something to keep an eye on

**Pull request merged**
