### PR TITLE
remove unused 'ScopedStorageMigrationDialog' 

### PR DESCRIPTION
**Pull request by david-allison**
Not high priority

## Purpose / Description
Removes an unused dialog + unused strings

* renames `ScopedStorageMigrationDialog` -> `ScopedStorageMigration`

I would like to extract more scoped storage work here, BUT not while active PRs will get conflicts

## How Has This Been Tested?
Only ran lint

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by lukstbit — APPROVED** [review]
LGTM
Why delete the `strings` label?

**Comment by david-allison** [comment]
The strings are now unused, cause lint errors due to this and won't be used in future

**Review by BrayanDSO — APPROVED** [review]

**Comment by david-allison** [comment]
This has happened twice and was not intentional. Unsure if it's an issue with the app

**Comment by mikehardy** [comment]
Pending #13428

**Pull request merged**
