### PR TITLE
Improvements in card browser code

### PR DESCRIPTION
**Pull request by ShridharGoel**
- Ensured that flows can be updated only from ViewModel.
- I think we don't need `runOnUiThread` when `lifecycleScope` is used.

### CODE REVIEW

**Comment by BrayanDSO** [comment]
notice: This branch is under `Anki-Android`, not in your fork

**Comment by david-allison** [comment]
Copied from Discord:

> DavidA — 31/01/2024 20:08
> Worth discussing publicly
> It seems wasteful in terms of code verbosity to make the flows read only

DavidA — 01/02/2024 12:54
> Convention feels better than more code
> Or lint it

**Comment by BrayanDSO** [comment]
> Convention feels better than more code
Or lint it

Fully agreed

**Comment by lukstbit** [comment]
I'm for making the API as read only from outside but with the current state of the code I agree that it would be come quite verbose.
My suggestion is that we close this proposal and wait for [explicit backing fields](https://github.com/Kotlin/KEEP/blob/explicit-backing-fields-re/proposals/explicit-backing-fields.md).

**Pull request closed without merging**
