### PR TITLE
Allow to search for cards with some flag

### LINKED ISSUE #5444: Flag cards feature request
Would be awesome if Ankidroid supports at some point the Flag Cards by colour option found on the desktop version.  Very practical!!!

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description
Anki allows to use flag to search cards, both in Browser and in Filtered deck.
This commit allows to do the same thing.

## Fixes
Fixes #5444

## Approach
Mostly as in Anki (so, sorry Mike, there is a little bit of binary computation).
With the exception that I had to deal with type conversion as in Java and not as in Python. So I decided to simply check whether the string is "0", "1", "2", "3", or "4" using a switch case. This avoid to try a conversion and deal with a potential exception. 

## How Has This Been Tested?

Creating a deck with a due card with flag 2 (on computer, as you still didn't merge my PR related to flags). Creating a filtered deck with search "flag:2". Emptying the deck. Synchronizing from computer onto ankidroid.  Seing that when I build the filtered deck on ankidroid, it find the above mentionned card and nothing else.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Anki-Android_2/Anki-Android_2/pullRequest?prid=4494093&bid=15154609)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Anki-Android/Anki-Android/pullRequest?prid=4494095&bid=15154612)

**Comment by Arthur-Milchior** [comment]
I currently don't see the points of the two identical comments.

**Comment by Arthur-Milchior** [comment]
Can you restart please

**Comment by Arthur-Milchior** [comment]
I should note that PR https://github.com/dae/anki/commit/fe599522ef7735c845cfa15c50bc3b8932ff3403 was accepted. It is already ported in the current PR, as I did not port the bug but directly ported a correct version of the feature

**Comment by mikehardy** [comment]
> I currently don't see the points of the two identical comments.

The point is that Codacy (our auto-linting service) shut down our project previously. Just prior to the original incarnation of our use of their service I re-configured it. Then they re-incarnated the previous version. So there are 2 identical configurations running at the same time. Maybe irritating but better 2 than 0. I'll clean up the other config as I get time, in the meantime as long as there is no deviation between the two it's not a huge priority

**Comment by mikehardy** [comment]
> Can you restart please

emulator hang on API25 noted - not the code-under-test's fault -- restarted

**Comment by mikehardy** [comment]
> > I currently don't see the points of the two identical comments.
> 
> The point is that Codacy (our auto-linting service) shut down our project previously. Just prior to the original incarnation of our use of their service I re-configured it. Then they re-incarnated the previous version. So there are 2 identical configurations running at the same time. Maybe irritating but better 2 than 0. I'll clean up the other config as I get time, in the meantime as long as there is no deviation between the two it's not a huge priority

Found the double more quickly than expected. Duplicate Codacy webhook deleted.

**Pull request merged**
