### PR TITLE
Added marketing images for play store

### LINKED ISSUE #13778: Create more Promotion-worthy images for Play Store listing
Apparently the images we currently have in our Play Store listing are not "Promotion worthy", I believe (based on their note) because they are not 1080px+?

Here are their content guidelines: https://support.google.com/googleplay/android-developer/answer/9866151#screenshots&zippy=%2Cscreenshots

The content is, I think, fine on the current screenshots so I would not over-think re-doing them.

However here are the "Highly Recommended" guidelines for non-game apps, with a max dimension of 3840px as the upper limit to keep in mind:

> Highly recommended
>
> Some sections of Google Play show groups of recommended apps and games in a large format using screenshots. To be eligible for recommendations in formats that use screenshots, the following guidelines are a requirement:
For apps, you must provide at least four screenshots with minimum 1080px resolution. These should be 16:9 for landscape (minimum 1920x1080px) screenshots and 9:16 for portrait screenshots (minimum 1080x1920px).

### PR DESCRIPTION
**Pull request by pproe**
## Purpose / Description

Add some more attractive play store images to increase the likelihood of being featured on Google Play store and keep in line with the play store standards.

## Fixes
#13778 "Apparently the images we currently have in our Play Store listing are not "Promotion worthy", I believe (based on their note) because they are not 1080px+?" 

## Approach

Added some mock up designs of replacement graphics to keep up with the standards of Google play store.

## How Has This Been Tested?

Ran through the google guidelines and think they cover most of the "highly recommended" sections.

https://support.google.com/googleplay/android-developer/answer/9866151#screenshots&zippy=%2Cscreenshots

## Learning (optional, can help others)

Built using Canva, Inkscape & Gimp. Canva is an awesome resource if others are looking to create quick marketing content. 

Colourset used:
- #169adc (Page Backgrounds)
- #f5f6f7 (Off-white text)
- #ffffff (Oval and cloud graphics)
- #29b6f6 (Screenshot annotation text bg)

### CODE REVIEW

**Comment by pproe** [comment]
Please let me know any preferred changes to styling. Also, happy to assist with localization of the text for different markets.

Wasn't sure if it was appropriate to keep the canva template within the repo so I've just added the pngs.

**Comment by BrayanDSO** [comment]
I really like the windows and the overall design.

Particularly, I don't like very much the "Tip: Dark mode spares your eyes" phrase. May not be true in some cases, and even if it did I wouldn't focus on it

And one question: Is that device frame an iPhone one? Looks a lot like one, and this is an Android app.

**Comment by pproe** [comment]
@BrayanDSO Thanks for your feedback, I've made a few changes to the design (colours). I've also changed the phone frame to look a little more android-y (it was the least iphone looking frame Canva has available) and moved the emphasis on the images more towards the core functions (reviewing cards/manging decks). Let me know what you think & if there are any other changes needed.

**Comment by BrayanDSO** [comment]
I'm gonna ask to change the navigation bar color because we updated it on 2.16 (yet to publicly release) to use the same color of the top bar

image

image


image


image

**Comment by user1823** [comment]
The screenshots of the reviewer and the stats are also taken from the old version (2.15.6).

These pages have also been changed on the latest version.

**Comment by pproe** [comment]
Unfortunately I don't have a dev environment set up right now. Would someone (perhaps @BrayanDSO or @user1823) be willing to provide screenshots to replace the stats and reviewer sections?

**Comment by BrayanDSO** [comment]
You can find a new version of the app at https://github.com/ankidroid/Anki-Android/releases

Try installing one of the parallel versions (A, B) to avoid overriding your current installation

**Comment by pproe** [comment]
I've gone ahead and updated the screenshots to version 2.16. 

Here's the link to the Canva: 
https://www.canva.com/design/DAFkBNZXUGQ/c5AfIwVOF4QQG9S9Hx2J2A/edit?utm_content=DAFkBNZXUGQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Couldn't find a better way to share it. If anyone knows, let me know.

**Review by BrayanDSO — APPROVED** [review]
Looks amazing to me. Thanks a lot!

**Review by mikehardy — APPROVED** [review]
These look great to me, thank you!
@BrayanDSO you have marketing change powers in play dashboard now I think - you want to update these? If not they will go in my task queue but I will get to them eventually :-)

**Comment by mikehardy** [comment]
Only assigning to Brayan for an *answer* not the work.
Should maintain "pending merge" status until the images are actually updated in Play console as there is no other way to link that work and I would forget otherwise...after updating on Play console on google's servers, merge here I think?

**Comment by BrayanDSO** [comment]
> Should maintain "pending merge" status until the images are actually updated in Play console as there is no other way to link that work and I would forget otherwise...after updating on Play console on google's servers, merge here I think?

LGTM. If it were me doing the upload, I'd like to keep this PR as a reminder while I haven't done it

**Comment by BrayanDSO** [comment]
> BrayanDSO you have marketing change powers in play dashboard now I think - you want to update these? If not they will go in my task queue but I will get to them eventually :-)

Only read this now. I'll do it. Looks fun

**Comment by BrayanDSO** [comment]
Under Google Play's revision. They should be automatically up in some days

**Comment by mikehardy** [comment]
Oh that's awesome @BrayanDSO ! Thank you for carrying these over there. In my experience the review is actually really fast.

**Comment by BrayanDSO** [comment]
> Oh that's awesome @BrayanDSO ! Thank you for carrying these over there. In my experience the review is actually really fast.

it took only some minutes to get the approval message. Although idk how to see those images in the normal way every people are going to

**Comment by mikehardy** [comment]
Hit the main URL - I see them: https://play.google.com/store/apps/details?id=com.ichi2.anki

image


So I'm going to call this "awesome", which is like "done", but much better. Thanks again @pproe !

**Comment by BrayanDSO** [comment]
Oh, right. I'm seeing the portuguese play store. Probably this will only change after https://github.com/ankidroid/Anki-Android/issues/10091 is done

**Pull request merged**
