### PR TITLE
NF: remove duplicate "help"

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Those strings appear in different context but always means the same thing, so probably should get the same translation

### CODE REVIEW

**Review by david-allison-1 — COMMENTED** [review]
Note: Help is about to be refactored in: https://github.com/ankidroid/Anki-Android/pull/7358

I'm unsure on this one:

"Help/Support" in the main nav bar, and "Get Help" from a dialog could presumably be translated differently

**Review by mikehardy — APPROVED** [review]
I dunno, if they're all translated to Help it seems like they should just be "Help", will collide with your refactor but seems okay as a current atomic unit

**Comment by Arthur-Milchior** [comment]
I don't see the difference between those two meaning of "help". 
If you'd be okay with keeping only two ressources, please let me know what changes to make and the difference. I believe at the very least when there are duplicate we keep, we should add a comment explaining why we keep it

**Review by david-allison-1 — APPROVED** [review]
Ok, no point in bikeshedding on this.

**Pull request merged**
