### PR TITLE
NF: replace tab by spaces

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Due to Kotlin migration it becames important. Indeed, sometime, lines are
identical APPART from those tab/spaces. This will ensure that those lines are
detected are actually identical during migration and will help reviewing the diff.

### CODE REVIEW

**Comment by david-allison-1** [comment]
needs a rebase + de-conflict

**Comment by Akshay0701** [comment]
Arthur, have you done all this changes manually? or is there any script you used to do this changes?
I am asking this because I also wanted to clean up code from my personal project...

**Comment by Arthur-Milchior** [comment]
Rebased.

@Akshay0701 I just used the search and replace feature of android studio. I double checked the git commit to ensure it seems alright

**Comment by Akshay0701** [comment]
oh okay, Thanks!

**Comment by mikehardy** [comment]
Sorry @Arthur-Milchior I didn't see this one or I would have merged it more quickly, it took another confict because ChessFilter moved to Kotlin already I think

**Comment by mikehardy** [comment]
I just rebased this to current, if CI passes I'll merge

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
