### PR TITLE
added version code suffix

### LINKED ISSUE #13101: Add a versionIdSuffix to debug builds and make sure the suffix appears on the debug info
So we can easily detect them on crash reports and GH issues

### PR DESCRIPTION
**Pull request by criticalAY**
## Pull Request template
added version code suffix

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes #13101

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
tested on oneplus nord ce
Screenshot_46

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Can we make it like `2.16alpha92.debug`? The version code is actually a shorthand that is translated to the version name (e.g. `2.16alpha92`), so it is a little reduntant here

**Comment by criticalAY** [comment]
> Can we make it like `2.16alpha92.debug`? The version code is actually a shorthand that is translated to the version name (e.g. `2.16alpha92`), so it is a little reduntant here

Sure!

**Comment by BrayanDSO** [comment]
I think that the appropriate suffix, according to [semver](https://semver.org/#spec-item-10), would be `+debug`, but we probably should discuss that

**Comment by criticalAY** [comment]
> I think that the appropriate suffix, according to [semver](https://semver.org/#spec-item-10), would be `+debug`, but we probably should discuss that

Android doc suggest using "-debug" for the suffix

**Comment by criticalAY** [comment]
The official docs suggest that we should use `.debug` for `applicationIdSuffix` and `-debug` for versionNameSuffix

**Comment by BrayanDSO** [comment]
> Android doc suggest using "-debug" for the suffix

Nice. Let's go with it then

**Comment by criticalAY** [comment]
> > Android doc suggest using "-debug" for the suffix
> 
> Nice. Let's go with it then

Done!

**Review by BrayanDSO — APPROVED** [review]

**Review by lukstbit — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
