### PR TITLE
[Kotlin Migration] AudioField

### PR DESCRIPTION
**Pull request by Akshay0701**

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
```
> Task :AnkiDroid:compilePlayReleaseKotlin FAILED
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioClipField.kt: (25, 29): Return type of 'getName' is not a subtype of the return type of the overridden member 'public abstract fun getName(): String defined in com.ichi2.anki.multimediacard.fields.AudioField'
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioRecordingField.kt: (26, 16): Type mismatch: inferred type is String? but String was expected
```

**Comment by Akshay0701** [comment]
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt:31: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
    protected var mName: String? = null
```
should I rename this to "name1" or kotlinclean("rename") would work?

**Comment by david-allison-1** [comment]
> ```
> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt:31: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki.lint]
>     protected var mName: String? = null
> ```
> 
> should I rename this to "name1" or kotlinclean("rename") would work?

`currentName` - `Cleanup` as we probably want `name` to be a property in the interface rather than a getter/setter

**Review by david-allison-1 — APPROVED** [review]
Second reviewer: a few changes were made out of necessity

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
