### PR TITLE
update: Replace string "Add Note" by "Add" at multiple places

### LINKED ISSUE #11861: Replace "Add note" by "Add"
So, here are the places where `Add Note` is used:

- One of the 3 app shortcuts
- NoteEditor
- FAB
- Gestures selection
- Reviewer menu

Following @brayanDSO analysis, we want to keep the string in Gesture and reviewer menu, and change the other ones. 

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/issues/10853#issuecomment-1112735559_ 

After two months, I assume original author @Shane-Patrick-Roach won't finish it. I don't think it's worth to use the original PR, given that it's a single line and we won't keep it. However, it may still be polite to credit it, as this author bringed the original idea to us.

### PR DESCRIPTION
**Pull request by oyeraghib**
## Purpose / Description
Replace "Add Note" by "Add" at multiple places as discussed in #10853 

## Fixes
Fixes #11861 
Closes #10853

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Thanks a lot

Could you change the comment on this string
Right now it indicates 
> A generic add button - Main Deck Picker and card templates

And I believe that you should remove the enumeration of places it's use. If I merged your PR as is, this enumeration would become incomplete. Since we don't need it to be complete, we can just remove the list

**Comment by oyeraghib** [comment]
> Thanks a lot
> 
> Could you change the comment on this string Right now it indicates
> 
> > A generic add button - Main Deck Picker and card templates
> 
> And I believe that you should remove the enumeration of places it's use. If I merged your PR as is, this enumeration would become incomplete. Since we don't need it to be complete, we can just remove the list

I have done that in a different commit. Should I squash them into one or is it fine ?

**Comment by Arthur-Milchior** [comment]
I can squash it at the end, no worry here. I love a beautiful history when there is a complex PR with multiple steps. Here, it's no big deal.  Thanks a lot for doing it yourself.

However, I fear I was not clear, I'm sorry for it.
I wanted you to update the comment to reflect the new state of the string. I certainly did not want you to entirely remove the comment. I was just asking to remove the enumeration "Main Deck Picker and card templates". 

Our linter would not accept your change here, because we add three different string "add" depending on the context (I do not know whether there are languages where they are actually translated by different word. But I can easily imagine that in some languages, "add" will need to be different depending on what is added)

**Comment by oyeraghib** [comment]
Thanks for explaining so well. I have updated the changes.

**Review by mikehardy — APPROVED** [review]
This looks good to me and seems to follow what was discussed in the related issue. Thank you!

**Comment by mikehardy** [comment]
Maintainers note: I marked this one with a "strings" label and "pending merge" instead of merging *on purpose* I want to finish getting strings that are real translations up to date before I merge this and get a bunch of automated noise in the i18n sync diff. Please don't merge until I've got #11854 merged (and then even another one to get from July 14-18 in...)

Then this should merge followed by a final sync that is just automated changes queued up as PRs with strings labels

Thanks!

**Pull request merged**
