### PR TITLE
migrate gradle to build-logic / composite build  module to share

### PR DESCRIPTION
**Pull request by AbdelrahmanEsam**
what I have done in this pr is 
1- migrate the application gradle script to gradle (build-logic) module
2- divide our big application build script to many kotlin extension functions for readability and maintenance

with comming prs I will migrate more .

### CODE REVIEW

**Comment by AbdelrahmanEsam** [comment]
@lukstbit

**Comment by lukstbit** [comment]
As I said in your previous PR I think we can use conventional plugins for some of our build code but your proposed changes go too far and they are out of scope. My thoughts were about using conventional plugins for packaging some of our current code that is clearly used multiple times:

- the subproject block from the root build file -> gradle recommends using a conventional plugin instead of the subprojects block
- the configuration code from robolectricDownloader.gradle
- the configuration code from jacoco.gradle
- the configuration code from lint.gradle

Related to code structure, as I said we need multiple commits for each change: One commit to create the new build-logic module structure(for example see the PR about the new common module) and then one commit for each of the change above(for example one commit for extracting the lint configuration). These commits should be independent so they can be reverted if needed without the need to revert everything. Please, also use proper commit messages.

Once we decide and follow up with a module structure we can look into extracting more if needed.

> 2- divide our big application build script to many kotlin extension functions for readability and maintenance

I would argue that this is not achieved by your changes. For example, with the current :AnkiDroid build file it is very easy to follow the build logic, while with your changes there are too many indirection before I would get to what I want to see.

**Comment by AbdelrahmanEsam** [comment]
@lukstbit  well for the first point  you can use convention plugins for all your gradle build  why not ? even in the now in android google sample they did that and I have discussed that with person from the google team  why you think it's not a good idea ? you well write your build as code rather than scripts I think this is so good .... when we do that  we  will be able to share build logic between other modules too and subproject (as my next step) 
for the second point about multiple commits now unlike the previous pr I didn't migrate any other scripts .... only the build.gradle of the main application ..... if you want to break this commit  to multiple  too ... please clearify your strategy about that .

**Comment by lukstbit** [comment]
> even in the now in android google sample they did that and I have discussed that with person from the google team why you think it's not a good idea ?

As you also mentioned, "Now in android" is a showcase project. They are using everything(architecture, di, multi module, benchmarking, baseline profiles etc) and have created an entire build infrastructure around/for this. They also have about a dozen google engineers regularly contributing to the app. We don't need/have this complexity in our app.

> you well write your build as code rather than scripts I think this is so good 

We have already written most build code that we need, now the focus is on reading it which is harder with your changes. We are also mostly using kotlin dsl which helps when writing new code.

> when we do that we will be able to share build logic between other modules too and subproject (as my next step)

This is premature as we don't have the module structure that we want yet. 

> only the build.gradle of the main application

I've mentioned above that this is not something that we want. I mentioned above the files which would benefit from being moved to conventional plugins.

**Comment by AbdelrahmanEsam** [comment]
ok thanks for your response I will close it .

**Pull request closed without merging**
