### PR TITLE
Mathjax flicker

### LINKED ISSUE #5384: Screen flickers/refreshes when a card changes
Hello,

I have a problem with flickering/refreshing every time new card shows. It doesn't happen on the desktop version of Anki. I don't know really why. Could it be due to the card template? I'm attaching gifs to show what I'm talking about.
Ankidroid 2.9.80a

edit. Stable version 2.8.4 has no such problem.

### PR DESCRIPTION
**Pull request by adamwolf**
## Purpose / Description
 Anki-Android adds mathjax-needs-to-render as a class to the card when it detects both \( and \) or \[ and \].

This does not control *loading* MathJax, but rather controls whether or not MathJax renders content. We hide all the content until MathJax renders, because otherwise the content loads, and has to reflow after MathJax renders, and it's unsightly.  However, if we hide all the content every time, folks don't like the repainting after every question or answer.  This is a middle ground, where there is no repainting due to MathJax on non-MathJax cards, and on MathJax cards, there is a small flicker, but there's no reflowing because the content only shows after MathJax has rendered.

I think if we reworked how the pages are loaded so that answers are "revealed" we could eliminate one more flicker, but I personally want to get 2.9 out first before thinking about that too much more :)

QUESTION:  I would like to test the actual generated output of the card, so I can test that the class is inserted when textContainsMathjax regardless of question or answer. Is there a good way to do that?  Do we want to refactor updateCard so it calls methods that generate the html, and then test those?

## Fixes
This *should* fix #5384.

## Approach
I added a new method, textContainsMathjax.

## How Has This Been Tested?

Ran the emulator tests, and tested on my device.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
I think you want this: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection  (which is to say, with a device connected you'll get a card.html on the filesystem you can look at, or you can attach the chrome devtools to the webview running on the emulator)

But I think you are talking about a unit test instead of visual inspection? For that I am not sure - may need some refactor yes. I don't mind that but it helps me a lot during review if commits are separate by "non-functional refactor" and "functional changes" so that I can follow things through

As for the solution itself, it seems sensible, but I haven't checked it myself visually - I don't use MathJax or heavy fonts or anything so I've never been a flicker-sensitive user but I do understand those that are

**Comment by adamwolf** [comment]
Oh, I use that Chrome remote debugger a lot! It was critical to get
Mathjax working.  I was talking about unit tests.

I think this does the trick to fix the flicker like we had discussed,
but it (eventually?) could use an automated test to test to make sure
the generated html output contains the appropriate classes.

Let me know what you all think.

**Comment by timrae** [comment]
Can you please revert your merge commit, and instead rebase onto master? We basically do not accept merge commit in PRs for this project, as I like to have a linear revision history. Also, most of the CI builds were failing, it seemed to have been timing out during unit test execution. I've restarted them so let's see, maybe it's just a travis problem.

**Comment by adamwolf** [comment]
Will do.  Sorry about that.  The tests passed here, but I only tested on
one SDK.

**Comment by timrae** [comment]
Thank you!!

**Comment by adamwolf** [comment]
I think I undid and redid the merge/rebase like you want.  Let me know if it needs further adjustment.

I am hesitant to do a refactor of the card presentation this close to release.  I added an issue for myself to add an automated test for the class itself.

**Pull request merged**
