### PR TITLE
build(ci): remove `IN_PROCESS` compiler execution strategy

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description

Added in f5ecb05efc3117238cbd42935542176d4436ee5f
Related: 655516582cbee7dffb70a3be6318103731f9b9a0

but CI runners now have 16GB RAM, so this is not necessary any more

## Fixes
* Part of #15368
* Reverts change added in https://github.com/ankidroid/Anki-Android/pull/11341
    *  https://github.com/ankidroid/Anki-Android/commit/f5ecb05efc3117238cbd42935542176d4436ee5f 

## Learning (optional, can help others)

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

> discovered you can eliminate the standalone (multi-gigabyte, persists after compile) kotlin compiler daemon by having it run in process, and just ensuring main process is sufficient (it is, determined by GC logging). I think this might be the final set, allowing for a build/lint run that's about 
> 
> - 2.5GB total for the JVM and a compile/lint
> - about 1.5GB*workers max, or 
> - total 5.5GB max in CI
> 
> https://github.com/ankidroid/Anki-Android/pull/11341/commits/97ac61197a3ab703ba110225665a582bc6f99a4e
> 
> Previous config was 
> - 7GB for compile/lint
> - about 1.5GB*workers
> - total 10GB maxin CI
> 
> No wonder windows blew up with 7.5GB ram + 1.5GB swap default, and adding swap made it work but in suffer mode.
> 
> This should be noticeable as less memory pressure on development machines as well, I had begun to notice it using up too much RAM on my machine even

* https://github.com/ankidroid/Anki-Android/pull/11341#issuecomment-1129119319

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
We may want to see if this improvement is still useful with M1 runners, as the RAM is reduced to 7GB

**Comment by david-allison** [comment]
8m19 (ubuntu): https://github.com/ankidroid/Anki-Android/actions/runs/7720840711/job/21046386915?pr=15369
13m5 (windows): https://github.com/ankidroid/Anki-Android/actions/runs/7720840711/job/21046387160?pr=15369

**Comment by mikehardy** [comment]
I think for the performance statistics (and the "correctness" - that is, whether it would even trigger an OOM type condition on the machine) to be representative here it has to be the uncached gradle state

Either a temporary workflow modification such that gradle cache is ignored or keyed wrong-on-purpose so restore fails, or purging the cache on workflows while testing

**Review by ShridharGoel — APPROVED** [review]

**Comment by mikehardy** [comment]
I needed to close/reopen in order to get the new unit test names run so that branch protection rules were satisfied but I also had an eye on performance. 13mins that time in the cached scenario for windows.

This time last close/reopen was (also primarily to get the unit test requirements vs new names lined up for 2nd time), but I took the opportunity to purge the caches for linux and windows (which are in the CI branch this affects) so they'll be under maximum fresh-compile memory pressure.

Hypothesis is they'll pass, then as long as the unit test runs are under 20mins I think that's pretty good for the uncached case. I'm guessing they'll come in between 15-18mins for windows / linux with cold cache

**Comment by mikehardy** [comment]
11mins (linux) and 15 (windows) in the cold cache state, and without crashing despite max memory pressure.
I'm going to call that a win.

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
