### PR TITLE
Set minimum height for cards in Card Browser

### LINKED ISSUE #11690: Small tap targets for single-line cards
Single-line cards offer much smaller tap targets than multiline cards.

Specifically, the student feels the tap targets are too small to reliably prevent user error when selecting single-line cards.

image

## Relevant heuristic

 [Error prevention](https://www.nngroup.com/articles/slips)

"Prevent unconscious errors by offering suggestions, utilizing constraints, and being flexible."

## Student's severity classification (minor, major, critical)

Minor, due to:

1. **Frequency**: "The frequency of this issue depends on the type of content the user is studying. If the user studies predominantly cards with large amounts of information, then it will rarely occur, but if they are studying cards that tend to only be one line of content, then it can happen quite frequently."

2. **Impact**: "This issue is moderately easy to overcome since the user can simply go back to tap the correct card, but it takes a few extra seconds each time they make an error (or if they are trying to be extra careful to tap the correct card), which can add up in terms of frustration."

3. **Persistence**: "This problem can be more permanently overcome if the user changes the font size in the setting, but since the default font size is so small and the user may not be aware that changing font size is an option, this can be a persisting issue."

4. **Weighting**: "Though this is an issue that can be overcome by changing the settings or mitigated by going back after tapping the wrong card, the fact that the problem arises due to default settings means that the user may not know about the alternate options. Therefore, it is frustrating enough that it is deserving of a severity of two."

This issues comes from [Source file](https://1sfu-my.sharepoint.com/personal/paulh_sfu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team%2Fheuristic%2Deval%2Dexemplary%2D4%2Epdf&parent=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team&ga=1) as discussed in #11664. *Text not wrapped in quotation marks is rewritten for brevity.*

### PR DESCRIPTION
**Pull request by viciousAegis**
## Purpose / Description
Fix the minimum size of a card to adhere to Material guidelines

## Fixes
Fixes #11690 

## Approach
set the minimum lines to 3 for the Card Browser columns

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
My immediate reaction is that they should be centered vertically

My second immediate reaction is "existing users are going to want an option to turn on a compact view" **however** I think our general stance of "we do our best to follow material guidelines and adhere to accessibility standards" is a solid defense here and is enough for me to say 48x48 touch target is minimum 

My third immediate reaction is gratitude that you have taken the time and posted this :-) - it should be first really

**Comment by BrayanDSO** [comment]
How does this look if someone changes the card browser font size to 200%?

**Comment by mikehardy** [comment]
> How does this look if someone changes the card browser font size to 200%? 3 lines as minimum may take a lot of space

great point, perhaps it is a minimum size *but* if the text is sufficiently big it should not get the padding (or however it is implemented)? No idea if that is technically possible

**Comment by BrayanDSO** [comment]
> > How does this look if someone changes the card browser font size to 200%? 3 lines as minimum may take a lot of space
> 
> great point, perhaps it is a minimum size _but_ if the text is sufficiently big it should not get the padding (or however it is implemented)? No idea if that is technically possible

`android:minHeight` should work, but I haven't tried.

**Comment by lukstbit** [comment]
`android:minHeight` should work coupled with the value one of the ?attr/listItemPreffered* theme attributes.

**Comment by viciousAegis** [comment]
This is how it looks with `minHeight` set to 48dp at 200% font scaling 
image

Is there a way to only center some cards vertically? For example, centering every card vertically would lead to this:
image

So, if we want to go for vertically centered cards, we only need to center the ones whose height is less than the` minHeight`. Is that possible?

**Comment by Arthur-Milchior** [comment]
To answer your question. The view is a JVM object as any other, you can do anything you want to those objects if the API allows it. I'm pretty sure that you can:
* check if the size is exactly the size you setted
* if so, change the both vertical alignments

I don't expect it to slow down browser that much, but still, would be nice to check it since it's suddenly adding logic. 

If you want to try, feel free to do it. But I'm not certain that it will actually be an improvement. So don't spend too much time on it unless another people agree with your choice (my opinion is weak)

**Comment by BrayanDSO** [comment]
I'd keep the PR for only the cards height size (with minHeight, not minLines) and discuss the other topics in separate issues.

Especially because I think there are planned changes for the cards view on your GSoC project, so the context may change a lot along or after your changes

**Comment by mikehardy** [comment]
No pressure, just curious for status + intention on this one? Is the goal to finish this up and merge? It appears to have a test regression if so

**Comment by viciousAegis** [comment]
I'm not sure if the goal is to merge at all at this point. This issue is directly related to my plans for my GSoC project, so cannot comment on it until other related details are clearer. I'll mark this off as a draft for now and see what the plans are in a couple weeks

**Pull request closed without merging**
