### PR TITLE
Fix bug around restoring InsertFieldDialog

### LINKED ISSUE #9811: [Bug] Crash: InsertFieldDialog - Don't Keep Activities
###### Reproduction Steps

1. Android Developer Settings - Enable "Don't keep Activities"
2. Deck Picker - Manage Note Types - Long Press a type - Cards
3. Long press - Insert Field
4. Minimise app
5. Maximise app

###### Expected Result

No Crash

###### Actual Result

```
2021-11-07 21:03:26.381 16777-16777/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 16777
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardTemplateEditor}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.ichi2.anki.dialogs.InsertFieldDialog: could not find Fragment constructor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.ichi2.anki.dialogs.InsertFieldDialog: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
        at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:320)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
        at com.ichi2.anki.AnkiActivity.onCreate(AnkiActivity.java:97)
        at com.ichi2.anki.CardTemplateEditor.onCreate(CardTemplateEditor.java:136)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.NoSuchMethodException: com.ichi2.anki.dialogs.InsertFieldDialog.<init> []
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getConstructor(Class.java:1728)
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483) 
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85) 
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728) 
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198) 
        at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149) 
        at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99) 
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:320) 
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273) 
        at com.ichi2.anki.AnkiActivity.onCreate(AnkiActivity.java:97) 
        at com.ichi2.anki.CardTemplateEditor.onCreate(CardTemplateEditor.java:136) 
        at android.app.Activity.performCreate(Activity.java:7994) 
        at android.app.Activity.performCreate(Activity.java:7978) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

###### Debug info
Latest alpha - e00531ed75169932f4eec5f047f626aaf42ae791 - branched off, but with no relevant changes

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

This PR fixes the bug where this dialog would crash when coming back to the activity(which was recreated while in the background). I removed the problematic listener from the dialog and replaced with the newer API `setFragmentResultListener/setFragmentResult`(which also made the fragment factory useless).

As a side note, during the migration a recursive call(in CardTemplateEditor.showInsertFieldDialog()) was introduced which made CardTemplateEditor to fail completely when trying to insert a field. This PR also fixes this issue.

## Fixes

Fixes #9811

## How Has This Been Tested?

Ran the usual tests.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Lovely stuff. Thanks! LGTM

One request: could you add a `@NeedsTest("explanation")` on the method/functionality which was broken

**Comment by lukstbit** [comment]
@david-allison I don't think we need a @ NeedTest. Basically, during the migration to kotlin some code was added to match he java API which produced a recursive call. My code removed the problematic code and everything is ok now. 

My comment was more about that we need serious testing after the migration to kotlin.

**Comment by mikehardy** [comment]
> My comment was more about that we need serious testing after the migration to kotlin.

but...that's exactly what a test is for? so that odd regressions (in the future, not just on kotlin migration) are caught? crash bugs in particular

Doesn't cost anything to add the annotation, and perhaps for GSoC 2023 it becomes a good task for a candidate (that's one of the points of adding NeedsTest annotations, so we have a stock of good tests to add, especially ones that might cause a crash...)

**Comment by lukstbit** [comment]
As requested, I've added the @ NeedTest annotation.
@mikehardy When is the new(stable) version of the app set to be released?

**Comment by mikehardy** [comment]
Thank you!
As soon as #5304 is resolved - that is "scoped storage migration" must be completed so that we are compliant with Google Play Store policies which require API30 as minSdkVersion and which then mean we have to handle API30 correctly (which is "scoped storage", for us)

**Comment by Akshay0701** [comment]
I missed this bug while writing InsertFieldDialog, Thanks!

**Pull request merged**
