### PR TITLE
NF: run most unit tests in foreground

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
As requested by @mikehardy on https://github.com/ankidroid/Anki-Android/pull/7005#pullrequestreview-627234122

Some tests break, I don't yet understand why, even if I send them back to background.

Which at least prove that I was right, it won't be a trivial change and I'm happy the previous change was merged first before considering why those tests are harder

### CODE REVIEW

**Comment by mikehardy** [comment]
I'll admit I'm surprised, +1 for your foresight

**Comment by Arthur-Milchior** [comment]
Very little foresight here. I already tried this last summer and already had similar problem. I don't recall whether they were resolved, but I know at that time @david-allison-1 was opposed to this idea anyway, since it makes test further away from real life usage of those methods

**Comment by david-allison-1** [comment]
We're not going to pick up race conditions with these tests... but moving to GitHub's made our tests extremely flaky (~50% of builds are failures, I'd say), and it means our new contributors can't trust the CI output.

Gains:

* No more flaky builds
* Speed

Loess:

* Regression cover for some race conditions between UI and the background task

**Comment by mikehardy** [comment]
Getting cover on race conditions is/was always uncertain and I don't recall us actually having fixes related to same coming from CI?

Test flakiness is a daily grind that impacts productivity for everyone all the time

I'm all-in on having CI either succeed or fail reliably every time

If we need to probe race conditions we need to do so systematically, not incidentally I think - I'm not sure how to do that exactly but if it is a thing that has value it shouldn't be incidental

**Comment by david-allison-1** [comment]
@Arthur-Milchior I'd like to come up with a plan to get through this, ideally focusing on the currently flaky tests

**Comment by Arthur-Milchior** [comment]
My best guess is that we should have a way to let the `before` function know that exceptionnaly, it should not move things to foreground and keep them in background. 
I would have hoped there may be a way to do it with annotation; to have an annotation on a test that allow to switch a variable even before `Before` is executed. However I can't figure out how to do it; I don't even know if it's possible, Junit website seems very badly documented (just a bunch of link to wiki on github), and I don't even understand how annotations can have any impact on the code workflow. 

If there is no otherway around, I guess I'll just have to split the class in two, and run the broken test in a special class where Before do not move the manager to foreground

**Comment by david-allison-1** [comment]
> My best guess is that we should have a way to let the `before` function know that exceptionnaly, it should not move things to foreground and keep them in background.
> I would have hoped there may be a way to do it with annotation; to have an annotation on a test that allow to switch a variable even before `Before` is executed. However I can't figure out how to do it; I don't even know if it's possible, Junit website seems very badly documented (just a bunch of link to wiki on github), and I don't even understand how annotations can have any impact on the code workflow.
> 
> If there is no otherway around, I guess I'll just have to split the class in two, and run the broken test in a special class where Before do not move the manager to foreground

What's the problem at the moment (why does `@Before` need to be run in the background, what's the exception)? 

I'm fairly confident that what you're after is possible, but it feels important to know why we need it

**Comment by Arthur-Milchior** [comment]
One of the exception I got was
> Caused by: java.lang.NullPointerException
	at com.ichi2.anki.dialogs.RecursivePictureMenuTest.clickChildAtIndex(RecursivePictureMenuTest.java:125)
	at com.ichi2.anki.dialogs.RecursivePictureMenuTest.testSelectingHeader(RecursivePictureMenuTest.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	... 6 more

you can look at other in the run.


I clearly have no idea what is exactly the problem. I just now that when setup is executed in foreground, testSelectingHeader fails, whether it is executed in back or foreground, while if the setup is executed in background, then testSelectingHeader succeed. So I want to be able to execute it in foreground. The most natural way to do it being to give a parameter before `set_up` is exectued

**Comment by david-allison-1** [comment]
Can we add a method to `RobolectricTest` which defines the scheduler type for the class, or a custom runner which will handle this via annotations?

We can then add a larger issue and incrementally fix the issues

**Comment by Arthur-Milchior** [comment]
Recreated. I had to split RobolectricTest in Background and Foreground and split some test classes in two. That's not ideal, maybe can be improved, but it works. And on my computer, the unit test time decreased from 7 minutes 52 seconds to 2 minutes 28 seconds which makes me willing to accept a code that is not as beautiful as I would hope just to be done with this overlong test time

**Comment by david-allison-1** [comment]
RE: Speedup - Not surprising, `sleep()` is evil, but it's great to get this over the finish line.

I'm looking through the commits and don't understand why delegates have been introduced, and the Robolectric class has been split into two.

I'm fairly sure there's going to be better ways of handling this, but I don't understand the thought process to get here.

**Comment by Arthur-Milchior** [comment]
I had to split some test classes in two, one for foreground and one for background. In order to avoid code duplication, I put the code in common in a delegate class, that is used by both new classes.
Since java do not have multiple inheritance, it seems I could not just create a AbstractCardBrowserTest class and then inherit from it. Indeed, I had to ensure that the CardBrowserBackgroundTest inherits from RobolectrictBackgroundTest and similarly for Foreground.

Since I need to choose between Background and Foreground before I run `@Before`, the only way I found was to inherit RobolectricTest, and override the setup method to put some test in foreground or background. This mean that I had to ensure that each test classes inherit a version of Robolectric that explicitly runs either in foreground or background

**Comment by david-allison-1** [comment]
What's stopping us from having an overridable method that we call in `setUp()` such as we're doing with:

`        DB.setSqliteOpenHelperFactory(getHelperFactory());`


For example:

```java
if (this.useForegroundTasks()) {
        runTasksInForeground();
} else {
        runTasksInBackground(); // legacy implementation
}
```

**Comment by Arthur-Milchior** [comment]
We can do it this way. Add an extra method instead of overriding. It makes absolutely no difference and I don't know why we would consider one to be better than the other. In any case, it would not change the fact that we need two distinct classes for foreground and background, and so split the tests classes between foreground part and background part and hence have a way to avoid code duplication

**Comment by david-allison-1** [comment]
Oh, the issue's that certain methods need to be run in the foreground and it's not acceptable to split by class?

We should be able to do this in a clean manner by extending `AndroidJUnit4`, and adding a "background" annotation to the tests which require the background scheduler.

**Comment by Arthur-Milchior** [comment]
The issue is that some tests need to be run in background. If they run in foreground, or even if some part of the setup run in foreground, then the test fail. I do not know why.

there are no tests that need to be run in foreground. However, I wanted to run as many test as possible in foreground so that we don't loose time. While I could have applied the rules that "as soon as a class has a test that needs to be run in background, all other tests are also run in background", I don't think it would have been a good idea. It would just slow everything down.

If you have any idea how to ensure that setup check whether the test run as an annotation present, then it could totally work. I've no idea how to do that. Please feel free to modify this code if you see a better way to do it

**Comment by Arthur-Milchior** [comment]
That's strange. I don't know why tests work on my computer and not on github.
`testDeleteTemplate` works on my computer if you run it in the whole test set, not if you run it individually

**Comment by mikehardy** [comment]
> The issue is that some tests need to be run in background. If they run in foreground, or even if some part of the setup run in foreground, then the test fail. I do not know why.

This understanding will be the central aspect of any change like this decreasing flakiness instead of increasing flakiness

Flakiness over time will be more expensive then performance gains

**Comment by Arthur-Milchior** [comment]
> This understanding will be the central aspect of any change like this decreasing flakiness instead of increasing flakiness
> 
> Flakiness over time will be more expensive then performance gains

I don't disagree. But it will be the job for another PR. 
If this PR were to increase flakyness, I want it to be rejected. If it improves tests, I still want it to be considered, even if another PR will in the future make even bigger improvement.

As a side note, as a developper, it will simply be far easier for me to run test regularly once I know that it will freeze my computer for 3 minutes instead of 8. I fear it is still painful to have the computer unusable during three minutes, but it is more acceptable

**Comment by david-allison-1** [comment]
> If you have any idea how to ensure that setup check whether the test run as an annotation present, then it could totally work. I've no idea how to do that. Please feel free to modify this code if you see a better way to do it

Please cherry-pick my two commits as you see fit: https://github.com/david-allison-1/Anki-Android/commits/8442-test-background

**Comment by Arthur-Milchior** [comment]
I don't get it. If your two commits do the work, why should I cherry-pick them? Just make a PR from scratch and we'll close this PR.
Yours is quite simpler. Mine became useless.
I would just require more javadoc/commit comment, because I have no idea how it works (but, it's usually the case with most of Robolectric. I didn't find the documentation very easy to grasp)

**Comment by mikehardy** [comment]
#9203 is definitely a cleaner solution - I can get behind that one - I think David wants your review there but it looks good to me

**Pull request closed without merging**
