### PR TITLE
kotlin cleanup : CheckBoxTriState.kt

### PR DESCRIPTION
**Pull request by UvrajSB**
## Fixes
Fixes part of #10489  

## How Has This Been Tested?
My physical device: Realme 8i

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Blocked on https://github.com/ankidroid/Anki-Android/pull/10966

**Comment by mikehardy** [comment]
Unblocked! :-)

**Comment by david-allison** [comment]
needs a de-conflict

**Review by mikehardy — APPROVED** [review]
LGTM

**Comment by mikehardy** [comment]
@david-allison - squash-merge is possible here ?

**Review by david-allison — CHANGES_REQUESTED** [review]
The ordering of functions in the file has been changed which makes this diff much harder to follow. This should be fixed to help future reviewers

**Comment by UvrajSB** [comment]
> The ordering of functions in the file has been changed which makes this diff much harder to follow. This should be fixed to help future reviewers

I changed the ordering because of  `@KotlinCleanup("move setter function here")` 
My interpretation was all the setter functions which were `setChecked` and `setOnCheckedChangeListener` are required to be placed below the cleanup annotation.

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
Throwing this one back to @mikehardy for a final check

**Pull request merged**
