### PR TITLE
Fix `<object>` loading with JS

### LINKED ISSUE #15863: [BUG]: SVG CSS update via JS incorrect rendering.
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

I have an svg file, and a simple template that updates the SVG style using Javascript.

```xml
<svg version="1.1" width="162px" height="120" xmlns="http://www.w3.org/2000/svg" id="keyboard" class="keyboard">

<style>
  path {
    stroke: #2c2c2c;
  }
  .white_key {
    fill:white;
  }

  .black_key {
    fill: #2c2c2c;
  }
</style>

<symbol id="white_key_path" width="23" height="120" >
  <path d="M0 0 h23 v115 q0 5 -5 5 h-13 q-5 0 -5 -5 v-115" fill="inherit" />
</symbol>
<symbol width="13" height="80">
  <path id="black_key_path" d="M0 0 h13 v77 q0 3 -3 3 h-7 q-3 0 -3 -3 v-77" fill="inherit" />
</symbol>
<!-- White keys  -->
<g class="white_key">
<use href="#white_key_path" class="note_C" x="0"  />
<use href="#white_key_path" class="note_D" x="23" />
<use href="#white_key_path" class="note_E" x="46" />
<use href="#white_key_path" class="note_F" x="69" />
<use href="#white_key_path" class="note_G" x="92" />
<use href="#white_key_path" class="note_A" x="115" />
<use href="#white_key_path" class="note_B" x="138" />
</g>
<!-- Black keys (overlap with the white keys) -->
<g class="black_key">
<use href="#black_key_path" class="note_Csharp" x="14.333333" />
<use href="#black_key_path" class="note_Dsharp" x="41.66666" />
<use href="#black_key_path" class="note_Fsharp" x="82.25" />
<use href="#black_key_path" class="note_Gsharp" x="108.25" />
<use href="#black_key_path" class="note_Asharp" x="134.75" />
</g>
</svg>
```

```html
<div class="vexbox">
  <h3> Key? </h3>
	<object id="keyboard_obj" type="image/svg+xml" data="_keyboard.svg" onload="changeRectColor()">
  </object>
</div>

<h2 class="answer" id="answer_key" >
{{English}}
</h2>

<script>
function changeRectColor() {
  var img_obj = document.getElementById("keyboard_obj");
  var notes = img_obj.contentDocument.querySelectorAll(".note_{{English}}");
  notes.forEach( (note) => { note.style.fill = "#98ff98"; } );
}
</script>
```

### Expected behaviour

Anki Desktop: 
image

### Actual behaviour

But the CSS modifications from JS don't work on AnkiDroid:

image

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 4a

Hardware = sunfish

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 4a Build/TQ3A.230805.001.S1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

ACRA UUID = c023d340-ad1e-45d7-bbe3-fab43e49f220

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Not sure where to start with debugging this. Pretty new to JS coding, and I don't see anything obvious here that would break the script.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description

See https://github.com/ankidroid/Anki-Android/issues/15863#issuecomment-1992190692 for more context

## Fixes
* Fixes #15863

## Approach
This is intended to be a quick fix, since the ideal solution would be the proposed at https://github.com/ankidroid/Anki-Android/issues/15863#issuecomment-1992190692. Given the fact that the negative impact here should be fairly low, this should be good to go.

the rest of the approach is in the commits

## How Has This Been Tested?

API 31 emulator, tested with the notetype of #15863

## Learning (optional, can help others)

I tried to take a look into Android's webview source code, and that is hugely huge

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
it may take some time before I answer, so push any changes if required

**Review by david-allison — APPROVED** [review]
Approving with the assumption that this goes into 2.17.

We'll want a more general fix for 2.18

**Comment by BrayanDSO** [comment]
> Approving with the assumption that this goes into 2.17.
> 
> We'll want a more general fix for 2.18

yeah, that's the goal

**Review by lukstbit — APPROVED** [review]

**Comment by mikehardy** [comment]
I wasn't able to cherry-pick this cleanly to the release-2.17 branch, the underlying files have diverged in non-obvious ways - may be possible with some thought +  manual intervention

**Comment by david-allison** [comment]
@mikehardy if you want this resolved in 2.17.7, could you pull it out into a separate issue and I'll get it resolved

**Pull request merged**
