### PR TITLE
Card Browser: Improve "Search Deck" UX

### LINKED ISSUE #8276: Implement Search Deck Function In Add Note Activity
## Problem
With Current Spinner in add note activity user can select any deck , but
->If number of decks is very big it will be hard for user to search particular deck in spinner ,

## Solution
->We can implement search option for user to find any particular deck to select in add note activity.
(the only thing i am unsure about is searching for sub-deck which is present under parent deck).

Work done till now:
I will keep this section updated with work done in this issue ,so that admins don't need to read for all conversions again.

Prototype of search deck design in add note
Capture

Note : I am not started working on this yet,i wanted to make sure that what admins thinks , whether this will be feasible for 
          user or not ?In my opinion, it will show large number list in more neat way and it will also save user time to search 
          deck.

### PR DESCRIPTION
**Pull request by Akshay0701**
## Need
With Current Spinner in card browser activity, user can select any deck, but
->If number of decks is very big it will be hard for the user to search a particular deck in the spinner.
->Anki-desktop does have search decks feature in browser activity.

## Work done till now:
1 Used `DeckSelectionDialog` class to implement search dialog.

## Output Pervious And Current
---->

### CODE REVIEW

**Comment by david-allison-1** [comment]
```
com.ichi2.anki.CardBrowserTest > browserDoesNotFailWhenSelectingANonExistingCard FAILED
    java.lang.AssertionError: 
    Expected: <5L>
         but: was <10L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.ichi2.anki.CardBrowserTest.browserDoesNotFailWhenSelectingANonExistingCard(CardBrowserTest.java:145)
```

**Comment by david-allison-1** [comment]
Just to note: love this, thanks!

**Comment by Akshay0701** [comment]
@david-allison-1 

> java.lang.AssertionError: 
Expected: <5L>
     but: was <10L>
Expected :<5L>
Actual   :<10L>

didn't understand why cardWord() return 10 instead of 5

**Comment by david-allison-1** [comment]
@Akshay0701 I don't know right now, try using a debugger. If it doesn't work, let me know and I'll investigate

Could be a code problem. Could be a test problem.

To be honest, the code looks good, so I'd guess it's a test problem

**Comment by Akshay0701** [comment]
i debuged after CardBrowser browser = getBrowserWithNotes(6); it should create 0-5 cards but its creating 0-12 and at point of deleteCardAtPosition(browser, 0); its value changed to 10 , 
its cant be test issue because I tried debugged with master branch and its creating 6 cards only  
i suspect its my code problem

**Comment by Akshay0701** [comment]
I think i got where problem is , when I replaced onTouch method with pervious methods then it work fine

**Comment by david-allison-1** [comment]
Likely blocked on https://github.com/ankidroid/Anki-Android/issues/8547#issuecomment-820021790

**Comment by Akshay0701** [comment]
> I think i got where problem is , when I replaced onTouch method with pervious onItemSelected methods then it work fine

But @david-allison-1 when I replaced OnTouch with pervious ItemClickListner then it return 6 cards , do you have idea about this ?

**Comment by david-allison-1** [comment]
> > I think i got where problem is , when I replaced onTouch method with pervious onItemSelected methods then it work fine
> 
> @david-allison-1 when I replaced OnTouch with pervious ItemClickListner then it return 6 cards , do you have idea about this ?

The bug is only triggered under certain conditions (for me: open then minimise the card browser), taking different strategies likely causes different outcomes

**Comment by mikehardy** [comment]
I am only commenting to say this is exactly why automated tests are so great (and so irritating!!) - I am shocked to discover how buggy my "looks good" code is every time I go to write a test for it :sweat_smile:, likewise how poorly organized it is - and then by contrast how much better organized it is when it is testable and how relaxed I feel when I know it is tested well (with unexpected bugs fixed). Nothing to do with this code or this test, just a general statement. Keep at it and I'm sure it will work @Akshay0701

**Comment by david-allison-1** [comment]
@Akshay0701 This should now work if you rebase it onto `master`

**Comment by Akshay0701** [comment]
I am closing this pr because I added this code in #8644.

**Pull request closed without merging**
