### PR TITLE
changed string splitting from spaces to comma

### LINKED ISSUE #8732: [Bug] Deck Options new cards steps numbers are not displayed correctly
###### Reproduction Steps

1.  Open "options"
2. Open "new cards"
3. The number in "Steps (in minutes)" are not displayed correctly

See the attached gif for more information.

###### Actual Result
A correct numerical integer, for example "110", instead of "1 10"

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Akshay0701**
fixes #8732

working ankidroid and ankidesktop

https://user-images.githubusercontent.com/52353967/124959593-fcdc0480-e038-11eb-93d7-c708b623a35e.mp4

### CODE REVIEW

**Comment by david-allison-1** [comment]
We need to ensure that this is only comma-separated in the UI, not in the JSON, otherwise we'll get massive issues.

The code doesn't read obviously as the above, and that's a worry.

The Anki 2.1.45 beta changes this UI, it'd be useful to see if any changes have been made here (which might be better than comma separation).

**Comment by Akshay0701** [comment]
> We need to ensure that this is only comma-separated in the UI, not in the JSON, otherwise we'll get massive compatibility issues.

we are not directly dealing with JSON at all, 
in `convertFromJSON` process we are iterating through all string from json and just adding comma instead of spaces,
and in `convertToJSON` process we are iterating through our edittext string and splitting them with comma instead of spaces(without dealing with json or core functionality, so it is just UI change and it will not bring any compatibility issue from our side).

**Comment by david-allison-1** [comment]
> > We need to ensure that this is only comma-separated in the UI, not in the JSON, otherwise we'll get massive compatibility issues.
> 
> we are not directly dealing with JSON at all,
> in `convertFromJSON` process we are iterating through all string from json and just adding comma instead of spaces,
> and in `convertToJSON` process we are iterating through our edittext string and splitting them with comma instead of spaces(without dealing with json or core functionality, so it is just UI change and it will not bring any compatibility issue from our side).

Oh, that's perfect then. Could you stick in a screenshot and then we're good to go.

If you have the time, and if you can think of one, could you rename the methods to better explain this.

**Comment by Akshay0701** [comment]
yes, I added a video which demonstrates working of change in ankidroid

**Comment by david-allison-1** [comment]
I'll want to bring this to my device and test myself.

Do spaces via the keyboard still work?

Can we use `", "` instead of `,` for displaying

**Comment by Akshay0701** [comment]
Why not, will do this.

**Comment by Akshay0701** [comment]
Done!

**Comment by mikehardy** [comment]
pending

> I'll want to bring this to my device and test myself.

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Just to note for other reviewers, this shouldn't change persistence
https://github.com/ankidroid/Anki-Android/blob/d0201e41381fe81a25e16730908de08fc53252d1/AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java#L297-L298

* The value in the EditText no longer accepts spaces
* The value in the EditText has been changed from displaying spaces, to displaying commas, we want spaces here as the keyboard for numerics doesn't prominently display a comma

**Comment by Akshay0701** [comment]
what should i do here ?

should I revert changes ?

**Comment by david-allison-1** [comment]
> what should i do here ?
> 
> should I revert changes ?

* There should be a way to change the display of the preference without changing the representation
* We should allow both comma separated and space separated variables in the textbox, but keep the in-memory representation consistent

**Comment by Akshay0701** [comment]
Got it!

now we are displaying steps in Preference like this -> 3, 20
and then users can use both multiple spaces or comma's
example: user input  "3    12,,, 25    6,,"
output [3,12,25,6]

**Comment by mikehardy** [comment]
Just noting that the CI Emulator test failure is unrelated, it was solved after this PR - if this PR were rebased it would be fine. I think it's still waiting on a look from David per self-assignment

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Sorry for the delay

I feel that this should only be comma separated in the visual summary of the preference, rather than modifying the EditText. 

The UX is diminished because a user feels they need to add the commas into the EditText, which takes many more presses on the keypad (comma is on a separate input panel in GBoard)

**Pull request closed without merging**
