### PR TITLE
Fix image crop required twice

### LINKED ISSUE #7768: Crop after taking image does not work
* Take Image
* Crop dialog appears - select crop
* Crop Image
* Image is not cropped

Pressing "Crop Image" works

### PR DESCRIPTION
**Pull request by david-allison-1**
We didn't modify our UI state from the crop dialog

Fixes #7768

Tested on my Android 9

### CODE REVIEW

**Comment by david-allison-1** [comment]
Despite the ViewModel class making the "new/existing image" code change much easier add, I don't feel it's made the underlying code easier to reason about, or test. 

This isn't a complicated screen in the grand scheme of things, but I feel it's high(er) priority to refactor further and test as it's caused a disproportionate number of problems.

**Review by mikehardy — APPROVED** [review]
Oh, that is subtle
Hard to test this one, either way.

**Comment by mikehardy** [comment]
Not sure what other testing you've done but without CI I just marked it pending merge, when you're happy with it please feel free to merge, I labeled it for 2.14.2 so I'll pick it in due course (and I run full API skew tests locally before releasing now)

**Comment by david-allison-1** [comment]
Full unit test and instrumented test run on API 28

**Pull request merged**
