### PR TITLE
48dp deck height

### PR DESCRIPTION
**Pull request by timrae**
There were several complaints from the beta testers about the decks being too compact, so I checked the [material guidelines](https://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing) and Google recommend 72dp for list items. I think that's obviously too big, but elsewhere in the document they recommend a 48dp minimum clicking area, which is also the height they use for the drawer list items. So that seems like a good number to go with.

new_deck_height

### CODE REVIEW

**Comment by timrae** [comment]
@hssm you complained about the size of the deck expander relative to the text size once; here's what it'd look like with 24dp expander icon if you like that better?

chevron_24dp

**Comment by snowtimeglass** [comment]
Though I feel the new size of deck list items is too big,
I might have to accustom myself to it...

On the other hand, 
I feel the new size of the deck expander is good.
I've also felt the expander was too big.

**Comment by timrae** [comment]
@snowtimeglass 
Yes I haven't really gotten used to the new size yet either, let's revisit the issue in a week or two.

**Comment by snowtimeglass** [comment]
> [Is everyone happy with the larger deck height after having a chance to get used to it? ](https://groups.google.com/d/msg/anki-android/DrMPHn9NQtk/qyeQ9ChFEAAJ)

Umm, yes, I've almost got used to it.
New users will prefer the new size, which follows the material guidelines, to the old compact one.
I also accept it with reluctance to part with the old one.

**Pull request merged**
