### PR TITLE
Speed up Tests 

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
I was getting frustrated with test speed, and this should help. 

**CI Runs**
* Run 1: 9m24s
* Run 2: 9m36

Improvement, but not as good as I'd hoped

## Approach
Implement a `FastAnkiDroidApp` for tests: don't call `onCreate`

## How Has This Been Tested?

Should be test only: app still opens

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
```
CI Runs

    Run 1: 9m24s
    Run 2: 9m36

```

That's not enough info to make a decision, I assume these are the jacocoUnitTestReport runs?

If so appears to be about a 10% improvement achieved by deepening the inheritance stack a little. I'm not anti but I wonder if it's worth it. I'm not sure 9.5 mins vs 10.5 mins in CI is worth anything - I've already stopped paying attention to things at that point and just labeled it pending merge. I keep a tab open with that PR label search and just refresh once in a while, to me that CI-minute has no relation to wall clock time anymore, it would need to be like 2 minutes before I'd consider it actually semi-interactive and start caring. :thinking: 

Convince me it's worth it?

**Comment by david-allison-1** [comment]
Via Android Studio's single-threaded default runner:

Before: 11m 2s 
After: 7m 9s

Best thing was: it picked up another simple optimisation

**Comment by mikehardy** [comment]
that's significant. what on earth is Android Studio doing not going parallel though? omg

**Comment by mikehardy** [comment]
This one suffered conflict bitrot while (it appears) it was waiting on me, sorry

**Comment by mikehardy** [comment]
I just scanned this again as it went stale, I'm not against this but it certainly hasn't been a priority sorry - every second I've got is currently going to release management / GSoC

**Pull request closed without merging**
