### PR TITLE
Remove allow_empty from card projection

### LINKED ISSUE #8311: CI Broken - no such column: allow_empty
This appears to have broken CI:

```
com.ichi2.anki.tests.ContentProviderTest > testMoveCardsToOtherDeck[0][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616393828073,1616393828277,1616393828506,1616393828883,1616393829171,1616393829514,1616393829727,1616393830070)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryNoteIds[0][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616393842541,1616393843186,1616393843458,1616393843638,1616393843858,1616393844115,1616393844324,1616393844822)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testUpdateNoteFields[0][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id=?": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryNotesProjection[0][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616393878268,1616393878819,1616393879184,1616393879491,1616393879961,1616393880460,1616393880768,1616393880969)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryDirectSqlQuery[0][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE mid=1616393888238": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testMoveCardsToOtherDeck[1][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616393956534,1616393956767,1616393956995,1616393957134,1616393957271,1616393957625,1616393957917,1616393958127)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryNoteIds[1][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616393967759,1616393967957,1616393968257,1616393968552,1616393969115,1616393969404,1616393969680,1616393969874)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testUpdateNoteFields[1][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id=?": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryNotesProjection[1][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE id in (1616394000267,1616394000643,1616394002353,1616394002709,1616394003437,1616394003955,1616394004681,1616394005692)": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)

com.ichi2.anki.tests.ContentProviderTest > testQueryDirectSqlQuery[1][TestingAVD(AVD) - 11] FAILED 
	android.database.sqlite.SQLiteException: error while compiling: "SELECT id as _id, guid, mid, allow_empty, mod, usn, tags, flds, sfld, csum, flags, data FROM notes WHERE mid=1616394016904": DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such column: allow_empty\"))", kind: Other }
	at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.<init>(StreamingProtobufSQLiteCursor.java:57)
```

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/7271#issuecomment-803837881_

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
No idea:
1. why it was not detected by tests (they were passing when merged)
2. I added them here, were they clearly have nothing to do

Fixes #8311

### CODE REVIEW

**Comment by david-allison-1** [comment]
I think this change looks fine from an implementation POV, but I'm a little concerned.

From memory, the change which was merged seems significantly different from the one that I reviewed (I don't recall the `AllowEmpty` class).

One question: we've added a parameter to the API, which seems fine, and this appears to default to 'false', which is a change in behaviour (this also matches AnkiDroid's change in behaviour here). 

https://github.com/ankidroid/Anki-Android/pull/7271/files#diff-eb3213e9e0e4826260f2375585de4bc810d9aa916d53235b302354cf228efe9fR806

It feels that this should be better documented (both as 'false' being the expected default value, and the change/bugfix in API result to match a later version of Anki Desktop) - unsure if this is a "breaking" change.

**Comment by Arthur-Milchior** [comment]
> From memory

I'd like to note you approved the january 21st. It may impact here

>  the change which was merged seems significantly different from the one that I reviewed (I don't recall the `AllowEmpty` class).

I checked whether a git diff could easily check out the difference between various version of the branch. Sadly, it mostly return the change that occurred on master between both version.

Feel free to revert if you feels its safer. I'll recreate the PR in this case.


>_One question: we've added a parameter to the API, which seems fine, and this appears to default to 'false

Nope. If the value is not set, the `getAsBoolean` return null. `Models.AllowEmpty.fromBoolean` sends `null` to Cloze_only

>', which is a change in behaviour (this also matches AnkiDroid's change in behaviour here). 

I disagree. The default previous behavior was to add cloze even if they don't generate cards and not to add standard note type without cards. This is exactly what occurs now if you don't provide a value to ALLOW_EMPTY. This is also the reason why I did multiple commit. I wanted to ensure that you can check that the big commit added options to change things but used default values similar to previous values, and then do the actual behavior changes in very small commits. Those two commits change the behavior in note importers and in `genCards` (This function is used during "check cards" and is not used when you just add a card from the "add card" window. )

I agree that if I had changed the default behavior it would have been a huge problem. However, it is not the case here. Actually, even "adding a note with no card" is still not possible with this change. The only change is "we don't delete note that has no card" and "we allow user to import note even if they generate no card"

> It feels that this should be better documented (both as 'false' being the expected default value, and the change/bugfix in API result to match a later version of Anki Desktop) - unsure if this is a "breaking" change.

Can you please let me know what you mean by "API matching desktop"? It seems upstream do not have an API.
Anyway

**Comment by david-allison-1** [comment]
Apologies, need to get back to real life - will write a longer comment later

Noted on `getAsBoolean` - my mistake - my API documentation went to `BooleanSupplier`, which returned `boolean`

If my comment was based on a faulty premise, no need to discuss, let's discard it and move on

**Comment by Arthur-Milchior** [comment]
@mikehardy and @david-allison-1 

Broken CI will block many people, and if they run test, may cause them to loose a lot of time to understand why it fails. So I'll exceptionnally merge this PR even if the only approval was:
> I think this change looks fine from an implementation POV

This is not to close the discussion, only to ensure that contributors can contribute with relevant CI feedback. If required, I'm still fine with reverting the previous PR too

**Comment by mikehardy** [comment]
@Arthur-Milchior your desire to make sure the tests were green again - and thus merging - is exactly the right bias I think, I'm only reading this later but I think this was handled very well for whatever that's worth. I never expect perfect but I love "fixes mistakes quickly" and "makes sure people aren't blocked" -> works for me

**Pull request merged**
