### PR TITLE
Update parallel build script for current MacOS+Android Studio build, and change storage directory for parallel builds

### PR DESCRIPTION
**Pull request by mikehardy**
Hi there - I made one set of small non-functional changes to the parallel build, and two functional changes -

1) I updated sed commands so they were "sed -i ''" vs "sed -i -e", this means the in-line edited files are no longer backed up, but the current combo of MacOS and AndroidStudio was failing to build when there were ".xml-e" (backup) files in the resources directory. Since we have version control for real backups and these builds will never be committed, it seemed an easy decision to remove the backup functionality to proceed with the build

2) the first functional change is the addition of one more sed line, this one to replace the storage directory name instance of 'AnkiDroid' with the parallel build name, in the same manner as the other replacement sed lines. This should remove confusion / configuration needs as the parallel builds should now work independently of one another out of the box

3) the second one is the addition of a 'parallel-package-release.sh' tool, that iteratively builds 3 parallel packages (A, B and C, like before) in a way that should make for compatible upgrades to previous users.

This appears to work for me now - installs and upgrades - with one caveat, the first time you install a parallel build it does two terrible things. It crashes first, then when you restart it, it runs but it does not correctly read the storage directory property. You have to go into advanced preferences and then leave advanced preferences (without doing anything) and then it works. I believe this is related to Issue #4748 

I still think this is an advantage over the current master/HEAD status, as current mainline does not build parallel builds correctly (on MacOS/AndroidStudio at least), and it also crashes on startup for me on fresh installs as noted in #4748 - thus these changes aren't a regression they just don't fix everything in the area

### CODE REVIEW

**Comment by timrae** [comment]
There was an error in my git repo which prevented the last couple of version bump commits from getting pushed. I've fixed the issue and pushed a new version, so you can remove that commit.

**Comment by timrae** [comment]
Also please remove the merge commit

**Comment by mikehardy** [comment]
Yes sorry - total git newbie, will polish it up 

-Mike
--
+14157209408 (WhatsApp and US phone) 

-----Original Message-----

**Comment by mikehardy** [comment]
It looks like there are various ways of removing commits with git (reversing changes, attempting to delete etc) but all of them have tradeoffs and these were small self-contained changes. I've created a second branch ('parallel2') that incorporates good suggestions cleanly, and I'll submit a fresh pull request from there.

**Comment by timrae** [comment]
Ah, sorry let me know next time if you need help with git, a new PR was unnecessary, you'd just do a git rebase followed by a force push.

**Comment by mikehardy** [comment]
Sometimes the painful slow way motivates the learning, so not all bad. I'll read up on those commands

**Comment by timrae** [comment]
In this case you have a mystery merge commit, so the `git rebase` might not have worked anyway. But say you didn't have that merge commit there, and you simply wanted to remove commit c5332c7fca2c100ab9b55202bc421e47a4f04263, you would typically do it like this:

```bash
# interactive rebase up to (and including) commit c5332c7
git rebase -i c5332c7^
# your default text editor opens up with a list of commits; delete c5332c7 (which is the first line) and save + exit
git push origin HEAD -f # force pushes the current branch to the remote named origin
```

**Pull request closed without merging**
