### PR TITLE
Added a Toolbar for the TagsDialog.

### PR DESCRIPTION
**Pull request by brunodea**
**Newest changes**
--
* Removed old resources related to the TagsDialog;
* Added Dialog for adding a tag. However, if the SearchActionItem is expanded and is not empty, the user can add the typed tag by clicking the AddTagActionItem;
* The EditTexts in the Dialog for adding a tag and in the SearchView have a filter that doesn't allow the user to type spaces or commas;
* There is no more "knowsHowToAddTag" shared preference;
* Shows a Snackbar for new tags and when the tag already exists. For each case, a different message is shown;
* If the user tries to add a tag that already exists, it is simply checked for him;
* Empty tags are not added and no message is shown;
* The Toolbar uses the same style as the app-wide toolbar;
* The select all action selects or deselects only the tags being displayed;
* The SearchQuery hint is `Add/filter tags` when the dialog type is `TYPE_ADD_TAG`, otherwise it is `Filter tags`;
* The add menu action only is shown if the dialog is of the type `TYPE_ADD_TAG`.

**Old PR info**
--
I've replaced the TagsDialog title with a toolbar with the actions: search, add and check all (in this order), as requested by @timrae. I think it indeed looks much better now. 

One thing that I'm not sure how to proceed is the ripple animation. Currently, there is no animation when the user selects a tag in the tag list. If anyone knows the best way to add it, please tell me! Thanks.

EDIT: I realized that the items in the CardBrowser had the ripple effect, so I just replicated that! It should be working nicely now. :-)

EDIT: Okay, some notes for you to know what I've actually implemented:
* There's still a Toast teaching the user how to add a tag. I think it is necessary, because it maybe a little obscure. The user has to type some text in the `SearchView` and the click the menu item Add tag;
  - The shared preference name is `knowsHowToAddNewTag` now. This way, old versions with `knowsHowToAddTag` already `true` will also show the Toast message;
  - The toast message only is shown if the user clicks the menu item add tag. However, if the user writes some tag in the searchview and then clicks the menu item add tag, the toast message will actually never be displayed;
  - **Do you think we should keep this toast message or simply not?**
* The Toolbar uses the same style as the app-wide toolbar;
* The select all action selects or deselects only the tags being displayed;
* The SearchQuery hint is `Add/Filter tags` when the type is `TYPE_ADD_TAG` and `Filter tags` otherwise.
* The add menu only appears when the dialog is of the type `TYPE_ADD_TAG` and its positive text is changed from Select to `OK`;

### CODE REVIEW

**Comment by timrae** [comment]
> There's still a Toast teaching the user how to add a tag. I think it is necessary, because it maybe a little obscure. The user has to type some text in the SearchView and the click the menu item Add tag;

If the user clicks "Add tag" while the SearchView is not open, instead of showing a toast, is it possible to pop up an input dialog where the user can type the tag they want to add? I think this would be more intuitive.

**Comment by timrae** [comment]
Also once the Tag is added, we should probably show a SnackBar or Toast saying `String.format("Added tag \"%s\"", tag)`

**Comment by timrae** [comment]
Oh, could you also remove any unused resources from this as well? E.g. the `ic_addtag`, `white_btn_radio`, and `blue_btn_radio` xml and pngs,  etc.

**Comment by brunodea** [comment]
> If we did do that, it could be cool if the OK button in the input dialog was greyed out until a valid tag was input

What is an invalid input? If the tag already exists, instead of disabled the positive button, I could make the tag checked when the user clicks on OK. What do you think?

**Comment by timrae** [comment]
> If the tag already exists, instead of disabled the positive button, I could make the tag checked when the user clicks on OK. What do you think?

Ah yes, that would be nice. I guess the only invalid tags are ones containing the space character, since that's the tag delimiter

**Comment by brunodea** [comment]
>  there's a method for this in AnkiActivity so you might be able to try `((AnkiActivity) getActivity()).showSimpleSnackbar(...)`

I just noticed that all Snackbar related methods from `AnkiActivity` are `protected`, so the only way for me to use it, would be to make the call in the Activity that called the TagsDialog. However, the message would be about all tags and would not appear for each tag added. So, at least for now, I will only show a Toast.

**Comment by timrae** [comment]
OK that's fine! Also fine to make them public, add extra overloaded
methods, or even just re-implement the method in the DialogFragment itself
since it's very simple.

**Comment by brunodea** [comment]
@timrae I've just sent the latest version. I'm not sure if I removed all old TagsDialog res files, but I think I did; if there are others that I should remove, please tell me!

**Comment by brunodea** [comment]
Oh, in the app-wide Toolbar (Actionbar) the Add action is placed before the Search action. However, in the TagsDialog the Search action comes first, do you think I should change it in order to be the same as the app-wide toolbar?

**Comment by timrae** [comment]
I don't think so, the order should be determined by the frequency with
which the action is used.
I'm going to build and check your PR now.

**Comment by brunodea** [comment]
Okay, nice. Thanks!

**Comment by timrae** [comment]
Looking really really nice @brunodea, thanks a lot!!!

**Comment by brunodea** [comment]
No problem! :-)

**Comment by timrae** [comment]
I don't suppose you'd be interested in working on this?

https://groups.google.com/forum/#!topic/anki-android/_m_As1MluXk

**Comment by brunodea** [comment]
Sure, I can work on it. But for the next days I'll be busy, so it'll have to wait a bit. Maybe until then Allison gives some life signal, but if he doesn't I'll surely take a look.

**Comment by hssm** [comment]
Really nice work on this. I just wanted to point out that the desktop client allows the use of commas in tags so there is no need to filter it out.

**Comment by brunodea** [comment]
Okay, I'll create a new PR with the fix.

**Comment by timrae** [comment]
Damn, it looks like I broke the layout in #863

**Comment by timrae** [comment]
It looks like the global theme `android:fitsSystemWindows="true"` is the culprit... I guess we either have to set that in the individual layout files for all our activities instead of putting it into the theme...?

**Pull request merged**
