### PR TITLE
Regression test for #6966

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
The bug was caused by d694006 .

Essentially, the bug is due to the fact that I called reset while there is a card in the reviewer, without actually
taking the card in the reviewer into account. Which is something I corrected later thanks to considering mHaveCounts and
mHaveQueue separately.

This would explain #6898 and #6768

The idea here is that:

* the learn queue gets emptied during reset
* when the card is answered, it is added in the learn queue. But since the queue was empty and not yet refilled, it is
added in a dirty queue. Normally, it's not a problem when the queue is dirty and empty, because _fillLrn will simply
fill the queue again. However, as soon as there is an element in the queue, it is assumed that it is not dirty. This is
corrected thanks to mHaveQueue which simply state whether the queue is dirty or not.
* Since the queue contains a single element and is assumed (incorrectly) not to be dirty, all other cards in learning
never enter the queue, so they are reviewed at the end of the review session
* If there are only cards in learning, the single card in the queue is the only one being reviewed, until it goes to the
Rev queue, at which point fillLrn is allowed to fill the queue again.
* I believe that the more general problem here is that, while I did realize I corrected plenty of bugs on 2.1.13 alpha, I
didn't realize that some of those bugs where in stable. Mostly because I have no idea when the stable branch was cut and
that my mental model of the code uses the code in alpha.

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
>         Caused by:
>        java.lang.AssertionError: Unexpected card ord
>        Expected: is <3>
>             but: was <2>

Fun fact, we created non deterministic tests...

That is actually done on purpose. cards in learning get fuzzying so they are not always seen in the same order. Need to add a few minutes of delay to ensure the max fuzz of card 1 does not make card 1 due date coming after card 2 due date

**Comment by Arthur-Milchior** [comment]
Is there a way to get the test run on both scheduler ? No reason not to do it on sched v2. But i don't know how to use the tool with Reviewer

**Comment by Arthur-Milchior** [comment]
Corrected so that I had 3 minutes between each review. It explain why it makes test deterministic. Quite happy because it makes my method `addM` useful in actual test !

**Comment by mikehardy** [comment]
> Is there a way to get the test run on both scheduler ? No reason not to do it on sched v2. But i don't know how to use the tool with Reviewer

If you want the reviewer to exercise both schedulers, you add "parameterization" to the tests, with a special runner, a parameter that varies, a definition of how it varies, and then in setUp (and maybe tearDown?) you use the parameter variation - example https://github.com/ankidroid/Anki-Android/commit/db11a0cba470b800786e6fa85647af0a5ae13417#diff-369a4739f0e54603a978d0e92deb7202R41-R62

**Comment by Arthur-Milchior** [comment]
Both sched used.

**Pull request merged**
