### PR TITLE
Fix #3400: Use the locale’s first day of the week in statistics

### LINKED ISSUE #3400: Use the locale’s first day of the week in statistics
Originally reported on Google Code with ID 2504

```
What steps will reproduce the problem?
1. Use e.g. German UI
2. Go to »Statistik«, that is “Statistics”
3. And »Gedächnisleistung nach Wochentag«, “Weekly Breakdown”

What is the expected output? What do you see instead?
The graph should start with the first day of the week, which, in Germany, is Monday.
Instead it starts with Sunday, which, in Germany is the last day of the week.

(This happens every time since the stats rework, i tried it with 2.4, but will skip
pasting version info.)

Please provide any additional information below.

Week starts on Monday in Germany, see e.g. https://ssl.icu-project.org/icu-bin/locexp?d_=en&_=de_DE

Looks like we should look at what the Calendar class thinks is the first day of the
week: https://developer.android.com/reference/java/util/Calendar.html#getFirstDayOfWeek%28%29

P.S.:
Why does the week-*end* contain the *start* day of the week in, say, the USA‽
```

Reported by `ospalh` on 2015-02-02 11:05:57

### PR DESCRIPTION
**Pull request by madhead**
Actually, the locale is not used, but extra setting is added to the app

### CODE REVIEW

**Comment by timrae** [comment]
It's not really a review option, how about adding to advanced statistics module in advanced preferences?

**Comment by madhead** [comment]
@timrae, under "Workarounds"? :)

**Comment by timrae** [comment]
It's under "Plugins"...

**Comment by madhead** [comment]
Oh, I see. Updated the branch...

**Comment by timrae** [comment]
Maybe an alternative solution to #3400 could be to use the user's language setting (under general options) as the basis for setting the day of the week? It would be far more intuitive if we could set it automatically rather than having a manual setting for it (which in general we are always trying to minimize the number of)

**Comment by madhead** [comment]
I agree that the number of settings should be as minimal, as possible, but, as I noted in #3400's comments, some people (like me) try to use English language whenever it is possible (e.g. due to poor localization). So, guessing will not work for them.

**Comment by timrae** [comment]
I agree that using the device locale for language is unsatisfactory but I don't see any problem with the using the app locale...

**Comment by madhead** [comment]
Well, my point is that even when the app will be 100% translated into Russian (my spoken language) I'll still be using OS default / English. And I know many people who will behave the same way. Some languages, like Belarussian, will probably never be translated and maintained in sync with the English version.

I saw the translations on Crowdin, even contributed a few last week, but... Still English is my choice for this and other apps and I want my system to be consistent. So, for me it is hard to think of a guaranteed way to guess this setting rather then to directly ask the user.

P.S. The same applies to currencies in many other apps. Once upon a time somebody stated that in my country we should use commas as decimal separators and his word landed in standards and specs. But I like dots, I'm used to them because dots are used in computers. So, I really appreciate apps that give me a choice.

**Comment by hssm** [comment]
I don't like the idea of adding a setting for something as minor as this.

From Google's design guidelines, settings should:
>    Capture a user preference
    Get accessed infrequently
    Are used by the majority of users
    **Are used by a minority of users, but are essential to supporting their needs**

I wouldn't call this essential.

**Comment by timrae** [comment]
Yeah the argument here for inclusion is a bit weak IMO to be honest... 

Users that explicitly set the locale and/or the app to an English locale are probably happy to see the days of the week ordered in that locale. Users like yourself that want to see the app in English with the days of the week in a different order are a minority and are not really negatively affected in any significant way (it's just an aesthetic issue).

Furthermore, this PR doesn't really address #3400 in a satisfactory way as it's hardcoding Sunday as the default start day rather than using the system locale as the default.

**Comment by eginhard** [comment]
I agree that a setting doesn't make sense for this, it should just be based on locale. You should then be able to have apps in English with weeks starting on a Monday by choosing English (UK).

**Comment by hssm** [comment]
Apparently the desktop client doesn't even have a *weekly breakdown*. I was hoping to copy what it was doing.

Tell you what, I'd accept a PR that just hard-codes Monday to Sunday because nobody in real life actually cares about Sunday *really* being the start of the week, and this is a pretty insignificant part of the application to fuss over.

**Comment by timrae** [comment]
:+1:

**Comment by madhead** [comment]
Lol. A [message](https://github.com/ankidroid/Anki-Android/issues/3400#issuecomment-748652205) by @github-actions bot triggered an email into my inbox, so I've re-read the thread…

Ironically, but now Google lets its users to choose the first day of week in their official Calendar app. It's the first option under "General" in Settings:

Screenshot_20201221-002025

**Pull request closed without merging**
