### PR TITLE
NF: remove !! from previousTask

### PR DESCRIPTION
**Pull request by Arthur-Milchior**

### CODE REVIEW

**Review by david-allison — COMMENTED** [review]
This seems harder to read

**Comment by Arthur-Milchior** [comment]
Because of the new lines added by linter, because of the let?

**Comment by david-allison** [comment]
> Because of the new lines added by linter, because of the let? 

Mostly the new lines, will know once that's fixed

**Comment by Arthur-Milchior** [comment]
Problem is that with the linter, I can't push without newline, it adds them automatically when I modify the file.

**Comment by david-allison** [comment]
(weak opinion)

Doesn't seem worthwhile then

**Comment by ShridharGoel** [comment]
To me, this looks better to read with each argument in a new line.

@Arthur-Milchior I think it might be happening because of your Android Studio settings.

**Comment by Arthur-Milchior** [comment]
> @Arthur-Milchior I think it might be happening because of your Android Studio settings.

It's when I do a `git commit` that the rewritting occurs. So I'd have thought it follows automated rules triggered by git. I was not expecting it to interact with android studio

**Pull request closed without merging**
