### PR TITLE
Robolectric 4.4: Switch to API 29 and LooperMode.PAUSED

### PR DESCRIPTION
**Pull request by david-allison-1**
I'm doing this as part of the Rust conversion, as having two LooperModes causes problems with loading native libraries.

Related: #7107

## Purpose / Description

Adopt the next release of Robolectric, which has a transitive dependency on Android API 29 as compile targets

So this moves us forward to API 29 with associated deprecation notices (fixed in #7332).

There is also a requirement from API 29 in Robolectric to use JDK 9, we'd jump to 11 due to it being a LTS, and this is currently nonstandard in Android Dev, so we continue testing from API 28.

## How Has This Been Tested?

It will be tested in Travis 

Tests have been run against API 28 and 29

## Testing required

Once the known failures are dealt with, could you run this under a custom Android Studio test config which defines "Run tests until failure". A lot of these tests are flaky, and it's been hours of work to track down and hopefully fix the problem.

### CODE REVIEW

**Comment by david-allison-1** [comment]
I get this failure with the sdk=28 change, I'm not sure how to handle it, as the code under test hasn't changed.

```
	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: A locale with a 2-letter code and regional variant resolves correctly
Expected: is "yue (Taiwan)"
     but: was "Cantonese (Taiwan)"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.ichi2.utils.LanguageUtilsTest.localeThreeLetterRegionalVariantResolves(LanguageUtilsTest.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	... 6 more
```

**Comment by mikehardy** [comment]
the l10n actually changes between the SDKs I found when implementing that exact test. I'm okay with updating to the test expected to match current actual

**Comment by david-allison-1** [comment]
> the l10n actually changes between the SDKs I found when implementing that exact test. I'm okay with updating to the test expected to match current actual

But, we're still running under SDK 28? I don't get how that would have changed. Regardless, I'll let it accept two values

**Comment by david-allison-1** [comment]
Oh! The assert was changed to the API 29 value in the change I based this off - nevermind

**Comment by david-allison-1** [comment]
Ready for review

**Comment by david-allison-1** [comment]
```
com.ichi2.anki.DeckPickerTest > limitAppliedAfterReview FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Caused by:
        java.lang.UnsupportedOperationException
            at com.ichi2.libanki.sched.AbstractDeckTreeNode.getNewCount(AbstractDeckTreeNode.java:176)
            at com.ichi2.anki.DeckPickerTest.lambda$limitAppliedAfterReview$6(DeckPickerTest.java:174)
            at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:660)
            at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
            at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:670)
            at com.ichi2.anki.DeckPickerTest.limitAppliedAfterReview(DeckPickerTest.java:173)
com.ichi2.anki.NoteEditorTest > clozeNoteWithClozeDeletionsDoesSave FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Caused by:
        java.lang.AssertionError: 
        Expected: is <1>
             but: was <0>
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
            at com.ichi2.anki.NoteEditorTest.clozeNoteWithClozeDeletionsDoesSave(NoteEditorTest.java:187)
```

**Comment by david-allison-1** [comment]
Note: My personal Travis can also be inspected

**Comment by david-allison-1** [comment]
```
2020-10-04 11:59:49.419 7380-7380/com.ichi2.anki I/DeckPicker: User has permissions to access collection
2020-10-04 11:59:49.420 7380-7380/com.ichi2.anki E/CollectionHelper: Could not initialize AnkiDroid directory
    com.ichi2.anki.exception.StorageAccessException: Failed to create AnkiDroid directory /storage/emulated/0/AnkiDroid
        at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:197)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:121)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:111)
        at com.ichi2.anki.CollectionHelper.getColSafe(CollectionHelper.java:152)
        at com.ichi2.anki.DeckPicker.firstCollectionOpen(DeckPicker.java:578)
        at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:435)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Review by mikehardy — APPROVED** [review]
Regarding the LanguageUtilsTest Asserts - dang, my bad. Thank you for fixing.
Regarding the entire move to SDK29 this is *huge* and gets it done in time for a no-pressure release-2.14 cut before Play Store cuts us off from pushing updates vs api28. Big thank you for bringing this one home

**Pull request merged**
