### PR TITLE
add a couple more Models.flush() calls that were missing

### PR DESCRIPTION
**Pull request by marcardar**

### CODE REVIEW

**Comment by timrae** [comment]
Currently the unit tests pass even without the flush() methods. Would you be able to add a method (something like reopenCollection()) which is called on all insert and update unit tests that causes the tests to fail if flush() is not present?

**Comment by marcardar** [comment]
I'm really not familiar with how libanki works, so it's probably better if you do something like that. I can remove the flush() changes from this PR if you like?

**Comment by timrae** [comment]
I don't think you really need an understanding of libanki; if I understand the problem correctly it should be sufficient to just close the collection without saving, reopen it, and then run the assert statements in the tests. 

With my new job and remaining papers to write for my PhD it will be hard for me to find the time to work on this.

**Comment by timrae** [comment]
I unexpectedly have found myself in a situation with some free time on my hands, so let me take care of this!

**Comment by marcardar** [comment]
Thanks!

**Comment by timrae** [comment]
Thanks for identifying and pushing this issue. I think I've addressed the problem in #4222.

**Pull request closed without merging**
