### PR TITLE
NF: Card and Note constructors are not-python like

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
While it made a little bit of sens previously, now that upstream moved to rust, it makes even less sens now..

https://github.com/ankitects/anki/commit/7ddaf93f7ac77259f8a17a85dbe4439036d3cdd0

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
LGTM. Could you link the Anki diff in your commit message

**Comment by Arthur-Milchior** [comment]
Done

**Review by david-allison-1 — APPROVED** [review]
LGTM

**Review by mikehardy — APPROVED** [review]
LGTM

**Pull request merged**
