### PR TITLE
Use chunk of 1mb in cursor

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
#Pull Request template

## Purpose / Description
AnkiDroid takse more than a minutes to start on my phone. Actually, profiling show it takes more than a minute to load the note type (I've got note type with >400 card types).
It seems that the maximal cursor size is slightly more than a mega bite. 
## Fixes
https://github.com/ankidroid/Anki-Android/issues/5921
 On my phone, it reduces loading from >1 minute to <20 seconds.

## Approach
I ensured that a megabyte is used, so that the number of query decrease and the speed increase.

I'd be curious to see if any alpha tester get problem (in which case it must be reverted) or if one mb is enough for every body.

## How Has This Been Tested?

Installing on my phone and seeing that I don't need to wait a minute regularly.

## Learning (optional, can help others)

I was trying to see how to use sqlite4java in AnkiDroid. It seems more efficient. But I don't fully understand how to replace the sqlite library used and what should be sqliteOpenHelperFactory in libanki/DB.java
So this is a less efficient fix, but quicker to create and to test 

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
Changing the sqlite library is not something I'm keen on doing right now, it is so fundamental, and I'm familiar with (and help maintain a bit) the requery library we use in order to maintain familiarity in the case of problems since it is so fundamental for our app. But! I have no problem with trying different cursor sizes out, it should be fine - the beauty of packaging our own sqlite library is that if it works for one person it should work for everyone (using the built in library means you have different versions with different problems in different Android API levels)

**Comment by Arthur-Milchior** [comment]
Oh, I've never realized that the library is inside the codebase. Could you please give me a link to any documentation and path of the library exactly.

**Comment by mikehardy** [comment]
Sure! and yes, since Android API1, Google has bundled "sqlite" which is a fantastic database, nearly bug free. But any database bug (or performance problem, or missing feature you need) is a grave problem for a database-backed app. And the old Android versions bundled old sqlite versions (of course). So we started bundling up-to-date sqlite versions so we stay close to Android (it's still the sqlite project) but so we knew exactly how the database would perform and what features (and bugs) were available regardless of what Android version people have.

Here is where we include it: https://github.com/ankidroid/Anki-Android/blob/e132593f0a916240431603e7aa63e41a21e65f5f/AnkiDroid/build.gradle#L133

Here is the repository where it is developed: https://github.com/requery/sqlite-android/

And it is built (and updated, when needed) from the upstream sqlite sources that google themselves use in their Android system images - link to current release https://sqlite.org/releaselog/3_31_0.html

**Comment by mikehardy** [comment]
This released as 2.10alpha65 as soon as google is done processing it

**Pull request merged**
