### PR TITLE
Draft: WYSIWYG Editor

### LINKED ISSUE #1377: "What-You-See-Is-What-You-Get" note editor (no HTML code visible to user)
## UPDATE - TEST DOWNLOAD AVAILABLE

**We are testing a Visual editor, you can install it to see how it works for you: https://github.com/david-allison-1/Anki-Android/releases/download/v2.10wysiwyg1/AnkiDroid-vised.apk**

Originally reported on Google Code with ID 474

```
I would be a great improvement to have a "What-You-See-Is-What-You-Get" style format
editing in card editor, with format buttons like in Anki Desktop.
Also, in the same UI or editing screen, to have buttons for fonts, "cloze", pictures,
record sound, etc... 

This enhancement, combined with the already pointed issues of playing movies and a
better card browser, would make Ankidroid a software definitely independent (or better
said, non-dependent) from Anki Desktop.
```

Reported by `Villatonil` on 2011-02-27 17:29:52

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Follow-on from #5975 with commits cleaned and most review feedback handled. 

Performed as `trgk` on Discord is interested and it'd be great to get this across the finish line.

Required:

* Remove reference to `implementation 'com.github.jkennethcarino:RTextEditorView:0.1.1'` and include summernote in a new commit (before Initial Commit) - document how summernote was included in the commit message
    * Consider: whether this would be best in a separate library to reduce the load on git when summernote updates
* Reconsider color picker library as it is not maintained
* Consider: Move the "Add List" functions behind an "experimental" feature flag, as they're not perfect
* A few TODOs related to the WebView renderer crashing. See: `onRenderProcessGone`

## Fixes
Fixes #1377

## Approach
----
**Features**

* Bold/Italic/Underline
* Cloze
* Text Align
* Lists (bullet & numbered)
* Remove Formatting
* Insert & Delete Image & move via copy/paste (**needs testing, and probably help**)
* Horizontal Line
* Record Audio
* MathJax
* Sound and Video work via [sound:]
* Text/Background Color
* View HTML
* `<iframe>` does not work in the viewer or the editor for me

### CODE REVIEW

**Comment by mikehardy** [comment]
If at all possible it would be great if the summernote import could be somehow scripted in a little shell script? That way it would not just be documented but as summernote updates we might even be able to just run the script and the "how" would be built in to the script via action (and some comments, likely) giving a basis for future explorers to adapt as they do. I'm okay with vendoring stuff like this to start vs trying to have some gradle-compatible package of it. It appears summernote is available via NPM, but whatever seems sensible works for me

It also appears that it relies on jQuery which has a related issue #7920 that @hgiesel is looking at (or self-assigned anyway, but of course it is holidays - Henrik please don't interpret me tagging you as "do something" it's just me saying "if you were doing anything here is something to keep eyes on" :-) )

I found a colorpicker library that appears to be alive! https://github.com/skydoves/ColorPickerView (via https://github.com/topics/colorpicker?l=java) and it goes down to minSdkVersion 15 with an Apache license so should be fine?

I haven't actually reviewed it yet but those were more structural issues you called out in review notes so I wanted to address them first

Exciting! This feature will be incredible for users, a game changer I think

**Comment by david-allison-1** [comment]
All sounds good!

> If at all possible it would be great if the summernote import could be somehow scripted in a little shell script? That way it would not just be documented but as summernote updates we might even be able to just run the script and the "how" would be built in to the script via action (and some comments, likely) giving a basis for future explorers to adapt as they do. I'm okay with vendoring stuff like this to start vs trying to have some gradle-compatible package of it. It appears summernote is available via NPM, but whatever seems sensible works for me

Definitely sounds like a good idea (are we doing this for MathJax?) - I'd lean on not including any of the files directly the project due to git file churn

> I found a colorpicker library that appears to be alive! https://github.com/skydoves/ColorPickerView (via https://github.com/topics/colorpicker?l=java) and it goes down to minSdkVersion 15 with an Apache license so should be fine?

My main preference for the current color picker was:

1. It looks good (main preference, didn't like most of them)
2. It shows a selectable list of colors which represent the default colors people would want
3. The default colors can be saved by us to improve the UX

I don't think the above picker handles 2 and 3 (and 1, but taste is subjective 🤣)

**Comment by mikehardy** [comment]
This color picker appears to be maintained at least https://github.com/kristiyanP/colorpicker#what-you-can-do - appears to satisfy 2 and 3, looks fine to me

**Comment by david-allison-1** [comment]
> This color picker appears to be maintained at least https://github.com/kristiyanP/colorpicker#what-you-can-do - appears to satisfy 2 and 3, looks fine to me

Passes the 'looks good' test for me

**Comment by mikehardy** [comment]
as for summernote:
- mathjax is vendored, it is not included in an automated way, it was hand-crafted and currently has issues unfortunately, so would be better automated
- I'm not too concerned about git churn as it should be a bundle shouldn't it? called by entry point? like one optimized / minified etc file. We shouldn't be including raw source we should include an artifact, I'd expect - definitely scripted in that sense

**Comment by dae** [comment]
Hi guys,

Just wanted to give you a brief heads up about tentative plans for the computer version. Like the new graphs, I think there's a potential for sharing some of the editing code across the different platforms. Henrik has been updating Anki's existing editing code to more modern TypeScript recently, and that forms a good base from which we could investigate integrating more code like a tag selector, deck/note type selector, and so on. It would mean moving away from native widgets for these functions, but would mean less duplication of work. The easiest option would be to have an adaptive page that can be used as-is like the graphs, but as the code has been split up, consuming parts of it are also a possibility.

Aside from the TS refactoring Henrik has done, nothing else has been done yet, and it may be months before this becomes a reality, even assuming no roadblocks are hit - so you may well want to proceed with this Summernote implementation for now, even if you're interested in integrating Anki's code in the future. But thought it was worth mentioning in any case.

**Comment by mikehardy** [comment]
Thanks for the heads up! I'm definitely keen on sharing whatever code is possible, and - for this project anyway where we have javascript VMs already in use on all platforms typescript seems like a great way to do it. If you want to tag this issue or any of us in specifically on any of the work there @dae or @henrik I'd welcome it. Thanks

**Comment by henrik** [comment]
Wrong Henrik but godspeed :)

**Comment by mikehardy** [comment]
Ha @henrik very sorry :sweat_smile: meant @hgiesel :-)

**Comment by snehilrx** [comment]
Hi Guys,

I have previously worked on a hackathon project that used cards to show notice using WebView. For the creation of those cards, I used [Aztec Editor.](https://github.com/wordpress-mobile/AztecEditor-Android) I had injected some custom CSS to make it feel more like a card. The main issue that I found using the editor was touch and gesture, for example, dragging text and images around. I felt like the editor should be more like Instagram story-editor. Using a WYSIWYG editor in mobile (my opinion) is cumbersome. 

I have looked at the visual editor. It uses [summer note](https://summernote.org/) js injection into WebView.

**Comment by Akshay0701** [comment]
Hello , i was understanding and testing pervious implementation of WYSIWYG Editor , this is fascinating no doubt ,there is one bug I noticed ,
step to reproduce 
1 create a note with visual editor include text ,list 
2 go to edit note then open visual editor 

expected output 
Webview should load with previous HTML 
Actual output 
At expectional case webview gets total blank 

After doing debugging i got to know its was happening because of bad formating of HTML in note editor 
`I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Invalid or unexpected token", source:file:///storage/emulated/0/AnkiDroid/collection.media/__visual_editor__.html%22 (1)`

for example in my case 

p tag was a issue , when I changed (manualy)
to 
--->>>

it worked fine , so the solution I think is having function to check formation of HTML and a way to fix unformatted HTML to formated form,
### i am looking for proper solution and i will attach that here soon .

**Comment by Akshay0701** [comment]
https://github.com/SimpleMobileTools/Simple-Draw
This might help us in many way for adding and improving current whiteboard for users, really clean and great implementation

**Comment by david-allison-1** [comment]
https://html-notepad.com/ is an interesting alternative to SummerNote, likely worth considering if it's not based on `contentEditable`

**Comment by Akshay0701** [comment]
Is there any problems with summer note ?, what is reason to change current summer note?

**Comment by david-allison-1** [comment]
> @david-allison-1 That is great But Is there any problems with summer note ?, what is reason to change current summer note?

It's based on `contentEditable`: this implies that they may be unable to fix bugs. I'm unsure about maintenance.

**Comment by david-allison-1** [comment]
Superseded by Akshay's work

**Pull request closed without merging**
