### PR TITLE
Conform to GitHub community standards more

### PR DESCRIPTION
**Pull request by mikehardy**
I saw a blurb somewhere in the github UI about community standards and made the mistake of clicking on it ;-)

It shows project conformance or lack thereof to github community standards, and some of what it measures seems like a good idea.

1- Issue template - we were using an old style, I moved it into the current preferred directory
2- Pull request template - these are possible now, and I wrote down the standards I am aware of in conjunction with other PR templates around github
3- a CONTRIBUTING file, it's just a link to the wiki page of same name

The PR template is the most interesting change. 

It is not my intent to create policy or start policy debates. I intend to avoid that on purpose actually. It was only my intent to document what I've learned or nudge towards non-controversial best practices. Please revise as needed with that intention in mind, then if merged this could help future people

### CODE REVIEW

**Comment by timrae** [comment]
I think the pull request template is a bit too much, I don't really want to discourage contributions by making developers fill all of that out, and many of the things there I don't necessarily intend to enforce, or even follow myself. There were a couple of points there like comments, whitespace, self review, etc that we could keep.

**Comment by mikehardy** [comment]
Yeah - I put the kitchen sink in the PR template - I think you can edit in place and it's an easy WYSIWYG editor - wanna just take an axe to things you don't like ? whatever it is, works for me...

**Comment by timrae** [comment]
I'm not sure that the CONTRIBUTING file adds much value, in that showing a link to the contributing wiki to people opening new PRs or issues is not really helpful and potentially annoying. I think I added one at some point in the past, and later removed it as I didn't feel it was meaningful for us (since the same content is shown for issues and PRs which are two totally different things).

**Comment by mikehardy** [comment]
I just pushed a commit that nuked the CONTRIBUTING file, and if you've edited the PR template to your satisfaction, that's good for me - I looked at it and think it will be valuable as-is now, would've stopped a couple rookie moves on my part anyway

**Comment by timrae** [comment]
I still see the contributing file, and would you be able to rebase so that it's two commits (one for the move and one for the new template)?

**Comment by mikehardy** [comment]
Sure I'll do my best to repackage current state as one clean commit

**Comment by timrae** [comment]
Two commits please, for the two separate changes

**Comment by mikehardy** [comment]
@timrae my increasing git skill level has allowed me to re-shape this PR as 2 commits (one per template) per request - should be ready to go?

**Comment by timrae** [comment]
Thanks.

Just a nitpick but please also try to be consistent with your capitalization in the commit title ;)
I tend to prefer to capitalize the first letter

**Pull request merged**
