### PR TITLE
SchedV2: Fix incorrect intervals on Lapsed Filtered cards

### LINKED ISSUE #6082: [schedv2] - Bug: Lapses in Filtered Decks use 'new' delay steps
###### Reproduction Steps

Reported by /u/CarelessSecretary9 on reddit for 2.9.6. Confirmed on 2.10alpha71

Relevant settings dump (via DataGrip)

<details><summary>Table Data</summary>

| id | nid | did | ord | mod | usn | type | queue | due | ivl | factor | reps | lapses | left | odue | odid | flags | data |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1510928829863 | 1510928805161 | 1587920953716 | 0 | 1587921512 | 0 | 2 | 2 | 0 | 25 | 1300 | 22 | 5 | 1004 | 0 | 1587920944107 | 0 |  |

| id | guid | mid | mod | usn | tags | flds | sfld | csum | flags | data |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 1510928805161 | G4gNm4/\*oC | 1481327979421 | 1587918621 | 0 |  LightYear::Pulmn::Intro::PulmonaryCirculation aaaa alacranlyadded bab bab::pulmonary::introduction::pulmonarycirculation  | What is the gold standard method for diagnosing pulmonary hypertension?Heart catheterization&lt;div&gt;&lt;br /&gt;&lt;/div&gt;&lt;div&gt;&lt;i&gt;The non-invasive method is via echocardiography&lt;/i&gt;&lt;/div&gt; | What is the gold standard method for diagnosing pulmonary hypertension? | 2317416375 | 0 |  |
</details>

```
INSERT INTO cards (id, nid, did, ord, mod, usn, type, queue, due, ivl, factor, reps, lapses, "left", odue, odid, flags, data) VALUES (1510928829863, 1510928805161, 1587920953716, 0, 1587921512, 0, 2, 2, 0, 25, 1300, 22, 5, 1004, 0, 1587920944107, 0, '');

INSERT INTO notes (id, guid, mid, mod, usn, tags, flds, sfld, csum, flags, data) VALUES (1510928805161, 'G4gNm4/*oC', 1481327979421, 1587918621, 0, ' LightYear::Pulmn::Intro::PulmonaryCirculation aaaa alacranlyadded bab bab::pulmonary::introduction::pulmonarycirculation ', 'What is the gold standard method for diagnosing pulmonary hypertension?Heart catheterization<div><br /></div><div><i>The non-invasive method is via echocardiography</i></div>', 'What is the gold standard method for diagnosing pulmonary hypertension?', 2317416375, 0, '');

INSERT INTO MY_TABLE(conf, dconf, decks) VALUES ('{"activeDecks": [1587920953716], "curDeck": 1587920953716, "newSpread": 0, "collapseTime": 1800, "timeLim": 0, "estTimes": true, "dueCounts": true, "curModel": "1587920938249", "nextPos": 0, "sortType": "noteFld", "sortBackwards": false, "addToCur": true, "dayLearnFirst": false, "schedVer": 2, "newBury": true, "imgocc": {"version": 1.25, "ofill": "FFEBA2", "qfill": "FF7E7E", "scol": "2D2D2D", "swidth": 3, "font": "Arial", "fsize": 24, "skip": ["Extra 1", "Extra 2"], "flds": {"id": "ID (hidden)", "hd": "Header", "im": "Image", "ft": "Footer", "rk": "Remarks", "sc": "Sources", "e1": "Extra 1", "e2": "Extra 2", "qm": "Question Mask", "am": "Answer Mask", "om": "Original Mask"}}, "localOffset": -60, "rollover": 4, "lastUnburied": 1}', '{"1": {"name": "Default", "new": {"delays": [1, 10], "ints": [1, 4, 7], "initialFactor": 2500, "separate": true, "order": 1, "perDay": 20, "bury": false}, "lapse": {"delays": [10], "mult": 0, "minInt": 1, "leechFails": 8, "leechAction": 0}, "rev": {"perDay": 200, "ease4": 1.3, "fuzz": 0.05, "minSpace": 1, "ivlFct": 1, "maxIvl": 36500, "bury": false, "hardFactor": 1.2}, "maxTaken": 60, "timer": 0, "autoplay": true, "replayq": true, "mod": 0, "usn": 0, "id": 1, "dyn": false}, "1587144167603": {"autoAgain": 120, "dyn": false, "autoplay": true, "new": {"bury": false, "ints": [15, 60, 7], "separate": true, "perDay": 0, "delays": [15, 20, 1440, 4320, 8640, 21600], "initialFactor": 2500, "order": 1}, "timer": 1, "currentValue": 120, "autoAnswer": 20, "id": 1587144167603, "maxTaken": 180, "lapse": {"leechFails": 8, "delays": [20], "mult": 0.7, "leechAction": 1, "minInt": 2}, "name": "Poorretention", "rev": {"bury": false, "maxIvl": 180, "ease4": 1.5, "perDay": 9999, "hardFactor": 1.2, "minSpace": 1, "fuzz": 0.05, "ivlFct": 0.54}, "maxLife": 120, "mod": 1587920944, "usn": 0, "replayq": true, "autoAlert": 10, "recover": 5, "anotherRetreat": false, "enableDamage": false, "damage": 5}}', '{"1": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "id": 1, "name": "Default", "mod": 1587920915}, "1587920944097": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": true, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention", "id": 1587920944097, "mod": 1587920947}, "1587920944098": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear", "id": 1587920944098, "mod": 1587920944}, "1587920944099": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::renal", "id": 1587920944099, "mod": 1587920944}, "1587920944100": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::renal::other", "id": 1587920944100, "mod": 1587920944}, "1587920944101": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1587144167603, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::renal::other::renalbladdertumors", "id": 1587920944101, "mod": 1587920944}, "1587920944102": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::psychiatry", "id": 1587920944102, "mod": 1587920944}, "1587920944103": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::psychiatry::pharmacology", "id": 1587920944103, "mod": 1587920944}, "1587920944104": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1587144167603, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::psychiatry::pharmacology::antidepressants", "id": 1587920944104, "mod": 1587920944}, "1587920944105": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::pulmonary", "id": 1587920944105, "mod": 1587920944}, "1587920944106": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::pulmonary::introduction", "id": 1587920944106, "mod": 1587920944}, "1587920944107": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1587144167603, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::pulmonary::introduction::pulmonarycirculation", "id": 1587920944107, "mod": 1587920944}, "1587920944108": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::pulmonary::obstructiverestrictive", "id": 1587920944108, "mod": 1587920944}, "1587920944109": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1587144167603, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::pulmonary::obstructiverestrictive::obstructive", "id": 1587920944109, "mod": 1587920944}, "1587920944110": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1587144167603, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::pulmonary::obstructiverestrictive::restrictive", "id": 1587920944110, "mod": 1587920944}, "1587920944111": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::reproductive", "id": 1587920944111, "mod": 1587920944}, "1587920944112": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::reproductive::embryology", "id": 1587920944112, "mod": 1587920944}, "1587920944113": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 0], "conf": 1587144167603, "usn": 0, "desc": "", "dyn": 0, "collapsed": false, "extendNew": 10, "extendRev": 50, "name": "DecreasedIntervalPoorRetention::Lightyear::reproductive::embryology::teratogensone", "id": 1587920944113, "mod": 1587920944}, "1587920953716": {"newToday": [0, 0], "revToday": [0, 0], "lrnToday": [0, 0], "timeToday": [0, 15975], "collapsed": false, "dyn": 1, "desc": "", "usn": 0, "delays": null, "separate": true, "terms": [["is:due prop:due>-1", 100, 0]], "resched": true, "return": true, "previewDelay": 10, "name": "Filtered Deck 1", "id": 1587920953716, "mod": 1587921512}}');
```

1. Move card into a Filtered deck via search on "gold".
2. Press "Again"

###### Expected Result

From Anki Desktop
* 4 Ease Options: <20m, 30m, 17d, 18d

###### Actual Result

From AnkiDroid
* 4 Ease Options:  <15m, <18m, <20m, 17d

###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[x] I have searched for similar existing issues here and on the user forum

----

Anki Desktop dump:

```
>>> pp(self.col.sched.nextIvl(self.reviewer.card, 1))
... pp(self.col.sched.nextIvl(self.reviewer.card, 2))
... pp(self.col.sched.nextIvl(self.reviewer.card, 3))
... pp(self.col.sched.nextIvl(self.reviewer.card, 4))
pp(self.reviewer.card)
1200
1800
1468800
1555200
{'data': '', 'did': 1587926456564, 'due': 1587928085, 'factor': 1300, 'flags': 0, 'id': 1510928829863, 'ivl': 17, 'lapses': 6, 'left': 1001, 'mod': 1587926628, 'nid': 1510928805161, 'odid': 1587920944107, 'odue': 0, 'ord': 0, 'queue': 1, 'reps': 23, 'type': 3, 'usn': -1}
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## References

https://github.com/ankitects/anki/commit/5a5be92d099f28985e62631164dc3c0d3f59be35

https://github.com/ankitects/anki/blob/5a5be92d099f28985e62631164dc3c0d3f59be35/anki/schedv2.py#L1175

## Purpose / Description

User report: Lapse intervals were incorrect.

This was caused by two issues: using the wrong delay config (meaning that good wouldn't graduate the card), and missing a change in Anki which added an additional bonus when pressing Easy.

## Fixes
Fixes #6082

## Approach
TDD. Extract dependencies, get a broken test, and fix it.

## How Has This Been Tested?

Only unit tests

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedV2Test.java  1
- AnkiDroid/src/test/java/com/ichi2/testutils/MockTime.java  1
- AnkiDroid/src/main/java/com/ichi2/libanki/utils/SystemTime.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5422304&bid=17780545)

**Comment by david-allison-1** [comment]
Thought I found a bug in testing, turned out to be an after-effect from the original bug. Seems all good to go.

**Comment by david-allison-1** [comment]
Just occurred to me: Could this not be brought into the beta until a "Check Database" is added? This will leave cards stuck in "relearn" until the user presses "Easy".

**Comment by mikehardy** [comment]
Sure, it's on master now but not alpha'd out. I can either wait for a fixIntegrity addition before I do another alpha or revert, implementors choice.

**Comment by david-allison-1** [comment]
> Sure, it's on master now but not alpha'd out. I can either wait for a fixIntegrity addition before I do another alpha or revert, implementors choice.

Let's give it **n** days (3? maintainer's choice 😉), and revert if the fixIntegrity check isn't done by then so we don't hold up the alpha for too long. I'm not currently in the right headspace to be confident in dealing with the edge cases concerning modifying `left`. Maybe later on today or tomorrow.

**Comment by mikehardy** [comment]
roger roger. Will about pace with #5151 then I think. No problem

**Comment by mikehardy** [comment]
I received this just now locally, could be robolectric timing?

```
com.ichi2.libanki.sched.SchedV2Test > filteredDeckSchedulingOptionsRegressionTest FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.NullPointerException
            at com.ichi2.libanki.sched.SchedV2Test.filteredDeckSchedulingOptionsRegressionTest(SchedV2Test.java:96)

```

**Comment by mikehardy** [comment]
I'm going to revert this now - it's failing CI unit tests now. Strange it worked before, not sure what happened :shrug:

**Comment by david-allison-1** [comment]
> I'm going to revert this now - it's failing CI unit tests now. Strange it worked before, not sure what happened 🤷

Fixed in #6086. I missed mocking the `Utils` class, which had a static dependency on IO (current system time).

**Pull request merged**
