### PR TITLE
[KotlinCleanup] AbstractFlashCardViewer

### PR DESCRIPTION
**Pull request by n1snt**
## How Has This Been Tested?
- Unit Tests
- Tested on a physical device

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by n1snt** [comment]
Can anyone please tell me what is meant by "internal for AnkiDroidJsApi" in KotlinCleanup?

**Comment by n1snt** [comment]
And also what is meant by "remove _ variables"?
Either these KotlinCleanup messages are really cryptic or I'm not understanding them properly :|

**Comment by david-allison** [comment]
> And also what is meant by "remove _ variables"? Either these KotlinCleanup messages are really cryptic or I'm not understanding them properly :|

The `_` variables were resolved (lambdas with some unused parameters).

The `internal for AnkiDroidJsApi` means that the access modifier was changed from the Java for use of the `AnkiDroidJsAPI` class to access it.

Now both classes are in Kotlin, ask if there's a better pattern which would allow access to the variables, if so, then use it. If not, then remove the cleanup

**Review by david-allison — APPROVED** [review]

**Comment by n1snt** [comment]
@david-allison can this PR be marked as hacktoberfest-accepted?

**Comment by krmanik** [comment]
I think it should be, have registered / checked it on https://hacktoberfest.com
```
Have 4 pull/merge requests accepted between October 1 and October 31 to complete Hacktoberfest
```

**Comment by krmanik** [comment]
@n1snt I have added the label.

**Comment by n1snt** [comment]
Thanks a lot.

**Comment by david-allison** [comment]
(Absolutely, I strongly support Hacktoberfest)

**Pull request merged**
