### PR TITLE
Play videos in `<video>` tags by default instead of using a fullscreen activity

### LINKED ISSUE #14377: Play videos in `<video>` tags instead of playing it ourselves
`<video>` tags can be embedded in the page, be muted, paused and be looped, which is way better than our custom handling of videos which is always fullscreen and can't do any of those things.

---

note: I believe that it is best to keep handling `<audio>` manually because our current approach doesn't stop other sounds that are playing in the device, while `<audio>` tags stop them, which would make impossible having background music while studying.

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description

`<video>` tags can be embedded in the page, be muted, paused and be looped, which is way better than our custom handling of videos which is always fullscreen and can't do any of those things.

## Fixes
Fixes #14377

## Approach
Replace the [sound] elements which contain a video with a `<video>` tag

Note, the playback issues should be fixed with #14490 

## How Has This Been Tested?

Emulator 33

[Screen_recording_20230929_161059.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/f95b8311-477b-4098-b784-de0f8c90fb09)

## Learning (optional, can help others)

How to hide the download button in `<video>` tags
https://stackoverflow.com/questions/41115801/in-chrome-55-prevent-showing-download-button-for-html-5-video?noredirect=1&lq=1

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by dae** [comment]
I have not tested this, but I don't spot any obvious issues in the code, and it's nice to see more code removed.

**Review by lukstbit — APPROVED** [review]
Seems fine from my testing.
The fullscreen video player button is grayed out.

Also, it isn't possible to add two videos?

**Comment by BrayanDSO** [comment]
> The fullscreen video player button is grayed out.

Apparently, that needs some kind of custom handling in the webview (https://stackoverflow.com/questions/15796661/android-webview-app-wont-let-video-player-go-full-screen)

Not sure, so I'd like to keep that for another issue

> Also, it isn't possible to add two videos?

Fixed that

**Comment by lukstbit** [comment]
Fine, with the expectation to create an issue for the fullscreen problem.

**Pull request merged**
