### PR TITLE
Changed Material Dialog with Alert Dialog for CardBrowserMySearchesDialog.kt

### PR DESCRIPTION
**Pull request by Prince-kushwaha**
## Purpose / Description
Replaces usages of MaterialDialog with AlertDialog in CardBrowserMySearchesDialog.kt
## Fixes
Related to #13315 

## How Has This Been Tested?
Open each one of the changed dialogs on their respective preferences
## Screenshot
WhatsApp Image 2023-07-05 at 10 21 58 PM

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Please read the big heading in #13315

**Review by BrayanDSO — COMMENTED** [review]
Do we still need these lines below?
```
                dialog?.dismiss() // Dismiss the root dialog
                if (savedFilters!!.isEmpty()) {
                    dialog!!.dismiss()
```

**Comment by Prince-kushwaha** [comment]
`dialog?.dismiss()` is needed  to dismiss the root dialog(Saved Search Dialog)
but there is not need of
`                if (savedFilters!!.isEmpty()) {
                    dialog!!.dismiss()`
becouse root dialog is already dismissed in give condition

**Comment by Prince-kushwaha** [comment]
@lukstbit   review this PR

**Comment by lukstbit** [comment]
Ok, but this part inside the positive button click listener should be deleted:

```
if (savedFilters!!.isEmpty()) {
    dialog!!.dismiss()
}
```

as the dialog is unconditionally closed one line above.

**Review by lukstbit — APPROVED** [review]

**Comment by Prince-kushwaha** [comment]
@BrayanDSO review this PR

**Comment by Prince-kushwaha** [comment]
@david-allison review this PR

**Review by david-allison — APPROVED** [review]
Pending 2.17

**Pull request merged**
