### PR TITLE
refactor: remove duplicated icons and unused old statistics color attributes

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description
Part of #13878 

## Approach
Set `colorControlNormal` as the icon colors, which should look automatically good in both light and dark themes. Also this fixes the issue of having a black warning icon in dark themes

## How Has This Been Tested?

33 emulator: went some places in the app with the changed icons

(sync error)
image
image

(pin and attachment)
image
image

(warning)
image
image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
nice one!

**Review by david-allison — APPROVED** [review]
Tested on API 34 and API 21

API 34 didn't look good previously, but there's no further regressions

**Comment by BrayanDSO** [comment]
> Tested on API 34 and API 21

minSdk now is 23, so I guess that you mean 23

**Comment by david-allison** [comment]
I need to get to bed that was a silly mistake: 
API 24 (Android Version = 7.0)

**Pull request merged**
