### PR TITLE
feat: use the backend's congrats screen

### LINKED ISSUE #14361: Use the backend's congrats screen
Currently AnkiDroid has its own code for rendering the congrats screen. If it instead displayed congrats.html/js when the deck is finished, it would display the same text as the desktop version, and would allow the removal of some AnkiDroid-only code.

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #14361 
* Fixes https://github.com/ankidroid/Anki-Android/issues/14662

## Approach
Add the congrats screen from Anki Desktop.

Note that a part of the original screen isn't shown because we don't support (and [ideally shouldn't](https://github.com/ankidroid/Anki-Android/issues/14361#issuecomment-1701946364)) `bridgeCommand`, which is a legacy python-javascript bridge used in the desktop version.

I actually tried to do replace it with POST requests in the desktop's repo, but got some trouble when trying to build the string with a link calling the backend method in Svelte, which is probably due to my limited knowledge about Js/Svelte/How Anki Desktop works

So I left a TODO, which sould suffice for now

## How Has This Been Tested?

Emulator 31

[faded.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/d57f83ea-e475-496b-a2ef-f5fca3d87a2d)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Also, the screen should have some buttons like the Desktop version do. 

image

AnkiMobile doesn't have them explicitly as well, only under the gear with 300+ options in the reviewer, so moving the buttons to Svelte is the least resistance path IMO

**Review by david-allison — CHANGES_REQUESTED** [review]
Implementers choice (only if it's fast): can we style the background to match AnkiDroid's colour scheme?

* Also fixes https://github.com/ankidroid/Anki-Android/issues/14662

**Comment by BrayanDSO** [comment]
Done only the background color as a quick solution, which is the most noticeable one.

Ideally someone should spend some time looking at what color/class are applied to each element and try to match with our theme, which takes some time and patience.

[congrats.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/9b076c1f-5aaa-4091-8037-543c1c329007)

[black.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/a5266c21-3769-4a18-9933-e477eed7fdc3)

**Review by david-allison — APPROVED** [review]
Looks great, thanks!

**Review by mikehardy — APPROVED** [review]
LGTM - I'll work strings through

**Pull request merged**
