### PR TITLE
Kotlin Cleanup #1048 : Use listOf() instead of Java's Arrays.asList() in Count.kt

### PR DESCRIPTION
**Pull request by arpitmx**
#### Problem: Count.kt file required a Kotlin cleanup, successfully cleaned.

Issue : Kotlin Cleanup #10489
File effected(s) : Count.kt 
File link : https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.kt

#### Kotlin provide two methods for returning a list : 

1. Returning mutable lists whose elements can be changed.
> Method :  mutableListOf(i1,i2,i3..iN);

2. Returning immutable lists whose elements can't be altered.
> Method : listOf(i1,i2,i3...iN);

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in if statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Unused import:

/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.kt:19:1 Unused import

**Comment by arpitmx** [comment]
Okay got it! , let me clean those unused imports and commit again.

**Comment by SySagar** [comment]
can I work on it?

**Comment by mikehardy** [comment]
I don't understand how you are even able to commit these with kotlin lint errors - but it took another one
You must run ktlint locally before committing or the fix/repair cycle is needlessly long and wastes time
For that reason we have a check that runs automatically as a git hook to check the files, and it seems like you are disabling it or something, then not running lint locally?

> 
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/sched/Counts.kt:19:1 Needless blank line(s)

**Comment by mikehardy** [comment]
@SySagar asking to work on someone else's PR in progress when they have been responsive is a bit odd I think? Look for an issue that has available work still, not a PR already in progress please

**Comment by Jatin887** [comment]
@arpitmx can't we use arrayListOf<T>() instead of listOf() since it is more optimized for primitive datatypes and more memory efficient.

**Comment by Jatin887** [comment]
@mikehardy can i take up this issue?

**Comment by mikehardy** [comment]
@Jatin887 this is not an issue, it's someone else's PR, so it doesn't work that way.
I assume @arpitmx is busy at the moment unless they say otherwise - I think it's exam times etc? - so you'll have to find other "good first issues" in the issues list, there still were some yesterday, plus there are KotlinCleanup's all through the codebase if you pull current and do a search

**Comment by Jatin887** [comment]
> @Jatin887 this is not an issue, it's someone else's PR, so it doesn't work that way. I assume @arpitmx is busy at the moment unless they say otherwise - I think it's exam times etc? - so you'll have to find other "good first issues" in the issues list, there still were some yesterday, plus there are KotlinCleanup's all through the codebase if you pull current and do a search

No problem! I just thought he is not working on that

**Pull request closed without merging**
