### PR TITLE
Use manually translated language names instead of getting them from java libraries

### LINKED ISSUE #13259: Use manually translated language names instead of getting them from java libraries
Currently we build the languages list dinamically by retrieving the language names from their locales. The java locales library is well known for being problematic and has created some issues.

Below is the demo of the issue of languages having their names changed (here depicted by changing from english to japanese)
https://user-images.githubusercontent.com/69634269/218898599-d0fbf6e9-7406-4040-a6ad-a166f867584f.mp4

Here's another example. `Gothic` isn't how the gothic language is called in gothic
image

And here is a language that hasn't got its name built correctly, so it used its language code (tl is the code of Tagalog)
image

---

My suggestion is to add a string to `01-core.xml` to represent each language name on their respective languages

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
Fixes #13259

## Approach
1. Make the `System language` string to be translated to the system language
2. Retrieve language names from constants instead of building them dinamically with java methods

## How Has This Been Tested?

SDK 25 emulator

https://user-images.githubusercontent.com/69634269/219368631-8d3dfece-acd1-4e42-a664-73ad8c5ca0fb.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
To the next reviewer: approve, but do not merge

**Comment by BrayanDSO** [comment]
A thought came to mind to test it on my phone to if it was slow getting all the translations, as I had only tested it on the emulator. And guess what, it is (around 500ms delay on my phone I guess). Creating around 100 Context objects can be heavy, huh.

I'll try making the strings constants, as after all, the language names shouldn't change. I'll try flagging the ones without a current translation, like gothic, as well

**Review by david-allison — APPROVED** [review]

**Review by lukstbit — APPROVED** [review]
@david-allison Still want to hold on merging this?

**Comment by david-allison** [comment]
Good to go now the strings are removed

**Pull request merged**
