### PR TITLE
NF: simplify a query

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This was tested by opening stats and seeing the number didn't change

### CODE REVIEW

**Review by david-allison-1 — COMMENTED** [review]
What's the code from Anki Desktop? Can we add tests to ensure we're not changing functionality?

**Comment by Arthur-Milchior** [comment]
Upstream does not have a method `getNewCards`. I checked in current version and 2.1.15 (before rust)
It has `introductionGraph` which uses a similar query. The difference is that this method is used to plot a graph - in which case day by day data is indeed useful. While we don't plot graph, we only show the sum.

**Comment by Arthur-Milchior** [comment]
I just measured with and without the change, there is no noticeable change in speed according to stopwatch

**Review by mikehardy — APPROVED** [review]
if it still meets the required display amount and is not represented upstream, LGTM

**Pull request merged**
