### PR TITLE
Revert "only perform card action if card is same as when touch started (#8480)"

### LINKED ISSUE #8527: [Bug] Gestures for answer buttons don't work
###### Reproduction Steps

1. Enable gestures
2. Set some gesture action to an answer action (e.g. answer button 1, answer button 3, answer recommended, etc.)
3. Go to any deck and perform the gesture.

###### Expected Result
The answer action should be performed after the gesture.

###### Actual Result
The answer action is not performed after the gesture.

###### Debug info
Tested on both physical device and emulator.

Physical device info:
```AnkiDroid Version = 2.15alpha39

Android Version = 10

Manufacturer = samsung

Model = SM-A307GN

Hardware = exynos7904

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-A307GN Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 330c9b2a-f22f-47aa-a891-66352d287395

Scheduler = std

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

Emulator info:
```
AnkiDroid Version = 2.15alpha39

Android Version = 9

Manufacturer = Google

Model = AOSP on IA Emulator

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 9; AOSP on IA Emulator Build/PSR1.180720.117; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36

ACRA UUID = d28ce267-ee89-4faf-a3d4-3fc904411482

Scheduler = std

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
The issue only affects the latest alpha release. I was able to pinpoint the commit that creates the issue (https://github.com/ankidroid/Anki-Android/commit/559b3f1e47c1dbdb6395007b31592d311337e003).

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #8572: [Bug] Gestures not working since 2.15alpha40
###### Reproduction Steps

1. have gestures turned on
2. choose "recommended answer (green) for swipe left
3.  try to answer card with good (swipe left)

###### Expected Result

card is marked good, next card appears

###### Actual Result

nothing happens

###### Debug info
sorry, immediately uninstalled the alpha, so no debug info.  2.15alpha40 on Android 9

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
The commit:

* Blocked Gestures (Issues: #8527, #8572)
* Stopped Visual Feedback on Buttons (Issue #8583)

It didn't seem feasible to fix both of these at the same time.

## Fixes
Fixes #8527
Fixes #8572
Fixes regression in #8583
Reopens #4631

## Approach
reverts commit 559b3f1e (#8480)

## How Has This Been Tested?

Added Unit Test + tested on my phone

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by farjadilyas** [comment]
We may not need to revert! Please check: https://github.com/ankidroid/Anki-Android/issues/8583#issuecomment-817801198

**Comment by priyag99** [comment]
This is needed as the content shown should belong to the same card which is clicked.

**Comment by mikehardy** [comment]
Comments on #8583 indicate revert is not needed, if I understand correctly. Reopen and we can merge this if needed of course

**Comment by david-allison-1** [comment]
Superseded by #8579

**Pull request closed without merging**
