### PR TITLE
JS API: Get AnkiDroid version

### PR DESCRIPTION
**Pull request by infinyte7**
## Purpose / Description
Some JS API and other functions in card.js defined in 2.10 to 2.13. Also some features will be get added. It will help in making features showing / hiding depends on version without showing errors. Also, show message/toast to update AnkiDroid if deck version required greater version. 

## Fixes
Fixes _Link to the issues._

## Approach
Using Javascriptinterface and ```BuildConfig.VERSION_NAME```

## How Has This Been Tested?
Tested on Android emulator using chrome inspect.

To front/back side of card
```javascript
console.log(AnkiDroidJS.ankiGetAnkiDroidVersion());
```

version

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
https://stackoverflow.com/questions/4616095/how-to-get-the-build-version-number-of-your-android-application

## Checklist
_Please, go through these checks before submitting the PR._

- [ x ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ x ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ x ] You have commented your code, particularly in hard-to-understand areas
- [ x ] You have performed a self-review of your own code

### CODE REVIEW

**Comment by infinyte7** [comment]
I understand this. But all the information about function available at GitHub.

Let assume an user downloaded and imported the deck into outdated AnkiDroid. The cards don't display or there are no information available at the download page. And user will log the issues related to it. So, It will be helpful for deck developer to use it and target the functions to specific AnkiDroid version.

Is there way to get version info inside front/back side of card inside webview?

**Comment by david-allison-1** [comment]
```javascript
if (AnkiDroidJS.ankiGetCardDid) {
    // code here
}
```

**Comment by infinyte7** [comment]
> Would this work?
> 
> ```js
> if (AnkiDroidJS.ankiGetCardDid) {
>     // code here
> }
> ```
It gives did of card.

This is my current idea.
The function ```ankiIsTopbarShown()``` will be available in AnkiDroid 2.13. I as a deck developer use it develop some features inside my deck and shared it. User downloaded it and imported in AnkiDroid 2.12 and the features inside didn't work, and they may log issues at AnkiDroid issues page. **I can mention it on my github page about AnkiDroid version requirements.** But this PR will be helpful in disabling the features without breaking the card, also showing message about updating AnkiDroid.

**Comment by david-allison-1** [comment]
> > Would this work?
> > ```js
> > if (AnkiDroidJS.ankiGetCardDid) {
> >     // code here
> > }
> > ```
> 
> It gives did of card.

Maybe we're misunderstanding each other

You can perform an `if` on a function to see if it exists. 
`// code here` will only be executed if AnkiDroid has the `ankiGetCardDid` function.

**Comment by infinyte7** [comment]
Found another way to get this using ```try catch``` of javascript.
If using undefined function will give errors that can be used to hide the features.
It can be closed now.
Thanks,

**Pull request closed without merging**
