### PR TITLE
Sync Badge: Disable if app used < 10 days

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
Some users were complaining about email harvesting

Related: #6804

## How Has This Been Tested?
Tested on my device, code is in a try..catch

## Learning 

😢

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
Requesting for 2.13.3

**Comment by david-allison-1** [comment]
Getting a persistent CI failure: https://travis-ci.org/github/ankidroid/Anki-Android/jobs/729455758

https://github.com/ankidroid/Anki-Android/issues/7236

**Comment by mikehardy** [comment]
as mentioned on discord I appreciate the sensitivity to reviews, but in my case I think we offer a pref, and I would rather have UI features be rock-solid predictable, no hidden inner workings. If the dialog wording could be enhanced or something to say "We warn about this because data loss is such a serious risk. If you accept the risk and don't want the warnings you may easily disable the warning..."

**Comment by david-allison-1** [comment]
> as mentioned on discord I appreciate the sensitivity to reviews, but in my case I think we offer a pref, and I would rather have UI features be rock-solid predictable, no hidden inner workings. If the dialog wording could be enhanced or something to say "We warn about this because data loss is such a serious risk. If you accept the risk and don't want the warnings you may easily disable the warning..."

Sounds like a better approach

**Pull request closed without merging**
