### PR TITLE
Hotfix 2.8.5

### PR DESCRIPTION
**Pull request by GolamRabbany123**
## Pull Request template
The Main Problem

## Purpose / Description
_The Main Problem

(Plz Read All things including suggestion)
When I have to Study with Anki .I have to input  things from texbook to anki.That takes a lot of time. Some study materials like Chemical Reaction can't be on Anki. I searched a lot and found Image Occlusion Enhanced but I can't use it in Droid.I begged of the developers in anki forum,Support, github.They didn't even told me they will try to solve. I don't know Man. PC users can't even take pictures of not How will they use anki Image Occlusion protentially.So, to use AnkiDroid Potentially you must Add Occlusion.
It will:-
1) save a lot of time
2) Droid user can Study any material.(You app says learn anything)😒😒
3)If you add this  I bed there will be a lot more user and it could be the best app of playstore
.
😭😭😭

Some Suggestion:---
1)Plz Try one more time. I know you can you are a good developer. You will be able to add Addons on anki droid.

2)If addons don't support plz make another app ♠ Anki Addons♠.Where we can use addon.

3)If 1,2 doesn't not work, Plz make just the Image Occlusion In built in AnkiDroid 2.9

When I was first time learnt about spacing effect.I started using a anki .It's a great tool I am greatfull to it's developers.

After using it for some time it felt like I am giving it much time than actual study. Writting question and answer which is already in the text book seem like time waste.After long time use and downloading shared deck I was saving time. I had been using templates from shared decks.Oneday I came across ♥ Image Occlusion ♥ .
My heart leaped up seeing anki's protensial .I could read a chapter take notes and click photo's of the note and use anki to remember key points and facts from the note.I was happier than I could say and great full to you. I was searching for how to use it.

But sadness grounded me when I figured out that it can't be used on Android.

I have seen many apps that use plugin why can't Anki.Threre are some apps for which I have  to install extra plugin to make some features to work. Why can't anki????

Plz I beg of your developer plz somehow Install plugin option .😭😭😭😭😭
So that I can use Image Occlusion.
I bed there will more user of Anki in android than any other platform if you install Image Occlusion Enhanced.
Plz Plz Plz Give this message direct to the developer....

Another thing for Anki's good is Mind Mapping.Tony Buzan Mind Map has proven to be one of best study tool. If anki combines with 'Mindly'- Mind mapping App.
They will be the best study system of all.I have talked to the mindly Devrloper plz contact them if you want.

Super memo has suggested anki to use SM-11 Algorithm. What is  anki saying about that?

lastly You can I know you can. You are the best developer. You can  get Image Occlusion Enhanced to anki. All Android users are waiting.
Thank You.

_
wa
## Fixes
_Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
Are you seriously commenting here now? At this point I feel harassed. You have been answered nicely and also asked to stop. Please stop.

**Comment by mikehardy** [comment]
A pull request means actually implementing a feature in fresh code and asking to integrate the features you authored. Not to beg. Begging does not work in open-source. Work works.

**Comment by mikehardy** [comment]
I am closing this, and please know that I will report future requests without effort to implement the feature as abuse and I will flag the requests as such on the various platforms they are made. We all have more important things to do with our time. Should you honestly attempt an effort at implementing it, I will happily change my stance. Until then, please stop.

**Comment by mikehardy** [comment]
References to the same request

Play Store:
https://play.google.com/store/apps/details?id=com.ichi2.anki&reviewId=gp%3AAOqpTOE2u-scOA2nZbemHcEbEehZmwJQvhFbbChfm8qVLt0vnbie_YFy-RjOgpxVeFUeuysmrhCnobqZoy6ewnA

Mailing list:
https://groups.google.com/d/msg/anki-android/kLpU_jBUzik/MFNn9W0uCwAJ

Mailing list 2:
https://groups.google.com/d/msg/anki-android/EkGNkkjINz8/0Y5P7JxGCwAJ

Mailing list 3:
https://groups.google.com/d/msg/anki-android/zodFQf7G9Q4/g_qNNaeUCwAJ

**Comment by GolamRabbany123** [comment]
I don' t know how to code.
I just requested you to do that.It will make anki most usefull

**Comment by GolamRabbany123** [comment]
ol
I am sorry

**Pull request closed without merging**
