### PR TITLE
Various Rust cleanups

### PR DESCRIPTION
**Pull request by david-allison**
* Remove unused class
* Remove annotations which were no longer relevant

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
CI will pass/fail it, if passes it is not possible for it to be wrong, so +1

**Comment by mikehardy** [comment]
needs to be admin merge override for the squash, so marked pending merge to make sure I come back around to it or someone does

**Comment by david-allison** [comment]
I'm happy to squash, push + queue later

**Comment by mikehardy** [comment]
just went green, done ✅

**Pull request merged**
