### PR TITLE
6052 customize keys and gestures

### PR DESCRIPTION
**Pull request by svenmeier**
## Purpose / Description
Implementation of customizable keys, taking the AndroidStudios' UI for assigning keys as a role model.

Until now gestures are listed in the preferences, and each one can be configured with a viewer command. Now viewer commands are listed instead, and gestures *and* keys are assigned to them:

binding_preferences
add_a_key
add_a_gesture
add_a_binding

## Fixes
https://github.com/ankidroid/Anki-Android/issues/6052

## Approach
I've joined keys and gestures into common preferences. I've thrown out the preference "gestureCornerTouch" - as soon as one corner-tap is assigned to any viewer command, corner-touches are applied.

Viewer commands are now a Enum, to make them easier to handle. 
For this I had to change a lot of places, which makes this change larger than expected. I cleaned up AbstractFlashcardViewer and Reviewer by pulling out much of the gesture and key processing.

Key events are now generally handling in key-down, to be able to intercept media keys (e.g. volume-up/-down). I'm not sure why PeripheralKeymap used key-up instead.

I don't expect this to be merged right away but a basis for a solution instead.

## How Has This Been Tested?

I've ran Ankidroid's test cases an tested manually on my Android device.

Note that two tests for the currently fixed peripheral keymap fail at the moment - before adjusting these I'd like to get some feedback first:
PeripheralKeymap supported different keys for the question and the answer side. That could be added here too, but personally I don't see much value in it.

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas ... pending
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

**Comment by david-allison-1** [comment]
Gah - I was off for February and missed this. 

It's fantastic in theory. I'll get it working and in if @svenmeier isn't here

**Comment by david-allison-1** [comment]
Seems great! Needs some UX work, but the UI for the key selection is fantastic. Gestures is great, but likely needs extensions

The value in having different commands for the question and answers comes from requests with users with a very limited number of buttons (Bluetooth headphones for example)

Ctrl+Ctrl left is a strange gesture name

The defaults have been changed, which isn't ideal

I'm not sure if this works with only the 9 point touch. 

9 point touch divides the grid into squares, and the original touch system divides it diagonally corner to corner

It's a lot of code to digest in the first commit. It'd be ideal to split this out to make it more reviewable for others

I'll give this a look from a code perspective tomorrow

**Comment by svenmeier** [comment]
Hi, I'm still watching.

Thanks for your feedback. I wanted to hear opinions before working on these points:

* different commands for question and answers ... with a very limited number of buttons
Understood. Of course it is possible to keep this, we'll just have to decide how to integrate it into the configuration UI.

* The defaults have been changed
With restoring the previous point we can keep the prior defaults too.

* works with only the 9 point touch
Actually 9 point and corners touch both are still supported. It just switches between them automatically depending on presence of a binding to a corner.

I will rebase my code to current HEAD and work on these.

**Comment by svenmeier** [comment]
Sorry, as it seems I won't have time to work in this in the near future.

Feel free to use/reuse my proposal as you seem fit, or view it as a concept only.

**Comment by david-allison-1** [comment]
Understood, I'll use it for 2.16. Thanks for taking the time! 

Sorry about not getting to the initial review sooner

**Comment by JKya** [comment]
Thanks a lot
It would be really useful and comfortable for BT keyboard,gamepad,remote
controller,joystick.


2021년 5월 29일 (토) 18:01, David Allison ***@***.***>님이 작성:

**Comment by david-allison-1** [comment]
Only hooking up gestures to go

**Comment by chtx** [comment]
Hello. How is this coming along? I really would like to have this feature. As I understand it, it's still not available even in alpha version, right?

**Comment by mikehardy** [comment]
Keeping this one open, it's nearly at the of an odyssey of work but not done I think :-)

**Pull request closed without merging**
