### PR TITLE
[Kotlin Migration] ExtendedFragmentFactory 

### PR DESCRIPTION
**Pull request by codingtosh**
[Kotlin Migration] ExtendedFragmentFactory

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
```
com.ichi2.utils.ExtendedFragmentFactoryTest > testAttachToFragmentManager FAILED
    java.lang.NullPointerException: mBaseFactory!!.instantiate(classLoader, className) must not be null
        at com.ichi2.utils.ExtendedFragmentFactory.instantiate(ExtendedFragmentFactory.kt:50)
        at com.ichi2.utils.ExtendedFragmentFactoryTest.testAttachToFragmentManager(ExtendedFragmentFactoryTest.java:95)

com.ichi2.utils.ExtendedFragmentFactoryTest > willCallBaseFactory FAILED
    java.lang.NullPointerException: mBaseFactory!!.instantiate(classLoader, className) must not be null
        at com.ichi2.utils.ExtendedFragmentFactory.instantiate(ExtendedFragmentFactory.kt:50)
        at com.ichi2.utils.ExtendedFragmentFactoryTest.willCallBaseFactory(ExtendedFragmentFactoryTest.java:51)

com.ichi2.utils.ExtendedFragmentFactoryTest > testAttachToActivity FAILED
    java.lang.NullPointerException: mBaseFactory!!.instantiate(classLoader, className) must not be null
        at com.ichi2.utils.ExtendedFragmentFactory.instantiate(ExtendedFragmentFactory.kt:50)
        at com.ichi2.utils.ExtendedFragmentFactoryTest.testAttachToActivity(ExtendedFragmentFactoryTest.java:74)
```

**Comment by codingtosh** [comment]
> ```
> com.ichi2.utils.ExtendedFragmentFactoryTest > testAttachToFragmentManager FAILED
>     java.lang.NullPointerException: mBaseFactory!!.instantiate(classLoader, className) must not be null
>         at com.ichi2.utils.ExtendedFragmentFactory.instantiate(ExtendedFragmentFactory.kt:50)
>         at com.ichi2.utils.ExtendedFragmentFactoryTest.testAttachToFragmentManager(ExtendedFragmentFactoryTest.java:95)
> 
> com.ichi2.utils.ExtendedFragmentFactoryTest > willCallBaseFactory FAILED
>     java.lang.NullPointerException: mBaseFactory!!.instantiate(classLoader, className) must not be null
>         at com.ichi2.utils.ExtendedFragmentFactory.instantiate(ExtendedFragmentFactory.kt:50)
>         at com.ichi2.utils.ExtendedFragmentFactoryTest.willCallBaseFactory(ExtendedFragmentFactoryTest.java:51)
> 
> com.ichi2.utils.ExtendedFragmentFactoryTest > testAttachToActivity FAILED
>     java.lang.NullPointerException: mBaseFactory!!.instantiate(classLoader, className) must not be null
>         at com.ichi2.utils.ExtendedFragmentFactory.instantiate(ExtendedFragmentFactory.kt:50)
>         at com.ichi2.utils.ExtendedFragmentFactoryTest.testAttachToActivity(ExtendedFragmentFactoryTest.java:74)
> ```

I've been trying to get this sorted for the past few hours, but seems like after replacing the null assertion(!!) with other approaches, the test just gets ignored due to an internal jvm error. (class loader is not getting initialized). Here is what I have tried till now:
1. Used an elvis operator instead of the null assertion for a safe call. 
2. Used an intermediary immutable variable to store the value of mBaseFactory, call instantiate() on that to return. 
3. Used a let block.
4. Cleaned the directory.

But no dice, this is what  the log shows: 
```
 Internal Error (moduleEntry.cpp:263), pid=14773, tid=14779
#  guarantee(java_lang_Module::is_instance(module)) failed: The unnamed module for ClassLoader org.mockito.codegen.ClassLoader$MockitoMock$51222887, is null or not an instance of java.lang.Module. The class loader has not been initialized correctly.
```

The compiler is complaining that it is either null or not  an instance of java.lang.Module, 
I tried to make the fakeClassLoader non-null:
`@Nonnull private static final ClassLoader fakeClassLoader`,
 but it didn't solve the issue so it can't be because it was null. 

I am still looking at the output dump of tests both before conversion and after conversion, but haven't been able to spot what exactly is causing this. 

Looked online to see if others had run into the same problem, and If I understand correctly from [this thread](https://github.com/mockito/mockito/issues/1696) , mockito doesn't support mocking classloader? But it was running just fine before the conversion... 🤔

**Comment by david-allison-1** [comment]
Also having issues. Marking as a draft

**Comment by david-allison-1** [comment]
@codingtosh - lazy hack

```kotlin
/*
 *  Copyright (c) 2022 David Allison <davidallisongithub@gmail.com>
 *
 *  This program is free software; you can redistribute it and/or modify it under
 *  the terms of the GNU General Public License as published by the Free Software
 *  Foundation; either version 3 of the License, or (at your option) any later
 *  version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY
 *  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 *  PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with
 *  this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.ichi2.testutils

import androidx.fragment.app.Fragment

/** HACK: Mockito had issues with mocking a class loader: https://github.com/ankidroid/Anki-Android/pull/10048 */
class MockFragmentClassLoader : ClassLoader() {

    override fun loadClass(name: String?): Class<*> {
        if (name == FAKE_CLASS_NAME) return Fragment::class.java
        throw IllegalStateException("Only intended for class: '$name'")
    }

    companion object {
        const val FAKE_CLASS_NAME: String = "androidx.fragment.app.Fragment"
    }
}
```

```java
/*
 Copyright (c) 2021 Tarek Mohamed Abdalla <tarekkma@gmail.com>

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU General Public License as published by the Free Software
 Foundation; either version 3 of the License, or (at your option) any later
 version.

 This program is distributed in the hope that it will be useful, but WITHOUT ANY
 WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 PARTICULAR PURPOSE. See the GNU General Public License for more details.

 You should have received a copy of the GNU General Public License along with
 this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.ichi2.utils;

import com.ichi2.testutils.MockFragmentClassLoader;

import org.junit.Test;

import javax.annotation.Nonnull;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.FragmentFactory;
import androidx.fragment.app.FragmentManager;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

public class ExtendedFragmentFactoryTest {


    @Nonnull
    private static final ClassLoader fakeClassLoader = new MockFragmentClassLoader();

    static class TestFragmentFactoryTest extends ExtendedFragmentFactory {
        public TestFragmentFactoryTest() {
        }
        public TestFragmentFactoryTest(@NonNull FragmentFactory baseFactory) {
            super(baseFactory);
        }
    }


    @Test
    public void willCallBaseFactory() {
        final FragmentFactory baseFF = mock(FragmentFactory.class);
        final ExtendedFragmentFactory testFF = new TestFragmentFactoryTest(baseFF);

        testFF.instantiate(fakeClassLoader, MockFragmentClassLoader.FAKE_CLASS_NAME);

        verify(baseFF, times(1)).instantiate(fakeClassLoader, MockFragmentClassLoader.FAKE_CLASS_NAME);
    }


    @Test
    public void testAttachToActivity() {
        final AppCompatActivity activity = mock(AppCompatActivity.class);
        final FragmentManager fragmentManager = mock(FragmentManager.class);
        final FragmentFactory baseFactory = mock(FragmentFactory.class);

        when(activity.getSupportFragmentManager()).thenReturn(fragmentManager);
        when(fragmentManager.getFragmentFactory()).thenReturn(baseFactory);

        final ExtendedFragmentFactory testFF = new TestFragmentFactoryTest();

        final ExtendedFragmentFactory result = testFF.attachToActivity(activity);

        assertEquals(testFF, result);

        verify(fragmentManager, times(1)).setFragmentFactory(testFF);

        testFF.instantiate(fakeClassLoader, MockFragmentClassLoader.FAKE_CLASS_NAME);

        verify(baseFactory, times(1)).instantiate(fakeClassLoader, MockFragmentClassLoader.FAKE_CLASS_NAME);
    }


    @Test
    public void testAttachToFragmentManager() {
        final FragmentManager fragmentManager = mock(FragmentManager.class);
        final FragmentFactory baseFactory = mock(FragmentFactory.class);

        when(fragmentManager.getFragmentFactory()).thenReturn(baseFactory);

        final ExtendedFragmentFactory testFF = new TestFragmentFactoryTest();

        final ExtendedFragmentFactory result = testFF.attachToFragmentManager(fragmentManager);

        assertEquals(testFF, result);

        verify(fragmentManager, times(1)).setFragmentFactory(testFF);

        testFF.instantiate(fakeClassLoader, MockFragmentClassLoader.FAKE_CLASS_NAME);

        verify(baseFactory, times(1)).instantiate(fakeClassLoader, MockFragmentClassLoader.FAKE_CLASS_NAME);
    }
}
```

**Comment by codingtosh** [comment]
@david-allison-1 Thanks, works well. Should I make these changes in the conversion commit or a separate PR?

**Comment by david-allison-1** [comment]
> @david-allison-1 Thanks, works well. Should I make these changes in the conversion commit or a separate PR?

I'm happy with them in the conversion, given that they're unit tests.

As long as each commit passes individually, I'm happy

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Sorry for the nit:

Could you switch/squash commit 2 and commit 3, it's concerning to have a known compiler error in the git history.

**Comment by codingtosh** [comment]
Ah, sorry for the oversight. Done, ptal.

**Review by david-allison-1 — APPROVED** [review]
LGTM, thanks so much for the quick turnaround!

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
