### PR TITLE
Default Sibling Burying to 'Off'

### LINKED ISSUE #6236: SchedV1: Default Deck settings inconsistent with Desktop
A user has provided me with a deck: `Sketchy_Pharm` which contains note types with around 40 card templates in a deeply nested deck hierarchy.

On AnkiDesktop, selecting a given deck shows 15 cards from the note type, whereas on AnkiDroid, only 1 card would be shown before the deck ends. This is because related cards are not being buried in Anki Desktop

Tested and reproduced on AnkiDroid 2.8.4 ... 2.11alpha5

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

Done in Anki Desktop: Caused too much confusion to new users

https://github.com/ankitects/anki/commit/3b29bf6cba9092b518cf404ee4a5fbd3368c88d1

## Fixes
Fixes #6236

## Approach
Follow upstream

## How Has This Been Tested?

On my device

## Learning (optional, can help others)
I need to get better at isolating variables while debugging. Lots of missteps with the assumption that the name of the collection didn't matter, and assuming that import/replace failed

We need to have some way of tracking/communicating breaking changes upstream.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
This one would be handled by their Rust lib, so maybe a moot point

**Comment by mikehardy** [comment]
Exactly why I want the rust port (eventually, understanding it's a huge change) - maintaining a port of living software is the burden of sisyphus

**Comment by mikehardy** [comment]
Going out now as 2.10.3beta3 and 2.11alpha6

**Comment by timrae** [comment]
@mikehardy
I must say I strongly disagree with merging non-bug-fixes into the beta stream. There are not many rules in AnkiDroid, but this is one of them.

**Comment by mikehardy** [comment]
Hmm - For this specific PR the question is if shoring up anki ecosystem compatibility is a bugfix or not ? I think of ecosystem compatibility as our strongest constraint, that's why I picked this one.

I have a few that are more aggressive picks in this one which is why I actually did betas for 2.10.x vs just issuing it (like some of the 2.9.x and 2.10.1) - Looking at this list https://github.com/ankidroid/Anki-Android/milestone/21?closed=1 I would have chosen others for this criticism though - and it would be valid, at least one is an outright feature though it doesn't affect defaults. 

I am still strongly focused on releasing a whole lot more and a lot faster though, and this is part of that. I was thinking that 2.11 was going to go unstable almost immediately with Arthur's performance PRs and I wanted these out prior, but in practice those didn't merge because of the unexpected volume of unrelated bugfixes and fresh contributors and (perhaps attracted by the rush of activity + releases? I think so)., and I gave those priority. I should have just done 2.11.0beta I think in retrospect. Not too late actually, maybe I'll do that.

Not sure exactly where I'm going with this except to say I hear you and let you know how I'm tuned at the moment - so more clearly I'll say I interpret the increased contributor activity as evidence the increased merge + release cadence is a positive, so I want to continue that. I think the thing to do is to go for new release-branch minors (2.11, 2.12) more frequently rather than forcing things into patch versions.

**Comment by mikehardy** [comment]
I forgot you have your notification rules tuned tightly, and I did not tag you, so here is a tag @timrae and I spent time trying to respond clearly in the comment above :-)

**Comment by timrae** [comment]
@mikehardy 
I'm all for the increased frequency of releases. I think you've all been doing an excellent job and investing a lot of time into the project which is great. However I do strongly feel that we need to tread lightly with merging into point release branches, as all of our feature branches are pushed directly to the beta channel, which has quite a lot of users these days. Ideally releasing to one of these branches should be considered an emergency 'hotfix' effort to remedy a new issue that was introduced into master and cannot wait to go through the full testing cycle (alpha->beta->public), rather than just any old liberally interpreted bug fix which seems to have become the case (I think I'm guilty of starting this trend due to my own laziness and piling up of unreleased bug fixes).

It's quite painful, which is why I haven't really done much of it over the years, but if you are going to be doing a higher frequency of releases, I think there will be more and more cases where you might have merged one or more PRs into master and released them to the alpha stream, and you realise that those changes are a bit risky or not quite ready to be shipped to beta users, whereas there is a backlog of other changes that you want to release. In these cases you'd cut off a new major branch, revert any risky changes in the new branch, and set it to beta track. Then you bump the version of master up one version.

Another thing we can do (which should ideally be in addition to not instead of the above), is to wait a little bit before cherry-picking into a release branch to give alpha users a bit of a chance to test the changes before they get pushed to the beta channel.

As for this particular change, I feel that since it's a behavioural change (and a fairly big one at that), interpreting it as a bug fix is a bit too liberal of an interpretation. I haven't been through the changes in detail, but yeah if there are straight up features getting merged into the point releases I think you probably need to reign this in a bit.

**Comment by mikehardy** [comment]
@timrae yeah, I think we were actually doing pretty good with the incredible blizzard of crash fixes through 2.9.x and the first two 2.10's but you're totally right to call this out. I appreciate you keeping me honest. I got so comfortable with the release machinery and we've had so much success despite the velocity that I had strayed from solid release engineering discipline here. 

I'm going to shelve the current 2.10.3 (or pick it down to the minimum must-fix items for the last API15 people since 2.11 goes API16 as a minimum) then do 2.11alpha/beta with the current codebase.

I may feel differently later but branching post-hoc and reverting a couple things doesn't sound that bad? That's a good idea for release management as I had been conflating current master stability with ability to cut a release branch but of course git doesn't care about the when.

I have noticed with installed count on play store mgmt pages that it does take a few days for any release (alpha/beta/public) to achieve reasonable install counts even if I consider possible reporting lag, so I've been using 3 days as a "soak time" for a build confidence unless it's some obvious high value crash fix.

Alright, I'll combine this thinking and these tricks into some modified behavior and we'll go forward with it for a cycle or two and see how it pans out. It will result in more frequent minors branching off master but version numbers are free on the internet and hopefully it works well

**Pull request merged**
