### PR TITLE
Gut out the old themes

### PR DESCRIPTION
**Pull request by timrae**
* Enable ripple animation when clicking on Deck or Card in ListViews
 * Get rid of all of the non-night-mode Themes code
 * Update the remaining Dialogs to Material, except for TagsDialog which requires more work
 * Remove the "instant add" feature. 3rd party apps should make use of our ContentProvider instead. Additionally, the instant add functionality could easily be moved to an external app ("AnkiDroid card cache" or something) which stores the results and then adds them via the ContentProvider

### CODE REVIEW

**Comment by hssm** [comment]
Thanks a lot for doing this. We've been sitting on this for a little too long I think. Is it ready for merging?

**Comment by timrae** [comment]
Yup if you're happy to remove instant add.
Once the tags dialog is rewritten we can pull out `StyledDialog` completely

**Comment by hssm** [comment]
I have no issue with removing instant add if it's superseded by the ContentProvided. From now until we release 2.5 there should be enough time for anyone using it to update.

**Comment by timrae** [comment]
superseded is a bit too strong a word, but yeah we can outsource that cache now

**Comment by timrae** [comment]
@brunodea
Do you have any time to update the TagsDialog to material design?
I want to completely get rid of the `StyledDialog` class, so the check boxes should probably be implemented manually in the layout xml.

**Comment by brunodea** [comment]
@timrae yeah, sure! Later today I can start working on it.

**Comment by timrae** [comment]
@brunodea Thanks so much! By the way, if you could consider [issue 2168](https://code.google.com/p/ankidroid/issues/detail?id=2168) in terms of the implementation you choose that would be excellent!

**Pull request merged**
