### PR TITLE
New schema and coroutine fixes

### PR DESCRIPTION
**Pull request by dae**
First few commits focus on coroutines, the rest fix a few bugs with the new schema path.

Closes https://github.com/ankidroid/Anki-Android/issues/12179
Closes https://github.com/ankidroid/Anki-Android/issues/12224
Closes https://github.com/ankidroid/Anki-Android/issues/12223

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
A few `@NeedsTest` annotations for the fixes would be great, but nothing blocking, all looks great!

**Comment by dae** [comment]
I added a @NeedsTest for the play icon issue, though it can't be tested until the new schema becomes the default in CI.

**Review by mikehardy — APPROVED** [review]
I'm still okay with this, and I'd like to get a new alpha out soon, so re-pinging @david-allison then we can merge and I will shape up a release hopefully today

**Comment by mikehardy** [comment]
> it can't be tested until the new schema becomes the default in CI

It's possible to add a test now that asserts the new schema is in place, as a matter of local development
I'll add new schema (via local.properties) to our matrix in CI to start the process of exercising it regularly

**Review by david-allison — APPROVED** [review]

**Pull request merged**
