### PR TITLE
Add SchedV2.java class to support Scheduler v2

### LINKED ISSUE #4905: Add support for the new Scheduler v2 from Anki 2.1
###### Research

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum
***
~~I'm posting this issue because Anki 2.1 RC1 is released and I'm worried about the compatibility between the desktop version and Ankidroid once the stable 2.1 is out. I'm sorry if it is still too early to post this issue.~~

Anki 2.1 stable is now released. 

The 2 most notable changes in the new scheduler are:
- The improved behavior of the filtered decks. The progress of the Learning cards is no longer reset when they are moved between the original deck and a filtered deck.
- The improved behavior of the subdecks. When studying a master deck, the cards from the subdecks within are taken in the proper SRS order, rather than in alphabetical order, how it was in the old scheduler. In other words, now the subdecks are properly mixed and not just stacked on top of one another.

Switching to the new scheduler in the desktop version breaks the compatibility of the collection with Ankidroid. Damien added the support of the new scheduler to Ankiweb and Ankimobile after he introduced it to the desktop beta.

From my (layman) point of view, the following steps need to be taken:

1. Basic support for the synced collections with the new scheduler enabled in the desktop version.
2. Ability to switch between the versions of the sheduler right in Ankidroid.

The changes the new scheduler introduces create a lot of opportunities for the more creative and efficient use of the filtered decks and subdecks. I think many Anki users will agree with me that it would be great to see those new features supported in Ankidroid as well.

Edit: [here's the article](https://anki.tenderapp.com/kb/anki-ecosystem/experiment-scheduling-changes-in-anki-21) with a more in-depth description of the new scheduler.

Thank you!

### PR DESCRIPTION
**Pull request by ChrisPWill**
## Purpose / Description
The improved behaviour of the Scheduler v2 is highly desirable, in particular because of the improved behaviour of subdecks and filtered decks.

## Fixes
This tackles #4905 although this only really covers adding the SchedV2 file, it doesn't cover integration with the existing code.

## Approach
I've systematically gone through the differences between the two scheduler versions in the Python code and replicated each code change in the java files.

## How Has This Been Tested?

Currently there hasn't been any testing of this new file. As such, I wouldn't advise it to be used as is. I'm open for suggestions on how to test this file in isolation, although I suspect it would be better to test it by replacing the existing scheduler with it in a follow-up PR.

### CODE REVIEW

**Comment by ChrisPWill** [comment]
Will update PR based on auto review.

**Comment by mikehardy** [comment]
Wow! This is a great start. It is going to take me a little while to look through this, but this port is obviously the first step towards v2 support.

We have no test scaffolding around the original scheduler so I'm not sure how I'd start with testing but I can think of a couple ways. One would be to create a small test collection that has at least some of the cases SchedV2 is supposed to handle better (like sub decks etc as you mention) and run it through a series of reviews in Anki Desktop, then put a copy of the before / after collection in a place the tests can see them. Now you can have a test that asks this SchedV2 implementation to run against the same before database and make sure you get the same "after" state for card scheduling information. Kind of a black box assuming the individual operations aren't well understood

A second way would be to stay very low-level and figure out for any given card setup (maybe just starting with a couple of the sub-deck cases) what the effect of a review should be and doing before/afters like that. Or maybe a combo?

I just updated the information here to elaborate on the testing support I've just recently added to the codebase to make this more possible: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#running-automated-test

You can see some example use of the unit test capabilities on [the current work I'm doing on database upgrades](https://github.com/mikehardy/Anki-Android/blob/issue5106/database-migrations-2/AnkiDroid/src/test/java/com/ichi2/anki/DeckPickerTest.java) - this might be useful as you think about how to set up Card for review, do scheduling operations, then check state after.

I wouldn't say full coverage or even addition of automated tests is a requirement for merger but it certainly makes me feel more comfortable - especially for fundamental parts of the code base

Do you want to try starting a new unit test in one of the two styles and seeing if some of the basic operations work?

**Comment by mikehardy** [comment]
Great - I should warn that the first time you run jacocoTestReport (or jacocoUnitTestReport) it will cause robolectric to run, and that first run dynamically downloads all the android.jar implementations for the various API levels we use (at least 2) and if you've not done it before it can be surprisingly slow, with no user feedback. Subsequent unit test runs on a fast machine take a bit under a minute with individual unit tests taking maybe 5s a piece. Not a terrible development cycle. Feel free to holler if anything is a sticking point and I'll do my best to help

**Comment by mikehardy** [comment]
Since it has been a while even though v2 scheduler support is a very popular request and we'll need it - I just wanted to note that the main reason is that v2 scheduler wasn't on the plan for the AnkiDroid 2.9 release and I really really want to get that release out, so all the spare time I use for AnkiDroid is going there. Please don't take lack of motion here as lack of interest!

**Comment by hssm** [comment]
I will give this a full review within a week. :octopus:

**Comment by hssm** [comment]
@ChrisPWill Thanks for doing this. 

I found a few errors but otherwise the commit looks good. I'm happy to take over this feature from here.

If everyone is in agreement, I'd like to squash and merge this PR and I'll continue from there.

**Comment by mikehardy** [comment]
I think that's fantastic! Give the jacocoUnitTestReport gradle target a try with a look at the two unmerged PR series (template editor and database versions) in particular, they may offer ideas for testing of the v1 / v2 interoperability stuff upstream.

**Comment by hssm** [comment]
@mikehardy Thanks, I'll have a look. There are [tests from upstream](https://github.com/dae/anki/blob/master/tests/test_schedv2.py) that we can copy, but I didn't plan on porting that over myself.

@timrae Should be a simple setting that works exactly like the force-full-sync option. I was hoping to start out by supporting syncing and using the desktop client as the place to enable it, but the server rejects it based on the user agent. So for testing purposes I'll either copy the collection or spoof the user agent.

**Comment by ChrisPWill** [comment]
@hssm No worries and thanks for taking over! I wanted to finish this properly but as I'm moving to Japan shortly I ended up having less free time than I expected. As I've used Ankidroid heavily over the years I'll try and make further properly tested contributions in the future, probably choosing something a little less ambitious next time 😅

**Comment by timrae** [comment]
@ChrisPWill 
If you do have time to port the unit tests over from python that would help a lot to give some confidence before releasing this out to the masses! ;) Good luck with your move to Japan, myself and several other AnkiDroid developers are living here too :)

**Comment by ChrisPWill** [comment]
Absolutely, that's something I can do for sure. It'll probably have to wait a couple weeks until my last day at work though. 

Thanks, I've visited a few times in the past so I know the ropes, but it'll be an interesting experience moving for sure :)

**Pull request merged**
