### PR TITLE
NF: Remove TaskOperations

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
It's last use was remove in 189886a78245d935d6175cbd170fe26112935394

### CODE REVIEW

**Review by lukstbit — APPROVED** [review]

**Review by ShridharGoel — APPROVED** [review]

**Comment by mikehardy** [comment]
If there are any other branches in the main repo that may deleted, can you clean them out 🙏?

**Comment by Arthur-Milchior** [comment]
How do I look for such branches? In https://github.com/ankidroid/Anki-Android if I try "Switch branches/tags", and search "arthurmilchior" for example, it does not show anything, so I guess I can't just search for my name.

I assume that if you ask this it means that it's an issue for you. Can you help me understand why, because I was not expecting it to be noticeable in any way.

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/branches/active

Ideally branches should be in your fork, not on the main repo

**Comment by mikehardy** [comment]
> I assume that if you ask this it means that it's an issue for you. Can you help me understand why, because I was not expecting it to be noticeable in any way.

As a mostly command line user of git I will semi-frequently do `git branch -av` to see what's in play for me locally and remotely. Is it vital? It should not be. The best metaphor I can think of is maybe a pilot walking around an airplane before flying - ideally I don't see anything unusual, but maybe I see some branch that I had forgotten about and it is in a state I am not expecting or that I need to take action on. So having tidy branch lists is something I value.

It is not the most important thing in the world but as David says, ideally branches are in forks and things are tidy here, or at minimum if branches are created here they have the assumption of being cleaned up (merged + deleted or closed + deleted) within a reasonable time. What's reasonable? reasonable people disagree ;-) but I think you see my preference now at least. Thanks Arthur

**Comment by Arthur-Milchior** [comment]
To be clear, I was not arguing that your request is not reasonable. It was real curiosity, because I had no idea that it was even noticeable, so I understood there was part of github for me to discover.

**Pull request merged**
