### PR TITLE
Transparent intent handler

### LINKED ISSUE #3931: IntentHandler briefly appears on startup
From here: https://groups.google.com/d/msg/anki-android/DrMPHn9NQtk/A0iiZifNAgAJ

Since the default background is white, in night mode, it looks like a brief white flash when the application starts. Surely there's a way to hide the activity completely.

### PR DESCRIPTION
**Pull request by timrae**
Fix #3931 and a couple of small changes to the clickable areas in the deck list

### CODE REVIEW

**Comment by hssm** [comment]
if you open the studyoptions of a deck that has no cards due, there are no visible counts/details.

**Comment by timrae** [comment]
Ah thanks

**Comment by timrae** [comment]
Wait do you not mean that the counts are empty? 

If people are primarily using this feature to see the new deck counts, they probably want to be able to open the study options even when there are no cards due.

**Comment by hssm** [comment]
Let me use screenshots so we're on the same page.

Deck with cards due, counts are visible, all is well:
screenshot_20151203-223013

Deck with no cards due, you get a congrats screen with no counts visible:
screenshot_20151203-223019


>If people are primarily using this feature to see the new deck counts, they probably want to be able to open the study options even when there are no cards due.

I had exactly this in mind. But they see a congrats screen instead of the counts they were after. So what do we do now, show a congrats screen with counts?

**Comment by timrae** [comment]
Ah right, I was looking with an empty deck so didn't get what you meant. There could be enough space to keep showing the counts in the congratulations view, though that message can get pretty long. I'll try have a play around at some point. At least now it's doing the same as what it used to, so nobody can really complain... Although they probably will anyway.

**Pull request merged**
