### PR TITLE
Disable WAL by default

### PR DESCRIPTION
**Pull request by timrae**
I noticed in the logcat from the crash in #3794 that AnkiDroid was having trouble changing from WAL mode to ROLLBACK. Presumably the wal file became corrupted or too big or something. This prompted me to check if there was any performance difference when reviewing on my device, and I didn't find any.

So I propose disabling WAL by default and adding a setting to re-enable it if people are actually finding AnkiDroid slower without it. If nobody finds any significant difference then we could remove the setting before releasing.

I'd like to hear opinions on this change

### CODE REVIEW

**Comment by hssm** [comment]
I'm honestly not comfortable with making this change while we're so close to the release. There are a lot of unknowns that will take time (that we don't have) to try to understand or to be revealed through testing.

>Presumably the wal file became corrupted or too big or something

This is not the conclusion I would draw from `SQLiteDatabaseLockedException: database is locked (code 5): retrycount exceeded`. Now, I'm no SQLite expert, but I would be very confident in saying that in order to switch journal modes, any active connections to the database (something that WAL is designed to allow) need to be closed before the switch is made. To me, this exception is telling us that we have a connection that we are not closing properly before getting to this point (a coding error that is our fault that we need to fix). Since the default journal mode only allows sequential access, this same problem will simply manifest earlier, or worse, get stuck in a deadlock waiting for the other connection to close.

I would say it's best not to fiddle with things like this unless you are *sure* it is going to fix something.

**Comment by timrae** [comment]
> This is not the conclusion I would draw from `SQLiteDatabaseLockedException: database is locked (code 5): retrycount exceeded.`

I was talking about the logcat not the stacktrace, sorry for not linking to it:

0	--------- beginning of /dev/log/main
1	--------- beginning of /dev/log/system
2	10-31 21:47:09.026 I/AnkiDroid(24687): DeckPicker:: Sync button pressed
3	10-31 21:47:09.056 I/AnkiDroid(24687): Sync - starting sync
4	10-31 21:47:11.651 I/AnkiDroid(24687): Sync: getting meta data from server
5	10-31 21:47:11.666 I/AnkiDroid(24687): Sync: building local meta data
6	10-31 21:47:12.416 I/AnkiDroid(24687): Sync: collection removed data
7	10-31 21:47:12.421 I/AnkiDroid(24687): Sync: sending and receiving removed data
8	10-31 21:47:14.006 I/AnkiDroid(24687): Sync: applying removed data
9	10-31 21:47:14.006 I/AnkiDroid(24687): Sync: collection small changes
10	10-31 21:47:14.016 I/AnkiDroid(24687): Sync: sending and receiving small changes
11	10-31 21:47:15.661 I/AnkiDroid(24687): Sync: merging small changes
12	10-31 21:47:15.661 I/AnkiDroid(24687): Sync: downloading chunked data
13	10-31 21:47:18.131 I/AnkiDroid(24687): Sync: applying chunked data
14	10-31 21:47:18.176 I/AnkiDroid(24687): Sync: collecting chunked data
15	10-31 21:47:18.191 I/AnkiDroid(24687): Sync: sending chunked data
16	10-31 21:47:22.996 I/AnkiDroid(24687): Sync: sending finish command
17	10-31 21:47:25.311 I/AnkiDroid(24687): Sync: finishing
18	10-31 21:47:25.486 I/AnkiDroid(24687): flush - Saving information to DB...
19	10-31 21:47:27.891 E/SQLiteLog(24687): (5) statement aborts at 1: [PRAGMA journal_mode = DELETE]
20	10-31 21:47:27.896 E/SQLiteLog(24687): (5) statement aborts at 1: [PRAGMA journal_mode = DELETE]

**Comment by hssm** [comment]
Would those lines not be the retry attempts that the stack trace talks about?

**Comment by timrae** [comment]
Yes I believe so. I don't think your conclusions should necessarily be any different after seeing the logcat, I just posted it FYI.

**Comment by timrae** [comment]
> I'm honestly not comfortable with making this change while we're so close to the release.

Yeah I understand your hesitation of not wanting to put it out into the wild in v2.5, but we now have more than 700 beta testers, so I think it could be a good opportunity to at least run a temporary experiment to test any positive / negative affects of WAL. E.g. we could switch the default value of WAL to "true" before making the final release, while still getting some experimental results from our current pool of beta testers (this would give us the option to say to tell people reporting errors to disable it and let us know what happens). We could also remove the option entirely if needed.

> ...this exception is telling us that we have a connection that we are not closing properly before getting to this point (a coding error that is our fault that we need to fix)

Maybe, do you have any ideas? Brainstorming, some possibilities could be: The widget, the Android media scanner, parallel installs, the content provider.

>  Since the default journal mode only allows sequential access, this same problem will simply manifest earlier, or worse, get stuck in a deadlock waiting for the other connection to close.

Yeah it may well do, although there is a non-zero chance it could fix the problem, and if it does end up just manifesting itself earlier then the resultant stack trace / logcats could potentially give us a hint on how to solve the issue. If it were to get stuck I suspect the same error message would boil up "database locked: retry count exceeded". The worst case I can see is that a small number of syncs that wouldn't have worked anyway still don't work, whereas the best case is that it's fixed or gives us a clue on how to fix it.

**Comment by timrae** [comment]
> The worst case I can see is that a small number of syncs that wouldn't have worked anyway still don't work

Well I guess that's not really true as the *worst* case would be that there is some disastrous unforeseen consequence that nobody predicted that deletes everybody's data. But I think that's pretty unlikely since a) ROLLBACK mode was used fine until Anki 2, and b) libanki was built assuming ROLLBACK mode will be used. Also we can mitigate such possibilities by doing a staged rollout

**Comment by hssm** [comment]
Okay, you've convinced me that it's at least worth a trial. I have two concerns at the moment.

Firstly, since we don't close the database any more, what happens in this scenario?
1 - User reviews 100 cards
2 - User upgrades beta
3 - AnkiDroid opens DB in default mode

Do the 100 reviews that were sitting in the WAL file disappear? Does SQLite know to recover it? Does it automatically merge it in when the OS terminates the process while upgrading? I don't know.

The other "unknown" I mentioned is something I've wondered for a while but never bothered to look into. Hell, it could even be the cause of the problem all along. 

We make use of the [execSQL](http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#execSQL%28java.lang.String%29) method which has a comment about not touching the journal mode if we use `enableWriteAheadLogging()`. We *don't* use `enableWriteAheadLogging()` explicitly, but the documentation for *that* method mentions an alternative way to acitvate its behaviour with a flag when opening the database. Is turning WAL on through the PRAGMA commands yet another way to turn this on? Does it have the same meaning internally? If so, have we been doing something bad all this time?

Again, I don't know, and I think it'll take some time to figure all this out.

**Comment by timrae** [comment]
> Do the 100 reviews that were sitting in the WAL file disappear? Does SQLite know to recover it? Does it automatically merge it in when the OS terminates the process while upgrading? I don't know.

According to [the sqlite documentation](http://sqlite.org/wal.html), the changes are supposed to be written into the main db automatically when the last connection is closed:

> In normal cases, new content is appended to the WAL file until the WAL file accumulates about 1000 pages (and is thus about 4MB in size) at which point a checkpoint is automatically run and the WAL file is recycled. The checkpoint does not normally truncate the WAL file (unless the journal_size_limit pragma is set). Instead, it merely causes SQLite to start overwriting the WAL file from the beginning. This is done because it is normally faster to overwrite an existing file than to append. When the last connection to a database closes, that connection does one last checkpoint and then deletes the WAL and its associated shared-memory file, to clean up the disk.

So when the process is shutdown by the Android system before updating, the reviews should be committed. I just tested it on the emulator doing a bunch of reviews with WAL enabled, and then pushed an update with WAL disabled, by pressing the start button in Android studio while the reviewer was still open. We should definitely test this more, but it looks like it will be OK.

One thing I noticed though was that reviewing / new card limit was not obeyed when I did the force restart (irrespective of WAL setting). I.e. if my daily review limit is 200 but I have more than 200 cards available, I then review 50 cards and do a force update, and Anki is saying I have 200 cards left to review, while also saying I've reviewed 50 cards today. Any ideas on why this is, and whether or not we should try to fix it?

> We don't use enableWriteAheadLogging() explicitly, but the documentation for that method mentions an alternative way to activate its behaviour with a flag when opening the database. Is turning WAL on through the PRAGMA commands yet another way to turn this on? Does it have the same meaning internally? If so, have we been doing something bad all this time?

That method is available from API 11 and I agree we should be using it on newer SDKs. The flag is only available from API 16, and from my brief check of the android source code they both [finally end up setting the same pragma](https://github.com/android/platform_frameworks_base/blob/marshmallow-release/core/java/android/database/sqlite/SQLiteConnection.java#L317). 

Your question prompted me to take a close look at the AnkiDb source code and I realized that we were trying to set the PRAGMA after we had already disabled WAL (via `disableWriteAheadLogging()`), and #3794 was happening on the *second call*  (to `queryString("PRAGMA journal_mode = DELETE")`). From the [commit history](https://github.com/ankidroid/Anki-Android/commits/7b207cad7161bfce2debea0380a4aaf42bdeadd4/src/com/ichi2/anki/AnkiDb.java) it seems that was an unintended consequence of multiple people working on the same code. I've added a new commit that cleans this up, though I personally hope we can just get rid of this WAL mess altogether at some point if the performance is not noticeably different.

Btw, I just noticed that the commit() method in AnkiDb doesn't do anything... Is that intended? If so, we should really put some comments in there.

**Comment by timrae** [comment]
The second commit doesn't handle some edge cases properly, I'll push a new commit later

**Comment by hssm** [comment]
Thanks for testing it. If I have time I might try out a few things myself. Indeed, it would be less of a mess without all this work around WAL.

>Any ideas on why this is, and whether or not we should try to fix it?

I'm curious about this now. I think I will look into it first, if only because it sounds interesting. Maybe it'll lead towards some other problem.

>Btw, I just noticed that the commit() method in AnkiDb doesn't do anything... Is that intended? 

This is another thing that has been a mystery to me for a while. The reason it's empty is simply because the Android SQLite API doesn't have an equivalent commit() call to [the python one](https://docs.python.org/2/library/sqlite3.html#sqlite3.Connection.commit) which is what the desktop client calls in that method. 

We *do* have `setTransactionSuccessful() ` available but putting it into that commit() block just feels like really bad code, especially if we don't know what we're trying to do with it.

For some background, our undo system is completely different to the desktop client. Some time ago I looked into porting the code and stopped when I realised we didn't have a commit(). The desktop undo system makes use of [rollback](https://docs.python.org/2/library/sqlite3.html#sqlite3.Connection.rollback) for complex actions. This is the **only** thing I am aware of that the `commit()` call can be useful for. I don't think there are any open transactions anywhere in the application where `"This method commits the current transaction."` makes any sense. The Android API doesn't have a `rollback()` equivalent either.

**Comment by timrae** [comment]
OK I think this should be ready now, it only tries to query/write to the journal_mode pragma when the device SDK doesn't have a native method available. WAL is disabled by default, but can be enabled in advanced preferences, unless it's a Gingerbread device, where it's always disabled (as it's always been). WAL gets disabled whenever the Collection is closed (irrespective of the WAL preference), and gets disabled when the Collection is opened if WAL is enabled and the preference is disabled.

Before releasing we could do any of the following:
a) release in it's current form with preference disabled by default
b) set the new preference to enabled by default
c) remove the preference, strip out all WAL code and always use DELETE
d) remove the preference and always use WAL on API 11+
etc etc

@hssm 
Please have a play around, testing on a few devices and merge if you're happy to go ahead

**Comment by hssm** [comment]
Okay let's go ahead with it.

**Comment by hssm** [comment]
Also, I've answered my own question. Yes, SQLite *does* figure out on its own that it needs to checkpoint a WAL file. It does this before it even opens a DB regardless of the journaling mode we are about to set:

>11-03 11:02:51.874 21816-21883/com.ichi2.anki E/SQLiteLog: (283) recovered 104 frames from WAL file /sdcard/AnkiDroid/collection.anki2-wal

It's kind of obvious now that I think about it, since the WAL property is embedded in the database and not doing this is a recipe for data loss.

I couldn't reproduce the behaviour you mentioned about the daily limits. Not sure what is up with that.

**Comment by hssm** [comment]
Oh wait, it does do it if you start the debugger while still in the reviewer. I was going back to the deck picker first.

**Comment by hssm** [comment]
I understand what is happening with the reviewer limit thing. Basically, there is a deck value named `revToday` that counts up how many cards were reviewed for the day. If you close the reviewer normally, we end up doing a call to `UIUtils.saveCollectionInBackground()` which ensures the value gets saved. If you kill the process before then, that value is never flushed to disk.

The reviews themselves are saved correctly on each review, and the ministats uses data from the revlog table (I believe) so that was reporting the correct stats as well.

**Comment by timrae** [comment]
Ah makes sense, thanks for the explanation! Would it be worth doing a save in the onPause() method? IIRC there's an issue with the note editor as well, where it only saves the collection when the activity finishes, so if you added 100 cards without closing the note editor and then AnkiDroid got updated you might lose those 100 cards.

**Comment by hssm** [comment]
Might be worth doing. I think it's only a matter of how regularly we want to do it for efficiency.

**Pull request merged**
