### PR TITLE
Update api build.gradle to enable explicitApi()

### LINKED ISSUE #15705: API needs `explicitApi`
all our API files should require `public` due to `explicitApi`

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/15704#discussion_r1506084059_
            
https://github.com/Kotlin/KEEP/blob/master/proposals/explicit-api-mode.md

### PR DESCRIPTION
**Pull request by ro4i7**
## Purpose / Description
In this Explicit API mode , the Kotlin compiler does additional checks to ensure more explicit public API definitions. Test files are ignored as they aren’t part of the public API; the explicit API mode only applies to production code.

## Fixes
* Fixes #15705 

## Approach
Update api/build.gradle.kts

## How Has This Been Tested?

android studio emulator

## Learning (optional, can help others)
_Describe the research stage_

https://www.baeldung.com/kotlin/explicit-api-mode

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by neeldoshii** [comment]
Thanks you for the contribution @ro4i7. Can you have a descriptive commit about the changes made and also have a descriptive PR title?

**Review by david-allison — CHANGES_REQUESTED** [review]
You want this in the API module

**Comment by ro4i7** [comment]
> You want this in the API module

okay

**Review by david-allison — APPROVED** [review]
Looks good to me, thanks!

Needs a https://github.com/ankidroid/Anki-Android/labels/squash-merge (this can be done by maintainers, but @ro4i7, you should look into how this is done in future)

The commit message should also be improved by the squash

Screenshot 2024-02-29 at 08 29 41

**Comment by ro4i7** [comment]
> Looks good to me, thanks!
> 
> Needs a squash merge (this can be done by maintainers, but @ro4i7, you should look into how this is done in future)
> 
> The commit message should also be improved by the squash
> 
> Screenshot 2024-02-29 at 08 29 41

Sure @david-allison

**Review by lukstbit — APPROVED** [review]

**Pull request merged**
