### PR TITLE
Factorize deck pref

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
I was looking at #11417 and this led me to find far more duplication than I expected.
If it's too hard to review all at once, I can split. The last commit is the hardest one. 
The first few commits, by removing some nullability thanks to late init, are really nice by themselves. Then many commits are factorizing copy-pasted code and can be considered by themselves (but would conflict with the first ones)

### CODE REVIEW

**Comment by mikehardy** [comment]
Converting this to draft since it's not really an actionable PR from a review perspective, with the work split out into multiple little PRs

**Comment by Arthur-Milchior** [comment]
Conflict resolved

**Review by david-allison — APPROVED** [review]

**Review by david-allison — CHANGES_REQUESTED** [review]
```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt: (526, 22): Unresolved reference: getString
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt: (530, 23): Unresolved reference: mSummaries
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt: (532, 22): Unresolved reference: mSummaries
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.kt: (534, 29): Unresolved reference: mSummaries
```

**Comment by mikehardy** [comment]
@Arthur-Milchior this has some sort of compile error :thinking: ?

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
@Arthur-Milchior squash or rebase?

**Comment by Arthur-Milchior** [comment]
@david-allison Currently neither. You did the two approval. We should maybe wait for a review by someone else.
Later, rebase

**Review by lukstbit — APPROVED** [review]
Changes look good.

Aren't this classes going away when the new backend is implemented?

**Comment by Arthur-Milchior** [comment]
@lukstbit I had no knowledge about it, I admit that enough people seems to follow the new back-end that I don’t feel like I had to go read it

**Comment by dae** [comment]
The new backend code will have a large impact on the future of AnkiDroid development, so as someone who reviews other people's PRs, I'd recommend getting up to speed with it.

**Comment by Arthur-Milchior** [comment]
Any advice where to start reading about it?

**Comment by dae** [comment]
In this case it requires keeping track of active/merged PRs - https://github.com/ankidroid/Anki-Android/pull/12175 is the one that will introduce the new decks screen. 

Related info:
- https://github.com/ankidroid/Anki-Android/issues/11882
- https://github.com/ankidroid/Anki-Android-Backend/blob/main/docs/OVERVIEW.md

**Pull request merged**
