### PR TITLE
Adapted material design icon to the widget, changed round icon and add adaptive icon for Android Oreo

### PR DESCRIPTION
**Pull request by cydia2020**
Add the flat icon to the counter widget on desktop, as before, the icon design was kept, just changed the icon to be more adapting the launcher icon, which looks more ordered than before

### CODE REVIEW

**Comment by timrae** [comment]
Can you please post a screenshot of what the changes look like?

We'll also need you to provide the source file (e.g. *.svg)

**Comment by cydia2020** [comment]
It will be included in the next PR which I'm planning to do GMT+11 tonight :)

ありがとうございました
いけざきたくみ　より



On Mon, Oct 9, 2017 at 1:13 PM +1100, "Tim Rae" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please post a screenshot of what the changes look like?

We'll also need you to provide the source file (e.g. *.svg)

―

**Comment by timrae** [comment]
Thank you :) 
I think no need to open a second PR though, you can just push to this same branch.

**Comment by cydia2020** [comment]
Yep, forgot that, last time it was like that. Cheers. I'll attach the unfinished screenshot now probably, I haven't touched the badges yet, so it would probably looks a little bit screwed for now, planning to remove the badges edge and make it a little smaller.

[image](https://ibb.co/dYs01G)

**Comment by cydia2020** [comment]
I'm also planning to introduce adaptive icon to the app. But  it's gonna take sometime.

**Comment by cydia2020** [comment]
Hey Tim

All done, added adaptive icon for O, but I had to change the minSDKVersion, don't know if the users can stand that.

The screen shot of the icons are in the docs/marketing, check it out, personally on my phone, it looks SICK :D 

Cheers

**Comment by cydia2020** [comment]
Also, from what I observed, changing the minSDK back to 8 and 10 doesnt affect the icon, but interestingly, my Pixel XL (which have a collection in it) can open anki successfully, my Nexus 5X (newly installed for testing) doesn't have a collection (ankidroid folder), more interestingly, after i copied the Pixel collection to my 5X, it starts work. I don't know whether it's regard to the icon (api) changes and the building tool changes, or the beta version of anki. Please investigate that before merging incase something goes wrong (but I guess you can reverse it anytime anyway) 

Cheers

**Comment by cydia2020** [comment]
Seems the problem of stablility issue can be fixed by changing the api build tool version. Mine is working perfectly now without any issues. More observations are needed.

**Comment by cydia2020** [comment]
Still crashes in some circumstances, but no more crashes up on launch, I think it's still the build tools' problem since I had to upgrade the build tool version to 26.0.2. I tried to logcated it, but the problem haven't been since then, still need more observations. Maybe you can come up with something 👍 :-)

**Comment by cydia2020** [comment]
Also, what would you say about this icon, the 追加 widget
http://ibb.co/eQHrab

**Comment by timrae** [comment]
FYI: `minSdkVersion` is supposed to be 14 now

**Comment by cydia2020** [comment]
Thank you for the info, I'll do more tests



On Tue, Oct 10, 2017 at 7:11 PM +1100, "Tim Rae" <notifications@github.com<mailto:notifications@github.com>> wrote:


FYI: minSdkVersion is supposed to be 14 now

**Comment by cydia2020** [comment]
I can let the problem reappear by locking the screen
10-10 21:12:53.782   796   810 I ActivityManager: Waited long enough for: ServiceRecord{7e03168 u0 com.ichi2.anki/com.ichi2.widget.AnkiDroidWidgetSmall$UpdateService}
10-10 21:13:38.627   796   810 W ActivityManager: Stopping service due to app idle: u0a99 -1m13s402ms com.ichi2.anki/.services.NotificationService
10-10 21:13:38.627   796   810 W ActivityManager: Stopping service due to app idle: u0a99 -59s853ms com.ichi2.anki/com.ichi2.widget.AnkiDroidWidgetSmall$UpdateService

Probably something with the widget or with the compiler that miscompiled something? Do you have and idea about this?

Cheers

**Comment by cydia2020** [comment]
Another logcat piece, catched when the app was upgraded
10-10 22:33:05.605   899  2220 I ActivityManager: START u0 {flg=0x10000000 cmp=com.ichi2.anki/.dialogs.AnkiDroidCrashReportDialog (has extras)} from uid 10397
10-10 22:33:05.624 16116 16148 D ACRA    : Wait for Toast + worker ended. Kill Application ? true
10-10 22:33:05.624 16116 16148 E ACRA    : com.ichi2.anki fatal error : Unable to create application com.ichi2.anki.AnkiDroidApp: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.ichi2.anki/.services.BootService }: app is in background uid UidRecord{2f300d8 u0a397 RCVR idle procs:1 seq(0,0,0)}
10-10 22:33:05.624 16116 16148 E ACRA    : java.lang.RuntimeException: Unable to create application com.ichi2.anki.AnkiDroidApp: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.ichi2.anki/.services.BootService }: app is in background uid UidRecord{2f300d8 u0a397 RCVR idle procs:1 seq(0,0,0)}
10-10 22:33:05.624 16116 16148 E ACRA    :      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
10-10 22:33:05.624 16116 16148 E ACRA    :      at android.app.ActivityThread.-wrap1(Unknown Source:0)
10-10 22:33:05.624 16116 16148 E ACRA    :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
10-10 22:33:05.624 16116 16148 E ACRA    :      at android.os.Handler.dispatchMessage(Handler.java:105)
10-10 22:33:05.624 16116 16148 E ACRA    :      at android.os.Looper.loop(Looper.java:164)
10-10 22:33:05.624 16116 16148 E ACRA    :      at android.app.ActivityThread.main(ActivityThread.java:6541)
10-10 22:33:05.624 16116 16148 E ACRA    :      at java.lang.reflect.Method.invoke(Native Method)
10-10 22:33:05.624 16116 16148 E ACRA    :      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-10 22:33:05.624 16116 16148 E ACRA    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-10 22:33:05.624 16116 16148 E ACRA    : Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.ichi2.anki/.services.BootService }: app is in background uid UidRecord{2f300d8 u0a397 RCVR idle procs:1 seq(0,0,0)}
10-10 22:33:05.624 16116 16148 E ACRA    :      at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
10-10 22:33:05.624 16116 16148 E ACRA    :      at android.app.ContextImpl.startService(ContextImpl.java:1461)
10-10 22:33:05.624 16116 16148 E ACRA    :      at android.content.ContextWrapper.startService(ContextWrapper.java:644)
10-10 22:33:05.624 16116 16148 E ACRA    :      at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:203)
10-10 22:33:05.624 16116 16148 E ACRA    :      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
10-10 22:33:05.624 16116 16148 E ACRA    :      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)

**Comment by cydia2020** [comment]
Seems the error is gone now for some reason, the workaround is to disable 電源最適化 for Anki in Android 7.0+, depend on you, should you accept the PR or not.

Cheers

**Comment by cydia2020** [comment]
https://photos.app.goo.gl/g06dODhDeWTHk5sl1

It looks like this now with the last icon be the adaptive icon and can be changed by the OEM or by the users if the OEM enables the feature. If you accepted the PR, would you please edit the time and count a little bit outward cause I cannot figure it out how to do it?

Thanks

**Comment by timrae** [comment]
Maybe for this PR we can just focus on updating the widget without including the adaptive icon?
It seems that your pngs are cropped too far...? E.g.

https://github.com/cydia2020/Anki-Android/blob/7a54e579c077193cd1413b616116d36583d84409/AnkiDroid/src/main/res/mipmap-xxhdpi/anki_round.png

**Comment by cydia2020** [comment]
Of course, but this is on the OEM, the OEM decides how far the crop goes. If you see the foreground and background files, they were not cropped.

More info about adaptive icon
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by cydia2020** [comment]
This is probably better?

**Comment by cydia2020** [comment]
Seems you're right, the padding is a little bit aggressive on the first icon, I've changed it now, it looks a lot better 👍

**Comment by timrae** [comment]
I'm really sorry, but would you be able to separate this into two pull requests please? I'd recommend to start with the new widget, which we can merge quickly if the screenshots look good :) For the adaptive icon, I need to do some reading and we need to figure out why the unit tests are failing, so let's first get the widget merged.

**Comment by cydia2020** [comment]
Okay, I'll do that Tuesday. Exams running ;)

Outlook for Android<https://aka.ms/ghei36> ??取得

________________________________

**Comment by timrae** [comment]
Great, thank you!

**Comment by cydia2020** [comment]
Seems you are really busy :), I'll close the PR now. And create a new PR ASA I've done the thing.
どうも

**Pull request closed without merging**
