### PR TITLE
 fix hang importing decks

### LINKED ISSUE #13880: App hangs up when importing
###### Reproduction Steps

1. Import a deck.
2. Change focus from app (turn off screen or switch to another app)
3. App hangs up

###### Expected Result

Importing should continue normally

###### Actual Result

App hangs up, importing prpgress will be lost as you have to kill the app

###### Debug info

AnkiDroid Version = 2.16.0beta2

Android Version = 12

ProductFlavor = full

Manufacturer = realme

Model = RMX2170

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; RMX2170 Build/SKQ1.210216.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.76 Mobile Safari/537.36

ACRA UUID = 2faedfa9-8c35-433f-be34-c02a5473aea9

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Fixes
- Fixes #13880

## Approach
* bypass the queue when checking the status of the collection

## How Has This Been Tested?
Physical device: S21

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by oakkitten — CHANGES_REQUESTED** [review]
At the **_very_** least this needs commentary.

Also, what does “Unsafe” mean? The method seems safe to call.

In the end of the day, I'm not exactly sure what this code does. “If we're OK, return null”—what exactly does this check for? What is “OK”? I **_strongly_** suggest refactoring this to make it clear what's going on. Please... 🥺

Also I suggest renaming the method containing the code. `getStartupFailureType` implies the existence of a failure. I suggest refactoring to remove `StartupFailure` altogether. It seems that you can easily split it into methods such as `ensureThereIsEnoughFreeDiskSpace` etc and maybe raise `TranslatableException` or something.

**Comment by oakkitten** [comment]
As I suggested before, we probably should have separate mechanisms of locking the collection for writing (only one client can write) and for reading (multiple clients can read). 

Also we might want to rely on synchronization instead of doing all operations from one thread. This will allow simplified and faster collection access, as well as calling coroutines inside `withCol`, but needs to be done very carefully.

Finally, some of the commonly queried state (sync state, deck list) should be cached if it's not possible to get from the backend fast. (`viewModel` + `StateFlow` is a good choice here.) Instead of fetching the state (and potentially locking the UI), trigger the refresh by launching a coroutine that emits to the flow. Never a frown with `StateFlow`.

**Comment by dae** [comment]
> Finally, some of the commonly queried state (sync state, deck list) should be cached if it's not possible to get from the backend fast. (viewModel + StateFlow is a good choice here.) Instead of fetching the state (and potentially locking the UI), trigger the refresh by launching a coroutine that emits to the flow. 

The sync status is already cached, since Android expects the menu building/updating operation to run synchronously. I think the deck list is already stored in memory in some form as well, though I don't know if DB queries are being invoked to look up certain info. To clarify my earlier statement: I think having screens fetch data + read from the stored data is a reasonable approach; what I think is less viable is trying to add more caches to the libanki level.

>  I think it's the first db call(in model.flush()) that hangs).

The DB adaptor and the backend both protect access with mutexes. If legacy code is performing a long-running operation on the collection outside of withCol, that will cause any DB operations/backend methods invoked by other threads to block until the first operation completes, whether or not it has been run inside withCol. It should not hang indefinitely though - is it possible something was still accessing the DB?

**Comment by oakkitten** [comment]
> as no readers can safely read during the course of a mutation

Why not? As long as the API returns data that is actively being mutated at the moment, it should be safe to use. The data might not be up to date but the subsequent update should fix that.

> needs to be done at the Rust layer

Why? It would be a better API I guess but it doesn't have to be no?

> Every time you introduce another cache, you increase the likelihood of new bugs caused by the cache not being correctly updated or invalidated when changes are made, so they need to be used judiciously.

Broadly speaking, view model-level caching is pretty common. If you don't have it, every time the UI is invalidated in a substantial way you will not have anything to display until the data is fetched, which leads to flicker unless your data repository has a way of providing data fast and in sync. And in some situations you have to factor in the possibility of the repository being busy. 

I'm not advocating for any specific caching but not everything can be solved by not running database operations on main thread. It's easy enough to run into all sorts of race conditions and other synchronization issues even if you only use one thread.

> Regarding your comments on David's changes, your comments feel like they are more directed at the legacy code that David is trying to quickly fix, instead of the fix itself.

While I do think we should aim for a long-term solution here, it's not like I am against a quick fix. But this really needs at least a comment. I don't know what's going here.

**Comment by lukstbit** [comment]
> is it possible something was still accessing the DB?

I think the deadlock is happening at sqlite level due to transactions done on different threads(withCol vs collection task background thread) which will block each other. This would explain why using withCol for the importing task succeeds.

I recommend as a solution that my old PR( #12799) to move from the ImportAdd task to a coroutine is reviewed and merged. I rebased and fixed all conflicts and tested the code. With the code in my PR the import action works when the import is started and the app is sent to the background and back to foreground. In this case the UI will still freeze when coming back but it will resume when the import finishes(this is happening on the new backend as well and is expected as we serialize collection access).

**Comment by dae** [comment]
> > as no readers can safely read during the course of a mutation

> Why not?

For the same reason you can't modify a list you're iterating over: reading from non-atomic values that are undergoing mutation results in undefined behaviour.

Also when caching is introduced, read operations are often actually write operations, as you need to be able to mutate the cache if it is missing an entry.

>> needs to be done at the Rust layer

> Why?

Because the Rust layer is protected by a mutex for the above reasons. No point running the code above it in parallel if the calls into it will be serialized anyway.

> It's easy enough to run into all sorts of race conditions and other synchronization issues even if you only use one thread.

Presumably you mean "one thread other than the UI thread" here. Yes, if one is not careful, it is possible to introduce race conditions by updating data on one thread that another thread will read. Most of those issues can be avoided by ensuring the UI, and any state the UI wishes to access, is only ever updated on the UI thread. Data can be safely fetched in a background thread, but the UI state/cached data must only ever be updated on the UI thread, to ensure changes are made atomically.

**Comment by mikehardy** [comment]
I think since #12799 was merged after discussion here (thanks @lukstbit ) this is no longer needed, so I'm going to close to clear the PR queue and our mental burden of what PRs are important...

reversible action (so please reverse if I'm wrong...) but as I understand it, this is now moot

**Pull request closed without merging**
