### PR TITLE
fix custom study session is empty on  "Limit to particular tags"

### LINKED ISSUE #14537: [BUG]: "Custom study -> Limit to particular tags" not working with v3 scheduler
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Enable V3 scheduler.
2. select "Custom Study" and "Limit to particular tags" and add cards to Custom study session.
3. But, actually, these cards won't b added to it.

### Expected behaviour

These cards shold be added correctly.

### Actual behaviour

Cards are not added to Custom Study session and it is empty.

### Debug info

```text
AnkiDroid 2.6.15
useing V3 scheduler
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by S-H-Y-A**
## Purpose / Description
Custom study session is empty on creating it with "Limit to particular tags" on V3.

## Fixes
* Fixes #14537

## Approach
the process of creating search terms was wrong and fix it.

## How Has This Been Tested?
AnkiDroid Version = 2.17alpha5-debug (80227afe829169b1147d0863330b8085ab019f86)
Android Version = 13
ProductFlavor = amazon
Manufacturer = asus
Model = ASUS_X01BDA
Hardware = qcom

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
Wow, great catch!

nit (non-blocking): add `@NeedsTest("14537: limit to particular tags")` to ensure we have regression cover here

**Comment by david-allison** [comment]
build failures are non-blocking, `main` is failing

**Review by david-allison — APPROVED** [review]
I like this so much I'm approving it twice, thanks!!

**Review by lukstbit — APPROVED** [review]
LGTM, thank you for the contribution!

**Pull request merged**
