### PR TITLE
Fixes for Navdrawer, Actionbar, DeckPickerContextMenu

### PR DESCRIPTION
**Pull request by eginhard**
Change Navdrawer from ListView to Linearlayout for easier theming.
Fix issues with selected deck in DeckDropdownWidget, it's now centrally managed in NavigationDrawerActivity whether the whole collection or a deck is selected.
Include Toolbar in DeckPicker layout for large devices.
Show 'Collapse Subdecks' option in DeckPickerContextMenu only when relevant.

### CODE REVIEW

**Comment by timrae** [comment]
Opening settings from the reviewer and then closing it leads to us getting booted back to the DeckPicker

**Comment by eginhard** [comment]
I shouldn't have changed anything to that behaviour, but I'm not exactly sure what you mean - did you get back to DeckPicker when you shouldn't or you didn't when you should have?

**Comment by timrae** [comment]
Back to the DeckPicker when I shouldn't have. 2.5alpha19 is fine, whereas this branch does it everytime.

**Comment by eginhard** [comment]
I managed to see it twice on the emulator, but I can't reliably reproduce it. On which SDK+device are you?

**Comment by timrae** [comment]
I haven't tested on a real device, just running in the emulator on SDK 19 and SDK 22

**Comment by timrae** [comment]
It happens because `mOldColPath==null`

**Comment by eginhard** [comment]
Ok, but I don't understand why this becomes null or why I don't encounter this. Do you have any idea?

**Comment by timrae** [comment]
Thanks for checking the reproducibility, it turns out that I had forgotten to turn off "don't keep activities" in the advanced Android settings after I turned it on for fixing Window Leaked exceptions. I did experience the same issue in another emulator, but I don't think it's related to this change.

**Comment by eginhard** [comment]
Thanks a lot for checking! Better safe than sorry. :)

**Pull request merged**
