### PR TITLE
[GSoC] Add `Developer options` category

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description
Move options exclusive to debug builds to its own category from the bottom of advanced category. 

## Approach
1. Create a XML layout with the previous debug options
2. Extract the debug options from the advanced category to the new one

## How Has This Been Tested?

https://user-images.githubusercontent.com/69634269/171644357-8adf8cf9-bd03-4f4d-b124-ffcb66fd3286.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Works for me, doesn't affect normal users, cleans things up for devs

**Review by david-allison — CHANGES_REQUESTED** [review]
Minor nitpick, then looks good to go!

I'm testing this on my phone currently

**Review by david-allison — COMMENTED** [review]
I've tested and I like this

**Comment by mikehardy** [comment]
emulator flake is https://github.com/ReactiveCircus/android-emulator-runner/issues/192 - unrelated to PR, restarting

**Review by david-allison — APPROVED** [review]
LGTM. I'm on my phone, merge at will if CI is happy

**Pull request merged**
