### PR TITLE
Correct Device "Back" Button in Restore From Backup

### LINKED ISSUE #5833: Restore From Backup - Pressing Device "Back" Button should return to Deck Browser
###### Reproduction Steps

1. Open Deck Browser
2. Select "Restore From Backup"
3. Accept the confirmation
4. Press the physical "Back" button on the device.

###### Expected Result

The user returns to the deck browser

###### Actual Result

The user is re-shown the confirmation to restore from backup.

This works correctly when using the "Back" button on the dialog.

###### Debug info
AnkiDroid Version = 2.10alpha50

Android Version = 9

ACRA UUID = 5a0ff95e-d1bb-46d6-9a61-d425ab3ab53d

###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[x] I have searched for similar existing issues here and on the user forum

----

Simple issue for someone to get familiar with the project

### PR DESCRIPTION
**Pull request by Sc-Weng**
## Purpose / Description

Now, AnkiDroid can return to deck browser successfully when visit "Restore From Backup" Dialog while the previous version will return to the confirmation dialog.

## Fixes
Fixes #5833

## Approach
For MaterialDialog, adding a Listener by setOnKeyListener() can moniter system's back key. Rewrite system back key operation by method dismissAllDialogFragments() which make its function same as button "Cancel".

## How Has This Been Tested?

1. Open Deck Browser
2. Select "Restore From Backup"
3. Accept the confirmation
4. Press the physical "Back" button on the device.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
Hi @Sc-Weng,

Thanks for the contribution!

Feel free to reopen this and rebase your change onto master, you typically don't need to close a pull request if there's changes to be made

**Comment by Sc-Weng** [comment]
@david-allison-1 Sorry that I think I may use a wrong version, so I am trying to open a new PR.

**Comment by david-allison-1** [comment]
Don't apologise at all. 

I can't see your contribution in the history, but:

* You should select `master` when creating a pull request (you can edit an open PR if you forget to do this).
* You should aim to start the pull request at the `HEAD` of master. It's likely that other PRs will be merged in before you finish. You rarely have a few conflicts to resolve, but it's normally plain sailing.
* If you do get conflicts, rebase your commits onto the new master via Android Studio

**Comment by Sc-Weng** [comment]
> Don't apologise at all.
> 
> I can't see your contribution in the history, but:
> 
> * You should select `master` when creating a pull request (you can edit an open PR if you forget to do this).
> * You should aim to start the pull request at the `HEAD` of master. It's likely that other PRs will be merged in before you finish. You rarely have a few conflicts to resolve, but it's normally plain sailing.
> * If you do get conflicts, rebase your commits onto the new master locally, and force push with-lease back to your PR branch

But how do I specify a version such as 2.10 if I select master?

**Comment by david-allison-1** [comment]
> But how do I specify a version such as 2.10 if I select master?

The following paragraph should explain our branching structure.
https://github.com/ankidroid/Anki-Android/wiki/Release-procedure#development-lifecycle

Master at the moment is the 2.11 alpha

If it's a bugfix, it'll be cherry picked into 2.10.X when we merge it.

As a rule, unless there's a really good reason not to, make the pull request into `master`, and @mikehardy will deal with placing it in 2.10

**Comment by Sc-Weng** [comment]
@david-allison-1 I need you help. For this PR, I cannot switch it to master. When I try to reopen this one, there are only release-2.10, release-2.9 and release-2.8 without a choice of "master".
For #6277, it can change to "master". However, it has another problem which is I use release-2.10 as the source branch. 
It seems that both these two PRs have some problems, and I don't know which one I should use. Or I have to create a third one? :(

**Comment by david-allison-1** [comment]
Okay, it would be best if you:

* Leave this one closed
* Go to #6277
* Locally in git or Android Studio:
   * Rebase `onto` master `from` `HEAD` (or `HEAD~n` depending on the number of commits you made).
* Check the history looks reasonable
* git push force-with-lease back to the pull request
* Change the pull request target to `master`

Best case: You're more familiar with `git rebase` and it works
Worst case: You try, it doesn't work, we get a third pull request and no harm is done, it's fine to make mistakes, we've all done it, it's how we improve, and we're all here to help :)

P.S: When starting the next commit, start from `master`

**Pull request closed without merging**
