### PR TITLE
Relaxed update permission check to allow for calls from AnkiDroid

### PR DESCRIPTION
**Pull request by marcardar**
(such as during tests).

### CODE REVIEW

**Comment by timrae** [comment]
I'm currently playing around with refactoring into two providers. If that turns into too much work then this would be a good temporary fix.

**Comment by timrae** [comment]
See #4143

**Comment by marcardar** [comment]
Added more runtime permissions checks. Please check.

**Comment by marcardar** [comment]
Just fixed my last commit.

**Comment by marcardar** [comment]
and just removed useless callingPackage local variable.

**Comment by marcardar** [comment]
...and no longer show log message when throwing exception

**Comment by timrae** [comment]
Thanks for this, I have a number of issues with the implementation so I've just pushed my own edited version to avoid discussing in detail (#4146).

**Pull request closed without merging**
