### PR TITLE
Used """ instead of " to avoid \"

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Pull Request template
Used `"""` instead of `"` to avoid `\"`

## Fixes
Bug #11451 

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by justdvnsh — APPROVED** [review]
LGTM !

**Review by lukstbit — CHANGES_REQUESTED** [review]
The changes look good, but it will result in 250+ lines of code which don't look inside the IDE so I'm not sure about them.

@BrayanDSO What do you think?

**Comment by BrayanDSO** [comment]
> The changes look good, but it will result in 250+ lines of code which don't look good inside the IDE so I'm not sure about them.

Agreed. Although we don't have a hard rule to respect the 100 characters limit of Kotlin code style, it makes things a lot easier to read.

I believe that we should keep the string concatenation (i.e., use of `= `), so something like the below should be good
```kotlin
            """<a href="/dings.cgi?speak=de/0/7/52qA5FttGIU;text=Wasser" """ +
            """onclick="return s(this)" onmouseover="return u('Wasser')">""" +
            ...
```

**Comment by SanjaySargam** [comment]
> > The changes look good, but it will result in 250+ lines of code which don't look good inside the IDE so I'm not sure about them.
> 
> Agreed. Although we don't have a hard rule to respect the 100 characters limit of Kotlin code style, it makes things a lot easier to read.
> 
> I believe that we should keep the string concatenation (i.e., use of `= `), so something like the below should be good
> ```kotlin
>             """<a href="/dings.cgi?speak=de/0/7/52qA5FttGIU;text=Wasser" """ +
>             """onclick="return s(this)" onmouseover="return u('Wasser')">""" +
>             ...
> ```

It means I have to use `+` operator and move code to next line right?

**Comment by BrayanDSO** [comment]
Basically, just use `"""` and replace `\"` without removing the previous concatenations ` + `

**Comment by SanjaySargam** [comment]
> Basically, just use `"""` and replace `\"` without removing the previous concatenations ` + `

Alright

**Comment by lukstbit** [comment]
@SanjaySargam Some of the changes make the tests in this class fail.

**Review by lukstbit — APPROVED** [review]

**Review by BrayanDSO — APPROVED** [review]

**Pull request merged**
