### PR TITLE
NF: path is always non null

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
I followed through each call/assignment, and by induction, it's clear that path
is always non null when used.

### CODE REVIEW

**Review by david-allison-1 — APPROVED** [review]
LGTM

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
```
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/CollectionV16.kt: (38, 29): Type mismatch: inferred type is String? but String was expected
```

**Comment by Arthur-Milchior** [comment]
Done

**Review by david-allison-1 — APPROVED** [review]
LGTM, blocked on https://github.com/ankidroid/Anki-Android/issues/10173

**Review by mikehardy — APPROVED** [review]
Nice! No longer blocked by dependency. Queuing for merge

**Pull request merged**
