### PR TITLE
UX Proposal: Move Suspend Cards into the overflow menu

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
The purpose of a pause button appeared to be unintuitive to some users due to the assumed association with media.

## How Has This Been Tested?
Tested on my Android, screen still works as expected.

## Research

A few ideas which would be more viable: pause button with a clock. The following are non-free, but roughly show ideas, I'd think a large pause button with a clock overlay in a corner would be better.

https://www.iconfinder.com/icons/1322181/clock_hours_pause_rest_show_times_icon
https://www.vectorstock.com/royalty-free-vector/pause-time-icon-vector-20483949

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
I'd rather change the icon than move anything. I like the idea of a clock with pause (first one is good looking I think), and alternatively you could do a music note with pause for media pause.
I found editing SVGs to be kind of fun+interesting, if I had to do it all the time it would probably get tedious but as a first foray into "how SVG works" and making some icons that looked alright it wasn't hard at all

**Comment by david-allison-1** [comment]
Sounds good to me. I'll see if I can get to it on Saturday. I need to fix the cloze icon for the Visual Designer at the same time.

Is the Android Drawable XML just SVG & rename?

PS: Would you prefer a draft PR/issue/email about these small changes in the future?

**Comment by mikehardy** [comment]
I dunno - I don't remember how I did it exactly but the result is like so https://github.com/ankidroid/Anki-Android/pull/5113/files?file-filters%5B%5D=.xml#diff-f5ea7243360d53e264eefdac733043f5

draft PRs are fine by me for discussion

**Comment by david-allison-1** [comment]
@mikehardy the unsuspend icon is currently a .png rather than a .svg: d98f676d094d5af8c89ad7d7f84916c4bbaf10e6.

Is there a reason for this?

**Comment by mikehardy** [comment]
Probably just that neither I nor anyone else has brought #5134 home yet: (https://github.com/ankidroid/Anki-Android/pull/5134#issuecomment-520218667) - it was really close though and I was thinking it would be just the effort of an hour or so to pull it, de-conflict it, test the replacement FAB and merge it in. Then I realized 2.9 was crashing right and left and re-prioritized :)

**Comment by david-allison-1** [comment]
OK, will leave it until #5134 goes in to reduce conflicts

**Pull request closed without merging**
