### PR TITLE
Improved efficiency and readability of joinFields()

### PR DESCRIPTION
**Pull request by marcardar**

### CODE REVIEW

**Comment by hssm** [comment]
Usually for this type of thing I use [TextUtils.join("delimiter", collection)](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/android/text/TextUtils.java#TextUtils.join%28java.lang.CharSequence%2Cjava.lang.Object[]%29). By the looks of it, it achieves the same result and wins on the readability part.

**Comment by hssm** [comment]
Would you be able to [squash your commits](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#squashing-a-series-of-commits-down-to-one) into one?

By the way, GitHub doesn't notify us when you update a pull request with a new commit, so in the future just let us know if you update the branch or it might take a white before we notice it.

**Comment by marcardar** [comment]
Thank you for the suggestion. How is this?

**Comment by hssm** [comment]
That looks fine. Thanks.

**Pull request merged**
