### PR TITLE
[Clean Up] : function naming conversion Warning 

### PR DESCRIPTION
**Pull request by gautamsingh2**
## Purpose / Description
fix warning of function naming conversion

## Fixes
issue #13282

## How Has This Been Tested?
emulator

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
Merge conflicts!

**Comment by mikehardy** [comment]
@criticalAY I will note that when I see a commit that says "Merge branch..." I immediately throw up a little in my mouth.
That's not the right way to go about it, it produces an appalling commit trail that makes commit-by-commit review a terrible experience.

You want to pull rebase and fix things ideally.

**Comment by mikehardy** [comment]
I will add, "git rebase" is *not* your friend 😆 - it is also a little nausea-inducing. But the payoff is a beautiful set of commits once you learn how to drive it

**Comment by criticalAY** [comment]
@mikehardy this is not my PR 😭 I usually do rebase my PRs, ig it was for @gautamsingh2 if I'm not wrong

**Comment by mikehardy** [comment]
It's for anyone reading. I've seen you merge though @criticalAY 🧐 😆

**Review by lukstbit — APPROVED** [review]
Thank you for the contribution!

**Comment by david-allison** [comment]
We used to have a guideline to be consistent with the Anki Desktop names in the `libAnki` classes.

The new backend code doesn't do this, and it's causing warnings, so let's move to a more standard naming convention

**Review by david-allison — APPROVED** [review]

**Pull request merged**
