### PR TITLE
Card generation rust

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This port into java the rules generation of anki 2.1.28.

For the user, it means that the error messages will be different if their template is not valid. In particular, it may be more detailed. When the cards are valid, they should see no difference unless there is a negated conditional. If there is a negated conditional, it means the card will be correctly generated, which is a change I really really like, and the reason why I ported this code !!! 

By the way, if we use rust backend, that's also change the users will get automatically.

It is mostly a direct translation in java from rust codes, with some modification to adapt the languages. For example, I used some inheritance instead of algebraic dataset. I added some methods to ease unit test (in particular, a list of node is itself a node, this avoid code duplication. And some methods takes either a set of String or a String...)

I don't notice a difference during normal review, card generation is still too quick to notice. However, this makes "Empty card" quite slower. Moving from 20 seconds to 35 seconds on my collection (that's my fault, I optimized this some weeks ago. :( )
This is kind of sad, because it's easy to optimize (i.e. use the efficient old code if there there is no conditional and use the exact algorithm only if there is negated conditional. I'll need to check whether DAE would accept that).
I'll still spend some time to see whether it can be optimized without changing the algorithm totally. But it's such a rare process that I believe the 2 minutes lost are acceptable if not optimal.

I added unit tests to check the lexing, the parsing, the rendering, for the various kind of conditional and in case of errors. I removed the reqs test, as "req" became useless.

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
I actually read these though it was quite large so perhaps I missed something
It all looked fine to me though, and I really really appreciate the testing
Going to merge this so it gets out there and we can start finding the users using invalid templates, going to be a support issue likely, may deserve a FAQ or something ("why are my templates invalid in new versions?")

**Comment by mikehardy** [comment]
@Arthur-Milchior this needs a conflict resolution from the other merge today but otherwise I'll release it

**Comment by Arthur-Milchior** [comment]
> I actually read these though it was quite large so perhaps I missed something

I beg your pardon. It's honestly a case where I fear that I could not create atomic PR. The lexer/parser alone would be useless, and nothing can be done without them

> It all looked fine to me though, and I really really appreciate the testing
I'll add some more actually, while playing with the new templates, I found new cool cases that were forbidden in Anki<2.1.28 and I didn't even realize it

> Going to merge this so it gets out there and we can start finding the users using invalid templates, going to be a support issue likely, may deserve a FAQ or something ("why are my templates invalid in new versions?")

I don't expect to get this kind of request honestly. What I may expect is to get message asking why new cards were generated. That's actually an unexpected side effect I met when going to 2.1.28, I had some templates that anki were not able to satisfy, and so the cards were never generated. With the new code, the cards are actually generated, while I forgot that I created those broken templates some time ago.

As far as faq is concerned, I'd assume the anki documentation should suffice; after all they went through the same change.

**Comment by Arthur-Milchior** [comment]
You'll find more unit test in `emptyness`. Especially cases where 2.1.27 and 2.1.28 differs, the reason why I care about this update so much!

No other tests are added in other functions, because complex requirement rules does not affect in any way the way lexing and parsing is processed

**Comment by mikehardy** [comment]
I noticed the conflict with #7976 I checked the string change carefully between them :-). I'll merge this one then let you patch 7980 since that's an easier fix ("delete that part") :-)

**Comment by Arthur-Milchior** [comment]
Note for later: when this is released, we should ask dae to add ankidroid in the list https://docs.ankiweb.net/#/templates/generation?id=limitations-in-older-anki-versions

**Pull request merged**
