### PR TITLE
Implemented a toast when back is pressed in DeckPicker activity

### PR DESCRIPTION
**Pull request by iamvs-2002**
## Purpose / Description
_Describe the problem or feature and motivation_
To add a toast message when back is pressed so that the user may press the back button twice to close the app.
## Fixes
Fixes _Link to the issues._
#8226 
## Approach
_How does this change address the problem?_
The video below shows the solution:

https://user-images.githubusercontent.com/54304786/113475740-07648c00-9495-11eb-8d6d-623c911bae19.mp4

## How Has This Been Tested?
I tested this on Google Pixel XL Api 30 android device.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
Thanks!

CI is failing

Could you rebase this onto master and  remove the merge commit

**Comment by iamvs-2002** [comment]
> Thanks!
> 
> CI is failing
> 
> Could you rebase this onto master and remove the merge commit

I am really sorry. I don't think I know how to do it. But I had pushed the changes on the master branch in the fork and then created a pull request.

**Comment by iamvs-2002** [comment]
> > Thanks!
> > CI is failing
> > Could you rebase this onto master and remove the merge commit
> 
> I am really sorry. I don't think I know how to do it. But I had pushed the changes on the master branch in the fork and then created a pull request.

I am ready to delete this fork, fork the repository again and then do the changes if it will solve the problem. Please guide me.

**Comment by david-allison-1** [comment]
Git will allow you to fix pretty much anything without deleting and creating a new Pull Request. If you need to delete things and start again, you can make a new branch from master, without deleting the fork.

For git rebase, I find [this tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) to be helpful (it'll take some reading), Android Studio also has really good abstractions for an interactive rebase under the "Git - Log" window.

**Comment by iamvs-2002** [comment]
> Git will allow you to fix pretty much anything without deleting and creating a new Pull Request. If you need to delete things and start again, you can make a new branch from master, without deleting the fork.
> 
> For git rebase, I find [this tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) to be helpful (it'll take some reading), Android Studio also has really good abstractions for an interactive rebase under the "Git - Log" window.

I couldn't understand it, I'll create it all again.

**Comment by iamvs-2002** [comment]
> > Git will allow you to fix pretty much anything without deleting and creating a new Pull Request. If you need to delete things and start again, you can make a new branch from master, without deleting the fork.
> > For git rebase, I find [this tutorial](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) to be helpful (it'll take some reading), Android Studio also has really good abstractions for an interactive rebase under the "Git - Log" window.
> 
> I couldn't understand it, I'll create it all again.

This time I'll do it from master -> master

**Comment by mikehardy** [comment]
Developing on main branch is a bad practice and leads to a few hard to fix cases.
I recommend before you start developing any new feature or bug fix, create a branch for the same

**Comment by iamvs-2002** [comment]
> Developing on main branch is a bad practice and leads to a few hard to fix cases.
> I recommend before you start developing any new feature or bug fix, create a branch for the same

So, shall I create a new branch in the main repository?

**Comment by Arnold2381** [comment]
@iamvs-2002 https://github.com/ankidroid/Anki-Android/wiki/Development-Guide Please take a look at this guide. It shows how to create a new pull request

**Comment by iamvs-2002** [comment]
> @iamvs-2002 https://github.com/ankidroid/Anki-Android/wiki/Development-Guide Please take a look at this guide. It shows how to create a new pull request.
> To be more specific I am talking about this part in the guide
> image

Thanks a lot, it really helped.

**Comment by Arnold2381** [comment]
@iamvs-2002 Anytime! Feel free to ask doubts.
Happy git and contributing!! ATB :)

**Pull request closed without merging**
