### PR TITLE
fix 9730 - Return correct values for current card

### LINKED ISSUE #9730: [Bug] AnkiDroidJS.ankiGetCardReps() and AnkiDroidJS.ankiGetCardInterval() return strange value
###### Reproduction Steps
I am retrieving the number of reviews and the interval:
● via the template:
```
<div>{{Front}}</div>
<div id="data"></div>

<script>
// get the interval and number review of the card 
var jsApi = {
    "version": "0.0.1",
    "developer": "dev@mail.com"
};
var apiStatus = AnkiDroidJS.init(JSON.stringify(jsApi));

document.getElementById("data").innerHTML="int:"+AnkiDroidJS.ankiGetCardInterval()+"; rev:"+AnkiDroidJS.ankiGetCardReps() ;

</script>
```

● via USB debugging

###### Expected Result
The retrieved values should match the one I see in the "Card info"

###### Actual Result
Sometimes the values don't match:

● Example 2:

image1

● Example 2

image

● It also seems that the first card of a deck gets a correct interval and reviews value but then it bugs for the following one and if I undo the last review, I get wrong value for the first card. Also, if I close anki on a card with wrong values, and then reopen after doing some tasks so that the card is reloaded, then the correct values are display. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.16alpha28

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.85 Mobile Safari/537.36

ACRA UUID = ba2a7ac3-aa20-4edc-8251-0b3de0ebd8be

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by infinyte7**
## Purpose / Description
When `currentCard` created and assigned the value in class then it does not return correct value. So, `currentCard` directly called from `activity` variable.

## Fixes
Fixes #9730

## Approach
Removed `currentCard` variable and directly accessed using `activity.currentCard`

## How Has This Been Tested?
Tested using chrome remote debugging on android devices.

## Learning (optional, can help others)
https://developer.android.com/reference/android/webkit/JavascriptInterface

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — COMMENTED** [review]
It's really difficult to review when there are refactors and functional changes mixed in
Even for the refactors, when there is a lot of code motion (extraction to new files etc) it's best to do the code motion even as a simple extraction separate from any other deeper refactoring
Then if you imagine how a reviewer looks at it, most of the diff here is probably skippable so that limited attention may be focused on the actual important changes, or at least in the simpler pure-code-motion or refactor-but-no-functional-change commits it's possible to switch to the appropriate mental state to review those commit by commit

Since this one is all mashed together and not fast to review, for me it goes in the queue for deeper review which I don't get to very often vs a quick roll through the commits and likely merge

**Comment by infinyte7** [comment]
I have removed refactor and new code in same commit. The refactor will be in separate PR.

**Review by mikehardy — APPROVED** [review]
Nice! This is really easy to understand when it is a clean commit like this. It is okay to have refactors in a PR, that's great actually, just think about the PR reviewer as someone to pay attention to, and think what would help them - splitting refactors into separate commits (on the same PR is okay) is the goal, then we just look commit by commit while reviewing and it is easy to follow

**Comment by infinyte7** [comment]
Thanks

**Comment by mikehardy** [comment]
Hi there! **October OpenCollective Notice**

Apologies for the delay, and if you're already submitted something to OpenCollective for PRs merged in **October** 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for October 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of August)

Thanks!

**Pull request merged**
