### PR TITLE
NF: loading browser faster

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Currently, two search occurs, and the first gets cancelled. This reduce the time from 20 seconds to 18 seconds on my collection.

I tested changing deck, changing to all deck, clicking on "search all deck", and all still works and don't start two days

### CODE REVIEW

**Comment by david-allison-1** [comment]
What happens if the collection is not open when the activity is launched?

**Comment by Arthur-Milchior** [comment]
I assume that the first call to `getCol` will see that the collection is not open, so the CollectionHelper will open the collection.

I've just tried it by:
* Enabling the "card browser" context menu everywhere
* forcing ankidroid close
* selecting a text in the web browser, and pressing "card browser"

It opens ankidroid and the card browse. It works prefectly. Of course, it's really slow because it needs to load the collection but I have the correct search result.

Anyway, if the collection was not accessible, there would be problems far before doing a search in the collection. Indeed, the cardbrowser need for example the list of decks. And this is not touched by this PR.

Can you please let me know whether there is any reason for you to assume that this PR would affect the case of closed collection, because I fail to see how it would relate

**Comment by david-allison-1** [comment]
When the collection is openable, but has not been open yet, taking the async path, so `onCollectionLoaded` is called after `onResume()` in the lifecycle - does the local variable still satisfy this assumption?

What if the AsyncTask for searching finishes before the local variable is set?

**Comment by Arthur-Milchior** [comment]
What is "the local variable" ? There are a lot of local variables through the code. I'd assume you want to speak about `mBrowserLoaded` since it's a new varible, but it's not local.

The search can't be executed before the collection is loaded here. The search occurs when some element of the list of deck is selected, and this only occurs when the list is filled with the list of deck, which requires the collection to be loaded. 

I'm not adding any new async task, I'm removing the first of the two task to avoid duplicate work. If there were a problem due to the fact that a search ends to soon, we would already have it.

**Comment by mikehardy** [comment]
with the new mBrowserLoaded variable required to be set at onCollectionLoaded before any searching can happen, this means that onCollectionLoaded should be in a try/catch/finally with mBrowserLoaded set in the finally, in order to make absolutely sure that searching wasn't blocked forever because someone adds a short-circuit return later or similar.

Is there a way for the search itself to cancel previous searches so that only one is extent at the same time? That would just be a manipulation of existing tasks and state but not add new state

**Comment by Arthur-Milchior** [comment]
> Is there a way for the search itself to cancel previous searches so that only one is extent at the same time? That would just be a manipulation of existing tasks and state but not add new state

That's actually a very good idea. Would something such as 1562a65403d5ded875451f01b46fe77bead42764 satisfies you ? :p

More seriously, this still lead to a reduction of 2 out of 20 seconds. I don't know why, because it's not like this delay another background task, but that's what my experience shows. And this also cost time on https://github.com/ankidroid/Anki-Android/pull/7513 , (that's actually how I found out this bug). 

> I'm not advocating this, just saying it's assumption added - that onCollectionLoaded will always go all the way to the end no matter what now

I hardly can imagine that someone add a return which break the flow without checking that it does not remove anything useful. And anyway, any test will show that no search show result, so it will be clear that the bug exists if the code is run.
And if there is an exception at some point, I don't see why we want to put something in finally. There does not seems to be anything in this method that is not required for the browser to work properly

**Review by mikehardy — APPROVED** [review]
Seems like it should work to me then, after reading through all of us batting it around as an idea

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Had a manual test. This is adding complexity due to an undiagnosed issue (phantom call to `selectDropDownItem`), adding code to work around it in this manner adds complexity, and will make it harder to diagnose the root cause of the bug.

Once we fix the phantom call issue, or the timing of it changes, then we have a race condition.

IMO, we should take one or both of two options:

* Keep track of the currently in-flight requests, and discard and log warn if the same search is performed multiple times - this brings attention to the bug, doesn't add complexity to the startup of the class.
* Fix/work around the bug

----

There is a possible race condition, depending on when the phantom method is called:

Searching is set by:

`selectDeckById -> selectDropDownItem`, which is guaranteed to not cause a race condition as it occurs right before setting the variable

AND a phantom call to `selectDropDownItem`, which occurs after `onCollectionLoaded`. I've commented out all of the code below 

`mActionBarSpinner.setVisibility(View.VISIBLE);` and I believe this likely occurs on Spinner init

----

A StackOverflow post has a lot of potentially viable solutions: https://stackoverflow.com/questions/13397933/android-spinner-avoid-onitemselected-calls-during-initialization

We should also add a regression test for this once it's fixed.

**Comment by mikehardy** [comment]
@david-allison-1 nice one!

**Comment by Arthur-Milchior** [comment]
I love the duplicate search idea. We should just ensure that the search is not discarded when the collection is changed

**Comment by mikehardy** [comment]
superceded by #7535

**Pull request closed without merging**
