### PR TITLE
Fix crash if NumberRangePref value is empty on close

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description
The app crashes if you delete all text on a NumberRangePreference , e.g. Timebox time limit + if sent a text with leading zeroes, the summary would have the leading zeroes as well, e.g. "0050"

## Approach
Make a check at `onDialogClosed`

## How Has This Been Tested?

1. Settings > Reviewing > Timebox time limit
2. Erase all text
3. Confirm
4. See if the new value is 0

---
1. Settings > Reviewing > Timebox time limit
2. Write "0050"
3. Confirm
4. See if the new value is 50

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
NeedsTest annotation would be great

**Review by mikehardy — APPROVED** [review]
Nice one - will mark pending merge + waiting for feedback just in case you push a NeedsTest annotation, totally happy to merge either way. Thanks for noticing + fixing a crash!

**Comment by BrayanDSO** [comment]
added it

**Comment by david-allison** [comment]
What happens on the backups dialog? Does this now default to 0?

**Comment by BrayanDSO** [comment]
Yes, it defaults to 0 (its minimum value) there. If it should fallback to `defaultValue`, I'm not sure. If the user deliberately wanted to put "nothing" as value and deliberetely confirmed instead of canceling, the value should be "nothing"/"0"/"the minimum value possible"

**Comment by david-allison** [comment]
> Yes, it defaults to 0 (its minimum value) there. If it should fallback to `defaultValue`, I'm not sure. If the user deliberately wanted to put "nothing" as value and deliberetely confirmed instead of canceling, the value should be "nothing"/"0"/"the minimum value possible"

Can we stop the user from submitting if there's no value?

**Comment by BrayanDSO** [comment]
Perhaps? I need to take a look into the API to be sure. If not, just using the previous configured value may be better.

**Comment by BrayanDSO** [comment]
Haven't found a method that worked with `PreferenceDialogFragmentCompat`. Best alternative seems to use a Material Dialog, which is quite simple to implement.

image

image

As `IncrementerNumberRangePreferenceCompat` is a subclass of `NumberRangePreferenceCompat`, it will need to be rewritten.

**Comment by david-allison** [comment]
> Perhaps? I need to take a look into the API to be sure. If not, just using the previous configured value may be better.

I'd rather do this. @mikehardy ?

**Comment by mikehardy** [comment]
> > Perhaps? I need to take a look into the API to be sure. If not, just using the previous configured value may be better.
> 
> I'd rather do this. @mikehardy ?

That works for me, good catch on the subleties here, I missed them when thinking through it

**Comment by BrayanDSO** [comment]
Simplified/optimized the code a bit. Now if the value is empty, the previous value is kept.

**Comment by mikehardy** [comment]
If you confirm this no longer crashes, LGTM (seems like it would work, to me, but I missed something last time, so...)

**Comment by BrayanDSO** [comment]
From my tests with the same approach of the PR description, there was no crashes.

**Review by mikehardy — APPROVED** [review]
LGTM

**Pull request merged**
