### PR TITLE
added README.md file for project dictionaries

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Screenshot 2023-12-25 020235
The typos appear was warning which can be avoided by adding the words to the dictionary, so creating a proper README file to guide the contributors 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
After it's merged it can be linked with the contribution guide

**Review by david-allison — APPROVED** [review]
Looks great! May be useful to add links to the README.

**Comment by criticalAY** [comment]
> Looks great! May be useful to add links to the README.

Will link it after its merged so that I link it with the right url

**Comment by david-allison** [comment]
I was referring to links such as: 

* https://www.jetbrains.com/help/idea/spellchecking.html (now seems deprecated)
* https://stackoverflow.com/a/36256338

which were in my [original commit message](https://github.com/ankidroid/Anki-Android/commit/a2d2c162fbf3404b27061b402161907ca1a6e46e).

**Comment by criticalAY** [comment]
ohh will amend them

**Review by lukstbit — APPROVED** [review]

**Pull request merged**
