### PR TITLE
semaphore executor test

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Avoid writing method specific code thanks to
standard library

### CODE REVIEW

**Review by david-allison — APPROVED** [review]

**Comment by Arthur-Milchior** [comment]
@david-allison Is it "pending merge" or "need second approval"?

**Comment by david-allison** [comment]
It's test only code and the tests pass, I'm happy to move quickly here.

**Comment by david-allison** [comment]
@Arthur-Milchior You're not submitting PRs from your fork, why?

**Comment by Arthur-Milchior** [comment]
`gh pr create` automate the boring part of the process consisting in uploading on arthurmilchior/Anki-Android and then creating the PR.
If there is an issue here, I'll revert to this habit. But it's a small time win on a boring task that I was happy to discover

**Comment by mikehardy** [comment]
I don't particularly mind, all our automation works on fork or non-fork PRs. I like good branch hygiene so I'd prefer branches to be named by contributor, for example `arthurmilchior/mybranchname` and we delete post-merge (as you did, thank you)

also more than happy to see the speed. we're all doing our best, if you're confident, merge and move on, we can continue iterating if we discover things after, but optimize for velocity in my opinion

**Pull request merged**
