### PR TITLE
fix(previewer): cards' ord couldn't be changed

### LINKED ISSUE #16155: [BUG]: Previewer can not Handle Notes with multiple card types
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Add a note using Basic (and reversed card)
2. Look at the cards in the previewer

### Expected behaviour

card 1 has `{{Front}}` in question side and card 2 has `{{Back}}` in question side

### Actual behaviour

depending on the card you select both of them has either `{{Front}}` on question side or `{{Back}}` on question side.

### Debug info

```text
AnkiDroid Version = 2.18alpha8 (6fc26947fd31743bc83e68f17ae7fec64bfa8e62)

Backend Version = provider(?) (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = null

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
* Fixes #16155

## Approach

update currentCard if ord is changed

## How Has This Been Tested?

With the issue steps in emulator 34. Also unit tested

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]

**Review by lukstbit — APPROVED** [review]

**Comment by alex-larkin** [comment]
Hello, I am also experiencing the issue described in #16155. I see that this pull request fixing #16155 was merged in April. I admit that I am a bit shy about jumping into an alpha or beta version. Any idea on when this fix will hit the Play Store? 

Also, thanks so much to everyone who develops the Anki ecosystem. This platform is a real life-changer. 

Thanks so much.

P.S. I know they're not really needed but here are my printscreens showing the same issue. Yellow shows {front} when it should show {back}.

delete
delete2
delete3

**Comment by david-allison** [comment]
Hi @alex-larkin,

We've started the beta process. We don't hold ourselves to a timeline, but I'd guesstimate 2 weeks for 2.19 to hit production.

**Comment by david-allison** [comment]
@alex-larkin In addition, this YouTube video should show you how to solve your issue with appearance in the Browser:

https://www.youtube.com/shorts/JbxNP4pSIBA

**Comment by alex-larkin** [comment]
Thanks so much David! I'll hold tight for the next release 😃.

**Comment by david-allison** [comment]
@alex-larkin The linked PR was merged for 2.18 and is for the Previewer, not the Card Browser.

You'll want to follow the instructions in the video above.

**Comment by alex-larkin** [comment]
delete

Thank you David. I had a bit of a hard time following the video. While I was working on that, though, I noticed a drop-down menu in the first column and changed it from "Sort Field" to "Answer". That fixed my issue. Not sure if that option got changed with the update or if I changed it by mistake, but in any case it's working again. 

image


Thanks so much for your help!

**Pull request merged**
