### PR TITLE
Fixed #8347 adding the password/email icon to the left hand side of the boxes.

### LINKED ISSUE #8347: Modifying login UI of the app
**Modifying login UI of the app**
Right now, the thing that the Login UI of the AnKidroid app is certainly quite good but the UI is not like premium. So I would like to improve the Login UI of the app .

**Describe the solution you'd like**
Moving ( Email Address & password) EditText  in a rounded box & login button corners in rounded form .

**Additional context**
Demo like this -:

https://user-images.githubusercontent.com/72181295/112653217-35821480-8e74-11eb-9651-2ad744ae919a.mp4

### PR DESCRIPTION
**Pull request by Prashant830**
## Purpose / Description
At login UI , password /email icon is missing so I adding the password/email icon to the left hand side of the EditText boxs.

## Fixes
fixes #8347 

## Approach
1  Added email icon at email EditText box
2  Added  password icon at password EditText box

## How Has This Been Tested?

Tested this UI with different sizes of devices.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison-1 — APPROVED** [review]
Looks good to me

Some duplication on the email icon (which is now blue): `ic_mail_outline_black_24dp.xml`

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/res/drawable/ic_mail_outline_black_24dp.xml

This may be possible to be combined, but changing the tint would be non-trivial

**Review by david-allison-1 — APPROVED** [review]
Requesting a review when I've reviewed the change dismisses my review.

**Comment by Prashant830** [comment]
sorry, please see my second change.
If it is correct then I will create a new PR and remove this PR

**Comment by david-allison-1** [comment]
It's better as it was previously

**Comment by Prashant830** [comment]
Okay
So let me close this PR.

**Comment by david-allison-1** [comment]
? You hadn't made the change in the PR, it was fine as it was in the image at the start of the PR

**Comment by Prashant830** [comment]
@david-allison-1 Sir, I cannot reopen this PR because I was Deleting my old Anki-repository for some reason.

**Comment by david-allison-1** [comment]
Okay, no worries. Let's rebase the other PR (and no need for a 'sir' 😄)

**Comment by Prashant830** [comment]
i have checked this app well but i do not get the option of share apk anywhere in it it is very important option of any app.
Can I put the option of Share apk button in this app.

**Comment by david-allison-1** [comment]
I wouldn't support that change.

**Comment by Prashant830** [comment]
Ok 
never mind

**Pull request closed without merging**
