### PR TITLE
All missing columns in browser

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description 
Adding in the browser all columns present in Anki.

## Fixes
I'm pretty sure someone asked for it, and I was mentioned because I did add interval. I can't find it anymore.

## Approach
As in Anki, with the following twists:
* the method to get due is in Cards.java. In anki it's in aqt/browser.py, but we don't literally have AQT, and anyway, it makes totally sens to decide that this is a method related to the card itself.
* the dates are localized. Anki didn't localize the date; I decided to use java DateFormat and let him localize date in Short format.

## How Has This Been Tested?

Open ankidroid with an existing used collection. Find a few cards (new, due, filtered), and ensure that each columns display the same values in Ankidroid and in Anki (assuming the collections are synchronized on both devices obviously) 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Only one failute, api 17. Can you restart please?

**Comment by mikehardy** [comment]
Yeah - saw that in my morning sweep and kicked it a few minutes ago - it's exactly this #5588 - I'm hesitant to disable the test because even though it's showing up as hard-to-reproduce it never happened before the libanki changes to sync things up started going in. I think there's something real there

**Comment by Arthur-Milchior** [comment]
Where di you see it has a succesul testing? I didn't see any feedback on the change i made from any user

**Comment by mikehardy** [comment]
I think I was inferring from https://github.com/ankidroid/Anki-Android/issues/5542 that @thoral and @Anthropos888 had seen it in the alphas

**Comment by mikehardy** [comment]
Last review for a while @timrae this one also looks like a pretty clean piece of code, easy to review + merge

**Comment by mikehardy** [comment]
@Arthur-Milchior there is a tiny collision here since I just merged #5599 - looks like a trivial conflict in import statements. If you resolve that and re-push I'll merge this one as well. Thank you!

**Comment by Arthur-Milchior** [comment]
Done

**Comment by mikehardy** [comment]
Nice! Apart from all the stability fixes I think this along with flags might be the only new features we have to offer for 2.10, nice to have something new for the users - thanks @Arthur-Milchior

**Comment by mikehardy** [comment]
2.10alpha50 is out with this! available as soon as google play finishes processing and starts serving it up :rocket:

**Comment by Anthropos888** [comment]
Something is wrong with the due time. Searching for all due cards today returns cards due on 17 or 18.03.2020 but AnkiDroid shows it as 19.01.1970

Screenshot_AD

Anki:
image

**Comment by mikehardy** [comment]
@Anthropos888 thank you thank you for being part of the alpha test group and reporting this. It is possible to see the exact commits that were in between alpha49 and alpha50 and it does seem like this might be the one that caused the regression out of the commits I see: https://github.com/ankidroid/Anki-Android/commits/master

@Arthur-Milchior can you take a look if/when you get a chance? 
@Anthropos888 I'll assume alpha49 works so if this is critical for you given we're all in a pandemic and it might take a while, just installing it from our releases page until you see that it is fixed here might be best

**Comment by Anthropos888** [comment]
@mikehardy alpha49 doesn't have the column for due time, so I can't test it.

**Comment by Arthur-Milchior** [comment]
@mikehardy It seems to me that you didn't link a commit but a branch. @Anthropos888 Sorry for the error.

**Comment by mikehardy** [comment]
@Arthur-Milchior yes - I just linked to the whole list of commits, there are only 4 commits from alpha49 to alpha50 which is I was just demonstrating with the link. I could be wrong but it makes sense that it is in here

I thought it was a regression but if due time did not even exist before this PR merged, then it's just a small defect in a totally new feature, which is progress of a sort. Something in the due calculation for the column must be off? I have not examined though - my country went on full lockdown which converted me to a homeschool teacher for my child, and does not leave much time for programming unfortunately

**Comment by Arthur-Milchior** [comment]
I'll take a look at it. Should not be that hard, even if the PR was 5 months ago.
I'll also have less time, but mostly because I'll start a new job in April.

**Comment by mikehardy** [comment]
Congratulations! Hopefully I/we can work through the rest of the stack of your PRs shortly then, I know they've sat there a while

**Pull request merged**
