### PR TITLE
Fixed the timebox

### PR DESCRIPTION
**Pull request by soCallmeAdityaKumar**
## Purpose / Description
Timer keeps running even the timebox was shown

## Fixes
* Fixes https://github.com/ankidroid/Anki-Android/issues/15500

## How Has This Been Tested?

https://github.com/user-attachments/assets/818e4391-4dbb-4d8f-847e-e95f3b99c62a

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
(just closing/re-opening to re-run CI after updating set of required checks in org settings)

**Review by mikehardy — APPROVED** [review]
🤔  easy to read the diff with spacing ignored, seems like it should solve it but I don't trust my kotlin async skills too much so definitely want a second

Thank you!

**Review by david-allison — CHANGES_REQUESTED** [review]
I don't understand how this works

@soCallmeAdityaKumar could you explain

`topCard` would have `startTimer()` called on it when it's set, not when accessed

https://github.com/ankidroid/Anki-Android/blob/06e8ac2ef3e0d35fb3efc59aabb38c796b276b04/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt#L1060-L1069

**Comment by soCallmeAdityaKumar** [comment]
> I don't understand how this works
> 
> @soCallmeAdityaKumar could you explain
> 
> `topCard` would have `startTimer()` called on it when it's set, not when accessed. Blocking this method doesn't feel like it would stop the timer, but it appears to work
> 
> https://github.com/ankidroid/Anki-Android/blob/06e8ac2ef3e0d35fb3efc59aabb38c796b276b04/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt#L1060-L1069

but as soon as dialog for timebox appears the flow further continues and the next card is set and the timer starts. So i have blocked the flow till when user chooses any options from the dialog.

**Comment by david-allison** [comment]
> flow further continues and the next card is set and the timer starts

Can you walk me through where this happens?

**Comment by soCallmeAdityaKumar** [comment]
> > flow further continues and the next card is set and the timer starts
> 
> Can you walk me through where this happens?

``` fun currentQueueState(): CurrentQueueState? {
        val queue = queuedCards
        return queue.cardsList.firstOrNull()?.let {
            CurrentQueueState(
                topCard = Card(it.card).apply { startTimer() },
                countsIndex = when (it.queue) {
                    QueuedCards.Queue.NEW -> Counts.Queue.NEW
                    QueuedCards.Queue.LEARNING -> Counts.Queue.LRN

    }```
    In this startTimer is called before the dialog everytime it is set

**Comment by david-allison** [comment]
Makes sense, cheers!

For transparency: I edited your comment to be a permalink to the code you listed

**Review by david-allison — APPROVED** [review]

**Pull request merged**
