### PR TITLE
build(deps): bump android gradle plugin to 7.0.0

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

More than anything, try it to make sure there are no major incompatibilities. Since there aren't, might as well post it up

## Fixes
Obsoletes #9328 

## Approach

- bcprov ignored via `ignorelist` now, may be removed w/AGP7.1 https://issuetracker.google.com/issues/159151549#comment12
- Triple-T publisher needs a switch to their agp7.0 track
- Obsolete versionCode/version/dexOptions removed (suggested by AGP migration task in Android Studio)
- AGP 7+ requires JDK11 to run, retire JDK8 from development

## How Has This Been Tested?

I tested it locally with API21 and API30 emulators up via `./gradlew clean jacocoTestReport`, no regressions detected

## Learning (optional, can help others)

Just reading release notes carefully and using the android gradle plugin migration assistant (which pointed out some of the deprecated / obsolete items in our gradle files)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
This should go through CI okay assuming I moved the workflows to JDK11 correctly earlier, I semi-remember I did that. We'll see

**Comment by david-allison-1** [comment]
Main query is about the version code removal from the API. Where is that set now?

**Comment by mikehardy** [comment]
The publisher takes it from the version up above, and version code is not applicable for android libraries (vs android apps) AFAICT

https://github.com/ankidroid/Anki-Android/blob/5efa59bf0de963a4ecc679cd022c3d8f794caacc/api/build.gradle#L3

The thing that got me over the hesitation is that the android gradle plugin migration utility did not say it was deprecated (which it did say about other items) it said "obsolete / ignored", which implies even if we don't understand it, it has no effect.

**Comment by mikehardy** [comment]
Ah darn. The bcprov jetifier ignore thing *is* resolved, but it is actually resolved in AGP7.1 (unreleased), for AGP7.0 they converted it to a warning, and we treat warnings as errors etc.

I'll put the bcprov ignore back in, with a comment that it may be removed when AGP7.1 is adopted

**Comment by mikehardy** [comment]
Ugh, lintOptions (which may be deprecated, but `lint` as the config DSL keyword failed too) appears to have some bad interaction with the new AGP7 - 

```
> Task :AnkiDroid:lintAnalyzePlayRelease FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/home/mike/work/AnkiDroid/Anki-Android/lint.gradle' line: 5

* What went wrong:
Execution failed for task ':AnkiDroid:lintAnalyzePlayRelease'.
> No such property: lintOptions for class: org.gradle.api.internal.provider.DefaultProperty


```

Not sure what + why, reading some docs didn't help, going to have to table this one for a while

**Comment by david-allison-1** [comment]
Before:
`println(android) -> extension 'android'`

After
`println(android) -> task ':api:lintDebug' property 'android`

**Comment by david-allison-1** [comment]
Done some experimentation. Unsure how useful it'll be

* Aside: New lint errors are introduced, which will need to be ignored or fixed
* `def android = android` at the head of the file fixes the first issue (`android` not defined)
* After this, `android.lintOptions.lintConfig = file("../lint-release.xml")` fails to have an effect
* If `android.lintOptions.lintConfig = file("../lint-release.xml")` is applied before the `lintVitalPlayRelease` task (`lintPlayRelease`), then it changes the config, otherwise it silently discards the variable.

Sample code:
```
tasks.whenTaskAdded { task ->
    def works = "lintPlayRelease"
    def fails = "lintVitalPlayRelease"
    def nameToUse = fails
    if (task.name == nameToUse) {
        println nameToUse
        android.lintOptions.abortOnError = true
        android.lintOptions.warningsAsErrors true
        android.lintOptions.lintConfig = file("../lint-release.xml")
        android.lintOptions.checkReleaseBuilds = true
    }
}
```

The `whenTaskAdded` phase is well before `.doFirst`

**Comment by mikehardy** [comment]
Some serious reading on gradle's deferred configuration / configuration on demand is probably necessary to untangle this

Perhaps coming at it totally separately, making a new task that reconfigures things, and making the lint tasks depend on the reconfiguration task would do it?

Most of the react-native modules that do gradle twiddling (messing with artifacts pre-merge, copying things etc) use that strategy, "make new task", "iterate on variants and make variant tasks you care about depend on your new task"

here's an example in case the idea is interesting https://github.com/oblador/react-native-vector-icons/blob/master/fonts.gradle

**Comment by david-allison-1** [comment]
I'm still in deep-dive mode, but:

I feel we can get away from the complexity by deleting our "non-release" config + baseline, it was used on Travis, but rarely looked at, and is no longer used at all

```
                // move the baseline by deleting api/baseline.xml and AnkiDroid/baseline.xml then ./gradlew lintDebug
                android.lintOptions.baseline file('./lint-baseline.xml')
                // # SyntheticAccessor
                // See discussion on #6205 - we should fix these for performance, but low priority
                // compared to other more significant warnings.

                // # ObsoleteLintCustomCheck
                // Requested in #6211 - not actionable by us - upstream issue
                // Sample:
                // > Warning: Lint found an issue registry
                // > (androidx.appcompat.AppCompatIssueRegistry) which requires a newer API level.
                // > That means that the custom lint checks are intended for a newer lint version;
                // > please upgrade
                android.lintOptions.disable 'SyntheticAccessor', 'ObsoleteLintCustomCheck'
                android.lintOptions.abortOnError true
                android.lintOptions.checkAllWarnings true
                android.lintOptions.warningsAsErrors true
                android.lintOptions.showAll true
                android.lintOptions.textReport true
                android.lintOptions.textOutput 'stdout'
                android.lintOptions.htmlReport true
```

**Comment by mikehardy** [comment]
Agreed - in practice it has not been used

**Pull request closed without merging**
