### PR TITLE
Feature workaround avi

### LINKED ISSUE #15772: .Avi files not playing
###### Reproduction Steps

1. Insert .avi  (file used: [sample avi files](https://filesamples.com/formats/avi))
2. Preview Card

###### Expected Result
Load the video

###### Actual Result
image
First field: .avi
Second field: .mp4

###### Debug info
2.18alpha2 Samsung S21

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Additional
This was reported in [Forum](https://forums.ankiweb.net/t/android/41960)

> The card on android has never been able to play avi videos (it won't sync over, I imported the avi video into the "collection.media" folder on android, and it won't play it either).

> Today I inserted an occasional mp4 video on my computer, and suddenly found that it could be synchronized to android and played without any problem. I would like to ask, does android have any special rules for synchronizing audio and video?

> The formats I've encountered are wav, mp3, mp4, avi. I found that mp4, wav can sync itself to the phone, while avi can't, and mp3 seems to be able to sync as well.

###### Context Code
``` @Test
    fun `parseSourcesToFileScheme - object`() {
        val mediaDir = "storage/emulated/0/AnkiDroid/collection.media"
        val result = parseSourcesToFileScheme("<object data=\"ben.avi\"></object>", mediaDir)
        assertEquals("""<object data="file:///$mediaDir/ben.avi"></object>""", result)```


// not in libAnki
object Sound {
    val VIDEO_EXTENSIONS = setOf("mp4", "mov", "mpg", "mpeg", "mkv", "avi")
```

### PR DESCRIPTION
**Pull request by henriqueccmac**
## Purpose / Description
.avi media file playback

## Fixes
Fixes #15772 

## Approach
We used the ffmpeg LTS library to enable codec conversion in the .avi file. This is a workaround. 
To enable .avi conversion the new advanced setting must be enabled. When enabled, when a .avi file is imported, its codec is transcoded into H.264. 
Although not an ideal implementation (would be best to implement the actual codec), the performance impact doesn't hinder the user experience in a significant way. A 46 second HD video takes ~2-3 seconds to convert during the import in a 2022 Samsung Tab S6.

## How Has This Been Tested?
We created tests to test correctness of file paths and to test if the conversion occurs only when the advanced preference is enabled and when the file has the .avi extension.

_Links to blog posts, patterns, libraries or addons used to solve this problem_
https://github.com/arthenica/ffmpeg-kit
https://developer.android.com/media/platform/supported-formats

## Checklist
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

Co-authored-by: Bernardo Galante <bernardo.galante@tecnico.ulisboa.pt>

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Have you researched or tried another approach? ~2-3 seconds doens't seem like a good experience to me. Specially if this happens in many cards

**Review by mikehardy — CHANGES_REQUESTED** [review]
So I did a thing in CI that let's anyone calculate size difference for any PR, #16613 and now we have our answer

A 29MB size increase in release mode is not anywhere near acceptable for this feature

**Comment by mikehardy** [comment]
I'm going to "draft" this one so it is out of the queue as it is not actionable in the current state
It appears that 2.17 used to work because we used an external webview

Perhaps with the javascript add-on system you could make a javascript add-on for the reviewer that looked for .avi media elements, and if it saw them it rewrote that part of the HTML using DOM tricks in javascript such that it would send the avi to an external media player?

**Comment by BrayanDSO** [comment]
IIRC, the Android [Media3](https://developer.android.com/media/media3) library will be introduced in @criticalAY's GSoC project. From a quick glance, it has a richer external player than the one we used. Maybe it can be used for solving that (I'm leaving the onus of researching to the PR authors)

**Comment by criticalAY** [comment]
Yep! will use it for audio and video attachments

**Pull request closed without merging**
