### PR TITLE
Non null simplification

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This depends on #11538

### CODE REVIEW

**Comment by mikehardy** [comment]
something unhappy about the compile @Arthur-Milchior 

```

w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt: (370, 35): Condition 'mCol == null' is always 'false'
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt: (370, 61): Unnecessary non-null assertion (!!) on a non-null receiver of type Collection

```

**Comment by Arthur-Milchior** [comment]
@mikehardy you copy pasted the error messages from #11598 
In this case, the linter only led to the second error, not the first one

**Comment by david-allison** [comment]
```
w: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/widgets/DeckAdapter.kt: (370, 35): Unnecessary non-null assertion (!!) on a non-null receiver of type Collection
```

**Comment by Arthur-Milchior** [comment]
Tried to rebase, but I realize there is nothing that remains to do

**Pull request closed without merging**
