### PR TITLE
NF: Refactor `Finder`

### PR DESCRIPTION
**Pull request by david-allison-1**
The start of decoupling abstractions from `libAnki`

Also somewhat to get to grips with this part of the codebase

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by dae** [comment]
Not sure this makes much sense with the Rust backend? When you were streaming individual rows directly from the database, cancelling and progress would work, but won't the majority of the time be spent up front now, with the loading of ids from the backend in pages being relatively fast in comparison? It also might be worth checking how much overhead you're adding by calling a progress func on every iteration of the loop - on Python at least, that would be quite expensive.

**Comment by david-allison-1** [comment]
Searching is currently a mess in terms of macro-level performance, I'd estimate that we can get a 3x performance boost (in the Java side - let alone using the Rust) with re-engineering. I'd rather go with a clean design which is compatible with our existing logic, and then optimise, rather than taking on optimisations before we have a good structure (but agreed that we should do them - saying "send a progress notification every n" provides a performance boost).

With this design, we can share the "send the first batch" logic between the Rust and Java

I feel it's useful to split these abstractions. When we move to Rust (with the list of IDs), we won't use progress notifications in this manner, but they will be used. Cancellation is going to be used, so we abstract it out.

When we move back to `sendProgress` style code, it will be best placed on an abstraction in or around `ProgressSender<T>`, rather than inside an individual task.

**Comment by david-allison-1** [comment]
To note: the follow up I'd be going for is (untested): https://github.com/ankidroid/Anki-Android/commit/f8860abb2e96528343f9142bf38f342339161347

I do have to say that I'm used to a `doProgress` being a near-0-cost abstraction, even over a large collection of items, but I'll profile once the code's working

**Comment by dae** [comment]
Sadly in Python even calling a function has a non-trivial overhead. I gather that's not so much of an issue with JIT - I was more assuming you were doing something with that progress like updating a progress bar. It might be at least worth checking the time taken for .query() to return, and then compare that to the time taken to gather all the resulting ids from the completed query. I'd expect the former to dwarf the latter in a non-trivial query, and I'm not so much proposing a new optimization as suggesting you might want to remove the existing "partial search" optimization and simplify things. :-)

**Review by mikehardy — APPROVED** [review]
LGTM but took a conflict while waiting sorry

**Comment by david-allison-1** [comment]
de-conflicted

**Comment by mikehardy** [comment]
:laughing: - this was a big lint rule
```

  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java:1127: Error: Field should be named: 'mRes' [NonPublicNonStaticFieldName]
                  private final List<Long> res = new ArrayList<>();
                                           ~~~
  /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java:1128: Error: Field should be named: 'mSendProgress' [NonPublicNonStaticFieldName]
                  private boolean sendProgress = true;
                                  ~~~~~~~~~~~~
```

**Comment by david-allison-1** [comment]
> 😆 - this was a big lint rule

Now it's in the IDE, I hope to never have to mention it again 😄

**Pull request merged**
