### PR TITLE
Convert Reviewer actions to ExecuteCommand

### LINKED ISSUE #6177: NullPointerException when pressing space bar
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/d167ecd1-4fb1-472f-9ff6-daa5df00158f

Judging from the LogCat, the `DeckPicker` was opened: `No startup screens required`

<details><summary>Logcat</summary>
	
```
--------- beginning of main
05-14 13:41:22.930 I/AnkiDroid(10562): AbstractFlashcardViewer:: Question successfully shown for card id 1561638421620
05-14 13:42:30.268 I/AnkiDroid(10562): AbstractFlashcardViewer:: EASE_2 pressed
05-14 13:42:30.273 I/AnkiDroid(10562): Answering card
05-14 13:42:30.275 I/AnkiDroid(10562): Answering card 1561638421620
05-14 13:42:30.302 I/AnkiDroid(10562): flush - Saving information to DB...
--------- beginning of system
05-14 13:42:30.403 I/AnkiDroid(10562): User has permissions to access collection
05-14 13:42:30.514 I/AnkiDroid(10562): colOpen: true
05-14 13:42:30.515 I/AnkiDroid(10562): No startup screens required
05-14 13:42:30.524 I/AnkiDroid(10562): Handling Activity Result: 901. Result: 52
05-14 13:42:30.526 I/AnkiDroid(10562): Creating notification channel with id/name: General Notifications/AnkiDroid
05-14 13:42:30.527 I/AnkiDroid(10562): Creating notification channel with id/name: Synchronization/Synchronisierung
05-14 13:42:30.529 I/AnkiDroid(10562): Creating notification channel with id/name: Global Reminders/Fällige Karten
05-14 13:42:30.530 I/AnkiDroid(10562): Creating notification channel with id/name: Deck Reminders/Erinnerungen
--------- beginning of crash
```

</details>

<details><summary>Stack Trace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.ichi2.libanki.Card.getODue()' on a null object reference
at com.ichi2.libanki.sched.Sched.answerButtons(Sched.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.getAnswerButtonCount(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer.getDefaultEase(AbstractFlashcardViewer.java:1)
at com.ichi2.anki.Reviewer.onKeyUp(Reviewer.java:5)
at android.view.KeyEvent.dispatch(KeyEvent.java:2772)
at android.app.Activity.dispatchKeyEvent(Activity.java:3559)
at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:1)
at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:2)
at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:3)
at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:4)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:1)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:1)
at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:427)
at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5663)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5531)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5157)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5214)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5190)
at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5354)
at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2783)
at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2291)
at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2282)
at android.view.inputmethod.InputMethodManager$H.handleMessage(InputMethodManager.java:569)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

</details>

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

Pre #6052 - functional changes and fixes to the keyboard mechanism before I make overarching changes to the architecture

* Allow EXIT to work when `blockControls()` has been called
* Block keyboard shortcuts when `blockControls()` has been called.
* Remove `getDefaultEase()`

## Fixes
Fixes #6177 (created after this PR).

## Approach
Unit Tests

## How Has This Been Tested?

Unit Tests

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/AbstractFlashcardViewerKeyboardInputTest.java  3
- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java  3
- AnkiDroid/src/test/java/com/ichi2/anki/ReviewerKeyboardInputTest.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5410708&bid=17739120)

**Comment by mikehardy** [comment]
@david-allison-1 just merged it, rebase away :-)

**Comment by david-allison-1** [comment]
@mikehardy done

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5410708&bid=17739120)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5410708&bid=17739120)

**Comment by david-allison-1** [comment]
Hopefully fixed test failure (didn't fail on my machine before)

https://travis-ci.org/github/ankidroid/Anki-Android/builds/678728952

```
com.ichi2.anki.ReviewerTest > exitCommandWorksAfterControlsAreBlocked FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Caused by:
        java.lang.NullPointerException
            at com.ichi2.anki.AbstractFlashcardViewer.blockControls(AbstractFlashcardViewer.java:2300)
            at com.ichi2.anki.ReviewerTest.lambda$exitCommandWorksAfterControlsAreBlocked$2(ReviewerTest.java:40)
            at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:551)
            at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
            at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:561)
            at com.ichi2.anki.ReviewerTest.exitCommandWorksAfterControlsAreBlocked(ReviewerTest.java:39)
```

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5410708&bid=17739120)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5410708&bid=17739120)

**Comment by david-allison-1** [comment]
Ready to go (definitely 2.11)

There's going to be a series of (hopefully reviewable) PRs over the next couple of weeks which will build up to 6052

**Comment by mikehardy** [comment]
The "don't blink app bar buttons" on review were in exactly this area and created a cherry-pick hash, so I picked these to release 2.10. I'm pretty confident in them but thought I would give you a heads-up. They'll at least get beta exposure prior to going out full public 🤞

**Comment by mikehardy** [comment]
Going out now as 2.10.3beta3 and 2.11alpha6

**Pull request merged**
