### PR TITLE
Improve documentation: activityHandlesRestoreBackup

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
User mentioned that the failure was confusing: it'll occur again, and this needs to be correct to stop crashes, so I've improved the documentation

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by bhatushar** [comment]
Inside `isUninitialized()` why can't we return `sInstance != null` and keep the name as `isInitialized()`? The code style guideline recommends avoiding negative logic.

**Review by mikehardy — APPROVED** [review]
LGTM - `!AnkiDroidApp.isUninitialized` reads poorly but I get it and there's no reason to change -> merging

**Comment by mikehardy** [comment]
@bhatushar to specifically address your comment and why I'm merging anyway - it's a bit of pragmatism really, you are write and I noted it - it does read poorly - but David in particular is pretty busy and the PR itself is both very small while affecting a code path that I expect hardly anyone to ever need to change, plus it's covered by a unit test etc etc - so sometimes rather than going back and forth a lot on a PR I merge and we move on - always plenty to do.

Which is a long way of saying, you're not really wrong, but yes I just merged it ;-)

**Comment by Arthur-Milchior** [comment]
I’ll add that you can do this pr yourself. It’s easy to do, to review, it’s a small but real improvement,  feel free to do such small work if you see anything needing it

**Pull request merged**
