### PR TITLE
Remove minSdk pin workaround

### PR DESCRIPTION
**Pull request by voczi**
Problem fixed after desugar_jdk_libs_nio was updated to version 2.1.0.
https://github.com/ankidroid/Anki-Android/pull/16968
https://github.com/google/desugar_jdk_libs/commit/c7dbf2c920a29db82ebf363255265cde2ccabb5d

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
> Task :AnkiDroid:minifyPlayReleaseWithR8 FAILED
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/outputs/mapping/playRelease/missing_rules.txt.
ERROR: R8: Missing class com.ichi2.anki.dialogs.tags.TagsDialogListener$-CC (referenced from: void com.ichi2.anki.dialogs.tags.TagsDialogListener.<clinit>())
Missing class com.ichi2.anki.reviewer.Binding$-CC (referenced from: void com.ichi2.anki.reviewer.Binding.<clinit>())



I'll restart just in case, but I would not be surprised it's a real issue.

**Comment by voczi** [comment]
Assuming it's a constructor now being called through reflection because of minSdk=23. Should just be a matter of adding the respective PG rule.

**Comment by voczi** [comment]
I'm just trying to make R8 keep the Kotlin metadata now, but I doubt it will work.
After taking a closer look at this, I've reached many dead-ends where it's simply stated to increase minSdk>=24. So I'm not sure, but I think there are two alternatives where we either 1) just close this PR and forget about it or 2) update minSdk to 24 once and for all (important decision for the upcoming 2.19 release).
I guess there's also a third option where we just go scorched earth and re-disable all of the APK optimizations.

**Comment by mikehardy** [comment]
I think we're reasonably close to getting 2.19 out the door - how close of course I do not know, but how about this option:

- don't spend more time on this until minSdk is 24, just let it sit as blocked by dependency
- get 2.19 out, then bump minSdk to 24
- then clear this out ?

**Comment by voczi** [comment]
> * get 2.19 out, then bump minSdk to 24

Sounds good to me.

**Comment by mikehardy** [comment]
yeah - remembered this from our prior collab when doing #17364 bump and saw it during sweeps for appearance of 23 / 24 version so got it

**Pull request closed without merging**
