### PR TITLE
Include filename in IOExceptions thrown by Utils.writeToFile()

### PR DESCRIPTION
**Pull request by tsudoko**
Makes it easier to find out which file causes #3567 on the user's device.
image

### CODE REVIEW

**Comment by timrae** [comment]
Thanks...

1) The function does not throw `IOException` anymore, right? You should be able to remove that from the function signature.

2) Just want to confirm, do you know why are we getting the `完了しました` in the message even though there was an error? The media sync gets cancelled when this error occurs, right? In this case it should not say "complete". Didn't it used to say something like "sync error" here?

**Comment by tsudoko** [comment]
> The function does not throw `IOException` anymore, right? You should be able to remove that from the function signature.

It can throw an `IOException` on `z.close()`, the compiler complained when I tried to remove the `throws` clause.

> Just want to confirm, do you know why are we getting the `完了しました` in the message even though there was an error? The media sync gets cancelled when this error occurs, right? In this case it should not say "complete". Didn't it used to say something like "sync error" here?

https://github.com/ankidroid/Anki-Android/blob/ce0404d757f6edbf67abe4a13d9351c4252b0f78/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L1545-L1549

---

Now that I think about it, re-throwing `IOException` in `Utils.writeToFile()` might be a better idea, since the problem from #3567 could appear not only during media sync.

**Comment by timrae** [comment]
> Now that I think about it, re-throwing IOException in Utils.writeToFile() might be a better idea, since the problem from #3567 could appear not only during media sync.

Sounds good to me!

**Comment by timrae** [comment]
As for the `完了` issue, it should go in a separate PR I think, but I guess we should be calling `showSyncErrorMessage()` instead of `showSimpleMessageDialog()`. We should probably add a new string to make it clear that the sync itself was successful but the media sync stopped prematurely as well.

**Comment by timrae** [comment]
Thanks! Also please try to remember to make a comment when you are ready for re-review, as github still doesn't notify us when new commits are pushed.

**Pull request merged**
