### PR TITLE
Use design time layout attributes to preview layouts with example values

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ Texts and colors are not included in the compiled APK.
+ See http://tools.android.com/tips/layout-designtime-attributes

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Rebase onto develop.

**Comment by hssm** [comment]
Thanks, I wasn't aware of this feature. Any reason you're using `holo_orange_light`?

**Comment by johnjohndoe** [comment]
I use background colors to visualize dimensions of different subviews. This makes it much easier to **spot layout problems**. I try to pick colors for the "debug backgrounds" which are **not** used as the actual app colors.

**Comment by hssm** [comment]
Thanks for the explanation. That makes a lot of sense.

**Comment by timrae** [comment]
Cool, I wasn't aware of this feature either, it's very useful.

**Comment by johnjohndoe** [comment]
You are very welcome. I am happy to help. Thank you for doing open source!

**Pull request merged**
