### PR TITLE
test(ci): fix windows timeout

### LINKED ISSUE #16404: CI: Timeouts on Windows Runner
This has been going on for a while. Placeholder issue to collect diagnostics

* #16253 for similar issue

### PR DESCRIPTION
**Pull request by david-allison**
## Fixes
* Fixes #16404

## Approach

```patch
Index: build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/build.gradle b/build.gradle
--- a/build.gradle	(revision 7853f54d4bd1d3144b4922defbf98570fe578847)
+++ b/build.gradle	(revision 35e7f8fc0aa0d707c0908e3c47e86a9dc9c84320)
@@ -43,10 +43,10 @@
             project.android.testOptions.unitTests.all {
                 // tell backend to avoid rollover time, and disable interval fuzzing
                 environment "ANKI_TEST_MODE", "1"
-
                 useJUnitPlatform()
                 testLogging {
-                    events "failed", "skipped"
+                    // logging "started" helps us catch timeouts
+                    events "started", "passed", "failed", "skipped"
                     showStackTraces = true
                     exceptionFormat = "full"
                 }
```

This pointed to `TagsDialog` being the issue

Tried adding `: RobolectricTest()`, still failed

So I redefined `@Flaky` to work on classes, and ignored the tests

## How Has This Been Tested?
https://github.com/david-allison/Anki-Android/actions/runs/9150302436

Screenshot 2024-05-19 at 21 39 31

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Gets a "what the heck" on *why* TagsDialog fails on windows??
But definitely fixes CI which is A-May-Zing

Thank you

**Comment by david-allison** [comment]
Really happy I finally had the time to deep dive - everything feels like it's going 300% faster now

**Comment by mikehardy** [comment]
This was intertwined with #16356 so it gets a pick to release-2.18 so I can pick the TagsDialog crash fixes

**Comment by david-allison** [comment]
Given this is test-only, I'm happy (and so is CI), cheers!

**Pull request merged**
