### PR TITLE
fix: IPA symbols in Type The Answer

### LINKED ISSUE #15535: [Bug] `<code>`'s `monospace` font is missing International Phonetic Alphabet symbols
* make a type in the answer card with the Back as `liŋˈɡwɪstɪks`

## AnkiDroid

Screenshot 2024-02-16 at 16 16 48

Issue in 2.16.X and 2.17

Font: `Droid Sans Mono`

----

## Anki Desktop

Screenshot 2024-02-16 at 16 17 52

Font: `Menlo` (macos `monospace`)

### PR DESCRIPTION
**Pull request by david-allison**
`liŋˈɡwɪstɪks` failed to render some characters in Type the Answer on API 33

Android's `monospace` font uses Droid Sans Mono, which was missing a number of symbols from the International Phonetic Alphabet (IPA)

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
* Fixes #15535

## Approach

We needed a GPL-Compatible monospace font for this.

GNU FreeFont (Free Mono) seems appropriate, as it has 4,177 glyphs and supported IPA

I obtained this font from [0] rather than building from source

[0] https://www.fontsquirrel.com/fonts/gnu-free-font

Project: https://www.gnu.org/software/freefont/

## How Has This Been Tested?
API 24:

Screenshot 2024-02-16 at 19 55 12

## Learning (optional, can help others)
* Fonts are hard to search by license
* Google Fonts are not 'easily' compatible with Anki, as they want code to be added to the `<head>` element
* Google Downloadable fonts require Play Services 
   * https://developer.android.com/develop/ui/views/text-and-emoji/downloadable-fonts 

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Specifically for discussion: this is a large dependency, but I feel it's worthwhile to fix `type the answer`

**Comment by BrayanDSO** [comment]
> If Android contains monospaced fonts

In the 31 emulator, the ones I found with `Mono` on its name were `CutiveMono` and `DroidSansMono`, so I'm afraid we can't rely on that

**Comment by david-allison** [comment]
Thanks for checking!

**Comment by BrayanDSO** [comment]
https://sourcefoundry.org/hack/

MIT licensed, 304kb uncompressed, tested with `liŋˈɡwɪstɪks`

**Review by BrayanDSO — APPROVED** [review]
Giving our license and that we don't have many options, LGTM

**Review by mikehardy — APPROVED** [review]
Same thought - 500kb space / 303kb transfer would be nice to avoid but if there aren't any other good options you take the option you've got. Those aren't too heavy and we saved more than that by vectorizing many of our graphics. You win some lose lose

LGreattTM as a fix

**Pull request merged**
