### PR TITLE
fixed a crash reverting the coordinator layout line

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Reverting the small change in #13651 

## Fixes
Crash due to the coordinator layout issue in preference screen

## How Has This Been Tested?
tested on oneplus nord ce
Screenshot_52

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by oakkitten** [comment]
This debug build-only crash is intentional though, it should've been `as? CoordinatorLayout` from the get-go, I just forgot to put it in when I made the initial PR (sorry!)

**Comment by criticalAY** [comment]
So how are we going to copy the debug info in debug builds?

**Comment by oakkitten** [comment]
The proper way would be to actually use `CoordinatorLayout`. The next best thing would be using [`Activity.canProperlyShowSnackbars()`](https://github.com/ankidroid/Anki-Android/blob/cef332e7f000bd49a8c204fed47a0ca9f5b5e585/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt#L284) and showing a snackbar if `true` and a toast if `false`—but this should be reserved for actions that can take any activity.

**Comment by BrayanDSO** [comment]
Make the layout a coordinator layout

**Comment by BrayanDSO** [comment]
Although, can't a toast be shown saying: "Hey Dev, this should be a coordinator layout, fix this" be better? Crashing interrupts people focus on whatever they are doing and make they need to check logcat in order to fix that instead

**Comment by criticalAY** [comment]
I agree with Brayan as I was trying to fix another issue and this happened

**Comment by criticalAY** [comment]
> The proper way would be to actually use `CoordinatorLayout`. The next best thing would be using [`Activity.canProperlyShowSnackbars()`](https://github.com/ankidroid/Anki-Android/blob/cef332e7f000bd49a8c204fed47a0ca9f5b5e585/AnkiDroid/src/main/java/com/ichi2/anki/snackbar/Snackbars.kt#L284) and showing a snackbar if `true` and a toast if `false`—but this should be reserved for actions that can take any activity.

A check for snackbar umm let's see but preference screens are not having coordinator layout technically so would it be feasible?

**Review by david-allison — CHANGES_REQUESTED** [review]
Not crashing is better than crashing, but not like this.

Could you change the crashing code to:

```kotlin
        val errorMessage = "While trying to show a snackbar, " +
            "could not find a view with id root_layout in $this"

        if (BuildConfig.DEBUG) {
            CrashReportService.sendExceptionReport(IllegalArgumentException(errorMessage), "Activity::showSnackbar")
        } 
        Timber.w(errorMessage)
        showThemedToast(this, text, false)
```

**Comment by BrayanDSO** [comment]
> preference screens are not having coordinator layout technically so would it be feasible?

It should be feasible to make the preferences activity layout be a CoordinatorLayout

**Comment by lukstbit** [comment]
The showSnackbar methods shouldn't throw an exception if a CoordinatorLayout isn't available. We have fragments where we can't make the transition showThemedToast->showSnackbar because it would break testing. Some of those fragments are tested in isolation and in order to run them the testing framework provides an empty/no CoordinatorLayout activity.

**Pull request closed without merging**
