### PR TITLE
Allow to install debug version of AnkiDroid 

### PR DESCRIPTION
**Pull request by madhead**
Allow to install debug version of AnkiDroid without `parallel-package-name.sh` hack.

### CODE REVIEW

**Comment by madhead** [comment]
Is it worth fixing?

**Comment by timrae** [comment]
Yeah I think this is pretty useful

**Comment by madhead** [comment]
Can't figure out how to fix it.. When I changed content URI in tests to `.debug` package, I get `SecurityException`:

    com.ichi2.anki.tests.ContentProviderTest > testUpdateNoteFields[device_23_x86(AVD) - 6.0] FAILED 
        java.lang.SecurityException: Permission not granted for: CardContentProvider.update /notes/1477957307667 (com.ichi2.anki.debug)

Any ideas?

**Comment by timrae** [comment]
Do the tests pass locally?

**Comment by hssm** [comment]
It looks like those errors happen when running the tests on API 25 (unrelated to this PR).

**Comment by timrae** [comment]
Closing for now, please reopen if you figure it out! :)

**Pull request closed without merging**
