### PR TITLE
cleanup for FieldEditText

### PR DESCRIPTION
**Pull request by oyeraghib**
## Purpose / Description
Kotlin Cleanup : FieldEditText

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Please merge  https://github.com/ankidroid/Anki-Android/pull/11590 into this PR

**Review by david-allison — APPROVED** [review]
Looks great!

**Review by david-allison — APPROVED** [review]

**Review by david-allison — CHANGES_REQUESTED** [review]
Please check the PRs compile

```
> Task :AnkiDroid:compilePlayDebugKotlin
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt: (206, 37): Type mismatch: inferred type is Uri? but Uri was expected
```

**Comment by mikehardy** [comment]
Still has a compile error of some sort:

```

e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt: (206, 37): Type mismatch: inferred type is Uri? but Uri was expected
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt: (208, 20): Overload resolution ambiguity: 
public final fun pastePlainText(): Boolean defined in com.ichi2.anki.FieldEditText
public final fun pastePlainText(): Boolean defined in com.ichi2.anki.FieldEditText
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt: (213, 5): Conflicting overloads: public final fun pastePlainText(): Boolean defined in com.ichi2.anki.FieldEditText, public final fun pastePlainText(): Boolean defined in com.ichi2.anki.FieldEditText
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.kt: (227, 5): Conflicting overloads: public final fun pastePlainText(): Boolean defined in com.ichi2.anki.FieldEditText, public final fun pastePlainText(): Boolean defined in com.ichi2.anki.FieldEditText

```

**Pull request closed without merging**
