### PR TITLE
Kotlin: enable `AutoCloseable.use { }`

### PR DESCRIPTION
**Pull request by david-allison-1**
Kotlin by default targets JDK 6

This lib allows usage of `AutoCloseable.use { }` instead of just `Closeable.use { }`

## How Has This Been Tested?

Briefly tried it and it seems to work now

## Learning (optional, can help others)

* https://stackoverflow.com/a/43269795
* https://mbonnin.medium.com/the-different-kotlin-stdlibs-explained-83d7c6bf293 

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
Wow! Is that really something all kotlin users have to do? It appears so but seems odd.

https://kotlinlang.org/docs/compiler-reference.html#no-stdlib-jvm doesn't indicate jdk7 or 8 stdlib... just *a* stdlib

Anyway, this would work for me except I want that `1.5.10` duplicate version centralized as I believe these move in lock step yes?

**Comment by mikehardy** [comment]
it's also up in here https://github.com/ankidroid/Anki-Android/blob/67e8d920666c22ff3d76ec241a0ccd99021bab69/build.gradle#L18 - would be ideal if that was defined once in build.gradle then reference in app/build.gradle etc

**Comment by david-allison-1** [comment]
https://mbonnin.medium.com/the-different-kotlin-stdlibs-explained-83d7c6bf293 is fairly informative, added to the OP

**Comment by david-allison-1** [comment]
There's also a possibility that we can use `jvmTarget` (1.7 or 1.8), will need to see if this works, and how/whether desugaring takes place on API 21. For now, I don't need streams, but they will come in handy later


```
kotlinOptions.jvmTarget = JavaVersion.VERSION_1_8 
```

**Comment by mikehardy** [comment]
Interesting article. The conclusion is counter to this testing experience though, are you sure this works all the way down to API21?

https://kotlinlang.org/docs/whatsnew14.html#dependency-on-the-standard-library-added-by-default - related, if we can't do -jdk7 stdlib then we can remove it entirely

**Comment by david-allison-1** [comment]
> Interesting article. The conclusion is counter to this testing experience though, are you sure this works all the way down to API21?
> 
> https://kotlinlang.org/docs/whatsnew14.html#dependency-on-the-standard-library-added-by-default - related, if we can't do -jdk7 stdlib then we can remove it entirely

I don't think we're using a Kotlin Grade project, we're still using Groovy

**Comment by david-allison-1** [comment]
Giving it a try

```kotlin
class Streamer {
    fun get(): Int {
        return listOf(1, 2, 3, 4, 5)
                .map { n -> n * n }
                .filter { n -> n < 10 }
                .first()
    }

    fun closeable() {

        val xx = X()

        xx.use {
            Timber.w("inside")
        }
    }

    class X : AutoCloseable {
        override fun close() {
            Timber.w("close")
        }

    }
}
```

on API 21 Emulator

* Testing with none: ❌ - closeable fails
* Testing with JDK7: ✔️ (eh? it shouldn't work as this also tests streaming, probably desgaring working its magic)
* Testing with JDK8:  ✔️ 
* Testing with `jvmTarget = "1.8"`: ❌- closeable fails

**Comment by david-allison-1** [comment]
extracted to variable. `ext { }` didn't seem to go through for the main plugin, so used `ext.kotlin_version`

**Review by mikehardy — APPROVED** [review]
making plugin versions variables is not a great experience no - but this is quite centralized should be easy to manage, thank you!

**Pull request merged**
