### PR TITLE
Update AnkiDroid to Mathjax 3

### PR DESCRIPTION
**Pull request by hgiesel**
## Purpose / Description
Update to Mathjax 3.1.2, up-to-date with Anki v2.1.36.

## Fixes
no issue for it

## Issues
Just like Anki, AnkiDroid does not have a functioning localStorage in its reviewer WebView.
This causes this exception to be thrown: 

    MathJax localStorage error: Cannot read property 'getItem' of null

MathJax 3 uses localStorage to save user settings, which the user can change by right clicking the output ([example](https://mathjax.github.io/MathJax-demos-web/tex-chtml.html)). So while this error log is annoying, MathJax 3 still works without a hiccup.

Anki resorted to simply filtering out the error log. I will have a look into how you'd do this on Android.

## Approach
I exchanged the MathJax source files in the project, updated the MathJax to the conf which Anki uses, and linked to it in the card.js. Additionally, MathJax 3 is now Promise-based.

Note, that it only includes a subset of the MathJax 3 files. Not all files are needed, because we don't use the full extent of MathJax, e.g. we don't use Asciimath, rendering to SVG, etc.. Which files it includes, can be seen in this [Bazel file in the Anki repo](https://github.com/ankitects/anki/blob/master/ts/mathjax.bzl).

## How Has This Been Tested?
I viewed cards featuring cards in the Emulator.

## Learning (optional, can help others)
* [Anki MathJax 3 PR](https://github.com/ankitects/anki/pull/809)
* [Another PR which included more libraries to load by default, so that users can use the full extent of MathJax packages](https://github.com/ankitects/anki/pull/824)

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Looks sane but is obviously a massive diff

**Comment by mikehardy** [comment]
Oh cool! Did not even know this was afoot. The CI failure was a type answer unit test failure that is unrelated, I restarted that runner and if it passes I'll restart the emulator tests, should pass.

My most important point re: Mathjax is always this question: with this PR will we be in sync completely with the Anki ecosystem? Based on your comments I'm assuming yes. But that also implies we don't have more features (and thus a larger APK than necessary when built for release)

**Comment by hgiesel** [comment]
> Looks sane but is obviously a massive diff

The other option is making installing MathJax via `npm`, and moving it to its destination directory part of the build process for AnkiDroid. This is how Anki does it.

>  But that also implies we don't have more features (and thus a larger APK than necessary when built for release)

It's the same conf, and the exact same files as in Anki.

**Comment by mikehardy** [comment]
> > Looks sane but is obviously a massive diff
> 
> The other option is making installing MathJax via `npm`, and moving it to its destination directory part of the build process for AnkiDroid. This is how Anki does it.

My Day Job(tm) is javascript/typescript mostly so I'm familiar with all that stuff. For a once every couple years job, I think I'll avoid the toolchain dependency and just commit the results. If it becomes time-consuming I could see maybe a "refresh" script that makes sure you have node installed and does the build and copies it in, but I'd still commit the results rather than have developers get node up and running and manage all that. Would be a separate PR and no priority at the moment though

> > But that also implies we don't have more features (and thus a larger APK than necessary when built for release)
> 
> It's the same conf, and the exact same files as in Anki.

Perfect. This is amazing, thank you!

**Comment by Arthur-Milchior** [comment]
@hgiesel Thank you so much. It really noticeably increased the speed at which I can see content of cards with dozens of mathjax formula. That was essentially the last thing that was too slow for my taste in ankidroid. I'm amazed how much faster mathjax 3 is compared to 2.

I've some mathjax related questions. If you know mathjax, maybe you can answer them. Otherwise, I'll just try to figure out myself later in the future.

There is still a noticeable lag when showing a card with even a single mathjax equation in it. This is mostly annoying because the whole card content lag, so I get a full black screen (in night mode) before getting some content, and flickering is not cool. 
I know that some website allow to load mathjax as plain text, and then transform the plain text into a mathematical formula, in order to load the main part of the page immediately. Do you think you could do this in ankidroid if you already know mathjax? This would allow to get the non-mathjax content displayed immediately.


Do you know whether there is any way to pre-render mathjax? To let mathjax knows what formulas it will need to render, and so give the formulas to mathjax so that it does the work in background and save the result for when the card is actually used.
It's kind of easy to know what will be the next content displayed. I.e. if we have some formulas in the answer, we should prepare them while the user read the question. If a card is in learning, then it's content was already computed the last time the card was seen. And otherwise, we can easily know what is the next new/due card that will be seen.
I am currently working on getting the next card ready in advance, but I'll still need to figure out how to help mathjax pre render the formulas, and help would be appreciated

**Comment by hgiesel** [comment]
> I know that some website allow to load mathjax as plain text, and then transform the plain text into a mathematical formula, in order to load the main part of the page immediately.

The hiding of the WebView before MathJax is rendered happens on purpose at the moment, [controlled by a HTML class `mathjax-needs-to-render`](https://github.com/ankidroid/Anki-Android/blob/fa3c20167bd7905b96c351b3536cbd4552bc8ac1/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L2207).

I would consider showing users unrendered MathJax worse than showing them a black screen, because it also makes the content jump, especially if you use block equations using `\[ ... \]`.

> Do you know whether there is any way to pre-render mathjax?

It is possible. MathJax also runs in NodeJS, [even though the docs are a bit sparse atm](http://docs.mathjax.org/en/latest/server/overview.html). But the trouble of interfacing with Node from Java might not be worth the trouble (or even be possible, I'm not really familiar with Android). 

I don't think MathJax does that kind of caching when rendering equations, however. Here are some [MathJax docs on performance](https://github.com/mathjax/MathJax/wiki/Understanding-mathjax-performance).

**Comment by mikehardy** [comment]
By the time you get to executing JS inside an Android app outside having a WebView and the Chrome engine doing it for you via simple interfaces you are basically running a react-native app which requires a company the size of facebook (they make react-native) to make work. I do react-native professionally and we don't want to do that here.

**Pull request merged**
