### PR TITLE
KotlinCleanup: convert to Parcelize in FieldEditText

### PR DESCRIPTION
**Pull request by alyoshenka**
## Purpose / Description
`@KotlinCleanup`: "Use `@Parcelize`"

Part of a larger issue, this PR transitions to using `@Parcelize` to save instance state in `FieldEditText.kt`. The old implementation used `Parcelable`, this change enhances clarity and makes the code more elegant. 

## Fixes
Related #10489 

## Approach
The older way of implementing `Parcelable` to save state introduces a lot of boilerplate code and as such is prone to errors. By instead using `@Parcelize` the code is much easier to read and maintain.

## How Has This Been Tested?
A test class has been added for this file: `FieldEditTextTest`. This test passed with the original version as well as the new version. 
To the best of my knowledge, this test adequately covers the changes. Additionally, running all tests using `./gradlew jacocoTestReport` passed.

## Learning (optional, can help others)
Since `FieldEditText` extends `View`, not `Activity`, it cannot be tested in the same way as an Activity. 

[Here](https://stackoverflow.com/questions/57310783/is-there-an-elegant-way-to-save-and-restore-view-state-in-kotlin) is the post I found that best described how the proposed changes should work.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- ~[ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)~
- ~[ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)~

### CODE REVIEW

**Comment by oakkitten** [comment]
A neat change!

Although I think that saving `ord` shouldn't be a part of this view, and probably this view should not exist at all. `ord` is not used in the view at all, as is not in related to UI. There's an ongoing effort in #12773 to add searching capabilities to editor, and I think converting the list of fields to a RecyclerView would be the way to go. This would be faster and provide some continuity and animations and would render state saving logic obsolete.

I would also argue against testing saving state. What these tests test is not our code or behavior, but `kotlinx.parcelize`. I should assume that `kotlinx.parcelize` already has tests for this 😛. The purpose of saving state is to survive activity recreation (e.g. in cases of theme change). Unit tests are just not sufficient for the job; if you want to test that, you need an integration test that ideally simulates various events that lead to activity recreation and checks if anything breaks.

By the way, you can have a ``@Test fun `With names that have spaces in them`() {}`` which is a bit easier to read. And I want to ask, what's the purpose of checking the value of `originalOrdValue`?..

**Comment by alyoshenka** [comment]
Thanks for the feedback! My reasoning for the providing the test was to ensure that `ord` is correctly saved using `@Parcelize` because I was concerned about my implementation being incorrect. I'm checking `originalOrdValue` to make sure that a new View loaded from the same state has the same `ord`, for the same reason.

Given that this View will likely change, can you give me some direction on where to go with the Kotlin Cleanup? Or just leave as is for now?

**Comment by oakkitten** [comment]
I meant this assert

```kt
val dummyOrdValue = 5
assertThat("dummy ord value must not be 0 for test validity", dummyOrdValue, not(0))
```

I understand that the value must be not `0` else the test would be meaningless. I just have never seen an assert like that before. Merely wondering!

I also understand the reason for the tests, but I mean *the implementation* was written by kotlin-parcelize authors. What these tests are testing is _the use_ of kotlin-parcelize API. The thing about those API is that it's dead simple, and unlikely to change. Which is to say, these tests are extremely unlikely to fail, and tests that are unlikely to fail are just not very useful. Conversely, as these tests do not check how the surrounding code use the `ord` value, the fact that the tests pass gives us little comfort. (This here is just my opinion)

As for Kotlin cleanup of *this* class, perhaps we can wait for @raehat, maybe they have plans for it? If you pop up on Discord maybe other folks will have some suggestions.

**Comment by alyoshenka** [comment]
The reason I put that assert in there was so that the value could be changed, and still error if it was (incorrectly) set to 0. I figured that was slightly better than a `// must not be set to 0 for test validity` comment. 

I understand what you're saying about this doesn't really add value to the codebase. I'll check Discord and see what comes up.  

Thanks so much for the polite feedback, it is much appreciated.

**Comment by raehat** [comment]
> There's an ongoing effort in #12773 to add searching capabilities to editor, and I think converting the fields to a `RecyclerView` would be the way to go. This would be faster and provide some continuity and animations and would render view state saving logic obsolete.

I do agree, I will implement recycler view in Card Editor, and push changes this week

**Comment by alyoshenka** [comment]
Not sure if this PR will even end up going through due to the planned changes, but in case it does, I removed the unnecessary test file.

**Review by lukstbit — APPROVED** [review]
Changes LGTM, and I don't see a reason not to implement them. Thank you!
I would postpone any more immediate work on this until things become more clear about the class future usage.

**Review by BrayanDSO — APPROVED** [review]
Lovely. Thanks

**Pull request merged**
