### PR TITLE
Updated strings from Crowdin 20210528

### PR DESCRIPTION
**Pull request by david-allison-1**
Standard I18N sync

For catching problems with `kn` language: #8979

### CODE REVIEW

**Comment by mikehardy** [comment]
for this one you'll need to also edit+push the changes to the language sync script and Java utliities no?

**Comment by david-allison-1** [comment]
> for this one you'll need to also edit+push the changes to the language sync script and Java utliities no?

Yes, I've got a PR pending, but I'd like the "language sync" from `kn` to be pure and free from other irrelevant language changes

* Sync + merge
* Add language to both script and app
* Sync + merge (containing only `kn`), so we have an easy review

**Comment by david-allison-1** [comment]
Fixed one:

https://crowdin.com/translate/ankidroid/7290/en-bn?filter=basic&value=0#q=empty_cloze_warning

Will check locally to see if there's more

**Comment by david-allison-1** [comment]
(A good reason to do this PR before adding a new language)

**Comment by david-allison-1** [comment]
all good locally, needs a new sync

**Comment by mikehardy** [comment]
crowdin will only rebuild the zip with rate limits on free plans. I think it's 30minute minimum between rebuilds, but might be 45, otherwise you just get the same zip contents and go on a wild goose chase

**Comment by david-allison-1** [comment]
Checks haven't started - reopening

**Comment by mikehardy** [comment]
yeah the workflow doesn't trigger on all the things that it should, sorry - haven't fixed that. I usually just manually go into actions and run it but close/reopen is a good trick

**Comment by david-allison-1** [comment]
Am I fine to be cheeky and merge this with admin privileges, or would you rather keep to "everything gets a review"

**Comment by mikehardy** [comment]
if I18N passes lint / unit tests merge, I say

**Comment by mikehardy** [comment]
I'm leaving it unapproved so you may feel cheeky

**Pull request merged**
