### PR TITLE
Readme.md: Update "build" to point to GitHub actions on master #8382

### LINKED ISSUE #8382: Readme.md: Update "build" to point to GitHub actions on master
It currently points to TravisCI, which we no longer use

https://shields.io/ will provide a badge

Use `build` as the shield text

### PR DESCRIPTION
**Pull request by Arnold2381**
## Purpose / Description
Updation of Readme badge link to actions page from travis 

## Fixes
Fixes #8382

### CODE REVIEW

**Comment by david-allison-1** [comment]
In future, could you ensure that the fixes is defined as `Fixes #8382` rather than `#8382`, as it links the issue and the PR

**Comment by david-allison-1** [comment]
I'm really sorry - I'm not sure about this one, it shows "passing", but the build is still running.

It's definitely better than what we have, and I have seen this check show 'pending', so I'm not sure what's going on

image

**Review by david-allison-1 — APPROVED** [review]
Thanks! Looks good to me

**Comment by Arnold2381** [comment]
Thanks!

**Review by mikehardy — APPROVED** [review]
RIP Travis, Long Live GitHub Actions :-)
Thanks

**Comment by mikehardy** [comment]
Hi there!

Just a friendly notice (one per person for PRs merged in March, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for March 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

Thanks!

**Pull request merged**
