### PR TITLE
Fix broken fullscreen

### LINKED ISSUE #3867: Temporarily displaying the menu bar in landscape mode with fullscreen enabled hides the rightmost menu button and the timer under the Android control buttons
On 2.5beta17, with fullscreen enabled, you can temporarily unhide the menu bar by swiping down from the top of the screen. If you're in landscape mode when you do this, you'll find that the three-vertical-dot menu icon is hidden beneath the Android controls (back, home, running apps). The timer is also hidden. See here:

screenshot_2015-11-22-13-59-32

With fullscreen disabled in Settings, landscape mode displays the menu bar icons and timer correctly, like this:

screenshot_2015-11-22-14-00-20

I like to review in landscape mode, and this issue makes it clumsy for me to edit my cards as I review them.

### LINKED ISSUE #4042: Full screen mode leaves large unused space below Answer buttons
On v2.6alpha4:

screenshot_20160105-073333
^ Notice the white space below Show Answer. Notice the bar at the top of the screen (blue) is also not hidden.
screenshot_20160105-073403
screenshot_20160104-205754

Debug info:
AnkiDroid Version = 2.6alpha4

Android Version = 6.0.1

ACRA UUID = 958af048-4c94-4a95-845f-b6ff5ba2150c

### PR DESCRIPTION
**Pull request by timrae**
It turns out that my conclusion that there was a bug in the support library when handling fitsSystemWindows() in immersive mode was incorrect, and in fact there was simply an error in my layout that made it seem that was the case. I corrected the error in [my port of the immersive mode sample project](https://github.com/timrae/ImmersiveModeSample) today to prove the concept, and just finished implementing the same changes in AnkiDroid.

@hssm 
It seems that you ended up taking a very similar approach in #4236  to what I ended up doing here, so that's a good sign I think. However I think my slightly different approach is a bit more clean and seems to be completely working as intended.

Could you please give it a test and review and let me know what you think? There are probably still some areas that could do with some tweaking.

Note: I also removed the `flashcard_progressbar` element as it seems to be unused.

Closes #3867 
Closes #4042

### CODE REVIEW

**Comment by timrae** [comment]
I just pushed a second commit with a few bugs fixes and stylistic improvements

**Comment by hssm** [comment]
Looks good and works well.

Your version ends up covering the top bar and answer buttons when the system/action bars are shown. Since it's not resizing the content then it doesn't have the laggy resize issue that mine does but you also lose those views.

It's not really a problem but personally I would opt for having them if it's easy to get them in. I think it should  be possible to clone them and make them appear/disappear like we do with the action bar (I say clone instead of move to avoid the resizing issue).

**Comment by timrae** [comment]
> It's not really a problem but personally I would opt for having them if it's easy to get them in. 

Yeah I agree, though I wouldn't say I'm motivated to do it myself ;)

> I think it should be possible to clone them and make them appear/disappear like we do with the action bar (I say clone instead of move to avoid the re-sizing issue).

If possible it'd probably be better to just animate them. I think it should be possible to implement with a CoordinatorLayout Behavior.

**Comment by hssm** [comment]
Yeah I'll give it a try some time tomorrow.

**Pull request merged**
