### PR TITLE
[Kotlin Migration] ActivityList

### PR DESCRIPTION
**Pull request by oyeraghib**
## Purpose / Description
[Kotlin Migration] ActivityList

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
CI is failing

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
Happy with the code changes, needs a rebase

**Comment by david-allison** [comment]
Either fix the error and select "amend" when committing.

Or in Android Studio: select "Git", select the two commits to combine, and "squash" them on the right click menu:

Screenshot 2022-05-13 at 18 51 33

When you're pushing, select "force push"

Screenshot 2022-05-13 at 18 52 18

**Comment by david-allison** [comment]
Taken on a conflict, looks good otherwise

**Review by mikehardy — APPROVED** [review]
Yep - looks like needs to fix the conflict (I think LoadProunciationActivity went away in unrelated PR) then good to go

**Comment by oyeraghib** [comment]
Closing as it is done in another PR #11909

**Comment by david-allison** [comment]
You should ideally keep the same PR open and force push

**Comment by oyeraghib** [comment]
Sure! Will keep that in mind.

**Pull request closed without merging**
