### PR TITLE
Putting tests for utility functions in Tags class

### PR DESCRIPTION
**Pull request by Vaibhavi1707**
## Purpose 
Adds tests for utility functions in the Tags class.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
Hi, this includes commits which are already in `master`.

* When making a branch, could you checkout your new branch when on master
* For this case, could you `git rebase -i` and `drop` the irrelevant commits
* Then force push with lease to your branch on the remote (this PR): `git push --force-with-lease`

**Comment by Vaibhavi1707** [comment]
Will do

**Comment by TarekkMA** [comment]
you can make your tests more declarative by using `assertListEquals` and `assertEquals`

**Comment by Vaibhavi1707** [comment]
Yes, that'll be better. All this time I tried adding `assertSame`, I missed this. Thanks a lot

**Comment by Vaibhavi1707** [comment]
Please wait, I have to complete the rebasing situation. I couldn't do it yesterday.

**Comment by david-allison-1** [comment]
> Please wait, I have to complete the rebasing situation. I couldn't do it yesterday.

No rush and no stress intended! Just flagging to avoid effort for other maintainers.

**Comment by Vaibhavi1707** [comment]
Okay, thanks :)

**Comment by Vaibhavi1707** [comment]
I am sorry for the inconvenience, but I'll have to close this or, as I've created another or only with the required changes.

**Comment by david-allison-1** [comment]
> I am sorry for the inconvenience, but I'll have to close this or, as I've created another or only with the required changes.

Don't worry - have a try at git every once in a while, being able to recover if something goes wrong is a valuable skill

**Pull request closed without merging**
