### PR TITLE
[Clean up]: Fix Android studio warnings

### PR DESCRIPTION
**Pull request by rubenquadros**
## Purpose / Description
Clean up Android Studio warnings.

## Fixes
Relates to #13282 

## Approach
I ran `Inspect code` on Android studio to check for warnings/errors. I refactored the code with the help of IDE to fix the warnings. 

<details>
<summary>Before:</summary>
<br>
Screenshot 2023-10-07 at 5 26 59 PM
</details>

<details>
<summary>After:</summary>
<br>
Screenshot 2023-10-07 at 5 55 25 PM
</details>

## How Has This Been Tested?
I have run `./gradlew test` to test these changes and make sure everything is working fine with no funny errors caused by this. Also relying on the pipeline to show any errors.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by lukstbit — CHANGES_REQUESTED** [review]
Thank you for contributing!
The issue linked mentions to fix only the issues in _one_ file. This makes it easier to review and also to keep score on issues still present. Fixing issues across multiple files(you've made changes to 43 files for example) makes it hard to review.

I'm ok with fixing multiple files here but please go over the changes you've made and keep only the changes in files _were all the IDE issue were resolved_ for that file(when you open a file in Android Studio look in the top right corner, there' should be a green check). For example the changes you've made here in `DatabaseCheck`, `NoteFieldDecorator` or `Utils` are ok to keep as you fixed all issues, changes for example in `CardBrowser` or `NoteEditor` should be reverted as not all IDE issue were fixed.

This would make this PR easier to review and merge.

**Comment by rubenquadros** [comment]
> Thank you for contributing! The issue linked mentions to fix only the issues in _one_ file. This makes it easier to review and also to keep score on issues still present. Fixing issues across multiple files(you've made changes to 43 files for example) makes it hard to review.
> 
> I'm ok with fixing multiple files here but please go over the changes you've made and keep only the changes in files _were all the IDE issue were resolved_ for that file(when you open a file in Android Studio look in the top right corner, there' should be a green check). For example the changes you've made here in `DatabaseCheck`, `NoteFieldDecorator` or `Utils` are ok to keep as you fixed all issues, changes for example in `CardBrowser` or `NoteEditor` should be reverted as not all IDE issue were fixed.
> 
> This would make this PR easier to review and merge.

Sure, I will revert the changes for which all the issues for a file are not fixed!

**Comment by rubenquadros** [comment]
Have updated the PR! Please review it once again :)

**Comment by rubenquadros** [comment]
@lukstbit I have updated the PR! Please review it again :)

**Review by lukstbit — APPROVED** [review]
LGTM, thank you for making the changes!

**Review by BrayanDSO — APPROVED** [review]

**Pull request merged**
