### PR TITLE
Fixed a conditional check for schedV2

### LINKED ISSUE #13429: [BUG]: automated sync lead to "collection not open"
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

* Install a recent issue
* have an account connected to ankiweb
* enable automated sync
* close the app
* wait enough to trigger a sync on start (I think it's 10 minutes)
* open the app

### Expected behaviour

Sync, then a usable app. Or at least in case of error, just a forced restart and a working app.

### Actual behaviour

"Collection not opened" appear while the sync occur.

Sometime instead, I got a SQL error message before the Collection not opened.

Also, if I just press okay, I get the warning message every 20 seconds or so the the app is not responding, while the app actually works perfectly as long as I press on the "wait" button.

### Debug info

```text
AnkiDroid Version = 2.16alpha93-debug

Android Version = 13

Manufacturer = samsung

Model = SM-A226B

Hardware = mt6833

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A226B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.65 Mobile Safari/537.36

ACRA UUID = a2af6a9d-da31-4e59-bb5d-ff252cd2826d

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

If I accept the android message to force quit the app and restart it it works as expected. If I stop the automated sync, it works correctly.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Follow up for #13433

## Fixes
Fixes #13429

## How Has This Been Tested?
Tested on one plus nord ce

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
@Arthur-Milchior please test the issue on this branch. I am hopeful it will fix it

**Review by mikehardy — APPROVED** [review]
That is somehow very difficult for me to parse through mentally, but I believe I have done so correctly and I believe this is a good change - same semantic meaning for the conditional but null-safe now. Thanks

**Comment by Arthur-Milchior** [comment]
I force pushed removing the first two commits. Because they cancelled each other and led to plenty of merge conflict

**Comment by criticalAY** [comment]
thankyou!

**Review by david-allison — APPROVED** [review]

**Pull request merged**
