### PR TITLE
fix: Removed done button and bottom separator in Intro screen

### LINKED ISSUE #13380: [BUG]: Layout issue in Intro screen
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

On startup of the app.

### Expected behaviour

The bottom separator should not come over the top of "Sync from AnkiWeb" button.

### Actual behaviour

The bottom separator comes over the top of "Sync from AnkiWeb" button.

bsep

### Debug info

```text
AnkiDroid Version = 2.16alpha94-debug

Android Version = 11

Manufacturer = unknown

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Android SDK built for x86 Build/RSR1.210210.001.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36

ACRA UUID = 8f4ed37f-3b1f-498c-ae43-a85002a1497a

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by pratyaksh1610**
## Purpose / Description
Removed done button and bottom separator in Intro screen

## Fixes
Fixes #13380

## Approach
Changed the visibility.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

**Review by david-allison — COMMENTED** [review]
What does this look like on a tablet?

**Comment by pratyaksh1610** [comment]
> What does this look like on a tablet?

I have updated the PR template.

**Comment by BrayanDSO** [comment]
Can we remove the bar?

**Comment by criticalAY** [comment]
> Can we remove the bar?

I think it looks fine considering the negative space we have

**Review by criticalAY — COMMENTED** [review]
You need to make changes in the landscape file to as we also have a landscape -v of this file

**Comment by pratyaksh1610** [comment]
I think there is no issue in landscape mode. 

l

**Comment by criticalAY** [comment]
Ahh I don't think there is an issue if we remove the done button as there are other two buttons and one of them does the same action as the done button. 
But what's your reason for the bar to be removed ?

**Comment by BrayanDSO** [comment]
> But what's your reason for the bar to be removed ?

It isn't fitting well in the layout (hence this PR) and only serves as a divider for the DONE button, which does nothing and IMO should be removed

**Comment by criticalAY** [comment]
wait you are not talking about `title_divider` ?

**Comment by lukstbit** [comment]
I second Brayan and think the divider and "Done" button should be removed as the done button is the same with "Get Started".

**Comment by criticalAY** [comment]
Ok if majority of us want to remove it then fine, I am also in

**Comment by david-allison** [comment]
I'm also +1 on the 'Done' button being removed.

**Comment by lukstbit** [comment]
>  How can I edit and commit changes ?

The library has methods to remove the divider and the buttons. Saw them once but I don't remember their names, check the  class that IntroductionActivity is extending.

**Comment by pratyaksh1610** [comment]
> > How can I edit and commit changes ?
> 
> The library has methods to remove the divider and the buttons. Saw them once but I don't remember their names, check the class that IntroductionActivity is extending.

I have updated the PR.

**Review by lukstbit — APPROVED** [review]
Looks much better now, thanks!

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
