### PR TITLE
WhiteBoard Editor item tint color to white

### LINKED ISSUE #13838: [BUG]: Wrong icon tint
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

There are icons that don't show the icon tint colour they are supposed to show 
-> drawing layout has a pen icon that is shown in black color rather than white in the toolbar though it is set to white but for some reason, it does not work 

### Expected behaviour

In light mode the pen color is white

### Actual behaviour

Black

### Debug info

```text
AnkiDroid Version = 2.16.0beta1-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = OnePlus

Model = EB2101

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; EB2101 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = 30fe5941-45f0-4cae-b24f-4345edd9b3a5

New schema = true

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by SanjaySargam**
## Purpose / Description
Wrong icon tint

## Fixes
Fixes #13838

## Approach
Created new drawable

## How Has This Been Tested?
Tested on Emulator ( Pixel 5 API 33 )
Screenshot 2023-05-13 192805

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by lukstbit** [comment]
When fixing any bug related to tinting/theming, screenshots should be provided for all themes we have(light, plain, dark, black).

**Comment by SanjaySargam** [comment]
Dark
dark

Black
black

Plain
plain

**Review by n1snt — APPROVED** [review]

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
I think that approaches that don't duplicate resources are better, such as https://github.com/BrayanDSO/Anki-Android/commit/a24b312098f1f01968ef04d09a9a9af54c089b86 (note that `@color/black` shouldn't be hardcoded here)

**Comment by SanjaySargam** [comment]
> I think that approaches that don't duplicate resources are better, such as [BrayanDSO@a24b312](https://github.com/BrayanDSO/Anki-Android/commit/a24b312098f1f01968ef04d09a9a9af54c089b86) (note that `@color/black` shouldn't be hardcoded here)

I agree with you. But the problem is `stroke_width` button is not visible in black theme
Screenshot 2023-05-16 082444

**Comment by SanjaySargam** [comment]
> I think that approaches that don't duplicate resources are better, such as [BrayanDSO@a24b312](https://github.com/BrayanDSO/Anki-Android/commit/a24b312098f1f01968ef04d09a9a9af54c089b86) (note that `@color/black` shouldn't be hardcoded here)

I agree with you but the problem is `stroke_width` button is not visible in Night Mode
Screenshot 2023-05-16 082444

**Comment by BrayanDSO** [comment]
Using `?attr/textColor` (or a similar attribute) instead of color/black should fix this

> > I think that approaches that don't duplicate resources are better, such as [BrayanDSO@a24b312](https://github.com/BrayanDSO/Anki-Android/commit/a24b312098f1f01968ef04d09a9a9af54c089b86) (note that `@color/black` shouldn't be hardcoded here)
> 
> I agree with you but the problem is `stroke_width` button is not visible in Night Mode Screenshot 2023-05-16 082444

Using `?attr/textColor` (or a similar attribute) instead of color/black should fix this

**Comment by SanjaySargam** [comment]
@BrayanDSO 
pushed latest commit check it once. I didn't use any duplicate resources

**Review by mikehardy — APPROVED** [review]
This LGTM - what do you think @BrayanDSO since you had some thoughts earlier?

**Review by BrayanDSO — APPROVED** [review]

**Pull request merged**
