### PR TITLE
Switch 'Anki Card' and 'Card Browser' in System Text Context Menu

### PR DESCRIPTION
**Pull request by david-allison-1**
I feel 'Anki Card' will get more use

----

Draft as untested and I'm not sure whether this will be accepted.

For existing users, this will enable both of the menu items if they previously viewed the settings, which may not be ideal

### CODE REVIEW

**Comment by mikehardy** [comment]
CI only failed because I manually cancelled the build, and I only did that because it's late here and I'm checking status of some very specific builds before doing a new alpha. I will probably forget to restart the build after, but that's the next step - no meaning in it, sorry

**Review by mikehardy — APPROVED** [review]
I don't want to overthink this - it seems fine, if you want to un-draft it and merge it, works for me

**Comment by Arthur-Milchior** [comment]
I don't even know what "System Text Context Menu " is, or what this code do

**Comment by david-allison-1** [comment]
When you highlight a word outside AnkiDroid, a context menu appears with items, if you click an arrow, app specific items appear.

* Google Translate Adds "Translate"
* Wikipedia adds "Search Wikipedia"
* AnkiDroid adds "Card Browser"

**Comment by Arthur-Milchior** [comment]
Nice. Yeah, seems cool to directly create a card through it.

**Pull request merged**
