### PR TITLE
Rework widget

### LINKED ISSUE #2038: AnkiDroid should not be running if the user is not using it
Originally reported on Google Code with ID 1136
```
If the user has no widgets and notifications set to never, AnkiDroid should not be running.
While it is up to the OS whether to stop the application or not, we should make sure
we do not keep it running longer than we need to.
For example, we should disable the BOOT_COMPLETED receiver if notifications are set
to never.
Moreover, we should not started the service to update the widget if there is no widget.

Does it happen again every time you repeat the steps above? Or did it
happen only one time?
Yes

What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title)
1.1
On what version of Android? (Home screen > menu > About phone > Android
version)
4.0
```

Reported by `flerda` on 2012-05-12 07:34:32

### LINKED ISSUE #3308: Widget drains phone battery
Originally reported on Google Code with ID 2412
```
After upgrading to Ankidroid 2.3.2 my phone battery strarted draining really fast. After
testing a bit more, I found that ankidroid is keeping the phone awake while on wifi.

Uninstalling Ankidroid solved the problem.

Attached picture shows battery usage without calling or surfing (idle). Points 1-2
are idle+wifi+ankidroid installed. 2-3 idle+no wifi+ankidroid installed. Point 5 is
where ankidroid was uninstalled.

Phone: Samsung Galaxy S4 mini (GT-I9195)
OS: Android 4.4.2
```

Reported by `camiloaa` on 2014-11-18 11:05:42

<hr>
 * *Attachment: battery_usage.png<br>*

### LINKED ISSUE #3392: The number of "Cards due" notification isn't consistent?
Originally reported on Google Code with ID 2496
```
(I'm not sure if it is a bug, but ...)


About "Cards due " notification number, 

(a) When the deck list is being shown,
   it means "the number of the due cards of the collection at that time" .
 
(b) When a deck overview screen (or its study screen) is being shown,
    it means that (a) + "the number of the cards which are not ready to be reviewed
in the deck" 

(c) When the home screen of Android is being shown,
    it means (b).
    (To be more precise, (a) + "the number of the cards which are not ready to be reviewed
in the last selected deck".) 
    
    (the number of the widget is the same as it.)
    

For example, a short time ago, 
the number of the notification on my AnkiDroid changed one after another as follows.
 


    home screen (199)...(c) 

--> deck list (190)...(a) 

--> overview of deck "A" (199)...(b) (this deck has 9 cards which are not ready to
be reviewed)

--> deck list (190)...(a) 

--> overview of deck "B" (193)...(b) (this deck has 3 cards which are not ready to
be reviewed)

--> home screen (193)...(c)



Is it intentional design?

 
 
Does it happen again every time you repeat the steps above? Or did it
happen only one time?

every time


Version of AnkiDroid
2.4beta17

Version of Android
4.3

```

Reported by `snowtimeglass` on 2015-01-27 14:25:50

### LINKED ISSUE #3430: First card reviewed in deck doesn't update number of cards due (when widget is enabled)
Originally reported on Google Code with ID 2534
```
What steps will reproduce the problem?
Reviewing cards.


What is the expected output? What do you see instead?
It seems that the first card reviewed doesn't count to change the number of cards due.
For instance, if at the start it states that I have four cards due (at the top: 0 0
4), then after correctly answering the first card I still see 0 0 4. Then after second
card: 0 0 3. After third: 0 0 2. After fourth: returns to main screen. 

The bugginess is also there but a bit different if there are incorrect cards involved.


Does it happen again every time you repeat the steps above? Or did it
happen only one time?

It seems to happen every time.

AnkiDroid Version = 2.4

Android Version = 4.1.2

ACRA UUID = 38a3902c-e698-4d2f-8ed5-79cae5887516

```

Reported by `yakovblum` on 2015-02-18 20:40:32

### LINKED ISSUE #3745: Review session returns to deck screen after every card with "No cards are due" message
I have been having a strange problem since recently. I will explain it using an example from today:
- I have 19 cards to review, and I press 'study'
- I press '10 minutes/again' for the first card -> the review session stops and gets me back to the deck screen with a toast saying 'no cards are due yet.'
- I press 'study' again, and go to the next card
- I press '10 minutes/again' -> the review session stops again and gets me back to the deck screen with the same toast
- repeat until the review list is exhausted

This is very annoying on the long run. I tested it with the desktop version, starting from the same deck state, and it's behavior is correct.

Has a similar issue been created yet? If necessary, I can make my collection available to reproduce the issue. I guess I could also record a video from my session, just tell me where to put it.

### PR DESCRIPTION
**Pull request by hssm**
I've turfed a lot of the widget code. Most of it is code for the big and medium widget which have been dead for years. The small widget has been simplified a lot which also fixes a few bugs it was causing.

I've removed some overzealous calls to `reset()` which caused a couple of the issues. Ensuring the cutoff time is updated is now handled by the internal `_checkDay()` method which will not have adverse side-effects (like resetting in the middle of a review session).

Also there was a horizontal bar in the middle of the widget that signified your progress for the day. I removed that to make my life easier. I'm not sure if anyone will even notice. 

--

Fixes #3392 - The counts are rebuilt every time. No more pointless caching.
Fixes #3430 - Fixed by removing `reset()` calls.
Fixes #3745 - Fixed by removing `reset()` calls.
Close #3308 - I have no reason to believe that it's true and there is no compelling evidence to support the case.
Close #2038 - No longer applies.

### CODE REVIEW

**Comment by timrae** [comment]
Don't you wanna put this in the 2.5 branch?

**Comment by timrae** [comment]
Great work on this :)

**Comment by hssm** [comment]
Yeah I did. I just forgot which direction we were doing the merging. If it's easier to just open a new PR targeting the release branch I can do that (and I'll include that other commit I just merged with it).

**Comment by timrae** [comment]
It's alright, I'll cherry pick them into the other branch

**Pull request merged**
