### PR TITLE
[GSoC] Replaced usage of catchingLifecycleScope with launchCatchingTask

### PR DESCRIPTION
**Pull request by divyansh-dxn**
Since both the functions almost do the same thing, there is no point for both to co-exist.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by Arthur-Milchior — APPROVED** [review]

**Review by lukstbit — CHANGES_REQUESTED** [review]
Remove the last commit because:

- I think there could be valid cases where a simple string would be used as the message
- The only usage of the new methods that receive a StringRes is in Statistics which is going t o be removed with the new backend. There's no need to add a string here and have people translate it just to be removed a bit later.

**Comment by divyansh-dxn** [comment]
> Remove the last commit because:
> 
> * I think there could be valid cases where a simple string would be used as the message
> * The only usage of the new methods that receive a StringRes is in Statistics which is going t o be removed with the new backend. There's no need to add a string here and have people translate it just to be removed a bit later.

But having a common error dialog which always have a single tile Error(R.string.vague_error) doesn't seems good to me. Also the migration https://github.com/ankidroid/Anki-Android/pull/12375 already had a custom title for progress dialog.

One thing can be that instead of StringRes, it would take a string as title but I'm also not convinced with it because error dialog titles should be localized.

**Comment by lukstbit** [comment]
> Also the migration https://github.com/ankidroid/Anki-Android/pull/12375 already had a custom title for progress dialog.

If you need them then add(just) the methods you need and delegate to the current methods.

**Comment by divyansh-dxn** [comment]
> > Also the migration #12375 already had a custom title for progress dialog.
> 
> If you need them then add(just) the methods you need and delegate to the current methods.

Seems fair 👍

**Review by lukstbit — APPROVED** [review]

**Pull request merged**
