### PR TITLE
Converted Floating Action Button to supported library

### LINKED ISSUE #4936: Convert FloatingActionMenu to supported library
The current FloatingActionMenu library is abandoned.

We should either convert to an actively developed replacement such as this one (the best I saw): https://github.com/leinardi/FloatingActionButtonSpeedDial

Or since our menu is fairly simple, implement it using framework SDKs such as this example: https://github.com/ajaydewari/FloatingActionButtonMenu (from https://stackoverflow.com/questions/30699302/android-design-support-library-expandable-floating-action-buttonfab-menu)

### PR DESCRIPTION
**Pull request by tanmayChakrawarty**
## Purpose / Description
Converted FloatingActionMenu to the supported library.

## Fixes
Fixes #4936 

## Screenshot
https://github.com/tanmayChakrawarty/FabMenu
screen

## How Has This Been Tested?

Tested on a physical device (Android 5.0).

## Learning (optional, can help others)
https://github.com/tanmayChakrawarty/FabMenu

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
(https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
@tanmayChakrawarty this was already in progress via #8290 as noted on the linked issue

**Comment by tanmayChakrawarty** [comment]
@mikehardy Sorry, I didn't see that. I want to know can I implement the background blur or content hiding feature whenever fab is clicked as mentioned in #8223

**Comment by mikehardy** [comment]
@tanmayChakrawarty you bring up an interesting point, I'm going to consolidate discussion on the existing PR and tag you there.

**Comment by iamvs-2002** [comment]
> @mikehardy Sorry, I didn't see that. I want to know can I implement the background blur or content hiding feature whenever fab is clicked as mentioned in #8223

You can do it by adding all the background in a layout and then changing the alpha of that layout whenever the fab is clicked.

**Pull request closed without merging**
