### PR TITLE
chore: remove AnkiDroid main module

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

This was added in an attempt to exclude non-English language files from the IDE to discourage new contributors from translating them

In Android Studio hedgehog this causes a complaint / gradle sync failure related to gradle and non-gradle modules though

## How Has This Been Tested?

If I open Android Studio on the Anki-Android repo with these files present, I receive an error message indicating it won't tolerate gradle and non-gradle modules

If I remove these files, and I open Android Studio on the Anki-Android project, it is fine

## Learning (optional, can help others)
No good deed unpunished

## Checklist

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
For posterity: See: https://github.com/ankidroid/Anki-Android/pull/14304 & https://github.com/ankidroid/Anki-Android/commit/09a5302a444df7e68574215fe9c8c525c1bb115f

**Review by david-allison — APPROVED** [review]
I'd prefer to also want to revert the `gitignore` changes in the linked commit (so this becomes a rollback)

Approving this regardless: implementer's choice

**Comment by david-allison** [comment]
I'm sad to see this one go: it was a personal boost to productivity as it excluded the resource files from the search

**Comment by mikehardy** [comment]
I think it was a step forward but it is not valid to have the IDE choke unfortunately 😞 

Good call on the "how" - with that prompt and the hash I reset the branch and made it a formal `git revert <hash>` then re-pushed, better?

**Review by david-allison — APPROVED** [review]

**Pull request merged**
