### PR TITLE
NF: Use Abstract Sched more when there is no difference between schedulers

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
One thing which I hate when working with scheduler, is that if I am looking for the definition, I go to AbstractSched instead of going to anything useful.

So I did the following change:
* if the code is the same in both sched, or not redefined in sched v1, I move the definition to AbstractSched
* I move some members to AbstractSched
* If an important part of both sched code is shared, I factorize it and put the difference either in a method or as a parameter of the similar method
* I move DeckDueTree in a separate file, because this file is already big enough
* When they are difference, I added a comment to explain what they are

In some case, I had to add some abstract methods, because they are used by the methods I moved to AbstractSched

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Only API=24 JDK="1.14" failing. I don't understand why

**Comment by mikehardy** [comment]
David just pointed out that the scheduler lives on in python code, meaning there is still a lot of value in tracking upstream here. If that's the case (I thought it was already moved to rust!) then we need to see upstream refactors to match these as we still need to track upstream in order to reliably mirror behavior.

**Comment by Arthur-Milchior** [comment]
May I suggest having the discussion in https://github.com/ankidroid/Anki-Android/issues/6819 so that we can track it in a single place and don't need to look for a bunch of PR which may get merged or not

**Comment by Arthur-Milchior** [comment]
Closed, because even if we factorize, I don't expect that adding to AbstractSched will be the way

**Pull request closed without merging**
