### PR TITLE
[Fixed] Wrong symbol for ascending/descending sorting in card browser #5802

### LINKED ISSUE #5802: Wrong symbol for ascending/descending sorting in card browser
###### Reproduction Steps

1. Open card browser
2. Menu > change display order
3. Look at the symbol after the current selection

###### Expected Result

Ascending symbol for ascending sorting 

###### Actual Result

Ascending symbol for descending sorting. See screenshot: the sort field is sorted Z to A (descending) but the triangle looks upwards/ascending.

Screenshot_20200310-094008~(1)

###### Debug info
AnkiDroid Version = 2.10alpha45

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [ x ] character to confirm the points below:*

[X  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by coma123**
## Fixes #5802 

sorting

### CODE REVIEW

**Comment by david-allison-1** [comment]
Hi, could you take a look at #6126, this PR does the same thing. 

There are comments there for additional work required which would need to be tested.

**Comment by mikehardy** [comment]
To be quite specific since the other PR seems to be stuck, in order to commit this we just need one more little change followed by testing, feedback from @RSBat in comment https://github.com/ankidroid/Anki-Android/pull/6126#issuecomment-625713513 (which has good testing scenarios) is that these lines need to be removed as well: https://github.com/ankidroid/Anki-Android/blob/dcfd5bd27e88b999f76de18e322776cadb40ef6d/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L513-L515

If you do that (remove those lines and test things) then this could be merged - thanks!

**Comment by coma123** [comment]
@david-allison-1 thanks for indicating this PR, didn't check before making new PR.
@mikehardy removed these lines as you showed.

**Comment by david-allison-1** [comment]
@coma123 Looks good to me!

Before I approve, could I confirm that you tested the change against RsBat's comment, and that the behaviour was as you'd expect.

**Comment by mikehardy** [comment]
@coma123 this just waiting on confirmation from you that you ran the test scenarios that were mentioned https://github.com/ankidroid/Anki-Android/pull/6126#issuecomment-625713513 I think

**Comment by coma123** [comment]
@mikehardy was busy this week at work and could no look at this.
Checkinfg now, but removing this lines did not change anything, I mean when you first enter and sort by any filter it has wrong arrow, when you click again already applied sort filter then it makes right arrow.

So looking where I can find to solve this, maybe you have some suggestion.

**Comment by coma123** [comment]
Hey @mikehardy @david-allison-1, sorry was busy this week at work and could not take a look. After testing removed default sorting on other place too in CardBrowser and reverted symbols back to normal as it was.
Now looks better and working. Would be great if you can test too and check if everything is perfect.

**Comment by mikehardy** [comment]
Hello! with the 2.14 release we started accepting donations with the stated goal of accepting money from users (the users' way of saying "Thanks!") to support maintenance and development of AnkiDroid.

We are looking through PRs merged in releases going back to release 2.10 (where we have good record keeping of what's in releases) to let our contributors know.

If you'd like to submit an expense related to your work here, to share in a portion of our hopefully-sustainable monthly disbursement, please read here and do so in the next couple of days:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process

This is our first time handling donations and attempting to compensate anyone with these processes, so please be flexible and patient with us

Thank you for your contribution to AnkiDroid!

**Pull request merged**
