### PR TITLE
OnBackpress deprecation handled

### PR DESCRIPTION
**Pull request by MudssirAhmed**
## Purpose / Description
deprecation: compileSdk 33 issues, In this PR onBackPress depreciation, is handled.

## Fixes
I change onBackPress with onBackPressedDispatcher.
[Issue Link](https://github.com/ankidroid/Anki-Android/issues/12364)

## Approach
onBackPress handled with onBackPressedDispatcher.

## How Has This Been Tested?
Manual test in my Handset.
I test manually by going to the screen.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by pratyaksh1610 — COMMENTED** [review]
Template ignored .
Please fill the PR template, else the PR will get closed.

**Comment by MudssirAhmed** [comment]
> Template ignored . Please fill the PR template, else the PR will get closed.

I'm new here, Thanks for the mention!

**Comment by mikehardy** [comment]
Really sorry this has sat so long! It looks like the correct direction to go to fix the problem correctly.
It also has some conflicts because we (those that have reviewer power...) did not get to it in a timely way, our fault, apologies.

I'll see if I can fix it up against the current API34 compile target in dependency-updates branch and get this landed as part of the effort to resolve #14558

**Comment by mikehardy** [comment]
related commit https://github.com/ankidroid/Anki-Android/pull/14515/commits/de116ebfddaada43665321ade961146ddabcd276

**Comment by BrayanDSO** [comment]
Marking as `Needs a new dev`

**Comment by lukstbit** [comment]
From what I understood about predictive back navigation there's a lot more work to be done to properly implement it(check [this answer](https://stackoverflow.com/questions/75462234/proper-usage-of-onbackpresseddispatcher) from one of the engineers working on it), it's not as simple as adding onBackPressedDispatcher.addCallback() and deleting onBackPressed().

I would recommend that we close this PR + the linked api 33 deprecation issue and we move to track it in #14558 .

**Comment by mikehardy** [comment]
> I would recommend that we close this PR + the linked api 33 deprecation issue and we move to track it in #14558

Agreed

**Comment by BrayanDSO** [comment]
I gave a ride to testing the predictive stuff. I guess that we could use a simple version of it while this thing actually gets out to the general public (it is still restricted to a developer option) and more activities are updated to good Android practices.

**Comment by lukstbit** [comment]
I still think keeping the deprecated onBackPressed() method along with the warning is better to indicate that work needs to be done vs adding a simple callback, removing the warnings and realizing when the feature becomes available that we need to do work to actually implement it.

After a quick look I think we could resolve like half of the deprecations now.

**Pull request closed without merging**
