### PR TITLE
build(ci): add emoji to pinned items to reorder

### PR DESCRIPTION
**Pull request by david-allison**
This orders all of the 'checks' together and makes 'Sync Translations' easier to recognize

Before:

* Code Quality Checks
* Emulator Tests
* Publish
* Sync Translations
* Unit Tests

After:

* 🚀 Publish
* 🌐 Sync Translations
* 🛠️ Code Quality Checks
* 🛠️ Emulator Tests
* 🛠️ Unit Tests

## How Has This Been Tested?

Screenshot 2024-12-20 at 19 44 25

Screenshot 2024-12-20 at 19 45 58

https://github.com/david-allison/Anki-Android/actions

* https://github.com/david-allison/Anki-Android/pull/43

### CODE REVIEW

**Comment by david-allison** [comment]
This may require a change of 'required checks' in the repo settings.

If this is a controversial change, close it, I'm not tied to it

We may also want `Add/Remove Labels` and `Conflict Scan` to have the 🛠️ so the PR checks are vertically aligned.

**Review by mikehardy — APPROVED** [review]
🆗 🆒

**Comment by mikehardy** [comment]
likely yes on required checks change, have to merge first to have the new names available for selection here https://github.com/ankidroid/Anki-Android/settings/branch_protection_rules/17281133

**Comment by david-allison** [comment]
I'll add 🛠️ to:

* Add/Remove Labels
* Conflict Scan

**Pull request merged**
