### PR TITLE
Yet Another Alternative Adaptive Icon

### PR DESCRIPTION
**Pull request by cydia2020**
See #4798

### CODE REVIEW

**Comment by cydia2020** [comment]
image

**Comment by cydia2020** [comment]
image
image
image

**Comment by MarcinMoskala** [comment]
👍

**Comment by mikehardy** [comment]
This would be fine by me but is not my favorite (because for some reason I like borders as a personal preference). I like that this has the question/answer idea baked in with the top/bottom, but I still prefer a well-defined icon that pops off the background like the simple one. I've left feedback on all of them now and just want to be clear I appreciate any effort and my aesthetic opinion may be worthless :-). But feedback is feedback

**Pull request closed without merging**
