### PR TITLE
NF: remove useless semicolons

### PR DESCRIPTION
**Pull request by Arthur-Milchior**

### CODE REVIEW

**Review by david-allison-1 — COMMENTED** [review]
This should be available as a lint check already. Can/should we enable it?

**Comment by Arthur-Milchior** [comment]
It was shown to me by automated code inspection already. 
I do not know whether it's the same thing as lint and how to automate finding new ones now that we don't have travis

**Comment by david-allison-1** [comment]
You can still mark the rule as fatal and perform a lint check manually via.

`gradlew AnkiDroid:lintRelease`

We'll be moving back to regular CI (we really need it), auto lint checking will also be included in this.

**Comment by mikehardy** [comment]
As I'm merging things I run `./gradlew clean jacocoTestReport lintRelease` as my local test (with all our supported APIs represented by a running emulator) since those were our good/no-good tests before

**Comment by david-allison-1** [comment]
On my PC now. `UnnecessarySemicolon` is the warning string - this won't be an easy lint rule to add as it's not an Android lint check. 

Let's get this in.

**Review by david-allison-1 — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
