### PR TITLE
focus answer field when text input required

### PR DESCRIPTION
**Pull request by werkn**
This is a solution to Issue #4699.  Places a toggle in Preferences->Reviewing that allows the answer field during card reviews to be automatically focused.

### CODE REVIEW

**Comment by Alyxvance** [comment]
i am not sure if i am right here with
https://github.com/ankidroid/Anki-Android/commit/07311ab6915ec38b7e05b44a392a828b04d95bfe
i have testet this on 2.8.4
the focus on the inputbar  which is shown on the bottom on screen works well
but if you have selectet type answer in the card then the focus wont work.
greetings

**Comment by werkn** [comment]
Ok, I'm travelling right now but will look at when I get back. Could you
provide reproduction steps so I can provide a fix.  Nothing crazy just
something like:

1.  Do action A, Click box B
2.  ....
N.  Error condition here, expected result:

Thanks, Ryan

**Comment by Alyxvance** [comment]
hm i think a video explain it better. i hope it works
https://youtu.be/oErXoR4s1l8
for infos what i do see subtitle 
the heavy check mark was not shown caus i use 
https://github.com/ankidroid/Anki-Android/issues/4841

**Comment by Alyxvance** [comment]
if you have seen the video right you shoyt seen thets the Show keyborad ist enabled
cause if is not aktive the other methot wont work too
this issue is only if you have input in card enabled
screenshot_20180610-025336

**Comment by werkn** [comment]
I see, you have the input box workaround set.  I did not support the input box within the card as it doesn't work the same way the default answer field does and as its under Advanced->Workarounds which are experimental and not app-core features.  I assumed the functionality will change in the future.  I'm new to the code base so I'll need to consult a senior maintainer as to what the future of input box within the card will be before implementing any changes.

@timrae is this pull request fine to leave without supporting Settings->Advanced->Workarounds->Text Input box in Card?  I was thinking adding a toast that comments the functionality isn't supported when users enable/disable auto-focus answer field.

**Comment by Alyxvance** [comment]
ah, i see, its an another instanse then. well, take you time, it will not kill me

**Comment by timrae** [comment]
I'm not super familiar with that part of the code base either to be honest as I have never used this feature. This issue of focus of the input field has a long history, so I was hoping @ospalh might chime in with some comments

**Comment by timrae** [comment]
@agrueneberg 

I noticed you also worked on this feature in #617, do you have any comments?

**Comment by bandico0t** [comment]
Hello @werkn,
I'm also interested in this feature and I saw that you request was merged, but I don't see the setting under Settings -> Review.
I wasn't able to find it and even joined the beta testers team. I believe at the moment I have the latest version in Google Play.
Should I build the app from source code to get this feature?
Thank you

**Comment by timrae** [comment]
You need to join the alpha program. Instructions are in the same place as the beta program. Alternatively you can install from apk file downloaded from GitHub

**Comment by timrae** [comment]
Actually this hasn't been merged yet, although I did merge  a different PR related to this. For the current PR I want someone familiar with the topic to review, but nobody has stepped forward unfortunately.

**Comment by mikehardy** [comment]
@timrae doesn't look like we're going to get any external review but it looks like a thoughtful change from my look at the diff. Even handles whether it has a hardware keyboard connected, and appears limited to only those with the type answer option and this new option enabled. If it doesn't alter the experience for anyone that doesn't opt-in I don't see why it shouldn't go - I've contemplated using type to enter before but between the diacritic comparison ( #4821 ) and all the taps for the keyboard it slows review so much I don't do it. This could make it useful feature. I'd patch it up vs my recent changes and re-PR if you'd review for any nits

**Comment by mikehardy** [comment]
I attempted to rebase this and prepare it for merge vs the current code and I saw 3 things -

1. AnkiDroid/src/main/res/values/strings.xml should not have been deleted
1. .gitignore should not have been modified
1. For some reason it doesn't work? Tried on API28 emulator - I can see that the code checks the preference correctly and attempts to request focus, but I get no focus on the input field and the keyboard does not pop up. If I manually tap the field I get the keyboard as expected and the diff works when the answer shows so I think my card template is set up correctly

I fixed the first two problems as I rebased to master before I pushed into a branch on my fork, but I'm not sure why it isn't working. If anyone wants to pick this up, you can see my rebased/fixed branch here:

https://github.com/mikehardy/Anki-Android/tree/autofocus_answer_field

**Comment by mikehardy** [comment]
Hey that's great, if you want to do a git reset - - hard mikehardy/autofocus-answer-field after adding me as a remote it might save you the time of the rebase and fix up on the first 2 issues but not important either way

If you need something api specific we have a great infrastructure for that by adding a method to the CompatHelper object, a base implementation in CompatV15 then overrides in higher APIs as needed

What did you test it on?

**Comment by werkn** [comment]
@mikehardy 
I just pulled in the last 8 months of commits from master and brought my branch up-to-date.

Running on a newly setup Nexus 5 VM (API 28) everything seems to be working as expected.  Note, I'm also using the default keyboard.  

Video can be found here: 
[API 28 Nexus VM](https://youtu.be/AIw5C97xsCU)

I also tested this on a live device (Moto G4) running 7.1.1, and an older 4.4 Alcatel device.
----

Out of curiosity what does your card template look like?  I've attached mine which I took directly from the desktop docs.  Maybe your template differs and is causes the issues.

### Template
screenshot_1544079963

**Comment by werkn** [comment]
There's also another issue I've found that is closely related to an issue I opened (#4820) that has to do with the lifecycle and creation of cards following **delete** and **undo** actions which effectively reload the previous card. 

Currently if you delete a card that follows a card with input, when redisplaying the card with input after a delete it will not autofocus.  I have a fix for this but I'll wait until we clear up the current issue.

**Comment by mikehardy** [comment]
Hmm. Could you re-push (probably a force push after the rebase) to this PR, I'll pull it and see what happens? Your testing sounds thorough so I suspect it was something on my end that I'll be able to figure out, likely ending with a confirm it works as expected...

**Comment by mikehardy** [comment]
@werkn you might be busy but just in case this was lost in the shuffle, see my comment above - I can test this after you push your rebased version to github and maybe it's just ready to go?

**Comment by werkn** [comment]
@mikehardy Sorry, been travelling in a fairly rural area with spotty internet over the holidays.  My pull request is indeed non-functioning as there were changes to card system that I must of missed pulling in when I rebased (my git-fu isn't the greatest).  My thoughts are that it would be easiest to just add me to your rebase and close this pull request and we can work of that one.  I'm back to work next week and will wrap this up so it can be committed.

**Comment by mikehardy** [comment]
Sounds like you were doing the holidays right :-). Okay, my git-fu is still at the toddler stage but I did rebase mikehardy/autofocus_answer_field with current master and while I haven't tested the intended functionality of this PR it seems to have merged fine at least. My comment here on getting it (once you've added my fork as a remote) should still apply, and you can just force-push to your branch with this PR still open I think https://github.com/ankidroid/Anki-Android/pull/4818#issuecomment-443545335

**Comment by mikehardy** [comment]
I'm going to close this as I could not get it to work but I'm open to a merge if you've got the code laying around re-open or open a fresh PR. Seemed like it was close

**Comment by Alyxvance** [comment]
why you have sill not implementet 
https://github.com/ankidroid/Anki-Android/commit/07311ab6915ec38b7e05b44a392a828b04d95bfe
i have to add it by my own again and again for me works is not perfekt but works 
and it is better 
greetings

**Comment by mikehardy** [comment]
@Alyxvance examine our list of recently closed PRs, think for a moment, then ask again https://github.com/ankidroid/Anki-Android/pulse/monthly ;-) - the question should be "what have you done to help?"

At this point, what you have done to help that PR is given us feedback that it works, which is useful. But it's in the wrong spot. You should post feedback on the PR itself. Other than that :man_shrugging: - that's how open source projects work.

**Comment by mikehardy** [comment]
Ah - actually it is in the right spot, is that on this PR but is closed? With this comment: "I'm going to close this as I could not get it to work but I'm open to a merge if you've got the code laying around re-open or open a fresh PR. Seemed like it was close"

"I could not get it to work" - as in I tested it and it failed testing, it needs work

**Comment by Alyxvance** [comment]
Okay sorry if i make troubble ... I have written 2 years ago a Response ... 
The 4. Or 5. Post Here ... 
It works in the aktual Beta and alpha ... Some Times of you do Not enter a Text it skips the Rating Buttons ...

**Comment by mikehardy** [comment]
I can re-test to see exactly how it failed again and describe it more clearly - I should have done so in my initial close. There was definitely some problem with it

**Comment by Alyxvance** [comment]
okay...
yes its some times if you use a hardware keyboard and do not write any text in the input field and then press enter it skips the rating buttons and shows the next card. 

the option "write in card" is a another instance if this feature on then it dosn't work.
if "write in card" on you do not get fokus on the input field in card.

**Comment by david-allison-1** [comment]
Hi @Alyxvance, This sounds like #5333, could you confirm this reproduction steps? 

Thanks

**Comment by Alyxvance** [comment]
yes i can confirm i have made a video https://www.youtube.com/watch?v=zuFjNLL4_fc
this is native playstore beta 
this is not implementet https://github.com/ankidroid/Anki-Android/commit/07311ab6915ec38b7e05b44a392a828b04d95bfe

if you want i can make a video with implementation but the skipps are difficult to get 

this is an older video https://www.youtube.com/watch?v=oErXoR4s1l8

but this are 2 diffrent instances one instannce are the type in card and the other then you have 
input field at the bottom

**Comment by david-allison-1** [comment]
> yes i can confirm i have made a video https://www.youtube.com/watch?v=zuFjNLL4_fc
> this is native playstore beta
> this is not implementet [07311ab](https://github.com/ankidroid/Anki-Android/commit/07311ab6915ec38b7e05b44a392a828b04d95bfe)
> 
> if you want i can make a video with implementation but the skipps are difficult to get
> 
> this is an older video https://www.youtube.com/watch?v=oErXoR4s1l8
> 
> but this are 2 diffrent instances one instannce are the type in card and the other then you have
> input field at the bottom
> 
> in the voideos ther are subtitles in to explain

I've got this issue in my backlog, will try to remember to ping you when it's done.

Fairly simple really: we handle the 'enter' key event inside a WebView listener, and it bubbles up and gets handled by the regular `onKey[Up/Down]` handler, causing two actions. I haven't put too much thought into a design to fix it, but it hopefully won't be too hard.

**Comment by Alyxvance** [comment]
independent of fokus
Well i have seen something 
not sure if its essential but if Type in card then the schow answerbutton is behint the keyborard if the software keybord on 
ichi2 anki

**Comment by Alyxvance** [comment]
tell me if its wrong if i tell yo more about keyboard issues 
see here anki is in full screen mode Hide the system bars 
Screenshot_20200326_222313_com ichi2 anki

**Comment by mikehardy** [comment]
This one still needs work - we're nearly caught up on PR backlog but without file conflict resolution etc (and maybe a note from me? I seem to have tested it and seen a failure before) this won't go in

**Comment by werkn** [comment]
@mikehardy this pull request is mine.

I haven't looked at this in ages but if I remember the conflicts were minimal at one point.  If I get some time in the next few weeks I'll fix up whats here and hopefully get it ready for review/commit.

**Comment by werkn** [comment]
Pulled all of master from the last 2 years into *autofocus_answer_field*.  

Testing it currently and appears to work as expected on API 28 with a Pixel 2 in VM.  

Also for testing I'm using the card template I included on this comment to this repo, if anyone is testing this PR it would help if they used my card template or linked the one they are using:
[https://github.com/ankidroid/Anki-Android/pull/4818#issuecomment-444775390](https://github.com/ankidroid/Anki-Android/pull/4818#issuecomment-444775390)

---

Will look into the issues seen by @Alyxvance, but I suspect as originally mentioned that he is using InputBox from advanced features.  

As per my earlier pull request comment on this issue:

> I see, you have the input box workaround set. I did not support the input box within the card as it doesn't work the same way the default answer field does and as its under Advanced->Workarounds which are experimental and not app-core features. I assumed the functionality will change in the future. I'm new to the code base so I'll need to consult a senior maintainer as to what the future of input box within the card will be before implementing any changes.
> 
> @timrae is this pull request fine to leave without supporting Settings->Advanced->Workarounds->Text Input box in Card? I was thinking adding a toast that comments the functionality isn't supported when users enable/disable auto-focus answer field.

Wasn't sure if a rebase or merge was preferred.  Let me know what's needed to move this forward, happy to contribute 😃.  While looking through commit history it appears contributors/core team have been busy working, much appreciated 👍👍👍.

Thanks,
werkn

**Comment by Alyxvance** [comment]
nope, inputbox from advanced does not get focus 
i use the normal input https://github.com/ankidroid/Anki-Android/pull/4818#issuecomment-604194683 rigtht side of piture but it will be nice if its works on card input too 

btw i use android 10 on Huawei, Anki 2.10.Alpha56 and your card template works too

Screenshot_20200413_112647_com ichi2 anki

**Comment by werkn** [comment]
@Alyxvance, okay thanks for the feedback.

I will look into InputBox and see what I can do.

**Pull request closed without merging**
