### PR TITLE
fix: Media check file list dark mode appearance

### LINKED ISSUE #15263: [BUG]: List of unused media has white background in Black theme
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Use Black theme
- Have unused media in the collection.media folder
- Click Check media

### Expected behaviour

The list of unused media has white text on gray background.

### Actual behaviour

The list has grey text on white background.

### Debug info

```text
2.17 alpha 15
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Fixes
* Fixes #15263

## How Has This Been Tested?

Screenshot 2024-01-19 at 18 29 18
Screenshot 2024-01-19 at 18 28 47

Screenshot 2024-01-19 at 21 37 03
Screenshot 2024-01-19 at 21 36 25

<details>
<summary>old</summary>

Screenshot 2024-01-19 at 18 28 28
Screenshot 2024-01-19 at 18 28 01

</details>

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by BrayanDSO — APPROVED** [review]

**Review by BrayanDSO — COMMENTED** [review]
Actually, can the dark themes' dialog have some constrast like the light ones'?

**Comment by david-allison** [comment]
Darker would seem better than lighter

**Comment by david-allison** [comment]
I preferred lighter so I went with it

Screenshot 2024-01-19 at 21 37 03
Screenshot 2024-01-19 at 21 36 25
Screenshot 2024-01-19 at 21 35 39
Screenshot 2024-01-19 at 21 35 15

**Review by lukstbit — APPROVED** [review]
Looks fine!

**Pull request merged**
