### PR TITLE
[JS API] Setter functions for current card

### PR DESCRIPTION
**Pull request by infinyte7**
## Purpose / Description
There are some addons in Anki which modify values for current card. The most popular one is Auto Ease Factor addon, which calculate ease for cards/notes information then set the ease.

The AnkiDroid JS API already provides almost all information about current card but there is no js api to modify current card's information. So this PR will solve the problem.

## Fixes
Fixes _Link to the issues._

## Approach
Using JavaScript Interface call function defined for `mCurrentCard`. Also modifying the information required JS API to be init i.e developer contract must provided so if any changes in future done, the contract will notify user/developer that to use the current function the JS API must init.

## How Has This Been Tested?
Tested using chrome remote debugging, by calling all function in dev tools.

## Learning (optional, can help others)
https://developer.android.com/reference/android/webkit/JavascriptInterface

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
approved to soon:

> /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java:3625: Error: Field should be named: 'mIsJsApiInit' [NonPublicNonStaticFieldName from com.ichi2.anki.lint]

**Comment by david-allison-1** [comment]
Sounds sensible - probably with a snackbar/similar to note that the call was correct (people will use the previewers to develop the templates)

**Comment by dae** [comment]
> Is AnkiMobile reviewer have variable in `card.js` for this `states.hard.normal.learning.scheduledSecs` and set the values in AnkiMobile?

Search for 'mutate' in reviewer.py - the approach is the same.

**Comment by infinyte7** [comment]
I will close this PR because it will be better to have separate PR when required or requested. This PR will be reference for implementing function for changing values of current card.

**Comment by MagTun** [comment]
I don't understand all the details of the last couple of post, so I just would like to clarify a point: does the fact that this PR is closed means that there won't be a way to reschedule a card via AnkiDroidJS (like a `ankiSetCardDue()`) as indicated [here](https://github.com/ankidroid/Anki-Android/issues/9727)?

**Comment by infinyte7** [comment]
It would implemented in another PR specifically for rescheduling.
After merge of this PR it will be easy to add more API.
https://github.com/ankidroid/Anki-Android/pull/9749

**Pull request closed without merging**
