### PR TITLE
Card Browser: Always show 'Search All'

### LINKED ISSUE #6344: Card Browser: Always show 'Search All'
Recently the "search all decks" button was added when no results are found. In my opinion it would make sense to always show this button, since it make sense that users want to search all decks, even though results were found in the current deck.

Details in
#5234 and #5268

### PR DESCRIPTION
**Pull request by david-allison-1**
## Draft

Realised that "Search All" makes little sense without explaining that a deck was searched.

##  Purpose / Description
Already requested by 2 users since it went into the alpha - seems like a great improvement got even better

## Fixes
Fixes #6344

## Approach
Just refactor the logic and remove the need for `cards == 0`

## How Has This Been Tested?

On my device

## Learning 
Lovely to get feedback from Alpha testers

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
Nope, was wrong, text is "Search all decks", good to go.

**Comment by david-allison-1** [comment]
@Arthur-Milchior Honour of merging is all yours (pending your approval) if Travis goes green

**Comment by Arthur-Milchior** [comment]
My bad, I fear I missed your message in the big list of notification I got. Slightly sorry, even if it's not that important

**Comment by david-allison-1** [comment]
@Arthur-Milchior Don't be! Just felt it'd be a nice welcome into the process.

**Pull request merged**
