### PR TITLE
Issue #4579 solved: add icon will not disappear after the search

### PR DESCRIPTION
**Pull request by bexsadirov**
I just recreate the menu by calling onCreateOptions menu when the searchView is collapsed.

### CODE REVIEW

**Comment by timrae** [comment]
Thank you for the merge request.
I think a little more research is required on this one... According to the API documentation, is the current behavior expected? Or is it a bug and the PR is a workaround?

**Comment by bexsadirov** [comment]
timrae, can you please clear up your question about API documentation?

**Comment by timrae** [comment]
@bexsadirov 
Does `invalidateOptionsMenu()` work?

**Comment by bexsadirov** [comment]
ide warns that invalidateOptionsMenu() can be called only within the same library group

**Comment by timrae** [comment]
I don't understand what you mean by that, but probably you need to call:
`supportInvalidateOptionsMenu()`

**Comment by bexsadirov** [comment]
@timrae 
Yes, supportInvalidateOptionsMenu() works. Should I create another pull request?

**Comment by timrae** [comment]
Thanks for trying that, it's a cleaner way :)
You can just update the current pull request by adding a new commit with the changes and I'll squash it down to a single commit when I merge

**Comment by timrae** [comment]
Thank you!

**Comment by bexsadirov** [comment]
@timrae you are welcome. I'll contribute as much as I can. I think you forgot to close the open issue: https://github.com/ankidroid/Anki-Android/issues/4579

**Comment by timrae** [comment]
Thanks. In the future if you write "fixes #issue_number" in the body of the
text of the PR it will close automatically

**Pull request merged**
