### PR TITLE
NF: introduce a hasSyncAccount method

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This is used already in a few part of the code, so refactoring seems nice.

I thought it was going to help scoped storage, but in fact, not

### CODE REVIEW

**Review by BrayanDSO — CHANGES_REQUESTED** [review]

**Comment by Arthur-Milchior** [comment]
It seems I failed to force push the last version of the commit. My bad.
I wanted to indeed refactor all use together, and the one of SyncStatus too.

**Comment by Arthur-Milchior** [comment]
Okay, now I've seen I can directly uses it. So there was no reason to add an extra function. 
Still, keep this PR open because refactoring is nice. But it becomes very low priority

**Review by BrayanDSO — APPROVED** [review]
LGTM

**Review by mikehardy — APPROVED** [review]
low priority, but, also nice and easy

**Pull request merged**
