### PR TITLE
Added unit tests for AudioRecorder

### PR DESCRIPTION
**Pull request by TheItsyBitsySpider**
## Purpose / Description
Added a few unit tests to cover the functions in AudioRecorder. It should be at 100% coverage now according to the report generated by Android Studio.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Akshay0701** [comment]
Thank you for the contribution @TheItsyBitsySpider 
please add copyright to newly added tests.

**Comment by TheItsyBitsySpider** [comment]
Thank you for the feedback! I added a copyright statement to the test, but in previous commits I made, such as AudioPlayerTest, I forgot to include it. Should I go back and add copyright statements to them as well?

**Comment by mikehardy** [comment]
> Thank you for the feedback! I added a copyright statement to the test, but in previous commits I made, such as AudioPlayerTest, I forgot to include it. Should I go back and add copyright statements to them as well?

@TheItsyBitsySpider yeah - if you know of any missing please add them as a separate PR - that would be great

**Review by mikehardy — APPROVED** [review]
LGTM - thanks!

**Comment by mikehardy** [comment]
Hi there!

If you're already submitted something to OpenCollective for PRs merged in July 2021, you may feel free to ignore this and it will be processed shortly

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for July 2021 submissions

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for this month)

Thanks!

**Pull request merged**
