### PR TITLE
Customizable toolbar buttons

### LINKED ISSUE #3154: Customize which icons are visible in the reviewer action bar
Originally reported on Google Code with ID 2257
```
> Please explain your idea here.
Have buttons whose actions is configured by the user.
Currently this is available for gestures, 
but gestures are not available when using the whiteboard.

One Use case that needs this:
Draw CJK characters with cards that do not fit the screen, as it is the case with cards
that include enough info.
Whiteboard needs to be switched on and off frequently to scroll the cards; for instance
to look at a stroke order diagram or or to look at kanji composites. The button present
in 2.2 has been removed in 2.3 and this has made reviews extremely painful.

see discussion in 
https://groups.google.com/forum/#!topic/anki-android/kCVim4Oq1bk


> Is this feature available on similar apps 
Available for Ankidroid's gestures though the actions currently do not include switching
the whiteboard on and off.

One way to implement this would be dedicated bar, with 4-5 buttons.
It's important that the buttons be always visible and actionable as any additional
click when multiplied by hundreds of reviews becomes a problem


```

Reported by `enrico200165` on 2014-08-28 05:21:38

### PR DESCRIPTION
**Pull request by timrae**
I went ahead and implemented the changes I requested in #4058 by myself.

Could someone please give it a test?

Closes #3154

### CODE REVIEW

**Comment by hssm** [comment]
I tested it on 3 devices (phone, tablet, emulator) and it seems to work well so far.

**Comment by arooooon** [comment]
Good and sorry again for being so lazy, although I intended to comple it. I only program periodically as a hobby.

Anyway, could you please add the option to disable 'Enable whiteboard'? Thats the only menu entry that isn't removable.

**Comment by timrae** [comment]
It's not supposed to be there, as it would be confused with hide whiteboard.

**Comment by arooooon** [comment]
I don't quite understand. What I mean is that I think we should be enable to hide "Enable whiteboard" entry althogether for those of us who don't use whiteboard. Not to put in the toolbar as an icon, no.

**Comment by timrae** [comment]
Hmmm I'm not really comfortable with that as there is no other way to turn it back on. With the other options that are removable that's not the case.

**Pull request merged**
