### PR TITLE
use sentence casing

### LINKED ISSUE #16120: Use sentence casing in some settings
If you go to Settings>>Controls then a few inconsistencies appear in capitalisation. The ones that I could spot are:

1. F in Flag is capitalised when it should be not.
2. W in Toggle Whiteboard is capitalised but other instances of whiteboard in the same screen are not.
3. L is not capitalised in Abort learning when it is in Abort Learning and Sync.

### PR DESCRIPTION
**Pull request by gayatriii0803**
## Purpose / Description
sentence casing

## Fixes
* Fixes #16120 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by lukstbit** [comment]
This is not how this issue should be fixed. In the linked issues there's a comment with more information https://github.com/ankidroid/Anki-Android/issues/16120#issuecomment-2041213568

**Comment by gayatriii0803** [comment]
@lukstbit Will you please guide me how to do this? Because the string is directly used in xml layout so that's why I can't call `toSentenceCase()`

**Comment by lukstbit** [comment]
If you look inside ControlSettingsFragment you can see a method where one of the preferences is set dynamically. Use it as an example.

**Comment by gayatriii0803** [comment]
@lukstbit I don't find any method. Will you please share code snippet?

**Comment by lukstbit** [comment]
https://github.com/ankidroid/Anki-Android/blob/94de856406ea3627302c82c28a7c261a824fcae4/AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt#L45-L49

**Pull request closed without merging**
