### PR TITLE
[Kotlin Migration] TaskListenerWithContext

### PR DESCRIPTION
**Pull request by kilitr**
## Purpose / Description
(At least for me,) the main branch did not compile anymore
```
> Task :AnkiDroid:compileAmazonDebugKotlin FAILED
e: ***\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\dialogs\customstudy\CreateCustomStudySessionListener.kt: (21, 1): Class 'CreateCustomStudySessionListener' is not abstract and does not implement abstract base class member public abstract fun actualOnPreExecute(context: CreateCustomStudySessionListener.Callback?): Unit defined in com.ichi2.async.TaskListenerWithContext
e: ***\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\dialogs\customstudy\CreateCustomStudySessionListener.kt: (28, 5): 'actualOnPreExecute' overrides nothing
e: ***\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\dialogs\customstudy\CreateCustomStudySessionListener.kt: (32, 5): 'actualOnPostExecute' overrides nothing
e: ***\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\export\ExportListener.kt: (27, 10): Class 'ExportListener' is not abstract and does not implement abstract base class member public abstract fun actualOnPreExecute(context: AnkiActivity?): Unit defined in com.ichi2.async.TaskListenerWithContext
e: ***\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\export\ExportListener.kt: (29, 5): 'actualOnPreExecute' overrides nothing
e: ***\Anki-Android\AnkiDroid\src\main\java\com\ichi2\anki\export\ExportListener.kt: (36, 5): 'actualOnPostExecute' overrides nothing

FAILURE: Build failed with an exception.
```

## Fixes
Compilation.

## Approach
I corrected some method signatures in CreateCustomStudySessionListener and ExportListener that had a wrong signature thus resulting in the interface not being implemented.

## How Has This Been Tested?

Before my fix i was not able to compile and run AnkiDroid, after my changes i was able to run AnkiDroid again. No Unit Tests, whatsoever were added.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison** [comment]
The main branch compiles and passes CI: https://github.com/ankidroid/Anki-Android/runs/5479318322?check_suite_focus=true

What does `git rev-parse HEAD` return?

**Comment by kilitr** [comment]
0aa58b7b56d46e54dd0cadd81bd0f6ff091d01e5 on main

**Comment by kilitr** [comment]
as far as i can tell, this issue is already present since these two files were migrated in a98685af4607b235f9bfe992e4832d4021dbf8ba and 9fdba649240b9fc10b34298eab923ebea3e99f40.

However another possible solution would be to specify the non nullable type in both cases:
https://github.com/kilitr/Anki-Android/commit/09bcadd817608d3801b06c0830431c4fe801c09f

**Comment by kilitr** [comment]
That's also what i encountered to be the best solution. I already started working on it.

Might i replace all contents of this PR with the migration of TaskListenerWithContext to Kotlin and additional cleanup stuff?

**Comment by Arthur-Milchior** [comment]
Would you be able to tell us the exact commit number you were compiling with. Also which version of java compiler/gradle you have? Maybe we can figure something out.

**Comment by Arthur-Milchior** [comment]
Yes, we usually force push a lot on PR in ankidroid. Never on main branch, but we love to have clean atomic commit history.

I won't work on it if you are already working on it and I'm looking forward to see your code.

**Comment by mikehardy** [comment]
Yeah, as a maintainer the general rule is that the main branch history is *real* history. You never re-write it.
But what is the value of the "history" of how your development branches came to be? That's like saving all the rough drafts and turning in your work with a pile of rough drafts taped to the final product :-). So on the dev branches I probably force push a few times for each branch, even for tiny changes (because there is always a tiny error, no matter how small the change). Then in the end the PR is just the final product, nice and clean

**Comment by kilitr** [comment]
> Would you be able to tell us the exact commit number you were compiling with. Also which version of java compiler/gradle you have? Maybe we can figure something out.

I just wanted to put together a list of error messages and versions... But since I started working on it. I didn't get any compilation error again. It might have been a problem with my cache.

Sorry for the inconvenience. However the state of both `CreateCustomStudySessionListener` and `ExportListener` bugs me and I will use this PR to migrate `TaskListenerWithContext.java` to Kotlin.

**Review by david-allison — CHANGES_REQUESTED** [review]
The first commit breaks the build. 

Please see https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md

(keyword: `kotlinMigration.gradle`)

Please only make two commits in a Kotlin Conversion PR:
* rename
* Absolute minimal to get it to compile
  * Add `@KotlinCleanup("message")` on any issues that you see

This is because we need to rebase the change to keep `git blame`, and need to be sure that all the intermediate commits compile, otherwise this breaks `git bisect`

**Review by david-allison — APPROVED** [review]
If CI is happy, I'm happy

**Comment by david-allison** [comment]
That makes sense!!

Squash with commit 2:

<details><summary>git patch</summary>

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.kt b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.kt	(revision 424c511b52fc41aca500d5586361e392175dde0d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/customstudy/CreateCustomStudySessionListener.kt	(date 1647015126560)
@@ -18,19 +18,19 @@
 import com.ichi2.anki.StudyOptionsFragment.DeckStudyData
 import com.ichi2.async.TaskListenerWithContext
 
-class CreateCustomStudySessionListener(callback: Callback?) : TaskListenerWithContext<CreateCustomStudySessionListener.Callback?, Void?, DeckStudyData?>(callback) {
+class CreateCustomStudySessionListener(callback: Callback?) : TaskListenerWithContext<CreateCustomStudySessionListener.Callback, Void?, DeckStudyData?>(callback) {
     interface Callback {
         fun hideProgressBar()
         fun onCreateCustomStudySession()
         fun showProgressBar()
     }
 
-    override fun actualOnPreExecute(callback: Callback) {
-        callback.showProgressBar()
+    override fun actualOnPreExecute(context: Callback) {
+        context.showProgressBar()
     }
 
-    override fun actualOnPostExecute(callback: Callback, result: DeckStudyData?) {
-        callback.hideProgressBar()
-        callback.onCreateCustomStudySession()
+    override fun actualOnPostExecute(context: Callback, result: DeckStudyData?) {
+        context.hideProgressBar()
+        context.onCreateCustomStudySession()
     }
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/export/ExportListener.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportListener.kt b/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportListener.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportListener.kt	(revision 424c511b52fc41aca500d5586361e392175dde0d)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportListener.kt	(date 1647015126560)
@@ -24,16 +24,16 @@
 import com.ichi2.themes.StyledProgressDialog
 import timber.log.Timber
 
-internal class ExportListener(activity: AnkiActivity?, private val dialogsFactory: ExportDialogsFactory) : TaskListenerWithContext<AnkiActivity?, Void?, Pair<Boolean?, String?>?>(activity) {
+internal class ExportListener(activity: AnkiActivity?, private val dialogsFactory: ExportDialogsFactory) : TaskListenerWithContext<AnkiActivity, Void?, Pair<Boolean?, String?>?>(activity) {
     private var mProgressDialog: MaterialDialog? = null
-    override fun actualOnPreExecute(activity: AnkiActivity) {
+    override fun actualOnPreExecute(context: AnkiActivity) {
         mProgressDialog = StyledProgressDialog.show(
-            activity, "",
-            activity.resources.getString(R.string.export_in_progress), false
+            context, "",
+            context.resources.getString(R.string.export_in_progress), false
         )
     }
 
-    override fun actualOnPostExecute(activity: AnkiActivity, result: Pair<Boolean?, String?>?) {
+    override fun actualOnPostExecute(context: AnkiActivity, result: Pair<Boolean?, String?>?) {
         if (mProgressDialog != null && mProgressDialog!!.isShowing) {
             mProgressDialog!!.dismiss()
         }
@@ -45,15 +45,15 @@
         // instead of a successful result.
         if (result.first == true && result.second != null) {
             Timber.w("Export Failed: %s", result.second)
-            activity.showSimpleMessageDialog(result.second)
+            context.showSimpleMessageDialog(result.second)
         } else {
             Timber.i("Export successful")
             val exportPath = result.second
             if (exportPath != null) {
                 val dialog = dialogsFactory.newExportCompleteDialog().withArguments(exportPath)
-                activity.showAsyncDialogFragment(dialog)
+                context.showAsyncDialogFragment(dialog)
             } else {
-                showThemedToast(activity, activity.resources.getString(R.string.export_unsuccessful), true)
+                showThemedToast(context, context.resources.getString(R.string.export_unsuccessful), true)
             }
         }
     }
Index: AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.kt b/AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.kt
--- a/AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.kt	(revision 424c511b52fc41aca500d5586361e392175dde0d)
+++ b/AnkiDroid/src/main/java/com/ichi2/async/TaskListenerWithContext.kt	(date 1647015076239)
@@ -19,7 +19,7 @@
 
 /** Similar to task listener, but if the context disappear, no action are executed.
  * We ensure that the context can't disappear during the execution of the methods. */
-abstract class TaskListenerWithContext<CTX, Progress, Result> protected constructor(context: CTX) : TaskListener<Progress, Result>() {
+abstract class TaskListenerWithContext<CTX, Progress, Result> protected constructor(context: CTX?) : TaskListener<Progress, Result>() {
     private val mContext: WeakReference<CTX>
     override fun onPreExecute() {
         val context = mContext.get()
```

</details>

**Review by mikehardy — APPROVED** [review]
looks good to me, just passed local testing as well

**Pull request merged**
