### PR TITLE
[GSoC] refactor: Migrate preferences formatted summaries configuration to the XMLs

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description
It's better to keep the UI configuration as much as possible on the XMLs, so this is a step toward this goal.

## Approach
On the commits

## How Has This Been Tested?

Ran the app and saw if everything was the same way as before

## Learning (optional, can help others)
For some unknown reason (I've discovered by chance), getAttributeResourceValue only works for the custom namespace if "http://schemas.android.com/apk/res-auto" is set as namespace too.

Actually we should declare attributes on `attrs.xml` and get rid of the custom namespace everywhere. But I'm not doing this today (nor in the near future, as this envolves fixing DeckOptions and FilteredDeckOptions's prefs too)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
Much nicer

**Comment by david-allison** [comment]
> Actually we should declare attributes on attrs.xml and get rid of the custom namespace everywhere. But I'm not doing this today (nor in the near future, as this envolves fixing DeckOptions and FilteredDeckOptions's prefs too)

Could you extract this to an issue if you want to take it on?

**Comment by BrayanDSO** [comment]
>Could you extract this to an issue if you want to take it on?

Sure. I'll get rid of the namespace for the AndroidX preferences next. It isn't hard and should be useful when DeckOptions/FilteredDeckOptions are migrated to AndroidX as well

**Review by lukstbit — APPROVED** [review]
Ok.

Are you sure the `res-auto` namespace is needed? I just deleted the line `xmlns:app1="http://schemas.android.com/apk/res-auto"` from `preferences_accessibility.xml` and `preferences_advanced_statistics.xml`, ran the app and the corresponding summaries are updated just fine.

**Comment by BrayanDSO** [comment]
> Are you sure the res-auto namespace is needed?

Definetely not. But just happened here. 

Anyway I'll remove the custom namespace on a next PR and use `res-auto` by default, so shouldn't be a problem.

**Pull request merged**
