### PR TITLE
Fix crash with bad filenames when detecting video

### PR DESCRIPTION
**Pull request by timrae**

### CODE REVIEW

**Comment by timrae** [comment]
@ospalh
Thanks for your suggestions, I found a new fix which looks a lot less hacky

**Comment by timrae** [comment]
@ospalh
I pushed another new commit

re: the utf-8 issue, I don't think there's a way to specify the encodings in the files themselves, AFAIK you have to do it [in the IntelliJ settings](http://blog.jetbrains.com/idea/2013/03/use-the-utf-8-luke-file-encodings-in-intellij-idea/). I don't really have time to look into this, but you're welcome to!

Any objections to merging this in the meantime?

**Comment by ospalh** [comment]
Firing up my Lolipop emulator takes time.
Have you tried it with a webm video? Are you sure it is not reported as `application/webm`? Because those can be audio or video.

**Comment by timrae** [comment]
> Have you tried it with a webm video?

Yes I checked all the officially supported video extensions, if you could double check that would be great though.

> those can be audio or video.

As can mp4, 3gp, etc

**Comment by ospalh** [comment]
Hmm. I’m not really happy.

My Lolipop emulator is just too slow, i gave up on that one.

But my KitKat devices  (Samsung 4.4.2 + CM 4.4.4) can play webm videos (I tried [this sample](http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5), but `getMimeTypeFromExtension("webm")` returns `null`.

**Comment by ospalh** [comment]
Oh, btw, forgot to say it, but thanks for fixing the crash.
So this is better than my version, but maybe we could keep a list after all.

**Comment by timrae** [comment]
Ah that's a shame, `MimeTypeMap.getSingleton().getMimeTypeFromExtension("webm")` returns `video/webm` on lollipop. I take it the other extensions work OK since you didn't complain about them?

**Comment by ospalh** [comment]
* mp4: OK, video/mp4 and it plays
* 3gp: OK, video/3gpp  and it plays
* ogv: OK, null and my KitKat can’t play it

But one more:

* flv: not OK, null, but plays as video

**Comment by timrae** [comment]
Does the UrlConnection method pickup flv?

**Comment by timrae** [comment]
f*ck it, can't be bothered anymore. I added flv to the whitelist

**Comment by timrae** [comment]
Could you please quickly confirm that everything is working now?

**Comment by ospalh** [comment]
I haven’t tested that, but i think the docs said both commands use the same database.

**Comment by ospalh** [comment]
Thanks. They all (-ogv) play now. :shipit: , or rather, :+1:  pull it.

(And my ISP seems to suffer from the heat here. The internet is a bit wonky.)

**Pull request merged**
