### PR TITLE
Fixed Undo Options after Custom Study

### LINKED ISSUE #16390: [BUG]: Using Custom Study Disables Undo Option
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Do a card
2. Use Increase New card limit from custom study
3. Press undo from the overflow menu or from the review screen

### Expected behaviour

undo works and undo option appears/undo doesn't work and undo option doesn't appear

### Actual behaviour

undo option appears in the overflow menu but clicking it shows "Nothing to undo"

### Debug info

```text
AnkiDroid Version = 2.18.0 (464cf290cc77c3f2c562cb03b408b78a13be261b)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.123 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by soCallmeAdityaKumar**
## Purpose / Description
After Custom Study the undo shows and after undo toast show for nothing to undo

## Fixes
- Fixes #16390

## How Has This Been Tested?

https://github.com/ankidroid/Anki-Android/assets/101629190/279b2268-d599-409d-b2c8-015ad0ae6cdd

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
This feels too complicated. Can you store `undoAvailable` in `OptionsMenuState` instead?

**Comment by soCallmeAdityaKumar** [comment]
> This feels too complicated. Can you store `undoAvailable` in `OptionsMenuState` instead?

done

**Review by david-allison — APPROVED** [review]
Looks great, cheers!

**Review by mikehardy — APPROVED** [review]
LGTM - thanks!

**Comment by mikehardy** [comment]
@soCallmeAdityaKumar I edited the description so it says:

```markdown
# Fixes
  - Fixes #16390
```

This allows github to cross-link things and auto-close issues that are fixed by PRs

@david-allison what do you think about cherry-picking this to release-2.18? Seems pretty self-contained if it picks cleanly, and was logged against 2.18.0

**Comment by david-allison** [comment]
Sure!

**Comment by mikehardy** [comment]
I rebased to main and squashed the two commits since there is no reason to have 2 commits for this PR
Adding to merge queue now that commit history is clean

**Pull request merged**
