### PR TITLE
TODO use snackbar instead of toast in deck dialogs

### PR DESCRIPTION
**Pull request by criticalAY**
## Pull Request template
replaced toast with snackbar

## Purpose / Description
https://github.com/ankidroid/Anki-Android/pull/12139#issuecomment-1224963182

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
Tested on google emulator 
1. Create a new deck on successful creation a snackbar will be shown stating deck created
2. Rename a deck and an appropriate snackbar is shown
3. Same for an invalid deckname

https://user-images.githubusercontent.com/48384865/206859602-ad0b28b5-7574-4ed6-8f97-1a3c4e06b259.mp4

Debug : 
AnkiDroid Version = 2.16alpha91

Android Version = 9

Manufacturer = Google

Model = AOSP on IA Emulator

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 9; AOSP on IA Emulator Build/PSR1.180720.122; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36

ACRA UUID = b882cb1c-9ebb-459b-9ca7-b58c481a9565

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by criticalAY** [comment]
Should we add a "UNDO" option too as a TODO ?

**Comment by BrayanDSO** [comment]
The TODO involved some issues commented at https://github.com/ankidroid/Anki-Android/pull/12139#issuecomment-1224986747 and this PR doesn't seem to answer any of the concerns on the comment.

Plus, you haven't filled the `How Has This Been Tested?` section on the PR, which unfortunately is becoming a frequent behavior on your PRs.

**Comment by criticalAY** [comment]
My apologies will strictly keep that in my mind. There was a comment station to replace the content with activity but we can also do the snackbar by passing the context as Activity?

**Comment by criticalAY** [comment]
My apologies will strictly keep that in my mind. There was a comment station to replace the content with activity but we can also do the snackbar by passing the context as Activity?

Edit : misread will look into it

**Comment by criticalAY** [comment]
Brayan I have updated the tests. Also would like to know should I change the param?

**Comment by criticalAY** [comment]
https://stackoverflow.com/questions/33263967/is-there-any-way-make-snackbar-persist-among-activity-changes/37707741#37707741 came across this could you go through it once as they are using application context here

**Comment by criticalAY** [comment]
as David mentioned using 'mShownDialog?.ownerActivity?.showSnackbar(R.string.deck_created)' is actually null but if we pass the context as Activity then that's not at the risk of being null and it should work fine with fragments too. no?

**Pull request closed without merging**
