### PR TITLE
NF: CheckResult in libanki and async

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Those where found using
```regexp
(private|protected|public) (?!void|static void).*\(.*\).*\{
```
and looking manually at each class.

I may go over anki at some point, at least over the class i regularly touch

### CODE REVIEW

**Comment by david-allison-1** [comment]
non-void doesn't mean that you should add CheckResult - for example `getCol` is valid to call without it, as it loads the collection

**Comment by Arthur-Milchior** [comment]
I did not add it to all non-void menu. Only to the ones which seems to seems to make no sens to call without using the result.
While you are correct in the sens that it has the side effect of loading the collection, it does not seems that there are places where you want to load the collection and not access it.

**Comment by Arthur-Milchior** [comment]
As an example of places where I did not add `@CheckResult`, there are methods which implements `bool remove()`, or methods creating collectionTasks, since usually we actually do not care about the result. And of courses methods which always return the same result.

**Comment by Arthur-Milchior** [comment]
If I remove `getCol` would you accept it, or is it a general rejection for this ?

I did previous PR removing useless function call that could have been catch thanks to check result. It's not in this PR because it was deleted in its own small PR

**Comment by mikehardy** [comment]
@david-allison-1 - there's a specific question in here for you :arrow_up: 
@Arthur-Milchior this took conflicts but seems better to wait on answer to your original question prior to effort

**Comment by david-allison-1** [comment]
I'm verging on full rejection unless there's a push for why it should go in, I've looked again and it seems to be adding more noise than signal. Most of these methods can be called without checking the result

**Comment by mikehardy** [comment]
Decisive vs non-decisive, as long as there's a shared goal and basis for trust. No then to save time de-conflicting if it doesn't provide DX value

**Pull request closed without merging**
