### PR TITLE
Queue as array

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
There is rarely a good reason to uses LinkedList, except when you want to add or remove elements at specific position often. Otherwise, Queues and Dequeues are more efficient. Actually https://docs.oracle.com/javase/7/docs/api/java/util/ArrayDeque.html suggest using ArrayDeque. This means using an array of Long instead of two object by Long (e.g. the node object and the Long object).

The only case where ArrayDeque is not optimal is for cards in learning mode. Since we want the card with least due date, that's actually the job of priority queue normally

### CODE REVIEW

**Comment by david-allison-1** [comment]
Could you add some perf testing here - Having the `LinkedList` go should intuitively be a win, but it's vital we confirm this, especially as we have a fixed upper bound of elements.

**Comment by Arthur-Milchior** [comment]
Actually quite hard to do. The place where this linked list was used more is loading deck. But this only take time when there is a lot of subdeck and no more card in the first one. It means I'd need to actually review a lot to be able to test it. 
On a new day collection, loading the deck with a lot of subdeck takes 3 seconds, and there is no noticeable difference in both case, but that's to be expected since there is almost nothing to dequee.

One of the big reason for this change is that there is no LongLinkedQueue. And `valueOf` is more noticeable in term of time taken in the profiler. To avoid them, I need to use fastutil, and so to move to library it contains. This goes into https://github.com/ankidroid/Anki-Android/pull/7623

**Comment by mikehardy** [comment]
If I understand:

> One of the big reason for this change is that there is no LongLinkedQueue. And valueOf is more noticeable in term of time taken in the profiler. To avoid them, I need to use fastutil, and so to move to library it contains. This goes into #7623

That's the real reason, a Collection typing thing, enabling other performance items?

**Comment by Arthur-Milchior** [comment]
Right. The goal is not this PR in itself. It's to make #7623 smallest. There is no way to actually do #7623 entirely without first removing the LinkedList.

Of course, it could be argued that doing whole of #7623 at once is not necessary. I just fear that this would require to split this PR in so many distinct PR that it will be even more of a hassle to merge them. And all of those PR's commit are really the same, changing some Collection, List, Map er Set to their fastUtil version. So I could also introduce some PR which does not touch those queues. It seems to me that splitting #7623 will lead to dozens of PR, but that may be for the better

**Comment by Arthur-Milchior** [comment]
Rebased with `./gradlew jacocoTestReport` passing

**Comment by mikehardy** [comment]
Same question as the other type-conversion PR - now that you know more about what type conversion optimizations will result in real savings, does this still have value?

**Comment by Arthur-Milchior** [comment]
This does not seem to change any structure used in a loop, and the queues are usually not really big, unless there is a really huge collection of deck or quite a lot of cards in learning. So it's going to save some space (since it'll be an array of `Long` instead of an extra object by `Long`) and some time, but not anything as significant that I used to hope.

I still believe that, for type clarity using a queue when we want a queue (either FIFO or priority) is better than using a linked list, but that's not a big argument in favor of merging it.

**Comment by mikehardy** [comment]
with apologies I'm going to go with your statement "that's not a strong argument in favor of merging it"
PR review time (and handling inevitable regression etc) should be I think limited to things with strong arguments, or things with strong automated tool support (like lint refactors)

**Pull request closed without merging**
