### PR TITLE
Make TTS pronounce "[...]" in cloze deletions

### LINKED ISSUE #6336: Improve Cloze Deletion TTS output
> [TTS] doesn't read anything out [on a Cloze]. So if I write:
> 
> A few lizards are venomous, eg {{c1::gila monster}}. They have {{c2::grooved teeth}} and {{c2::sublingual venom glands}}.

> On card one it will read out "A few lizards are venomous, eg. They have grooved teeth and sublingual venom glands."

> It doesn't say "blank" "deletion" or even pause for 5 seconds, so it's hard to tell where the deletion was because the sentence just doesn't make sense to listen to. I guess because it's just reading what is visible? Can you change the (...) to read out as "blank" or similar?

User reported on reddit: https://www.reddit.com/r/Anki/comments/gv67qy/option_to_have_anki_read_aloud_the_text_on_my/fsn2v3p/ . Needs verification.

### PR DESCRIPTION
**Pull request by david-allison-1**
## Goals

Ensure the localisation strategy makes sense

## Purpose / Description
Make TTS pronounce "[...]" in cloze deletions

## Fixes
Fixes #6336

## Approach
We now perform a find/replace and it says "blank". This is localisable

## How Has This Been Tested?

Unit tests and on my phone.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/ReadTextTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5626711&bid=18431915)

**Comment by david-allison-1** [comment]
This doesn't handle 

https://github.com/ankidroid/Anki-Android/blob/be587b4553854b1d6c7a07fb5f3693a937de3966/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L2190-L2196

Not sure if this should block it from going in

**Comment by mikehardy** [comment]
Could be handled I guess but if I'm reading that correctly it means that clozes won't be handled gracefully during sample talk while people are selecting a language? If I'm correct on that, I'm not bothered and my approval stands, change if you want though, at least 30-40mins left to make up your mind as CI is chewing through everything :-)

**Comment by david-allison-1** [comment]
Just on the manual language change screen, force pushing a fix now

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/anki/ReadTextTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5626711&bid=18431915)

**Pull request merged**
