### PR TITLE
I have done some modification of the card browser

### PR DESCRIPTION
**Pull request by seniorandre**
1. Added CheckBox in ListView for marking notes by tap
2. Added menu item and operation - Rename Tag
3. Added SingleSelect mode into TagDialog (TYPE_SINGLE_TAG)
4. Added menu item - Clear search filter
5. Added choose new Tag mode with toast on start into TagDialog(TYPE_NEW_NAME_TAG).

### CODE REVIEW

**Comment by hssm** [comment]
I will take a look at this soon.

**Comment by hssm** [comment]
Sorry for the delay on this. Here are my thoughts.

>1. Added CheckBox in ListView for marking notes by tap

Marking/unmarking doesn't happen frequently enough to warrant the extra space it takes up. I don't think it looks very good either.
screenshot_20161011-105232

You can already mark cards by long-tapping a row so this isn't really adding much more value.

>2. Added menu item and operation - Rename Tag
>3. Added SingleSelect mode into TagDialog (TYPE_SINGLE_TAG)
>5. Added choose new Tag mode with toast on start into TagDialog(TYPE_NEW_NAME_TAG).

There might be a use for this, I have nothing against it. Maybe someone else wants to chime in with their opinion but so far I'm okay with adding it. From a quick test, it seems to crash if a tag is only 1 character long. The strings need to be fixed up a bit but we can deal with that later.

>4. Added menu item - Clear search filter

You can already clear the filter with the back arrow that appears when a filter exists. What new functionality does this add? Am I missing something?

--

Sorry but I think only the rename tag portion of this pull request is worth merging.  I will review the PR again once you remove the other parts.

**Comment by timrae** [comment]
If you want to be able to quickly mark multiple cards at once, what you *could do* is to switch to the multi-select view when a user long taps on an item, and from there offer mark/delete/suspend/preview via a contextual action bar. This is what they do in the gmail app and many other apps on Android that require multiple selection in a list view.

There's an open issue for such functionality (#2339) and a PR for this would be highly welcome!

**Comment by seniorandre** [comment]
> Marking/unmarking doesn't happen frequently enough to warrant the extra space it takes up. I don't think it looks very good either.
If I want to sort cards by tags, without this option, it is hard to do

> You can already clear the filter with the back arrow that appears when a filter exists.
This option is very hard to find. It is not an intuitive interface. Standard operation must exist in the menu and be available via the button.

> what you could do is to switch to the multi-select view when a user long taps on an item.
I think about it. But my gmail has the first column for the multiple-choice also.

**Comment by hssm** [comment]
>If I want to sort cards by tags, without this option, it is hard to do. Card browser is not for frequent use, But sorting cards should be easy.

Sorry, I don't understand what this has to do with sorting.

>This option is very hard to find. It is not an intuitive interface.

A back arrow in the search box is a [material design pattern](https://material.google.com/patterns/search.html#search-in-app-search). This *is* the standard.

**Comment by timrae** [comment]
>> what you could do is to switch to the multi-select view when a user long taps on an item.

> I think about it. But my gmail has the first column for the multiple-choice also.

Yes, this is true now that I check it again. However with our two column layout, I feel that we don't really have space for the checkbox. In a previous version of gmail you had to long-tap to access multiple selection.

**Comment by timrae** [comment]
It would be great if you could adapt to this to only show the checkboxes on long-click

**Comment by timrae** [comment]
I think this PR can be closed now that we have #4839

**Pull request closed without merging**
