### PR TITLE
Add "copy to clipboard" action for Snackbar shown in AnkiActivity when there's no app to show a url

### LINKED ISSUE #15671: Add "copy to clipboard" action for Snackbar shown in AnkiActivity when there's no app to show a url
Nit: add a to-do to use "copy to clipboard" functionality

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/15649#discussion_r1501721835_

### PR DESCRIPTION
**Pull request by javaman97**
## Fixes
* Fixes  #15671 

## Approach
I added action "copy to clipboard" for Snack bar as per requirement.

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Firstly: could you aim to rebase, rather than introduce merge commits into the history

We have a snackbar library which would be much better to use:

```kotlin
            showSnackbar(R.string.no_browser_notification) {
                setAction(android.R.string.copyUrl) {
                    copyToClipboard(url.toString(), failureMessageId = R.string.something_wrong)
                }
            }
```

**Comment by javaman97** [comment]
> Firstly: could you aim to rebase, rather than introduce merge commits into the history. This would include dropping the additional commits which are in this PR
> 
> In future: `pull` main, then make a new branch from it
> 
> We have a snackbar library which would be much better to use:
> 
> ```kotlin
>             showSnackbar(R.string.no_browser_notification) {
>                 setAction(android.R.string.copyUrl) {
>                     copyToClipboard(url.toString(), failureMessageId = R.string.something_wrong)
>                 }
>             }
> ```
> 
> Additionally: we always use `R.string` rather than hardcoding strings, to allow our translators to do their thing There was also a lint error which this introduced, which explained that `showSnackbar` should be used, could you check these errors in future before committing


Alright, I will keep those points in mind while commiting and making a PR

**Comment by criticalAY** [comment]
This PR seems to be of no use since OP created a new one #15693

**Comment by david-allison** [comment]
> > Firstly: could you aim to rebase, rather than introduce merge commits into the history. This would include dropping the additional commits which are in this PR
> > In future: `pull` main, then make a new branch from it
> > We have a snackbar library which would be much better to use:
> > ```kotlin
> >             showSnackbar(R.string.no_browser_notification) {
> >                 setAction(android.R.string.copyUrl) {
> >                     copyToClipboard(url.toString(), failureMessageId = R.string.something_wrong)
> >                 }
> >             }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Additionally: we always use `R.string` rather than hardcoding strings, to allow our translators to do their thing There was also a lint error which this introduced, which explained that `showSnackbar` should be used, could you check these errors in future before committing
> 
> Alright, I will keep those points in mind while commiting and making a PR

Please rebase and force push next time, making a new PR loses out on the history

**Pull request closed without merging**
