### PR TITLE
feature #6726: make app resizable on Android desktops

### LINKED ISSUE #6726: Make AnkiDroid resizable
###### Reproduction Steps

1. Open AnkiDroid
2. Try to resize the window

###### Expected Result

It is resizing.

###### Actual Result

It is not.

###### Debug info

**AnkiDroid Version:** `2.11.3`
**Android Version:** `10`
**ACRA UUID:** `188bad92-bf7f-47f6-9171-0988a58670a3`

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### More details

I'm using [Samsung DeX](https://www.samsung.com/us/explore/dex/), which gives a desktop like experience and makes use of Android windowing support.

[Samsung has documentation on how to enable window resizing](https://developer.samsung.com/samsung-dex/modify-optimizing.html):

```xml
<application
    android:resizeableActivity="true">
</application>
```

This documentation also has more tweaks and information on how to improve the desktop experience in case you're interested.
They also have [an app testing guide](https://developer.samsung.com/samsung-dex/testing.html) (although some apps are fine with this guide but won't work on "real" DeX sometimes).

At the moment the resizing button is greyed out and AnkiDroid is always nearly squarish:

Screenshot of AnkiDroid on Samsung DeX

**PS:** I know that it is possible to _force_ all apps to be resizable via `Samsung Labs` > `Force Resize` but it would obviously better to make the application natively resizable to create less friction.

### PR DESCRIPTION
**Pull request by alexanderadam**
https://github.com/ankidroid/Anki-Android/issues/6726

## Purpose / Description

This PR should fix #6726

## Fixes
Fixes [6726](https://github.com/ankidroid/Anki-Android/issues/6726)

## Approach

Adding an attribute to the manifest

## How Has This Been Tested?

I've build it and tested it on Samsung Galaxy Tab S6 with Samsung Dex

## Learning (optional, can help others)

Adding an attribute makes life easier for users

* https://developer.samsung.com/samsung-dex/modify-optimizing.html

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] Strings resources: All strings added as resources are unique or contain a comment for seemingly duplicate strings to explain the difference between both resources

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
I just re-read the related issue and I don't see why not to allow it. It may have lifecycle / activity restart issues but even those are getting fewer I think, and it is one of those features for users where if it breaks, don't do that ;-). But if it works, it's a new feature they didn't have before

**Comment by alexanderadam** [comment]
> It may have lifecycle / activity restart

I forgot to mention: I tested my build and experienced nothing weird (no activity restarts or whatsoever)

**Comment by mikehardy** [comment]
That's great news! It is something we have been grinding away on while refactoring / adding features internally - slowly cleaning things up so that if an Activity restarts (due to any config / size / rotation / whatever change) it will work seemlessly. I'm sure there are still problems but should not be so many

**Comment by mikehardy** [comment]
just got back from vacation and saw this was still pending -> merged!

**Comment by mikehardy** [comment]
Hello! with the 2.14 release we started accepting donations with the stated goal of accepting money from users to support maintenance and development of AnkiDroid

This PR was included in 2.14, and if you'd like to submit an expense to share in a portion of our hopefully-sustainable monthly disbursement, please read here and do so in the next couple of days:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process

This is our first time handling donations and attempting to compensate anyone with these processes, so please be flexible and patient with us

Thank you for your contribution to AnkiDroid!

**Pull request merged**
