### PR TITLE
Use ContextCompat

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@timrae Can you take a look at [Travis CI](https://travis-ci.org/ankidroid/Anki-Android/pull_requests) please? I tried several adjustments to get tests passing there - without success though.

**Comment by hssm** [comment]
Travis has been acting up lately. Not entirely sure if it's our fault yet since it usually works after I restart the build once or twice.

**Comment by johnjohndoe** [comment]
Maybe you want to experiment with [cache and timeout settings](http://stackoverflow.com/a/28949723/356895) unrelated to my pull request.

**Comment by hssm** [comment]
Thanks, I'll look into it some day but it's not really a priority at the moment.

**Comment by johnjohndoe** [comment]
I rebase #4116 onto develop now and force push the branch, okay?

**Comment by hssm** [comment]
I don't think you need to, it's mergeable as it is.

**Comment by johnjohndoe** [comment]
No problem. Takes a second. But easier to review the history and debug.

**Pull request merged**
