### PR TITLE
Change DeckDropDownNavigation to Spinner

### PR DESCRIPTION
**Pull request by eginhard**
Change deprecated ActionBarNavigation in DeckDropDown widget to Spinner, also fixing the dropdown menu colors
Fix bug with statistics not always updating when changing deck (deleted too much code in previous commit)
Use EditText bottom line for duplicate warning

### CODE REVIEW

**Comment by timrae** [comment]
I found a crash when switching from Statistics to Browser. This is what I did but it doesn't seem to happen everytime (happened twice so far)

Open Statistics
Scroll to Cards Types tab
Change deck
Open Card Browser


04-11 08:49:47.920: E/AndroidRuntime(2146): FATAL EXCEPTION: main
04-11 08:49:47.920: E/AndroidRuntime(2146): Process: com.ichi2.anki, PID: 2146
04-11 08:49:47.920: E/AndroidRuntime(2146): java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131427417, class android.widget.ListView) with Adapter(class com.ichi2.anki.CardBrowser$MultiColumnListAdapter)]
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.ListView.layoutChildren(ListView.java:1562)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.AbsListView.onLayout(AbsListView.java:2151)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.View.layout(View.java:15671)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.View.layout(View.java:15671)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:907)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.View.layout(View.java:15671)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.View.layout(View.java:15671)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.View.layout(View.java:15671)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.View.layout(View.java:15671)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.View.layout(View.java:15671)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.View.layout(View.java:15671)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.os.Handler.handleCallback(Handler.java:739)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.os.Looper.loop(Looper.java:135)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at android.app.ActivityThread.main(ActivityThread.java:5257)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at java.lang.reflect.Method.invoke(Native Method)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
04-11 08:49:47.920: E/AndroidRuntime(2146): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
04-11 08:49:47.920: D/DeckTask(2146): Waiting for 37 to finish before starting 30
04-11 08:49:47.920: E/DeckTask(2146): previously running task was cancelled: 37
04-11 08:49:47.920: E/DeckTask(2146): java.util.concurrent.CancellationException
04-11 08:49:47.920: E/DeckTask(2146): 	at java.util.concurrent.FutureTask.report(FutureTask.java:92)
04-11 08:49:47.920: E/DeckTask(2146): 	at java.util.concurrent.FutureTask.get(FutureTask.java:163)
04-11 08:49:47.920: E/DeckTask(2146): 	at android.os.AsyncTask.get(AsyncTask.java:487)
04-11 08:49:47.920: E/DeckTask(2146): 	at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:229)
04-11 08:49:47.920: E/DeckTask(2146): 	at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:74)
04-11 08:49:47.920: E/DeckTask(2146): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
04-11 08:49:47.920: E/DeckTask(2146): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-11 08:49:47.920: E/DeckTask(2146): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-11 08:49:47.920: E/DeckTask(2146): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-11 08:49:47.920: E/DeckTask(2146): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-11 08:49:47.920: E/DeckTask(2146): 	at java.lang.Thread.run(Thread.java:818)

**Comment by timrae** [comment]
Is it necessary to include `spinner_triangle`? I.e. can't we get it from the SDK or appcompat? If it's necessary I think we should include all the resolutions

**Comment by timrae** [comment]
I just added a progress bar to the toolbar, could you rebase please?

**Comment by timrae** [comment]
I'm looking into the crash now, it's a multi-threading issue

**Comment by timrae** [comment]
I merged this via #813, but you could you please address the spinner png issue at some point?

**Comment by eginhard** [comment]
Thanks! I'll add the others resolutions when I get home tomorrow evening.

I merged this via #813 <https://github.com/ankidroid/Anki-Android/pull/813>,
but you could you please address the spinner png issue at some point?

—
Reply to this email directly or view it on GitHub
<https://github.com/ankidroid/Anki-Android/pull/805#issuecomment-92023624>.

**Pull request closed without merging**
