### PR TITLE
Time

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Fixes: 11541

It is based on all PR I made today to work on time, except for the "Clock" PR. I guess it'll thus won't be merged until the other are. The goal here if you want to review is just to concentrate on last commit.

Essentially, this last commit consists simply in removing all occurrence of Time through the main code, using instead static methods to access Time everywhere, and changing Time at start of tests.

### CODE REVIEW

**Review by david-allison — COMMENTED** [review]
A singleton doesn't mean we can't have the class as a concrete dependency (for example: CollectionHelper and `col`), and I want to push for this approach, especially as it reduces code churn.

Unspecified dependencies are not good for testability.

We get a lot less code churn if `CollectionHelper.getTimeSafe()` returns a singleton, this decouples it from the collection (our goal) and it feels reasonable: reducing the surface area of using the singleton.

We want a large TODO to move this to dependency injection ASAP, but it feels like the best 'feasible' solution to unblocking GSoC while keeping the architecture in a reasonable state.

**Comment by Arthur-Milchior** [comment]
I have two question.
Why do you expect code churn? I was expecting once this change is in, we would not have to deal with time again.
Also, you want the dependency to be injected in what?

**Comment by david-allison** [comment]
> I have two question. Why do you expect code churn? I was expecting once this change is in, we would not have to deal with time again. 

This is code churn. 
Using a singleton without control via a DI framework means that tests aren't able to be run in parallel. I doubt what we have now is the final iteration.

> Also, you want the dependency to be injected in what?

Class constructor, for the most part. Definitely don't do this manually

**Comment by Arthur-Milchior** [comment]
Then I'm lost. We already have Time in many constructors. I thought the goal was to ensure time was not in the state of elements anymore. If it's even in constructor, I clearly didn't get what I had to do here

**Pull request closed without merging**
