### PR TITLE
lint: enable CheckResult & Kotlin Cleanup on `Counts`

### PR DESCRIPTION
**Pull request by david-allison**
Stemmed from a code review where `.count()` was unnecessarily called

Realised that Kotlin didn't check `@CheckResult` by default, and we hadn't enabled the lint

Then did some cleanup on `Counts()`

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM - love those build-time errors vs run time errors

**Comment by mikehardy** [comment]
@david-allison please merge at will my only hesitation was squash or rebase, I would have rebased but was not 100% it was bisectable on all commits. I think it is but thought if I have a doubt, defer to author

**Comment by david-allison** [comment]
Bisectable

**Comment by mikehardy** [comment]
Just to keep things spicy, this interacted with the material dialogs PR and there's a brief commit stretch where this lint will fail :sweat_smile:

**Pull request merged**
