### PR TITLE
Bump API to 1.1.0

### PR DESCRIPTION
**Pull request by Rapptz**
## Purpose / Description

Bump the gradle version for the API package.

## How Has This Been Tested?

It's been untested (sorry). However this *shouldn't* break anything. The release machinery is what needs actual testing and I'm not capable of testing that :)

Hopefully it all works out.

## Checklist

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
    - Sorry, the github editor added an extra newline but it shouldn't be catastrophic.
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
A thing of beauty :-)

**Comment by mikehardy** [comment]
only marking this "pending merge" because I want to attempt release right after I merge and I'm caught up in some other repos at the moment, will have to get this next time I have a chance

**Comment by mikehardy** [comment]
The API library does not seem to have publishing to maven central setup

I have locally integrated the API version bump and cleaned things up so a local publish works, but I will need to log a separate issue to track down auto-publishing. I have used mavenCentral before and it is kind of a pain, it might be better to use jitpack

Jitpack already has a test release of this up I think?

implementation 'com.github.ankidroid.Anki-Android:api-v1.1.0' ?

https://jitpack.io/com/github/ankidroid/Anki-Android/api-v1.1.0/
Need some work I think though, following docs here: https://jitpack.io/docs/BUILDING/

A test integration to the apisample should show whether it is working or not

**Comment by Rapptz** [comment]
Thanks for the merge!

I've used jitpack before with no issues so I'll be sure to give it a try.

**Comment by mikehardy** [comment]
Just a friendly notice (one per person, regardless of PR quantity) that we try to process OpenCollective payments monthly - it's time for Dec 2020 submissions

Process note:

    At the end of the month, go to our OpenCollective expense form and follow their process to file an expense.
    As this process is new, we have little information on how many people will submit expenses, so we don't know what the total will be. As mentioned in "sustainable" above, we are trying to distribute about 10% of the total balance each month but we are just guessing right now. Please limit your expense to a maximum of 30 hours claimed working on AnkiDroid, and I believe we can support 10USD/hour for those hours, making a maximum expense claim of 300USD. Please include your GitHub or Discord name in the notes so we may verify your contribution.
    We will look at all the expenses and approve all the reasonable ones or work with you to adjust them, at which point OpenCollective (the company) indicates they do transfers twice a week.
    We may - if the total looks much above or below 10% of our total balance goal - reject all of the expenses with specific instructions to raise or lower the amount of hours you may claim to better match our goal.

**Pull request merged**
