### PR TITLE
Resolved weak warnings: converted objects into data objects

### PR DESCRIPTION
**Pull request by magicteo**
## Purpose / Description
Resolved weak warnings: converted objects into data objects

## Fixes
Related to #13282 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
Looks good to me, thanks!!

----

(learning, no action needed):

There are more commits here than necessary

Screenshot 2023-11-19 at 18 26 56

for future: 
* If you're making a new change, start from `main` and branch off, so you don't pick up commits from other branches
* If you do have commits you don't want, prefer to `drop` + `force push` rather than adding additional commits to the history
  * This is an easy case of `git rebase` to use and get familiar with 

Screenshot 2023-11-19 at 18 31 41

Screenshot 2023-11-19 at 18 32 48

**Comment by magicteo** [comment]
thanks @david-allison 
I'll follow your tips for the next PR!

**Review by Prince-kushwaha — COMMENTED** [review]
I think it is better to Squash Commits.

**Comment by magicteo** [comment]
@Prince-kushwaha Yes I know, they already pointed out the mistake in the comment above. For the next PR I'll avoid unnecessary commits. For this PR, I think we can merge since the squash would be automatic with the merge.

**Review by lukstbit — APPROVED** [review]
Thanks!

**Pull request merged**
