### PR TITLE
NF:Create an enum for note editor caller

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This also shows that `RESULT_UPDATED_IO_NOTE` is a distinct kind of value

I was looking at code nearby and found this to be nicer to read

### CODE REVIEW

**Comment by david-allison** [comment]
Will this combine well with `OpenNoteEditorDestination` introduced in:

* https://github.com/ankidroid/Anki-Android/pull/16597/files#diff-6d9f7ea7bba9cc72513b5078633cee9bdbbd1ea7646114869679f302ad607459R2509-R2604

**Comment by Arthur-Milchior** [comment]
The second one to be merged will get a merge conflict, I fear. 
Using `bundleOf` I admit we can't use the helper method anymore. So either we'd need to make `EXTRA_CALLER` public, or use 
```
bundleOf( 
             EXTRA_IMG_OCCLUSION to imageUri 
         ).apply {bundle -> 
  CALLER_IMG_OCCLUSION.putInBundle(bundle)
}
```

By the way, `EXTRA_CALLER` is usually used in intents, not in bundles. We usually use "caller" for bundles right now, while `EXTRA_CALLER` is defined as `"CALLER"`.
But that should be acomment for the other PR

**Comment by david-allison** [comment]
We should still be able to use `bundleOf`.

`to` creates a `Pair<A, B>`: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/to.html

As long as we introduce a method which creates a pair, we can use it within `bundleOf`

**Review by david-allison — CHANGES_REQUESTED** [review]
Continuing to use `.putExtra` would be much cleaner:

```patch
Subject: [PATCH] aa
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt	(date 1719923254491)
@@ -41,6 +41,7 @@
 import com.ichi2.anim.ActivityTransitionAnimation.Direction
 import com.ichi2.anki.CollectionManager.TR
 import com.ichi2.anki.CollectionManager.withCol
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.anki.browser.CardBrowserColumn
 import com.ichi2.anki.browser.CardBrowserColumn.Companion.COLUMN1_KEYS
 import com.ichi2.anki.browser.CardBrowserColumn.Companion.COLUMN2_KEYS
@@ -2181,7 +2182,7 @@
         @VisibleForTesting
         fun createAddNoteIntent(context: Context, viewModel: CardBrowserViewModel): Intent {
             val intent = Intent(context, NoteEditor::class.java)
-            NoteEditorCaller.CALLER_CARDBROWSER_ADD.putAsExtra(intent)
+            intent.putExtra(NoteEditorCaller.CALLER_CARDBROWSER_ADD)
             if (viewModel.lastDeckId?.let { id -> id > 0 } == true) {
                 intent.putExtra(NoteEditor.EXTRA_DID, viewModel.lastDeckId)
             }
Index: AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt	(date 1719923254499)
@@ -86,6 +86,7 @@
 import com.ichi2.anki.NoteEditorCaller.CALLER_PREVIEWER_EDIT
 import com.ichi2.anki.NoteEditorCaller.CALLER_REVIEWER_ADD
 import com.ichi2.anki.NoteEditorCaller.CALLER_STUDYOPTIONS
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.anki.bottomsheet.ImageOcclusionBottomSheetFragment
 import com.ichi2.anki.dialogs.ConfirmationDialog
 import com.ichi2.anki.dialogs.DeckSelectionDialog.DeckSelectionListener
@@ -195,9 +196,6 @@
         bundle.putInt(BUNDLE_KEY, ordinal)
     }
 
-    fun putAsExtra(intent: Intent) =
-        intent.putExtra(EXTRA_CALLER, ordinal)
-
     companion object {
         fun getFromBundle(bundle: Bundle) =
             entries[bundle.getInt(BUNDLE_KEY)]
@@ -205,6 +203,9 @@
         fun getFromExtra(intent: Intent) =
             entries[intent.getIntExtra(EXTRA_CALLER, CALLER_NO_CALLER.ordinal)]
 
+        fun Intent.putExtra(caller: NoteEditorCaller) =
+            putExtra(EXTRA_CALLER, caller.ordinal)
+
         private const val BUNDLE_KEY = "caller"
         private const val EXTRA_CALLER = "CALLER"
     }
@@ -482,7 +483,7 @@
         } else {
             if (intentLaunchedWithImage(intent)) {
                 Timber.i("Intent contained an image")
-                CALLER_ADD_IMAGE.putAsExtra(intent)
+                intent.putExtra(CALLER_ADD_IMAGE)
             }
             caller = NoteEditorCaller.getFromExtra(intent)
             if (caller == CALLER_NO_CALLER) {
@@ -625,7 +626,6 @@
             CALLER_IMG_OCCLUSION, CALLER_ADD_IMAGE -> {
                 addNote = true
             }
-            else -> {}
         }
 
         if (addNote) {
@@ -1386,7 +1386,7 @@
 
     private fun openNewNoteEditor(intentEnricher: Consumer<Intent>) {
         val intent = Intent(this@NoteEditor, NoteEditor::class.java)
-        CALLER_NOTEEDITOR.putAsExtra(intent)
+        intent.putExtra(CALLER_NOTEEDITOR)
         intent.putExtra(EXTRA_DID, deckId)
         // mutate event with additional properties
         intentEnricher.accept(intent)
Index: AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt b/AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt
--- a/AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/main/java/com/ichi2/widget/AddNoteWidget.kt	(date 1719922967157)
@@ -23,6 +23,8 @@
 import com.ichi2.anki.IntentHandler
 import com.ichi2.anki.NoteEditor
 import com.ichi2.anki.NoteEditorCaller
+import com.ichi2.anki.NoteEditorCaller.CALLER_DECKPICKER
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.anki.R
 import com.ichi2.anki.analytics.UsageAnalytics
 import timber.log.Timber
@@ -65,7 +67,7 @@
         ) {
             val remoteViews = RemoteViews(context.packageName, R.layout.widget_add_note)
             val intent = Intent(context, NoteEditor::class.java)
-            NoteEditorCaller.CALLER_DECKPICKER.putAsExtra(intent)
+            intent.putExtra(CALLER_DECKPICKER)
             val pendingIntent = PendingIntentCompat.getActivity(context, 0, intent, 0, false)
             remoteViews.setOnClickPendingIntent(R.id.widget_add_note_button, pendingIntent)
             appWidgetManager.updateAppWidget(appWidgetIds, remoteViews)
Index: AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt	(date 1719923254505)
@@ -47,6 +47,7 @@
 import com.google.android.material.snackbar.Snackbar
 import com.ichi2.anim.ActivityTransitionAnimation.getInverseTransition
 import com.ichi2.anki.CollectionManager.withCol
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.anki.Whiteboard.Companion.createInstance
 import com.ichi2.anki.Whiteboard.OnPaintColorChangeListener
 import com.ichi2.anki.cardviewer.Gesture
@@ -657,7 +658,7 @@
     fun addNote(fromGesture: Gesture? = null) {
         val intent = Intent(this, NoteEditor::class.java)
         val animation = getAnimationTransitionFromGesture(fromGesture)
-        NoteEditorCaller.CALLER_REVIEWER_ADD.putAsExtra(intent)
+        intent.putExtra(NoteEditorCaller.CALLER_REVIEWER_ADD)
         intent.putExtra(FINISH_ANIMATION_EXTRA, getInverseTransition(animation) as Parcelable)
         addNoteLauncher.launch(intent)
     }
Index: AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt b/AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt
--- a/AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/test/java/com/ichi2/anki/NoteEditorTest.kt	(date 1719923254502)
@@ -27,6 +27,7 @@
 import androidx.test.ext.junit.runners.AndroidJUnit4
 import anki.config.ConfigKey
 import com.ichi2.anim.ActivityTransitionAnimation.Direction.DEFAULT
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.anki.NoteEditorTest.FromScreen.DECK_LIST
 import com.ichi2.anki.NoteEditorTest.FromScreen.REVIEWER
 import com.ichi2.anki.api.AddContentApi.Companion.DEFAULT_DECK_ID
@@ -515,8 +516,8 @@
         ensureCollectionLoadIsSynchronous()
         val i = Intent()
         when (from) {
-            REVIEWER -> NoteEditorCaller.CALLER_REVIEWER_ADD.putAsExtra(i)
-            DECK_LIST -> NoteEditorCaller.CALLER_DECKPICKER.putAsExtra(i)
+            REVIEWER -> i.putExtra(NoteEditorCaller.CALLER_REVIEWER_ADD)
+            DECK_LIST -> i.putExtra(NoteEditorCaller.CALLER_DECKPICKER)
         }
         return super.startActivityNormallyOpenCollectionWithIntent(clazz, i)
     }
@@ -532,7 +533,7 @@
             REVIEWER -> {
                 i = EditCardDestination(n.firstCard().id).toIntent(targetContext, DEFAULT)
             }
-            DECK_LIST -> NoteEditorCaller.CALLER_DECKPICKER.putAsExtra(i)
+            DECK_LIST -> i.putExtra(NoteEditorCaller.CALLER_DECKPICKER)
         }
         return super.startActivityNormallyOpenCollectionWithIntent(clazz, i)
     }
Index: AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionIntentBuilder.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionIntentBuilder.kt b/AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionIntentBuilder.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionIntentBuilder.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/ImageOcclusionIntentBuilder.kt	(date 1719923009085)
@@ -19,6 +19,8 @@
 import android.content.Context
 import android.content.Intent
 import android.net.Uri
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
+
 /**
  * Builder class for creating intents related to image occlusion in the [NoteEditor].
  */
@@ -27,7 +29,7 @@
     fun buildIntent(imageUri: Uri?): Intent {
         return Intent(context, NoteEditor::class.java).apply {
             putExtra(NoteEditor.EXTRA_IMG_OCCLUSION, imageUri)
-            NoteEditorCaller.CALLER_IMG_OCCLUSION.putAsExtra(this)
+            putExtra(NoteEditorCaller.CALLER_IMG_OCCLUSION)
         }
     }
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/EditCardDestination.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/EditCardDestination.kt b/AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/EditCardDestination.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/EditCardDestination.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/noteeditor/EditCardDestination.kt	(date 1719922967153)
@@ -24,6 +24,7 @@
 import com.ichi2.anki.AnkiActivity
 import com.ichi2.anki.NoteEditor
 import com.ichi2.anki.NoteEditorCaller
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.libanki.CardId
 
 /**
@@ -36,7 +37,7 @@
 @CheckResult
 fun EditCardDestination.toIntent(context: Context, animation: ActivityTransitionAnimation.Direction): Intent {
     return Intent(context, NoteEditor::class.java).apply {
-        NoteEditorCaller.CALLER_EDIT.putAsExtra(this)
+        this.putExtra(NoteEditorCaller.CALLER_EDIT)
         putExtra(NoteEditor.EXTRA_CARD_ID, cardId)
         putExtra(AnkiActivity.FINISH_ANIMATION_EXTRA, animation as Parcelable)
     }
Index: AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerHelpers.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerHelpers.kt b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerHelpers.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerHelpers.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/previewer/PreviewerHelpers.kt	(date 1719923254493)
@@ -23,6 +23,7 @@
 import com.ichi2.anki.LanguageUtils
 import com.ichi2.anki.NoteEditor
 import com.ichi2.anki.NoteEditorCaller
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.themes.Themes
 import com.ichi2.utils.toRGBHex
 import org.intellij.lang.annotations.Language
@@ -30,7 +31,7 @@
 class NoteEditorDestination(val cardId: Long) {
     fun toIntent(context: Context): Intent =
         Intent(context, NoteEditor::class.java).apply {
-            NoteEditorCaller.CALLER_PREVIEWER_EDIT.putAsExtra(this)
+            putExtra(NoteEditorCaller.CALLER_PREVIEWER_EDIT)
             putExtra(NoteEditor.EXTRA_EDIT_FROM_CARD_ID, cardId)
         }
 }
Index: AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt b/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/instantnoteeditor/InstantNoteEditorActivity.kt	(date 1719923254508)
@@ -45,6 +45,7 @@
 import com.ichi2.anki.DeckSpinnerSelection
 import com.ichi2.anki.NoteEditor
 import com.ichi2.anki.NoteEditorCaller
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.anki.R
 import com.ichi2.anki.dialogs.DeckSelectionDialog
 import com.ichi2.anki.launchCatchingTask
@@ -160,7 +161,7 @@
     private fun openNoteEditor() {
         val sharedText = intent.getStringExtra(Intent.EXTRA_TEXT)
         val noteEditorIntent = Intent(this, NoteEditor::class.java).apply {
-            NoteEditorCaller.CALLER_INSTANT_NOTE_EDITOR.putAsExtra(this)
+            putExtra(NoteEditorCaller.CALLER_INSTANT_NOTE_EDITOR)
             putExtra(Intent.EXTRA_TEXT, sharedText)
         }
         startActivity(noteEditorIntent)
Index: AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt	(date 1719922993236)
@@ -78,6 +78,7 @@
 import com.ichi2.anki.CollectionManager.withOpenColOrNull
 import com.ichi2.anki.InitialActivity.StartupFailure
 import com.ichi2.anki.InitialActivity.StartupFailure.*
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.anki.StudyOptionsFragment.StudyOptionsListener
 import com.ichi2.anki.analytics.UsageAnalytics
 import com.ichi2.anki.deckpicker.BITMAP_BYTES_PER_PIXEL
@@ -1429,7 +1430,7 @@
 
     fun addNote() {
         val intent = Intent(this@DeckPicker, NoteEditor::class.java)
-        NoteEditorCaller.CALLER_DECKPICKER.putAsExtra(intent)
+        intent.putExtra(CALLER_DECKPICKER)
         startActivity(intent)
     }
 
Index: AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/reviewer/ReviewerFragment.kt	(date 1719923254513)
@@ -42,6 +42,7 @@
 import com.ichi2.anki.Flag
 import com.ichi2.anki.NoteEditor
 import com.ichi2.anki.NoteEditorCaller
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.anki.R
 import com.ichi2.anki.cardviewer.CardMediaPlayer
 import com.ichi2.anki.previewer.CardViewerActivity
@@ -317,7 +318,7 @@
 
     private fun launchAddNote() {
         val intent = Intent(context, NoteEditor::class.java).apply {
-            NoteEditorCaller.CALLER_REVIEWER_ADD.putAsExtra(this)
+            putExtra(NoteEditorCaller.CALLER_REVIEWER_ADD)
         }
         noteEditorLauncher.launch(intent)
     }
Index: AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt b/AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt
--- a/AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/androidTest/java/com/ichi2/anki/NoteEditorTest.kt	(date 1719923254510)
@@ -21,6 +21,7 @@
 import android.os.Build
 import androidx.test.ext.junit.rules.ActivityScenarioRule
 import androidx.test.platform.app.InstrumentationRegistry
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.anki.testutil.GrantStoragePermission
 import com.ichi2.utils.KotlinCleanup
 import org.hamcrest.Matchers.*
@@ -42,7 +43,7 @@
         get() {
             return Intent(targetContext, NoteEditor::class.java).apply {
                 component = ComponentName(targetContext, NoteEditor::class.java)
-                NoteEditorCaller.CALLER_DECKPICKER.putAsExtra(this)
+                putExtra(NoteEditorCaller.CALLER_DECKPICKER)
             }
         }
 
Index: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt	(revision 988eea88c5589df4f1ee5392d780071f537d5462)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt	(date 1719922967160)
@@ -40,6 +40,7 @@
 import androidx.drawerlayout.widget.DrawerLayout
 import com.google.android.material.color.MaterialColors
 import com.google.android.material.navigation.NavigationView
+import com.ichi2.anki.NoteEditorCaller.Companion.putExtra
 import com.ichi2.anki.dialogs.help.HelpDialog
 import com.ichi2.anki.preferences.Preferences
 import com.ichi2.anki.preferences.sharedPrefs
@@ -443,7 +444,7 @@
             val intentAddNote = Intent(context, NoteEditor::class.java)
             intentAddNote.action = Intent.ACTION_VIEW
             intentAddNote.flags = Intent.FLAG_ACTIVITY_CLEAR_TASK
-            NoteEditorCaller.CALLER_DECKPICKER.putAsExtra(intentAddNote)
+            intentAddNote.putExtra(NoteEditorCaller.CALLER_DECKPICKER)
             val noteEditorShortcut = ShortcutInfoCompat.Builder(context, "noteEditorShortcutId")
                 .setShortLabel(context.getString(R.string.menu_add))
                 .setLongLabel(context.getString(R.string.menu_add))
```

**Comment by david-allison** [comment]
Sanjay's done similar work, which got merged

**Pull request closed without merging**
