### PR TITLE
Use <input/> tags for the type answer feature (API ≥ 15 only)

### LINKED ISSUE #3727: Remove "Smart Typing" and "Predictive text" for {{type::NN}} field
I use AnkiDroid for learning English, and use the "Type in the answer feature", but the "Smart Typing" feature of mobile keyboard is a real nuisance because it always displays the right spelling in front of my eyes, so I am wondering is it possible to disable the "Smart Typing" of mobile keyboard for {{type::NN}} field as I see on some other apps.

### PR DESCRIPTION
**Pull request by ospalh**
Use an input tag, that is, let the user type the correct answer into the card itself, when `{{type::field NN}}` is used.
It took me quite a while to make this a PR, because of some problems with input tags on old Android versions. I couldn’t find a work around for those problems, so for older Androids the old input box stays.

I had thought this was more of an aesthetic improvement, but it looks like this fixes an actual problem, at least on my phone (With CyanogenMod 5.1). Without this, when i wanted to type an answer i had either the keyboard *or* the input text box between the card and the answer button on screen, not both:

screenshot_2015-10-13-11-20-22
screenshot_2015-10-13-11-20-42

A bit of a pain.

Here how it looks on Anki desktop: An input box inside the card
gypt_dt

And here with this change:

screenshot_2015-10-13-11-05-37

This works with a few new JavaScript functions. You start out with the card without the keyboard. When you tap the input box, the show answer button is hidden and you get the keyboard. When you tab somewhere else, this is reversed. When you use return while typing the answer is shown.

There are some differences to Anki desktop:
* When you have several `{{type::NN}}` fields, this code uses the text last typed, Anki desktop always uses the text from the first input box. As this setup is explicitly forbidden in the [manual](http://ankisrs.net/docs/manual.html#typinganswers), i think this is OK. Better than [having demons fly out of your nose](http://catb.org/jargon/html/N/nasal-demons.html).
* On the preview screen Anki desktop drops the input box completely. This change shows an input box but ignores the font and font size. (They are a little bit hard to get to.) I guess this could be improved, but is still better than Anki desktop.

Also: with the old version, there *might* have been some way to fix #3727, but i don’t know how to change the behavior of the keyboard in this case.

### CODE REVIEW

**Comment by hssm** [comment]
Thanks, it's looking good. I've given it a quick test and it seems to work well. Code is fine too.

There is an [`autocomplete` attribute](http://www.w3schools.com/tags/att_input_autocomplete.asp) in HTML that you can use to turn off suggestions. Add `autocomplete='off'` to the `<input>` element and you should resolve that issue. If possible, try to also do this for the old approach. I don't think it's too difficult if [this](http://stackoverflow.com/questions/1959576/turn-off-autosuggest-for-edittext) suggestion works.

One very minor problem I've found. If you have the keyboard open and the answer buttons hidden, then tap away to another application and return, you are presented with no keyboard or answer buttons. A tap anywhere brings the buttons back so it's not a big deal but would be nice if you could improve that.

**Comment by hssm** [comment]
Actually the SO link isn't going to help since we already do what it says to do. Not sure why it isn't working already. Hmm...

**Comment by ospalh** [comment]
I did add the `autocomplete="off"`. Thanks for the tip. I guess it can't hurt. May depend on the IM/keyboard you use.

**Comment by ospalh** [comment]
Also, i noticed a problem with the PR:
The compare string is not cleared when a new card is shown.
Should be easy to fix.

**Comment by timrae** [comment]
So this is ready to merge @hssm?

**Pull request merged**
