### PR TITLE
fix: Loading the deck count and toolbar takes more time if internet is enabled

### LINKED ISSUE #14355: [BUG]: Loading the deck count and toolbar takes more time if internet is enabled with the new backend
Haven't tested with the legacy backend, since it will be removed very soon

My guess is that the sync status fetching is happening before the UI update and since `withCol` works with a queue, the UI update will always have to wait for it

2.16.4, new backend enabled, Android 13

### LINKED ISSUE #14828: [BUG]: Crash loop when Anki Web email address needs to be reconfirmed
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Open AnkiDroid and sync (via auto-sync in my case)
2. Get a popup dialog with "Syncing failed, because your email address needs to be (re)confirmed. Please visit ankiweb.net, and log in as *** to proceed". Click on "Ok".
3. The crash report dialog opened, I clicked "Cancel" instead of sending a report.
4. Same dialog as in step 2 opened, I clicked ok, which opened another crash report dialog. I was stuck in a loop of these two dialog without being able to use the app.
5. At some point I sent the crash report (https://ankidroid.org/acra/app/1/bug/100545/report/e93a590d-b9b2-4dff-a294-d6c6ed4d9df1) instead of clicking cancel:
```
net.ankiweb.rsdroid.exceptions.BackendSyncException: Syncing failed, because your email address needs to be (re)confirmed. Please visit ankiweb.net, and log in as *** to proceed.
	at net.ankiweb.rsdroid.BackendException$Companion.fromError(SourceFile:148)
	at net.ankiweb.rsdroid.BackendKt.unpackResult(SourceFile:31)
	at net.ankiweb.rsdroid.BackendKt.access$unpackResult(SourceFile:1)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(SourceFile:2)
	at net.ankiweb.rsdroid.Backend$runMethodRaw$1.invoke(SourceFile:1)
	at net.ankiweb.rsdroid.Backend.withBackend(SourceFile:13)
	at net.ankiweb.rsdroid.Backend.runMethodRaw(SourceFile:16)
	at anki.backend.GeneratedBackend.syncStatusRaw(SourceFile:8)
	at anki.backend.GeneratedBackend.syncStatus(SourceFile:15)
	at com.ichi2.libanki.Collection.syncStatus(SourceFile:8)
	at com.ichi2.utils.SyncStatus$Companion.getSyncStatus(SourceFile:25)
	at com.ichi2.anki.DeckPicker.fetchSyncStatus(SourceFile:7)
	at com.ichi2.anki.DeckPicker.access$fetchSyncStatus(SourceFile:1)
	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(SourceFile:4)
	at com.ichi2.anki.DeckPicker$updateMenuState$2.invoke(SourceFile:1)
	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(SourceFile:3)
	at com.ichi2.anki.CollectionManager$withOpenColOrNull$2.invoke(SourceFile:1)
	at com.ichi2.anki.CollectionManager$withQueue$2.invokeSuspend(SourceFile:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:119)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(SourceFile:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:1)
```
6. I don't remember if sending the report or restarting the app got me out of that loop. Now I still get the initial dialog because I haven't reconfirmed my email yet, but after there is no crash and I can review as usual.

### Expected behaviour

After dismissing the initial dialog, I should be able to use the app as normal.

### Actual behaviour

See above.

### Debug info

```text
AnkiDroid Version = 2.17alpha6 (393f61b229a26ec97eb13c83f0d1f09652f776c2)

Android Version = 14

ProductFlavor = play

Manufacturer = Google

Model = Pixel 7a

Hardware = lynx

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 7a Build/UP1A.231105.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.67 Mobile Safari/537.36

ACRA UUID = 068b9e6f-d246-4c9a-9dad-33a48044990d

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
* #14355 

## Fixes
* Fixes #14355 
* Fixes #14828

## Approach
* remove code from a `withCol` block
* take dae's suggestion and move to `CollectionManager.getBackend().syncStatus(auth)`, understanding that it can throw

## How Has This Been Tested?
Briefly tested on an API 33 emulator

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by dae** [comment]
backend.getSyncStatus() may block, and appears to be called from a synchronous context now - you might need to shift it to an IO context now that it's no longer using withCol?

**Review by mikehardy — APPROVED** [review]
Seems reasonable, going to request review from the Esteemed Mr Elmes

**Comment by david-allison** [comment]
Ah, didn't realise it was blocking, thanks!

**Comment by dae** [comment]
This might also require another backend update, as the mutex on the JVM end that guards transactions is probably being locked: https://github.com/ankidroid/Anki-Android-Backend/blob/e06e512e2357efa7764363fcba14623fa7225ec7/rslib-bridge/proto.rs#L93

**Comment by dae** [comment]
Actually David, I think you can probably cut out the mutex handling code. About 5 months ago I refactored the service handling code, and all DB-related calls now appear to be protected by the internal collection mutex, so there should be no need for one on the JVM side.

**Comment by david-allison** [comment]
I'll get this in later today. Thanks!

**Comment by david-allison** [comment]
blocked on backend `0.1.30-anki23.10.1`

**Comment by mikehardy** [comment]
backend is in, 🚂

**Comment by david-allison** [comment]
🚀🚀. Anything I need to rebase here, or can it go in immediately?

**Comment by mikehardy** [comment]
Oh good point - no, it's a coordinated change but not actually dependent. I think it goes in now...

**Pull request merged**
