### PR TITLE
Add searchbar in CardTemplateEditor

### LINKED ISSUE #10843: Search option in card template editor
**Is your feature request related to a problem? Please describe.**
The search option will be helpful in card template editor to quickly find the known strings.

**Describe the solution you'd like**
Search option in options menu

**Describe alternatives you've considered**
The alternative will be copy the card templates content to different editor and edit there.

**Additional context**
AnkiDesktop has the seach box in card template editor.

### PR DESCRIPTION
**Pull request by dorrin-sot**
## Fixes
Fixes #10843 

## Approach
Added SearchView and "Next" and "Prev" and "Case Sensitive" buttons to toolbar
Added `EditTextSearchbar` class for all search logic (mainly `findNextResult` and `findPrevResult`)

#### For Searching Forward:
1. Search from cursor to end
2. If nothing found, search from start to cursor
3. If nothing found, Search from start to end (for the case of `query` being split by cursor)

#### For Searching Backward:

1. Search from cursor to start
2. If nothing found, search from end to cursor
3. If nothing found search from start to end (for the case of `query` being split by cursor)

## How Has This Been Tested?
- Emulator:

https://user-images.githubusercontent.com/59933477/168368004-c4da7e46-614f-4470-8572-1eaa3ac8644e.mov

- Unit Tests: Will soon add in separate PR

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by dorrin-sot** [comment]
accidentally closed the first pr while trying to rename the branch 😅

**Comment by dorrin-sot** [comment]
@mikehardy @david-allison  Hi sorry could you review this? 👀

**Comment by mikehardy** [comment]
I would like to but I'm neck deep in my "important" and "urgent" quadrant right now, and while I'd like all AnkiDroid items to be treated as important and urgent, on reflection vs contracts etc, they are important but not urgent - https://todoist.com/productivity-methods/eisenhower-matrix#the-eisenhower-matrix-%E2%80%94-urgent-vs-important

responding to pings takes additional time, so please be patient :pray:

**Comment by dorrin-sot** [comment]
> I would like to but I'm neck deep in my "important" and "urgent" quadrant right now, and while I'd like all AnkiDroid items to be treated as important and urgent, on reflection vs contracts etc, they are important but not urgent - https://todoist.com/productivity-methods/eisenhower-matrix#the-eisenhower-matrix-%E2%80%94-urgent-vs-important
> 
> 
> 
> responding to pings takes additional time, so please be patient :pray: 

oh sorry looking forward to then 👀

**Comment by dorrin-sot** [comment]
Hi again sorry to bother are you available to review this feature now? 👀

**Comment by mikehardy** [comment]
@dorrin-sot I'm available for review now, but this took a conflict during the time it sat, apologies :weary:

**Comment by david-allison** [comment]
I'm now available for reviews, please ping me once conflicts are fixed

**Comment by dorrin-sot** [comment]
Apologies I recently moved and I was finally able to get my VPN to work in order to use gradle this morning😭 Will get back to these soon

**Comment by mikehardy** [comment]
Never any rush, hope your move went okay and you enjoy downloading a few gigabytes of software updates and stuff since you were offline a while :laughing:

**Comment by david-allison** [comment]
Please don't apologize, it's great to have you back (and to be back myself)! Please feel free to get in touch via Discord private messages so we can work through merging your queue of PRs

**Comment by mikehardy** [comment]
Certainly not closed with malice - happy to reopen and work with you when/if time permits getting these through

**Pull request closed without merging**
