### PR TITLE
Progress Dialog of NoteEditor Extra Space Remove

### PR DESCRIPTION
**Pull request by imaryandokania**
## Purpose / Description
Solves the bug of extra space

Before:
Screenshot_1615822428

After:
Screenshot_1615946584

## Fixes
"" in progress dialog changed to null
fixes bug ankidroid#8252

## How Has This Been Tested?

Tested on Emulator: Pixel 3a API R

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Hi

I commented on the bug report, Id on't understand what's going on here. In any case, can I please ask you to rebase onto master and squash. It seems most commits here are not actually useful. That means that I had to look at four commits while a single one would have been sufficient. I can always squash when I add it to codebase, so that's not so bad for the history.

**Comment by imaryandokania** [comment]
> Hi
> 
> I commented on the bug report, Id on't understand what's going on here. In any case, can I please ask you to rebase onto master and squash. It seems most commits here are not actually useful. That means that I had to look at four commits while a single one would have been sufficient. I can always squash when I add it to codebase, so that's not so bad for the history.

Actually my old pr is still pending (created from master) and if I try to rebase my master, then that pr will have issues , I had messaged @mikehardy regarding this as well.

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
It'd be a useful learning experience to `rebase` the relevant commit onto the current master branch so we have a single commit and a clean history

We could squash and merge this, and will do if necessary, but learning how to use git to produce a clean commit history is a useful skill to learn. 

Do let us know if it turns out to be a hassle.

**Comment by imaryandokania** [comment]
> It'd be a useful learning experience to `rebase` the relevant commit onto the current master branch so we have a single commit and a clean history
> 
> We could squash and merge this, and will do if necessary, but learning how to use git to produce a clean commit history is a useful skill to learn.
> 
> Do let us know if it turns out to be a hassle.



> It'd be a useful learning experience to `rebase` the relevant commit onto the current master branch so we have a single commit and a clean history
> 
> We could squash and merge this, and will do if necessary, but learning how to use git to produce a clean commit history is a useful skill to learn.
> 
> Do let us know if it turns out to be a hassle.

I am stuck , my old pr is pending for approval and if I rebase those commit will be lost.Can you suggest what shall I do ?

**Comment by david-allison-1** [comment]
You don't have to understand this explanation straight away, but do read it a few times and Google for how it works. I've explained what to do at the end of this message.

Git works a lot like a blockchain, if you've ever looked at the data structure

* Each commit ID is a hash of its contents
* Each commit contains a reference to a `parent` commit, forming a tree of commits
* A branch is a named pointer to a commit
* Changes in one branch won't affect another branch - as branches are just pointers, and you can treat the git data structure as immutable/append only


----

* A Git `rebase` may change the `parent` pointer of a commit. Because the contents of a commit changes, its hash changes. If a commit's `parent` has changed, the content of the child commit has changed, so the hash change flows up through the tree, until you're at a leaf node.
* This means that a `rebase` doesn't modify a commit, it adds one or more commits to git.
* This allows a user to rewrite history, which is very powerful when used on your own private branch, and causes big problems if used on a branch where other people make changes

---

Don't have the free time to go into detail on the `git` command line right now (and I'd need to look it up to make sure I have all the command perfect), I'll explain via the GUI:

* Check out the `tree2` branch
* Inside Android Studio, go to "Git - Log"
* Right click the first commit that you made, and select "Interactively Rebase From Here"
* You'll see a GUI with 4 commits, select "drop" on the 3 that you don't want, and "pick" for the one that you do want
    * This action may produce merge conflicts. I don't believe it will in your case
* Now, you've changed history on your branch, GitHub won't like this and will block a 'git push'. You'll need to perform a "force push (with lease)" to state that changing history was your intention.
    * Force pushes are something that you typically want to be very careful with if you're working in public.
* Go to `VCS - Git - Push` - select "force push" from the drop-down arrow next to "Push"

In future, check out `master`, perform a `git pull`, and then checkout your new branch to make changes. That will save you the need to rebase

But, learning how to fix things if they go wrong in Git is probably more important.

**Pull request closed without merging**
