### PR TITLE
feat: disable Java fallback for Col Backend

### PR DESCRIPTION
**Pull request by david-allison**
We've released 2.15, and Rust appears to be stable!

No point in keeping the Java-only code around

* Repurpose `BackendNotSupportedException`
* Remove `JavaDroidBackend`

Note: Media/Syncing still uses the Framework for SQL

This is caused by "new DB(string)", this has been marked as a candidate for cleanup, but not yet.

## How Has This Been Tested?

Unit tested only - code shouldn't be hit

But... there are some exceptions from loading Rust, we should see if we can solve these before implementing this

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison-1** [comment]
Sadly, there seems to be 3 rare issues in ACRA.

I've had a /very/ quick Google, and https://github.com/facebook/SoLoader was mentioned.

**Comment by mikehardy** [comment]
FWIW soloader is *the* react-native loader for the JSC ("Javascript Core" - or "Hermes" - a separate javascript engine) which is the heart of all react-native applications which you can then further read as "is used by multiple billions of devices successfully"). Which is then to conclude that if it is able to load your native code technically - as in you can get it to work in this use case - then it should be a very very trustworthy piece of code.

**Comment by mikehardy** [comment]
Read more deeply (and I'm looking through the UnsatisfiedLinkError issues) but I don't think soloader will actually solve anything for us, even though it would likely do no harm.

https://github.com/facebook/SoLoader/issues/65

> Relinked and SoLoader are both addressing the issue that pre lollipop versions are not loading so's dependencies before loading the so file. If you are targeting android 5.0 or higher you don't have that issue the bionic linker already does that. Besides that SoLoader has some extra functionality for looking for so files in the apk archive or other directories.

**Comment by mikehardy** [comment]
Okay - the comment above was updated a couple times :point_up: so if you only read it the first time, re-read.

- I think SoLoader (or ReLinker) is unnecessary and red herring, I would not investigate personally anymore
- I would use `readelf` (I think, based on what I just read but have not put in practice yet) to verify the DT_NEEDED and .dynamic headers chunks of the .so products are correct as generated so we know our toolchain is producing valid output and the problem really is a delivery/unpack/load issue on target devices vs something we are doing
- I would add a dialog for users that experience any RustBackendException for UnsatisfiedLinkError to try a restart, then try a reinstall in that order (taking care to make sure they have a collection backup - thinking to future when we do ScopedStorage)
- I would send an exception report as we do now even if we are not fully crashing (because of the dialog) and I would expand our crash report to note disk free/total reporting (example code here if we don't already have some around somewhere https://github.com/react-native-device-info/react-native-device-info/blob/7a87ea18dbe4076f063e08b74dbd42bb2a9c3dac/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L353-L405 - in fact I think we do for collection import / unpack pre-check but this code I just referenced is probably more modern!)
- I mentioned analytics elsewhere - I think we do analytics hits on exception reports but I'm not sure if we do them before or after the ACRALimiter / de-duplication happens - I think it's *after* so we will have incomplete stats. We should add a specific analytics hit for the UnsatisfiedLinkError with extras that specify the flavor of link failure for reporting

I think with some investigating, a little user messaging, and a little stats addition we will have handled this about as thoroughly as possible? Then getting rid of Java collection touches will be the thing to do

**Review by mikehardy — CHANGES_REQUESTED** [review]
thoughts as noted in some really long comments :sweat_smile:

**Comment by mikehardy** [comment]
Nice. I'm okay with the current state of the derivative issues as well

**Pull request closed without merging**
