### PR TITLE
New consistent card previewer UI

### PR DESCRIPTION
**Pull request by unusualstranger**
## Purpose / Description
This pull request unifies UI in all flashcard viewers. Previously previewers had their own UI which had its own disadvantages, such as:
 - there was no proper overlapping of webview with navigation buttons, so if card has custom background, webview bounds become visible which is kind of annoying to look at;
 - navigation buttons had too much shadow;
 - buttons were tall and clumsy.

## Approach
This pull request changes the design of navigation buttons and flip card button, following [Material Design guidelines](https://material.io/design/navigation/understanding-navigation.html).

[Screenshot](https://cdn.discordapp.com/attachments/701922522836369498/748416530689294417/SVID_20200827_123404_1.mp4)

If you like the current UI more, it's fine, you can reject this one. I just wanted to make them more consistent and logical, and as a side effect more intuitive.

## How Has This Been Tested?

SDK 28 Android 9 HUAWEI Honor 9 (STF-AL10). Tests have been modified to reflect the change of flip card button ID.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
I do like this from a consistency perspective. I like the other one purely as design preference.

I think consistency in a UI is more important (sadly), so I think this is worth merging.

But! I state that context on UI priority preference because I had a thought yesterday to solve the tricky open-source UI problem of "how do we overhaul the UI without making everyone used to the old way angry?" problem.

We have worked hard on a Javascript UI so people can replace the reviewer experience entirely. And it basically works now. I think the end state is we create and release a Javascript Reviewer UI replacement called "AnkiDroid Original Reviewer", and then anyone that gets mad gets a pointer to that. Then we can overhaul the buttons and everything on all of them to bring them in to the year 2020

But that is only related to this PR in that I am going to accept and merge it even though the other one looks better, because "consistency" (for now...)

**Comment by infinyte7** [comment]
Okay, I will test it with my js api card template designs.

I am building plug and play features type js script. If user want to add button at bottom then just adding the js file do that things.
Like previous _js_addon_progress_bar.js example.

**Comment by unusualstranger** [comment]
My thoughts on this:

I actually like this UI more for reasons outlined in PR comment and because it's simpler and has less visual density than my first version. I can't think of a better UI for reviewer buttons though, I think it's pretty good already with ripple stuff. But the whole application needs to have some "design refresh", yeah :D

Regarding JavaScript: it would be really nice to have something like React Native view building (I don't know how it's called, basically synthesizing Android views out of React component tree but without React because it's heavy) because it will have advantages from both worlds: customization from JavaScript and native UX. Security is important too though.

@infinyte7 where do buttons get added? in HTML or native Android views?

~~I don't know how you're going to wire up JavaScript and Android framework together without performance issues. I mean, sometimes I play around with React Native and try to max out the performance just for fun (with Reanimated and other fancy stuff) and that's possible and it's proven and used in production by many corps such as Facebook, but for an app that's mostly written in Java with native elements that would be hard to approach. Having HTML UI instead of native one would bring its own set of problems. For example, I'm going through Recognition RTK (Remembering the Kanji) pre-made deck (it's like Lazy Kanji but newer). Card template has four fonts included (grotesque, antiqua, handwritten and stroke order) and for some reason they leak. Yes, on every HTML change from native side all fonts get reloaded, and after 10-15 cards WebView simply crashes. I don't know how you replace card contents on answering (I was planning to go through that code and see if I can do anything to fix it), but if I had JS buttons there, that would be so annoying and bad from UX perspective. Like, my phone is Huawei, and it's not really fast. It's very sluggish, __especially__ in a browser. All things built with web tech feel like they're Web, they're only just mocking native experience, but they can't. Imagine UI that crashes every minute, taking down all your reviewing UI. 

It's not like I'm against JavaScript or something like that, but it needs to be done very carefully IMO. Anki Desktop UI is pretty much all HTML and it works great, mostly because of great choice of Webkit over Blink and having actual logic in Python and Rust rather than JS, so it's fine as long as ~~

**Comment by mikehardy** [comment]
We are planning on having a native Reviewer UI, no question.

A JS replacement would be for those that were dissatisfied with whatever our default choices were, allowing them to satisfy their needs without splitting the default code base 1000 ways, that's a real thing

Right now the card is effectively clobbered, which is why local storage etc is necessary (to survive card flips). The "right way" to do it is I believe a DOM rewrite and re-render, similar to react (or react-native, which is actually what my Day Job(tm) project works with)

**Comment by unusualstranger** [comment]
And what I mean is basically it can't be simpler that four buttons in a row with some text, so if UI is going to be more complicated than that it has to have some good advantages over current design. It's compact, it supports even some ancient 2.7" phones on API 16 I've never seen in my life. But you do you :) That's about these four buttons though, I think reviewer as a whole and the application have some room for UI improvements.

**Pull request merged**
