### PR TITLE
Clean deck adapter and may be fix a crash

### LINKED ISSUE #13794: [2.16beta01 Bug]: IndexOutOfBoundsException on DeckAdapter
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 8(offset:8).state:29 androidx.recyclerview.widget.RecyclerView{b2ffdd6 VFED.V... ......ID 0,0-1440,2673 #7f0901d1 app:id/files}, adapter:com.ichi2.anki.widgets.DeckAdapter@1000a4d, layout:androidx.recyclerview.widget.LinearLayoutManager@ae0eb86, context:com.ichi2.anki.DeckPicker@c21356d
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:382)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:39)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:35)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:7)
	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:40)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:116)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

https://ankidroid.org/acra/app/1/bug/47707/report/3482ece4-f673-4242-9af7-5fdeb6368cf3
Android 13
Samsung phone

@david-allison said on Discord:
> * DeckAdapter issue (I suspect on Samsung phones): https://ankidroid.org/acra/app/1/bug/47707/report/3482ece4-f673-4242-9af7-5fdeb6368cf3
  * Likely a very simple fix, judging from StackOverflow

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Each commit except the last one consist in cleaning part of the code, so that I could understand what it is doing.

Last commit ensure that the deck adapter see all its values updated simultaneously, and just before the adapter is notified, instead of seeing a list cleared long before the notification. 

Hopefully fix #13794 except that I don't know how to reproduce it

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Tests fail

**Comment by oakkitten** [comment]
I said this before and I'll say this again, not using mutable lists is the ✨ **_number 1_** ✨ way of solving recycler view issues. `val items: MutableList<...>` → `var items: List<...>`. (In fact, if you can get away with it, prefer immutable lists at all times. Or immutable ahything.)

**Comment by Arthur-Milchior** [comment]
Given #13815, I'll remove the last commit that was doing change, and only keep the one improving the code

**Comment by lukstbit** [comment]
@Arthur-Milchior After merging David's PR this took some conflicts.

**Review by mikehardy — APPROVED** [review]
This seems fine to me, marked as low priority but I'd merge it with second approval

**Comment by mikehardy** [comment]
rebased to main since it has sat for a while, and re-pushed. It passed `./gradlew jacocoTestReport` locally so I think it is good to go in case it gets second approval any time soon

**Pull request closed without merging**
