### PR TITLE
Don't create backup after restore

### LINKED ISSUE #8897: [Bug] Restoring from an automatic backup shouldn't immediately create a new backup because it causes the oldest to be deleted.
###### Reproduction Steps

1. Find something "not right" in your collection and decide to go through AD's automatic backups
2. Restore from backup
3. AnkiDroid will create a new "backup" as soon as it finishes restoring, and deletes the oldest one
4. Repeat 1-3 atleast 8 more times (unless you've changed the default preference "Max Number of Backups" (under Advanced)
5. Notice that all 8 of your automatic backups are now from today and the thing that was "not right" in your collection has been propogated to all of them

###### Expected Result
Restoring from a backup should not immediately create a new backup. Ideally the AD restore process should follow desktop (as of v. 2.1.43):
1. warn the user they are replacing their current collection with an older backup
2. let them choose a backup
3. confirm with them that `Automatic syncing and backups have been disabled while restoring. To enable them again, choose the profile or restart Anki[droid]`

###### Actual Result
Restoring from a backup immediately creates a new backup, thus deleting the oldest one. This means collection mistakes get spread through the older backups. 

Additionally, it seems that [the backup section of the AD manual](https://docs.ankidroid.org/manual.html#backups) is incorrect when it says "The backup is taken in the background when you first start the app. A backup will only happen if more than 5 hours has elapsed since the last time a backup was created" because I now have 8 backups from May 21, 2021. Even if this 5 hour rule were in place, I don't think restoring should result in a new backup being made: If today I restore from an artitrary backup, say 5/14/21, then AD will create a new backup for thats basically identical except with todays date.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.15alpha49

Android Version = 7.0

Manufacturer = LGE

Model = LGL84VL

Hardware = sf317

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; LGL84VL Build/NRD90U; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.91 Mobile Safari/537.36

ACRA UUID = 80da83ce-b9bf-4913-9e68-b343866833da

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Fixes
Fixes #8897

## Approach
1. Remove backup creation in `CollectionTask.java` after backup restoring
2. Remove `BackupManager.kt` `force` parameter since it isn't used anymore
3. Fix `BackupManagerTest.java`

## How Has This Been Tested?

Phone: Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30
https://user-images.githubusercontent.com/69634269/154801101-a3b986d6-ead3-4570-9394-ea302d01fcdf.mp4

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
This PR is mixing two things that do not need to be mixed I think?
1- the bugfix, stop doing a backup right after restore
2- the force flag, and associated test

Are they really intermingled, such that you cannot fix the issue without removing the force flag? If so, then it makes sense, but your two commits are not independently working, so they should be one commit (or we need to squash merge, but better to be in the habit of making sure each commit works on it's own)

If they are not truly entangled, then better to at least separate the bugfix so that it is one (working by itself) commit, then a second refactor commit where you note that force is no longer used, and you refactor it out + fix the test

What do you think?

**Comment by BrayanDSO** [comment]
Yes, they can be separated. Sorry for messing up with the commits org. I'll try to find the commands and reorganize them

**Comment by mikehardy** [comment]
No problem, honestly moving up the work effort a step from just "getting things done" to "making sure the work presents itself well commit by commit" is not something most professional software or commercial software organizations do even. We are a bit more picky in that regard here, but the volume of issues and pull requests is what drives it - I think if most commercial software organizations really were trying to review + merge 3+ PRs a day with with currently 70+ in flight they might need the same strategy.

Anyway, that's the motivation :-), thanks for looking back through it - I do like the change and I appreciate your taking it up

**Comment by BrayanDSO** [comment]
Thanks for being "picky". It's always better to build better habits and having higher standards. So, again, thank you 😄

**Comment by BrayanDSO** [comment]
I think it's okay now

**Review by mikehardy — APPROVED** [review]
This LGTM - thanks!

**Comment by Akshay0701** [comment]
Thank you @brayanDSO for your contribution, 

Code looks good(treat this as approval), but I would like to test this in my machine, I will let you know my tonight.

**Review by Akshay0701 — APPROVED** [review]
LGTM

**Comment by mikehardy** [comment]
Hi there! FEBRUARY OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [February 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-02-01..2022-02-28) (I'll do my best to follow this with the same process for March in a week)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of January)

Thanks!

**Pull request merged**
