### PR TITLE
Let AnkiDroid open zip files

### PR DESCRIPTION
**Pull request by timrae**
It appears that the latest version of Gmail is now setting the MIME type of apkg files to application/zip so I've added an intent filter for that

### CODE REVIEW

**Comment by wlhunag** [comment]
Hi, @timrae 
Everytime I download a .zip file from web browser, by default it opens via Ankidroid.
And it shows "That is not a valid apkg file."
device-2016-01-23-124959

Is there a better solution than delete this commit?

**Comment by timrae** [comment]
@wlhunag could you please install the app [intent intercept](https://play.google.com/store/apps/details?id=uk.co.ashtonbrsc.android.intentintercept) and share exactly which intent is getting picked up by AnkiDroid? Also, under Android settings > apps > AnkiDroid > Launch by Default, what is written? If you uninstall AnkiDroid, which app opens the zip file?

**Comment by wlhunag** [comment]
@timrae After I install `intent intercept`, I saw several options to open the .zip file.
When I test it on my phone using .zip file, it works fine now.

Image of Yaktocat
The Launch by Default setting is clear.
But I remember it sometimes opens other files in the past few weeks (or months) ,and shows the "not a valid apkg file" message.

Sorry that I cannot duplicate the problem now.

Anyway, that you for replying so fast.

**Comment by timrae** [comment]
I think Android might have automatically cleared the launch be default settings for zip files when you installed intent intercept, because that app supports opening zip files. That means the solution was probably just to clear the launch by default setting.

Regardless, could you please share the content of the intent when you choose "Intercept the Intent" in the above screen?

**Comment by wlhunag** [comment]
intent:///storage/emulated/0/Download/7za920.zip#Intent;scheme=file;action=android.intent.action.VIEW;type=application/zip;launchFlags=0x10000000;S.archive_file_name=%2Fstorage%2Femulated%2F0%2FDownload%2F7za920.zip;end 

ACTION:android.intent.action.VIEW 
DATA:file:///storage/emulated/0/Download/7za920.zip 
TYPE:application/zip 

FLAGS:
FLAG_RECEIVER_FOREGROUND 

EXTRAS:
EXTRA: 1:
Class:java.lang.String 
Key:archive_file_name 
Value:/storage/emulated/0/Download/7za920.zip 

3 ACTIVITIES MATCH THIS INTENT
檔案管理員(com.asus.filemanager-com.asus.filemanager.activity.FileManagerActivity)
AnkiDroid(com.ichi2.anki-com.ichi2.anki.IntentHandler)
ES檔案瀏覽器(com.estrongs.android.pop-com.estrongs.android.pop.app.compress.CompressionProxyActivity)

**Comment by timrae** [comment]
Thanks, we can limit the opening of zips by AnkiDroid to the case where the file extension is .apkg when it's a `file://` URI like it is here. Unfortunately I don't think we can do that when it's a `provider://` URI (for example when you open via the download manager), since the provider often doesn't give the file extension.

**Comment by wlhunag** [comment]
Thanks, it looks good!
And thank you, for developing this wonderful app.

**Pull request merged**
