### PR TITLE
Show two numbers in planification

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
As required on https://github.com/ankidroid/Anki-Android/issues/5829

Note that in case of month and year, I left it as it is, with a
floating point number. Still wishing that we never ever show "1.1
month remaining", because this number is supposed to be the time
required to study today assuming no pause are taken, and that nobody
can ever spend more than a month during a single day !

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Screenshot_20200618-183855_AnkiDroid

**Comment by Arthur-Milchior** [comment]
Screenshot_20200618-184243_AnkiDroid

**Comment by Arthur-Milchior** [comment]
In this case, in vertical mode, the screen is too short for me to see the number of minutes

**Comment by Arthur-Milchior** [comment]
I should note that, sadly, this is not a mock test, and this is really the number of card/time planified by ankidroid for my collection :(

**Comment by david-allison-1** [comment]
This needs a follow-up to turn the strings into `%1$d`:

```
C:\GitHub\Anki-Android-David\AnkiDroid\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2383: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
C:\GitHub\Anki-Android-David\AnkiDroid\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:2385: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?
```

**Pull request merged**
