### PR TITLE
Fix: UI - AnkiWeb account Login & Logout screen UI fixes

### LINKED ISSUE #17312: AnkiWeb Login Screen: text truncated
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Go to **Settings > Sync > AnkiWeb Account**. The text seems to be cut off. Image

After I've logged in, the screen looks weird in landscape mode. Image

### Expected behaviour

described above...

### Debug info

2.19beta6

### (Optional) Anything else you want to share?

_No response_

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by rohegde7**
## Purpose / Description
UI fix on the Ankiweb account Login and Logout.

## Fixes
* Fixes #17312

## Approach
- For Login screen added a horizontal padding to the "Note: AnkiWeb is not affiliated with AnkiDroid" text to avoid the last letter getting truncated
- For Logout screen I fixed the issue where "Logged in as" text was overlapping with the toolbar. I changed the nested Relative and Linear layout file with a better Constraint layout. Also have used NestedScrollView for any unconventional device layout that might need scrolling. I have made sure to keep all the layout IDs in use so nothing crashes.

## How Has This Been Tested?

- Used physical pixel 4a, Pixel 6a and OnePlus 8 devices to test it manually.

## Learning
Constraint Layout: 
https://developer.android.com/reference/androidx/constraintlayout/widget/ConstraintLayout

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
@rohegde7 I truly appreciate the effort here but the issue you filed this PR on already had direct interest from another developer who actively mentioned to you they were working on it.

It is considered impolite and a potential waste of effort via duplication to work on PRs that are claimed when the other person is still expressing active interest.

We may review and merge this PR but I want to be clear that coordination failures like that will not be rewarded. The OpenCollective PR comment bot will likely comment in the future but no part of the effort on this PR is eligible for an OpenCollective claim and any expense related will be rejected

**Comment by Prince-kushwaha** [comment]
Hi @rohegde7, Please Don't work on any issue in which someone is already working.

**Comment by rohegde7** [comment]
@mikehardy Thanks for the reply! I didn’t know about these standards. Will follow there things in the future. 

Meanwhile may I know what’s the time span devs usually take from commenting about taking on an issue and raising a PR? Do we have a hard rule about it? 

Also do we add the dev working on an issue as an assignee? 

All help is really appreciated! Excited to be contributing here.

**Comment by mikehardy** [comment]
> @mikehardy Thanks for the reply! I didn’t know about these standards. Will follow there things in the future.

Excellent - thanks!

> Meanwhile may I know what’s the time span devs usually take from commenting about taking on an issue and raising a PR? Do we have a hard rule about it?

There is no rule for it. It is collaborative, the idea is you picture you are in a room with your fellow developers all sitting near each other. Would you just start working on a task that someone else mentioned they were working on? No, of course not, that would be rude.

You would ask. And you would wait and listen for the answer. If there is a truly long period of time between "hey, are you still working on this?" and no answer, say 3-4 days, then go ahead and post again "did not hear back, I'll start on this"

Collaboration is everything

> Also do we add the dev working on an issue as an assignee?

In general no, we tried doing that before but it reflects too much ownership, for those rare cases when the dev that expressed initial interest simply does not get back to it, and also it's a burden for maintainers to assign and unassign people. So we keep it slightly less formal than full assignment

> All help is really appreciated! Excited to be contributing here.

Nice to have a new dev excited to be here 😄  - welcome!

**Review by criticalAY — COMMENTED** [review]
Root layout should be kept Coordinator layout since snackbars need that /though this activity doesn't have any but as convention/ rest looks good structure wise

**Comment by rohegde7** [comment]
> Root layout should be kept Coordinator layout since snackbars need that /though this activity doesn't have any but as convention/ rest looks good structure wise

So is it okay if we do not use coordinator here?

**Comment by mikehardy** [comment]
@rohegde7 unless there is a technical reason not to do coordinator layout, I believe the answer is "no"
If there is a technical reason, than the way to have progress here is to describe the technical reason
My take on your comment is sort of a "okay but can I ignore this comment?", and... no?

**Comment by criticalAY** [comment]
I am sure it can work with coordinator layout, and we should follow the convention

**Comment by rohegde7** [comment]
@criticalAY Sure let me make that change and push the update ASAP!

**Pull request closed without merging**
