### PR TITLE
NF: repair MediaTest

### PR DESCRIPTION
**Pull request by Arthur-Milchior**

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
was this a side effect of an NF refactoring PR?

**Comment by mikehardy** [comment]
Yes #12560 I think

**Comment by Arthur-Milchior** [comment]
It was. And yeah, you found the right one (I added a comment there too)

**Comment by mikehardy** [comment]
Second time I've seen this flake, very strange. Both on macOS-unit run for what it's worth

```
DeckPickerTest > [1] > com.ichi2.anki.DeckPickerTest.databaseLockedNoPermissionIntegrationTest[1] FAILED
    java.lang.IllegalStateException: Job "coroutine#192":StandaloneCoroutine{Cancelling}@15e1d023 is already complete or completing, but is being completed with CompletedExceptionally[java.lang.RuntimeException: GoogleAnalyticsExecutor is null]
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:831)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
        at kotlinx.coroutines.intrinsics.CancellableKt.dispatcherFailure(Cancellable.kt:65)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:78)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:[110](https://github.com/ankidroid/Anki-Android/actions/runs/3210672077/jobs/5248397221#step:8:111))
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask(CoroutineHelpers.kt:122)
        at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask(CoroutineHelpers.kt:131)
        at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask$default(CoroutineHelpers.kt:128)
        at com.ichi2.anki.StudyOptionsFragment.refreshInterface(StudyOptionsFragment.kt:499)
        at com.ichi2.anki.StudyOptionsFragment.refreshInterface(StudyOptionsFragment.kt:483)
        at com.ichi2.anki.StudyOptionsFragment.onCreateView(StudyOptionsFragment.kt:162)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
        at com.ichi2.anki.AnkiActivity.onStart(AnkiActivity.kt:[112](https://github.com/ankidroid/Anki-Android/actions/runs/3210672077/jobs/5248397221#step:8:113))
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnStart(RoboMonitoringInstrumentation.java:285)
        at android.app.Activity.performStart(Activity.java:7825)
        at jdk.internal.reflect.GeneratedMethodAccessor[114](https://github.com/ankidroid/Anki-Android/actions/runs/3210672077/jobs/5248397221#step:8:115).invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.robolectric.shadows._Activity_$$Reflector18.performStart(Unknown Source)
        at org.robolectric.android.controller.ActivityController.lambda$start$2(ActivityController.java:162)
        at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:204)
        at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:64)
        at org.robolectric.android.controller.ActivityController.start(ActivityController.java:157)
        at com.ichi2.anki.RobolectricTest$Companion.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.kt:267)
        at com.ichi2.anki.RobolectricTest.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.kt)
        at com.ichi2.anki.RobolectricTest.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.kt:340)
        at com.ichi2.anki.DeckPickerTest.databaseLockedNoPermissionIntegrationTest(DeckPickerTest.kt:281)
```

**Comment by mikehardy** [comment]
Okay, third time I've seen this now, something is definitely wrong with macOS unit tests

```
DeckPickerTest > [1] > com.ichi2.anki.DeckPickerTest.databaseLockedNoPermissionIntegrationTest[1] FAILED
    java.lang.IllegalStateException: Job "coroutine#192":StandaloneCoroutine{Cancelling}@7f95536e is already complete or completing, but is being completed with CompletedExceptionally[java.lang.RuntimeException: GoogleAnalyticsExecutor is null]
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:831)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
        at kotlinx.coroutines.intrinsics.CancellableKt.dispatcherFailure(Cancellable.kt:65)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:78)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask(CoroutineHelpers.kt:122)
        at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask(CoroutineHelpers.kt:131)
        at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask$default(CoroutineHelpers.kt:128)
        at com.ichi2.anki.StudyOptionsFragment.refreshInterface(StudyOptionsFragment.kt:499)
        at com.ichi2.anki.StudyOptionsFragment.refreshInterface(StudyOptionsFragment.kt:483)
        at com.ichi2.anki.StudyOptionsFragment.onCreateView(StudyOptionsFragment.kt:162)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:[251](https://github.com/ankidroid/Anki-Android/actions/runs/3210672077/jobs/5248557246#step:8:252))
        at com.ichi2.anki.AnkiActivity.onStart(AnkiActivity.kt:112)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnStart(RoboMonitoringInstrumentation.java:285)
        at android.app.Activity.performStart(Activity.java:7825)
        at jdk.internal.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.robolectric.shadows._Activity_$$Reflector18.performStart(Unknown Source)
        at org.robolectric.android.controller.ActivityController.lambda$start$2(ActivityController.java:162)
        at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:204)
        at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:64)
        at org.robolectric.android.controller.ActivityController.start(ActivityController.java:157)
        at com.ichi2.anki.RobolectricTest$Companion.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.kt:267)
        at com.ichi2.anki.RobolectricTest.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.kt)
        at com.ichi2.anki.RobolectricTest.startActivityNormallyOpenCollectionWithIntent(RobolectricTest.kt:340)
        at com.ichi2.anki.DeckPickerTest.databaseLockedNoPermissionIntegrationTest(DeckPickerTest.kt:281)

        Caused by:
        java.lang.RuntimeException: GoogleAnalyticsExecutor is null
            at com.brsanthu.googleanalytics.request.GoogleAnalyticsRequest.sendAsync(GoogleAnalyticsRequest.java:1871)
            at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
            at com.brsanthu.googleanalytics.request.GoogleAnalyticsRequest.sendAsync(GoogleAnalyticsRequest.java:1870)
            at com.ichi2.anki.analytics.UsageAnalytics.sendAnalyticsException(UsageAnalytics.kt:276)
            at com.ichi2.anki.analytics.UsageAnalytics.sendAnalyticsException(UsageAnalytics.kt:252)
            at com.ichi2.anki.analytics.UsageAnalytics.installDefaultExceptionHandler$lambda$1(UsageAnalytics.kt:122)
            at org.acra.builder.ReportExecutor.handReportToDefaultExceptionHandler(ReportExecutor.java:102)
            at org.acra.reporter.ErrorReporterImpl.uncaughtException(ErrorReporterImpl.java:147)
            at com.ichi2.anki.analytics.UsageAnalytics.installDefaultExceptionHandler$lambda$1(UsageAnalytics.kt:127)
            at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1055)
            at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1050)
            at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1050)
            at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:61)
            at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
            at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:146)
            at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:383)
            at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
            at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
            at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
            at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
            at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
            at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
            at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
            at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
            at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask(CoroutineHelpers.kt:122)
            at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask(CoroutineHelpers.kt:131)
            at com.ichi2.anki.CoroutineHelpersKt.launchCatchingTask$default(CoroutineHelpers.kt:128)
            at com.ichi2.anki.StudyOptionsFragment.refreshInterface(StudyOptionsFragment.kt:499)
            at com.ichi2.anki.StudyOptionsFragment.refreshInterface(StudyOptionsFragment.kt:483)
            at com.ichi2.anki.StudyOptionsFragment.onCreateView(StudyOptionsFragment.kt:162)
            at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
            at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
            at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
            at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
            at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
            at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
            at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
            at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
            at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
            at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
            at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
            at com.ichi2.anki.AnkiActivity.onStart(AnkiActivity.kt:112)
            at android.app.Instrumentation.$$robo$$android_app_Instrumentation$callActivityOnStart(Instrumentation.java:1425)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java)
            at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnStart(RoboMonitoringInstrumentation.java:285)
            at android.app.Activity.$$robo$$android_app_Activity$performStart(Activity.java:7825)
            at android.app.Activity.performStart(Activity.java)
            at jdk.internal.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by mikehardy** [comment]
I have intel mac machines to check this, will investigate in a minute, but it appears that we have multiple build + test breaks going on at once, developed over a couple of days. Will take some time to get the tree back in shape I guess.

**Comment by mikehardy** [comment]
superceded by combo pr #12602

**Pull request closed without merging**
