### PR TITLE
test(ci): take advantage of new public repo action runner capabilities

### LINKED ISSUE #15368: Handle CI Runner performance improvements
might just quickly change the number of threads in CI in the build gradle since they're all 4 vCPU now, and maybe stop doing the in-process kotlin compile? Those are both just toggles and might speed up windows as a quick extra-commit-win

future investigation may be to revive the old emulator test workflow we had that did nested virt on ubuntu to get the emulator to run there and convert tests emulator back to ubuntu ? but keeping it on macos-current is fine for now, incremental steps are positive steps

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/15367#issuecomment-1918305589_

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

The new github actions runners have about 2x the vCPU and they have nested virt enabled

## Fixes
* Fixes #15368 

## Approach
- one commit doubles the max test forks, based on the throughput benchmarks Azure posts that seems right
- one commit switches to ubuntu, and fiddles with permissions a little bit so it works

## How Has This Been Tested?

The PR is made of tests

## Learning (optional, can help others)
- https://github.com/actions/runner-images/issues/183#issuecomment-1442154492 (which now applies to public repos too)
- https://stackoverflow.com/questions/37300811/android-studio-dev-kvm-device-permission-denied/61984745#61984745
- https://github.com/reactivecircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Well, how bout that. This appears to be one of the rare "That was easy" PRs.

> INFO    | Boot completed in 25109 ms

**Comment by mikehardy** [comment]
So much faster! https://github.com/ankidroid/Anki-Android/actions/workflows/tests_emulator.yml

Appears to be 2x faster vs current macOS as advertised

May be that the new Apple Silicon public runners would be faster yet but since they don't appear to support nested virtualization we can't use them and may never be able to.

This is a nice improvement.

**Review by david-allison — APPROVED** [review]
Looks great! Blazing fast (and much cheaper for GitHub)

@mikehardy could I get this cross-licenced under MIT? I suspect we can contribute this upstream and merge it into the emulator runner repo

**Comment by mikehardy** [comment]
🤔 the emulator repo documents this as how to do it, so I'm not sure they need anything ? :-)

That said, sure, permission to license any way that seems useful

**Pull request merged**
