### PR TITLE
Remove unused strings

### PR DESCRIPTION
**Pull request by hssm**
I used the tool from https://github.com/ankidroid/Anki-Android/pull/761 for the most part to remove unused strings. I skipped dimens.xml and colors.xml since they are probably being actively worked on, and I skipped all the translated versions since that should be handled by crowdin.

### CODE REVIEW

**Comment by timrae** [comment]
Hmm there are still more than a thousand unused resource errors... for example `R.string.multimedia_editor_languages_russian`, etc etc

**Comment by hssm** [comment]
I imagine most of them would disappear once you upload the new resource files to crowdin and pull in the new translations (i.e., the new files won't have the fields we just removed).

Although for this particular example, I don't know what is going on. That field doesn't exist in the default translation...

**Comment by timrae** [comment]
Hmmm strange... I already did a push to crowdin, then deleted all translation files, and then pulled from crowdin. It could be a crowdin bug I guess

**Comment by nicolas-raoul** [comment]
Crowdin has one of the best support teams I have ever dealt with, don't
hesitate to report bugs if you find any.

**Comment by hssm** [comment]
I honestly don't know how the crowdin stuff works. Does it have separate branches for dev/release? Does it delete translation entries if the default one is deleted?

**Comment by nicolas-raoul** [comment]
Gitub does not have branches unfortunately, so we don't provide additional translations for bugfix releases.

Crowdin removes translated entries if the English one is deleted.

**Comment by timrae** [comment]
I just synced the crowdin project with develop today. Theoretically it does
delete unused strings but we will have to figure out what's going on.

I've been meaning to start a brand new project anyway and import the
strings into it, which is supposed to fix the issues with plurals in some
languages... It might kill two birds with one stone

**Comment by timrae** [comment]
So, it turns out that the multimedia strings were missing from the crowdin script...  Mystery solved lol. Sorry for the confusion

**Comment by eginhard** [comment]
Recreating the project would be great to finally get proper plurals support. :)

**Comment by nicolas-raoul** [comment]
@Enno Do you mean that improvements got implemented in Crowdin, but we have
to re-create the project to benefit from them?

**Comment by timrae** [comment]
Nicolas, yes exactly... actually I mentioned this to you several times in
the past lol.

If you search the forum for "plurals" I guess you should find the thread.

**Comment by nicolas-raoul** [comment]
Good news: Plurals are now activated on our Crowdin project :-)

They will be usable after the next strings push.
Note: Translations of strings with plurals will be lost.

Cheers!

**Comment by eginhard** [comment]
@nicolas-raoul Thanks a lot, that is great news!

**Comment by timrae** [comment]
Great, thanks a lot @nicolas-raoul! I just cleaned up the resources again and did a new push to crowdin, where I confirmed that plural forms are now activated

**Pull request merged**
