### PR TITLE
Convert line-endings from CRLF to LF.

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ This commit introduces no code change!
+ Please do not commit files with Windows line endings (CRLF) since this
  causes a permanent **full-file-diff** on Unix machines. The Git config
  can be setup to automatically convert line endings back and forth on a
  Windows machine.

---

> Formatting and whitespace issues are some of the more frustrating and subtle problems that many developers encounter when collaborating, especially cross-platform. It’s very easy for patches or other collaborated work to introduce subtle whitespace changes because editors silently introduce them, and if your files ever touch a Windows system, their line endings might be replaced. Git has a few configuration options to help with these issues.

> `core.autocrlf`

> If you’re programming on Windows and working with people who are not (or vice-versa), you’ll probably run into line-ending issues at some point. This is because Windows uses both a carriage-return character and a linefeed character for newlines in its files, whereas Mac and Linux systems use only the linefeed character. This is a subtle but incredibly annoying fact of cross-platform work; many editors on Windows silently replace existing LF-style line endings with CRLF, or insert both line-ending characters when the user hits the enter key.

> Git can handle this by auto-converting CRLF line endings into LF when you add a file to the index, and vice versa when it checks out code onto your filesystem ...

Source: [Git documentation - Configuration - Formatting-and-Whitespace](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace)

### CODE REVIEW

**Comment by agrueneberg** [comment]
Good to see that only three non-essential files are affected. Does Android Studio take care of this automatically? I don't see it in the `.idea` folder.

**Comment by johnjohndoe** [comment]
@agrueneberg What exactly do you mean? Git told me that line endings are odd. This has nothing to do with the editor.

**Comment by agrueneberg** [comment]
I'm just wondering if the fact that no code files are affected is due to not having developers on Windows, or Android Studio taking care of the conversion. You're suggesting that Windows users should change their Git configuration to better contribute, and I think this could be better enforced as part of our Android Studio project files (if not done already).

**Comment by johnjohndoe** [comment]
Android Studio has no custom configuration for Git afaik. It reads the global configuration for Git, which is located in `$HOME/.gitconfig` on Unix. Similar on Windows.

**Comment by hssm** [comment]
@agrueneberg I wondered the same thing.

Android Studio has a [setting](https://www.jetbrains.com/idea/help/configuring-line-separators.html#d78843e115) for new files and the default is system-dependent. So if I understand things correctly, any *new* files created on a Windows machine will use CRLF and we've just been lucky that nobody has done this yet. For existing files, the IDE determines the scheme and continues to use it (it's indicated in the status bar at the bottom, after the line/column numbers).

As for this PR, I don't know if it makes sense to modify those three files since they are generated with an external application.

@johnjohndoe 
>Git told me that line endings are odd.

At what point does it tell you? Are you modifying those files?

**Comment by johnjohndoe** [comment]
Yes, the problem occurs most often with files created by external applications. Git shows files as modified as soon as I checkout the repository onto my Ubuntu machine.

**Comment by johnjohndoe** [comment]
I rebased the branch onto current _develop_.

**Comment by timrae** [comment]
@johnjohndoe 
Could you please give us a set of reproducible steps to demonstrate the issue? Are you trying to edit these specific SVG image files? I work on both Ubuntu and Windows machines a lot and don't usually have any problem. We had some problems in the past when I ran the crowdin scripts on a Windows machine, but other than that it's been smooth sailing.

**Comment by johnjohndoe** [comment]
To clarify once again - I am **not** trying to edit these SVG files. All I do is **checking out** the repository to an Ubuntu machine.

To see the Windows line endings `CRLF` yourself just open a SVG file in an editor of your choice which is capable of distinguishing line endings on Ubuntu.

You might wanna use my Git configuration to reproduce the checkout. Please find my settings [here](https://github.com/johnjohndoe/dotfiles/blob/master/gitconfig).

**Comment by agrueneberg** [comment]
Thanks for sharing your config. Looks like the warnings are coming from the `*crlf` options which are unset by default. I wouldn't mind merging this provided that Illustrator for Windows can deal with those line endings (one would hope, right?).

**Comment by johnjohndoe** [comment]
Illustrator should work fine since Git is able to checkout files with Windows line endings as mentioned in the documentation:

> ... Git can handle this by auto-converting CRLF line endings into LF when you add a file to the index, and vice versa when it checks out code onto your filesystem ...

The general idea is **not to mix** line endings in the repository. There all files are stored with the same type of line endings, e.g. `LF` for a multi-platform project.

**Comment by agrueneberg** [comment]
Well, Git only converts the line endings if `core.autocrlf` is set to `true`. So it will work for you, but it might not work for others (unless this is enabled by default on Git for Windows?). In any case, I don't think it will be an issue and I agree that ideally the line endings should not be mixed. Thanks for bringing this to our attention @johnjohndoe and thanks for merging @timrae.

**Comment by johnjohndoe** [comment]
You are very welcome. This will make it much easier for contributors to participate.

**Pull request merged**
