### PR TITLE
Replaced Toast with Snackbar in AudioView.kt

### PR DESCRIPTION
**Pull request by Giyutomioka-SS**
## Purpose / Description
Replaced toast with Snackbar in AudioView.kt

## Fixes
Related to #13411

## How Has This Been Tested?
Tested on Realme 6 (API level 30)

image

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
AudioView is also used in the Reviewer's "Check Pronunciation" feature, how does it look there?

**Comment by Giyutomioka-SS** [comment]
Preview of Snackbar in "Check Pronunciation" feature


https://github.com/ankidroid/Anki-Android/assets/91668590/fbd0b01f-bf08-4b06-a4d8-85844d762895

**Comment by david-allison** [comment]
That seems to obscure the 'show answer' button

**Comment by criticalAY** [comment]
I will peel off this `AudioView.kt` soon as I am working on the new UI for the audio recorder, which would remove the need for an Audio view and an AudioRecorder, Refer #14591

**Comment by Giyutomioka-SS** [comment]
Should i close this PR then ?

**Comment by criticalAY** [comment]
Depends on the reviewer as it might take a few weeks for me to get there, leaving it to David

**Pull request closed without merging**
