### PR TITLE
increase max backups from 10 to 99

### LINKED ISSUE #9022: Increase or eliminate the upper limit of backup generation
**Is your feature request related to a problem? Please describe.**
With backup limits of up to 10 generations, I'm worried about preparing for upcoming delicate changes such as schema changes.

**Describe the solution you'd like**
Increase or eliminate the upper limit of backup generation

**Describe alternatives you've considered**
The classic method of manually re-backing up backup files.

**Additional context**
As the storage capacity of smartphones has increased recently, it may be more advantageous to raise the default setting value of the backup generation at the same time.
Even if the default number is set to 50 generations like the anki desktop, I think that there are few people who run out of storage capacity with current smartphones.

### PR DESCRIPTION
**Pull request by david-allison-1**
User wanted more

Fixes #9022

Note: The slider position implies that the user should increase the setting now, unsure if this is wise.

image

### CODE REVIEW

**Review by mikehardy — DISMISSED** [review]
I realize I'm increasing scope from a change of two digits to something else but I saw this the other day while examining the crash related to the new "increment" dialog type and I thought "the backups dialog is currently not the new +/- increment type but should be converted". If it's not hard (that is: at your option) - converting this to the new increment dialog would be great. Otherwise, merge at will

**Comment by david-allison-1** [comment]
Sounds good, will get to it tomorrow

**Comment by david-allison-1** [comment]
image

**Review by mikehardy — APPROVED** [review]
Nice, and I'm glad it's that easy to switch these things

**Pull request merged**
