### PR TITLE
NF: init capacity of list, map and set

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
I went through list, map and set, checking when the size can be known in advance and added it. I went through them already to transform them into fastutil's LongList, IntList, etc... and wanted to add size simultaneously. But, given that I'm not yet sure that fastutil is actually an improvement, I left it for a future PR

### CODE REVIEW

**Comment by mikehardy** [comment]
To make sure I understand this correctly: there is no downside as the size passed in a collection initializer is the initial allocation, but there is nothing to stop it from internally resizing afterwards correctly?

I guess there is the downside of perhaps pre-allocating more than you would use but I imagine your initializers are correct

**Comment by Arthur-Milchior** [comment]
Your analysis is entirely right. An array list is basically a pair with an array and the position of the last element in it. The array gets copied in a bigger array if no more room stay.
This ensure that no resizing is required when an upper bound of the size can be known in advance.

The size I set is an upper bound of the actual size of the array used. 
For example, if some element of list L is copied into list L', then L' is initialized with capacity of L's size. This ensure that no copy, no new allocation, are required. If actually, no element is copied, the lost size is just the size of L. 
I did not initialize when there is no way to know initial size, such as when we query the database or when the only known upper bound is the number of note/card but I expect the actual number of element of the list to be quite smaller.

In the case where I made an error, I can imagine two consequences:
* either there is an error while computing the initial capacity (e.g. during the tests, I got a null pointer exception, because I was trying to get some information before the collection was loaded), in which case we should see it quickly
* or there is an error in the size I predicted, which simply mean that reallocation will occur as it does currently. The first reallocation will occur when the list has the number of element I indicated in the inialization, instead of occurring when the 11th element is added, but that's no big deal.

**Comment by Arthur-Milchior** [comment]
Conflict removed

**Comment by mikehardy** [comment]
Oh dang, this took a conflict again @Arthur-Milchior - this looks like a perfect candidate for merge since you answered my question (long ago...)

**Comment by Arthur-Milchior** [comment]
Rebased

**Review by mikehardy — APPROVED** [review]
LGTM

**Comment by david-allison-1** [comment]
This change sets the `initialCapacity` for `HashSet` and `HashMap`

My understanding is that these collections will expand their capacity when `capacity > intialCapcity * loadFactor` (maybe `>=`)

As `loadFactor < 1`, this means that by setting the capacity equal to the known collection size, we'll guarantee that each collection will go through a resize operation, which is what we want to avoid

**Comment by Arthur-Milchior** [comment]
Oops.
Indeed, in this case, I should have divided it by .75 to ensure no resizing. Thanks for catching it

**Pull request merged**
