### PR TITLE
load balancer plugin

### PR DESCRIPTION
**Pull request by jakeprobst**
http://code.google.com/p/ankidroid/issues/detail?id=2152
https://ankiweb.net/shared/info/1417170896
So basically this is a cool thing I did for the desktop as a plugin but there is like not a way to do plugins here so heres to hoping this gets merged so when anki decides to change how syncing works which forces me to update I dont have to spend 3 hours trying to figure out why eclipse isnt working when it turns out the entire build system changed.

### CODE REVIEW

**Comment by jvanprehn** [comment]
I'm thinking about adding this as a plugin. 

I think that the hook in Sched.java is just the easy part.

The plugin has deck-specific options, so I'm considering creating a hook in DeckOptions.onCreate().

After this.addPreferencesFromResource(R.xml.deck_options); I could call the hook, passing it this.getPreferenceScreen() and this.getPreferenceManager() and maybe some other things we need.

The hook can then do a preferenceManager.createPreferenceScreen, add preferences to it and then add this preference screen to the passed preferencescreen.

I also have to add a hook to DeckOptions.cacheValues and DeckOptions.commit().

I think it's better than cluttering deck_options.xml with it... What do you think?

**Comment by hssm** [comment]
Would be it possible to extend the `DeckOptions` class and override those specific methods instead? I think you can get away with not duplicating code by placing `super` calls at the end of your own implementations.

**Comment by gajewsk2** [comment]
Any update on this? What's holding this up?

**Comment by jvanprehn** [comment]
img-20170720-wa0002

**Comment by langlieb** [comment]
That's the perfect response. Congratulations!

**Comment by jhennig3** [comment]
It looks to me like this branch could be merged without a problem, has it been? I recently commented on a separate [issue](https://github.com/ankidroid/Anki-Android/issues/2943) for the incorporation for the load-balancer to ankidroid, is this the resolution of that?

**Comment by timrae** [comment]
Did you try reading the comments for clues as to why it hasn't been merged?

**Comment by timrae** [comment]
Your only option really is to rebase this onto master branch and build yourself a custom version of ankidroid. There are some tips for that on the development wiki

**Comment by mikehardy** [comment]
Just noting that this is still very popular in Anki desktop, and @jakeprobst has been successfully maintaining the plugin there for quite some time. Other users have forked and built his AnkiDroid to get it even (3 forks and counting - not bad).

I'm not sure what the popularity hurdle for a feature is, but if there was a way to do this (just hooking into libanki, but otherwise supporting it as an advanced preference plugin) I think this one might be popular enough, especially since the code exists as a PR already and assuming Jake is okay with handling issues that arise.

?

**Comment by timrae** [comment]
If someone makes a PR adding support for scheduler v2 then we will be able to support multiple schedulers and this will be trivial

**Comment by mikehardy** [comment]
Hmm - that brings up a good point @jakeprobst - does this handle the v2 scheduler in Python yet? Just curious if you layer on top, or replace the schedule function, or ? - and for the others on this issue (I say that because I see a baby picture in here and I'm a parent too) - I've resurrected this from the dead and if it's traffic you don't want please leave a reaction on the original pull request (or issue or both) as a "vote" then unsubscribe so we don't spam you. Cheers

**Comment by mikehardy** [comment]
Hey! Nice to hear you chime in. You're extension has enduring popularity and I think it's a rare signal to see people actually fork on github just to build a mod. Maybe we can come up with something clean here?

**Pull request closed without merging**
