### PR TITLE
Improve pre commit hook

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
I expect first commit to be sufficient. Commit three is probably overkill. But I don't want to lose hours of work anymore. And the slight risk that, if we stop overwritting the same file all the time, we save data seems quite nicer than risking a repeat.

Fixed: #17591

### CODE REVIEW

**Comment by david-allison** [comment]
How does this code differ from the currently generated hook?

Can a subset of this be submitted upstream?

**Comment by Arthur-Milchior** [comment]
The base of the bug is that we had `set -e`. That's not part of the code that is marked as copied from upstream. 
It cause the code to halt when the lint fails, and so the restore of the patch is never done.

Patch 2 by itself there is no reason to just ask them to rename a variable.

Patch 3 may be nice. But honestly, I added just for extra safety. When their code work as expected (i.e. we have not added `set -e` beforehand) there is no need for it. Also, even without `set -e`, even if  applying the patch fail, finding the patch and applying may not be easy for most users who are not used to go in a hidden folder, open a file that is not known by android studio and apply a patch. That's really a last resort save if everything else fails

**Review by david-allison — APPROVED** [review]
Forgot to approve. LGTM!

**Review by mikehardy — APPROVED** [review]
LGTM, my condolences for the last work that triggered this - hadn't commented on that but have seen the comments going around. What a pain

**Pull request merged**
