### PR TITLE
Ensure that onboarding can be cancelled

### PR DESCRIPTION
**Pull request by Arthur-Milchior**

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Could you also add a unit test to ensure that new constants aren't missed

**Comment by Arthur-Milchior** [comment]
I don't see how to do it. I can check that all flags we use are actually in the set defined here, but that only work if we assume that we'll want all flags ever to be cancellable (it's true right now. Will it remain so?)
Also, at most, it would fail during running a new installation of ankidroid, which is not something easy to automatically detect

**Comment by david-allison-1** [comment]
You should be able to reflect through the companion object, and ensure that `len(features) == len(constants in companion)`

along the lines of 

https://github.com/ankidroid/Anki-Android/blob/783e3406d76742a10afe5f8e9739b96d8c502160/AnkiDroid/src/test/java/com/ichi2/anki/servicemodel/PreferenceUpgradeServiceTest.kt#L90-L101

**Comment by Arthur-Milchior** [comment]
Done, I think

**Review by david-allison-1 — APPROVED** [review]
LGTM

**Review by mikehardy — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
