### PR TITLE
Remove most of custom activity transition animations in favor of consistency

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description
The app isn't consistent at all with its activity transitions. A lot of them were without animation because it was easier to call it when `finish` and `startActivity` were deprecated. Another bunch was just inconsistency that is natural when the repo has more than 300 different contributors

## Approach
In the commits

## How Has This Been Tested?

Emulator 31

[abc.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/8e02d763-4c24-4dec-8b38-5e116bb1bbc1)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
This has a side effect of really helping with the predictive back implementation I think ( 👀 @lukstbit ) since one of the issues there is that knowing how to finish (with animation? without? which type?) was one of the things you had to know in order to line up the correct back handling as it would trigger the animation

Just to say, I'm in favor of simplifying - however hopefully there is still a little bit of eye-candy with regards to animations so the app looks nice as it goes between screens. Looks like it's all "standard" system fade in now (at least on that SDK level, I think Android itself varies the default transition as it goes from Android 5 to Android 14)

Anyway, probably still worth it even though the standard fade is a little 🥱 😄

**Comment by BrayanDSO** [comment]
Make them consistent also means that we can change the default animations in a single sweep if necessary.

**Review by david-allison — APPROVED** [review]

**Comment by lukstbit** [comment]
@BrayanDSO This took some conflicts, do you have time to fix them? If not, I can also fix them so we move this forward.

**Review by lukstbit — APPROVED** [review]
Two issues to fix:
- unused imports
- AnkiActivity.launchActivityForResultWithAnimation() could be deleted as well as it has just two uses which were recently added in ImportFileSelectionFragment

Feel free to merge after fixing those.

**Comment by mikehardy** [comment]
@BrayanDSO I scanned this one before and didn't leave a review but it looked good to me. I'm doing a bunch of review/merge shepherding right now, if you leave it I'll work it in via squash merge when CI is ready ✅

**Pull request merged**
