### PR TITLE
Indicate we incorporate AGPLv3 code.

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Indicate we incorporate AGPLv3 code.

While we don't have to list all licences used from any library, this seems especially relevant because:
* AGPLv3 is seens as a risk by some (e.g. https://opensource.google/docs/using/agpl-policy/ ) and there should be a clear warning I believe
* It can easily be argued that anki backend is very related to ankidroid, and is not just a third-party library. Especially since it seems quite probable that one day we'll need to make some PR to anki backend for our need.

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
This is fine by me for the record but I'll defer to @david-allison-1

**Comment by dae** [comment]
It would be good if you could make this clear in the -backend module as well - currently both GitHub and https://search.maven.org/artifact/io.github.david-allison-1/anki-android-backend simply say "GPL3"

**Comment by david-allison-1** [comment]
Sounds good to me. Will do ASAP

**Comment by david-allison-1** [comment]
https://github.com/david-allison-1/Anki-Android-Backend/commit/0dafa4552fae3ee1387d448f4fa6c97730506227

**Comment by Arthur-Milchior** [comment]
I don't understand where exactly those agpl indication need to be added. But if, David, you feel confident to know what's required, that's fine by me

**Pull request merged**
