### PR TITLE
lint: remove unknown issues from lint.xml

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

These were trigging "UnknownIssueId" lint warnings because they
are no longer valid lint issues
_Describe the problem or feature and motivation_

## Learning (optional, can help others)

Lint rules change over time

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
UnknownIssueId should probably be made a fatal lint :thinking: ?

**Comment by david-allison-1** [comment]
Let's 

> UnknownIssueId should probably be made a fatal lint 🤔 ?

Let's do it

**Comment by mikehardy** [comment]
will add it to the fatal list as a second commit (and will massage first commit until it passes of course...)

**Review by david-allison-1 — APPROVED** [review]
LGTM 👍

**Pull request merged**
