### PR TITLE
feat(new reviewer): collapse user actions

### PR DESCRIPTION
**Pull request by voczi**
## Purpose / Description
Collapse user actions in the new reviewer. Takes up too much space of the drop-down.

## Fixes
N/A.

## Approach
Add all user actions under a new menu instead, so they do not take up all the space.

## How Has This Been Tested?
Tested in emulator, API 34.

## Learning (optional, can help others)
Inkscape for creating vectors, to then import it in Android Studio as a resource.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

https://github.com/user-attachments/assets/70edb0a1-63c8-4b0b-ab14-e58d6396ab2d

### CODE REVIEW

**Comment by BrayanDSO** [comment]
I am not sure if that's desired. It's an extra tap every time that someone wants to trigger an User action. 

Unless the user has many of them configured, it doesn't seem worth it to have a standalone menu.

Those actions should not be in the menu by default. That will be changed when the new configuration screen for toolbar actions is implemented. Hiding them right now is temporary work that will be replaced soon, so also not worth it for a developer option.

**Comment by voczi** [comment]
> Unless the user has many of them configured, it doesn't seem worth it to have a standalone menu.

I think in that case, this can be kept and used if the drop-down ends up overflowing because a user has added too many actions.

**Comment by BrayanDSO** [comment]
The options that I see are:

1. Don't group
2. Always group
3. Only group after X actions are shown

I'm not strong in any of them. The current status in the legacy reviewer is `Don't group`, and nobody came to complain about it or suggest something else, so I tend to prefer keeping things as is.

**Comment by voczi** [comment]
Sounds good.

**Pull request closed without merging**
