### PR TITLE
[Kotlin Migration] DatabaseChangeDecorator

### PR DESCRIPTION
**Pull request by codingtosh**
[Kotlin Migration] DatabaseChangeDecorator

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM

**Review by mikehardy — CHANGES_REQUESTED** [review]
Oh wait, there is a nullability problem.
Side question, why aren't kotlin files generating line numbers :thinking: 

```

    java.lang.NullPointerException: Parameter specified as non-null is null: method com.ichi2.utils.DatabaseChangeDecorator.query, parameter bindArgs
        at com.ichi2.utils.DatabaseChangeDecorator.query(DatabaseChangeDecorator.kt)
        at com.ichi2.libanki.DB.<init>(DB.java:79)
        at com.ichi2.libanki.backend.RustDroidBackend.openCollectionDatabase(RustDroidBackend.java:55)
```

**Comment by david-allison-1** [comment]
This one should be converted to use Kotlin Delegation in a follow-up commit as a medium priority extension

**Comment by david-allison-1** [comment]
Just to note: expecting to get this in as just a Kotlin conversion, no need for the follow-up to be handled in this PR

**Comment by codingtosh** [comment]
> Just to note: expecting to get this in as just a Kotlin conversion, no need for the follow-up to be handled in this PR

@david-allison-1  Ah, okay. This was a bit of a blocker. I couldn't find any documentation on medium priority extensions(method?). Could you please link some reading material on it?

Meanwhile I've removed the NPE's, I'll upload the patch shortly.

**Comment by david-allison-1** [comment]
> > Just to note: expecting to get this in as just a Kotlin conversion, no need for the follow-up to be handled in this PR
> 
> @david-allison-1 Ah, okay. This was a bit of a blocker. I couldn't find any documentation on medium priority extensions(method?). Could you please link some reading material on it?
> 
> Meanwhile I've removed the NPE's, I'll upload the patch shortly.

Sorry! Just my bad English.

* Medium-priority: don't backlog it forever
* Extension: something to be done outside this PR
* Kotlin Delegation: Using the `by` keyword so we don't need to re-implement the functionality: https://kotlinlang.org/docs/delegation.html

**Comment by codingtosh** [comment]
@david-allison-1 Thanks for the clarification, pushed the required changes, PTAL.

**Review by david-allison-1 — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]
Boom!

**Pull request merged**
