### PR TITLE
reset deck language

### PR DESCRIPTION
**Pull request by arooooon**
Added the ability to reset specific deck languages as claimed in Preferences>>Advanced>>Reset language.

### CODE REVIEW

**Comment by timrae** [comment]
You should only show the reset TTS language option if TTS is enabled in advanced preferences. Personally I think it makes more sense to put it in the reviewer overflow menu than the long press menu, as users are most likely to want to reset the language from the reviewer when the wrong language is spoken

**Comment by timrae** [comment]
I think "TTS" needs to be in the string somewhere too, maybe "Reset TTS languages" is enough without saying "deck" as that's reasonably obvious

**Comment by timrae** [comment]
Maybe it would be useful to show a snackbar "TTS languages reset for current deck" on resetting?

**Comment by timrae** [comment]
Another possibility could be to say "Set TTS language" in the menu and actually show the language selector dialog directly. This would be a little harder to code but slightly more intuitive to use IMO

**Comment by arooooon** [comment]
Oh yeah... forgot about hiding it when TTS is disabled. 

As for the text, in the Reset function in Advanced it says it will reset not only TTS but also "dictionaries". And every other item in the deck context menu had "deck" in it, so that's why :)

I think it is best to have the reset deck option in deck context menu since it concerns not just one card but the whole deck.

Yes I would prefer the last option to be able to set language for each card, but I haven't quite understood when a language is prompted. Deck, card and if the card appears as a question or answer.

If you add a 'basic and reversed' note/card it will ask you what language you want during review *twice* for each card. Once for when it appears as the question and once for when it appears as the answer.. weird. Why would one wanna choose a different language for the same card?

**Comment by arooooon** [comment]
I can't find any info on what model and model type means.. 

from storeLanguage(Context context, long did, int ord, int qa, String language)

"Associates a language to a deck, model, and card model for a given type."

**Comment by timrae** [comment]
> I think it is best to have the reset deck option in deck context menu since it concerns not just one card but the whole deck.

Deck options and whiteboard are both not card-specific yet are available in the reviewer context menu, so I don't think that's enough reason by itself. We should choose the location that offers the better user experience, wherever that is.

> If you add a 'basic and reversed' note/card it will ask you what language you want during review twice for each card.

Looking at the code, it stores the `ord` which is the card number within the template. It would be 0 for the first card in the note type, 1 for the second, etc etc.

> Why would one wanna choose a different language for the same card?

If you have Japanese > English for one card and English > Japanese for another card you wouldn't want them both to speak Japanese on the front and English on the back!

> I can't find any info on what model and model type means

Model means "note type", it's an old term from the Anki 1.x days. It would be useful to improve the javadoc in that method

**Comment by arooooon** [comment]
Okido reviewer context menu is fine by me, but then the text in Advanced should update as well. I will fix this in a few days and resubmit.

Hah I'm really confused about all these terms notes, card types, templates...I think I have to read the manual, never really used those features. Maybe then I can add functionality to set tts directly for each card.

**Comment by timrae** [comment]
Yeah check out ["the basics"](http://ankisrs.net/docs/manual.html#the-basics) section of the desktop manual, and also have a look through the database and the [database documentation](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure) to get a feel for how things are stored and the (relatively few I hope) differences between the terms used in the manual vs. the terms used by developers.

**Comment by arooooon** [comment]
So can we agree on having a "Select TTS" in the reviewer context menu instead of a reset function? This will show the language selector for the current card and for both question and answer. I think this would be the best solution. Maybe we don't need to reset specific decks at all?

Also I have tried finding a way to remove the old commits in this pull request, but...

**Comment by timrae** [comment]
"Select TTS language" in reviewer context menu sounds good to me. For now you'll need to pass the metadb the did and ord, though maybe we can look at changing the way it's stored later on!

You can use git rebase in interactive mode to squash your commits down to one, and then do a force push, or just create a new PR if you prefer.

**Comment by timrae** [comment]
Oops sorry I accidentally pressed the close button

**Pull request closed without merging**
