### PR TITLE
shortcut icons updated to be consistent with the UI

### LINKED ISSUE #14251: Shortcuts are not standardized according to the Google guidelines
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Long tap the app icon > Long tap each shortcut > Drop each shortcut on the home screen

### Expected behaviour

The appearance (e.g. size, background) of shortcuts is harmonize (consistent) with other apps shortcuts.

### Actual behaviour

The appearance of shortcuts isn't harmonize (consistent) with other apps shortcuts.
image
`AnkiDroid Version = 2.16.2 / Android Version = 11 / Oppo phone `

The background may be adjusted automatically in newer versions of Android, but the inconsistency of proportion still seems to remain (The inner shapes look a bit too big).
image
`2.16.2 full release from GH. Android 13 Samsung phone`
https://github.com/ankidroid/Anki-Android/issues/14246

### Debug info

```text
AnkiDroid Version = 2.16.2

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36

ACRA UUID = 5ba46727-9ddb-47f3-a810-53f66d97a89e

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

There seem to be some guidelines for app shortcuts.
image
https://developer.android.com/develop/ui/views/launch/shortcuts/best-practices
image
image

I have been trying that for a while.
image
sample (system icon is full size in 24x24dp)

image

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
Updated the shortcut icon's vector files to adhere with the new UI making it consistent with the other shortcuts in the android following the guidelines 

## Fixes
Fixes #14251

## Approach
_How does this change address the problem?_

## How Has This Been Tested?
testicons

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
The background looks bad on the OneUI Launcher (two-tone colours):

image

**Comment by criticalAY** [comment]
Anything you would like to suggest ?

**Comment by david-allison** [comment]
Find an open source app which has non-circular icons which work well and see how they manage it in the source

I'd suggest Firefox: "New tab"

**Comment by criticalAY** [comment]
I went through their codebase they are using `oval` shape as their background for the shortcut but this creates an issue with the rounds icon shortcuts here : 
image

**Comment by criticalAY** [comment]
I am making the background white as firefox is also using its own background color instead of grey and we have white and blue as our primary colors so this should be suffice and fix this issue

**Comment by david-allison** [comment]
Could we select a color for our own circles/ovals which would complement the standard white/black backgrounds which Android provides?

The "off-white" on white currently looks off, if we selected a lighter grey (or cream?), would this look better?

**Comment by criticalAY** [comment]
> 

yes I did it I made it white, we can change it

**Comment by david-allison** [comment]
I'm happy to keep it as it is now

**Review by david-allison — APPROVED** [review]
Thanks!

**Comment by criticalAY** [comment]
Google calendar also has this issue when using round icons just like Uber and I am confident that this is due to the two layers of background(oval) and foregrounds being used.

**Comment by david-allison** [comment]
Thanks so much for the thorough investigation, icons are much better!

**Review by lukstbit — APPROVED** [review]

**Pull request merged**
