### PR TITLE
Sched inheritance

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description
* Follow Anki's code base
* Avoid code duplication

## Approach
As in Anki. Having Sched inheriting SchedV2 even if it makes no sens as far as typing goes.

The commits are similar to the one in anki and mention them. You should keep as separate commit; this way if there is a bug, it's easy to check what the commit is supposed to be.

Given the limit way java work, I decided to put all schedulers in the same package. This way, the SchedV2 method ca be protected when it's required, accessed from Sched is possible, while it's still not accessible from anything which is not a scheduler

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  22
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java  4
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  22
         

Clones added
============
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  9
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5305417&bid=17364367)

**Comment by Arthur-Milchior** [comment]
I'm dealing with the scheduler code right now. Of course, if you merge a PR while I'm creating another one, conflict appears. I'll rebase it soon

**Comment by Arthur-Milchior** [comment]
Don't merge. It bugs and I'll correct it soon

**Comment by Arthur-Milchior** [comment]
Corrected

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  22
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java  4
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  22
         

Clones added
============
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  7
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5305417&bid=17364367)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  22
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  22
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java  4
         

Clones added
============
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  7
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5305417&bid=17364367)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  22
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  22
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java  4
         

Clones added
============
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  7
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5305417&bid=17364367)

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java  4
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  22
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  22
         

Clones added
============
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  8
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5305417&bid=17364367)

**Comment by Arthur-Milchior** [comment]
there was a mistake that did not appear immediately. `getDeclaredMethod` does not interact well with inheritance, so I got an error message because in `Sched`, `getDeclaredMethod` could not access a method which was inherited from SchedV2. So as advised in another PR, I replace those `getDeclaredMethod` by some lambdas.
The remaining of the PR didn't change

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           

Complexity increasing per file
==============================
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.java  4
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  22
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  22
         

Clones added
============
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java  8
- AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5305417&bid=17364367)

**Comment by mikehardy** [comment]
I appreciate them being in multiple commits - each transformation was pretty contained and seemed sensible with the exception of the one mega-change to do the inheritance. I really appreciate you helping us track libanki. These all look good to me so I'm going to put them in, it should help #5967 as you mentioned

**Comment by mikehardy** [comment]
This is released as 2.10alpha66 as soon as google is done processing it

**Pull request merged**
