### PR TITLE
Remove useless conversions

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
There are multiple conversion between types that are useless. I remove those `collection2Array` and `toPrimitive`. This require to create directly a List of Long. 

This require to add one conversion, but since it's used only in test, it's still save time

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
What's the time saving here? 

It seems that we'd get both better performance, and cleaner code from adding in `DB.queryLongArray`

**Comment by Arthur-Milchior** [comment]
I'd love a queryLongArray. However, without knowing in advance the size of the result set, I can't create an array of the correct size. 


I expect to try to move what I can to LongArrayList, the ArrayList from fastutil where `long`s are used instead of `Long`. And most of the change I did recently are preliminary work I wanted to do before introducing fastutil. In this case, using ArrayList instead of arrays means that I will easily be able to uses LongArrayList, which is essentially a `long[]` which can be resized.

Given how slow the database is, I suspect that resizing is less expensive than computing the result size first and resizing if required.

The time gain should here occur only if you try to forget a lot of things and when you switch a deck between "random" order and "added" order

**Comment by mikehardy** [comment]
@Arthur-Milchior Does this still have value, given what you now know about how the database handles Objects and what conversion savings are possible?

**Comment by Arthur-Milchior** [comment]
This still have value. I may one day be able to do better, but each time I tried I met unplanned trouble that blocked the process. So I won't tell not to merge this because one day I may be able to do better

**Comment by Arthur-Milchior** [comment]
Conflict removed

**Review by mikehardy — APPROVED** [review]
Reducing conversions is fine and if this is as far as it can go now okay
I echo David's desire for some indication of the gains
Performance PRs *should* specify the data set it was tested against plus a before/after timing. Ideally in the form of a unit test - it's possible to mark unit tests as `@Large` and then not run them normally by having a filter or similar, then we can make sure we don't accidentally regress performance - something that otherwise happens pretty frequently since performance optimizations are usually somewhat fragile

**Comment by Arthur-Milchior** [comment]
Are you saying that Large unit test check there is no performance regression automatically?
I've never heard of it. 

Should I create test just for logging time taken by the optimized action?

Seems complex, in the sens that the log will be specific to the device on which they run.

**Comment by mikehardy** [comment]
What I mean is that you can annotate tests to give the test runner a notion of the "size" / impact of a test, then using test runner arguments you can filter out really painful (large) tests, so you only run them when you want to do a regression run

If you can't design a test that shows a measurable enough impact on test harness built for the test (this is usually part of the "large" impact - test fixture construction) on most reasonable development environments it's possible to argue that the performance improvement is not worth it, although you would want to specify for those tests the general constraints / performance levels of the environment as well.

It is not that complex in my experience, it is usually just a very iterative test data generator, then a unit test that exercises the code that uses that data, making sure something hasn't gone terribly wrong

**Comment by Arthur-Milchior** [comment]
I can design the test. I just don' know how automated those test are or whether I should run them manually before and after the PR to have a specific difference to document.

**Comment by mikehardy** [comment]
Think "normal unit test with a very large test fixture and an assertion on time not correctness"
It's not "those tests" it's just way of coding a unit test. If you annotate them `@Large` they should be filtered out of CI normal runs and just run when specific performance checks should be done (manually to document, and periodically to verify)

**Pull request merged**
