### PR TITLE
NF: collectionTask creation and launch are distinct

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This is part of https://github.com/ankidroid/Anki-Android/pull/6721 

By itself, it does no actual change. However, when Collection Tasks will get created and then launched, it ensures that the value of mPreviousTask is the previously launched tasks instead of the previously created task. 

The main reason of this change are: 
* to ensure that constructors of subclass will remain small
* to avoid doing anything in constructor, appart from setting values, because otherwise I know that David would ask me to change my PR anyway

### CODE REVIEW

**Comment by mikehardy** [comment]
What I don't understand is why this is "better" constructor behavior. Previously it was just taking the value and setting it, which to me is fine. It's not doing work, it's just initializing internal state. And it seems to me the task does not have a valid internal state until this is initialized so it's actually a little more correct (to me) for it to be sent in the constructor.

I'm not strongly against the change I just don't see how it's an improvement, seems like a small step back. Is it truly needed for a CollectionTask refactor?

**Comment by Arthur-Milchior** [comment]
I realize that this PR was to small to make sens by itself. My bad.

Right now, I still believe this variable should disappear and that it makes no sens at all. That's the reason for https://github.com/ankidroid/Anki-Android/pull/6630, so it's hard for me to state whether we want it in constructor or in launch...

My goal is the bigger PR is that I want CollectionTask to be abstract and then to have one class by task. In order to avoid a lot of code duplication, I want to avoid the need to create a constructor AND a factory method in each subclass. The easy way to do it is to ensure that the constructor simply constructs using the data given and that the `launch` method deals with the general part of the initialization. 

I should note that, currently, the constructor is already public while we can't actually use it safely. So making the constructor safe to use seems to be an improvement anyway (but not one justifying this PR by itself. The big picture is really to be able to reach #6721)

**Comment by mikehardy** [comment]
Yep - I gave it approval because I do realize you are playing a long game of chess with your PRs, and I know you are going somewhere useful with it :-)

**Comment by Arthur-Milchior** [comment]
Please note that I added two more commits. This ensure that if we merge this PR and not the other one, it remains in a state which I believe to be acceptable

**Comment by Arthur-Milchior** [comment]
> Yep - I gave it approval because I do realize you are playing a long game of chess with your PRs, and I know you are going somewhere useful with it :-)

Well, I hope there is no opponent in this chess game. It makes things simpler.

More seriously, the reason I give the big PR and not only the small one is that I'd be curious about you and David's opinion about the main idea. The other small PR you merged made sens by themselves. This one only makes sens as a first step. And I don't know whether you like the general direction. Even if I can't imagine that anyone would be a fan of current CollectionTask's code.

**Comment by david-allison-1** [comment]
Awaiting discussion: https://github.com/ankidroid/Anki-Android/pull/6721#discussion_r459801182

**Comment by Arthur-Milchior** [comment]
If you like my new #6271 version, then I'll close this PR as it become useless

**Comment by david-allison-1** [comment]
Yep - the new 6721 looks better, thanks!

**Pull request closed without merging**
