### PR TITLE
make sure we don't import cards into a filtered deck

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
## Purpose / Description
Main purpose: having libanki similar to Anki's folder Anki.

## Fixes
Theoretical risks of importing card in filtered deck

## Approach
As in Anki

## How Has This Been Tested?

gradlew. And I expect it to be tested by travis here. 

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
failure in instrumented tests, you will have to have a simulator up or a device plugged in to see an instrumented tests failure when you run `./gradlew jacocoTestReport`. Neat thing about AndroidStudio, in the Analyze menu there is an analyze stack trace option and you can just paste this in there and it'll make the parts of the stack trace clickable so you can zip right to the problem

```

07:23:20 V/InstrumentationResultParser: Error in testAnki2Updates(com.ichi2.anki.tests.libanki.ImportTest):
07:23:20 V/InstrumentationResultParser: java.lang.AssertionError: expected:<0> but was:<1>
07:23:20 V/InstrumentationResultParser: at org.junit.Assert.fail(Assert.java:88)
07:23:20 V/InstrumentationResultParser: at org.junit.Assert.failNotEquals(Assert.java:834)
07:23:20 V/InstrumentationResultParser: at org.junit.Assert.assertEquals(Assert.java:645)
07:23:20 V/InstrumentationResultParser: at org.junit.Assert.assertEquals(Assert.java:631)
07:23:20 V/InstrumentationResultParser: at com.ichi2.anki.tests.libanki.ImportTest.testAnki2Updates(ImportTest.java:238)
```

**Comment by Arthur-Milchior** [comment]
Here is what I did. Please tell me what step I missed.
* Open android studio
* create two virtual device. Here it's Nexus 6 API 29. And 3.4 WGVGA API 16. (I choosed them randomly)
* Click on the green arrow to run it.
* from a terminal, starts `./gradlew jacocoTestReport`
Wait

And I don't get a single error. Neither do I have any indication that the devices were used. So I guess there is something I should do to tell gradlew where to find the devices, but I don't see what

**Comment by Arthur-Milchior** [comment]
Force push because this commit did conflict with the current state of the master branch. More precisely, it seems it did uses intNow, which was recently renamed to intTime.

**Comment by mikehardy** [comment]
Not sure what to say but I reproduce the error locally. I added your fork as a remote @Arthur-Milchior and pulled this branch, then with an emulator up (something old, like API8 or such) 

`(base) mike@kunashir:~/work/AnkiDroid/Anki-Android (MakeSureWeDontImportCardsIntoAFilteredDeck) % ./gradlew clean jacocoTestReport`

failed with the same error in CI 🤷‍♂

**Comment by mikehardy** [comment]
@Arthur-Milchior as mentioned this one still needs attention - the instrumented tests are failing at all API levels as described above

**Pull request closed without merging**
