### PR TITLE
Fix note editor not closing on save when coming from intent

### PR DESCRIPTION
**Pull request by hssm**
We were using two caller codes for the same thing, and only one of them had the logic we needed for properly handling a card add when it comes from an intent. I've merged them into one.

### CODE REVIEW

**Comment by timrae** [comment]
Do you have anything else for 2.5?

**Comment by hssm** [comment]
No that should be it. I have no other plans at the moment. This was just a minor annoyance I thought I could fix quickly. Too bad I missed the beta window by a few minutes :(

**Comment by timrae** [comment]
No worries, let's call this RC1. I'd like to release 2.5 by the end of the weekend

**Comment by hssm** [comment]
Sounds good, let's go with that plan.

**Pull request merged**
