### PR TITLE
[Kotlin Migration] StatsMetaInfo

### PR DESCRIPTION
**Pull request by codingtosh**
[Kotlin Migration] StatsMetaInfo

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]

**Review by mikehardy — CHANGES_REQUESTED** [review]
oops - lint failing on this one

**Comment by codingtosh** [comment]
@mikehardy Thanks for pointing out, might require refactoring across other files as well. Hitting the bed for now, will look into these when I'm up.

**Comment by codingtosh** [comment]
@mikehardy @david-allison-1, I've patched up #10012 and #10016 lint failures, but this one requires refactoring across other files for each of the properties here and also a little tweaking of the getters and setters. Let me know if I should do it within this conversion PR, or suppress the lint for now, add a KotlinCleanup and do it in a followup PR.

**Comment by david-allison-1** [comment]
> @mikehardy @david-allison-1, I've patched up #10012 and #10016 lint failures, but this one requires refactoring across other files for each of the properties here and also a little tweaking of the getters and setters. Let me know if I should do it within this conversion PR, or suppress the lint for now, add a KotlinCleanup and do it in a followup PR.

Sounds good!

`SuppressLint`, `KotlinCleanup`, and flag the instances of the cleanup attribute with a comment in this PR

**Comment by codingtosh** [comment]
Uploaded the patch, ptal.

> flag the instances of the cleanup attribute with a comment in this PR
A little confused here, could you please elaborate on this? Do you mean put a comment here on github mentioning the variables that need to be cleaned up? Or put the comment within the code?

**Review by david-allison-1 — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]

**Comment by david-allison-1** [comment]
> A little confused here, could you please elaborate on this? Do you mean put a comment here on github mentioning the variables that need to be cleaned up? Or put the comment within the code?

I meant on the GitHub PR, but doesn't matter - I went through manually

**Pull request merged**
