### PR TITLE
Utilize AndroidX Compat functions

### PR DESCRIPTION
**Pull request by TacoTheDank**
## Purpose / Description
Utilize compatibility functions available in AndroidX Core:

### 1st commit
- [BundleCompat](https://developer.android.com/reference/androidx/core/os/BundleCompat)
- [IntentCompat](https://developer.android.com/reference/androidx/core/content/IntentCompat)
- [ParcelCompat](https://developer.android.com/reference/androidx/core/os/ParcelCompat)

### 2nd commit
- [ShortcutInfoCompat](https://developer.android.com/reference/androidx/core/content/pm/ShortcutInfoCompat.Builder)
- [ShortcutManagerCompat](https://developer.android.com/reference/androidx/core/content/pm/ShortcutManagerCompat)
- [IconCompat](https://developer.android.com/reference/androidx/core/graphics/drawable/IconCompat)

### 3rd commit
- [ActivityCompat](https://developer.android.com/reference/androidx/core/app/ActivityCompat)

### 4th commit
- [PendingIntentCompat](https://developer.android.com/reference/androidx/core/app/PendingIntentCompat)

## How Has This Been Tested?

I built an APK and played around a bit. Things seem to work fine.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by BrayanDSO — APPROVED** [review]
LGTM. The ActivityCompat.recreate() was a surprise to me. Thanks a lot

**Review by Prince-kushwaha — COMMENTED** [review]
fix branch  conflicts

**Comment by TacoTheDank** [comment]
@Prince-kushwaha Fixed conflicts.

**Review by lukstbit — APPROVED** [review]
Great, thank you for contributing!

**Pull request merged**
