### PR TITLE
Permission exception for `hasFile`

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
It depends on #10438
It can already be merged. I plan to do similar test with MoveDirectoryContent once I know how to deal with the fact that it uses compat from compat helper

### CODE REVIEW

**Comment by david-allison** [comment]
commit 1 shouldn't be necessary, or this should be blocked on getting it merged

**Review by david-allison — APPROVED** [review]
LGTM in terms of the changes

**Comment by Arthur-Milchior** [comment]
Made a change. Now `newDirectoryStream` throw only on the given directory and not all directory. More similar to the behavior I want to simulate

**Review by david-allison — APPROVED** [review]
Still LGTM

**Review by mikehardy — APPROVED** [review]
LGTM

**Comment by mikehardy** [comment]
#5304

**Pull request merged**
