### PR TITLE
Migrating Robolectric to kotlin 

### PR DESCRIPTION
**Pull request by Arnold2381**
## Purpose / Description
Solves a part of lint[tests]: NewApi 
Mentioned https://github.com/ankidroid/Anki-Android/pull/9615#discussion_r725642046 

## Fixes
Related #9538

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Arnold2381** [comment]
@david-allison-1 please take a look

**Comment by Arnold2381** [comment]
Ok david i will give it a shot. If i cant, you can do it.

**Comment by david-allison-1** [comment]
> @david-allison-1 i was trying to figure out the solution So instead of copying the path from source root in the string can we copy the path from content root? And then obviously change this `def path = projectDir.absolutePath + "/src/main/java" + className` to `def path = projectDir.absolutePath + className` I think then our work is done!

My criteria for success would be:

* If it works for regular code
* If it works for test code

If a solution works for the above, it's a good solution, and your suggestion seems good to me!

**Comment by david-allison-1** [comment]
Blocked on #9640

Once this goes in, rebase onto master and test that my change works for you.

**Comment by Arnold2381** [comment]
Thanks!!

**Comment by david-allison-1** [comment]
can you push your changes so I can see them?

**Pull request merged**
