### PR TITLE
Adding Congrats page back to Empty deck , Completed deck and Deck with limit set. #15886

### PR DESCRIPTION
**Pull request by xenonnn4w**
## Purpose / Description
A large number of users do not like the screen so rolling back to congrats page for a while .

## Approach
https://github.com/ankidroid/Anki-Android/pull/15818
Partially reverted back the above PR .

## Fixes
* https://github.com/ankidroid/Anki-Android/issues/15886

## How Has This Been Tested?

https://github.com/ankidroid/Anki-Android/assets/139516059/197f74ec-9ca2-4e9a-9a66-0a01cf5459fe

## Pending work 
i tried to show "_The deck is empty, try adding some cards to it._" but failed to produce it . Also the The " _next learning card will be ready in .._." 

## Checklist
_Please, go through these checks before submitting the PR._

- [x ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x ] You have performed a self-review of your own code
- [ x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by SanjaySargam** [comment]
Many commits!
I suggest you to use git rebase and make it into one commit

**Comment by SanjaySargam** [comment]
Test fails
```
> Task :AnkiDroid:ktlintMainSourceSetCheck FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt:102:1 Unused import
```
Remove unused import

**Comment by xenonnn4w** [comment]
@SanjaySargam should i create a fresh PR with all of checks you suggested or work here only ?

**Comment by SanjaySargam** [comment]
Work here only.

Steps:
1. You need first undo the commits using `git reset –hard HEAD@{n}` n indicates a number of commits you want to undo. In your case, it's 7
2. Make required changes
3. git add & git commit
4. force push

**Comment by SanjaySargam** [comment]
15 commits

You did it wrong. I'm curious to know what steps you followed

**Comment by xenonnn4w** [comment]
i did it from android studio, git revert {hash of file which to revert}.

**Comment by SanjaySargam** [comment]
> 1. You need first undo the commits using `git reset –hard HEAD@{n}` n indicates a number of commits you want to undo. In your case, it's 7
> 2. Make required changes
> 3. git add & git commit
> 4. force push

You should follow this stesp

**Comment by xenonnn4w** [comment]
@SanjaySargam i'm getting this if i try to execute `git reset –hard HEAD@{n}`

https://github.com/ankidroid/Anki-Android/assets/139516059/d79a57e0-d412-4602-a160-599b6edeb41a


i also read [this](https://www.freecodecamp.org/news/git-reset-hard-how-to-reset-to-head-in-git/#:~:text=Be%20aware%20that%20the%20git,of%20the%20%2D%2Dhard%20flag.) but i did'nt helped me

**Comment by SanjaySargam** [comment]
I think the problem is in the terminal
Try this
`git reset –hard 'HEAD@{n}'`

**Comment by xenonnn4w** [comment]
> git reset –hard 'HEAD@{n}'

image
:(

**Comment by SanjaySargam** [comment]
--hard

two hyphens

**Comment by xenonnn4w** [comment]
image

**Comment by xenonnn4w** [comment]
image

**Comment by SanjaySargam** [comment]
use another terminal 
git bash

**Comment by xenonnn4w** [comment]
image
image
is this good?

**Comment by SanjaySargam** [comment]
Ok fine. 
In future, It is recommended to create a separate branch for each PR

**Comment by xenonnn4w** [comment]
Yup , i'll be aware of that from next time , for time being can i create a fresh PR {already created separate branch} to clean up these 16 commits as these giving so messy vibes .

**Comment by SanjaySargam** [comment]
> Yup , i'll be aware of that from next time , for time being can i create a fresh PR {already created separate branch} to clean up these 16 commits as these giving so messy vibes and close this one .

Ok

**Comment by xenonnn4w** [comment]
Thank you for guiding me throughout!

**Comment by david-allison** [comment]
@xenonnn4w In future, please rebase + force push your changes to your branch, rather than creating a new pull request, it makes it much easier for reviewers, and anyone diving into the code history if everything is in one place

**Comment by xenonnn4w** [comment]
@david-allison Thanks for guiding me , i learned this lesson; will not repeat this in future, though I already got it as you replied same to a previous closed PR of someone but I got that late sry :').

**Pull request closed without merging**
