### PR TITLE
Whiteboard gesture fix

### LINKED ISSUE #4259: Full screen issues
I came across these two issues today:

1. If the whiteboard is enabled and in landscape mode, the answer buttons cannot be interacted with:
screenshot_20160501-192630

2. In full screen mode, if you turn off the screen and turn it back on again, the system bars appear over the content. Showing and dismissing the system bars will fix it, so it's not a major problem. Doesn't have to be in landscape but it's a lot more evident there:
screenshot_20160501-192905

### PR DESCRIPTION
**Pull request by timrae**
I think this fixes #4259. Hopefully it hasn't introduced other errors elsewhere. I'm looking to get some feedback on how well it works and a few points below before merging.

The PR adds a 20dp margin to all edges of the whiteboard and gesture detector layers. The gesture detector layer already had this margin in the top and bottom, so I just kept the same number arbitrarily. The number seems to basically work, but according to my testing it may need to be slightly increased in some cases. 

0. I'm not sure if there's any standard for how many dp are taken up by these "system swipe zones"...? If there is an official number then we should use it, if not then I guess we could either dig into the source code, use trial and error, or change to a different and more reliable approach (not sure what that might be).

0. Obviously the PR reduces the drawable area of the whiteboard. See the screenshot below; it's probably much more noticeable on a smaller screen. Maybe we should disable the margin when fullscreen is disabled?

0. Perhaps with this change to the gesture touch layer, we could also re-enable swipe to open the navigation drawer, as this PR also effectively deals with the same issue. Again, 20dp might be too small for 100% reliable results.

whiteboard_gesture_limits

### CODE REVIEW

**Comment by hssm** [comment]
I gave it a quick test and I think it's working well.

1 - I think for now we can leave it and fine-tune it if we get any complaints about it.
2 - I don't use the whiteboard so I'm probably not the best to judge, but it seems *fine*. I'd like to think people aren't drawing on the very edges for what is meant to be a quick sketch of something since it's actually harder to position your fingers at the edges.
3 - That makes sense, I agree. By the looks of it the whiteboard also disables it so we'd need to re-enable that as well.

Seems good to merge as it is (or you can point 3 first if you want). We can fine-tune after the beta with some feedback.

**Comment by timrae** [comment]
Thanks for the comments, OK let's just put it out there and wait for feedback, I'll submit a separate PR for point 3.

**Comment by hssm** [comment]
Btw, want me to do the release notes?

**Comment by timrae** [comment]
Yes please!!!

**Comment by timrae** [comment]
> want me to do the release notes?

Thanks for doing this.

> Added new full screen mode available only with gestures (hides everything)

Fullscreen mode with answer buttons and topbar hidden was added in v2.5 actually!

**Comment by hssm** [comment]
Oops, I guess I lost track of what we'd done with it. Weren't we still showing the app bar in 2.5?

**Comment by timrae** [comment]
I'm pretty sure it was working almost the same as it was now thanks to some hacks by the material drawer author, but with #3867.

**Comment by timrae** [comment]
> I'm pretty sure it was working almost the same as it was now

Well not really the same... Now the action bar appears over the top of the flashcard (translucently), whereas before the whole thing would resize.

**Comment by hssm** [comment]
Yeah I remember now. I'll edit the release notes.

**Comment by timrae** [comment]
I guess we should also mention that the size of the whiteboard and gesture
detection areas has been reduced

**Pull request merged**
