### PR TITLE
Updated strings from Crowdin 20210924

### PR DESCRIPTION
**Pull request by mikehardy**
Non-Standard I18N sync - includes the new Sardinian translation

Related #9550

### CODE REVIEW

**Comment by mikehardy** [comment]
Fixed the format string error in Sardinian webview init message, we'll resync in a bit

**Comment by david-allison-1** [comment]
> Fixed the format string error in Sardinian webview init message, we'll resync in a bit

Just to confirm: there were 5 issues in the lint

**Comment by david-allison-1** [comment]
Updated: https://crowdin.com/translate/ankidroid/8167/en-sc?filter=basic&value=0#q=sync_error_invalid_sync_server

**Comment by david-allison-1** [comment]
Builds locally, kicking off another

**Comment by mikehardy** [comment]
:facepalm: I only saw the one explicit lint error and missed that the number "5" was showing, thanks for catching that.
I was actually showing 13 errors on ubuntu locally with `./gradlew lint` which is sort of unexpected, and I'm going to look in to having more (some reasonable number) of messages displayed in the action output if possible...

**Comment by david-allison-1** [comment]
`gradlew lintAmazonRelease` was clear for me, but I'm having build issues, interesting

**Comment by david-allison-1** [comment]
A lint failure should publish the HTML report as an artifact

**Comment by mikehardy** [comment]
I've got no local build errors and it runs locally for me on a quick click-around so I think we're :100: here

**Comment by david-allison-1** [comment]
Works for me after and Android Studio restart

**Pull request merged**
