### PR TITLE
Migrate to kotlin

### PR DESCRIPTION
**Pull request by Arnold2381**
## Purpose / Description
Kotlin Migration.

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM - I restarted the emulator tests, they shouldn't be affected by this anyway, it's our typical flaky "process crashed" over there

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
This needs to be rebased onto master

**Comment by Arnold2381** [comment]
Sorry re requested review from Mike again! By mistake.

**Review by david-allison-1 — APPROVED** [review]
LGTM. Pending CI

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
