### PR TITLE
[KotlinCleanup] CardBrowser 

### PR DESCRIPTION
**Pull request by oyeraghib**
## Purpose / Description
[KotlinCleanup] CardBrowser

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
> Task :AnkiDroid:lintPlayDebug FAILED
218
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:137: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
219
    lateinit var mDeckSpinnerSelection: DeckSpinnerSelection
220
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
221
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:139: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
222
    @VisibleForTesting

**Comment by oyeraghib** [comment]
> > Task :AnkiDroid:lintPlayDebug FAILED
> > 218
> > /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:137: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
> > 219
> > lateinit var mDeckSpinnerSelection: DeckSpinnerSelection
> > 220
> > ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > 221
> > /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt:139: Error: Variable name should not use field prefixes. [VariableNamingDetector from com.ichi2.anki:lint-rules]
> > 222
> > @VisibleForTesting

It required changes in one more file : `FinderTest.java`
So I updated both

**Comment by Arthur-Milchior** [comment]
I'm fine with you updating both. I'd still love if you could ensure it passes linting and is accetped by github actions

**Comment by oyeraghib** [comment]
@Arthur-Milchior This is showing some conflicts and seems like I cannot resolve them myself as GitHub says.

**Comment by Arthur-Milchior** [comment]
Actually, on your computer, you can do 
```
git fetch ankidroid
git pull ankidroid/main --rebase
```
(assuming the name of ankidroid's remote is "ankidroid" in your git system)
This will ensure that you fetch latest update from our github, then apply all of your commit on top of the current main branch. This way, you'll be presented with each conflict one by one and can resolve individually.

**Comment by Arthur-Milchior** [comment]
Any news @oyeraghib ? Don’t hesitate to ask more question on discord if you need help.

**Comment by oyeraghib** [comment]
> Any news @oyeraghib ? Don’t hesitate to ask more question on discord if you need help.

Oh! Actually I forget to update on this one. Making it as a draft until I rebase it and then I will request you for the review. Thanks for reminding.

**Comment by oyeraghib** [comment]
@Arthur-Milchior Please review if possible.

**Review by mikehardy — APPROVED** [review]
Nice! Thank you and thanks for your patience on review+merge

**Pull request merged**
