### PR TITLE
NF: Use col's time instead of `new SystemTime`

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
There remained a few use of real time in the code. I thought about them while reviewing https://github.com/ankidroid/Anki-Android/pull/6956 by thinking what way the use could still fail to use time in a proper way

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
On discord, you mentionned "future proofing", by ensuring that the current time is never used in the code by future devs. This lead to the question of present proofing. I don't see how I could ensure that such a mistake is not still present. As you can guess, I've not read the entire codebase, but only searched for methods I already know we use, and methods I find on the way.

I won't read through the entire codebase anyway

**Comment by mikehardy** [comment]
Ideally a merge of #6956 would show immediately - via build failure in Travis - when/if there were still instances in the codebase

**Comment by Arthur-Milchior** [comment]
Unless I'm wrong, it will only detect the methods listed by David. It won't show any other methods. And I would suspect that java as far too many methods to get current time/date to be reasonable to look for all of them in lint

**Review by david-allison-1 — APPROVED** [review]
LGTM

**Pull request merged**
