### PR TITLE
Undo action

### PR DESCRIPTION
**Pull request by criticalAY**
## Purpose / Description
action undo was not working in StudyOptionFragment in relation to:: [Bug] an invalid "Undo" button appears on Deck Overview screen #12277

## Fixes
Removed the action_undo option from the tool bar in the main fragment

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Hi, in future, please rebase + force push your branches rather than closing them. It gives us loads of notifications, and people looking back at the history of a change lose context

**Comment by criticalAY** [comment]
ok will keep that in mind in future

**Comment by criticalAY** [comment]
Also, I am getting an error JAVA_HOME... when I am trying to commit something now. I pushed earlier too but did not get any such error like could you please help me with that? I have already checked my JAVA JDK version also asked this thing on discord but got no response

**Comment by david-allison** [comment]
If you're having an issue, you'll need to provide enough context for someone to look into.

`Also, I am getting an error JAVA_HOME` isn't enough to understand your problem.

**Comment by criticalAY** [comment]
can i share the issue on discord?

**Comment by david-allison** [comment]
That would be sensible. If it's an issue that others will have, it'd be best to write up an issue on GitHub after its been resolved. If it's specific to you, Discord will work.

**Pull request closed without merging**
