### PR TITLE
Copy-edit the github release text

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

The previous release text was sort of a "wall of text" and did not properly signal to the different types of users we send to the releases page what they would be interested in

## Approach
Just tightened up the wording

Example of old text:

----

The builds with letter codes below (A, B, etc) are universal parallel builds. They will install side-by-side with the main APK build for testing, or to connect to a different AnkiWeb account in combination with changing the storage directory in preferences. If you install the main APK below, you should install the version matching your CPU instruction set. If you do not know that information, there are many guides on finding it, for example https://www.howtogeek.com/339665/how-to-find-your-android-devices-info-for-correct-apk-downloads/

----

New text:

----

**For regular users:**<br/><br/>Install the main APK below, trying the 'universal' build first for new installs. If it refuses to install and run correctly or you have previously installed from the Play Store, you must pick the APK that matches CPU instruction set for your device.<br/><br/>This will be arm64-v8a for most phones from the last few years but [here is a guide to help you choose](https://www.howtogeek.com/339665/how-to-find-your-android-devices-info-for-correct-apk-downloads/)<br/><br/><br/>**For testers and multiple profiles users:**<br/><br/>The builds with letter codes below (A, B, etc) are universal parallel builds. They will install side-by-side with the main APK for testing, or to connect to a different AnkiWeb account in combination with changing the storage directory in preferences

----

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
@david-allison-1 this is many people's first time seeing the app so I tightened the text up and a second pair of eyes might be able to make it even better, so let me know if you have any word-smithing ideas before I merge

**Comment by mikehardy** [comment]
Hmm - didn't realize we were taking crashes from people doing the wrong arch. I'll recommend the universal at the start then with a follow-on that if it refuses to install over an existing installation you need to select the correct build for your CPU etc etc ?

The mere mention of modems triggers the audio memory of hearing the 14.4 handshake

**Comment by david-allison-1** [comment]
Ah - assumed you were aware - https://github.com/ankidroid/Anki-Android/issues/6483 and the like. It's our biggest crasher in most of the alphas (and 100% of 2.12beta4)

Seems reasonable.

**Comment by mikehardy** [comment]
I updated the text I'm contemplating, can you re-read above? Or see a live version of the current text https://github.com/ankidroid/Anki-Android/releases/tag/v2.12.0beta4

**Comment by mikehardy** [comment]
Great, thanks for the review on that, text is easy technically but really benefits from the collaboration

**Pull request merged**
