### PR TITLE
Allow unbury of non-selected deck

### LINKED ISSUE #6200: "Unbury" doesn't work
1. Long tapping on any deck in the deck list
2. Tapping "unbury"
3. That operation doesn't work at all or cancel the wrong number of bury cards

Also;

1. Tapping on "custom study session"
2. Tapping on ... menu on the top of the screen and then tap on "option" (in Japanese オプション)
3. In the "search conditions of filter" (in Japanese フィルターの抽出条件)
4. Putting "is:buried" in the box
5. That operation doesn't work at all

But;

1. Tapping on "card browser" in the drawer menu
2. Tapping on the magnifier icon on the top of the screen
3. Putting "is:buried" in the box
4. That operation seems to work properly

Also, buried cards turn into unbried automatically tomorrow. (normal function)

All the operation above worked properly before version 2.9.7.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.10.2

Android Version = 9

ACRA UUID = 1c3742fa-517d-4191-a140-6c1031b0a391

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
You can unbury cards via the Deck Picker's long-press menu, which does not change the selection.

This goes via method: `unburyCardsForDeck(DeckIds)`, which is not the active deck, our code assumed we wanted to unbury the selected deck

## Fixes
Fixes #6200

## Approach
Partial revert of e0b5f7bd357978a4ab45faddeb1a6e2045719ab0

## How Has This Been Tested?

Unit tests

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5551117&bid=18201192)

**Comment by mikehardy** [comment]
Marking this for a pick to 2.10 - doesn't seem to be any reason not to? (no dependent unit test infrastructure even I don't think)

**Comment by david-allison-1** [comment]
Hmm... confirm beforehand with the unit test infrastructure. There are a few methods that I moved to `RobolectricTest` in dafa65473afa4550845d15bcf0e898b77ea90dcf

**Comment by david-allison-1** [comment]
I'm fine to split this out into one PR for the fix, and one for the test?

**Comment by mikehardy** [comment]
Actually if you just gave me two commits I could pick the fix but not the test. Good catch!

**Comment by david-allison-1** [comment]
> Actually if you just gave me two commits I could pick the fix but not the test. Good catch!

Done - was how the commit was originally, but I feel there's value in including tests with the commit that is fixed

**Comment by mikehardy** [comment]
Generally agreed on that - TDD style maybe even test first separate! - but I appreciate the split thank you!

**Comment by david-allison-1** [comment]
> Generally agreed on that - TDD style maybe even test first separate! - but I appreciate the split thank you!

I wouldn't want to that personally - risks broken master builds if you don't squash/rebase before merging

**Comment by mikehardy** [comment]
Is an unexposed bug not already a broken build, just one that isn't visible?
And here, the sound of one hand clapping: :hand:

**Comment by mikehardy** [comment]
Less tangentially, I actually don't see the two separate commits here?

**Comment by david-allison-1** [comment]
GitHub timed out when pushing... fixed

**Comment by timrae** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- AnkiDroid/src/test/java/com/ichi2/libanki/sched/SchedTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/timrae/Anki-Android/pullRequest?prid=5551117&bid=18201192)

**Comment by mikehardy** [comment]
going out in 2.10.3beta2 and will be in 2.11alpha6 - I needed the SchedTest and deck refactor for a different pick so after all that I ended up picking the dependencies as well - they were all clean. So I think our tests are still largely coherent between release-2.10 and master though that isn't a forward promise

**Pull request merged**
