### PR TITLE
fix build: conflicted conversion of CardBrowser

### PR DESCRIPTION
**Pull request by david-allison**
## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by krmanik — APPROVED** [review]

**Comment by krmanik** [comment]
`Squash merge` or `Rebase and merge`?

**Review by mikehardy — APPROVED** [review]
Sorry I wasn't running the full CI suite locally to get post-merge checks, I was counting on the CI completion per-PR from the point where they branched - wish they would allow us to use their "merge PRs as a train" feature - going to look into that again

**Comment by krmanik** [comment]
> Doesn't matter if there's only one commit

Okay, Thanks

**Comment by mikehardy** [comment]
I think I've found all the affected PRs and notified folks, also I pasted the commit reference of this fix into the commit that broke, for future git bisect people

**Pull request merged**
