### PR TITLE
test: ensure constant uniqueness

### PR DESCRIPTION
**Pull request by WPum**
## Purpose / Description
Resolves `@NeedsTest("constant values are unique")`

## Approach
Use Kotlin reflection to check uniqueness for all `public const` values in objects.

## How Has This Been Tested?

1. Create a `public const` property with duplicate values, say `const val TEST = "syncMedia"` in `UniqueWorkNames`
2. The unit test fails

## Learning (optional, can help others)
https://youtrack.jetbrains.com/issue/KT-55449/Reflection-IllegalArgumentException-Callable-expects-0-arguments-but-1-were-provided-on-getting-const-property-value-of-Object

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by BrayanDSO — APPROVED** [review]
Really nice. Thanks

**Review by lukstbit — APPROVED** [review]
Looks good, left two nitpicks to fix and then we can merge this.

**Comment by WPum** [comment]
Fixed.

**Review by david-allison — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
