### PR TITLE
Remove custom font feature

### LINKED ISSUE #14343: Remove Custom Fonts setting
I mean the `Fonts` setting at the `Appearance` section. It was added ˜11 years ago and have not got much care since then. 

Currently it needs some work because the AnkiDroid directory is not accessible by common means in Android 10+ devices with the play store version, because of scoped storage. This means that the user cannot add a custom font to use it.

Also, the default font options provided by the preferences (Open sans light, bold, etc) do not work at all in the Samsung phones I have tested, although I recall them working in the emulator.

Additionally, the default way to use custom fonts is by embedding them in the media files so the font can be reused along all of the Anki ecosystem.

Probably the goal of the setting was to fix possible issues with languages with many characters if the system font could not handle them all, like chinese. Or maybe because someone just wanted to use a different font and then implemented the feature. Since Android has evolved a lot since then, most likely the feature is not necessary nowadays and should be removed

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description

Removes the custom font settings along with the code around them. Mostly simple deleted code, but review more carefully the changes in `ReviewerCustomFonts`.

## Fixes
Fixes #14343 

## How Has This Been Tested?

Ran the tests.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by BrayanDSO — APPROVED** [review]
The smell of cutting code is always lovely. Glad to see this gone

**Review by dae — APPROVED** [review]
Assuming you've tested it, LGTM.

**Comment by dae** [comment]
Sorry, I think I should have done something with strings first. :-(

**Comment by dae** [comment]
@mikehardy do you want me to revert this for now?

**Comment by lukstbit** [comment]
Don't revert I'll work through the strings tomorrow.

**Pull request merged**
