### PR TITLE
Change GestureProcessor.java to Kotlin

### PR DESCRIPTION
**Pull request by DeFuex**
## Purpose / Description
Just a change from Java to Kotlin

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
Hi, thanks for the PR. 

Currently this removes the history from the file. Could you follow the migration procedure as seen in this PR: https://github.com/ankidroid/Anki-Android/pull/9495 so the file retains both its history, and allows each commit to build.

Thanks!

**Comment by DeFuex** [comment]
@david-allison-1 Just that i know what's going on. The migration policy is renaming the existing file instead of just deleting it and using the new Kotlin class?

**Comment by mikehardy** [comment]
@DeFuex you can see the full context of why we migrate them the way we do, and how we do it here https://github.com/ankidroid/Anki-Android/pull/9480 - there's a gradle script to do it for you at this point even

**Comment by DeFuex** [comment]
@mikehardy Oh, just read this, but i guess `git mv` should be fine to be used? :)

**Pull request closed without merging**
