### PR TITLE
Dependency updates 20240830

### PR DESCRIPTION
**Pull request by mikehardy**
Fairly standard - requires new Android Studio though

Tested locally macOS / JDK21 / emulator API35 with 16kb page size, worked fine

### CODE REVIEW

**Comment by mikehardy** [comment]
Squash merge, as labeled, if someone gets this before I turn attention back to it 🙇

**Comment by david-allison** [comment]
Flaky test: 

* https://github.com/ankidroid/Anki-Android/actions/runs/10640871215/job/29501280821?pr=17004
* https://github.com/ankidroid/Anki-Android/issues/17010

**Comment by mikehardy** [comment]
I don't think we need to block this on a flaky test, I believe the flaky is in main? and it's tracked as an issue now (thank you!)

**Comment by david-allison** [comment]
I intended to merge once CI passed, cheers!

**Comment by mikehardy** [comment]
Great, for bonus points, CI passed after I rebased the whole queue on to current main so it's similar valid CI check to merge-queue. 🚂

**Pull request merged**
