### PR TITLE
Calculate scheduler limits for sync using AnkiWeb limit

### LINKED ISSUE #5666: Collection in a state where it's in an inconsistent state on every sync
###### Reproduction Steps

1. Make any change in Ankidroid
1. Perform sync from Ankidroid

###### Expected Result

Sync completes without conflicts.

###### Actual Result

Sync seems to proceed as normal - data is uploaded and downloaded - and the Ankidroid complains that the local collection is inconsistent. Making changes to the collection on the desktop doesn't result in inconsistencies on the desktop side.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

```
AnkiDroid Version = 2.10alpha17

Android Version = 10

ACRA UUID = b6658709-db1a-4b5b-a883-36f015a21153
```
###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

### LINKED ISSUE #5672: Collection deemed to be inconsistent when current deck has more than a thousand review
###### Reproduction Steps

1. Have a collection with a deck D with more than a thousand review due
2. Select D.
3. Sync

###### Expected Result
Being able to synchronize

###### Actual Result
See an error message stating that your collection is inconsistent.

At step 2, if you select another deck, with a small number of due review, then everything is allright.

###### Debug info
I'll update later when I've got my phone with me. I'm using the latest beta from the store.

###### Research
Asking the computer to check the collection and then doing a full sync from computer to ankidroid does not solve the problem.

According to Damien Elmes, https://anki.tenderapp.com/discussions/ankiweb/4273-collection-keeps-being-found-as-inconsistent the sync fails because «sanityCheck endpoint returns the differing counts in the JSON reply. The review due counts appear to differ.» 
This seems extremely consistent with the fact that numbers in anki are limited to 1000, while ankidroid shows arbitrarily great numbers. 

I'd try to fix it myself, but there is already a lot of PR I created which are still pending, so I guess I'll wait to see what happens with code I already submitted before writting more.

*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

Seems similar to https://github.com/ankidroid/Anki-Android/issues/5666

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
We modified `mReportLimit` in #5326 to allow a user to see how many cards they had if there were more than 1000 in a queue.

This had an impact on calculating the number of cards in the current deck, which is required for a sync to ensure that the server and client are consistent.

This caused an inconsistency (as we calculate the proper value), and this meant that a full sync needed to occur if a dynamic deck with over 1000 cards in a queue was selected or a subdeck of the selected deck.

## Fixes
Fixes #5666 
Fixes #5672

## Approach

This fixes the issue by instantiating a new scheduler with the correct `mReportLimit` for calculating the number of cards in the selected deck.

## How Has This Been Tested?

I have a test collection (SchedV1).

1. Synced with normal deck from Android - worked.
2. On Desktop - filled dynamic deck with ~1700 cards on AnkiDesktop - `self.sched.counts() - (7, 0, 1000)`.
3. Sync to server and sync from Android
4. Review a card
5. Sync - Failure

---

After applying the fix, the sync worked, also works with a regular deck.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by david-allison-1** [comment]
Before we merge, could I note that we do work (relating to day cutoffs) in the constructor of `sched`. I've deemed this to be safe, but a second pair of eyes would be useful.

**Comment by mikehardy** [comment]
I'm sure that's unimportant and won't result in any problems ever #5831 #5380 :wink: - I'll double-check then merge if I see nothing or raise a comment if I notice something. Thanks for the headsup

**Comment by david-allison-1** [comment]
> I'm sure that's unimportant and won't result in any problems ever #5831 #5380 😉 - I'll double-check then merge if I see nothing or raise a comment if I notice something. Thanks for the headsup

"new day starts at" is always going to be nasty 😉. This is just performing the cutoff check/operation, which is the same as `sched.reset()`, performed a few lines before.

**Comment by mikehardy** [comment]
> Before we merge, could I note that we do work (relating to day cutoffs) in the constructor of `sched`. I've deemed this to be safe, but a second pair of eyes would be useful.

So, as we create the new schedulers in order to do the sync with an injected non-default limit, we may be unburying things and dirtying decks etc based on day cutoff as a side effect. That does seem safe in so far as it's bound to happen eventually and is also idempotent + correct for whatever the time of day is. Does seem fine to me.

Is that how you read it?

**Comment by david-allison-1** [comment]
> > Before we merge, could I note that we do work (relating to day cutoffs) in the constructor of `sched`. I've deemed this to be safe, but a second pair of eyes would be useful.
> 
> So, as we create the new schedulers in order to do the sync with an injected non-default limit, we may be unburying things and dirtying decks etc based on day cutoff as a side effect. That does seem safe in so far as it's bound to happen eventually and is also idempotent + correct for whatever the time of day is. Does seem fine to me.
> 
> Is that how you read it?

Precisely, but it was worth getting a second pair of eyes over it.

**Comment by mikehardy** [comment]
2.10alpha55 is out with the fix, as soon as Google is done processing it and starts delivery...

**Comment by mikehardy** [comment]
released in 2.9.6beta4

**Pull request merged**
