### PR TITLE
Upgrade ankidroid backend to 0.1.4

### LINKED ISSUE #8178: [Bug] Rust - Check Database OOM
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/2811a70b-bccf-4ad4-9b94-3386ac6d4196

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 169408 byte allocation with 118096 free bytes and 115KB until OOM, target footprint 536870912, growth limit 536870912
at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
at com.google.protobuf.Utf8$SafeProcessor.decodeUtf8(Utf8.java:20)
at com.google.protobuf.Utf8.decodeUtf8(Utf8.java:2)
at com.google.protobuf.CodedInputStream$ArrayDecoder.readStringRequireUtf8(CodedInputStream.java:3)
at BackendProto.Sqlite$SqlValue.<init>(Sqlite.java:20)
at BackendProto.Sqlite$SqlValue.<init>(Sqlite.java:1)
at BackendProto.Sqlite$SqlValue$1.parsePartialFrom(Sqlite.java:2)
at BackendProto.Sqlite$SqlValue$1.parsePartialFrom(Sqlite.java:1)
at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:14)
at BackendProto.Sqlite$Row.<init>(Sqlite.java:15)
at BackendProto.Sqlite$Row.<init>(Sqlite.java:1)
at BackendProto.Sqlite$Row$1.parsePartialFrom(Sqlite.java:2)
at BackendProto.Sqlite$Row$1.parsePartialFrom(Sqlite.java:1)
at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:14)
at BackendProto.Sqlite$DBResult.<init>(Sqlite.java:15)
at BackendProto.Sqlite$DBResult.<init>(Sqlite.java:1)
at BackendProto.Sqlite$DBResult$1.parsePartialFrom(Sqlite.java:2)
at BackendProto.Sqlite$DBResult$1.parsePartialFrom(Sqlite.java:1)
at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:14)
at BackendProto.Sqlite$DBResponse.<init>(Sqlite.java:16)
at BackendProto.Sqlite$DBResponse.<init>(Sqlite.java:1)
at BackendProto.Sqlite$DBResponse$1.parsePartialFrom(Sqlite.java:2)
at BackendProto.Sqlite$DBResponse$1.parsePartialFrom(Sqlite.java:1)
at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:18)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:24)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:26)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:27)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:9)
at BackendProto.Sqlite$DBResponse.parseFrom(Sqlite.java:5)
at net.ankiweb.rsdroid.BackendV1Impl.getPage(BackendV1Impl.java:4)
at net.ankiweb.rsdroid.BackendMutex.getPage(BackendMutex.java:2)
at net.ankiweb.rsdroid.database.Session.getPage(Session.java:1)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.getNextPage(StreamingProtobufSQLiteCursor.java:3)
at net.ankiweb.rsdroid.database.StreamingProtobufSQLiteCursor.moveToNext(StreamingProtobufSQLiteCursor.java:2)
at com.ichi2.libanki.Collection._fieldData(Collection.java:3)
at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:5)
at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:2)
at com.ichi2.libanki.Collection.updateFieldCache(Collection.java:16)
at com.ichi2.libanki.Collection.q(Unknown Source:0)
at com.ichi2.libanki.q.apply(Unknown Source:4)
at com.ichi2.libanki.Collection.lambda$fixIntegrity$1(Collection.java:2)
at com.ichi2.libanki.Collection.j(Unknown Source:0)
at com.ichi2.libanki.g.consume(Unknown Source:8)
at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:27)
at com.ichi2.async.CollectionTask$CheckDatabase.task(CollectionTask.java:5)
at com.ichi2.async.CollectionTask$CheckDatabase.task(CollectionTask.java:1)
at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:14)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more
```

Initial Thoughts

* Better handling of Rust DB Streaming 
  * Maybe: instead of 1000 rows, determine how to count the size of a protobuf as we stream it into a byte array, and stop at a certain point
   * Or vary the number of rows: since we're getting FieldData, rows can be arbitrarily large
   * Maybe this isn't a blocker if we can "fail forward" and move this to Rust in V2.16.X.
* https://github.com/david-allison-1/Anki-Android-Backend/issues/14 - provide a lambda to the backend which contains "Are we low on/OOM"
* Maybe catch the OOM here and use a fallback which won't fail? This will be slow but better than crashing.

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description

Dependency upgrade to fix database related bugs

* rsdroid-testing: diagnose file not found error
* fix OOM via memory limit on DB row results
* Add Java-based exceptions for rust errors

## Fixes
Fixes #8178 (hopefully)
Makes a start on #8075

## How Has This Been Tested?

* Ran unit tests
* Slight test on my phone
* ⚠️ We need some form of performance regression cover - maybe as an issue, maybe I need to write something here. I do feel this will be slightly slower than the previous implementation, I'm not sure if we /need/ to tackle it here, but we need to be aware

## Learning
https://github.com/david-allison-1/Anki-Android-Backend/compare/0.1.2...0.1.4

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Ha - so much embodied in one little digit change
I felt the same way but probably only 10% as much when doing the google-analytics-java dependency work - slaving away over on the side and then the PR is a version bump. This is huge though!

**Comment by david-allison-1** [comment]
> Ha - so much embodied in one little digit change
> I felt the same way but probably only 10% as much when doing the google-analytics-java dependency work - slaving away over on the side and then the PR is a version bump. This is huge though!

Could we/I/reviewers do a quick check with the unit test times before a merge? Just want to ensure it's not /massively/ slower

**Comment by mikehardy** [comment]
on it - I'm watching actions etc and in merge mode for a release as soon as everything is clear, I'll check times before merge

**Comment by mikehardy** [comment]
Pretty consistently from 8:45ish to 9:00ish before for the actual unit test execution phase


8:13 on this PR doing actual test execution
7:15ish on main branch runs doing actual test execution before

So maybe a 15% or so reduction it that difference is reproducible.

OOM is not okay and this structural change is vital, it may be there are optimizations to make but I'll take 15% for correctness, especially as the first take on a structural change

@david-allison-1 thoughts?

**Comment by mikehardy** [comment]
emulator test timings too unstable to be useful. I thought unit test timings were quite stable though, with possible exception that the code for comparison (this PR) only has one run, but it was definitely different than the recent runs which were all very tightly clustered

**Comment by mikehardy** [comment]
I'm in a merge-y mood, going to merge this as 15% for correctness does not meet definition of "massive" to me. Notable, but not massive. Iterate and improve :rocket:

**Comment by mikehardy** [comment]
7:47 on the actual test execution on the merge, so timing a bit unstable, and it performed significantly better on main branch on merge. They may be some gradle caching affecting this run to run, now that it has landed we can get some more post-merge timing.

**Pull request merged**
