### PR TITLE
Mark reviewer custom scheduler test as flaky

### PR DESCRIPTION
**Pull request by mikehardy**
This was a rabbit-hole.

Given: gradle has this new [test-fixtures](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures) dependency that is in between "main", "test", and "androidTest", but Kotlin doesn't support it yet: https://youtrack.jetbrains.com/issue/KT-50667

And Given: the only other way you can share code between test and androidTest without shipping it in main, is by making a new module that they both depend on: https://blog.danlew.net/2022/08/16/sharing-code-between-test-modules/

And Given: we are implemented in Kotlin, 

Then: I have made a new testlib module, and made test and androidTest depend on it

Then: I moved the flaky test rule there

Then: I annotated the last current seriously flaky test (which was in androidTest, not test) as flaky

Learning: if you have one module depending on another module, and one module has flavors but the other doesn't, gradle cannot figure out how to correctly disambiguate the dependency with flavors, since all the flavors match with the only difference being a flavor attribute that the other module doesn't care about. The solution is to have equal flavor attributes on both sides of the dependency, then gradle automatically lines them up and disambiguates.

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
`testCustomSchedulerWithCustomData` is also flaky

**Comment by david-allison** [comment]
Aside: I'm /REALLY/ happy we're moving to a shared library for tests.

Optionally there is a `@DuplicatedCode` annotation, which contains other classes which are in use between both `androidTest` and `test`

If we have time here, we can also move these across

If we don't, we should add a https://github.com/ankidroid/Anki-Android/labels/Good%20First%20Issue%21 to do so

**Comment by david-allison** [comment]
```
* What went wrong:
Execution failed for task ':testlib:mergePlayDebugAndroidTestJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/DEPENDENCIES' from inputs:
      - /Users/runner/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.5.11/f6d42fee5110c227bac18a550a297e028f2fb21a/httpclient-4.5.11.jar
      - /Users/runner/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.4.13/853b96d3afbb7bf8cc303fe27ee96836a10c[183](https://github.com/ankidroid/Anki-Android/actions/runs/7745429054/job/21121396942?pr=15381#step:7:184)4/httpcore-4.4.13.jar
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/8.2/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information
```

**Comment by mikehardy** [comment]
Huh - was working locally but perhaps something was cached.

I may have actually marked the wrong one! Will check and either move the mark or add the mark for custom scheduler - it was the intended target I think

I have no time to move other items or de-duplicate, this was already far over budget w.r.t. time as it was intended to just be an optimization on merge management and turned into a mini-odyssey on getting the thing to build. Can't shave yaks right now alas

**Comment by mikehardy** [comment]
- added packaging options in testlib that copies what is in `:AnkiDroid` so that file won't conflict
- marked the second test (there were two!) that uses custom scheduler as flaky

**Review by david-allison — APPROVED** [review]
Great step forward!

**Review by BrayanDSO — APPROVED** [review]

**Comment by david-allison** [comment]
```
com.ichi2.anki.ReviewerTest > testCustomSchedulerWithRuntimeError[test(AVD) - 11] FAILED 
	java.lang.AssertionError: View assertion was not true within 30000 milliseconds
	at org.junit.Assert.fail(Assert.java:89)
E0201 20:37:37.824023 bcf7000 FrameBuffer.cpp:3765] Failed to find ColorBuffer:314

com.ichi2.anki.ReviewerTest > testCustomSchedulerWithCustomData[test(AVD) - 11] FAILED 
	java.lang.AssertionError: View assertion was not true within 30000 milliseconds
	at org.junit.Assert.fail(Assert.java:89)
```

??

**Comment by mikehardy** [comment]
@david-allison I must be fundamentally misunderstanding something, really confused

perhaps androidTest is missing the env var CI 🤔 probably

**Comment by mikehardy** [comment]
AdaptionUtil.isUserATestClient as an addition to the CI check method - what do you think?

**Comment by david-allison** [comment]
We're using `Sytem.getEnv("CI")`, we probably want `BuildConfig.CI`

**Pull request merged**
