### PR TITLE
Collection task split

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This is a second try of a project I care a lot about: removing TaskData and improving typing of tasks. I listened to what seemed to be the biggest remark of the previous try: moving the code a lot. In this one, I simply add each function in a small class which extends an interface `Task`. CollectionTask execute a task. `LaunchCollectionTask` ensures that the listener accepts a subtype of the value sent by the task. 

Most of the line noted as changed are only changed because this required to add an extra level of indentation, since functions moved inside of classes.

I see three main advantages in this PR. First, it improves typing. It's now really easy to see the type of data sent from task to listener, instead of having to guess what is in the task data, and if it's an array object, what object they are.
The second is that casting from Object to something always require time in order to check that the cast is valid. This will make all process using the array of object slightly quicker.

EDIT: third advantage.
`CollectionTask` is quite complex. The type indicates that the task can only send progress data, check for cancellation and do nothing else with `CollectionTask`. Hopefully, reducing the scope will allow for smoother transition from async task to a non deprecated background manager

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Any idea what means "An error occurred while generating the build script." in the mac build ? Restarting does not help

**Comment by Arthur-Milchior** [comment]
Rebased. `./gradlew jacocoTestReport  ` succeed

**Comment by mikehardy** [comment]
This one took a bunch of conflicts from others merged just now - I was inclined to review + merge if you can patch it up. #7046 and #7685 appear related, may be easier to put them in one PR so they do not conflict with each other

**Comment by Arthur-Milchior** [comment]
Rebased.
Since I'll need to resolve conflict in both PR, I'll prefer to do it when one is merged. So that if there is any problem in the other, it does not block the first. Anyway, it'll be the same amount of work for me

**Comment by mikehardy** [comment]
Okay, this one is now thoroughly conflicted from the other recent merges :-). I have read it a couple times though, inclined to merge after patching up conflicts

**Comment by Arthur-Milchior** [comment]
Rebased

**Review by mikehardy — APPROVED** [review]
Alright, let's get this typing in there

**Pull request merged**
