### PR TITLE
Revert "Remove possibility of TagsDialog NullPointerException"

### PR DESCRIPTION
**Pull request by david-allison-1**
Reverts ankidroid/Anki-Android#6175

The above commit is a bugfix for an issue which appeared to be from automated testing.

In doing so, this adds a parameter to the fragment constructor, which I didn't realise shouldn't be done.

----

> All `Fragment` classes you create **must** have a public, no-arg constructor.

Saw a crash on ACRA due to "Could not find Fragment constructor"

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/990db3a6-6ea8-44da-96dd-0e6e41db7769

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.NoteEditor}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.ichi2.anki.dialogs.TagsDialog: could not find Fragment constructor
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5527)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5418)
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.ichi2.anki.dialogs.TagsDialog: could not find Fragment constructor
at androidx.fragment.app.Fragment.instantiate(Fragment.java:8)
at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:1)
at androidx.fragment.app.FragmentManagerImpl$6.instantiate(FragmentManagerImpl.java:1)
at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:4)
at androidx.fragment.app.FragmentManagerImpl.restoreSaveState(FragmentManagerImpl.java:27)
at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:2)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:3)
at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:4)
at com.ichi2.anki.AnkiActivity.onCreate(AnkiActivity.java:4)
at com.ichi2.anki.NoteEditor.onCreate(NoteEditor.java:2)
at android.app.Activity.performCreate(Activity.java:7458)
at android.app.Activity.performCreate(Activity.java:7448)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
... 13 more
Caused by: java.lang.NoSuchMethodException: <init> []
at java.lang.Class.getConstructor0(Class.java:2327)
at java.lang.Class.getConstructor(Class.java:1725)
at androidx.fragment.app.Fragment.instantiate(Fragment.java:4)
... 26 more
```

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
How to access this link/create an account on Acralyzer ?

**Comment by mikehardy** [comment]
Great question - I'll message you the credentials @Arthur-Milchior 
Acralyzer / our crash dump system should never have personally identifiable information in it (we are very careful with how we handle that, mostly by refusing to handle it) but on the off chance someone does put in PII we do not hand out access freely, though we do on request

**Comment by mikehardy** [comment]
There appears to be a compile failure with the automated attempt to revert, you'll have to manually revert @david-allison-1  - good tech test on github though, it had potential and I could see a revert via github "revert button" working in the future, without violating process

**Comment by mikehardy** [comment]
only thing I don't like is that it branches in the main repo but those aren't too hard to clean up, no big deal.

**Pull request closed without merging**
