### PR TITLE
Update e-mail message

### LINKED ISSUE #10256: E-mail message of exported deck does not parse html correctly
###### Reproduction Steps

1. Long press on any deck.
2. Click export deck.
3.  send via E-mail.

###### Expected Result
The E-mail body should contain 2 hyperlinks first one on "**AnkiDroid**" and another on "**Anki distributions**".

###### Actual Result
Both the anchor tags are not working as link.

Screenshot 2022-01-21 103857

### PR DESCRIPTION
**Pull request by AayushSolanki**
Fixes #10256 
e-mail message is edited and links are added at the bottom of message

**Before**
153740319-ab141c3c-2d1a-41bf-adac-63081f3358b5

**After**
153740330-b613d1ab-ccb0-4cc0-bab7-2cf35f8548be

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Build fails

```
> Task :AnkiDroid:compilePlayDebugKotlin
e: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt: (119, 54): Unresolved reference: export_email_text_new
```

**Review by AayushSolanki — COMMENTED** [review]
changes done

**Review by mikehardy — APPROVED** [review]
Nice! thank you

**Comment by mikehardy** [comment]
Hi there! FEBRUARY OpenCollective Notice

Just a friendly notice that we try to process OpenCollective payments monthly - it's time for [February 2022 submissions](https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+merged%3A2022-02-01..2022-02-28) (I'll do my best to follow this with the same process for March in a week)

If you are interested in compensation for this work, the process with details is here:

https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process#how-to-get-paid

(I only post one comment per person to avoid spamming you, regardless of the number of PRs merged, but this note applies to all PRs merged for in the month of January)

Thanks!

**Pull request merged**
