### PR TITLE
Added AnkiWeb logo to 'AnkiWeb account' screen

### LINKED ISSUE #16300: [suggestion] Add AnkiWeb logo to 'AnkiWeb account' screen
As a desirable approach on the client (AnkiDroid) side, I suppose that it would be better to use AnkiWeb logo for the "AnkiWeb account" screen rather than AnkiDroid logo (only), to be less misleading. 
image

In case that an app has a screen for connecting to Twitter/X, it is natural to use Twitter/X logo in the screen, rather than the logo of the app itself (only). 

I would think the same is true for the screen for connecting to AnkiWeb.

_Originally posted in https://github.com/ankidroid/Anki-Android/issues/16260#issuecomment-2084674323_

### PR DESCRIPTION
**Pull request by dattasneha**
## Purpose / Description

Add AnkiWeb logo to 'AnkiWeb account' screen
## Fixes
* Fixes #16300 

## Approach
Add AnkiWeb logo and make specific changes in required files taking reference from #16672

## How Has This Been Tested?

Tested on Android physical device.
#### Light mode
|Before|After|
|--|--|
|WhatsApp Image 2024-09-19 at 10 42 34 PM|WhatsApp Image 2024-09-20 at 2 45 45 PM|
|WhatsApp Image 2024-09-19 at 10 42 35 PM|WhatsApp Image 2024-09-19 at 10 43 58 PM|

#### Dark mode
|Before|After|
|--|--|
|WhatsApp Image 2024-09-20 at 3 34 23 PM|WhatsApp Image 2024-09-20 at 3 23 56 PM (1)|
|WhatsApp Image 2024-09-20 at 3 37 00 PM|WhatsApp Image 2024-09-20 at 3 23 56 PM|

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by brishtibheja** [comment]
How does this look like in dark mode? Does the star's inside have the background colour? I think that's how it should look like.

**Review by david-allison — COMMENTED** [review]
Thanks!

This doesn't look like the proposed design in:

* https://github.com/ankidroid/Anki-Android/issues/16300

Could you check on the issue/`#ankidroid-design` for a consensus on the design, then make any changes once consensus is reached

**Comment by snowtimeglass** [comment]
Thank you for PR. For now, the logo in the light mode screen looks good to me. 

Can you replace the screenshot for login screen after the change? (The current screenshot there seems a duplication of the already-logged-in screen after the change.)


---

As for the color setting of the "AnkiWeb" text (image), it may need to be changed so that the color switches to black/white in light/dark mode, like the other characters in the screen.

image

image

**Comment by dattasneha** [comment]
> How does this look like in dark mode? Does the star's inside have the background colour? I think that's how it should look like.

@brishtibheja added the screenshots for dark mode. PTAL.


> Could you check on the issue/`#ankidroid-design` for a consensus on the design, then make any changes once consensus is reached

@david-allison Done. Wrote a message on discord channel and made the suggested changes. PTAL.


> Thank you for PR. For now, the logo in the light mode screen looks good to me.


Thanks @snowtimeglass, replaced the screenshot with the correct one and changed the text color for dark mode as well. PTAL.

**Comment by snowtimeglass** [comment]
Thank you for the changes. The "AnkiWeb" text looks good to me.

---
As for the star, perhaps it might be more desirable for the team to approach the upstream to inquire if they could provide the data of the "genuine" AnkiWeb star logo.
image

**Comment by david-allison** [comment]
Can we move discussion of the design back to the issue. 

In particular: I personally feel the designs in https://github.com/ankidroid/Anki-Android/issues/16300#issuecomment-2124630342 are better, and we should define what we want this pull request to do before it's reviewed, otherwise there will be a lot of back & forth here

**Comment by snowtimeglass** [comment]
The two-icons-connection concept is also attractive for me, but its design might need some more adjustment. The thin-gray connecting line in [the suggested image](https://github.com/ankidroid/Anki-Android/issues/16300#issuecomment-2120357850) still doesn't look good enough to me:


(an example image for alternative)
image

That said, I'm still not sure whether requesting such change of concept and design would be good in this pull request.

**Pull request closed without merging**
