### PR TITLE
Implement Pluto for on-device debugging

### PR DESCRIPTION
**Pull request by ShridharGoel**
https://github.com/plutolib/pluto

### CODE REVIEW

**Comment by mikehardy** [comment]
:thinking: what is difficult + not possible now, that this makes possible, where placing and reading log traces is not possible?

**Comment by ShridharGoel** [comment]
@mikehardy This is mainly for making logs, exceptions, ANRs, shared preferences data etc. available on the device itself.

**Comment by mikehardy** [comment]
So, am I assuming that you are developing or running a debug build and are not connected via adb to any development environment, and you find yourself with a need to access those things but you cannot now?

I must admit I have never *wanted* to do that :laughing: . If I am not in front of a computer it is because I am not working, and I don't want to see that junk, and if I can't reproduce it when I get back to the computer and have direct access, I don't particularly care.

I'm not sure, this doesn't seem like it will really unlock productivity, but I dunno. I'm a weak -1 on it, I welcome any others that may sway my opinion or a consensus that disagrees though

**Comment by BrayanDSO** [comment]
>  If I am not in front of a computer it is because I am not working

Same here. Never wanted to debug anything with my phone only

**Comment by david-allison** [comment]
Weak '-1' here: it's something I wouldn't use

**Comment by ShridharGoel** [comment]
It's mostly helpful for users who reach out for issues: they can easily install the debug build to provide logs. But if most people think that it's not useful for AnkiDroid, then I'll be closing the PR.

**Pull request closed without merging**
