### PR TITLE
Bump Gradle from 5.6.1 to 5.6.3, JaCoCo to 0.8.4

### PR DESCRIPTION
**Pull request by pkubowicz**
## Purpose / Description
The are [known issues](https://docs.gradle.org/5.6.2/release-notes.html#fixed-issues) in currently used Gradle 5.6.1

## Fixes
Also fix some clumsy Gradle usages:
- duplicate keys in gradle.properties
- casting string jacocoVersion property to string

## How Has This Been Tested?

CI run would be enough

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by mikehardy** [comment]
Not sure what happened on Travis when CI ran but it blew up completely with something about read-only filesystems on the emulated devices, which is most unexpected. I re-ran it and we'll see how it goes, I'll investigate further if it continues to behave strangely.

**Comment by mikehardy** [comment]
I reproduce this failure locally first time when I pull your branch and run `./gradlew jacocoTestReport` while emulators are up.

It seems you'll have to revise and re-push after determining the root cause

**Comment by pkubowicz** [comment]
I get this error when executing `./gradlew jacocoTestReport` even on master branch, so there is no way for me to check this locally. I can run the app in emulator, but no way of getting tests running in the command line.

I tested my change using Travis CI. Since I cannot see what is wrong with JaCoCo 0.8.5, I simply downgraded to 0.8.4 to get everything working.

**Comment by mikehardy** [comment]
Interesting - I have no problem with master, I just made sure I was in sync now and ran `./gradlew clean jacocoTestReport` with a few emulators up and all was fine. That said I'll try the jacoco 0.8.4 version and I expect it will pass for me as well as CI

**Comment by pkubowicz** [comment]
4 hours ago Gradle released 5.6.3 fixing some issues in 5.6.2, so I had to amend my commit once again. Sorry for that :)

**Comment by mikehardy** [comment]
Upgrading versions is a treadmill which is I outsource the work to dependabot ;-). It doesn't do the jacoco upgrades correctly though so this is still a help for sure. I just want to run it locally to make sure then I'll merge. Thanks!

**Pull request merged**
