### PR TITLE
Added test for AssetHelper util class.

### PR DESCRIPTION
**Pull request by Arnold2381**
## Purpose / Description
Added a test for AssertHelper Util class

## How Has This Been Tested?
Unit Test

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Arnold2381** [comment]
@david-allison-1 PTAL. 
Also while I was writing the test I found out that 
String mimeType = URLConnection.guessContentTypeFromName(path);
the mimeType in AssertHelper.java util class stores text/plain for .docx,.pptx,.xslx, for filenames without extension ex: "test"
so will this be an issue?

**Review by david-allison-1 — APPROVED** [review]
LGTM, thanks!

**Comment by david-allison-1** [comment]
> @david-allison-1 PTAL.
> Also while I was writing the test I found out that
> String mimeType = URLConnection.guessContentTypeFromName(path);
> the mimeType in AssertHelper.java util class stores text/plain for .docx,.pptx,.xslx, for filenames without extension ex: "test"
> so will this be an issue?

I think "best guess" will be fine here, as long as this is documented

**Comment by Arnold2381** [comment]
Ok!!

**Review by mikehardy — APPROVED** [review]
nice! thank you

**Comment by mikehardy** [comment]
> codecov/project — 37.23% (+0.10%) compared to dfa10a3

...every little bit

**Pull request merged**
