### PR TITLE
Changed Material Dialog with Alert Dialog for DeckPicker.kt

### PR DESCRIPTION
**Pull request by PalashKohli007**
## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Thanks!

This reformats the file and makes it hard to understand the change.

Could you ensure the diff only contains changes you care about. 

This may require changing your IDE's formatting settings

**Comment by david-allison** [comment]
Also picked up a conflict

**Comment by PalashKohli007** [comment]
> Also picked up a conflict

resolved, please review

**Comment by david-allison** [comment]
My other comment still stands, the functional changes are effectively unreviewable currently due to the unrelated changes: https://github.com/ankidroid/Anki-Android/pull/13336/files

**Pull request closed without merging**
