### PR TITLE
Dynamicaly set in sentence case... Flag,Toggle Witeboard,Abort Learning

### LINKED ISSUE #16120: Use sentence casing in some settings
If you go to Settings>>Controls then a few inconsistencies appear in capitalisation. The ones that I could spot are:

1. F in Flag is capitalised when it should be not.
2. W in Toggle Whiteboard is capitalised but other instances of whiteboard in the same screen are not.
3. L is not capitalised in Abort learning when it is in Abort Learning and Sync.

### PR DESCRIPTION
**Pull request by jainv4156**
## Fixes
* Fixes #16120

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Looks great!

CI is failing

```patch
Index: AnkiDroid/src/main/res/values/sentence-case.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/values/sentence-case.xml b/AnkiDroid/src/main/res/values/sentence-case.xml
--- a/AnkiDroid/src/main/res/values/sentence-case.xml	(revision 7f692bf1b60d8c85528d1399670c3b798486eb26)
+++ b/AnkiDroid/src/main/res/values/sentence-case.xml	(date 1721377507242)
@@ -26,7 +26,7 @@
 col.redoLabel()
 undoActionUndone()
 -->
-<resources>
+<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="DuplicateCrowdInStrings">
     <string name="sentence_toggle_suspend">Toggle suspend</string>
     <string name="sentence_toggle_bury">Toggle bury</string>
     <string name="sentence_set_due_date">Set due date</string>
```

Apply this (double tap shift -> apply patch from clipboard).

'amend'/'squash' it in with the previous commit, and force push

Then we can get this in

**Comment by david-allison** [comment]
Additional comment: use this syntax in the PR description:

* It links the issue in GitHub so it's auto-closed
* It provides a good link preview

```
* Fixes #16120
```

**Review by david-allison — APPROVED** [review]
Great stuff, thanks so much!

**Comment by jainv4156** [comment]
> Great stuff, thanks so much!

You’re welcome

**Review by lukstbit — APPROVED** [review]
Thank you!

**Pull request merged**
