### PR TITLE
Fix tablet deck picker / study options getCol crashes

### PR DESCRIPTION
**Pull request by mikehardy**
## Purpose / Description

I'm testing on full gamut of emulators API21-31 including a tablet.
Turns out on a tablet when you run it first time the study options fragment attempts to load and do some complex things with the toolbar that involve collection state

But there's no permission to touch the collection on first run yet, so it crashes the app.

Also when I went to add testing I found that if the backend was locked it would crash.

## Fixes
Unlogged

## Approach
Mark getCol() nullable and make it exception-tolerant, check getCol() return to see if it's Null and choose sensible defaults if so, to avoid the crash

## How Has This Been Tested?

Reproduced easily with a Tablet running AnkiDroid first time.
Can no longer reproduce after.

Also parameterized the DeckPickerTest which uncovered 4 different ways it could crash, 1 of which is not easily user-testable but was an issue - when backend was locked - fixed that

## Learning (optional, can help others)
Our testing infrastructure is pretty rich, it was easy to just add a parameter and have robolectric hammer this use case on my behalf

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison-1 — COMMENTED** [review]
Is the issue here that we're no longer throwing `IlegalStateException`? It seems that we expect `getCol()` to fail in the method, and that we've added additional failure cases which aren't handled

**Comment by david-allison-1** [comment]
Also, emulator test is flaky

```
com.ichi2.anki.DeckPickerTest > checkIfClickOnCountsLayoutOpensStudyOptionsOnMobile[TestingAVD(AVD) - 11] FAILED 
	androidx.test.espresso.base.RootViewPicker$RootViewWithoutFocusException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:
	Root{application-window-token=android.view.ViewRootImpl$W@e213269, window-token=android.view.ViewRootImpl$W@e213269, has-window-focus=false, layout-params-type=1, layout-params-string={(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION fmt=RGBA_8888 wanim=0x10302fe
```

**Comment by mikehardy** [comment]
@david-allison-1 

1) unsure, mostly I know crash --> fix. The only place I've seen getCol crash was this test. But to your point the extra case was the  backend locked exception. 3 null failures, 1 locked exception prompting the new try/catch

2) I'm running on tip of dev branch which is flaky yes, that's next but there appear to be 4 flakes on the API gamut. Wanted to fix actual crashes first since it's a clear issue for anyone that tries the app on a tablet.

**Comment by mikehardy** [comment]
#9205 should fix the rest of the stability problems. 1 of them was content provider making some assumptions which has existed forever so I left it and 1 of them was screen lock fouling a test which I think is probably expected so I left it too. The other 2 were both in the new test which PR 9205 should nail down

**Review by david-allison-1 — APPROVED** [review]

**Pull request merged**
