### PR TITLE
 Added AnkiWeb logo to 'AnkiWeb account' screen and 'Logged in' screen.

### PR DESCRIPTION
**Pull request by divyansh1576**
## Purpose / Description
To change the Ankidroid logo to AnkiWeb logo on Login page and My Accounts screen .

## Fixes
* Fixes  https://github.com/ankidroid/Anki-Android/issues/16300
* Closes #17095

## How Has This Been Tested?
Tested on Android physical device. ( API - 34)

## Screenshot

| | |
|:-------------------------------:|:-------------------------------:|
| My account                 | My account                   |

|  | |
|:-------------------------------:|:-------------------------------:|
| Login screen                 |  Login screen
## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Love the concept!

The logos on the left and right should be larger with more margin between the star and the border

**Comment by thedroiddiv** [comment]
Just a UI suggestion, when not logged in show the link as disconnected? And when logged in show it connected?

**Comment by snowtimeglass** [comment]
Thank you for the PR.

I think it would be more desirable to minor-adjust the color of the dashed line and the chain, and the spacing of them. In other words, I personally prefer more consistency in the spacing and the color (or the gradation of the colors).

(image)
image

**Comment by david-allison** [comment]
I'd love to see @snowtimeglass' suggestion, with a little more padding between the star and the border of the circle (likely by enlarging the circle, and keeping the star in the same position)

**Review by david-allison — CHANGES_REQUESTED** [review]
Moving the above comment on the logo change to be a blocker on merging

**Comment by divyansh1576** [comment]
## Changes
- Changed the login logo as per the suggestion of @snowtimeglass . 
- Added more padding between the logo and the border of Ankiweb. 
- Changed the preview in PR description.

**Comment by david-allison** [comment]
Much better! 

I'd make the circles slightly bigger still, but that's a nitpick

The blocker is that the logos aren't aligned vertically

**Comment by divyansh1576** [comment]
Updated as per the suggestion
- Increased the size of the circle. 
- Adjusted the size/alignment of the logo's.
Screenshot 2024-10-08 002947

**Comment by david-allison** [comment]
@divyansh1576 ping me if this isn't reviewed within 24 hours. I'm not currently at my PC

I suspect my feedback will be that the star on the right has been skewed by a scale operation

**Comment by snowtimeglass** [comment]
Thank you for the change!

AnkiDroid icon looks good to me.


Because of the symmetry of the dot color gradation between the left side and right side, the dot on the right end is darker than AnkiWeb star, which rather looks inharmonious to me.
image

How about making the dot color gradation on the right side brighter than the color of AnkiWeb star?

(image)

image

**Comment by divyansh1576** [comment]
>How about making the dot color gradation on the right side brighter than the color of AnkiWeb star?

Thanks for the  detailed review, Sounds good to me .

**Review by david-allison — APPROVED** [review]
Looks great, cheers!

**Comment by xenonnn4w** [comment]
WhatsApp Image 2024-10-09 at 16 40 31_e8f47313
If possible, as per above discussion you can try having something like this for Log In screen.

**Comment by divyansh1576** [comment]
@xenonnn4w Updated!


image

**Review by david-allison — APPROVED** [review]
If I've approved and you haven't made significant changes, there's no need to ask for reapproval. Still good to go 😁

**Review by mikehardy — APPROVED** [review]
This is really cool! I like the way it looks

I tested it locally and found a problem with landscape mode where now that there are two logos (instead of just one), only one of the logos was hidden in landscape mode

Hiding the logo in landscape is intentional to preserve screen real estate for the actual interactive parts of the screen so I think it's worth maintaining, and with apologies it was easier for me to just play with the fix and commit it then to describe it, so I did that

Here's a video of the landscape switching in both logged in and logged out states now to show it is working

I'm +1 on it

[ankilogo_with_landscape_logo_vis_fix.webm](https://github.com/user-attachments/assets/5420c2f1-9443-4621-b2c1-2f74a6347183)

**Review by david-allison — APPROVED** [review]
Squashed changed commit message.

Good to go

**Pull request merged**
