### PR TITLE
Preparing query in basicCheck

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This is equivalent; we simply check whether an ord is negative or at
least equal to the number of element

### CODE REVIEW

**Comment by mikehardy** [comment]
Are template ordinals permitted to have gaps?
I believe they are, in the cloze case I think it is permitted to have c1 c3 and c4, skipping c2 for instance.

The previous check would correctly fail an ord 2, while this one would incorrectly let 2 pass but incorrectly fail an ord 4

**Comment by Arthur-Milchior** [comment]
You're absolutely right, templates ordinal can have gaps. This is irrelevant because the code skip note type which are are cloze type and consider only standard type.

**Comment by Arthur-Milchior** [comment]
I should note that if those types were not skipped, the previous version would have failed long long time ago.

**Comment by mikehardy** [comment]
Ah interesting. I'm in CardTemplateEditor a lot, let me check to see if non-cloze template ordinals can have gaps or if they are always adjusted down. I think gaps are not allowed there (which makes this change valid) but I want to be 100% sure

**Comment by Arthur-Milchior** [comment]
I'll help you. Take a look at `_updateFieldOrds`. The point of this function is exactly this: ensure that the ord of the template at position `i` is `i`. 

And `_updateFieldOrds` is called after each change to the note type.

So if there are gaps in non cloze type, there is a problem

**Comment by mikehardy** [comment]
that's what I remembered too, and even in my CardTemplateEditor rewrite as #5151 I ensure the same - this works - thanks!

**Comment by mikehardy** [comment]
released as 2.10alpha71 as soon as google finishes processing it

**Pull request merged**
