### PR TITLE
intNow to intTime

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
In order to be consistent with anki code

## Purpose / Description
libanki tries to be as consistent as possible with Anki code. There is at least two functions where the name was changed. 
One change was motivated - I guess - by the fact that "new" is a valid method name in Python and not in Java. The other change seems useless. So in this branch/pull request, I just intend to do a global search/replace to be consistent with anki as far as function name goes.

## How Has This Been Tested?
Gradlew and Travis.

Honestly, there is nothing to test here. It's just a method whose name is changed. The only point is to be consistent with anki code.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
Ideally, the title would be «names consistent with anki's code». But I can't change the name of a pull request.

The second commit contains only a new comment, which I belive to be useful. I do not understand how it is even possible that Travis reject it while it accepted  the first commit

**Comment by mikehardy** [comment]
Regarding the CI failure - that's because Android emulator in the Travis CI environment is imperfect. Specifically the CI environment is a virtual machine spun up in some cloud providers hosting system, and they don't allow nested virtualization. So the emulators that spin up are running software CPU emulation which is very very slow. The occasional effect of that is that one of the emulators hangs for some unrelated reason or simply takes too long for some dependent tool that then times out, and you get spurious failures. The answer is to just ask that level to re-run for that CI pass (as I just did now) and it resolves.

Not ideal but it's the state of the art for Android apps doing CI unfortunately. Our PR volume (and thus false negative volume) has historically been low enough that this hasn't been the thing to optimize

In your PRs if you click in the details tab and notice that one or two of the oraclejdk8 builds failed, but not all of them, and especially if they are scattered in the API levels (as opposed to "all the APIs below 21 failed", for instance), it's probably just one of these spurious failures.

**Comment by Arthur-Milchior** [comment]
I can't find a rerun button on https://travis-ci.org/ankidroid/Anki-Android/builds/597645980 nor on https://travis-ci.org/ankidroid/Anki-Android/jobs/597645989
And a check is still failing with a message which is not clear at all. 
> The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "BCL"" failed and exited with 52 during .

**Comment by Arthur-Milchior** [comment]
Thank you for all of your explanation.
It's the first time I contribute to such a big project, and I must admit that there are plenty of new things here for me. So I do appreciate helps.

**Comment by mikehardy** [comment]
:-) - yeah, the last check is oraclejdk11 and it's more of a technology test than anything. I'd like to get the newer JDKs working but they still have a problem so that one is an "allowed failure" in Travis (and it has a little lighter-text note saying so at the bottom of the grid). It's just there so we maintain multi-JDK CI even if the code itself doesn't run yet.

As long as all the oraclejdk8 steps pass, it'll go green as a unit

I don't think people outside the AnkiDroid org get permission to re-run builds, it's something I do normally, but it's something I can certainly deputize if it makes sense

**Comment by Arthur-Milchior** [comment]
I'm new as far as ankidroid is related, so I'm not going to ask to be deputized (is it even English). But if it occurs often, then I guess I'll eventually ask for it if it's ok.

**Comment by Arthur-Milchior** [comment]
I now explictly stated that there is just nothing to test here. My only goal is consistency with anki code. A method name change; there is no more and no less code than before, no new/deleted line of code; and only edition is renaming or comment.

**Pull request merged**
