### PR TITLE
NF: remove all onboarding related code

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
It seems it will never get used.

Note that 19-onboarding was never sent for translation, so no need to edit the translation file or crowdin

### CODE REVIEW

**Review by david-allison — APPROVED** [review]

**Comment by Arthur-Milchior** [comment]
I missed some string and a part of a layout specifically for tutorial. Sorry to have to ask for a re-review David

**Review by david-allison — APPROVED** [review]
More code removed? Even better

**Comment by david-allison** [comment]
```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/drawable/hand_icon.xml:1: Error: The resource R.drawable.hand_icon appears to be unused [UnusedResources]
<vector android:height="24dp" android:tint="#FFFFFF"
^
```

**Review by BrayanDSO — APPROVED** [review]
Good riddance

**Pull request merged**
