### PR TITLE
Remove @NeedsTest from a file

### PR DESCRIPTION
**Pull request by RobozinhoD**
## Purpose / Description

https://github.com/ankidroid/Anki-Android/issues/13283#issuecomment-1435222750
> @NeedsTest("removing JvmOverloads should fail"). Removing JvmOverloads is not behavior of the app or user, but of the programmer. What would the test be like? Can we make a test that would somehow recompile the app, removing JvmOverloads, and then run it in an emulator and verify that it crashes? Suppose this test fails, how does this help us?

## Fixes
#13283

## Approach
Removed the annotation

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
As with other classes with JvmOverloads, we have a test which fails if `JvmOverloads` is removed, because it's not obvious that it's required and is a holdover from the Kotlin Conversion.

In this particular case, the requirement for `@JvmOverloads` was removed in: 709bb80a8334084c63afddcfa447b8a78713f44e

so the annotation can be removed from both `NumberRangePreferenceCompat` and `SeekBarPreferenceCompat`

**Comment by RobozinhoD** [comment]
SeekBarPreferenceCompat doesn't have a NeedsTest annotation to remove, or should I do something else?

**Comment by david-allison** [comment]
> SeekBarPreferenceCompat doesn't have a NeedsTest annotation to remove, or should I do something else?

Remove the `JvmOverloads`, it's no longer necessary

**Review by BrayanDSO — APPROVED** [review]
> Remove the JvmOverloads, it's no longer necessary

I bet it will fail `PreferencesTest.fragmentsDoNotThrowOnCreation`, so we already have a test for this. 

709bb80a8334084c63afddcfa447b8a78713f44e only simplifies the logic of `onDisplayPreferenceDialog` and doesn't change the fact that the framework XML interpreter can't handle Kotlin's default parameters

**Comment by david-allison** [comment]
> > Remove the JvmOverloads, it's no longer necessary
> 
> I bet it will fail `PreferencesTest.fragmentsDoNotThrowOnCreation`, so we already have a test for this.
> 
> [709bb80](https://github.com/ankidroid/Anki-Android/commit/709bb80a8334084c63afddcfa447b8a78713f44e) only simplifies the logic of `onDisplayPreferenceDialog` and doesn't change the fact that the framework XML interpreter can't handle Kotlin's default parameters

I've tested, there's no crash on API 32 emulator. There is a crash before the linked commit

**Review by david-allison — APPROVED** [review]

**Pull request merged**
