### PR TITLE
fix all types of sorting when browser options are set to "notes"

### LINKED ISSUE #12742: [Bug] By sort field order does not work when browser notes
###### Reproduction Steps
1. Create a few basic cards but not alphabetically, e.g. 2, 4, 6, 1, 3, 5
2. Card browser, change display order, by sort field and set browser options to "cards". You can see the cards in alphabetical order (1, 2, 3, 4, 5, 6).
3. Change browser options to "notes".

###### Expected Result
Cards are in alphabetical order

###### Actual Result
Cards are in order as added

###### Debug info
AnkiDroid Version = 2.16alpha88

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 6e947d7c-0fbc-4a5c-805f-d612c7208dc1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by pratyaksh1610**
## Purpose / Description
Fixes all types of sorting when browser options are set to "notes".

## Fixes
Fixes #12742 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)

### CODE REVIEW

**Review by BrayanDSO — CHANGES_REQUESTED** [review]
Tests fail

```
CardBrowserTest > checkCardsNotesMode FAILED
    java.lang.AssertionError: 
    Expected: <3>
         but: was <6>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at com.ichi2.anki.CardBrowserTest$checkCardsNotesMode$1.invokeSuspend(CardBrowserTest.kt:773)
        at com.ichi2.anki.CardBrowserTest$checkCardsNotesMode$1.invoke(CardBrowserTest.kt)
        at com.ichi2.anki.CardBrowserTest$checkCardsNotesMode$1.invoke(CardBrowserTest.kt)
        at com.ichi2.anki.RobolectricTest$runTest$1.invokeSuspend(RobolectricTest.kt:650)
        at com.ichi2.anki.RobolectricTest$runTest$1.invoke(RobolectricTest.kt)
        at com.ichi2.anki.RobolectricTest$runTest$1.invoke(RobolectricTest.kt)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invokeSuspend(TestBuilders.kt:212)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invoke(TestBuilders.kt)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTestCoroutine$2.invoke(TestBuilders.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTestCoroutine(TestBuilders.kt:211)
        at kotlinx.coroutines.test.TestBuildersKt.runTestCoroutine(Unknown Source)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invokeSuspend(TestBuilders.kt:167)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invoke(TestBuilders.kt)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$1$1.invoke(TestBuilders.kt)
        at kotlinx.coroutines.test.TestBuildersJvmKt$createTestResult$1.invokeSuspend(TestBuildersJvm.kt:13)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:[106](https://github.com/ankidroid/Anki-Android/actions/runs/3352780952/jobs/5555155717#step:8:107))
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:12)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:166)
        at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
        at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest(TestBuilders.kt:154)
        at kotlinx.coroutines.test.TestBuildersKt.runTest(Unknown Source)
        at com.ichi2.anki.RobolectricTest.runTest(RobolectricTest.kt:648)
        at com.ichi2.anki.RobolectricTest.runTest$default(RobolectricTest.kt:643)
        at com.ichi2.anki.CardBrowserTest.checkCardsNotesMode(CardBrowserTest.kt:756)
```

**Comment by dae** [comment]
Turning the notes mode into cards mode is not the correct way to solve this.

**Comment by pratyaksh1610** [comment]
Any hints on how can I approach to this ?

**Comment by dae** [comment]
findNotes() references "noteSortType". The card list screen is probably saving the settings to the wrong config name in notes mode.

**Comment by pratyaksh1610** [comment]
`
open fun findNotes(query: String, order: SortOrder = SortOrder.NoOrdering()): List<Long> {
        return Finder(this).findNotes(query)
    }
`

This is the function which reference sort type but the sort type is not passed anywhere else.

**Pull request closed without merging**
