### PR TITLE
fix: added tag doesn't reflect in adapter

### LINKED ISSUE #8762: [Bug] Regression added tag in `TagsDialog` don't appear in RecyclerView
My PR #8322 Added this bug since the main data structure backing the recycler view `mFilteredList` is a copy of all tags in `TagsList` the changes in `TagsList` don't reflect to the recyclerview

###### Reproduction Steps

1. Open TagsDialog
2. Click '+' icon
3. Add tag

###### Expected Result

the new tag is visible in the  list

###### Actual Result

the new tag isn't visible in the list

### PR DESCRIPTION
**Pull request by TarekkMA**
## Purpose / Description
I have reverted to the old way of handling `mFilteredList`.

## Fixes
Fixes #8762

## Approach
`mFilteredList` will be only set when there is a search filter active, otherwise, it's null and the adapter will use the original full list.

## How Has This Been Tested?

Emulator

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Is there a way to do a test here? Seems like robolectric should be able to drive the activity enough that you can check it and verify the regression + the fix? I'll admit, these kinds of tests where it deals with a few UI elements at once are a bit involved, but the fragment stuff is so new it would be nice to have more testing exercising it

**Comment by TarekkMA** [comment]
> Is there a way to do a test here? Seems like robolectric should be able to drive the activity enough that you can check it and verify the regression + the fix? I'll admit, these kinds of tests where it deals with a few UI elements at once are a bit involved, but the fragment stuff is so new it would be nice to have more testing exercising it

I will try, the issue I think is the involvement of RecyclerView. will see if I can use robolectric to deal with it

**Comment by TarekkMA** [comment]
@mikehardy done.

I had to add these lines to make sure the adapter is updated to the new data.

```java
            recycler.measure(0, 0);
            recycler.layout(0, 0, 100, 1000);
```

**Review by mikehardy — APPROVED** [review]
Cool, lgtm

**Pull request merged**
