### PR TITLE
[Kotlin Migration] AddContentApi

### PR DESCRIPTION
**Pull request by n1snt**
## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Hey @n1snt ! :wave: - I am really sorry this staled out, and it appears the underlying types have changed a little bit so that it no longer compiles (if it compiled before?) but it also looks relatively easy to fix.

Are you interested in collaborating to get this merged, or would you like to hand it off to a new dev? No pressure either way, just let us know. Thanks!

**Comment by n1snt** [comment]
Hello @mikehardy, I'm still interested in working on this. 
I'll have a look at this & will try to fix it in the coming few days.

**Comment by mikehardy** [comment]
Oh great thank you! I've just come back from summer travels so we will hopefully not be losing any more PRs to the Stale Bot, I really hate it when that happens

**Comment by n1snt** [comment]
So I tried fixing the build here and ran across an issue in a Utils method. (Line 40)

`    @JvmStatic
    fun joinFields(list: Array<String?>?): String? {
        return if (list != null) TextUtils.join("\u001f", list) else null
    }
`

It is accepting null as list arg.
Do we need it to accept null values (in list & list as null)?

**Comment by david-allison** [comment]
@ankidroid/reviewers - further breaking changes on the `API` module

It's a public method, and a breaking change if we change the type signature/functionality

* I would like to make a breaking change:
    * `fun joinFields(list: Array<String?>?): String? {` to 
    * `fun joinFields(list: Array<String>?): String? {`
* I would like to add a TODO to see if we can include a `contract` for null -> null and non-null to non-null: https://www.baeldung.com/kotlin/contracts

@n1snt see discussion above, assume it's still going to accept `null`

**Comment by mikehardy** [comment]
I'm okay with those breaking changes. I can't imagine why having a null field would be useful ?
I assume the typing can be pseudo-validated by looking at the type definition upstream in Rust to cross-check

**Comment by n1snt** [comment]
@david-allison I have created PR for the changes you proposed.  #12250
This needs to get merged to fix this PR.

**Comment by david-allison** [comment]
Approved, thanks for keeping this moving

**Comment by david-allison** [comment]
I made a mistake with `Utils`, the class was `internal`, so the changes were non-breaking to consumers

**Pull request closed without merging**
