### PR TITLE
Changed contrast as per given in issue 12476

### PR DESCRIPTION
**Pull request by adityarai004**
## Purpose / Description
The Application has a black theme, while adding a new card or task the two buttons "Tags" and "Cards" background doesn't look pretty good.

## Fixes
adityarai004:#12476
Changed the color of background as per given in the issue and i just picked up a bit higher contrast color from the color picker android studio.

## Approach
The approach is pretty simple, just find the corresponding color file in the android studio "project" tab and do a hit and trial of different colors as per requirement.
## How Has This Been Tested?
Just downloaded the source code of ankidroid and cloned it using git desktop and loaded the whole application code in my PC's android studio. Run the app and yeah its done.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have performed a self-review of your own code
- [ x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by adityarai004** [comment]
image
(old)
image
(new)

**Comment by david-allison** [comment]
Thanks! Could you edit + fill out the first post (especially the `Fixes #XXX` line, which links the issue to the pull request).

Change looks good from the screenshots! Thanks again

**Comment by adityarai004** [comment]
> Thanks! Could you edit + fill out the first post (especially the `Fixes #XXX` line, which links the issue to the pull request).
> 
> Change looks good from the screenshots! Thanks again

Done and Thank you, I am happy to hear you feel that way!

**Review by david-allison — APPROVED** [review]
Perfect, thanks!!

**Review by mikehardy — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
