### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by david-allison-1**
Bad Kotlin Migration merge: Both base class and subclasses were migrated differently

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Ah bummer - not thrilled it happens but I can't imagine how long it would take if we had a "branch must be up to date before merging" policy - I've done those before and it would make this Kotlin blitz take a month

**Comment by mikehardy** [comment]
Thanks a ton for fixing this by the way

**Comment by david-allison-1** [comment]
I'm sure we could get something nonintrusive in terms of developer time (merge to `develop`, which enqueues then merges to `master` if green), but it's likely not worth the effort and thought to get it right at this point.

Velocity is fantastic

**Comment by mikehardy** [comment]
Oh wait, I just read about this new feature check this out - I just signed us up for the beta waitlist

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/adding-a-pull-request-to-the-merge-queue

Appears to be designed just about right

**Comment by david-allison-1** [comment]
I love it when smart people mean we barely need to do anything ☺️

**Comment by mikehardy** [comment]
especially when they give you free CI minutes :see_no_evil:

**Pull request merged**
