### PR TITLE
nf: Kotlin Cleanup

### PR DESCRIPTION
**Pull request by david-allison**

### CODE REVIEW

**Review by lukstbit — CHANGES_REQUESTED** [review]
Looks good, got a ktlint issue with imports in DeckPickerTest.

**Comment by david-allison** [comment]
Can't repro the failure. Rebased onto `main`, marking as draft for now

**Comment by lukstbit** [comment]
A simple "Optimize imports" should fix the ktlint failure.

**Comment by david-allison** [comment]
I used to be able to reproduce issues with `./gradlew lint`, this no longer works.

I've fixed the issue, and rebased, but would rather fix the underlying cause as it impacts my workflow

**Comment by lukstbit** [comment]
Was this supposed to be found just with lint(as it's a ktlint related task failure)? I always ran the style checks with:

`./gradlew clean lint ktlintCheck`

**Review by lukstbit — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
