### PR TITLE
fix(translations): make arrays constant

### LINKED ISSUE #7794: Remove 11-arrays.xml string-array elements
Arrays are better used in `constants.xml` and referenced via `@string` to allow for changes in the order of the array

----

* Deprecate `11-arrays.xml`
   * Instead, use `@string` references: https://stackoverflow.com/a/4161645
       * How do we do this without trashing the existing translations? Doesn't seem easy in Android Studio
   * Enforce via lint check

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/7793#issuecomment-735378061_

-----

Follow up steps from #7800 :

* [x] Language sync
* [x] Copy from string-array to string for each language file

<details><summary>progress</summary>

**no action**

* [x] af
* [x] am
* [x] bn
* [x] ckb
* [x] da
* [x] fy
* [x] ga
* [x] got
* [x] gu
* [x] hr
* [x] hy
* [x] is
* [x] jv
* [x] ka
* [x] kk
* [x] km
* [x] ky
* [x] lv
* [x] mn
* [x] mr
* [x] my
* [x] nn (nnno)
* [x] pa (pain)
* [x] ro
* [x] sq
* [x] ss
* [x] sw
* [x] tg
* [x] tgl (tagalog: tl)
* [x] th
* [x] ti
* [x] tn
* [x] ts
* [x] tt (ttru)
* [x] ur (urpk)
* [x] uz
* [x] ve
* [x] wo
* [x] xh
* [x] yue (yu)
* [x] zu

**Action Needed**

* [x] ar
* [x] az
* [x] be
* [x] bg
* [x] ca
* [x] cs
* [x] de
* [x] el
* [x] eo
* [x] es-rAR
* [x] es-rES
* [x] et
* [x] eu
* [x] fa
* [x] fi
* [x] fil
* [x] fr
* [x] gl
* [x] heb
* [x] hi
* [x] hu
* [x] ind
* [x] it
* [x] ja
* [x] ko
* [x] ku
* [x] lt
* [x] mk
* [x] ms
* [x] nl
* [x] no
* [x] pl
* [x] pt-rBR
* [x] pt-rPT
* [x] ru
* [x] sat
* [x] sk
* [x] sl
* [x] sr
* [x] sv
* [x] ta
* [x] te
* [x] tr
* [x] uk
* [x] vi
* [x] zh-rCN
* [x] zh-rTW

</details>

* [x] Move gestures_labels to constants.xml

### LINKED ISSUE #10554: Extract arrays: `night_theme_labels` and `day_theme_labels`
----

All commits pass all tests and compile. So, yes, a rebase merge is better.

There is just the situation about the strings that need to be moved from the xml arrays.
I had added on the PR text:
> Note: theme_light, theme_plain, theme_black, theme_dark need to be moved from their arrays.
> This PR is blocked until then. For now, these strings are being duplicated, as settled in Discord.

This does not seem something I can do myself, since it's necessary to do language sync (stated [here](https://github.com/ankidroid/Anki-Android/pull/7800#issue-753471802)), and I don't know what impedes this to be automated.

@david-allison said on Discord to ping him to do it, so now I am doing it.

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/pull/10520#issuecomment-1069381684_

### PR DESCRIPTION
**Pull request by david-allison**
If we changed array ordering, CrowdIn corrupted the ordering of strings

To fix this: define a fixed order in constants.xml, and use
translatable strings from `11-arrays`

Fixes #7794
Fixes #10554 

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
This is a lazy fix, as the CrowdIn method would have taken multiple hours.

The downside is 34 strings on CrowdIn need to be re-translated, or someone needs to go through the next sync manually

**Comment by david-allison** [comment]
```
> Task :AnkiDroid:lintPlayDebug FAILED
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/01-core.xml:91: Error: Duplicate string value "Suspend card", used in leech_action_suspend_card, menu_suspend_card [DuplicateCrowdInStrings from com.ichi2.anki.lint]
    <string name="menu_suspend_card">Suspend card</string>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values/11-arrays.xml:27: Duplicates value in menu_suspend_card. Add a comment attribute on both strings to explain this duplication
1 errors, 0 warnings
```

**Review by mikehardy — APPROVED** [review]
Tough balance on the tension between i18n churn and getting this fixed
This was subtle enough to fix and we're constrained strongly on time that I agree with this point on that decision axis. Let's go

**Comment by mikehardy** [comment]
@david-allison I feel this requires a close eye on the i18n sync, could you fire it off after a quick introspect to make sure it's good to go pre-push-to-crowdin and then make sure the commit on crowdin pull is as expected?

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/actions/runs/1998935703 - I'll also do some manual work to fix up the translations

**Pull request merged**
