### PR TITLE
Fixed reviewer not updating if flag changed in Cardbrowser and more than 1 activity in stack

### LINKED ISSUE #11831: [Bug] Reviewer not updated If flag/mark changed in CardBrowser and there is more than 1 activity in backstack
1. Open the reviewer
2. Open **Statistics** from the navigation drawer
3. Open card browser and mark a card
4. Go back to the reviewer
5. Check if the card is marked

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/issues/11396#issuecomment-1133583029_

### PR DESCRIPTION
**Pull request by dorrin-sot**
## Fixes
Fixes #11831 

## Approach
- 11831: Added "currentCard" and "reloadRequired" the intents in `NavigationDrawerActivity#onBackPressed` and recieved them in `NavigationDrawerActivity#onActivityResult`

## How Has This Been Tested?

https://user-images.githubusercontent.com/59933477/178156452-1237423f-d700-4ec5-ac2d-fab7f8514084.mov

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — COMMENTED** [review]
Could you add a test? It's very easy for a regression to appear here

**Comment by dorrin-sot** [comment]
@david-allison Sure! 
Just that I've always struggled with tests that require navigations (My main issue is always retrieving the current activity after navigating to it). Could you please give an advice on what works or if we already have tests that include lots of navigation?

**Comment by mikehardy** [comment]
I may not be remembering correctly but I think some of the cardtemplatepreviewer stuff sends intents and checks intent handling and cross activity action. May be useful?

**Comment by dorrin-sot** [comment]
@mikehardy Thanks

**Comment by dorrin-sot** [comment]
Sorry I couldn't find anything there for testing `startActivityForResult` and `onActivityResult`. Is it ok if I add an instrumentation test instead?

**Comment by mikehardy** [comment]
If you can get it to work that way, that works for me, I'll prefer an androidTest over no test. Just be really really careful about reliability. Historically they are the flakiest

**Comment by david-allison** [comment]
Look into `ShadowActivity`, if that doesn't help, agreed with Mike, better to have an instrumented test with a note to fix it later

**Pull request closed without merging**
