### PR TITLE
Add round icon

### PR DESCRIPTION
**Pull request by cydia2020**
This add round icon of Anki for devices that supports, eg. Google Pixel and/or any third party ROMs that implemented this feature. The icon itself haven't changed, it's just a round layer underneath the icon.

### CODE REVIEW

**Comment by timrae** [comment]
Why? Changing the icon requires extensive interaction with the community to make sure the majority of people like it; it's a lot of work.

**Comment by timrae** [comment]
Oh, I see this is in *addition* to the existing icon, not replacing it. Could you please add the .svg source to the folder [`docs/graphics/src `](https://github.com/ankidroid/Anki-Android/tree/master/docs/graphics/src)?

**Comment by timrae** [comment]
Also, would you be able to move in the non-round icon to the same `mipmap` folders, and rename your round one to `anki_round.png` to better distinguish between them?

**Comment by cydia2020** [comment]
Alright, give me one second

**Comment by cydia2020** [comment]
here you go, a little bit messy since I am in a hurry, but it works 😁

**Pull request merged**
