### PR TITLE
Android test utils.kt

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
New test of https://github.com/ankidroid/Anki-Android/pull/10779 with an androidTest file

I add to rename the class first, becase Kotlin would reject compilation due to class conflict with the same class in /test folder

Emulator crash as soon as I start it, so I can't run the test

### CODE REVIEW

**Comment by david-allison** [comment]
> New test of #10779 with an androidTest file
> 
> I add to rename the class first, becase Kotlin would reject compilation due to class conflict with the same class in /test folder
> 
> Emulator crash as soon as I start it, so I can't run the test

I'd say let's shelve it for now, and exclude ANDROID_TEST from the script

**Review by david-allison — CHANGES_REQUESTED** [review]
```
> Task :AnkiDroid:compileAmazonDebugAndroidTestKotlin
e: warnings found and -Werror specified
w: /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/AndroidTestUtils.kt: (75, 46): 'getter for defaultDisplay: Display!' is deprecated. Deprecated in Java
w: /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/AndroidTestUtils.kt: (75, 61): 'getMetrics(DisplayMetrics!): Unit' is deprecated. Deprecated in Java

> Task :AnkiDroid:compileAmazonDebugAndroidTestKotlin FAILED
> Task :AnkiDroid:deleteSingleFileInGradle UP-TO-DATE

> Task :AnkiDroid:compilePlayDebugAndroidTestKotlin FAILED
e: warnings found and -Werror specified
w: /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/AndroidTestUtils.kt: (75, 46): 'getter for defaultDisplay: Display!' is deprecated. Deprecated in Java
w: /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/AndroidTestUtils.kt: (75, 61): 'getMetrics(DisplayMetrics!): Unit' is deprecated. Deprecated in Java

> Task :AnkiDroid:jacocoAmazonDebug
```

**Comment by Arthur-Milchior** [comment]
When I try to run on my device, on DeckPickerTest.checkIfStudyOptionsIsDisplayedOnTablet I got

> java.lang.NullPointerException
at com.ichi2.libanki.DeckManager.get(DeckManager.kt:81)
at com.ichi2.libanki.Decks.current(Decks.java:1035)
at com.ichi2.anki.DeckPicker.__renderPage(DeckPicker.java:2292)
at com.ichi2.anki.DeckPicker$UpdateDeckListListener.actualOnPostExecute(DeckPicker.java:2184)
at com.ichi2.anki.DeckPicker$UpdateDeckListListener.actualOnPostExecute(DeckPicker.java:2155)
at com.ichi2.async.TaskListenerWithContext.onPostExecute(TaskListenerWithContext.kt:48)
at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.java:228)
at android.os.AsyncTask.finish(AsyncTask.java:771)
at android.os.AsyncTask.access$900(AsyncTask.java:199)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8653)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Which I have no idea how to debug. Since it's not an emulator (they fail to start), it should have halted immediately due to `assumeTrue(InstrumentedTest.isEmulator());`

**Review by david-allison — CHANGES_REQUESTED** [review]
We need to work out how to stop Kotlin seeing this as a redeclaration

`androidTest` has no dependencies on `test` and vice-versa, they shouldn't clash.

**Pull request closed without merging**
