### PR TITLE
Pontoon add documentation

### LINKED ISSUE #12452: Add Pontoon as a place for translators to help (contributing/support messaging)
We need to start messaging the changes for translators in AnkiDroid (contributing, support etc) that Pontoon is a place to help with translations as well as Crowdin,

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/12448#issuecomment-1251267309_

### PR DESCRIPTION
**Pull request by lonewolf2208**
## Purpose / Description
This PR was intend to inform the translators that Pontoon is also a place to help with translations along with CrowdIn.

## Fixes
This PR is an attempt to fix #12452 

## Approach
I first search for all the wiki pages that describe about Crowdin and then tried to learn about how Pontoon works and then added information about pontoon along with Crowdin. 

## How Has This Been Tested?

No testing needed to be done as the changes were made in wiki files .

## Learning (optional, can help others)
Since it is my first time interacting with Pontoon and Crowdin . I learned about their working and how translation works . 

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Hi, there's 1000 commits in this PR, as it appears to merge the wiki into Anki-Android. Was this intended?

**Comment by lonewolf2208** [comment]
> Hi, there's 1000 commits in this PR, as it appears to merge the wiki into Anki-Android. Was this intended?

Sorry, that was not intended. So, I had made changes to the github wiki and these were the steps I followed.
1) I cloned the github wiki on my local
2) Made a new repository. Made the necessary changes in github wiki and pushed it to the new repository.
3) I upstreamed and synced the feature branch with main and therefore you are probably seeing a thousand commits.

Should I close this pull request, if yes. How should I commit to github wiki.

**Comment by lonewolf2208** [comment]
```diff 
diff --git a/Development-Guide.md b/Development-Guide.md
index 7f0ff4e..3af2a8f 100644
--- a/Development-Guide.md
+++ b/Development-Guide.md
@@ -267,9 +267,7 @@ An apk file signed with a standard "debug" key will be generated named `"AnkiDro
 
 ## Adding translations
 
-AnkiDroid uses [string resources](https://developer.android.com/guide/topics/resources/string-resource) for all translatable strings. These are managed by a platform called [CrowdIn](https://crowdin.com/project/ankidroid).
-
-A translation consists of a key (used to reference the translation from Java), and a value:
+AnkiDroid uses [string resources](https://developer.android.com/guide/topics/resources/string-resource) for all translatable strings. These are managed by a platform called [CrowdIn](https://crowdin.com/project/ankidroid) and [Pontoon](https://i18n.ankiweb.net/)
 
 ```xml
 <string name="example_key">Example value</string>
@@ -282,7 +280,7 @@ A translation consists of a key (used to reference the translation from Java), a
    - If the item is a plural, see [Google's documentation for handling plurals](https://developer.android.com/guide/topics/resources/string-resource#Plurals)
 4. Ignore any errors stating that these are missing translations after adding the string. If it compiles, it's fine. Maintainers will handle generating the strings after the pull request is completed.
 5. Take a screenshot of the string in context and add it to the Pull Request
-6. After the change is merged, a maintainer should add this screenshot to the CrowdIn string to help translators with context
+6. After the change is merged, a maintainer should add this screenshot to the platform to help translators with context
 
 <details><summary>Example of the correct file to modify</summary>
 
@@ -298,14 +296,14 @@ A translation consists of a key (used to reference the translation from Java), a
 * Values should be unique in English. If the values are not unique, a `comment=""` attribute must be added to explain the differences to our translators. This is enforced by lint.
 
 ## Handling translations
-As described in the [contributing wiki](https://github.com/ankidroid/Anki-Android/wiki/Contributing#translate-ankidroid), AnkiDroid localization is done through the Crowdin platform. Developers should basically ignore all resource folders that have non-English locales. Edit the English strings only, and one of the project owners will handle the syncing of the translations. The process works as follows:
+As described in the [contributing wiki](https://github.com/ankidroid/Anki-Android/wiki/Contributing#translate-ankidroid), AnkiDroid localization is done through the Crowdin and Pontoon platform. Developers should basically ignore all resource folders that have non-English locales. Edit the English strings only, and one of the project owners will handle the syncing of the translations. The process works as follows:
 
 * Developers can freely add, delete, or modify strings in English to the resources folder (`values/`) and commit to git.
   * Renaming translation keys should be avoided if at all possible if the use is the same as it causes re-translation (appears as a delete-old/add-new to translators).
   * If you update the value of an existing key it *will not* be marked as needing translation. Existing translations are preserved. If you need to change a string significantly, meaning it needs re-translation, you must use a new key and remove the old key.
-* A project owner will run a script that pushes those changes to the crowdin platform
-* Translators will see any new untranslated strings on crowdin and submit their translations
-* Before release a project owner will run another script which pulls all the current translations from crowdin and overwrites the existing files
+* A project owner will run a script that pushes those changes to the crowdin and pontoon platform .
+* Translators will see any new untranslated strings on crowdin and pontoon and submit their translations
+* Before release a project owner will run another script which pulls all the current translations from crowdin and pontoon and overwrites the existing files
 * These new files are then committed and pushed to GitHub
 
 ## Making "parallel" builds
diff --git a/Introduce-a-new-service,-library-or-dependency.md b/Introduce-a-new-service,-library-or-dependency.md
index c2a913c..77c6b8d 100644
--- a/Introduce-a-new-service,-library-or-dependency.md
+++ b/Introduce-a-new-service,-library-or-dependency.md
@@ -10,7 +10,7 @@ First, let me list the services that we use today. That may illustrate the choic
 * java and kotlin compiler, for compilation
 * We use [gradle](https://github.com/ankidroid/Anki-Android/blob/main/gradlew) as a build system.
 * We use [open collective](https://opencollective.com/ankidroid) for donations,
-* We use [crowdin](https://crowdin.com/project/ankidroid) for translation,
+* We use [crowdin](https://crowdin.com/project/ankidroid) and [pontoon](https://i18n.ankiweb.net/) for translation,
 * We use github to host code, host our wiki, and a lot of automated [actions](https://github.com/ankidroid/Anki-Android/tree/main/.github/workflows) such as automated testing, linting, adding milestone to PR, publishing an update, updating translation from, hosting various alpha binaries,
 * We use [codecove](https://codecov.io/gh/ankidroid/Anki-Android/) for code coverage by test,
 * We use Play Store, F-store and Amazon store to distribute our app to users and update the apps,
diff --git a/Translating-AnkiDroid.md b/Translating-AnkiDroid.md
index ba32478..0dddf5d 100644
--- a/Translating-AnkiDroid.md
+++ b/Translating-AnkiDroid.md
@@ -39,6 +39,37 @@ To see where texts are used and check your translation, you can see screenshot o
 * Some translation strings may have many plural forms in your language. These are represented by labels like `one`, `few`, `many`, etc. in Crowdin.
 You can find the meanings of these terms for your language [here](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html).
 
+# AnkiDroid specific translations on Pontoon:
+
+  It is a recently-developed system that makes it easier for translators to deal with plurals, and makes it easier for developers to provide useful comments to help with translation. Steps to follow : 
+  * Firstly , you need to create an account in order to make changes on https://anki.tenderapp.com/discussions/private with  the following information:
+    1. The language or languages you'd like to translate.
+    2. Your email address. Please note that the email address you provide will be visible to people browsing GitHub.
+    3. The username you'd like to use (for example, 'bob5')
+    4. Please include the following text in your message: "I license any translations I contribute under the 3-clause BSD license."
+  * You must now visit to https://i18n.ankiweb.net/ and sign in to your account . 
+  * Choose a language.
+  * Select one of the project(core,desktop,mobile).
+  * Choose one of the resourse . 
+  * Selece any of the filter acoording to the translation status.(by default = all)
+  * Green bullet=translated, Grey bullet= Missing .  
+  * Terms like "%s", "%1$d" are placeholders for strings or numbers which will be filled later by AnkiDroid. They must not be changed, e.g. reversed ("1%d2") or filled with  spaces ("% s").
+ 
+
+For each grey bullet, translate the English text to your language. 
+Here is an eg of simple replacement in pontoon .
+**Simple Replacement**
+
+<img src="https://translating.ankiweb.net/anki/simple-replacement@2x.png" height=300></img>
+* When the text is a simple string, all you need to do is write the text in your native language and click Save (or press the Enter key).
+* Under the English text, many strings will contain a comment to help you understand where the string is being used, or to give an example of how it appears.
+* "Context" is the short name for this string, and may sometimes give you a hint as to where it is used or what it is trying to represent.
+
+
+**Tips:**
+* Many languages change words depending on number. For example, English uses "1 cat", but "3 cats".
+You can find the meanings of these terms for your language [here](https://translating.ankiweb.net/intro.html).
+
 ## Logic of the separation in different files
 
   * android\_market.xml : Text seen by Android users who see AnkiDroid in the Market, and are pondering whether to install it or not.
diff --git a/Translation-of-string-resources.md b/Translation-of-string-resources.md
index 22e0331..f13a18d 100644
--- a/Translation-of-string-resources.md
+++ b/Translation-of-string-resources.md
@@ -1,5 +1,5 @@
 # Translation
-Here is a documentation on adding string resources , which will get translated by crowdin.
+Here is a documentation on adding string resources , which will get translated either by crowdin or by pontoon.
 
 ## Steps are:

```

@mikehardy hi! here is the diff output for the git wiki changes. Please take a look...

**Comment by lonewolf2208** [comment]
Good day, @david-allison  If you could evaluate and close this PR, it would be beneficial.

**Comment by mikehardy** [comment]
Sorry this took so long @lonewolf2208 I think this looks fine - please feel free to add these changes to the wiki if you have not already. Thank you!

**Comment by lonewolf2208** [comment]
Hello @mikehardy can you tell me how to merge these changes to wiki . Should I create a new PR or is there any other way

**Comment by lonewolf2208** [comment]
I have made the changes on wiki you can check . @mikehardy

**Comment by mikehardy** [comment]
Excellent, thank you!

**Pull request closed without merging**
