### PR TITLE
Update build tools and support libraries

### PR DESCRIPTION
**Pull request by hssm**

### CODE REVIEW

**Comment by timrae** [comment]
How come you closed the last one? Do you want me to merge or put out an alpha?

**Comment by hssm** [comment]
Merge it.

They released new updates today and I didn't want the PR merged until I updated it. But it turns out you can't reopen a PR if you force push a branch, so I had to open a new one.

**Comment by timrae** [comment]
Ah yeah, weird "feature".
Btw, what are these new license things?

**Comment by hssm** [comment]
Travis was failing on some license stuff that it (or gradle?) is meant to accept automatically.

Got it from https://github.com/travis-ci/travis-ci/issues/6555

**Pull request merged**
