### PR TITLE
implement themed icon on Android 13 or higher

### PR DESCRIPTION
**Pull request by Alpaca131**
## Purpose / Description
Implementing themed icon feature on Android 13 or higher.

## Fixes
This isn't a bug fix.

## Approach
Added a monochrome icon.

## How Has This Been Tested?
I've ran the build on API 33 Emulator with themed icon enabled, and confirmed the app icon shows properly in the home screen.

## Learning (optional, can help others)
[Adaptive icons | Android Developers](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Screenshots of SDK 33 emulator, Pixel 2:
image

image

---
The code looks really nice, and I like having this new feature

About the icon, I think that if the Anki star borders (the white ones on the default icon) used the monochrome color (the grey on the screenshots) and the filling (the blue on the default icon) used the background color (the green/light blue on the screenshots), it would look better

**Comment by Alpaca131** [comment]
That seems great! I tested two types of icons. Which do you think is the best?
<Plan1>
image1
image2
<Plan2>
image3
image4

Personally, I prefer Plan2 more, though both are cool!

**Comment by Alpaca131** [comment]
I made a subtle change to the fillAlpha of the star shape inside. 
image
image
How would you think?

**Comment by Alpaca131** [comment]
In dark mode and in light mode.
icon1
image

**Comment by Alpaca131** [comment]
idk why the test failed, because it builds normally on my PC. 
I made tiny changes to the color code so I hope it will work.

**Review by BrayanDSO — APPROVED** [review]
Approving because the change looks really good and I'm fine with either of the options provided (Plan 1 or 2), although I personally prefer Plan 1. 

I'm going to leave to reviewer number 2 and @Alpaca131 to decide

**Comment by oakkitten** [comment]
Can't decide between plans, but how about:
* thicker strokes, to be in line with other apps
* make edges of words in “lines of text” rounded
* fewer “lines of text”, and perhaps make it more dense, to move them farther from the edges

**Comment by Alpaca131** [comment]
I've installed custom pixel launcher that provides unofficial themed icons for third-party apps, and
AnkiDroid's icon was included in that.

**Comment by Alpaca131** [comment]
> Can't decide between plans, but how about:
> * thicker strokes, to be in line with other apps
> * make edges of words in “lines of text” rounded
> * fewer “lines of text”, and perhaps make it more dense, to move them farther from the edges

That's sound nice! I would try it.
But for the second one, I don't think we can notice that difference whether the edge is rounded or sharped at the screen size of smartphones.

**Review by Koudinka — APPROVED** [review]

**Review by lukstbit — APPROVED** [review]
Design and me are incompatible so I'm ok with the current iteration of the icon.

@Alpaca131 Thanks for contributing. If you don't have anything to add I'll soon merge this PR.

@oakkitten 

> to move them farther from the edges

I agree with this and I actually tried to do it myself and didn't like it. The problem is that the top line doesn't go the full width and the star also stands out a bit. So, no matter how I tried to center the icon and leave it some margin it just looked slightly off to me. You can see this by tweaking the root `group` tag(I used `android:scaleY="0.9" android:scaleX="0.9" android:translateX="55"  android:translateY="55"` for example). 

I want to merge this PR to be able to update some dependencies, if you feel strongly about this please open an issue.

**Pull request merged**
