### PR TITLE
Fixed #8347 adding the password/email icon to the left hand side of the boxes.

### LINKED ISSUE #8347: Modifying login UI of the app
**Modifying login UI of the app**
Right now, the thing that the Login UI of the AnKidroid app is certainly quite good but the UI is not like premium. So I would like to improve the Login UI of the app .

**Describe the solution you'd like**
Moving ( Email Address & password) EditText  in a rounded box & login button corners in rounded form .

**Additional context**
Demo like this -:

https://user-images.githubusercontent.com/72181295/112653217-35821480-8e74-11eb-9651-2ad744ae919a.mp4

### PR DESCRIPTION
**Pull request by Prashant830**
## Purpose / Description
At login UI , password /email icon is missing so I adding the password/email icon to the left hand side of the EditText boxs.

## Fixes
fixes #8347 

## Approach
1  Added email icon at email EditText box
2  Added  password icon at password EditText box

## How Has This Been Tested?

Tested this UI with different sizes of devices.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
This looked better in https://github.com/ankidroid/Anki-Android/pull/8355. Can you close this and reopen that?

**Comment by Prashant830** [comment]
@david-allison-1 Leave PR #8355. See this PR, I made all the changes in it like: - email / password icon colors change

**Comment by david-allison-1** [comment]
Could you please revert to the implementation that you used in the previous approved PR. 

It was fine to be merged, and I preferred the implementation using a different icon (as the colors here don't look great)

**Comment by Prashant830** [comment]
Okay
Thanks for the reply

**Comment by david-allison-1** [comment]
I'll take this on if it gets closed as stale. Nice to have

**Pull request closed without merging**
