### PR TITLE
App is not getting restarted when switching between day and night mode.

### LINKED ISSUE #8351: [App is getting restarted when switching between day and night mode]
###### Reproduction Steps

1.  Click on the night mode button
2.  You will see splash screen again

###### Expected Result
It should not show splash screen, it should change current be on current activity.

###### Actual Result
We see splash screen again

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Arnold2381**
## Purpose / Description
Every time the user was changing the light mode, the app was getting restarted

## Fixes
Fixes #8351 

## Approach
In the previous code, after clicking the light mode change toggle, the stack was created with the new task added to the previous stack and started because of which the splash screen was loaded too. I have changed that too starting a newActivity instead.

## How Has This Been Tested?
https://user-images.githubusercontent.com/46752548/115993514-c1609b00-a5f0-11eb-8960-67ff94b19f9b.mp4

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by Arnold2381** [comment]
@mikehardy  can you please see if this is okay?

**Comment by mikehardy** [comment]
I definitely will but please be patient I'm focusing all attention on release-2.15 blockers as top priority and I have a lot less time during the work week unfortunately

**Review by mikehardy — COMMENTED** [review]
@Arnold2381 ! Thank you so much for your patience, I am so sorry it took this long to examine this.

I have questions on this:
- the method is named with phrase "invalidate back stack" - does this still invalidate the back stack?
- there are other places where this is called, does the new behavior still meet the expectations of all other callers?

**Comment by Arnold2381** [comment]
@mikehardy Sorry for the late reply. I looked for it, its not meeting the expectations of one of the callers. I will have to look for an another method I guess.

**Pull request closed without merging**
