### PR TITLE
Adds CSS to hide content until MathJax renders.

### PR DESCRIPTION
**Pull request by adamwolf**
## Purpose / Description
Mathjax shouldn't show the markup and then rewrite it with the rendered output.  I had set this all up before, having the card template start with a hidden css class, and then removing it when mathjax is done rendering--but I forgot to include the mathjax.css file where I defined it.  This was also creating an ugly message in logcat.

## Fixes
https://github.com/ankidroid/Anki-Android/issues/5377

## Approach
Make the hidden class actually not show things.

## How Has This Been Tested?

Verified on a device, on Mathjax and non mathjax cards.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by adamwolf** [comment]
The new behavior, as of this patch, doesn't seem bad.  I don't think it's perfect.

It doesn't seem to add a noticeable delay or blip on non-mathjax cards, which is good.

Right now, on mathjax cards, it does blip the question part when the answer is revealed. If this is worse than before, we could look into moving the hidden class to the question or answer part.  I took a look, and it doesn't look like we have labeled divs for the question and the answer halves... would we want to add these?

My laptop is at the shop for a few more days than expected, so I'm not sure we'd want to wait until I have time to tune this up perfectly.  Let me know what you all think.

**Comment by adamwolf** [comment]
Works for me!

**Comment by adamwolf** [comment]
Actually, @timrae, can we hold off on merging this for a day or two?  I want to rename the CSS class from hidden to something else.  @glutanimate uses hidden in Cloze Overlapper and maybe others as well.  I know we can't guarantee clashes but I think I'll do something like mathjax-not-rendered-yet or something :)

**Comment by timrae** [comment]
Sure no problem

**Comment by glutanimate** [comment]
@adamwolf Thanks for taking this into consideration! In retrospect, I wish I had had the same foresight with when I wrote those add-on templates. This will definitely serve as a reminder to choose more specific CSS names in the future.

**Comment by adamwolf** [comment]
@glutanimate I love your stuff, I definitely want to make sure it works here too :) (I just signed up for your Patreon the other day.  I'd love to talk about AnJoy sometime...)

@timrae I just pushed the class name change.  Works for me.  I changed it from "hidden" to "mathjax-hasnt-rendered-yet".  A little long, but obvious what it is!  Easy to change though, so let me know if it needs updates before it's ready.

**Comment by mikehardy** [comment]
for naming collisions, always best to prefix if possible e.g. "ankidroid_blah blah blah.css" if it's really specific to something/anything, use that thing as the prefix, then description as name. Not worth making a change, just a strategy I use successfully

**Pull request merged**
