### PR TITLE
Fix: androidTest/DeckPickerTest

### PR DESCRIPTION
**Pull request by Kshitij09**
## Purpose / Description
DeckPickerTest expecting the `StudyOptionsFragment` after adding a new card to a deck and pressing back is failing on both Mobile as well as Tablet. Reason:
* Incorrect viewId for Dialog's EditText
* pressBack at the first attempt is not working

## Approach
* As per the `afollestad/material-dialogs` (v0.9.6.0)

    https://github.com/afollestad/material-dialogs/blob/03fed5b82196063a983a986128cc64ec98a321f7/core/src/main/java/com/afollestad/materialdialogs/DialogInit.java#L514

    The EditText within a Dialog has id `android.R.id.input`. Doing the required id change fixed the first part of the issue. 

* As per the observations, `pressBack()` is not working on the first attempt. Calling it twice fixes the 2nd part of the issue.

## How Has This Been Tested?

Running tests on Mobile and Tablet emulator (API 32)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
Awesome!

**Review by mikehardy — CHANGES_REQUESTED** [review]
Neat! Unfortunately when I pull it locally and run it against API24 and API31 emulators it doesn't appear to work :thinking: 

```

com.ichi2.anki.DeckPickerTest > checkIfClickOnCountsLayoutOpensStudyOptionsOnMobile[TestingAVD_API-24_TAG-GAPI(AVD) - 7.0] FAILED 
        androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId() is <2131296681/com.ichi2.anki:id/fab_main>
        

com.ichi2.anki.NoteEditorTabOrderTest > testTabOrder[TestingAVD_API-24_TAG-GAPI(AVD) - 7.0] SKIPPED 

com.ichi2.anki.NoteEditorTabOrderTest > testTabOrder[TestingAVD_API-31_TAG-PLAY(AVD) - 12] SKIPPED 
Tests on TestingAVD_API-24_TAG-GAPI(AVD) - 7.0 failed: There was 1 failure(s).
Apr 14, 2022 4:06:34 PM com.google.testing.platform.RunnerImpl$Companion summarizeAndLogTestResult
SEVERE: Execute com.ichi2.anki.DeckPickerTest.checkIfClickOnCountsLayoutOpensStudyOptionsOnMobile: FAILED
androidx.test.espresso.NoMatchingViewException: androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId() is <2131296681/com.ichi2.anki:id/fab_main>

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=932, height=551, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(932xwrap) gr=#11 sim=#20 ty=2 fl=#1800002 fmt=-3 wanim=0x7f110007 needsMenuKey=2}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}

+->LinearLayout{id=-1, visibility=VISIBLE, width=932, height=551, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@c2a1e6d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}

+-->ViewStub{id=16909288, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@8825aa2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}

+-->FrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=932, height=551, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@26a2333, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}

+--->MDRootLayout{id=-1, visibility=VISIBLE, width=932, height=551, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@dcf7eee, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=5}

+---->LinearLayout{id=2131296875, res-name=md_titleFrame, visibility=VISIBLE, width=932, height=166, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@eee521c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}

+----->AppCompatImageView{id=2131296869, res-name=md_icon, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@625ae25, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}

+----->AppCompatTextView{id=2131296874, res-name=md_title, visibility=VISIBLE, width=806, height=71, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@eb89bfa, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=63.0, text=SD card full, input-type=0, ime-target=false, has-links=false}

+---->ScrollView{id=2131296866, res-name=md_contentScrollView, visibility=VISIBLE, width=932, height=217, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@17cc5ab, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=166.0, child-count=1}

+----->AppCompatTextView{id=2131296863, res-name=md_content, visibility=VISIBLE, width=932, height=175, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@b2807a1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=21.0, text=Backup not saved. Not enough space left on SD card. Lower the backup depth or remove some other files., input-type=0, ime-target=false, has-links=false}

+---->MDButton{id=2131296861, res-name=md_buttonDefaultNeutral, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@9e47dc6, tag=NEUTRAL, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false}

+---->MDButton{id=2131296860, res-name=md_buttonDefaultNegative, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@1c01187, tag=NEGATIVE, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false}

+---->MDButton{id=2131296862, res-name=md_buttonDefaultPositive, visibility=VISIBLE, width=189, height=126, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@988c8b4, tag=POSITIVE, root-is-layout-requested=false, has-input-connection=false, x=711.0, y=404.0, text=OK, input-type=0, ime-target=false, has-links=false}
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1566)
at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:12)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:7)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:8)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:4)
at com.ichi2.anki.DeckPickerTest.createDeckWithCard(DeckPickerTest.java:103)
at com.ichi2.anki.DeckPickerTest.checkIfClickOnCountsLayoutOpensStudyOptionsOnMobile(DeckPickerTest.java:72)
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId() is <2131296681/com.ichi2.anki:id/fab_main>

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=932, height=551, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(932xwrap) gr=#11 sim=#20 ty=2 fl=#1800002 fmt=-3 wanim=0x7f110007 needsMenuKey=2}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}

+->LinearLayout{id=-1, visibility=VISIBLE, width=932, height=551, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@c2a1e6d, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}

+-->ViewStub{id=16909288, res-name=action_mode_bar_stub, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@8825aa2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}

+-->FrameLayout{id=16908290, res-name=content, visibility=VISIBLE, width=932, height=551, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@26a2333, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1}

+--->MDRootLayout{id=-1, visibility=VISIBLE, width=932, height=551, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@dcf7eee, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=5}

+---->LinearLayout{id=2131296875, res-name=md_titleFrame, visibility=VISIBLE, width=932, height=166, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@eee521c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}

+----->AppCompatImageView{id=2131296869, res-name=md_icon, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@625ae25, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}

+----->AppCompatTextView{id=2131296874, res-name=md_title, visibility=VISIBLE, width=806, height=71, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@eb89bfa, tag=null, root-is-layout-requested=false, has-input-connection=false, x=63.0, y=63.0, text=SD card full, input-type=0, ime-target=false, has-links=false}

+---->ScrollView{id=2131296866, res-name=md_contentScrollView, visibility=VISIBLE, width=932, height=217, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@17cc5ab, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=166.0, child-count=1}

+----->AppCompatTextView{id=2131296863, res-name=md_content, visibility=VISIBLE, width=932, height=175, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@b2807a1, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=21.0, text=Backup not saved. Not enough space left on SD card. Lower the backup depth or remove some other files., input-type=0, ime-target=false, has-links=false}

+---->MDButton{id=2131296861, res-name=md_buttonDefaultNeutral, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@9e47dc6, tag=NEUTRAL, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false}

+---->MDButton{id=2131296860, res-name=md_buttonDefaultNegative, visibility=GONE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=true, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@1c01187, tag=NEGATIVE, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=, input-type=0, ime-target=false, has-links=false}

+---->MDButton{id=2131296862, res-name=md_buttonDefaultPositive, visibility=VISIBLE, width=189, height=126, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.view.ViewGroup$LayoutParams@988c8b4, tag=POSITIVE, root-is-layout-requested=false, has-input-connection=false, x=711.0, y=404.0, text=OK, input-type=0, ime-target=false, has-links=false}
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1566)
```

**Comment by Kshitij09** [comment]
@mikehardy does it fail all the time? Or it's behaving flaky and succeeding occasionally

**Comment by Kshitij09** [comment]
It's giving me the following error when running on API24. I think there's something from instrumentation libs not supporting this API level.
```
SEVERE: Test execution failed with fatal error!
com.google.testing.platform.api.plugin.PluginException: Exception thrown during onBeforeAll invocation of plugin com.google.testing.platform.plugin.android.AndroidDevicePlugin.
	at com.google.testing.platform.plugin.PluginLifecycleKt.invokeOrThrow(PluginLifecycle.kt:216)
	at com.google.testing.platform.plugin.PluginLifecycleKt.invokeOrThrow$default(PluginLifecycle.kt:205)
	at com.google.testing.platform.plugin.PluginLifecycle$onBeforeAll$1.invoke(PluginLifecycle.kt:92)
	at com.google.testing.platform.plugin.PluginLifecycle$onBeforeAll$1.invoke(PluginLifecycle.kt:88)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:105)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent$default(Telemetry.kt:98)
	at com.google.testing.platform.plugin.PluginLifecycle.onBeforeAll(PluginLifecycle.kt:88)
	at com.google.testing.platform.executor.SingleDeviceExecutor$execute$4.invoke(SingleDeviceExecutor.kt:86)
	at com.google.testing.platform.executor.SingleDeviceExecutor$execute$4.invoke(SingleDeviceExecutor.kt:86)
	at com.google.testing.platform.executor.SingleDeviceExecutor.runUnlessCancelled(SingleDeviceExecutor.kt:105)
	at com.google.testing.platform.executor.SingleDeviceExecutor.execute(SingleDeviceExecutor.kt:86)
	at com.google.testing.platform.RunnerImpl.run(RunnerImpl.kt:108)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy$run$4.invoke(NonInteractiveServerStrategy.kt:80)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy$run$4.invoke(NonInteractiveServerStrategy.kt:79)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:66)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy.run(NonInteractiveServerStrategy.kt:79)
	at com.google.testing.platform.main.MainKt$main$4.invokeSuspend(Main.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.google.testing.platform.main.MainKt.main(Main.kt:66)
	at com.google.testing.platform.main.MainKt.main$default(Main.kt:34)
	at com.google.testing.platform.main.MainKt.main(Main.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.testing.platform.launcher.Launcher.main(Launcher.java:149)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 120000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:158)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:128)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.base/java.lang.Thread.run(Thread.java:829)

Apr 15, 2022 3:45:50 AM com.android.tools.utp.plugins.host.additionaltestoutput.AndroidAdditionalTestOutputPlugin deviceShellAndCheckSuccess
WARNING: Shell command failed (1): ls "/storage/emulated/0/Android/data/com.ichi2.anki/files/test_data"
ls: /storage/emulated/0/Android/data/com.ichi2.anki/files/test_data: No such file or directory

Apr 15, 2022 3:45:50 AM com.android.tools.utp.plugins.host.additionaltestoutput.AndroidAdditionalTestOutputPlugin afterAll
WARNING: Failed to retrieve additional test outputs from device.
com.android.ddmlib.SyncException: Remote object doesn't exist!
	at com.android.ddmlib.SyncService.pullFile(SyncService.java:341)
	at com.android.ddmlib.internal.DeviceImpl.pullFile(DeviceImpl.java:1083)
	at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDevice.pullFile(DdmlibAndroidDevice.kt)
	at com.android.tools.utp.plugins.deviceprovider.ddmlib.DdmlibAndroidDeviceController.pull(DdmlibAndroidDeviceController.kt:254)
	at com.google.testing.platform.executor.DeviceControllerProxy$pull$2.invoke(DeviceControllerProxy.kt:82)
	at com.google.testing.platform.executor.DeviceControllerProxy$pull$2.invoke(DeviceControllerProxy.kt:82)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:66)
	at com.google.testing.platform.executor.DeviceControllerProxy.pull(DeviceControllerProxy.kt:79)
	at com.android.tools.utp.plugins.host.additionaltestoutput.AndroidAdditionalTestOutputPlugin.copyAdditionalTestOutputsFromDeviceToHost(AndroidAdditionalTestOutputPlugin.kt:222)
	at com.android.tools.utp.plugins.host.additionaltestoutput.AndroidAdditionalTestOutputPlugin.afterAll(AndroidAdditionalTestOutputPlugin.kt:206)
	at com.google.testing.platform.plugin.PluginLifecycle$onAfterAll$1$2$1.invoke(PluginLifecycle.kt:180)
	at com.google.testing.platform.plugin.PluginLifecycle$onAfterAll$1$2$1.invoke(PluginLifecycle.kt:179)
	at com.google.testing.platform.plugin.PluginLifecycleKt$invokeOrThrow$1.invoke(PluginLifecycle.kt:213)
	at com.google.testing.platform.plugin.PluginLifecycleKt$invokeOrThrow$1.invoke(PluginLifecycle.kt:212)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:105)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent$default(Telemetry.kt:98)
	at com.google.testing.platform.plugin.PluginLifecycleKt.invokeOrThrow(PluginLifecycle.kt:212)
	at com.google.testing.platform.plugin.PluginLifecycleKt.invokeOrThrow$default(PluginLifecycle.kt:205)
	at com.google.testing.platform.plugin.PluginLifecycle$onAfterAll$1.invoke(PluginLifecycle.kt:179)
	at com.google.testing.platform.plugin.PluginLifecycle$onAfterAll$1.invoke(PluginLifecycle.kt:173)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:105)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent$default(Telemetry.kt:98)
	at com.google.testing.platform.plugin.PluginLifecycle.onAfterAll(PluginLifecycle.kt:173)
	at com.google.testing.platform.executor.SingleDeviceExecutor$execute$3.invoke(SingleDeviceExecutor.kt:83)
	at com.google.testing.platform.executor.SingleDeviceExecutor$execute$3.invoke(SingleDeviceExecutor.kt:82)
	at com.google.testing.platform.result.TestResultListenerManager.afterTestSuite(TestResultListenerManager.kt:140)
	at com.google.testing.platform.RunnerImpl.run(RunnerImpl.kt:118)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy$run$4.invoke(NonInteractiveServerStrategy.kt:80)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy$run$4.invoke(NonInteractiveServerStrategy.kt:79)
	at com.google.testing.platform.core.telemetry.common.noop.NoopDiagnosticsScope.recordEvent(NoopDiagnosticsScope.kt:35)
	at com.google.testing.platform.core.telemetry.TelemetryKt.recordEvent(Telemetry.kt:66)
	at com.google.testing.platform.server.strategy.NonInteractiveServerStrategy.run(NonInteractiveServerStrategy.kt:79)
	at com.google.testing.platform.main.MainKt$main$4.invokeSuspend(Main.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.google.testing.platform.main.MainKt.main(Main.kt:66)
	at com.google.testing.platform.main.MainKt.main$default(Main.kt:34)
	at com.google.testing.platform.main.MainKt.main(Main.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.testing.platform.launcher.Launcher.main(Launcher.java:149)


Platform error occurred when running the UTP test suite
```

However, it's working on API31 for me, both mobile and tablet. Should I raise an issue for the same?

**Comment by mikehardy** [comment]
On API24 I am getting a different failure - yours looks like the one from our CI emulator test flake at the moment - it's what it looks like when your emulator is not actually fully running for whatever reason? Perhaps deleting data and setting up the emulator from scratch again (see #10601)

My failure is that the view hierarchy doesn't have a match, and I just re-tested with a bunch of iterations, it fails every time.

API31 worked - it may have worked before and I wasn't paying attention, I edited my comment above to reflect uncertainty

I have API25-30 laying around too so I started them all up.

image


API25: test1 failed, same view hierarchy error, test2 worked, test3 failed
API26: test1 worked, test2 worked, test3 worked
API27: test1 worked, test2 worked, test3 worked
API28: test1 worked, test2 worked, test3 failed
API29: test1 failed, same view hierarchy error, test2 failed again, test3 failed
API30: test1 failed, same view hierarchy error, test2 failed again, test3 failed

So, still looks flaky to me, this isn't reliable enough to include at the moment

**Comment by Kshitij09** [comment]
Got it. So should we merge these changes and `@Ignore` mobile test or not take any of these changes. Can you share behavior without this change, from `main` branch? Maybe we'll get to know if there are any improvements

**Comment by mikehardy** [comment]
It's a flaky test still. My test results were inconsistent even on same platform.
So this will simply not merge at all, sorry
UI tests are *notoriously* difficult for this reason Perhaps re-implementing it as a unit test in robolectric would be better - it is possible to send Robolectric a "Config" (we do this to change fake "device language" for some tests) so you can send different screen sizes and then probe behavior?

**Comment by Kshitij09** [comment]
Closing this as of now. I believe this is not a high priority. Will come up with unit test for the same later

**Pull request closed without merging**
