### PR TITLE
Dismiss all Dialog Fragment

### LINKED ISSUE #13740: [BUG]: DeckPickerMenuOption is still alive on screen after selecting an option
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Long press to a Deck untill DeckOptionMenu shows up and choose options like , "Rename Deck" or "Create subdeck".

https://user-images.githubusercontent.com/91174350/234812812-f6da918a-6799-4c21-979d-47ae9054d05e.mp4

### Expected behaviour

DeckOption Menu should close after choosing options.

### Actual behaviour

It still alive on screen after selecting an option

### Debug info

```text
AnkiDroid Version = 2.15.6
Android Version = 11
Device = Redmi note 8 pro
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### LINKED ISSUE #13751: [Bug] Delete Deck Dialog Dismisses Immediately Upon Opening
###### Reproduction Steps

1. Create Deck
2. Add Cards
3. Delete Deck

###### Expected Result
Delete Deck Dialog must be shown as usual 

###### Actual Result
Delete Deck Dialog dismisses when opening

https://user-images.githubusercontent.com/65113071/235163403-ab577638-5f19-4ded-b828-e30c2cce4d56.mp4

###### Debug info
AnkiDroid Version = 2.16alpha98-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = c070f6dc-866e-4fcf-8bc1-2aa53bcca93d

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by nayeemdv**
## Purpose / Description
This PR Fixes issues because of my last PR(#13741)..

## Fixes
Fixes #13740
Fixes #13751 

## Approach
I find out that my last PR (#13741)  dismissed all the fragment dialog even the upcoming ones...
So i added "dismissAllDialogFragments" only where it needed and removed the overall "dismiss"..
it resolves for all the options  Except "Custom Study Option"..

## How Has This Been Tested?
Redmi note 8 pro

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by nayeemdv** [comment]
@mikehardy Please review this!!

**Comment by nayeemdv** [comment]
my bad I forgot to sync the project with upstream!!

**Review by criticalAY — APPROVED** [review]
Seems good to me

**Comment by criticalAY** [comment]
Fixes #13751

**Review by mikehardy — APPROVED** [review]
Nice! Thank you

**Pull request merged**
