### PR TITLE
Update ic_flag_blue.xml

### PR DESCRIPTION
**Pull request by Jennifer202006**
The blue colour is dark. 
I think the lighter one is better.

## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes _Link to the issues._

## Approach
_How does this change address the problem?_

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration (SDK version(s), emulator or physical, etc)

## Learning (optional, can help others)
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

## Checklist
_Please, go through these checks before submitting the PR._

- [ ] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [ ] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [ ] You have commented your code, particularly in hard-to-understand areas
- [ ] You have performed a self-review of your own code

### CODE REVIEW

**Comment by Jennifer202006** [comment]
Please check the attached file.&nbsp;











-----
Best&nbsp;Regards,
Jennifer

---Original---

**Comment by Jennifer202006** [comment]
Yes. The colour in the Anki Deskto is ok.

**Comment by mikehardy** [comment]
Matching Desktop in general would be great, @Jennifer202006 thanks for proposing the change!

**Comment by mikehardy** [comment]
@Jennifer202006 

We are waiting on an update to the PR following suggestion to update all colors in the array to match anki desktop:

> Could we use the same blue as is in Anki Desktop? `#77AAFF`
> 
> https://github.com/ankitects/anki/blob/9dcbb8958d64f5be7bfa01201817947eec388c4c/qt/ts/src/reviewer.ts#L111
> 
> We might want to change all flags to match the values in that array?
> 
> Could you post a screenshot of how it looks now?

**Comment by Jennifer202006** [comment]
> @Jennifer202006
> 
> We are waiting on an update to the PR following suggestion to update all colors in the array to match anki desktop:
> 
> > Could we use the same blue as is in Anki Desktop? `#77AAFF`
> > https://github.com/ankitects/anki/blob/9dcbb8958d64f5be7bfa01201817947eec388c4c/qt/ts/src/reviewer.ts#L111
> > We might want to change all flags to match the values in that array?
> > Could you post a screenshot of how it looks now?

**Comment by Jennifer202006** [comment]
Screenshot_20200622_014848

**Pull request merged**
