### PR TITLE
Catch up on libanki changes

### PR DESCRIPTION
**Pull request by hssm**
For the first commit, the value that was removed was also being shuffled around the place for no reason, so I removed all traces of it.

### CODE REVIEW

**Comment by timrae** [comment]
Auto-merging these patches into develop is causing me too much strife... would you be able to separately commit these and all future patches into each branch please?

**Comment by timrae** [comment]
The ShowcaseView commit as well please

**Comment by hssm** [comment]
Sure thing, give me a few minutes.

**Comment by timrae** [comment]
Thanks it might save me a nervous breakdown! 
Auto-merging from release-xxx branches into develop is usually fine, but 2.4.x maintenance in develop is a recipe for disaster

**Pull request merged**
