### PR TITLE
Hotfix 2.6.2

### PR DESCRIPTION
**Pull request by hssm**
@timrae 

Here's the basis for the 2.6.2 release. I think we have enough important fixes to warrant a release soon. I omitted https://github.com/ankidroid/Anki-Android/commit/eee8b4afd04837c7dbfde9bf588166c21624c144 since it's not essential.

I might still sneak in a couple of minor fixes before we end up releasing this, but I wanted to get the process going asap.

### CODE REVIEW

**Comment by hssm** [comment]
Oh yeah I need a changelog too. I'll add that to this branch soon.

**Comment by hssm** [comment]
Okay changelog is added.

**Comment by timrae** [comment]
Theoretically hotfix releases are only [supposed](https://github.com/ankidroid/Anki-Android/wiki/Release-procedure) to be for "urgent bug fixes"; perhaps swipe to sync would fit better into a 2.7 alpha release... What do you think @hssm and anyone else following this thread?

**Comment by hssm** [comment]
My least favorite thing about that release model is that it was taking us 6+ months to get out minor enhancements to our users. I don't want to keep doing that.

Maybe "hotfix" isn't the best name for the branch but I kept it out of consistency. With the release date I'm aiming for, we get a little over a week of beta testing which I feel is enough for these small changes.

**Comment by timrae** [comment]
In principle I think all enhancements should go through proper alpha phase testing to give users a chance to give feedback on them before we release them into the wild.

I feel the current release model has been working pretty well for us in terms of quality control, and since this is a community driven open source project there should probably be an open discussion about any changes to it before such a decision is made...

**Comment by timrae** [comment]
> The release date I'm aiming for

Traditionally a decision on a release date has always been preceded by a forum post seeking community input... Even if nobody replies, I still think it's a good idea.

**Comment by timrae** [comment]
When I talked to @nicolas-raoul the other day he said that we should keep consistency with the version naming convention, and since this branch has new features, we should call it 2.7. Sound OK? I released it as 2.6.2alpha1 last month but ended up releasing it to the beta channel (accidentally at first but left it that way).

I agree that having smaller faster releases is a good idea provided they go through proper testing. I can't do SSH out of my company firewall though, so might have to handover the releasing/packaging responsibility if I become a bottleneck.

**Comment by timrae** [comment]
Acralyzer isn't showing any reports to me unfortunately, it looks like maybe it's running out of resources again

**Comment by agrueneberg** [comment]
@timrae Strange, there is still plenty of memory available. I restarted the server and compacted the CouchDB database. There was also an instance of Tomcat running, but I didn't see any apps that run on top of it so I shut it down. That should also free up some resources. Please let me know if it still doesn't work for you.

**Comment by hssm** [comment]
Okay let's do that then.

**Comment by timrae** [comment]
Just pulled the latest translations and released 2.7beta1. If no problems
then we can release it soon.

**Pull request merged**
