### PR TITLE
Fix `isActionButton` for `targetSdkVersion` 31

### PR DESCRIPTION
**Pull request by david-allison**
`isActionButton` is no longer be usable after `targetSdkVersion 30` and emulator tests fail.

## Purpose / Description
This allows us to bump `targetSdkVersion` from 30 to 31 without test errors.

Note: we're on 29 currently, and there are additional fixes which are required for 29 -> 30

## Approach
 Use a method on the toolbar, defined in `ToolbarUtil`.

* Remove `ActionBarOverflow` + `Test`
* `isShownInActionBar` no longer returns null
* Move `reviewerUI` onto `Reviewer`
  * No need to add `isActionButton` to other inheritors

## How Has This Been Tested?

Emulator, API 32 

* Returns `true` by default
* Returns `false` when

## Learning (optional, can help others)

`isActionButton` appears no longer be usable after API 30:

```java
@UnsupportedAppUsage(maxTargetSdk = Build.VERSION_CODES.R, trackingBug = 170729553)
```

https://cs.android.com/android/_/android/platform/frameworks/base/+/31b73ad4b9d200f308cf0ae444fcda41f533acce:core/java/com/android/internal/view/menu/MenuItemImpl.java;l=46;drc=5f0edaaaf55f26420345a1cd690b988f752d17c6;bpv=1;bpt=0;dlc=c185f08c4a408fa7abc578851d31cdce6ad86f6f

Suggestion came from: https://stackoverflow.com/a/70515942/

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Certainly seems like a simpler way to go about it - thanks!

**Comment by oakkitten** [comment]
We are using `MenuItemImpl.isActionButton` elsewhere, does this also crash? If not, why not use here as well? `findViewById` is quite hacky & bug-prone

**Comment by oakkitten** [comment]
See this commit message about the problems with `findViewById`: [`e35b107` (#12409)](https://github.com/ankidroid/Anki-Android/pull/12409/commits/e35b107a0c72afbb38f935b67576f2297d2203ae) and the solution:

https://github.com/ankidroid/Anki-Android/blob/a71b31d3ccc331326cf48297d3351b72469af5ee/AnkiDroid/src/main/java/com/ichi2/utils/MenuUtils.kt#L29-L36

I think casting to `MenuItemImpl` is safe enough? As I understand, the only danger here is this code starting to fail to compile after library update. Also no users have complained so far, as far as I know...

**Comment by david-allison** [comment]
Agreed - casting is better. Will do this

**Pull request merged**
