### PR TITLE
Simplify schedule collection task listener

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
ScheduleCollectionTaskListener was more complex than useful. The first PR is obviously good. The second may be rejected, I would not argue, even if I believe it's an improvement overall

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Seems fine to me

**Comment by mikehardy** [comment]
@Arthur-Milchior took a conflict but otherwise I'd merge it

**Comment by mikehardy** [comment]
@Arthur-Milchior I looked at this with an eye towards resolving it myself, and it is a bit tangled because it looks like one of the methods you moved may have independently been altered to be abstract? The `@PluralRes` annotation looks simple but I'm not sure how to de-conflict the other part. Could you check it out, then we may merge

**Comment by Arthur-Milchior** [comment]
Rebased.

As you know by now, I'm always okay with rebasing myself. I was busy, it was not a priority, but I'm clearly not expecting you to do this kind of work. Especially when I publish plenty of PR editing the same part of the code at once

**Review by mikehardy — APPROVED** [review]

**Comment by mikehardy** [comment]
> Rebased.
> 
> As you know by now, I'm always okay with rebasing myself. I was busy, it was not a priority, but I'm clearly not expecting you to do this kind of work. Especially when I publish plenty of PR editing the same part of the code at once

Oh sure - I don't feel pressure either, sometimes I just check the conflicts with an eye towards fixing them because they are so obvious and it takes <1min and closes something out of the queue. I find that very satisfying, totally worth it when possible :-)

**Pull request merged**
