### PR TITLE
Hotfix 2.6.1

### PR DESCRIPTION
**Pull request by hssm**
I made it use the crowdin side for all the translations. I think it's ready for a beta now.

### CODE REVIEW

**Comment by timrae** [comment]
OK I'll make a release when I get home!

**Comment by timrae** [comment]
Can you please remove d2cf630? Version incrementing is done with the release script, so that commit would lead to beta2 being the first beta

**Comment by hssm** [comment]
Done.

**Comment by timrae** [comment]
Done, thanks for resolving the merge conflicts!

**Pull request merged**
