### PR TITLE
Migrate CollectionUtilsTest to Kotlin

### PR DESCRIPTION
**Pull request by oyeraghib**
## Purpose / Description
Migrated CollectionUtilsTest to Kotlin

## How Has This Been Tested?
Tests were running on local machine (Windows 11)
Android Studio Version : Bumblebee 2021.1.1 Patch 2

collection utils test

## Checklist

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
Needs to follow the steps listed in the docs: https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md

**Comment by oyeraghib** [comment]
> Needs to follow the steps listed in the docs: https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md

While following this link I am unable to make a commit from Android Studio. Actually I am generally not able to commit anything from Android Studio because of issue https://github.com/ankidroid/Anki-Android/issues/10549, so that's why I am trying to commit using --no-verify on Git Bash.

**Comment by david-allison** [comment]
> While following this link I am unable to make a commit from Android Studio. Actually I am generally not able to commit anything from Android Studio because of issue #10549, so that's why I am trying to commit using --no-verify on Git Bash.

The first step is to get to a workflow where you can commit and the checks pass.

**Comment by oyeraghib** [comment]
I am closing this pull request and will make a new one following the guidelines in the docs.

**Pull request closed without merging**
