### PR TITLE
Kotlin Cleanup : renamed variable (val --> value) in CardUtils.kt

### PR DESCRIPTION
**Pull request by divyansh-dxn**
## Purpose / Description
_Describe the problem or feature and motivation_
Kotlin Cleanup: renamed `val` to value in CardUtils.kt

## Fixes
Fixes part of [#10489](https://github.com/ankidroid/Anki-Android/issues/10489)

## Approach
_How does this change address the problem?_
1. Renamed the variable at all occurrences 

## How Has This Been Tested?
Passed all the unit tests and runs as expected on Realme 6i API 31

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [   ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [   ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by ShridharGoel** [comment]
Can you add a better PR title?

**Review by ShridharGoel — APPROVED** [review]

**Review by david-allison — APPROVED** [review]
Awesome!

Notes:

* `Fixes #X` links + closes the issue. This issue should still be open
* Use `[x]` for checkboxes

**Comment by david-allison** [comment]
? Why did you close this

**Comment by divyansh-dxn** [comment]
Sorry I tried to rename the branch, I didn't know it would delete the current PR

**Comment by divyansh-dxn** [comment]
I'll just create a new one

**Comment by divyansh-dxn** [comment]
https://github.com/ankidroid/Anki-Android/pull/10519
I've re-created the PR. Have a look.

**Pull request closed without merging**
