### PR TITLE
[KotlinCleanup] Utils

### PR DESCRIPTION
**Pull request by n1snt**
## How Has This Been Tested?

- Physical device 
- Tests

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented on your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [x] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]

**Review by david-allison — CHANGES_REQUESTED** [review]
Legit failure

> Task :AnkiDroid:compilePlayDebugAndroidTestKotlin FAILED
e: /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/ContentProviderTest.kt: (168, 33): Unresolved reference: collection2Array

**Comment by n1snt** [comment]
@david-allison fixed the issue.

**Comment by Arthur-Milchior** [comment]
I approve. Not clear if @david-allison approval is still valid. If so, can you please merge David?

**Review by david-allison — APPROVED** [review]
All good now the tests pass

**Pull request merged**
