### PR TITLE
Add share question button

### PR DESCRIPTION
**Pull request by GAumala**
Hello everyone! I made a new feature that I'd like to share with you. It's a very small change, but it has helped me a lot studying. I added a button to the toolbar menu that lets the user share the question with other apps. 

Currently I use anki to learn japanese words. I downloaded an n4 deck and started studying with that. The problem is that sometimes, words that I know absolutely nothing about appear on my study session, and I would have to copy the word, navigate to my dictionary app, paste it and look up info. Now, instead of all that hassle, with only one button, I can instantly get definitions, related words and example sentences. I'm sure others will also find it useful.

The "question" that gets shared comes from the fields array of the currently displayed card's note. If there is a better way of doing this, please let me know and I'll change it ASAP.

### CODE REVIEW

**Comment by marcardar** [comment]
I'm just guessing, but have you tried mCurrentCard.q()?

**Comment by GAumala** [comment]
That was my first attempt, but that method returns the question inside a span tag.

**Comment by timrae** [comment]
Hi, thanks for sharing. Unfortunately I don't think this is a good candidate for merging into the main codebase, as looking up just the question is a very specific usage case.

On most new versions of Android, you can just long tap on the word then select share, and choose your dictionary from the share menu; this PR would only save one click.

**Comment by timrae** [comment]
If you're interested:

One way to do get the number of taps down on Android M that I thought might be a good idea, is to improve our current "dictionary lookup" feature by adding a "LOOKUP" button to the new [floating toolbar for text selection](http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-text-selection) on Marshmallow that searches in the user's preferred dictionary.

This would get the lookup down to the same number of taps as in this PR without limiting to only the text in the question or cluttering up the toolbar.

**Comment by GAumala** [comment]
That looks pretty cool. I'd love to give it a shot, but currently I don't have any M devices...

**Comment by hssm** [comment]
It doesn't *have to* be a floating toolbar. A customized Contextual Action Bar will work as well (and we can turn it into the floating kind later on).

If you are interested in working on something like this you can continue the discussion in https://github.com/ankidroid/Anki-Android/issues/2210.

**Comment by timrae** [comment]
According to my previous investigation, it would be very difficult or impossible to use a contextual action button as there's no API to get the selected text.

**Pull request closed without merging**
