### PR TITLE
Only do color inversion as fallback when .night_mode not specified in css

### PR DESCRIPTION
**Pull request by timrae**
See the [discussion in the forum](https://groups.google.com/forum/#!topic/anki-android/XN11PNdFhOQ)... I think this is currently the best solution on the table.

### CODE REVIEW

**Comment by ospalh** [comment]
> currently the best solution

Probably.
My two ideas aren’t really better:

* Store a bit in the deck options: Could work, *if* the options were exported in shared decks
* Use another keyword like `deactivate_color_inversion`. Maybe a little bit less surprising, but more obscure

**Comment by timrae** [comment]
OK let's go with this then

**Comment by gajewsk2** [comment]
This is awesome.  Can you put this in a beta release soon? Thanks.

**Comment by timrae** [comment]
Beta is going to take a while but I'll release an alpha next week

**Pull request merged**
