### PR TITLE
Add Database check for decks with invalid config

### LINKED ISSUE #6454: Ankidroid crash via Cloud Sync ("Collection Not Opened")
###### Reproduction Steps

1. Sync on Ankidroid.
2. Error: Collection Not Opened. An error ocurred while accesssing your collection...
3. When use an possible option on "Error Handling" app not open or not sync.

collection.anki2.bak:
https://drive.google.com/file/d/13FDSaa18trXG-YMkSpxsDh9coQ_TJewa/view?usp=sharing
collection.anki (DESKTOP)
https://drive.google.com/file/d/1QXygK4yoJ7KXfgHFnBUuoFea2ULW_91e/view?usp=sharing

###### Expected Result

Sync correctly.

###### Actual Result

When I try to sync data on Ankidroid I get this error:

"Collection not opened, An error ocurred while accessing your collection. It may have been caused by a harmless bug, or there may be a problem whit it.

Try running check database, or restoring from backup by pressing the "options" button. If you continue to see this message, please file a bur report: https://docs/ankidroid.org/help.html"

Every time it shows me the failure of the collections I have 4 options in the "Error handling":
-Check database. (Nothings happen).
-Restore from Backup
-Full sync from server (Same result).
-Delete collection and create a new one. (Open but not sync)

I have tried to uninstall and clean the Ankidroid folder, have imported a security copy made with Anki Desktop, still crash.

I created the cards in Anky Desktop for Windows 2.1.26 (70784154) and I study them in AnkiDroid, everything was fine until after syncing the app show this error.
First sync ask me if i want to download or upload, I choose Upload on AnkiDesktop and Download on AnkiDroid.
I only remember create a new type of card with hints (html code included) I erased but nothings changes.

I know this problem has been discussed in other threads but I still haven't managed to solve it

What can I do? 
If the problem persists, is there an alternative so that I can continue studying cards from my mobile?

###### Debug info

AnkiDroid Version = 2.11.1

Android Version = 10

ACRA UUID = 7501521e-a2cc-44d4-a8d7-22e4c3817b48

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum (I can´t solve it...)
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison-1**
## Notes

ℹ️ Happy for this to be rejected/taken to the drawing board as a "let's get to the root cause rather than work around it", I feel it's more likely that this was caused by Anki Desktop, as it's a syncing issue. 

## Purpose / Description
A user had invalid "conf" values when syncing from Anki Desktop

This meant that they could sync from Anki Desktop, but their collection was reported as corrupt in AnkiDroid, as the deck list could not be displayed

## Fixes
Fixes #6454

## Approach
Check Database

## How Has This Been Tested?

Tested on my phone - supplied collection no longer crashes after check database. My main collection showed no problems

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by dae** [comment]
Some reports have cropped up about this since .26 was released, but I haven't been able to reproduce it in local testing - adding a new option group and syncing, the new option group appears on the other device/profile. If you discover the steps that cause it, please let me know. The syncing code has subsequently been moved to Rust and the issue may already have been resolved, but with a repro case we can confirm that, and I can put out a point release with a fix.

**Comment by david-allison-1** [comment]
@dae Reproduced on `Anki Desktop Version 2.1.28 (f44597bb)`:

* `Deck Options - Add (new options group) - Close with the X`

**Comment by dae** [comment]
What am I missing?
[Untitled.mov.zip](https://github.com/ankidroid/Anki-Android/files/4778112/Untitled.mov.zip)

**Comment by david-allison-1** [comment]
Sorry for wasting your time, I can't reproduce this. I'll have another shot tonight.

**Pull request merged**
