### PR TITLE
Fix FileImport NullPointerExceptions and implement ClipData

### LINKED ISSUE #5870: [2.9 ACRA] NullPointerException: File Import
First crash for 2.9.6beta4

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/fc81b2e6-c6bb-4807-8abc-b7adfb526c20

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.IntentHandler}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3516)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3668)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:7971)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
at com.ichi2.utils.ImportUtils.handleFileImport(ImportUtils.java:2)
at com.ichi2.anki.IntentHandler.onCreate(IntentHandler.java:10)
at android.app.Activity.performCreate(Activity.java:7957)
at android.app.Activity.performCreate(Activity.java:7946)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3491)
... 11 more
```

### PR DESCRIPTION
**Pull request by david-allison-1**
## Purpose / Description
A NPE was caused by the file import.

A few stack traces imply that ClipData wasn't being handled correctly, we try to pass this into the content provider API and hope this works.

## Fixes
Fixes #5870

## Approach

* We explicitly handle null.
* We attempt to extract the URI from the clip data.
* We use [Pokémon Exception Handling](https://wiki.c2.com/?PokemonExceptionHandling) to avoid failure.

## How Has This Been Tested?

Untested. My Android still imports correctly.

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

## Review goals

* Line 84: We implicitly return null if the intent is unhandled, this seems unintentional
* The crash report logging may log far too many problems, not sure about your opinion on this.
* (optional) Ask me to unit test this

### CODE REVIEW

**Comment by david-allison-1** [comment]
> looks good - last couple commits cleared up what I would have quibbled on - I know I sometimes re-think things and re-read a few times, so I'll approve now but wait until you think it's good to go for merge

Thanks! I have no problem at all with long review times, I'd rather see things go out correctly than quickly, despite the fact that the alpha & beta process exists and does its job.

Do you have any comments on the Review Goals (bottom of the original post)?

**Comment by mikehardy** [comment]
Line 84, implicit null return, who consumes:
https://github.com/ankidroid/Anki-Android/blob/be0a768906af0b4a47b8078f78a51e01235d31dc/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.java#L37
https://github.com/ankidroid/Anki-Android/blob/be0a768906af0b4a47b8078f78a51e01235d31dc/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L688

They handle it as "success"

And what could the line produce?
https://github.com/ankidroid/Anki-Android/blob/be0a768906af0b4a47b8078f78a51e01235d31dc/AnkiDroid/src/main/java/com/ichi2/utils/ImportUtils.java#L122

Nothing really because it's a dialog popping up. I think it's fine, not a big fan of the return null error message to mean things are fine style, but it exists and does work - I remember working in this area before and testing it all out via #5790 

The refactors didn't seem to change it semantically, so that one just continues doing what it's doing

I/we obviously have a laser focus on crashes right now so I'm +1 on more logging for them to make sure we nail things. The volume handled by the crash reporting system before I started the "fix all the crashes" campaign in 2.8 and de-duped the reports was stupendous, so I'm not worried about volume as long as there is signal. Can clamp it down later

Unit tests: I :heart: unit tests but they should be productivity aids (TDD) or guard rails around really hairy code (which is productivity as well, but against regressions sucking up time later). And in the end up to the volunteer IMHO

I agree on correct + speed, but I'm also pretty decisive, if I've read something and it looks good :man_shrugging: - I'm really comfortable with git and the release process now so follow-on fixes aren't hard and haven't been numerous in practice vs the current velocity so I'll keep the bias for speed until that equation tilts another direction. Vámanos!

**Comment by mikehardy** [comment]
so with all that I'll merge if your comfortable, or if you want to harness it in some tests lemmeno

**Comment by david-allison-1** [comment]
Cheers! Also really happy with the velocity, and I don't feel it's a realistic regression that could come up given the additional code that's been produced, I'll don the cowboy hat for this one 🤠.

I plan to move to a more testing/refactoring heavy approach once we're down to a reasonable (0 😉) number of crashes, but that's probably going to take to the end of summer. There's so many little concurrency bugs that probably warrant an incremental modelling/redesign, and that still scares me as it spans the entire project, and needs to stay within the libAnki design constraints.

But... it's possible, and we're getting there!

----

Since it's a bugfix, I'd like to see it in 2.9.6 if possible. Let's get it in

**Comment by mikehardy** [comment]
I learned a little with translation sync on #5875 that spanning branches that have divergent translations while crowdin (translation management site) only has "current" is a bit painful. It's possible and I made it work, but it's also a bit painful. This has new strings, so I'd like to stay this until 2.10 both to avoid and at the same time ice the 2.9 branch to help make it so 2.10 will be quick - hopefully just a matter of a few weeks really. 

My goal for versions > 2.9 is to increase release cadence. The 2.9.x series was a trial for me of that, and it seemed fine so even if it's just a few bug fixes and one feature per minor version I'm okay with that as long as it gets out to users

**Comment by mikehardy** [comment]
2.10alpha60 has this, released just now

**Pull request merged**
