### PR TITLE
fix queryIntentActivities deprecation

### PR DESCRIPTION
**Pull request by RobozinhoD**
## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
part of #12364

## How Has This Been Tested?

I don't know to test it

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
If the unit test passes, I'm happy

**Review by david-allison — CHANGES_REQUESTED** [review]
Tests are failing

**Review by david-allison — APPROVED** [review]
LGTM

**Comment by lukstbit** [comment]
This was stale and about to be closed and I've taken the liberty of fixing the conflicts to not waste the work that was already done.

Note: I had to also fix one test. The deprecated method was from a class written in java but the new method was written in kotlin. This made one test fail because mockito and kotlin classes don't go along very well. So I replaced the failing `any()` call with the actual value used in the code(see `CustomTabsHelper.getPackageNameToUse()`).

I'm leaving this to a second reviewer as I added code to the PR. I reviewed it myself, if there's no action on this, I'll merge it as well in several days.

**Review by david-allison — APPROVED** [review]
LGTM

**Pull request merged**
