### PR TITLE
build: bump compileSdkVersion to 33

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
The goal is to get the compile SDK version to the current version (33 was just released)

## Fixes
- Closes #12169

## Approach
* Based off #12169
* Bump `compileSdkVersion` to 33 + commit
* Build + find errors
* Rebase before the commit and fix the errors
* Repeat until the build is clean

## How Has This Been Tested?

Untested 

## Learning (optional, can help others)
Lots of deprecations, will list in a new comment so I can extract them to an issue

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by david-allison** [comment]
Maintainers: peel this off into either an epic issue (to be split later), or one or more issues for deprecation:

* Activity.onBackPressed
* Intent.getParcelableExtra
* Bundle.getSerializable
* Intent.getSerializable
* Parcel.readSparseArray
* Parcel.readSerializable
* Parcel.readList
* Bundle.getParcelableArrayList
* Bundle.get (array access: `b["key"]``)
* Bundle.getParcelable
* PackageManager.resolveActivity
* PackageManager.getPackageInfo
* PackageManager.queryIntentActivities
* PackageManager.resolveService

**Review by mikehardy — APPROVED** [review]
My vote - Peel for an issue marked as good first issue with a check list of identifiable search strings for ultimate closure

It will be a while before these bite and they'll be great GSoC 1st PRs IMHO

Thanks for taking the baton here, really appreciated

**Comment by mikehardy** [comment]
will unblock #12342

**Comment by BrayanDSO** [comment]
conflicts conflicts conflicts, lovely conflicts

**Review by BrayanDSO — APPROVED** [review]
Besides the conflict, LGTM

**Pull request merged**
