### PR TITLE
lint[tests]: NewApi

### PR DESCRIPTION
**Pull request by Arnold2381**
## Purpose / Description
Solves a part of lint[tests]: NewApi 
Mentioned in #9615

## Fixes
Related #9538

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Yeah, I think it might be a misconfiguration or something, not exactly sure what's going on. Perhaps we're not checking formatting

**Comment by ShridharGoel** [comment]
@mikehardy Just checked locally, lint checks are passing even when the formatting is improper, even for non-test files.

**Comment by mikehardy** [comment]
It's always something... Could you peel that off as a new issue if it is not already one?

**Comment by ShridharGoel** [comment]
@mikehardy Yes, done.

**Comment by Arnold2381** [comment]
David the tests are passing in my local why are they failing here?

**Pull request merged**
