### PR TITLE
refactor: CardViewer sounds

### PR DESCRIPTION
**Pull request by david-allison-1**
Small refactor/perf improvement, untested

Part of a larger plan to combine `TTS` and `Sound`

`getConfigForCurrentCard` hit the database, so this should speed up that aspect

#5793

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Cool - LGTM

**Comment by mikehardy** [comment]
The CI failures were something I've never seen before for JUnit. Emulator tests was typical "process crashed". Restarted both, they did not appear related on first glance

**Comment by david-allison-1** [comment]
> The CI failures were something I've never seen before for JUnit. Emulator tests was typical "process crashed". Restarted both, they did not appear related on first glance

I'm getting to the level of 'need a new PC' again. I'm relying on CI rather than testing locally due to build speed.

Failures are due to test structure. Will fix tomorrow.

**Comment by mikehardy** [comment]
It's a bit schizophrenic but this is why I have a much much larger PC then run typically 4 "work clusters" centered around VMs on it, each with different projects (sometimes same repo but different branches). I switch to another cluster once I *think* everything is golden on one batch of work, and it chews through full test suite prior to PR push, but other than fans whirring I'm still productive. Previous machine I could only really have one thing going at once and I found with the thorough test suites in play on a few of my projects the test wait time was much worse then what I encounter now as "mental context switch time"

I suppose this sort of thing should all be in the cloud with VSCode hitting Azure containers via remote :thinking: instead of having it local but then you're really network dependent which is something I avoid if possible.

**Comment by mikehardy** [comment]
"will fix tomorrow" he says before fixing hahaha. merge at will :-)

**Comment by david-allison-1** [comment]
Lost confidence given the test failures, had a run on my device and it seemed good, let's go!

---

Next changes 

* flesh out SoundPlayer, removing the concerns from the CardViewer, 
* move the question/answer state out of `Sound` and into SoundPlayer
* convert the two classes to use completion listeners & add tests
* Introduce the sound from the Rust, instead of parsing the content

**Pull request merged**
