### PR TITLE
fix: 'mark' should not flip card to question

### LINKED ISSUE #14656: [BUG]: note edits flip cards to 'question' side
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Open the reviewer, tap on "answer". 

* [x] Tap on "mark"
* [ ] Edit Tags (https://github.com/ankidroid/Anki-Android/pull/14875)
* [ ] Edit Note

### Expected behaviour

Answer updated

### Actual behaviour

It shows the question again

### Debug info

```text
Running on df10031dac7bcdbb9640d51bd9b9040de87ed315
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
* #14656

## Fixes
* Partially #14656

## Approach
`AbstractFlashCardViewer::opExecuted` performs `updateCardAndRedraw` unless `handler === this`

`updateCardAndRedraw` flips the card to the question

Since we handle the state change: `onMark` -> `onMarkChanged` we don't need the call to `updateCardAndRedraw`

## How Has This Been Tested?
Added a couple unit tests, tested briefly on device

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by user1823** [comment]
The issue also mentions "or anything that edit the note". I have found that updating the question/answer HTML also reproduces the bug in AnkiDroid. In Desktop, the buggy behavior is not seen after this action too.

**Comment by david-allison** [comment]
* Tags: needs work
* Editing card: needs work

**Comment by david-allison** [comment]
Great catch! I've updated the main issue.

I'm keeping this in for review, as it closes off one of the bugs

Tags + Editing are going to need a little more thought: they can potentially flip a card (if the template is `{{Tags}}` and all tags are removed, so we need to emulate Anki Desktop's behaviour here)

**Comment by david-allison** [comment]
I'd like this merged, this fixes 1/3 of the issue

**Pull request merged**
