### PR TITLE
Rename `m` to noteType

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
And `mm` to noteTypes.

As first part of #17598 as David requested the PR to be split.

### CODE REVIEW

**Review by david-allison — APPROVED** [review]

**Comment by david-allison** [comment]
* This will badly conflict with https://github.com/ankidroid/Anki-Android/pull/17678

**Review by lukstbit — APPROVED** [review]
@david-allison Do you want the linked PR to go first?

**Comment by Arthur-Milchior** [comment]
I'm fine with waiting. This change is quite easy to make with search/replace

**Comment by david-allison** [comment]
> @david-allison Do you want the linked PR to go first?

Na, my linked PR will take longer to review

**Comment by david-allison** [comment]
@Arthur-Milchior This will conflict regardless with your other changes, needs rebase

**Review by mikehardy — APPROVED** [review]
LGTM. I fixed the conflicts (all trivial) and force-pushed. re-queueing

**Pull request merged**
