### PR TITLE
Reorder API creation steps to fix accessing models on first access.

### LINKED ISSUE #5465: Error accessing "models" first time when AnkiDroid not open
###### Reproduction Steps

1. Do not use AnkiDroid for a while, or forcibly kill it
2. Call `com.ichi2.anki.api.AddContentApi.getModelList` via its API from another app. The api version used is `com.ichi2.anki:api:1.1.0alpha5`
3. I get an IllegalArgumentException back, "Must set a non-null context to create the configuration."
4. If I try the same action again, it succeeds

###### Expected Result

The `CardContentProvider` is correctly loaded and responds successfully when `getModelList` is called the first time.

###### Actual Result

I get this exception in logcat. This is on 2.9beta14.

```
2019-10-12 21:47:46.263 1625-1645/? I/ActivityManager: Start proc 29971:com.ichi2.anki/u0a233 for content provider com.ichi2.anki/.provider.CardContentProvider
2019-10-12 21:47:46.286 29971-29971/? E/com.ichi2.anki: Not starting debugger since process cannot load the jdwp agent.
2019-10-12 21:47:46.294 1625-17835/? I/ActivityManager: DSS on for com.ichi2.anki and scale is 1.0
2019-10-12 21:47:46.311 29971-29971/? I/com.ichi2.anki: The ClassLoaderContext is a special shared library.
2019-10-12 21:47:46.311 29971-29971/? W/com.ichi2.anki: Insufficient pre-allocated space to mmap vdex.
2019-10-12 21:47:46.330 29971-30003/? E/DatabaseUtils: Writing exception to parcel
    java.lang.IllegalArgumentException: Must set a non-null context to create the configuration.
        at androidx.sqlite.db.SupportSQLiteOpenHelper$Configuration$Builder.build(SupportSQLiteOpenHelper.java:4)
        at com.ichi2.libanki.DB.<init>(DB.java:6)
        at com.ichi2.libanki.Storage.Collection(Storage.java:5)
        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:6)
        at com.ichi2.anki.provider.CardContentProvider.query(CardContentProvider.java:3)
        at android.content.ContentProvider.query(ContentProvider.java:1078)
        at android.content.ContentProvider.query(ContentProvider.java:1170)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:241)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:102)
        at android.os.Binder.execTransact(Binder.java:739)
```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

### PR DESCRIPTION
**Pull request by adamwolf**
## Purpose / Description
There's an issue on API access on first access, or maybe if Ankidroid wasn't opened for a while.

## Fixes
#5465

## Approach
Adjusts creation steps per Hanping.

## How Has This Been Tested?

It has not been tested.

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code

### CODE REVIEW

**Comment by timrae** [comment]
How does this fix work?

**Comment by adamwolf** [comment]
I will be setting up to reproduce the issue later this week, and I can see
if it I can reproduce the issue with this "fix".

**Comment by sergeant-wizard** [comment]
Thanks, I've been looking into this too since it was causing my app to crash.
I confirmed that before this patch, even the [sample](https://github.com/ankidroid/apisample) was crashing, but with the patch it resolved the problem.

**Comment by mikehardy** [comment]
@sergeant-wizard fantastic feedback, thank you

**Comment by adamwolf** [comment]
@hanpingchinese so this works... any insight as to why it works? :)

**Comment by mikehardy** [comment]
Looks like something racy - getting shared preferences and setting up logging takes time, and until they happen before this patch, the static instance isn't set so you can't statically access the app instance which is how lots of the code is getting access to the context etc

So this works in a sense, but it's possible sInstance is used before it's really initialized, and none of the other statics based on sInstance are checking if it's null or not or have any notion of "am I actually initialized?" or not.

It seems like there might be more to do here but at the same time this also seems like an incremental improvement as none of the stuff I mentioned just now exists as it is, and this does seem to fix an issue.

**Comment by timrae** [comment]
From the docs for `Application.onCreate()`:

> Called when the application is starting, before any activity, service, or receiver objects (excluding content providers) have been created.

**Comment by mikehardy** [comment]
"excluding ContentProviders" - so that's the problem, I suppose the ContentProvider needs to essentially busy/wait on the sInstance return being non-null? But all other cases are easy then

**Comment by timrae** [comment]
Ideally we want to be sure that the Application onCreate() function is finished before using the API.

**Comment by hanpingchinese** [comment]
I think it's dangerous to grab the application instance before `super.onCreate()` has been called. Instead, I believe it's best practice to put it immediately after. Isn't that how is used to be before things like the UsageAnalytics section were added?

**Comment by mikehardy** [comment]
Hmm - I may be misunderstanding, but I think (based on that document snippet) that calling a ContentProvider just creates a simple race. The application is started, and onCreate is either called or in the process of being called at the same time the ContentProvider begins running and may call into the application.

In our case the ContentProvider uses static functions to blindly grab the application instance that may not exist yet because onCreate() is not done yet (or is not far enough along)

So, to me then things like analytics are interesting in that they slow down onCreate on it's way to setting the sInstance variable, but it's possible that this has been happening already just with less frequency on devices that are slow to initialize preferences (and thus slow to set the sInstance variable)

I agree it's dangerous to grab the application instance before *it is initialized* but it is not possible to say we will not try to grab it before onCreate *has been called* per the docs. We are apparently not in control of that.

So in general if onCreate is doing things that the ContentProvider needs the ContentProvider and Application instance need to coordinate that with some sort of signaling so the ContentProvider does not proceed until onCreate() is done (or sufficiently done to signal it's the instance is okay to use.

I think this means polling on the return value of sInstance until it's not null (inefficient but easy) or doing a wait/notify on some lock object (efficient but harder) or similar?

**Comment by hanpingchinese** [comment]
It's strange that by design the contentProvider onCreate is called before the application onCreate which kind of implies the contentProvider does not need whatever application onCreate does. But still it makes sense to set sInstance after Application/super.onCreate() because then, the worst that can happen is an NPE - easy to detect. Setting it before, will lead to potentially more confusing errors because of some indeterministic state. From what I understand, if the sInstance is set as in the older versions (straight after super.onCreate) then we have not received any such NPEs, in which case waiting for the sInstance to be set is unnecessary. Maybe that code can be added once we receive the first NPE?

**Comment by hanpingchinese** [comment]
Also, this is definitely worth reading: https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html

**Comment by timrae** [comment]
Interesting...

> When an Android app process is first started, there is well-defined order of operations:

> Each ContentProvider declared in the manifest is created, in priority order.
The Application class (or custom subclass) is created.
If another component that was invoked via some Intent, that is created.

It seems we were assuming that the ContentProvider *could* (but necessarily) be started before `Application.onCreate()`, but it seems that there is an even stronger guarantee that it *will* be started before it. In that case perhaps we should in fact be doing our initialization procedure in the Content Provider rather than the Application subclass...? It's a pretty weird poorly documented design, typical Google.

**Comment by mikehardy** [comment]
That is much stronger as an order of operations than I was thinking. If that was the case, for coherence of logic it seems like there should be one object doing all the init things and exported an init method very publicly documented to synchronize so anyone calling in to it would init or wait, then return only when init was valid or attempted-but-impossible (inaccessible database or whatever). That would go a long ways towards making the Application class less of a behemoth as well. Moving it into the ContentProvider doesn't seem like the right home

**Comment by timrae** [comment]
Of course I didn't mean putting the code itself in the content provider, but the call to the init function would need to go there.

For readability purpose we could (and probably should) have a singleton that inits the application state and is called in both the application class and the content provider, but the former would basically be a no-op.

**Comment by adamwolf** [comment]
Does anyone else have any bandwidth to take these changes on? They all
sound good, but I don't have the bandwidth right now to handle this.

Thanks!

**Comment by mikehardy** [comment]
I don't personally either. @timrae Perhaps as it is crashing right now the patch could be provisionally merged with a note indicating the plan but without closing the issue, and the sketch of the real solution could be placed on the relevant issue?

I recognize that means it may not get done for some time but leaving a crash bug open when an existing PR with reported success on a simple line move would at least band-aid it doesn't feel right to me

**Comment by timrae** [comment]
Can you change to make the assignment after the call to super() as requested by @hanpingchinese? I'm not sure this will make any difference, but I agree we should put it back to the same as it was in 2.8.

**Comment by adamwolf** [comment]
I made the change, I think.  I have to admit I haven't been following this 100% :)

**Comment by mikehardy** [comment]
I packed up the discussion on what happened, why, and the thinking above on a full solution as #5613

**Pull request merged**
