### PR TITLE
[Kotlin Migration] FixedPreferencesTitleLength Lint Rule

### PR DESCRIPTION
**Pull request by prateek-singh-3212**
Migrated FixedPreferencesTitleLength.java to FixedPreferencesTitleLength.kt

### CODE REVIEW

**Comment by prateek-singh-3212** [comment]
Mentors should I add commit of test of FixedPreferencesTitleLength in this PR or include it in new file

**Review by david-allison — CHANGES_REQUESTED** [review]
I don't believe the first commit compiles - `kotlinMigration.gradle` needs to handle `lint-rules` as it doesn't right now.

**Comment by prateek-singh-3212** [comment]
@david-allison Should I use MAIN source for lint rule?

**Comment by justdvnsh** [comment]
@prateek-singh-3212 Yes. Main source should be used for this.

**Comment by prateek-singh-3212** [comment]
@david-allison sorry for the delay. I will unable to focus on this PR due to my university exams. I will proceed wiyh this after 11th May

**Comment by david-allison** [comment]
No rush!

Probably best to restart this one from scratch - I've added `kotlinMigration-lint.gradle` which should be used

**Pull request closed without merging**
