### PR TITLE
Dependency updates 20220216

### PR DESCRIPTION
**Pull request by mikehardy**
This is not quite a standard dependency update PR - reviewer notes:

- yes, we're adopting an appcompat alpha, $deity help us
- pay close attention to the last commit - there is quite a bit of trouble harmonizing the build compatibility targets, I *think* this way is okay but I'm not sure if the spec of a jvmToolchain in the lint-rules repo will fail people that don't have JDK8 installed? If not then doing the source/target compatibility stuff is better if more verbose

I linked relevant sources online in the commit

This is rebased against main as of just now when I create this PR

### CODE REVIEW

**Comment by mikehardy** [comment]
@lukstbit was involved in some of the source/target compatibility stuff with lint-rules, setting it for kotlin to the 11 target, but for some reason now locally when I test I really had to force it as I committed in the last commit on this PR. Maybe an interaction with gradle 8 + kotlin 1.8+ ?

**Comment by mikehardy** [comment]
CI appears to be just your "normal flakes"

**Review by david-allison — APPROVED** [review]
Looks good, with a request to squash OR squash in the compile fix, so we don't have a breakage in the history

**Comment by mikehardy** [comment]
Oh yes - re: squash merge. I always squash the dependency updates but it wasn't labeled as such. Doing so now...

**Review by lukstbit — APPROVED** [review]
Probably the kotlin version update is at fault, it's related to [jvm target compatibility](https://kotlinlang.org/docs/gradle-configure-project.html#check-for-jvm-target-compatibility-of-related-compile-tasks)(notice the warning below there as well). Once [this bug](https://issuetracker.google.com/issues/260059413) is fixed we should be able to set a jvm toolchain for each module and solve these compatibility issues going forward.

**Comment by mikehardy** [comment]
> Probably the kotlin version update is at fault, it's related to [jvm target compatibility](https://kotlinlang.org/docs/gradle-configure-project.html#check-for-jvm-target-compatibility-of-related-compile-tasks)(notice the warning below there as well). Once [this bug](https://issuetracker.google.com/issues/260059413) is fixed we should be able to set a jvm toolchain for each module and solve these compatibility issues going forward.

That was my understanding based on the documentation + warnings as well, but I'm glad you've also seen it and feel the same now, so there are at least two of us aware of it / the knowledge is distributed better. These aren't the hardest things to shift around a bit in case my "first use in our project" of `jvmToolchain` blows up for people - that one could be replaced by a kotlin + java duo of source/target compatibility blocks.

Okay, merge then and we'll see :-). Thanks all

**Pull request merged**
