### PR TITLE
Fixed Bug : Show Updated Content In EditText(CardTemplateEditor)

### PR DESCRIPTION
**Pull request by Akshay0701**
## Steps to reproduce the bug 
1 open card template editor 
2 edit content Front or back.
3 change to style 
4 again change to front or back

## Expected Output 
Edittext should show updated content 

## Actual Output 
Editext showing pervious version of content

### CODE REVIEW

**Comment by Akshay0701** [comment]
I was responsible for this bug from #8730 PR but now fixed.

**Comment by david-allison-1** [comment]
If you have time, it'd be great to add a test here

**Review by david-allison-1 — APPROVED** [review]
Actually... Looks good to me. Add a new issue if you feel the test is worth it

**Comment by Akshay0701** [comment]
Sure

**Comment by Akshay0701** [comment]
included in #8772

**Pull request closed without merging**
