### PR TITLE
NF: factorize DeckPreferenceHack

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Most complex part of #11418. Factorizing preference hack as much as possible

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
This would work for me, but needs de-conflict

**Comment by Arthur-Milchior** [comment]
@mikehardy done

**Comment by mikehardy** [comment]
The conflicts left were just a change to import statements. I made them locally, re-ran CI tasks locally, they passed, so I pushed and merged. Onwards

**Comment by Arthur-Milchior** [comment]
Happy to add to my list of PR that remove more code than it adds.
One day, I'll finally have an empty repo :P

**Pull request merged**
