### PR TITLE
NF: Fix typo in email text

### PR DESCRIPTION
**Pull request by david-allison-1**
Had this PR done a while back - never submitted. Whoops

Got a reminder on the mailing list

### CODE REVIEW

**Comment by mikehardy** [comment]
Looks like a flake 

```
om.ichi2.libanki.sched.AbstractSchedTest > undoAndRedoPreload[SchedV1] FAILED
    java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
        at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.AssertionError
            at org.junit.Assert.fail(Assert.java:87)
            at org.junit.Assert.assertTrue(Assert.java:42)
            at org.junit.Assert.assertNotNull(Assert.java:713)
            at org.junit.Assert.assertNotNull(Assert.java:723)
            at com.ichi2.libanki.sched.AbstractSchedTest.undoAndRedo(AbstractSchedTest.java:362)
            at com.ichi2.libanki.sched.AbstractSchedTest.undoAndRedoPreload(AbstractSchedTest.java:373)
```

**Review by mikehardy — APPROVED** [review]
LGTM, re-running CI that appeared to flake

**Comment by david-allison-1** [comment]
Probably needs a rebase to the latest master

**Comment by mikehardy** [comment]
Interesting - not sure if this threw a crash report but the emulator tests have started flaking with `process crashed` like on the merge to master here


```

02-01 12:52:28.059  3792  3792 I UsageAnalytics: initialize()
02-01 12:52:28.059  3792  3792 D UsageAnalytics: App tracking id 'tid' = UA-125800786-1
02-01 12:52:28.125  1959  2611 I CheckinCompat: No service .checkin.CheckinService to disable [CONTEXT service_id=130 ]
02-01 12:52:28.126  1959  2611 I CheckinCompat: No service .update.SystemUpdateActivity to disable [CONTEXT service_id=130 ]
02-01 12:52:28.127  1959  2611 I CheckinCompat: No service .update.SystemUpdateService$SecretCodeReceiver to disable [CONTEXT service_id=130 ]
02-01 12:52:28.131  3480  3639 D HostConnection: HostConnection::get() New Host Connection established 0x7d6ad82e58d0, tid 3639
02-01 12:52:28.140  3792  3792 I WebViewFactory: Loading com.google.android.webview version 83.0.4103.106 (code 410410686)
02-01 12:52:28.143  3792  3792 I ichi2.anki:acr: The ClassLoaderContext is a special shared library.
02-01 12:52:28.144  3792  3792 D nativeloader: classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle/lib/x86_64:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/x86_64:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/x86_64:/product/lib64:/system/product/lib64
02-01 12:52:28.153  3792  3792 I ichi2.anki:acr: The ClassLoaderContext is a special shared library.
02-01 12:52:28.154  3792  3792 D nativeloader: classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle/lib/x86_64:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/x86_64:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/x86_64:/product/lib64:/system/product/lib64
02-01 12:52:28.164  3480  3639 D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_async_frame_commands ANDROID_EMU_gles_max_version_3_0 
02-01 12:52:28.167  3480  3639 D EGL_emulation: eglCreateContext: 0x7d6ac83390f0: maj 3 min 0 rcv 3
02-01 12:52:28.169  3480  3639 D EGL_emulation: eglMakeCurrent: 0x7d6ac83390f0: ver 3 0 (tinfo 0x7d6a68342140) (first time)
02-01 12:52:28.201  3792  3792 I cr_LibraryLoader: Loaded native library version number "83.0.4103.106"
02-01 12:52:28.201  3792  3792 I cr_CachingUmaRecorder: Flushed 3 samples from 3 histograms.
02-01 12:52:28.205  3792  3792 I TetheringManager: registerTetheringEventCallback:com.ichi2.anki
02-01 12:52:28.245   509   635 W InputDispatcher: channel '470b000 Toast (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-01 12:52:28.246   509   635 E InputDispatcher: channel '470b000 Toast (server)' ~ Channel is unrecoverably broken and will be disposed!
02-01 12:52:28.253  3792  3792 E cr_VariationsSeedLoader: Failed loading variations seed. Variations disabled.
02-01 12:52:28.260   509  1828 I ActivityManager: Process com.ichi2.anki (pid 2691) has died: fg  FGS 
```

was the related snippet of device logs. As an init process localization it seems to be failing right around when UsageAnalytics and ACRA start up. I've seen this at least twice maybe thrice? Could be ACRA multi-process stuff + rust? I don't have anything else to go on right now, just making putting this on the radar, it appears to be 5% or so flaky, more or less (maybe less, maybe up to 15-20% there aren't enough runs yet)

**Pull request merged**
