### PR TITLE
Always return same value

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
This partially deal with the warning that some methods always return the same value. 

There are two many warnings where I miss the context to know what to do with them. Some methods could probably be replaced by static final constants.  Some other methods seems related to work in progress where a more interesting value may be eventually used.

### CODE REVIEW

**Review by david-allison-1 — CHANGES_REQUESTED** [review]
I've had a look through the first few examples, and I don't feel that this is adding value - the return values are whether an event should be handled, and are the responsibility of the method, not the caller.

**Comment by Arthur-Milchior** [comment]
Then I guess it should be documented. Because in lot of case, it returns values that are never read, with no explanation of why those values are returned.

Does not explains `getFont` which returns null and `getName` which returns the empty string

**Comment by Arthur-Milchior** [comment]
Do you know whether there is a way to tell the linter to deactivate entirely this test, because I guess that removing it everywhere is adding too much noise to the code

**Review by david-allison-1 — APPROVED** [review]

**Comment by david-allison-1** [comment]
Likely some IDE documentation and files in https://github.com/ankidroid/Anki-Android/tree/master/.idea to set a consistent lint style within the project.

Might be worth adding an issue to get around to looking into this.

**Comment by Arthur-Milchior** [comment]
Did you meege by accidenr ? I thought you were against this change @david-allison-1

**Comment by david-allison-1** [comment]
I'm pro 50% of the change, and ambivalent/weak no for the rest, but it's not a hill I want to die on and it's best for me/us to focus on changes that will provide value to devs or users rather than bikeshed. 

It's not an incorrect change, and we'll quickly be able to revert or refactor if a new requirement comes up.

**Pull request merged**
