### PR TITLE
Query with null selection

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Based on top of #12016. Removing a method that is not required anymore thanks to DB migration

### CODE REVIEW

**Comment by Arthur-Milchior** [comment]
I'm fine rebasing. But there was no merge conflict, and the first PRs were merged, so I don't expect that the label "waiting for feedback" was relevant there

**Comment by lukstbit** [comment]
@Arthur-Milchior I added the label to get your attention in case of conflicts or other issues(due to your other PRs) so this PR could be merged as soon as possible.

**Review by lukstbit — APPROVED** [review]

**Comment by Arthur-Milchior** [comment]
I don't think I get information about label. Or I missed it. I only saw it while looking at the list of my open PR in ankidroid.

But I admit I've so much notification it's easy to miss some

**Review by david-allison — APPROVED** [review]

**Comment by mikehardy** [comment]
Just a workflow note: adding labels does not generate a notification, but for someone that regularly has a query for issues based on the labels and uses it as a work queue (as I do) the labels can be helpful. Tagging people *does* generate a notification

**Comment by Arthur-Milchior** [comment]
why do you query for "waiting for feedback"? Unless you're the author, doesn't seem very useful.

I admit that I mostly query GSOC. Usually the priority

**Pull request merged**
