### PR TITLE
Remove `.avi` from supported video extensions, and add `.webm`

### LINKED ISSUE #15772: .Avi files not playing
###### Reproduction Steps

1. Insert .avi  (file used: [sample avi files](https://filesamples.com/formats/avi))
2. Preview Card

###### Expected Result
Load the video

###### Actual Result
image
First field: .avi
Second field: .mp4

###### Debug info
2.18alpha2 Samsung S21

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Additional
This was reported in [Forum](https://forums.ankiweb.net/t/android/41960)

> The card on android has never been able to play avi videos (it won't sync over, I imported the avi video into the "collection.media" folder on android, and it won't play it either).

> Today I inserted an occasional mp4 video on my computer, and suddenly found that it could be synchronized to android and played without any problem. I would like to ask, does android have any special rules for synchronizing audio and video?

> The formats I've encountered are wav, mp3, mp4, avi. I found that mp4, wav can sync itself to the phone, while avi can't, and mp3 seems to be able to sync as well.

###### Context Code
``` @Test
    fun `parseSourcesToFileScheme - object`() {
        val mediaDir = "storage/emulated/0/AnkiDroid/collection.media"
        val result = parseSourcesToFileScheme("<object data=\"ben.avi\"></object>", mediaDir)
        assertEquals("""<object data="file:///$mediaDir/ben.avi"></object>""", result)```


// not in libAnki
object Sound {
    val VIDEO_EXTENSIONS = setOf("mp4", "mov", "mpg", "mpeg", "mkv", "avi")
```

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description
AVI isn't supported by default in Android's WebView (nor in general [Android](https://developer.android.com/media/platform/supported-formats)), while `.webm` is

## Fixes
* Fixes #15772

## Approach
In the commits

## How Has This Been Tested?

Emulator 31
1. Add videos [from this site](https://filesamples.com/categories/video) with `webm` and `avi` files
Result: webm videos are played and nothing happens with avi files

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM and makes sense - we can only do what the platform supports

**Comment by mikehardy** [comment]
The only thing I don't understand is how the reporter indicates that this is a regression from 2.17alpha1 to 2.17alpha2 ? https://discord.com/channels/368267295601983490/701922522836369498/1214713415009042503

If android doesn't support it, how did it work on 2.16.5 as reported ? Very confusing

The code change looks correct assuming the assertion of no avi support is correct but the 2.16.5 "worked" data point needs a set of eyes

**Comment by david-allison** [comment]
I **presume** it worked due to us using an external video player activity:

* Android likely supports `avi`
* Android WebView likely doesn't

**Comment by BrayanDSO** [comment]
> I presume it worked due to us using an external video player activity

I presume the same, although Android docs don't specify AVI support

**Comment by BrayanDSO** [comment]
For the time being and 2.17 releasing process, I believe that this is the best option.

If anyone wants to add `.avi` support back, be welcome and create an issue. 

Simply reverting to the old media player isn't an option right now, since there will be people that will want the web player features back, like being embedded, seeking, play/pause, speeding, etc, and I believe that they are bigger than the people that want `.avi`, which AFAIK is the only Anki video extension not supported right now.

**Comment by mikehardy** [comment]
All reasonable points, thank you

**Pull request merged**
