### PR TITLE
Toolbar elevation

### PR DESCRIPTION
**Pull request by timrae**
see #3890

### CODE REVIEW

**Comment by timrae** [comment]
I didn't really like the way the shadow was cast on the light blue bar in the reviewer, so have changed the counts bar to the default (i.e. white) color. Some feedback on if others like this, and whether or not to include it in 2.5 would be appreciated if anyone is paying attention.

counts-bar

**Comment by hssm** [comment]
Wouldn't it look bad for anything that isn't a white background? The current way kind of "blends" into the action bar somewhat. If you have a non-white background you now have 3 very distinct set of colours for each section.

Anyway we shouldn't be sneaking in non-bugfixes this late into a release candidate.

**Comment by timrae** [comment]
Yeah true, I guess a better solution would be to add an elevation to the top bar, I just can't be f'd right now; will look into it later for 2.5.1

**Comment by adelq** [comment]
I prefer the white counts bar with toolbar elevation, it's more legible and looks more aesthetically pleasing

**Pull request closed without merging**
