### PR TITLE
Refactor: Use androidx Activity APIs in AbstractFlashcardViewer

### PR DESCRIPTION
**Pull request by nicdard**
## Purpose / Description
_Describe the problem or feature and motivation_

## Fixes
Fixes (partially): #8602 

## Approach
Each `startActivityForResult` and corresponding case in `onActivityResult` is refactored to use the new API.
This PR introduce a way to access the callback during testing, avoiding the lambda style for this reason. I have tried to follow the recommended way (https://developer.android.com/training/basics/intents/result#test) by using a custom `ActivityResultRegistry` to address this use case but I did not found a way to either inject it before the field initialisation or to shadow it using `Robolectric Shadows` (tried to implement one for `ActivityResultRegistry` but some tasks are not finished and this is the cause of the failure of some tests). 
In order to be sure that the style looks good before moving to the others, I just refactored the code in `AbstractFlashcardViewer` to give an example of this use for the sake of testing. I will refactor all other activities as soon as this PR will be merged.

## How Has This Been Tested?

Unit testing.
On emulators: API 30 and API 25.

## Learning (optional, can help others)
https://developer.android.com/training/basics/intents/result#test
https://www.programmersought.com/article/3398962077/
http://robolectric.org/javadoc/4.1/org/robolectric/shadow/api/Shadow.html
https://github.com/robolectric/robolectric/tree/master/shadows/framework/src/main/java/org/robolectric/shadows (use them as examples)

## Checklist
- [x] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
There is one issue with this new activity API stfucture so far, and I'm not sure exactly how to reproduce it or how to handle it

it appears when the activity result is handled / returned, the handling fragment/activity is not in the initialized state that we used to expect, so view elements / internal members may not be initialized.

We need to understand this before continuing to alter the codebase to this pattern

Example: #8913  crash --> temporary crash workaround but without really understanding the issue: #8914

**Comment by mikehardy** [comment]
This one needs to be marked draft until my comment above is understood + addressed

**Comment by nicdard** [comment]
> This one needs to be marked draft until my comment above is understood + addressed

Sorry for the absance of the last month! I was relocating and starting my internship so I did not really have time to follow up also because I have still to plan my next recolation in september when I will start my studies for the master

As soon as I have time I'll take a look on this

**Comment by mikehardy** [comment]
No problem! Life of course takes priority, but I don't think we had the bandwidth to really understand it either. I couldn't figure it out quickly when I looked anyway, and then ran out of time completely for nearly a month too. Anyway, plenty of time, it's a long term migration - no rush, and good luck with everything

**Pull request closed without merging**
