### PR TITLE
[Bug Fix] Fixed AlertDialog theme color made darker

### LINKED ISSUE #15241: The background of AlertDialogs in the black theme should be darker
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Use Black theme.
- Long press a deck on the Decks page to open the menu.
- See the background color of the menu (it's too bright)
- Click Custom Study
- See the background color of the menu (it's dark, as expected)

### Expected behaviour

The long-press menu should be dark and should have the same background color as the Custom Study menu.

### Debug info

```text
2.17 alpha 15
```

### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by Subhadiptech**
## Purpose / Description
App uses both MaterialDialog and AlertDialog. In dark mode, the AlertDialog was not black, it was light gray, which is a mismatching the color of the MaterialDialog color.

## Fixes 
* Fixes #15241 

## Approach
Strategy was to add a style and use theme to set the AlertDialogStyle

## How Has This Been Tested?
Testing happened by opening the app and triggering any one dialog which uses AlertDialog, both in dark and light mode, and calibrated with the MaterialDialog to avoid any UI mismatch.

### Before:

Screenshot 2024-01-24 at 10 39 56 PM

### After: 

Screenshot 2024-01-21 at 10 11 40 PM

## Checklist

- [x] Added proper style with DayNight parent.
- [x] Added style in themes
- [x] Testing in Dark Mode.
- [x] Testing in Light Mode.

### CODE REVIEW

**Review by david-allison — APPROVED** [review]
LGTM, thanks!

**Review by mikehardy — APPROVED** [review]
LGTM - thank you!

**Comment by mikehardy** [comment]
needs someone to squash merge when merge queue is empty (currently has entries so I can't) https://github.com/ankidroid/Anki-Android/queue/main

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/labels/squash-merge

**Comment by Subhadiptech** [comment]
In future:

Could you avoid merge commits, and rebase instead
Could you rebase + force push the same PR, rather than creating a new one (we lose the review comment history in new PRs): https://github.com/ankidroid/Anki-Android/pull/15329

@david-allison Noted.

**Pull request merged**
