### PR TITLE
 Material design version of account setup

### PR DESCRIPTION
**Pull request by jshevek**
Register and login pages placed in scrollviews to accomodate landscape
      and small screens.
    Also fixed state transition issues, allowing back/cancel to transition
      rom account setup to login
    
    Not done:
    - Dialogs
    - home/up button in action bar not implemented.

### CODE REVIEW

**Comment by timrae** [comment]
Thanks, looking really good!

Would you be able to squash to a single commit please? 

Whenever possible please try to avoid having commits like "fixed bug in last commit" and "Merge $BRANCHNAME"... instead use `git commit --amend` or `git rebase [-i]` commands and do a `git push -f` if necessary. Sometimes when there are a ton of merge conflicts it's difficult to squash/rebase, but in general please at least attempt it and write in your PR description if you fail.

**Comment by jshevek** [comment]
> Would you be able to squash to a single commit please? 

I did last night, shortly after this request.    I can't work on this today to resolve merge conflicts, so unless someone else does it looks like merge conflicts may accumulate.  Of course, others are also resolving the same conflicts on other branches.  I'm new to git, but it seems like there should be a strategy that minimizes that duplication of effort.

**Comment by timrae** [comment]
You have an extra `>` at the end of the xml which is causing Travis to fail. It seems that you successfully squashed to one commit, but now there are merge conflicts (probably after Houssam's PRs today) so you'll need to rebase again as well sorry. 

> it seems like there should be a strategy that minimizes that duplication of effort

communication and getting the work done quicker are the only ways I can think of...

**Comment by jshevek** [comment]
There were two xmls files with extra ">" earlier, I removed both and made sure the build worked.  Maybe I undid this fix during a merge. 

> It seems that you successfully squashed to one commit,

Twice.  I've done that twice now. Its become a loop.  After each squash, there is a delay during which more merge conflicts are created, creating the need (or perceived need?) for another merge + squash.   

Why are we squashing to such an extreme?   This particular pr is simple and narrow in scope.

**Comment by timrae** [comment]
It sounds like you're getting frustrated... sorry about that! It becomes a lot easier as you get used to using git, but I'll give you some tips inline below:

> After each squash, there is a delay during which more merge conflicts are created, creating the need (or perceived need?) for another merge + squash.

There's no need for an explicit merge; `rebase` does the merging automatically. Let's take the first "merge + squash" as an example:

You did your work, then went to submit it and realized that there were merge conflicts (this is kind of unavoidable in an open source project) so you did `git merge develop` which creates another commit, resolved the conflicts and then pushed to github. You then found that the Travis build failed so added another commit to fix that, leaving 3 commits.

If you knew in advance that we prefer to "rewrite the history" so that our commit history is clean (whenever feasible), then instead of doing `git merge develop` to resolve the conflicts, you would do `git rebase develop`, which would leave you with one mergeable commit. When you found that Travis was failing you could then do `git commit --amend`, again leaving you with one commit. Then when I go to review the PR, it looks good and there's only one commit, therefore I merge and it's done.

> I did [squash the commits] last night, shortly after this request.

Is it possible that you forgot to push? At the time of my first comment there were 3 commits.

> Why are we squashing to such an extreme? This particular pr is simple and narrow in scope.

Maybe I'm missing your point, but it's precisely because this PR is simple and narrow in scope that we expect it to be a single commit. We don't want to "pollute" the history with multiple commits for a simple change. For complicated changes with a lot of merge conflicts it can be advantageous to have an explicit commit which shows the merge, but for relatively small simple changes it should almost always be a single commit.

Anyway, now that you know to do `rebase` instead of `merge` it should be much easier for you.

**Comment by timrae** [comment]
By the way, for quickly resolving merge conflicts you can try using the "search everywhere" function in Android Studio, done by double pressing shift on your keyboard. I normally search for "<<<<"

**Comment by ospalh** [comment]
> (F)or quickly resolving merge conflicts 

... i use `git mergetool` with "meld" as the visual diff program. Takes a little time to set up, GIYF. Once it is running that program merges some of the conflicts plain git has problems with and you can often just resolve the remaining conflicts with a single click selecting your or their version.

**Comment by timrae** [comment]
I've taken care of the rebasing in #814

**Pull request closed without merging**
