### PR TITLE
Theme refactor:   Per Tim's request  - not a real pull request.   

### PR DESCRIPTION
**Pull request by jshevek**
This is not a real pull request, as this code is a partial refactor, which is largely untested. Many of these changes will be reversed or improved upon before being ready for submission. 

I wish to restore theming ability to this app, and introduce an AMOLED friendly, night-viewing friendly theme.   In the course of this I will:

-> remove as much programmatic changes to the UI appearance as is reasonable
-> centralize all reference to images and colors into a few places.  
-> create new icon images directly based on the old icons

I'll also be changing some of night mode specific code.   If I have the time for it, I'll add  some very basic UI testing code. 

I've already merged some code with Allison, who is working on Material Design related upgrades to the app, but this branch still uses the original entirely non-CardView approach.

### CODE REVIEW

**Comment by timrae** [comment]
Thanks for this, please keep pushing your new commits to the same branch so that they show up here, and let us know when you're ready for a first code review

**Comment by timrae** [comment]
@abvanpelt
Please take note of #745 which will should be merged into develop soon after getting 2.4.1 out of the way

**Comment by timrae** [comment]
OK #745 has been merged, and this now has merge conflicts with the develop branch. I think you should probably pull out the commits from @abvanpelt from this PR as they belong in a separate PR. I'd also recommend focusing on the reworking of themes so we can get it merged ASAP and dealing with the UI tests later

**Comment by timrae** [comment]
@jshevek
Do you think you could put together a pull request for just the refactoring, without all the other stuff like dark theme, `RecyclerView`, and preferences changes? It's a pretty significant change so it will be helpful for everyone working on material design if we can get that merged ASAP

**Comment by jshevek** [comment]
You guys are moving faster than me. I don't want to slow other people down. 
 
Who is working on Material Design besides Allison and Eginhard?  Maybe if all UI-working people were discussing their plans/work together in one place, we'd all know better how to interleave our efforts.

I noticed this comment from hssm in another thread:
 
 "I've left that work for someone working on theming since they will likely end up doing it better or changing it completely anyway."

so I can see the benefit of getting some kind of commit in soon, but the problem is that the previous approach to theming (and the UI in general) involved a lot of interdependancy between separate parts of the code, and I'm piecewise changing the whole approach,   so this (partially done) refactoring has necessarily involved breaking things. Its not ready.

I can pull out RecylerView right away, and pull out the other parts when I'm got things minimally working (I use them to check for obvious breakages). I feel I might need to do UI testing before then, though.

Or were you thinking that you or hssm might finish what I've started, wrt refactoring themes.java, themes.xml and affected code? And so I should submit a pr which includes even careless changes which have caused hidden, unfixed bugs in the UI?

**Comment by timrae** [comment]
No, by all means please continue as you see fit... I just want to make sure
this stays focused on refactoring rather than a massive "material design
overhaul" which never materializes into something. The longer it stays in
PR form the more merge conflicts it will generate

That said,  based on the relative silence of the others, it may be safe to
say you're the only one actively working on material design right now. I
think refactoring will reduce the barrier to contribution significantly.

**Comment by abvanpelt** [comment]
@timrae, thanks for pointing out that PR to me. 

I'd pushed some initial work to my cardview-v7 branch [https://github.com/abvanpelt/Anki-Android/tree/cardview-v7] and then discovered that PR. I'll need to redo some of my implementation -- it involved some new data structures that aren't necessary anymore. 

You can at least see the initial RecyclerView and CardView work there.

**Comment by jshevek** [comment]
>> rather than a massive "material design overhaul" which never materializes into something

Oh, that makes sense.  It was true that I was thinking that maybe Allison's idea for a card-based deckpicker could be introduced pre-'material design overhaul'.  Since the current deckpicker already looks card-like, I thought it (and maybe other individual and subtle cardifications) could go as a stand-alone change without an overhaul.  I hadn't fully thought it through, and should have mentioned my thought process in  merging her commit. 

I've already started reverting those merges from my branch.  You are right, the theme refactor is going to be pretty big on its own.

**Comment by timrae** [comment]
@abvanpelt
Great, I think the RecyclerView / CardView deck picker can be treated essentially independently of this theme re-factoring, so would you be able to open up a new preliminary pull request as soon as you've reworked your changes based on #745? It doesn't need to be ready to merge, it's just so that we can see what you're doing and where you're at.

**Comment by timrae** [comment]
Sorry we've been doing a bit of refactoring recently. If it's difficult to merge, copying and pasting the new theme code into the latest development branch might be an option.

**Comment by jshevek** [comment]
Yes, I did not know how fast you guys would be moving with this code. I knew Allison was doing things so I kept track with her  to be sure our code with work with each others, but I didn't anticipate you guys doing so much so fast. 

Also, I didn't realize how far reaching the programmatic approach to theming/UI tweaking was within the app, and how much would need to be changed.

So my new (current, might be changed) plan is to just start a new branch and do this in bite sized pieces. Maybe fix everything that relates to icons (which also addresses the naming issue mention on the other PR).   Then commit that, and after its accepted start on shifting color references to using attr and standard theme values where appropriate.  

Before I tried to rip out all of the programmatic UI tweaking and replace it fully. Now  I'm thinking I would leave most of that code in place until near the end of the process.

It all depends on how much time I have for a span.

**Comment by timrae** [comment]
Yes I think that's a good idea. Small PRs done over a short time (a day or two) or which concentrate on one or two specific files will work much better. 

In addition to the gradual change from code to xml, removing all of the redundant themes (blue, flat, etc) from Themes.java, leaving only the white theme would also be useful. I think it's fine to temporarily break night mode if necessary for this.

Finally, I believe @hssm has some refactoring planned in `AbstractFlashcardViewer.java` and `Reviewer.java`, so you might want to wait for that before undertaking any significant changes to those classes.

**Comment by hssm** [comment]
Besides the simple interface commit that was just merged, I don't plan on doing anything major any time soon, so feel free to modify them as you wish.

**Comment by timrae** [comment]
@jshevek @abvanpelt
I managed to get in touch with @eginhard and have just merged his work into develop. There are several bugs and things that need to be completed, but I think it will make a good base, so I'll close this PR. Let's coordinate on the forum for now, and please make a new draft PR as soon as you have made some commits

**Comment by jshevek** [comment]
That's great timing! It was time for me to start fresh anyway.

**Pull request closed without merging**
