### PR TITLE
Cleanups for libanki package

### PR DESCRIPTION
**Pull request by lukstbit**
## Purpose / Description
More cleanups for the libanki package. Mostly simple changes with the exception of the last commit where I removed a dependency on android `Resources` to further decouple libanki from android.* dependencies.
Easier to review one by one.

## How Has This Been Tested?
Ran the tests.

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by dae — APPROVED** [review]
LGTM.

Re DeckRenameException, the "already exists" case could be removed, as the backend will return successfully if the user attempts to add a deck that already exists. If you wanted to go a step further, you could consider dropping the custom exception entirely, and just relying on BackendDeckIsFilteredException instead. AnkiDroid doesn't need to actually handle this error; it can just print the localized message when the exception is caught by launchCatchingTask.

**Comment by lukstbit** [comment]
Thanks, I created an issue for the changes in DeckRenameException.

**Review by BrayanDSO — APPROVED** [review]
Neat

**Comment by BrayanDSO** [comment]
`Needs Author Reply` to fix conflicts. Merge at will when fixed

**Pull request merged**
