### PR TITLE
Rename browser labels to Card type, Note type

### PR DESCRIPTION
**Pull request by snowtimeglass**
## Purpose / Description
Tweak Card browser column labels as on the desktop version by https://github.com/ankitects/anki/pull/2751/ 

* Card -> Card type 
* Note -> Note type

**Anki Desktop Version ⁨23.10.1**
image

Incidentally, tweak the other labels by using sentence case 
* Card Modified -> Card modified 
* Note Modified -> Note modified

## Fixes
N/A

## How Has This Been Tested?
Checked on a physical device (Android 11)
| before | after |
|---|---|
|image|image|
image|image
image|image
image|image
image|image

## Checklist

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [x] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Comment by mikehardy** [comment]
Hmm - two thoughts:

1- I don't *think* (could be wrong...) this will cause any re-translation of the strings in the array, as the key/name of the array did not change. Normally if you change an English string and you want it re-translated you have to make it like a remove/add by changing the key name

2- If I am correct with 1 above, then we will trigger a need for translators to re-translate all of the strings but....we can access the backend translations now. Why not just use the backend translations directly for this now instead of trying to match them here and having translators do the work on Desktop and AnkiDroid ? 

We appear to have a slight mis-match on what Desktop allows for the column (they have 19 options if I count correctly?) and we only have 11 so I'm not sure how to handle this exactly, but it is a thought anyway - would be great to harmonize and re-use translations rather than have to do a remove/add of the whole array here

**Comment by david-allison** [comment]
I'm going to be in the area soon (CardBrowser rewrite), with apologies; I'm a light 'not now' because it adds additional overhead for strings which won't exist in the new system

We have a few columns which don't map 1:1 with the Anki Backend. 

In addition to this, we shouldn't be using `string-array` with constant strings as it causes problems with the addition/reordering new items and CrowdIn

Instead, it should be in this format:

https://github.com/ankidroid/Anki-Android/blob/603bd59a20c15037d0eea1297e22178dce6b76a0/AnkiDroid/src/main/res/values/constants.xml#L217-L221

**Comment by snowtimeglass** [comment]
Thank you for all the guidance. I guess it will be better to wait the CardBrowser reconstruction. Of course, feel free to close this pull request, depending on the work.


In Desktop, the column options appear to include the "Sort Field" and FSRS indicators (e.g. "Retrievability").

Regarding re-use of backend strings and translations, I'm concerned about the inconsistency style between "Title Case" on Desktop and "Sentence case" on AnkiDroid, as previously talked around the following comments:

>"Undo Add Note" and the like use "Title Case" for two reasons: it's what seems to be the standard in menubars, and we had a bunch of already translated actions in that case. I'm not really sure it's worth making translators translate all these actions twice. If there are inconsistency issues, couldn't you just dynamically convert particular strings to "Sentence case", perhaps for a whitelisted set of languages?

_Originally posted by @dae in https://github.com/ankidroid/Anki-Android/issues/12961#issuecomment-1368514930_
            

> Title Case menu bars might have been standard on Windows, but it seems that this trope might be disappearing, as some modern Windows applications such as Edge, or Photos, or Clock, seem to prefer Sentence casing. Others don't, however, such as Calculator. (Reusing old strings?) It's definitely not standard on Android, though, and I don't know about Apple.
> 
> I would personally love Anki to switch to Sentence casing, because:
> 
> * It would be more consistent with Anki itself; other languages such as Spanish, French or Russian do no use Title Casing within Anki
> * Easily reuse strings in Android
> * I see no point in Title Casing in the first place
>
> (...)
> >couldn't you just dynamically convert particular strings to "Sentence case", perhaps for a whitelisted set of languages
>
>That would work for English, I guess, but not for other languages I know. A lot of languages use tenses/conjugations/whatever, so this is going to work well for a very few select cases. Can we even come up with a list with such languages? How sure can we be that this would work for those languages? Sounds dangerous to me

_Originally posted by @oakkitten in https://github.com/ankidroid/Anki-Android/issues/12961#issuecomment-1368525072_

>  About title casing, I don't see the point either.

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/issues/12961#issuecomment-1368568748_

> There seems to be no consensus yet on conforming capitalization to Anki Desktop ("Title Case" style), so I've rewrited the string, "Undo Stroke" to "Undo stroke" ("Sentence case" style) :-)

_Originally posted by @snowtimeglass in https://github.com/ankidroid/Anki-Android/issues/12961#issuecomment-1399453129_

**Comment by dae** [comment]
If AD switches to the desktop browser searching/sorting code, it will mean dropping any AnkiDroid-specific sort orders in favour of the desktop options, so the casing should at least be consistent.

**Comment by mikehardy** [comment]
I'm unconcerned about title case vs sentence case from an AnkiDroid perspective. Consolidating translations in one spot is an enormous when vs capitalization, and capitalization can then be "fixed" in one spot

**Pull request closed without merging**
