### PR TITLE
Update deck list rendering

### PR DESCRIPTION
**Pull request by hssm**
Moved all the decklist building code into the DeckAdapter along with
some refactoring to simplify the process.

Fixes include:
- Hide the default deck when necessary [Issue 1550](https://code.google.com/p/ankidroid/issues/detail?id=1550)
- Colour filtered decks
- Highlight the current deck [Issue 2686](https://code.google.com/p/ankidroid/issues/detail?id=2686)
- Correctly focus on the current deck on startup or when it changes

--
Hopefully the colours I chose are suitable.

It turns out that setting a background colour on a view removes the click animation. Hooray. There's [a workaround](http://stackoverflow.com/questions/26686250/material-effect-on-button-with-background-color) for that, I think, but haven't tried.

I'm also really bothered by the space/colour of the dividers on the highlighted row. They don't blend well with the white theme:
dividers
I fiddled a bit with the `DividerItemDecoration` but didn't really accomplish anything. Could use some tips if anybody knows, I'd like to make it look better.

### CODE REVIEW

**Comment by timrae** [comment]
Hmm yeah the ripple animation is a pretty key part of material design, could you make some drawables? We already do this with the answer buttons in the Reviewer (though they don't have ripples defined yet in the v21 directory)

**Comment by timrae** [comment]
I don't have any idea about that space at the bottom between the selected deck and the divider. Maybe disabling the divider altogether on the selected deck would look better? I have no idea

**Comment by hssm** [comment]
The divider issue is fixed. I replaced the custom class with a simpler one from SO and made some drawables to go with it, so that's looking good now.

I give up on the ripple animation. I've been trying an endless combination of things over the last few days and I can't come up with something that looks and behaves correctly and I don't feel like spending any more time on it.

**Comment by timrae** [comment]
OK I might have a play at some point if I have some free time.
If possible could you give a short summary of what you tried and why it didn't work to avoid wasting too much time on it?

**Comment by timrae** [comment]
This is looking nice! After actually trying it out live I realize the ripple is not that important for the design, as it's obvious which deck we tapped on due to the color changing to grey.

Are you still planning on switching the arrows for icons?

**Comment by ospalh** [comment]
Well it does look nice. :smile: 
But I think [this](https://code.google.com/p/ankidroid/issues/detail?id=2696) crash happens because of this PR. :cry:

**Comment by hssm** [comment]
@ospalh Thanks for the reproduction steps. I came across it earlier but wasn't sure what caused it. I have a fix for it locally now.

@timrae Yes the arrow icon was next on my list.

As for the ripple, here's [a branch](https://github.com/hssm/Anki-Android/tree/decklist-ripple) with some remains of an attempt I did. I found that either:
1 - Setting a background
2 - Calling `notifyDataSetChanged()`
3 - Having `onClickListener`s attached

...all had an impact on whether the ripple was drawn. I tried creating ripple drawables in the drawbale-v21 directory and setting those as the background in the DeckAdapter. They worked insofar as applying the drawable (the background colour would change), but the ripple wouldn't work until I removed the `notifyDataSetChanged()` call from the click listener. Except now it ripples the whole deck list instead of the element clicked. And long-tapping shows the ripple on the wrong element for some strange reason. Sometimes the ripple would get stuck half-way through the animation, so you have a strangely coloured half-rippled decklist.

I tried updating specific rows with `notifyItemChanged()` instead of the whole thing with `notifyDataSetChanged()` which didn't really help. I also tried the notify calls inside `runOnUiThread()` which did nothing.

The closest thing to working is not setting a background at all except for the current deck (so you get no ripple if you tap the current deck again), except the views get recycled (imagine that) and any item in the deck list can randomly get the selected background colour as you tap or scroll. This is why I'm setting a background colour in the first place.

**Pull request merged**
