### PR TITLE
Remove lookup dictionary

### LINKED ISSUE #3896: Remove mostly unused / brittle "Lookup dictionary" feature
It is appropriate that the following texts ("None" and "Eijiro") should be translated.
image

### PR DESCRIPTION
**Pull request by BrayanDSO**
## Purpose / Description
Remove mostly unused "Lookup dictionary"

## Fixes
Fixes #3896 

## Approach
- Remove analytics constants about it
- Remove now unused functions and  `customDictionary` table at metaDb
- Remove strings and icon only used by it
- Remove it and its command from gestures
- Clear unused functions and variables

## How Has This Been Tested?

Tested on emulator (API30) and on my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS)

### Procedure:
Check if preference was deleted:
1. Open Settings
2. Go to Advanced
3. Check if  `Lookup dictionary` doesn't appear

Check if gesture action was deleted:
1. Open Settings
2. Go to Gestures
3. Enable gestures
4. Select any gesture
5. Check if `Lookup expression`  doesn't appear

Check if app bar option was deleted:
1. Open settings
2. Go to Reviewing -> App bar buttons
3. Check if `Lookup text` doesn't appear

Check if functionality persists:
1. Open a note
2. Long tap a word and copy it (nothing special should happen)

## Checklist
_Please, go through these checks before submitting the PR._

- [X] You have not changed whitespace unnecessarily (it makes diffs hard to read)
- [X] You have a descriptive commit message with a short title (first line, max 50 chars).
- [X] Your code follows the style of the project (e.g. never omit braces in `if` statements) 
- [X] You have commented your code, particularly in hard-to-understand areas
- [X] You have performed a self-review of your own code
- [X] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### Screenshoots just to confirm the options don't appear
Screenshot_20220213_132429
Screenshot_20220213_133104
Screenshot_20220213_133149

### CODE REVIEW

**Comment by BrayanDSO** [comment]
Fixed lint (just noticed I can run it locally, sorry) and most unit test build errors. 

The only remaining one is the one on `gesture_set_no_conflicts()` on `UpgradeVolumeButtonsToBindingsTest.kt`. It's a expected error because it used `lookup dictionary` command.

**Comment by david-allison** [comment]
Note for maintainers: currently requires a squash merge as some intermediate commits don't compile

**Comment by BrayanDSO** [comment]
I believe everything is fixed. Just waiting for review

**Comment by david-allison** [comment]
Kicking off CI, will review after

**Comment by BrayanDSO** [comment]
Reminder: if this gets accepted, [market description](https://github.com/ankidroid/Anki-Android/blob/master/docs/marketing/localized_description/marketdescription.txt) should be updated to remove "dictionary integration" from it 

I haven't changed it because I thought only the manteiners should edit it

**Review by david-allison — APPROVED** [review]
@mikehardy I'm happy with this, but I feel we should change `marketdescription` here as well. Does that work for you?

**Comment by mikehardy** [comment]
Changing market description would be great - just to note that it is currently copy-pasted I think, by me (or anyone else with google store rights) since publishing the description is not automated I don't think ? But I'll have to check. Either way at least having it updated here is a good thing yes

**Comment by mikehardy** [comment]
@BrayanDSO could you update this to change the market-description as well? Then we can merge

**Comment by mikehardy** [comment]
> Should I edit only english market description or all of them?

A good question - I'm not sure if this is one of the things we localize? Or if it is, I think this is one of the ones where it just one massive blob of text, so if we change the key name (to force re-translation) it is kind of expensive for all translators.

Are you on crowdin.com? You might look there to see how many of the market descriptions have actually been translated, or perhaps it's possible to grep through the values-nn folders and see?

My goal is to have the market description actually updated, while not forcing re-translation if possible, but also without putting too much work on the translators or on you as the PR submitter - these goals may all be mutually incompatible

**Comment by BrayanDSO** [comment]
Market descriptions is on `docs\marketing\localized_description`.

Its always the 7th item below `★ Additional features:`, so it's easy to mass replace it on all files. I can do it and double-check it in only some minutes

**Comment by david-allison** [comment]
I believe we update each of the files here

**Comment by BrayanDSO** [comment]
I removed them all, just in case. To check it, try to find the line with `(ColorDict, GoldenDict, Leo.org... etc)`

For the only three languages with non-latin letters, I used google translator on the 7th line below `★ Additional features:` to confirm they are about lookup dictionary:
`markdetdescription-te: నిఘంటువు సమన్వయ (కలర్ డిక్ట్, గోల్డెన్ డిక్ట్, లియో.ఆర్గ్, ఎడీక్ట్, విభిన్న వెబ్ డిక్షనరీలు)`
`markdetdescription-mr: शब्दकोष एकत्रीकरण (कलरडिक्ट, गोल्डनडिक्ट, लिओ.ऑर्ग, अ‍ॅडिक्ट, विविध वेब शब्दकोष)`
`markdetdescription-fa: یکپارچگی واژه نامه (کلر دیک،گلدن دیک،لئوارگ،آا دیک،واژه نامه های گوناگون وب)`

**Review by mikehardy — APPROVED** [review]
The last commit looks great - thank you! The emulator CI run had an unrelated failure so I restarted it, but marking it pending merge now and as soon as CI goes green (it should go green...) this is ready to go I think

**Comment by mikehardy** [comment]
maintainer note: squash merge

**Comment by LGFox** [comment]
Can someone share why this feature was removed, please? It was a very convenient feature that saved me a lot of time going back and forth between AnkiDroid and my favorite dictionary.

**Comment by redstoneleo** [comment]
just wonder why Remove lookup dictionary？

**Comment by david-allison** [comment]
* https://github.com/ankidroid/Anki-Android/issues/3896#issuecomment-945187482

**Pull request merged**
