### PR TITLE
Fetching correct DeckID at EditNote

### LINKED ISSUE #17604: [BUG]: Note editor shows Default deck for all cards
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Open any note in the note editor.

### Expected behaviour

The note editor should show the deck in which the card is located. Instead, it shows the "Default" deck.

### Debug info

```text
2.21 alpha 2
```

### (Optional) Anything else you want to share?

Might be related to https://github.com/ankidroid/Anki-Android/issues/17603

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

### PR DESCRIPTION
**Pull request by soCallmeAdityaKumar**
## Purpose / Description
Note editor shows Default deck for all cards 

## Fixes
* Fixes #17604

## How Has This Been Tested?

https://github.com/user-attachments/assets/2d106940-d8d1-45fb-b47c-9caf05cc8e8a

## Checklist
_Please, go through these checks before submitting the PR._

- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [ ] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by david-allison — CHANGES_REQUESTED** [review]
This isn't close to the correct solution. 

The code change causing the problem was already identified on this issue.

**Comment by soCallmeAdityaKumar** [comment]
> This isn't close to the correct solution.
> 
> The code change causing the problem was [already identified on the issue](https://github.com/ankidroid/Anki-Android/issues/17604#issuecomment-2543813431).

This is working on my side, orginalDeckID is always 0 , giving value of deckId to did if oDid is 0.

**Review by david-allison — CHANGES_REQUESTED** [review]
I'm disappointed here. 

I diagnosed the issue and I posted the hunk/diff of the change which caused the issue. All that was required was to revert that hunk

It's now been two rounds review for what should be an easy 'LGTM':

* The change is still wrong
* `this@Card.toBackendCard().deckId` should be `this@Card.did`

Start again from my [issue comment](https://github.com/ankidroid/Anki-Android/issues/17604#issuecomment-2543813431).

If you feel there's still an issue, explain it, or write a test for it.

**Comment by david-allison** [comment]
No reply to my comment, which wasn't addressed

You've been here for almost two years and should know better. Enough is enough here.

**Pull request closed without merging**
