### PR TITLE
fix: remove pref_summary_percentage

### PR DESCRIPTION
**Pull request by david-allison**
## Purpose / Description
The advice was incorrect (we should use `%%`, not `\%%`), and the string was duplicated

We had a problem with the Turkish string `\%%%s`

`%%%s` worked

But:
`%%%s` is detected as having 1 format string
`\%%%s` is detected as having 0

and this broke lint

## Fixes
* Fixes #15727
* Unblocks #15726

## Approach
Remove the bad string, encourage our translator to fix `percentage`

## How Has This Been Tested?

`%s%%`
Screenshot 2024-03-01 at 09 58 32

`%%%s`
Screenshot 2024-03-01 at 10 00 13

and lint passes

```
➜  Anki-Android git:(remove-percentage-summary) ✗ ./gradlew lint
warn: removing resource com.ichi2.anki.debug:string/pref_summary_percentage without required default value.

warn: removing resource com.ichi2.anki.debug:string/pref_summary_percentage without required default value.

warn: removing resource com.ichi2.anki.debug:string/pref_summary_percentage without required default value.

warn: removing resource com.ichi2.anki.debug:string/pref_summary_percentage without required default value.


> Task :AnkiDroid:compileAmazonDebugJavaWithJavac
Note: /Users/davidallison/StudioProjects/Anki-Android/AnkiDroid/build/generated/aidl_source_output_dir/amazonDebug/out/android/content/pm/IPackageStatsObserver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

BUILD SUCCESSFUL in 1m 7s
101 actionable tasks: 21 executed, 5 from cache, 75 up-to-date
```

## Checklist
- [x] You have a descriptive commit message with a short title (first line, max 50 chars).
- [x] You have commented your code, particularly in hard-to-understand areas
- [x] You have performed a self-review of your own code
- [ ] UI changes: include screenshots of all affected screens (in particular showing any new or changed strings)
- [ ] UI Changes: You have tested your change using the [Google Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)

### CODE REVIEW

**Review by BrayanDSO — APPROVED** [review]

**Comment by david-allison** [comment]
On this one: merge before https://github.com/ankidroid/Anki-Android/labels/Strings, as strings are broken

**Comment by david-allison** [comment]
I'm YOLOing this in - I'm low on time

Brayan introduced this and was the review I was concerned about (if there was context I was missing)

And this blocks a release

**Comment by BrayanDSO** [comment]
> Brayan introduced this and was the review I was concerned about (if there was context I was missing)

tbh, I don't remember the context as well. If it works, I'm happy

**Comment by david-allison** [comment]
Needs a cherry-pick to keep strings in sync

**Review by mikehardy — COMMENTED** [review]
😆 that's one way to get rid of the problem with the string, purge string

**Pull request merged**
